/** 자동 생성 — data/nrm-music-quotes.xlsx|.csv 수정 후 npm run generate:music-quotes */

export type NrmMusicQuoteEntry = {
  nameKo: string;
  nameEn: string;
  years: string;
  quoteEn: string;
  quoteKo: string;
};

export const NRM_MUSIC_QUOTES: readonly NrmMusicQuoteEntry[] = [
  { nameKo: '루트비히 판 베토벤', nameEn: 'Ludwig van Beethoven', years: '1770–1827', quoteEn: 'Music is a higher revelation than all wisdom and philosophy.', quoteKo: '음악은 모든 지혜와 철학보다 더 높은 계시이다.' },
  { nameKo: '루트비히 판 베토벤', nameEn: 'Ludwig van Beethoven', years: '1770–1827', quoteEn: 'To play a wrong note is insignificant; to play without passion is inexcusable.', quoteKo: '틀린 음을 치는 것은 대수롭지 않다. 열정 없이 연주하는 것은 용서할 수 없다.' },
  { nameKo: '루트비히 판 베토벤', nameEn: 'Ludwig van Beethoven', years: '1770–1827', quoteEn: 'Music is the mediator between the spiritual and the sensual life.', quoteKo: '음악은 영적인 삶과 감각적인 삶 사이의 중재자이다.' },
  { nameKo: '루트비히 판 베토벤', nameEn: 'Ludwig van Beethoven', years: '1770–1827', quoteEn: 'Don\'t only practice your art, but force your way into its secrets.', quoteKo: '예술을 연습하는 것에 그치지 말고, 그 비밀 속으로 파고들어라.' },
  { nameKo: '루트비히 판 베토벤', nameEn: 'Ludwig van Beethoven', years: '1770–1827', quoteEn: 'Music should strike fire from the heart of man, and bring tears from the eyes of woman.', quoteKo: '음악은 남자의 마음에서 불을 일으키고, 여자의 눈에서 눈물을 흘리게 해야 한다.' },
  { nameKo: '볼프강 아마데우스 모차르트', nameEn: 'Wolfgang Amadeus Mozart', years: '1756–1791', quoteEn: 'The music is not in the notes, but in the silence between.', quoteKo: '음악은 음표 안에 있는 것이 아니라, 그 사이의 침묵 안에 있다.' },
  { nameKo: '볼프강 아마데우스 모차르트', nameEn: 'Wolfgang Amadeus Mozart', years: '1756–1791', quoteEn: 'Neither a lofty degree of intelligence nor imagination nor both together go to the making of genius. Love, love, love, that is the soul of genius.', quoteKo: '높은 지성도, 상상력도, 둘의 조합도 천재를 만들지 않는다. 사랑, 사랑, 사랑, 그것이 천재의 영혼이다.' },
  { nameKo: '볼프강 아마데우스 모차르트', nameEn: 'Wolfgang Amadeus Mozart', years: '1756–1791', quoteEn: 'I pay no attention whatever to anybody\'s praise or blame. I simply follow my own feelings.', quoteKo: '나는 누구의 칭찬이나 비난에도 전혀 신경 쓰지 않는다. 나는 단지 내 감정을 따를 뿐이다.' },
  { nameKo: '볼프강 아마데우스 모차르트', nameEn: 'Wolfgang Amadeus Mozart', years: '1756–1791', quoteEn: 'When I am traveling in a carriage, or walking after a good meal, or during the night when I cannot sleep; it is on such occasions that ideas flow best and most abundantly.', quoteKo: '마차를 타고 여행할 때, 좋은 식사 후 산책할 때, 잠들지 못하는 밤에, 바로 그런 순간에 아이디어가 가장 잘 흐른다.' },
  { nameKo: '요한 제바스티안 바흐', nameEn: 'Johann Sebastian Bach', years: '1685–1750', quoteEn: 'The aim and final end of all music should be none other than the glory of God and the refreshment of the soul.', quoteKo: '모든 음악의 목적과 최종 목표는 오직 신의 영광과 영혼의 회복이어야 한다.' },
  { nameKo: '요한 제바스티안 바흐', nameEn: 'Johann Sebastian Bach', years: '1685–1750', quoteEn: 'I was obliged to be industrious. Whoever is equally industrious will succeed equally well.', quoteKo: '나는 부지런해야만 했다. 똑같이 부지런한 사람은 똑같이 성공할 것이다.' },
  { nameKo: '요한 제바스티안 바흐', nameEn: 'Johann Sebastian Bach', years: '1685–1750', quoteEn: 'It\'s easy to play any musical instrument: all you have to do is touch the right key at the right time and the instrument will play itself.', quoteKo: '악기 연주는 쉽다. 적절한 시간에 적절한 건반을 누르기만 하면 악기가 알아서 연주한다.' },
  { nameKo: '프레데리크 쇼팽', nameEn: 'Frédéric Chopin', years: '1810–1849', quoteEn: 'Simplicity is the final achievement. After one has played a vast quantity of notes and more notes, it is simplicity that emerges as the crowning reward of art.', quoteKo: '단순함은 최종적인 성취이다. 수많은 음표들을 연주한 후에, 예술의 최고 보상으로 단순함이 나타난다.' },
  { nameKo: '프레데리크 쇼팽', nameEn: 'Frédéric Chopin', years: '1810–1849', quoteEn: 'Bach is like an astronomer who, with the help of ciphers, finds the most wonderful stars.', quoteKo: '바흐는 암호의 도움으로 가장 경이로운 별들을 찾아내는 천문학자와 같다.' },
  { nameKo: '프레데리크 쇼팽', nameEn: 'Frédéric Chopin', years: '1810–1849', quoteEn: 'I wish I could throw off the thoughts which poison my happiness, but I take a kind of pleasure in indulging them.', quoteKo: '행복을 독살하는 생각들을 떨쳐내고 싶지만, 나는 그것에 탐닉하는 것에서 일종의 즐거움을 느낀다.' },
  { nameKo: '표트르 일리치 차이콥스키', nameEn: 'Pyotr Ilyich Tchaikovsky', years: '1840–1893', quoteEn: 'Inspiration is a guest that does not willingly visit the lazy.', quoteKo: '영감은 게으른 자를 기꺼이 찾아오지 않는 손님이다.' },
  { nameKo: '표트르 일리치 차이콥스키', nameEn: 'Pyotr Ilyich Tchaikovsky', years: '1840–1893', quoteEn: 'Where the heart does not enter, there can be no music.', quoteKo: '마음이 들어가지 않는 곳에는 음악이 있을 수 없다.' },
  { nameKo: '표트르 일리치 차이콥스키', nameEn: 'Pyotr Ilyich Tchaikovsky', years: '1840–1893', quoteEn: 'I sit down to the piano regularly at nine o\'clock in the morning and Mesdames les Muses have learned to be on time for that rendezvous.', quoteKo: '나는 매일 아침 9시에 피아노 앞에 앉는다. 뮤즈 여신들도 그 약속 시간에 맞춰 오는 법을 배웠다.' },
  { nameKo: '클로드 드뷔시', nameEn: 'Claude Debussy', years: '1862–1918', quoteEn: 'Music is the silence between the notes.', quoteKo: '음악은 음표 사이의 침묵이다.' },
  { nameKo: '클로드 드뷔시', nameEn: 'Claude Debussy', years: '1862–1918', quoteEn: 'Works of art make rules; rules do not make works of art.', quoteKo: '예술 작품이 규칙을 만든다. 규칙이 예술 작품을 만드는 것이 아니다.' },
  { nameKo: '클로드 드뷔시', nameEn: 'Claude Debussy', years: '1862–1918', quoteEn: 'Music is the arithmetic of sounds as optics is the geometry of light.', quoteKo: '음악은 소리의 산술이고, 광학은 빛의 기하학이다.' },
  { nameKo: '클로드 드뷔시', nameEn: 'Claude Debussy', years: '1862–1918', quoteEn: 'People come to music to seek oblivion.', quoteKo: '사람들은 망각을 찾아 음악으로 온다.' },
  { nameKo: '프란츠 리스트', nameEn: 'Franz Liszt', years: '1811–1886', quoteEn: 'Music embodies feeling without forcing it to contend and combine with thought.', quoteKo: '음악은 감정을 생각과 싸우거나 결합하도록 강요하지 않고 구현한다.' },
  { nameKo: '프란츠 리스트', nameEn: 'Franz Liszt', years: '1811–1886', quoteEn: 'Beware of missing chances; otherwise it may be altogether too late someday.', quoteKo: '기회를 놓치지 않도록 조심하라. 그렇지 않으면 언젠가 완전히 너무 늦을 수 있다.' },
  { nameKo: '프란츠 리스트', nameEn: 'Franz Liszt', years: '1811–1886', quoteEn: 'Life is only a long and bitter suicide, and faith alone can transform this suicide into a sacrifice.', quoteKo: '삶은 길고 쓰라린 자살일 뿐이며, 오직 믿음만이 이 자살을 희생으로 변화시킬 수 있다.' },
  { nameKo: '요하네스 브람스', nameEn: 'Johannes Brahms', years: '1833–1897', quoteEn: 'Without craftsmanship, inspiration is a mere reed shaken in the wind.', quoteKo: '장인정신이 없으면, 영감은 바람에 흔들리는 갈대에 불과하다.' },
  { nameKo: '요하네스 브람스', nameEn: 'Johannes Brahms', years: '1833–1897', quoteEn: 'It is not hard to compose, but it is wonderfully hard to let the superfluous notes fall under the table.', quoteKo: '작곡하는 것은 어렵지 않다. 불필요한 음표를 테이블 아래로 떨어뜨리는 것이 놀랍도록 어렵다.' },
  { nameKo: '안토닌 드보르자크', nameEn: 'Antonín Dvořák', years: '1841–1904', quoteEn: 'I have composed too much.', quoteKo: '나는 너무 많이 작곡했다.' },
  { nameKo: '안토닌 드보르자크', nameEn: 'Antonín Dvořák', years: '1841–1904', quoteEn: 'In the Negro melodies of America I discover all that is needed for a great and noble school of music.', quoteKo: '미국의 흑인 선율에서 나는 위대하고 고귀한 음악 학파에 필요한 모든 것을 발견한다.' },
  { nameKo: '리하르트 바그너', nameEn: 'Richard Wagner', years: '1813–1883', quoteEn: 'I write music with an exclamation point!', quoteKo: '나는 느낌표로 음악을 쓴다!' },
  { nameKo: '리하르트 바그너', nameEn: 'Richard Wagner', years: '1813–1883', quoteEn: 'Imagination creates reality.', quoteKo: '상상력이 현실을 창조한다.' },
  { nameKo: '리하르트 바그너', nameEn: 'Richard Wagner', years: '1813–1883', quoteEn: 'Joy is not in things; it is in us.', quoteKo: '기쁨은 사물 안에 있지 않다. 그것은 우리 안에 있다.' },
  { nameKo: '구스타프 말러', nameEn: 'Gustav Mahler', years: '1860–1911', quoteEn: 'A symphony must be like the world. It must contain everything.', quoteKo: '교향곡은 세상과 같아야 한다. 모든 것을 담아야 한다.' },
  { nameKo: '구스타프 말러', nameEn: 'Gustav Mahler', years: '1860–1911', quoteEn: 'If a composer could say what he had to say in words, he would not bother trying to say it in music.', quoteKo: '작곡가가 말로 할 말을 할 수 있다면, 음악으로 말하려 애쓰지 않을 것이다.' },
  { nameKo: '구스타프 말러', nameEn: 'Gustav Mahler', years: '1860–1911', quoteEn: 'Don\'t bother looking at the view—I have already composed it.', quoteKo: '경치를 보느라 시간 낭비하지 마라—나는 이미 그것을 작곡했다.' },
  { nameKo: '세르게이 라흐마니노프', nameEn: 'Sergei Rachmaninoff', years: '1873–1943', quoteEn: 'Music is enough for a lifetime, but a lifetime is not enough for music.', quoteKo: '음악은 평생을 위해 충분하지만, 평생은 음악을 위해 충분하지 않다.' },
  { nameKo: '세르게이 라흐마니노프', nameEn: 'Sergei Rachmaninoff', years: '1873–1943', quoteEn: 'I feel like a ghost wandering in a world grown alien.', quoteKo: '나는 낯설어진 세상을 떠도는 유령 같은 기분이다.' },
  { nameKo: '이고르 스트라빈스키', nameEn: 'Igor Stravinsky', years: '1882–1971', quoteEn: 'Lesser artists borrow, great artists steal.', quoteKo: '작은 예술가는 빌리고, 위대한 예술가는 훔친다.' },
  { nameKo: '이고르 스트라빈스키', nameEn: 'Igor Stravinsky', years: '1882–1971', quoteEn: 'Music is, by its very nature, essentially powerless to express anything at all.', quoteKo: '음악은 본질적으로 아무것도 표현할 수 없다.' },
  { nameKo: '이고르 스트라빈스키', nameEn: 'Igor Stravinsky', years: '1882–1971', quoteEn: 'I haven\'t understood a bar of music in my life, but I have felt it.', quoteKo: '나는 평생 한 마디의 음악도 이해하지 못했지만, 느꼈다.' },
  { nameKo: '세르게이 프로코피예프', nameEn: 'Sergei Prokofiev', years: '1891–1953', quoteEn: 'In my view, the composer, just like the poet, the sculptor or the painter, is in duty bound to serve man, the people.', quoteKo: '내 관점에서 작곡가는 시인, 조각가, 화가처럼 인간과 민중을 섬길 의무가 있다.' },
  { nameKo: '세르게이 프로코피예프', nameEn: 'Sergei Prokofiev', years: '1891–1953', quoteEn: 'I abhor imitation. I abhor hackneyed devices.', quoteKo: '나는 모방을 혐오한다. 진부한 기법을 혐오한다.' },
  { nameKo: '엑토르 베를리오즈', nameEn: 'Hector Berlioz', years: '1803–1869', quoteEn: 'Time is a great teacher, but unfortunately it kills all its pupils.', quoteKo: '시간은 위대한 스승이지만, 불행히도 모든 제자를 죽인다.' },
  { nameKo: '엑토르 베를리오즈', nameEn: 'Hector Berlioz', years: '1803–1869', quoteEn: 'Every composer knows the anguish and despair occasioned by forgetting ideas which one had no time to write down.', quoteKo: '모든 작곡가는 적을 시간이 없어서 잊어버린 아이디어로 인한 고뇌와 절망을 안다.' },
  { nameKo: '로베르트 슈만', nameEn: 'Robert Schumann', years: '1810–1856', quoteEn: 'To send light into the darkness of men\'s hearts—such is the duty of the artist.', quoteKo: '사람들의 마음의 어둠 속에 빛을 보내는 것—그것이 예술가의 의무이다.' },
  { nameKo: '로베르트 슈만', nameEn: 'Robert Schumann', years: '1810–1856', quoteEn: 'My music is best understood by children and animals.', quoteKo: '내 음악은 아이들과 동물들이 가장 잘 이해한다.' },
  { nameKo: '조르주 비제', nameEn: 'Georges Bizet', years: '1838–1875', quoteEn: 'As a musician I tell you that if you were to suppress adultery, fanaticism, crime, evil, the supernatural, there would no longer be the means for writing one note.', quoteKo: '음악가로서 말하건대, 간통, 광신, 범죄, 악, 초자연을 억압한다면 음표 하나도 쓸 수 없게 될 것이다.' },
  { nameKo: '조제프 하이든', nameEn: 'Joseph Haydn', years: '1732–1809', quoteEn: 'There was no one near to confuse me, so I was forced to become original.', quoteKo: '나를 혼란스럽게 할 사람이 주변에 없었기에, 나는 독창적이 될 수밖에 없었다.' },
  { nameKo: '조제프 하이든', nameEn: 'Joseph Haydn', years: '1732–1809', quoteEn: 'Young people can learn from my example that something can come from nothing.', quoteKo: '젊은이들은 내 예에서 무에서도 무언가가 나올 수 있다는 것을 배울 수 있다.' },
  { nameKo: '페릭스 멘델스존', nameEn: 'Felix Mendelssohn', years: '1809–1847', quoteEn: 'Music cannot be expressed in words, not because it is vague but because it is more precise than words.', quoteKo: '음악은 말로 표현할 수 없다. 모호해서가 아니라 말보다 더 정확하기 때문이다.' },
  { nameKo: '지아코모 푸치니', nameEn: 'Giacomo Puccini', years: '1858–1924', quoteEn: 'Inspiration is an awakening, a quickening of all man\'s faculties, and it is manifested in all high artistic achievements.', quoteKo: '영감은 각성이고, 인간의 모든 능력의 촉진이며, 모든 높은 예술적 성취에서 드러난다.' },
  { nameKo: '루이 암스트롱', nameEn: 'Louis Armstrong', years: '1901–1971', quoteEn: 'What we play is life.', quoteKo: '우리가 연주하는 것은 삶이다.' },
  { nameKo: '루이 암스트롱', nameEn: 'Louis Armstrong', years: '1901–1971', quoteEn: 'If you have to ask what jazz is, you\'ll never know.', quoteKo: '재즈가 뭔지 물어봐야 한다면, 당신은 절대 모를 것이다.' },
  { nameKo: '루이 암스트롱', nameEn: 'Louis Armstrong', years: '1901–1971', quoteEn: 'Musicians don\'t retire; they stop when there\'s no more music in them.', quoteKo: '음악가는 은퇴하지 않는다. 그들 안에 더 이상 음악이 없을 때 멈출 뿐이다.' },
  { nameKo: '듀크 엘링턴', nameEn: 'Duke Ellington', years: '1899–1974', quoteEn: 'There are two kinds of music. Good music, and the other kind.', quoteKo: '음악에는 두 종류가 있다. 좋은 음악, 그리고 나머지.' },
  { nameKo: '듀크 엘링턴', nameEn: 'Duke Ellington', years: '1899–1974', quoteEn: 'A problem is a chance for you to do your best.', quoteKo: '문제는 당신이 최선을 다할 기회이다.' },
  { nameKo: '듀크 엘링턴', nameEn: 'Duke Ellington', years: '1899–1974', quoteEn: 'It don\'t mean a thing if it ain\'t got that swing.', quoteKo: '스윙이 없으면 아무 의미도 없다.' },
  { nameKo: '마일스 데이비스', nameEn: 'Miles Davis', years: '1926–1991', quoteEn: 'Do not fear mistakes. There are none.', quoteKo: '실수를 두려워하지 마라. 실수란 없다.' },
  { nameKo: '마일스 데이비스', nameEn: 'Miles Davis', years: '1926–1991', quoteEn: 'If you understood everything I said, you\'d be me.', quoteKo: '내가 한 말을 다 이해했다면, 당신은 나일 것이다.' },
  { nameKo: '마일스 데이비스', nameEn: 'Miles Davis', years: '1926–1991', quoteEn: 'I\'m always thinking about creating. My future starts when I wake up every morning.', quoteKo: '나는 항상 창작에 대해 생각한다. 내 미래는 매일 아침 일어날 때 시작된다.' },
  { nameKo: '엘라 피츠제럴드', nameEn: 'Ella Fitzgerald', years: '1917–1996', quoteEn: 'The only thing better than singing is more singing.', quoteKo: '노래하는 것보다 좋은 것은 더 많이 노래하는 것뿐이다.' },
  { nameKo: '엘라 피츠제럴드', nameEn: 'Ella Fitzgerald', years: '1917–1996', quoteEn: 'It isn\'t where you came from; it\'s where you\'re going that counts.', quoteKo: '어디서 왔는지가 아니라 어디로 가는지가 중요하다.' },
  { nameKo: '빌리 홀리데이', nameEn: 'Billie Holiday', years: '1915–1959', quoteEn: 'If I\'m going to sing like someone else, then I don\'t need to sing at all.', quoteKo: '누군가처럼 노래할 거라면, 전혀 노래할 필요가 없다.' },
  { nameKo: '빌리 홀리데이', nameEn: 'Billie Holiday', years: '1915–1959', quoteEn: 'Singing songs like \'The Man I Love\' or \'Porgy\' is no more work than sitting down and eating Chinese roast duck.', quoteKo: '\'내가 사랑하는 남자\'나 \'포기\' 같은 노래를 부르는 건 앉아서 중국식 오리구이를 먹는 것보다 힘들지 않다.' },
  { nameKo: '프랭크 시나트라', nameEn: 'Frank Sinatra', years: '1915–1998', quoteEn: 'The best revenge is massive success.', quoteKo: '최고의 복수는 엄청난 성공이다.' },
  { nameKo: '프랭크 시나트라', nameEn: 'Frank Sinatra', years: '1915–1998', quoteEn: 'You only go around once, but if you play your cards right, once is enough.', quoteKo: '인생은 한 번뿐이지만, 카드를 잘 치면 한 번으로 충분하다.' },
  { nameKo: '프랭크 시나트라', nameEn: 'Frank Sinatra', years: '1915–1998', quoteEn: 'Alcohol may be man\'s worst enemy, but the Bible says love your enemy.', quoteKo: '술은 인간의 최악의 적일 수 있지만, 성경은 적을 사랑하라고 한다.' },
  { nameKo: '냇 킹 콜', nameEn: 'Nat King Cole', years: '1919–1965', quoteEn: 'The best thing to do is keep believing in yourself and keep working hard.', quoteKo: '가장 좋은 것은 자신을 계속 믿고 열심히 노력하는 것이다.' },
  { nameKo: '존 레논', nameEn: 'John Lennon', years: '1940–1980', quoteEn: 'Life is what happens when you\'re busy making other plans.', quoteKo: '인생은 다른 계획을 세우느라 바쁠 때 일어나는 것이다.' },
  { nameKo: '존 레논', nameEn: 'John Lennon', years: '1940–1980', quoteEn: 'A dream you dream alone is only a dream. A dream you dream together is reality.', quoteKo: '혼자 꾸는 꿈은 그저 꿈일 뿐이다. 함께 꾸는 꿈은 현실이 된다.' },
  { nameKo: '존 레논', nameEn: 'John Lennon', years: '1940–1980', quoteEn: 'You may say I\'m a dreamer, but I\'m not the only one.', quoteKo: '당신은 내가 몽상가라고 말할 수 있지만, 나만 그런 것은 아니다.' },
  { nameKo: '존 레논', nameEn: 'John Lennon', years: '1940–1980', quoteEn: 'Time you enjoy wasting was not wasted.', quoteKo: '즐기며 낭비한 시간은 낭비한 시간이 아니다.' },
  { nameKo: '폴 매카트니', nameEn: 'Paul McCartney', years: '1942 ~', quoteEn: 'And in the end, the love you take is equal to the love you make.', quoteKo: '결국, 당신이 받는 사랑은 당신이 주는 사랑과 같다.' },
  { nameKo: '폴 매카트니', nameEn: 'Paul McCartney', years: '1942 ~', quoteEn: 'I used to think anyone doing anything weird was weird. Now I know that it is the people that call others weird that are weird.', quoteKo: '예전에는 이상한 일을 하는 사람은 이상하다고 생각했다. 이제 남을 이상하다고 부르는 사람이 이상한 것임을 안다.' },
  { nameKo: '조지 해리슨', nameEn: 'George Harrison', years: '1943–2001', quoteEn: 'It\'s all in the mind.', quoteKo: '모든 것은 마음속에 있다.' },
  { nameKo: '조지 해리슨', nameEn: 'George Harrison', years: '1943–2001', quoteEn: 'With every mistake, we must surely be learning.', quoteKo: '모든 실수에서 우리는 분명히 배우고 있다.' },
  { nameKo: '밥 딜런', nameEn: 'Bob Dylan', years: '1941 ~', quoteEn: 'A man is a success if he gets up in the morning and gets to bed at night, and in between he does what he wants to do.', quoteKo: '아침에 일어나 밤에 잠들고, 그 사이에 하고 싶은 일을 하면 그 사람은 성공한 것이다.' },
  { nameKo: '밥 딜런', nameEn: 'Bob Dylan', years: '1941 ~', quoteEn: 'He not busy being born is busy dying.', quoteKo: '태어나느라 바쁘지 않은 자는 죽어가느라 바쁜 것이다.' },
  { nameKo: '밥 딜런', nameEn: 'Bob Dylan', years: '1941 ~', quoteEn: 'The times they are a-changin\'.', quoteKo: '시대는 변하고 있다.' },
  { nameKo: '밥 딜런', nameEn: 'Bob Dylan', years: '1941 ~', quoteEn: 'I define nothing. Not beauty, not patriotism. I take each thing as it is, without prior rules about what it should be.', quoteKo: '나는 아무것도 정의하지 않는다. 아름다움도, 애국심도. 나는 각각의 것을 그것이 어떠해야 한다는 사전 규칙 없이 있는 그대로 받아들인다.' },
  { nameKo: '지미 헨드릭스', nameEn: 'Jimi Hendrix', years: '1942–1970', quoteEn: 'Music doesn\'t lie. If there is something to be changed in this world, then it can only happen through music.', quoteKo: '음악은 거짓말하지 않는다. 이 세상에 바꿔야 할 것이 있다면, 그것은 오직 음악을 통해서만 일어날 수 있다.' },
  { nameKo: '지미 헨드릭스', nameEn: 'Jimi Hendrix', years: '1942–1970', quoteEn: 'Knowledge speaks, but wisdom listens.', quoteKo: '지식은 말하지만, 지혜는 듣는다.' },
  { nameKo: '지미 헨드릭스', nameEn: 'Jimi Hendrix', years: '1942–1970', quoteEn: 'I\'m the one that\'s got to die when it\'s time for me to die, so let me live my life the way I want to.', quoteKo: '죽을 때가 되면 죽어야 하는 건 나니까, 내가 원하는 대로 살게 해줘.' },
  { nameKo: '데이비드 보위', nameEn: 'David Bowie', years: '1947–2016', quoteEn: 'I don\'t know where I\'m going from here, but I promise it won\'t be boring.', quoteKo: '여기서 어디로 갈지 모르겠지만, 지루하지는 않을 것을 약속한다.' },
  { nameKo: '데이비드 보위', nameEn: 'David Bowie', years: '1947–2016', quoteEn: 'I always had a repulsive need to be something more than human.', quoteKo: '나는 항상 인간 이상의 무언가가 되고자 하는 혐오스러운 욕구가 있었다.' },
  { nameKo: '데이비드 보위', nameEn: 'David Bowie', years: '1947–2016', quoteEn: 'Tomorrow belongs to those who can hear it coming.', quoteKo: '내일은 그것이 오는 것을 들을 수 있는 자의 것이다.' },
  { nameKo: '프레디 머큐리', nameEn: 'Freddie Mercury', years: '1946–1991', quoteEn: 'I won\'t be a rock star. I will be a legend.', quoteKo: '나는 록스타가 되지 않을 것이다. 나는 전설이 될 것이다.' },
  { nameKo: '프레디 머큐리', nameEn: 'Freddie Mercury', years: '1946–1991', quoteEn: 'The reason we\'re successful, darling? My overall charisma, of course.', quoteKo: '우리가 성공한 이유? 물론 나의 전반적인 카리스마지.' },
  { nameKo: '프레디 머큐리', nameEn: 'Freddie Mercury', years: '1946–1991', quoteEn: 'I dress to kill, but tastefully.', quoteKo: '나는 죽이게 차려입지만, 품위 있게.' },
  { nameKo: '엘비스 프레슬리', nameEn: 'Elvis Presley', years: '1935–1977', quoteEn: 'When things go wrong, don\'t go with them.', quoteKo: '일이 잘못될 때, 함께 잘못되지 마라.' },
  { nameKo: '엘비스 프레슬리', nameEn: 'Elvis Presley', years: '1935–1977', quoteEn: 'Ambition is a dream with a V8 engine.', quoteKo: '야망은 V8 엔진을 단 꿈이다.' },
  { nameKo: '엘비스 프레슬리', nameEn: 'Elvis Presley', years: '1935–1977', quoteEn: 'I don\'t know anything about music. In my line you don\'t have to.', quoteKo: '나는 음악에 대해 아무것도 모른다. 내 분야에서는 알 필요가 없다.' },
  { nameKo: '미크 재거', nameEn: 'Mick Jagger', years: '1943 ~', quoteEn: 'It\'s all right letting yourself go, as long as you can get yourself back.', quoteKo: '자신을 놓아주는 것은 괜찮다. 다시 찾을 수 있기만 하면.' },
  { nameKo: '미크 재거', nameEn: 'Mick Jagger', years: '1943 ~', quoteEn: 'Lose your dreams and you might lose your mind.', quoteKo: '꿈을 잃으면 정신을 잃을 수도 있다.' },
  { nameKo: '키스 리처즈', nameEn: 'Keith Richards', years: '1943 ~', quoteEn: 'Music is a language that doesn\'t speak in particular words. It speaks in emotions.', quoteKo: '음악은 특정 단어로 말하지 않는 언어이다. 감정으로 말한다.' },
  { nameKo: '키스 리처즈', nameEn: 'Keith Richards', years: '1943 ~', quoteEn: 'I\'ve never had a problem with drugs. I\'ve had problems with the police.', quoteKo: '나는 마약에 문제가 있었던 적이 없다. 경찰에 문제가 있었다.' },
  { nameKo: '레이 찰스', nameEn: 'Ray Charles', years: '1930–2004', quoteEn: 'Music is my life, it is a reflection of what I go through.', quoteKo: '음악은 내 삶이다. 그것은 내가 겪는 것의 반영이다.' },
  { nameKo: '레이 찰스', nameEn: 'Ray Charles', years: '1930–2004', quoteEn: 'I was born with music inside me. Music was one of my parts.', quoteKo: '나는 음악을 안고 태어났다. 음악은 나의 일부였다.' },
  { nameKo: '스티비 원더', nameEn: 'Stevie Wonder', years: '1950 ~', quoteEn: 'Music, at its essence, is what gives us memories.', quoteKo: '음악은 본질적으로 우리에게 기억을 주는 것이다.' },
  { nameKo: '스티비 원더', nameEn: 'Stevie Wonder', years: '1950 ~', quoteEn: 'Just because a man lacks the use of his eyes doesn\'t mean he lacks vision.', quoteKo: '눈을 사용할 수 없다고 해서 비전이 없는 것은 아니다.' },
  { nameKo: '아레사 프랭클린', nameEn: 'Aretha Franklin', years: '1942–2018', quoteEn: 'Music does a lot of things for a lot of people. It\'s transporting, for sure.', quoteKo: '음악은 많은 사람들에게 많은 것을 한다. 확실히 다른 세계로 데려다준다.' },
  { nameKo: '아레사 프랭클린', nameEn: 'Aretha Franklin', years: '1942–2018', quoteEn: 'Be your own artist, and always be confident in what you\'re doing.', quoteKo: '자신만의 예술가가 되어라. 그리고 당신이 하는 일에 항상 자신감을 가져라.' },
  { nameKo: '밥 말리', nameEn: 'Bob Marley', years: '1945–1981', quoteEn: 'One good thing about music, when it hits you, you feel no pain.', quoteKo: '음악의 좋은 점 하나는, 그것이 당신을 칠 때 고통을 느끼지 않는다는 것이다.' },
  { nameKo: '밥 말리', nameEn: 'Bob Marley', years: '1945–1981', quoteEn: 'Don\'t gain the world and lose your soul; wisdom is better than silver or gold.', quoteKo: '세상을 얻고 영혼을 잃지 마라. 지혜는 은이나 금보다 낫다.' },
  { nameKo: '밥 말리', nameEn: 'Bob Marley', years: '1945–1981', quoteEn: 'The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.', quoteKo: '진실은, 모든 사람이 당신을 상처 줄 것이라는 것이다. 당신은 고통받을 가치가 있는 사람을 찾아야 한다.' },
  { nameKo: '프린스', nameEn: 'Prince', years: '1958–2016', quoteEn: 'A strong spirit transcends rules.', quoteKo: '강한 정신은 규칙을 초월한다.' },
  { nameKo: '프린스', nameEn: 'Prince', years: '1958–2016', quoteEn: 'Despite everything, no one can dictate who you are to other people.', quoteKo: '모든 것에도 불구하고, 아무도 당신이 누구인지 다른 사람에게 지시할 수 없다.' },
  { nameKo: '프린스', nameEn: 'Prince', years: '1958–2016', quoteEn: 'Cool means being able to hang with yourself.', quoteKo: '쿨하다는 것은 자기 자신과 함께할 수 있다는 것이다.' },
  { nameKo: '안토니오 비발디', nameEn: 'Antonio Vivaldi', years: '1678–1741', quoteEn: 'There are no words here, there is only music.', quoteKo: '여기에는 말이 없다, 오직 음악만 있을 뿐이다.' },
  { nameKo: '안토니오 비발디', nameEn: 'Antonio Vivaldi', years: '1678–1741', quoteEn: 'If you don\'t like this, I\'ll stop writing music.', quoteKo: '이것마저 마음에 안 들면 나 이제 음악 안 만들란다.' },
  { nameKo: '게오르크 프리드리히 헨델', nameEn: 'George Frideric Handel', years: '1685–1759', quoteEn: 'I should be sorry if I only entertained them; I wished to make them better.', quoteKo: '내가 사람들을 그저 즐겁게만 해주었다면 유감일 것이다. 나는 그들을 더 나은 사람으로 만들고 싶었다.' },
  { nameKo: '게오르크 프리드리히 헨델', nameEn: 'George Frideric Handel', years: '1685–1759', quoteEn: 'Whether I was in my body or out of my body when I wrote it, I know not. God knows.', quoteKo: '내가 그걸 썼을 때 내 몸 안에 있었는지 몸 밖에 있었는지 나는 모른다. 하나님만이 아신다.' },
  { nameKo: '아널드 쇤베르크', nameEn: 'Arnold Schoenberg', years: '1874–1951', quoteEn: 'If it is art, it is not for all, and if it is for all, it is not art.', quoteKo: '예술이라면 대중을 위한 것이 아니고, 대중을 위한 것이라면 예술이 아니다.' },
  { nameKo: '아널드 쇤베르크', nameEn: 'Arnold Schoenberg', years: '1874–1951', quoteEn: 'My music is not lovely, but I don\'t intend it to be.', quoteKo: '내 음악은 사랑스럽지 않다. 그리고 난 그렇게 만들 생각도 없다.' },
  { nameKo: '존 케이지', nameEn: 'John Cage', years: '1912–1992', quoteEn: 'I can\'t understand why people are frightened of new ideas. I\'m frightened of the old ones.', quoteKo: '사람들이 왜 새로운 아이디어를 두려워하는지 이해할 수 없다. 나는 옛것들이 두렵다.' },
  { nameKo: '존 케이지', nameEn: 'John Cage', years: '1912–1992', quoteEn: 'Everything we do is music.', quoteKo: '우리가 하는 모든 행동이 음악이다.' },
  { nameKo: '존 케이지', nameEn: 'John Cage', years: '1912–1992', quoteEn: 'There is no such thing as silence. Something is always happening that makes a sound.', quoteKo: '침묵이라는 것은 존재하지 않는다. 소리를 만들어내는 무언가가 항상 일어나고 있다.' },
  { nameKo: '에릭 사티', nameEn: 'Erik Satie', years: '1866–1925', quoteEn: 'The musician is perhaps the most modest of animals, but he is also the proudest.', quoteKo: '음악가는 아마 동물 중 가장 겸손하겠지만, 동시에 가장 오만할 것이다.' },
  { nameKo: '에릭 사티', nameEn: 'Erik Satie', years: '1866–1925', quoteEn: 'Before I compose a piece, I walk around it several times, accompanied by myself.', quoteKo: '나는 곡을 쓰기 전에, 나 자신을 동반하고 그 곡 주변을 몇 번이고 산책한다.' },
  { nameKo: '에릭 사티', nameEn: 'Erik Satie', years: '1866–1925', quoteEn: 'If you want to live long, live poor and without ambition.', quoteKo: '오래 살고 싶다면 가난하게, 야망 없이 살아라.' },
  { nameKo: '에릭 사티', nameEn: 'Erik Satie', years: '1866–1925', quoteEn: 'Although our intellect is always functioning, it is really doing very little.', quoteKo: '우리의 지성이 언제나 작동하고 있긴 하지만, 실제로 하는 일은 거의 없다.' },
  { nameKo: '드미트리 쇼스타코비치', nameEn: 'Dmitri Shostakovich', years: '1906–1975', quoteEn: 'A creative artist works on his next composition because he was not satisfied with his previous one.', quoteKo: '창조적인 예술가가 다음 곡을 작업하는 이유는 이전 곡에 만족하지 못했기 때문이다.' },
  { nameKo: '드미트리 쇼스타코비치', nameEn: 'Dmitri Shostakovich', years: '1906–1975', quoteEn: 'Waiting for execution is one of the themes that has tormented me all my life.', quoteKo: '처형을 기다리는 것은 평생 나를 괴롭혀온 테마 중 하나이다.' },
  { nameKo: '모리스 라벨', nameEn: 'Maurice Ravel', years: '1875–1937', quoteEn: 'The only love affair I ever had was with music.', quoteKo: '내가 해본 유일한 연애는 음악과의 연애뿐이었다.' },
  { nameKo: '모리스 라벨', nameEn: 'Maurice Ravel', years: '1875–1937', quoteEn: 'I don\'t need to express my feelings; I just write notes.', quoteKo: '내 감정을 표현할 필요는 없다. 난 그저 음표를 적을 뿐이다.' },
  { nameKo: '글렌 굴드', nameEn: 'Glenn Gould', years: '1932–1982', quoteEn: 'The purpose of art is not the release of a momentary ejection of adrenaline but rather the gradual, lifelong construction of a state of wonder and serenity.', quoteKo: '예술의 목적은 아드레날린의 일시적인 분출이 아니라, 경이로움과 평온함의 상태를 평생에 걸쳐 점진적으로 구축해 나가는 것이다.' },
  { nameKo: '글렌 굴드', nameEn: 'Glenn Gould', years: '1932–1982', quoteEn: 'I shut myself in a room for months, and it’s the closest thing to heaven I know.', quoteKo: '몇 달 동안 방에 처박혀 있는 것, 그것이 내가 아는 천국에 가장 가까운 모습이다.' },
  { nameKo: '헤르베르트 폰 카라얀', nameEn: 'Herbert von Karajan', years: '1908–1989', quoteEn: 'If you have achieved everything in your life, you are ready to die.', quoteKo: '인생에서 모든 것을 성취했다면, 죽을 준비가 된 것이다.' },
  { nameKo: '헤르베르트 폰 카라얀', nameEn: 'Herbert von Karajan', years: '1908–1989', quoteEn: 'The art of conducting consists in knowing when to leave the orchestra alone.', quoteKo: '지휘의 기술은 오케스트라를 언제 가만히 내버려 두어야 하는지 아는 데 있다.' },
  { nameKo: '필립 글래스', nameEn: 'Philip Glass', years: '1937 ~', quoteEn: 'Music is not a reflection of reality. It is a reality itself.', quoteKo: '음악은 현실의 반영이 아니다. 음악 그 자체가 하나의 현실이다.' },
  { nameKo: '필립 글래스', nameEn: 'Philip Glass', years: '1937 ~', quoteEn: 'You practice and you practice and you practice, and then you go on stage and you forget everything.', quoteKo: '연습하고, 연습하고, 또 연습하라. 그리고 무대에 올라가면 모든 걸 잊어버려라.' },
  { nameKo: '장 시벨리우스', nameEn: 'Jean Sibelius', years: '1865–1957', quoteEn: 'Pay no attention to what the critics say. A statue has never been erected in honor of a critic.', quoteKo: '평론가들의 말에 신경 쓰지 마라. 평론가를 기리기 위해 세워진 동상은 어디에도 없다.' },
  { nameKo: '아스토르 피아졸라', nameEn: 'Astor Piazzolla', years: '1921–1992', quoteEn: 'For me, tango was always for the ear rather than the feet.', quoteKo: '나에게 탱고는 언제나 발을 위한 것이 아니라 귀를 위한 것이었다.' },
  { nameKo: '아람 하차투리안', nameEn: 'Aram Khachaturian', years: '1903–1978', quoteEn: 'Music is a language that does not require translation.', quoteKo: '음악은 번역이 필요 없는 언어다.' },
  { nameKo: '지오반니 피에를루이지 다 팔레스트리나', nameEn: 'Giovanni Pierluigi da Palestrina', years: '1525–1594', quoteEn: 'Music exalts the human soul; it is the language of the angels.', quoteKo: '음악은 인간의 영혼을 고양시킨다. 그것은 천사들의 언어다.' },
  { nameKo: '클라우디오 몬테베르디', nameEn: 'Claudio Monteverdi', years: '1567–1643', quoteEn: 'The end of all good music is to affect the soul.', quoteKo: '모든 좋은 음악의 목적은 영혼에 영향을 주는 것이다.' },
  { nameKo: '헨리 퍼셀', nameEn: 'Henry Purcell', years: '1659–1695', quoteEn: 'Music is the exalted language of the soul.', quoteKo: '음악은 영혼의 고결한 언어이다.' },
  { nameKo: '장 필립 라모', nameEn: 'Jean-Philippe Rameau', years: '1683–1764', quoteEn: 'Music is a science which must have definite rules.', quoteKo: '음악은 명확한 규칙을 가져야만 하는 과학이다.' },
  { nameKo: '칼하인츠 슈톡하우젠', nameEn: 'Karlheinz Stockhausen', years: '1928–2007', quoteEn: 'We need to make music that changes people\'s minds, not music that just entertains them.', quoteKo: '우리는 그저 사람들을 즐겁게 하는 음악이 아니라, 사람들의 정신을 바꾸는 음악을 만들어야 한다.' },
  { nameKo: '칼하인츠 슈톡하우젠', nameEn: 'Karlheinz Stockhausen', years: '1928–2007', quoteEn: 'The 9/11 attack was the greatest work of art that exists for the whole cosmos.', quoteKo: '9/11 테러는 전 우주에 존재하는 가장 위대한 예술 작품이다.' },
  { nameKo: '레너드 번스타인', nameEn: 'Leonard Bernstein', years: '1918–1990', quoteEn: 'To achieve great things, two things are needed; a plan, and not quite enough time.', quoteKo: '위대한 일을 성취하려면 두 가지가 필요하다. 계획, 그리고 약간 모자란 시간.' },
  { nameKo: '레너드 번스타인', nameEn: 'Leonard Bernstein', years: '1918–1990', quoteEn: 'This will be our reply to violence: to make music more intensely, more beautifully, more devotedly than ever before.', quoteKo: '이것이 폭력에 대한 우리의 대답이 될 것이다. 이전보다 더 강렬하게, 더 아름답게, 더 헌신적으로 음악을 만드는 것.' },
  { nameKo: '커트 코베인', nameEn: 'Kurt Cobain', years: '1967–1994', quoteEn: 'It\'s better to burn out than to fade away.', quoteKo: '서서히 꺼지는 것보다 한 번에 불타버리는 것이 낫다.' },
  { nameKo: '커트 코베인', nameEn: 'Kurt Cobain', years: '1967–1994', quoteEn: 'Wanting to be someone else is a waste of the person you are.', quoteKo: '다른 사람이 되고 싶어 하는 것은 자신이라는 사람을 낭비하는 것이다.' },
  { nameKo: '커트 코베인', nameEn: 'Kurt Cobain', years: '1967–1994', quoteEn: 'Thank you for the tragedy. I need it for my art.', quoteKo: '비극에 감사한다. 내 예술에는 비극이 필요하다.' },
  { nameKo: '마이클 잭슨', nameEn: 'Michael Jackson', years: '1958–2009', quoteEn: 'If you wanna make the world a better place, take a look at yourself, and then make a change.', quoteKo: '세상을 더 나은 곳으로 만들고 싶다면, 자신을 돌아보고 변화를 시작해라.' },
  { nameKo: '마이클 잭슨', nameEn: 'Michael Jackson', years: '1958–2009', quoteEn: 'Lies run sprints, but the truth runs marathons.', quoteKo: '거짓말은 단거리를 달리지만, 진실은 마라톤을 달린다.' },
  { nameKo: '마이클 잭슨', nameEn: 'Michael Jackson', years: '1958–2009', quoteEn: 'To give someone a piece of your heart is worth more than all the wealth in the world.', quoteKo: '누군가에게 당신의 마음 한 조각을 주는 것은 세상의 모든 부보다 가치 있다.' },
  { nameKo: '투팍 샤커', nameEn: 'Tupac Shakur', years: '1971–1996', quoteEn: 'I\'m not saying I\'m gonna change the world, but I guarantee that I will spark the brain that will change the world.', quoteKo: '내가 세상을 바꿀 거라 말하진 않겠다. 하지만 세상을 바꿀 정신에 불꽃을 일으킬 것임은 보장한다.' },
  { nameKo: '투팍 샤커', nameEn: 'Tupac Shakur', years: '1971–1996', quoteEn: 'Reality is wrong. Dreams are for real.', quoteKo: '현실이 잘못된 것이다. 꿈이야말로 진짜다.' },
  { nameKo: '에미넴', nameEn: 'Eminem', years: '1972 ~', quoteEn: 'You\'ve got to find that inner strength and just pull that shit out of you.', quoteKo: '당신은 내면의 힘을 찾아내서 그 빌어먹을 것을 밖으로 끄집어내야 한다.' },
  { nameKo: '에미넴', nameEn: 'Eminem', years: '1972 ~', quoteEn: 'Dealing with backstabbers, there was one thing I learned. They\'re only powerful when your back is turned.', quoteKo: '등 뒤에서 칼을 꽂는 인간들을 상대하며 배운 게 하나 있다. 그들은 당신이 등을 돌리고 있을 때만 강하다는 것이다.' },
  { nameKo: '오지 오스본', nameEn: 'Ozzy Osbourne', years: '1948 ~', quoteEn: 'Of all the things I\'ve lost I miss my mind the most.', quoteKo: '내가 잃어버린 모든 것들 중에서, 내 정신머리가 가장 그리워.' },
  { nameKo: '오지 오스본', nameEn: 'Ozzy Osbourne', years: '1948 ~', quoteEn: 'I knew it was time to get off the drugs when I was having long conversations with a horse.', quoteKo: '말과 진지하게 긴 대화를 나누고 있을 때, 아 이제 마약을 끊을 때가 됐구나 싶었다.' },
  { nameKo: '갤러러 형제 - 오아시스', nameEn: 'Noel Gallagher / Liam Gallagher', years: '1967 ~ / 1972 ~', quoteEn: 'I\'m not arrogant, I just think we\'re the best band in the world.', quoteKo: '난 거만하지 않다. 그저 우리가 세계 최고의 밴드라고 생각할 뿐이다.' },
  { nameKo: '갤러러 형제 - 오아시스', nameEn: 'Noel Gallagher / Liam Gallagher', years: '1967 ~ / 1972 ~', quoteEn: 'If I wasn\'t a musician, I don\'t know. I’d probably be a god.', quoteKo: '내가 음악가가 안 됐다면? 글쎄, 아마 신이 되었겠지.' },
  { nameKo: '갤러러 형제 - 오아시스', nameEn: 'Noel Gallagher / Liam Gallagher', years: '1967 ~ / 1972 ~', quoteEn: 'True perfection has to be imperfect.', quoteKo: '진정한 완벽함은 불완전해야 한다.' },
  { nameKo: '칸예 웨스트 / 예', nameEn: 'Kanye West / Ye', years: '1977 ~', quoteEn: 'My greatest pain in life is that I will never be able to see myself perform live.', quoteKo: '내 인생 최고의 고통은 내가 무대에서 공연하는 모습을 내 눈으로 직접 볼 수 없다는 것이다.' },
  { nameKo: '칸예 웨스트 / 예', nameEn: 'Kanye West / Ye', years: '1977 ~', quoteEn: 'We\'re not human beings. We\'re creators.', quoteKo: '우리는 인간이 아니다. 창조자들이다.' },
  { nameKo: '톰 요크 - 라디오헤드', nameEn: 'Thom Yorke', years: '1968 ~', quoteEn: 'Being in a band turns you into a child and keeps you there.', quoteKo: '밴드를 한다는 것은 당신을 어린아이로 만들고, 그 상태에 머물게 하는 것이다.' },
  { nameKo: '톰 요크 - 라디오헤드', nameEn: 'Thom Yorke', years: '1968 ~', quoteEn: 'Pathetic strings make me cry.', quoteKo: '한심한 현악 소리는 날 울게 만든다.' },
  { nameKo: '보노 - U2', nameEn: 'Bono', years: '1960 ~', quoteEn: 'Music can change the world because it can change people.', quoteKo: '음악은 사람을 바꿀 수 있기 때문에 세상을 바꿀 수 있다.' },
  { nameKo: '레이디 가가', nameEn: 'Lady Gaga', years: '1986 ~', quoteEn: 'Some women choose to follow men, and some women choose to follow their dreams.', quoteKo: '어떤 여성들은 남자를 따르기로 선택하고, 어떤 여성들은 꿈을 따르기로 선택한다.' },
  { nameKo: '레이디 가가', nameEn: 'Lady Gaga', years: '1986 ~', quoteEn: 'If you don\'t have any shadows, you\'re not standing in the light.', quoteKo: '당신에게 그림자가 없다면, 당신은 빛 속에 서 있는 것이 아니다.' },
  { nameKo: '마돈나', nameEn: 'Madonna', years: '1958 ~', quoteEn: 'I\'m tough, I\'m ambitious, and I know exactly what I want. If that makes me a bitch, okay.', quoteKo: '나는 터프하고, 야망이 있으며, 내가 무엇을 원하는지 정확히 안다. 만약 그것 때문에 내가 독한 년이 된다면, 뭐 상관없다.' },
  { nameKo: '마돈나', nameEn: 'Madonna', years: '1958 ~', quoteEn: 'No matter who you are, no matter what you did, no matter where you\'ve come from, you can always change, become a better version of yourself.', quoteKo: '당신이 누구든, 무슨 짓을 했든, 어디서 왔든, 당신은 언제든 변해서 더 나은 자신이 될 수 있다.' },
  { nameKo: '비제이', nameEn: 'Björk', years: '1965 ~', quoteEn: 'I find it sometimes quite beautiful that we don\'t know all the answers.', quoteKo: '우리가 모든 정답을 알지 못한다는 사실이 때로는 꽤 아름답게 느껴진다.' },
  { nameKo: '타일러 더 크리에이터', nameEn: 'Tyler', years: '1991 ~', quoteEn: 'I\'m not a follower. I\'m a leader. And anyone who speaks their mind is a leader.', quoteKo: '나는 추종자가 아니다. 리더다. 그리고 자기 생각을 말하는 사람은 누구나 리더다.' },
  { nameKo: '빌리 아이리시', nameEn: 'Billie Eilish', years: '2001 ~', quoteEn: 'In the dark, total darkness, everyone\'s equal.', quoteKo: '어둠 속에서, 완전한 어둠 속에서는 모두가 평등하다.' },
  { nameKo: '테일러 스위프트', nameEn: 'Taylor Swift', years: '1989 ~', quoteEn: 'People are going to judge you anyway, so you might as well do what you want.', quoteKo: '사람들은 어차피 당신을 판단할 것이다. 그러니 그냥 당신이 원하는 걸 하는 게 낫다.' },
  { nameKo: '제이지', nameEn: 'Jay-Z', years: '1969 ~', quoteEn: 'I\'m not a businessman, I\'m a business, man!', quoteKo: '나는 비즈니스맨이 아니다. 나 자체가 비즈니스다.' },
  { nameKo: '제이지', nameEn: 'Jay-Z', years: '1969 ~', quoteEn: 'Identity is a prison, you can never escape, but the way to redeem your past is not to run from it, but to try to understand it.', quoteKo: '정체성은 결코 탈출할 수 없는 감옥과 같지만, 과거를 보상하는 방법은 도망치는 것이 아니라 그것을 이해하려고 노력하는 것이다.' },
  { nameKo: '제이지', nameEn: 'Jay-Z', years: '1969 ~', quoteEn: 'Excellence is being able to perform at a high level over and over again.', quoteKo: '탁월함이란 높은 수준의 성과를 몇 번이고 반복해서 보여줄 수 있는 능력이다.' },
  { nameKo: '제이지', nameEn: 'Jay-Z', years: '1969 ~', quoteEn: 'Remind yourself, nobody\'s built like you, you design yourself.', quoteKo: '기억해라, 아무도 너처럼 만들어지지 않았다. 너 자신을 디자인하는 것은 바로 너다.' },
  { nameKo: '나스', nameEn: 'Nas', years: '1973 ~', quoteEn: 'Sleep is the cousin of death.', quoteKo: '잠은 죽음의 사촌이다.' },
  { nameKo: '나스', nameEn: 'Nas', years: '1973 ~', quoteEn: 'No security in this wild world; when push come to shove, you can only trust your own people.', quoteKo: '이 거친 세상에 안전이란 없다. 상황이 막바지에 다다르면 오직 내 사람만 믿을 수 있을 뿐이다.' },
  { nameKo: '나스', nameEn: 'Nas', years: '1973 ~', quoteEn: 'I non-stop write, it’s like a habit.', quoteKo: '나는 쉬지 않고 글을 쓴다. 그건 그냥 습관 같다.' },
  { nameKo: '나스', nameEn: 'Nas', years: '1973 ~', quoteEn: 'Beyond the walls of intelligence, life is defined.', quoteKo: '지성의 벽을 넘어설 때, 비로소 삶이 정의된다.' },
  { nameKo: '노토리어스 비아이지 / 비기', nameEn: 'The Notorious B.I.G.', years: '1972–1997', quoteEn: 'Mo money, mo problems.', quoteKo: '돈이 많아질수록, 문제도 많아진다.' },
  { nameKo: '노토리어스 비아이지 / 비기', nameEn: 'The Notorious B.I.G.', years: '1972–1997', quoteEn: 'We can\'t change the world unless we change ourselves.', quoteKo: '우리 자신을 바꾸지 않는 한 우리는 세상을 바꿀 수 없다.' },
  { nameKo: '노토리어스 비아이지 / 비기', nameEn: 'The Notorious B.I.G.', years: '1972–1997', quoteEn: 'Excellence is my presence, never tense, never hesitant.', quoteKo: '나의 존재 자체가 탁월함이다. 절대 긴장하지 않고, 절대 망설이지 않지.' },
  { nameKo: '드레이크', nameEn: 'Drake', years: '1986 ~', quoteEn: 'You only live once: that\'s the motto, nigger, YOLO.', quoteKo: '인생은 오직 한 번뿐이야. 그게 우리의 모토지, YOLO.' },
  { nameKo: '드레이크', nameEn: 'Drake', years: '1986 ~', quoteEn: 'Haters will broadcast your failures, but whisper your success.', quoteKo: '너를 미워하는 자들은 너의 실패를 동네방네 소문내겠지만, 너의 성공은 조용히 속삭일 것이다.' },
  { nameKo: '드레이크', nameEn: 'Drake', years: '1986 ~', quoteEn: 'Sometimes I wish I could just go back to the baseline.', quoteKo: '가끔은 그냥 모든 게 시작되던 기준점으로 돌아가고 싶을 때가 있다.' },
  { nameKo: '드레이크', nameEn: 'Drake', years: '1986 ~', quoteEn: 'I was born to make mistakes, not to fake perfection.', quoteKo: '나는 실수를 하기 위해 태어난 것이지, 완벽함을 연기하기 위해 태어난 게 아니다.' },
  { nameKo: '켄드릭 라마', nameEn: 'Kendrick Lamar', years: '1987 ~', quoteEn: 'If I\'m gonna tell a real story, I\'m gonna start with my name.', quoteKo: '내가 진짜 이야기를 하려고 한다면, 내 이름부터 시작하겠다.' },
  { nameKo: '켄드릭 라마', nameEn: 'Kendrick Lamar', years: '1987 ~', quoteEn: 'We hurt people that love us, love people that hurt us.', quoteKo: '우리는 우리를 사랑하는 사람들에게 상처를 주고, 우리에게 상처를 주는 사람들을 사랑한다.' },
  { nameKo: '켄드릭 라마', nameEn: 'Kendrick Lamar', years: '1987 ~', quoteEn: 'Conscience is a baseline, you can\'t fake that.', quoteKo: '양심은 기준선이다. 그것은 속여낼 수 없다.' },
  { nameKo: '켄드릭 라마', nameEn: 'Kendrick Lamar', years: '1987 ~', quoteEn: 'Look at me, I\'m a loser. I\'m a winner. I\'m good, I\'m bad.', quoteKo: '나를 봐라, 나는 루저이자 위너다. 착하기도 하고 악하기도 하지.' },
  { nameKo: '제이 콜', nameEn: 'J. Cole', years: '1985 ~', quoteEn: 'There is no such thing as a life that is better than yours.', quoteKo: '네 삶보다 더 나은 삶 같은 건 세상에 존재하지 않는다.' },
  { nameKo: '제이 콜', nameEn: 'J. Cole', years: '1985 ~', quoteEn: 'No need to fix what God already put his paintbrush on.', quoteKo: '신이 이미 붓칠을 해놓으신 것을 굳이 고치려 들 필요는 없다.' },
  { nameKo: '제이 콜', nameEn: 'J. Cole', years: '1985 ~', quoteEn: 'They say time is money, but really, it\'s not. Time is life.', quoteKo: '사람들은 시간이 돈이라고 하지만, 진짜는 아니다. 시간은 곧 생명이다.' },
  { nameKo: '스눕 독', nameEn: 'Snoop Dogg', years: '1971 ~', quoteEn: 'I want to thank me for being me at all times.', quoteKo: '언제나 나 자신으로 살아준 나 자신에게 감사하고 싶다.' },
  { nameKo: '스눕 독', nameEn: 'Snoop Dogg', years: '1971 ~', quoteEn: 'It\'s so easy a caveman can do it.', quoteKo: '그건 하도 쉬워서 원시인도 하겠다.' },
  { nameKo: '스눕 독', nameEn: 'Snoop Dogg', years: '1971 ~', quoteEn: 'If the ride is more fly, then you must buy.', quoteKo: '차 분위기가 죽여준다면, 당연히 사야지.' },
  { nameKo: '닥터 드레', nameEn: 'Dr. Dre', years: '1965 ~', quoteEn: 'You just have to find that thing that\'s special about you that distinguishes you from all the others.', quoteKo: '너는 그저 다른 모든 사람들과 너를 구별해 주는 너만의 특별한 것을 찾아내면 된다.' },
  { nameKo: '닥터 드레', nameEn: 'Dr. Dre', years: '1965 ~', quoteEn: 'I\'ve gone absolute silver and gold, but I never forgot the ghetto.', quoteKo: '내 음반들이 완전히 실버와 골드를 기록하며 대박이 났지만, 난 결코 빈민가를 잊은 적이 없다.' },
  { nameKo: '아이스 큐브', nameEn: 'Ice Cube', years: '1969 ~', quoteEn: 'Today was a good day.', quoteKo: '오늘은 좋은 날이었어.' },
  { nameKo: '아이스 큐브', nameEn: 'Ice Cube', years: '1969 ~', quoteEn: 'Truth is the ultimate power. When the truth comes around, all the lies have to run and hide.', quoteKo: '진실은 궁극의 힘이다. 진실이 나타나면 모든 거짓은 도망쳐 숨어야 한다.' },
  { nameKo: '50센트', nameEn: '50 Cent', years: '1975 ~', quoteEn: 'Get rich or die tryin\'.', quoteKo: '부자가 되거나, 아니면 부자가 되려다 죽거나.' },
  { nameKo: '50센트', nameEn: '50 Cent', years: '1975 ~', quoteEn: 'Sleep is for those people who are broke.', quoteKo: '잠은 돈이 없는 거지들이나 자는 것이다.' },
  { nameKo: '50센트', nameEn: '50 Cent', years: '1975 ~', quoteEn: 'Wise men listen and laugh, while fools talk.', quoteKo: '지혜로운 자들은 듣고 웃지만, 바보들은 지껄인다.' },
  { nameKo: '릴 웨인', nameEn: 'Lil Wayne', years: '1982 ~', quoteEn: 'I am probably the most visual writer there is. I don\'t write down anything.', quoteKo: '나는 아마 현존하는 가장 시각적인 작가일 것이다. 왜냐하면 난 아무것도 받아적지 않으니까.' },
  { nameKo: '릴 웨인', nameEn: 'Lil Wayne', years: '1982 ~', quoteEn: 'The more time you spend complaining, the less time you have to get money.', quoteKo: '불평하는 데 시간을 더 많이 쓸수록, 돈을 벌 시간은 줄어든다.' },
  { nameKo: '릴 웨인', nameEn: 'Lil Wayne', years: '1982 ~', quoteEn: 'I\'m a prisoner of my own mind.', quoteKo: '나는 내 정신의 포로다.' },
  { nameKo: '맥 밀러', nameEn: 'Mac Miller', years: '1992–2018', quoteEn: 'No matter where life takes me, find me with a smile.', quoteKo: '삶이 나를 어디로 데려가든, 내가 미소 짓고 있는 모습을 찾아내 주길.' },
  { nameKo: '맥 밀러', nameEn: 'Mac Miller', years: '1992–2018', quoteEn: 'The end of the world is not the end of anything, it\'s just the beginning of a whole new universe.', quoteKo: '세상의 종말은 무언가의 끝이 아니다. 그것은 완전히 새로운 우주의 시작일 뿐이다.' },
  { nameKo: '맥 밀러', nameEn: 'Mac Miller', years: '1992–2018', quoteEn: 'Enjoy the best things in your life, cause you ain\'t gonna get to live it twice.', quoteKo: '인생에서 가장 좋은 것들을 즐겨라, 두 번 살 수 있는 게 아니니까.' },
  { nameKo: '주스 월드', nameEn: 'Juice WRLD', years: '1998–2019', quoteEn: 'Even if I\'m not here, my music will always live.', quoteKo: '내가 비록 여기 없더라도, 내 음악은 언제나 살아있을 것이다.' },
  { nameKo: '주스 월드', nameEn: 'Juice WRLD', years: '1998–2019', quoteEn: 'We\'re perfectly imperfect.', quoteKo: '우리는 완벽하게 불완전하다.' },
  { nameKo: '주스 월드', nameEn: 'Juice WRLD', years: '1998–2019', quoteEn: 'Words have a lot of power. If you say you\'re gonna do something, do it.', quoteKo: '말에는 큰 힘이 있다. 무언가를 하겠다고 말했다면, 해라.' },
  { nameKo: '텐타시온', nameEn: 'XXXTentacion', years: '1998–2018', quoteEn: 'What is money if I can\'t buy peace of mind?', quoteKo: '마음의 평화를 살 수 없다면 돈이 다 무슨 소용이란 말인가?' },
  { nameKo: '텐타시온', nameEn: 'XXXTentacion', years: '1998–2018', quoteEn: 'The saddest thing about betrayal is that it never comes from your enemies.', quoteKo: '배신에 대해 가장 슬픈 점은, 그것이 결코 적들로부터 오지 않는다는 사실이다.' },
  { nameKo: '텐타시온', nameEn: 'XXXTentacion', years: '1998–2018', quoteEn: 'Your self-worth is determined by you. You don\'t have to depend on someone telling you who you are.', quoteKo: '너의 가치는 네가 결정한다. 누군가가 네가 누구인지 말해주는 것에 의존할 필요는 없다.' },
  { nameKo: '포스트 말론', nameEn: 'Post Malone', years: '1995 ~', quoteEn: 'I\'m just a human being who likes making music.', quoteKo: '나는 그저 음악 만드는 것을 좋아하는 한 인간일 뿐이다.' },
  { nameKo: '포스트 말론', nameEn: 'Post Malone', years: '1995 ~', quoteEn: 'You can\'t get broads if you don\'t got no money.', quoteKo: '돈이 없으면 여자들을 얻을 수 없다.' },
  { nameKo: '포스트 말론', nameEn: 'Post Malone', years: '1995 ~', quoteEn: 'Surround yourself with people who want to see you grow.', quoteKo: '네가 성장하는 모습을 보고 싶어 하는 사람들로 주변을 채워라.' },
  { nameKo: '트래비스 스콧', nameEn: 'Travis Scott', years: '1991 ~', quoteEn: 'I\'m not into making rules, I\'m into breaking them.', quoteKo: '나는 규칙을 만드는 데 관심이 없다. 규칙을 부수는 데 관심이 있지.' },
  { nameKo: '트래비스 스콧', nameEn: 'Travis Scott', years: '1991 ~', quoteEn: 'You can\'t buy the vibe.', quoteKo: '바이브는 돈으로 살 수 없다.' },
  { nameKo: '에이셉 라키', nameEn: 'A$AP Rocky', years: '1988 ~', quoteEn: 'I dress to express, not to impress.', quoteKo: '나는 남에게 잘 보이려고 옷을 입는 게 아니라, 나를 표현하기 위해 입는다.' },
  { nameKo: '에이셉 라키', nameEn: 'A$AP Rocky', years: '1988 ~', quoteEn: 'Everybody has a right to be ugly, but you\'re abusing the privilege.', quoteKo: '모든 사람에게는 못생겨질 권리가 있지만, 넌 그 특권을 남용하고 있구나.' },
  { nameKo: '플레이보이 카티', nameEn: 'Playboi Carti', years: '1996 ~', quoteEn: 'I\'d rather die before I come in last.', quoteKo: '꼴찌를 하느니 차라리 죽는 게 낫다.' },
  { nameKo: '플레이보이 카티', nameEn: 'Playboi Carti', years: '1996 ~', quoteEn: 'If you\'re a king, you don\'t have to say it.', quoteKo: '네가 진짜 왕이라면, 굳이 말로 입증할 필요가 없다.' },
  { nameKo: '아웃카스트 - 안드레 3000', nameEn: 'André 3000', years: '1975 ~', quoteEn: 'The South got something to say.', quoteKo: '남부 힙합도 할 말이 있다고.' },
  { nameKo: '아웃카스트 - 안드레 3000', nameEn: 'André 3000', years: '1975 ~', quoteEn: 'Knowing is half the battle, but doing is the other half.', quoteKo: '아는 것은 전투의 절반일 뿐이고, 행하는 것이 나머지 절반이다.' },
  { nameKo: '로린 힐', nameEn: 'Lauryn Hill', years: '1975 ~', quoteEn: 'We can\'t plan for everything, but we can be ready for anything.', quoteKo: '우리가 모든 것을 계획할 수는 없지만, 무엇이든 맞이할 준비는 되어 있을 수 있다.' },
  { nameKo: '로린 힐', nameEn: 'Lauryn Hill', years: '1975 ~', quoteEn: 'Fantasy is what people want, but reality is what they need.', quoteKo: '환상은 사람들이 원하는 것이지만, 현실은 그들에게 필요한 것이다.' },
  { nameKo: '니키 미나즈', nameEn: 'Nicki Minaj', years: '1982 ~', quoteEn: 'Stay in school. Don\'t ever depend on a man for anything.', quoteKo: '학교 열심히 다녀라. 어떤 일에서든 남자에게 절대 의존하지 마라.' },
  { nameKo: '니키 미나즈', nameEn: 'Nicki Minaj', years: '1982 ~', quoteEn: 'If I am winning, it means you can win too.', quoteKo: '내가 이기고 있다면, 그건 너도 이길 수 있다는 뜻이다.' },
  { nameKo: '니키 미나즈', nameEn: 'Nicki Minaj', years: '1982 ~', quoteEn: 'I\'m a thin girl, but my money is fat.', quoteKo: '난 마른 여자지만, 내 지갑은 뚱뚱해.' },
  { nameKo: '카디 비', nameEn: 'Cardi B', years: '1992 ~', quoteEn: 'Knock me down 9 times but I get up 10.', quoteKo: '아홉 번 나를 쓰러뜨려 봐라, 난 열 번 일어날 테니.' },
  { nameKo: '카디 비', nameEn: 'Cardi B', years: '1992 ~', quoteEn: 'I don\'t care about anyone liking me, I care about my checks.', quoteKo: '누가 날 좋아하든 말든 상관 안 해, 난 내 수표 계좌만 신경 써.' },
  { nameKo: '미시 엘리엇', nameEn: 'Missy Elliott', years: '1971 ~', quoteEn: 'Originality is the key to longevity.', quoteKo: '독창성이야말로 장수의 열쇠다.' },
  { nameKo: '미시 엘리엇', nameEn: 'Missy Elliott', years: '1971 ~', quoteEn: 'I\'ve always been a risk-taker.', quoteKo: '나는 언제나 위험을 감수하는 사람이었다.' },
  { nameKo: '라킴', nameEn: 'Rakim', years: '1968 ~', quoteEn: 'Thinking of a master plan, \'cause ain\'t nothing but sweat inside my hand.', quoteKo: '원대한 계획을 생각하는 중이다, 왜냐하면 지금 내 손안에는 땀밖에 쥔 게 없으니까.' },
  { nameKo: '라킴', nameEn: 'Rakim', years: '1968 ~', quoteEn: 'It ain\'t where you\'re from, it\'s where you\'re at.', quoteKo: '네가 어디 출신인지는 중요하지 않다, 네가 지금 어디에 와 있는지가 중요하지.' },
  { nameKo: '런 디엠씨 - 디엠씨', nameEn: 'DMC', years: '1964 ~', quoteEn: 'Hip hop didn\'t invent anything, hip hop reinvented everything.', quoteKo: '힙합은 그 어떤 것도 새로 발명하지 않았다. 힙합은 모든 것을 \'재발명\'했다.' },
  { nameKo: '퍼블릭 에너미 - 척 디', nameEn: 'Chuck D', years: '1960 ~', quoteEn: 'Rap is the Black CNN.', quoteKo: '랩은 흑인들의 CNN이다.' },
  { nameKo: '퍼블릭 에너미 - 척 디', nameEn: 'Chuck D', years: '1960 ~', quoteEn: 'Don\'t believe the hype.', quoteKo: '과장 광고를 믿지 마라.' },
  { nameKo: '우탱 클랜 - 르자', nameEn: 'RZA', years: '1969 ~', quoteEn: 'Wu-Tang is for the children.', quoteKo: '우탱 클랜은 어린이들을 위한 것입니다.' },
  { nameKo: '우탱 클랜 - 르자', nameEn: 'RZA', years: '1969 ~', quoteEn: 'Wisdom is better than silver and gold.', quoteKo: '지혜는 은이나 금보다 더 낫다.' },
  { nameKo: '우탱 클랜 - 르자', nameEn: 'RZA', years: '1969 ~', quoteEn: 'The environment you are raised in determines how you see the world.', quoteKo: '네가 자란 환경이 네가 세상을 바라보는 방식을 결정한다.' },
  { nameKo: '우탱 클랜 - 메소드 맨', nameEn: 'Method Man', years: '1971 ~', quoteEn: 'Cash rules everything around me, C.R.E.A.M. Get the money, dollar dollar bill y\'all.', quoteKo: '현금이 내 주변의 모든 것을 지배한다. 돈을 벌어라, 모두 달러 지폐를 챙겨.' },
  { nameKo: '메건 더 스탤리언', nameEn: 'Megan Thee Stallion', years: '1995 ~', quoteEn: 'Once you realize your own worth, you will stop handing people discounts.', quoteKo: '너 자신의 가치를 깨닫고 나면, 사람들에게 네 가치를 할인해서 제공하는 짓 따윈 그만두게 될 것이다.' },
  { nameKo: '메건 더 스탤리언', nameEn: 'Megan Thee Stallion', years: '1995 ~', quoteEn: 'I\'m a savage. Classy, bougie, ratchet.', quoteKo: '난 야성적이지. 고급스럽고, 부유하면서도, 거침없어.' },
  { nameKo: '퓨처', nameEn: 'Future', years: '1983 ~', quoteEn: 'If you\'re not in the studio, you\'re losing money.', quoteKo: '녹음실에 앉아있는 게 아니라면, 넌 지금 돈을 잃고 있는 중이다.' },
  { nameKo: '퓨처', nameEn: 'Future', years: '1983 ~', quoteEn: 'Sensational.', quoteKo: '끝내주는군.' },
  { nameKo: '릴 우지 버트', nameEn: 'Lil Uzi Vert', years: '1995 ~', quoteEn: 'I can\'t flex no more, gave my watch to my best friend.', quoteKo: '더 이상 자랑할 수가 없네, 내 시계를 제일 친한 친구한테 줘버려서 말이야.' },
  { nameKo: '릴 우지 버트', nameEn: 'Lil Uzi Vert', years: '1995 ~', quoteEn: 'No matter how dark it gets, the sun will rise again.', quoteKo: '아무리 어두워지더라도, 태양은 다시 떠오를 것이다.' },
  { nameKo: '21 새비지', nameEn: '21 Savage', years: '1992 ~', quoteEn: 'How much money you got? A lot.', quoteKo: '돈 얼마나 갖고 있냐고? 아주 존나게 많이.' },
  { nameKo: '21 새비지', nameEn: '21 Savage', years: '1992 ~', quoteEn: 'I\'d rather be rich and lonely than broke with friends.', quoteKo: '친구 많고 빈털터리인 것보단 차라리 부유하고 외로운 게 낫다.' },
  { nameKo: '제이든 스미스', nameEn: 'Jaden Smith', years: '1998 ~', quoteEn: 'How can mirrors be real if our eyes aren\'t real?', quoteKo: '우리 눈이 진짜가 아니라면 어떻게 거울이 진짜일 수 있겠어?' },
  { nameKo: '맥클모어', nameEn: 'Macklemore', years: '1983 ~', quoteEn: 'One man\'s trash is another man\'s treasure.', quoteKo: '누군가에게는 쓰레기인 것이 다른 누군가에게는 보물이다.' },
  { nameKo: '챈스 더 래퍼', nameEn: 'Chance the Rapper', years: '1993 ~', quoteEn: 'When you completely trust God, you don\'t worry about the outcome.', quoteKo: '네가 완전히 신을 신뢰할 때, 너는 결과에 대해 걱정하지 않게 된다.' },
  { nameKo: '챈스 더 래퍼', nameEn: 'Chance the Rapper', years: '1993 ~', quoteEn: 'We don\'t do the same drugs no more.', quoteKo: '우리는 이제 더 이상 같은 마약을 하지 않아.' },
  { nameKo: '빅 션', nameEn: 'Big Sean', years: '1988 ~', quoteEn: 'I guess it’s true what they say, money can\'t buy happiness. But it can buy a jetski, and have you ever seen a sad person on a jetski?', quoteKo: '돈으로 행복을 살 수 없다는 말은 진짜인 것 같다. 하지만 돈으로 제트스키는 살 수 있지. 제트스키 타면서 슬퍼하는 사람 본 적 있어?' },
  { nameKo: '위즈 칼리파', nameEn: 'Wiz Khalifa', years: '1987 ~', quoteEn: 'Work hard, play hard.', quoteKo: '일할 땐 열심히 일하고, 놀 땐 화끈하게 놀아라.' },
  { nameKo: '위즈 칼리파', nameEn: 'Wiz Khalifa', years: '1987 ~', quoteEn: 'We all want to be successful, but we don\'t all want to work for it.', quoteKo: '우리 모두는 성공하길 원하지만, 모두가 그것을 위해 노력하고 싶어 하지는 않는다.' },
  { nameKo: '릴 디키', nameEn: 'Lil Dicky', years: '1988 ~', quoteEn: 'Save dat money.', quoteKo: '그 돈 좀 아껴라.' },
  { nameKo: '타일라 야웨', nameEn: 'Tyla Yaweh', years: '1995 ~', quoteEn: 'Life is a movie, you are the director.', quoteKo: '인생은 영화다, 네가 바로 감독이다.' },
  { nameKo: '릴 베이비', nameEn: 'Lil Baby', years: '1994 ~', quoteEn: 'I’m the one who’s gotta die when it’s time for me to die, so let me live my life the way I want to.', quoteKo: '내 죽을 때가 되면 죽어야 하는 건 나 자신이다. 그러니 내가 원하는 방식대로 내 인생을 살게 내버려 둬라.' },
  { nameKo: '릴 베이비', nameEn: 'Lil Baby', years: '1994 ~', quoteEn: 'Money bring power, but power bring pain.', quoteKo: '돈은 권력을 가져오지만, 권력은 고통을 가져온다.' },
  { nameKo: '건나', nameEn: 'Gunna', years: '1993 ~', quoteEn: 'Drip or drown.', quoteKo: '멋지게 꾸미거나, 아니면 도태되거나.' },
  { nameKo: '퀘보 - 미고스', nameEn: 'Quavo', years: '1991 ~', quoteEn: 'We started from the bottom, now we\'re in the charts.', quoteKo: '우리는 바닥에서 시작했고, 이제는 차트에 있다.' },
  { nameKo: '스위스 비츠', nameEn: 'Swizz Beatz', years: '1978 ~', quoteEn: 'The sky is not the limit, it\'s just the view.', quoteKo: '하늘은 한계가 아니다, 그저 풍경일 뿐이다.' },
  { nameKo: '루페 피아스코', nameEn: 'Lupe Fiasco', years: '1981 ~', quoteEn: 'You can\'t play the game if you don\'t know the rules.', quoteKo: '규칙을 모른다면 게임을 플레이할 수 없다.' },
  { nameKo: '루페 피아스코', nameEn: 'Lupe Fiasco', years: '1981 ~', quoteEn: 'Don\'t let the uniform define who you are.', quoteKo: '제복이 당신이 누구인지 정의하게 두지 마라.' },
  { nameKo: '에이셉 퍼그', nameEn: 'A$AP Ferg', years: '1988 ~', quoteEn: 'Always strive and prosper.', quoteKo: '언제나 고군분투하고 번창하라.' },
  { nameKo: '디 엠 엑스', nameEn: 'DMX', years: '1970–2021', quoteEn: 'To flooded with wealth is to starve the spirit.', quoteKo: '부유함에 지나치게 침수되는 것은 영혼을 굶주리게 만드는 것이다.' },
] as const;
