/** 기간별 차트 드롭다운 레이아웃 상수 (React 무의존 — 테스트용) */

export const PERIOD_CHART_DROPDOWN_MIN_VISIBLE_OPTIONS = 5;

export const PERIOD_CHART_DROPDOWN_OPTION_ROW_HEIGHT = 52;

export const PERIOD_CHART_DROPDOWN_SHEET_SCROLL_HEIGHT =
  PERIOD_CHART_DROPDOWN_OPTION_ROW_HEIGHT * PERIOD_CHART_DROPDOWN_MIN_VISIBLE_OPTIONS;
