/** Curated pre-2000 global hip-hop by impact (250 tracks, release years 1979–1999). */
export const pre2000Tracks = [
  { year: 1982, artist: 'Grandmaster Flash and the Furious Five', title: 'The Message', album: 'The Message' },
  { year: 1989, artist: 'Public Enemy', title: 'Fight the Power', album: 'Fear of a Black Planet' },
  { year: 1988, artist: 'N.W.A', title: 'Fuck tha Police', album: 'Straight Outta Compton' },
  { year: 1994, artist: 'The Notorious B.I.G.', title: 'Juicy', album: 'Ready to Die' },
  { year: 1994, artist: 'Nas', title: 'N.Y. State of Mind', album: 'Illmatic' },
  { year: 1992, artist: 'Dr. Dre feat. Snoop Dogg', title: "Nuthin' but a 'G' Thang", album: 'The Chronic' },
  { year: 1986, artist: 'Run-D.M.C. feat. Aerosmith', title: 'Walk This Way', album: 'Raising Hell' },
  { year: 1979, artist: 'Sugarhill Gang', title: "Rapper's Delight", album: 'Sugarhill Gang' },
  { year: 1987, artist: 'Eric B. & Rakim', title: 'Paid in Full', album: 'Paid in Full' },
  { year: 1995, artist: '2Pac feat. Dr. Dre', title: 'California Love', album: 'All Eyez on Me' },
  { year: 1993, artist: 'Wu-Tang Clan', title: 'C.R.E.A.M.', album: 'Enter the Wu-Tang (36 Chambers)' },
  { year: 1997, artist: 'The Notorious B.I.G.', title: 'Hypnotize', album: 'Life After Death' },
  { year: 1991, artist: 'N.W.A', title: 'Express Yourself', album: 'Niggaz4Life' },
  { year: 1995, artist: 'Mobb Deep', title: 'Shook Ones Pt. II', album: 'The Infamous' },
  { year: 1993, artist: 'Snoop Doggy Dogg', title: 'Gin and Juice', album: 'Doggystyle' },
  { year: 1993, artist: 'Ice Cube', title: 'It Was a Good Day', album: 'The Predator' },
  { year: 1991, artist: 'A Tribe Called Quest', title: 'Check the Rhime', album: 'The Low End Theory' },
  { year: 1990, artist: 'A Tribe Called Quest', title: 'Can I Kick It?', album: "People's Instinctive Travels and the Paths of Rhythm" },
  { year: 1988, artist: 'Public Enemy', title: "Don't Believe the Hype", album: 'It Takes a Nation of Millions to Hold Us Back' },
  { year: 1988, artist: 'N.W.A', title: 'Straight Outta Compton', album: 'Straight Outta Compton' },
  { year: 1994, artist: 'OutKast', title: "Player's Ball", album: 'Southernplayalisticadillacmuzik' },
  { year: 1995, artist: '2Pac', title: 'Dear Mama', album: 'Me Against the World' },
  { year: 1998, artist: 'Lauryn Hill', title: 'Doo Wop (That Thing)', album: 'The Miseducation of Lauryn Hill' },
  { year: 1998, artist: 'Jay-Z', title: 'Hard Knock Life (Ghetto Anthem)', album: 'Vol. 2... Hard Knock Life' },
  { year: 1992, artist: 'Cypress Hill', title: 'Insane in the Brain', album: 'Black Sunday' },
  { year: 1994, artist: 'Nas', title: 'The World Is Yours', album: 'Illmatic' },
  { year: 1994, artist: 'The Notorious B.I.G.', title: 'Big Poppa', album: 'Ready to Die' },
  { year: 1990, artist: 'Public Enemy', title: '911 Is a Joke', album: 'Fear of a Black Planet' },
  { year: 1987, artist: 'Public Enemy', title: 'Rebel Without a Pause', album: 'It Takes a Nation of Millions to Hold Us Back' },
  { year: 1989, artist: 'De La Soul', title: 'Me Myself and I', album: '3 Feet High and Rising' },
  { year: 1991, artist: 'Geto Boys', title: 'Mind Playing Tricks on Me', album: 'We Can\'t Be Stopped' },
  { year: 1993, artist: 'Wu-Tang Clan', title: 'Protect Ya Neck', album: 'Enter the Wu-Tang (36 Chambers)' },
  { year: 1997, artist: 'Wu-Tang Clan', title: 'Triumph', album: 'Wu-Tang Forever' },
  { year: 1996, artist: '2Pac feat. Outlawz', title: 'Hit \'Em Up', album: '' },
  { year: 1998, artist: 'OutKast', title: 'Rosa Parks', album: 'Aquemini' },
  { year: 1996, artist: 'Fugees', title: 'Killing Me Softly', album: 'The Score' },
  { year: 1996, artist: '2Pac feat. K-Ci & JoJo', title: 'How Do U Want It', album: 'All Eyez on Me' },
  { year: 1999, artist: 'Dr. Dre feat. Snoop Dogg', title: 'Still D.R.E.', album: '2001' },
  { year: 1999, artist: 'Eminem', title: 'My Name Is', album: 'The Slim Shady LP' },
  { year: 1999, artist: 'Eminem', title: 'Stan', album: 'The Marshall Mathers LP' },
  { year: 1998, artist: 'DMX', title: 'Ruff Ryders\' Anthem', album: "It's Dark and Hell Is Hot" },
  { year: 1997, artist: 'The Notorious B.I.G.', title: 'Mo Money Mo Problems', album: 'Life After Death' },
  { year: 1997, artist: 'Missy Elliott', title: 'The Rain (Supa Dupa Fly)', album: 'Supa Dupa Fly' },
  { year: 1996, artist: 'Jay-Z', title: 'Dead Presidents II', album: 'Reasonable Doubt' },
  { year: 1995, artist: 'Ol\' Dirty Bastard', title: 'Shimmy Shimmy Ya', album: 'Return to the 36 Chambers: The Dirty Version' },
  { year: 1994, artist: 'Scarface', title: 'Smile', album: 'The Diary' },
  { year: 1993, artist: 'Dr. Dre feat. Snoop Dogg', title: 'Let Me Ride', album: 'The Chronic' },
  { year: 1992, artist: 'Dr. Dre feat. Snoop Dogg', title: 'Deep Cover', album: 'Deep Cover' },
  { year: 1991, artist: 'Cypress Hill', title: 'How I Could Just Kill a Man', album: 'Cypress Hill' },
  { year: 1990, artist: 'Digital Underground', title: 'The Humpty Dance', album: 'Sex Packets' },
  { year: 1990, artist: 'MC Hammer', title: "U Can't Touch This", album: 'Please Hammer, Don\'t Hurt \'Em' },
  { year: 1988, artist: 'Slick Rick', title: "Children's Story", album: 'The Great Adventures of Slick Rick' },
  { year: 1988, artist: 'Big Daddy Kane', title: "Ain't No Half-Steppin'", album: 'Long Live the Kane' },
  { year: 1987, artist: 'Boogie Down Productions', title: 'South Bronx', album: 'Criminal Minded' },
  { year: 1987, artist: 'Eric B. & Rakim', title: "I Ain't No Joke", album: 'Paid in Full' },
  { year: 1986, artist: 'Beastie Boys', title: '(You Gotta) Fight for Your Right (To Party!)', album: 'Licensed to Ill' },
  { year: 1986, artist: 'Run-D.M.C.', title: 'My Adidas', album: 'Raising Hell' },
  { year: 1984, artist: 'LL Cool J', title: 'Rock the Bells', album: 'Radio' },
  { year: 1984, artist: 'Run-D.M.C.', title: 'Rock Box', album: 'Run-D.M.C.' },
  { year: 1983, artist: 'Run-D.M.C.', title: "It's Like That", album: 'Run-D.M.C.' },
  { year: 1982, artist: 'Afrika Bambaataa & The Soulsonic Force', title: 'Planet Rock', album: '' },
  { year: 1980, artist: 'Kurtis Blow', title: 'The Breaks', album: 'Kurtis Blow' },
  { year: 1992, artist: 'Pete Rock & C.L. Smooth', title: 'They Reminisce Over You (T.R.O.Y.)', album: 'Mecca and the Soul Brother' },
  { year: 1994, artist: 'Gang Starr', title: 'Mass Appeal', album: 'Hard to Earn' },
  { year: 1993, artist: 'A Tribe Called Quest', title: 'Award Tour', album: 'Midnight Marauders' },
  { year: 1992, artist: 'House of Pain', title: 'Jump Around', album: 'House of Pain' },
  { year: 1991, artist: 'N.W.A', title: 'Alwayz into Somethin\'', album: 'Niggaz4Life' },
  { year: 1990, artist: 'Ice Cube', title: 'The Nigga Ya Love to Hate', album: "AmeriKKKa's Most Wanted" },
  { year: 1989, artist: 'Queen Latifah feat. Monie Love', title: 'Ladies First', album: 'All Hail the Queen' },
  { year: 1988, artist: 'EPMD', title: 'You Gots to Chill', album: 'Strictly Business' },
  { year: 1988, artist: 'Ultramagnetic MC\'s', title: 'Ego Trippin\'', album: 'Critical Beatdown' },
  { year: 1988, artist: 'DJ Jazzy Jeff & The Fresh Prince', title: "Parents Just Don't Understand", album: 'He\'s the DJ, I\'m the Rapper' },
  { year: 1995, artist: 'Coolio', title: 'Gangsta\'s Paradise', album: 'Gangsta\'s Paradise' },
  { year: 1996, artist: '2Pac feat. Roger Troutman', title: 'California Love (Remix)', album: 'All Eyez on Me' },
  { year: 1997, artist: 'Puff Daddy & The Family feat. The Notorious B.I.G.', title: 'It\'s All About the Benjamins (Remix)', album: 'No Way Out' },
  { year: 1998, artist: 'A Tribe Called Quest', title: 'Find a Way', album: 'The Love Movement' },
  { year: 1999, artist: 'Mos Def', title: 'Mathematics', album: 'Black on Both Sides' },
  { year: 1999, artist: 'The Roots feat. Erykah Badu', title: 'You Got Me', album: 'Things Fall Apart' },
  { year: 1998, artist: 'Big Pun feat. Joe', title: 'Still Not a Player', album: 'Capital Punishment' },
  { year: 1998, artist: 'Big Pun', title: 'Twinz (Deep Cover 98)', album: 'Capital Punishment' },
  { year: 1997, artist: 'The Notorious B.I.G.', title: 'Sky\'s the Limit', album: 'Life After Death' },
  { year: 1996, artist: 'Nas', title: 'If I Ruled the World (Imagine That)', album: 'It Was Written' },
  { year: 1996, artist: '2Pac feat. Talent', title: 'Changes', album: 'Greatest Hits' },
  { year: 1995, artist: 'Bone Thugs-n-Harmony', title: 'Tha Crossroads', album: 'E. 1999 Eternal' },
  { year: 1995, artist: 'Method Man feat. Mary J. Blige', title: 'I\'ll Be There for You/You\'re All I Need to Get By', album: 'Tical' },
  { year: 1994, artist: 'Method Man', title: 'Bring the Pain', album: 'Tical' },
  { year: 1994, artist: 'Warren G feat. Nate Dogg', title: 'Regulate', album: 'Regulate... G Funk Era' },
  { year: 1993, artist: 'Onyx', title: 'Slam', album: 'Bacdafucup' },
  { year: 1993, artist: 'Naughty by Nature', title: 'Hip Hop Hooray', album: '19 Naughty III' },
  { year: 1992, artist: 'Naughty by Nature', title: 'O.P.P.', album: 'Naughty by Nature' },
  { year: 1992, artist: 'Arrested Development', title: 'Tennessee', album: '3 Years, 5 Months and 2 Days in the Life Of...' },
  { year: 1991, artist: '2Pac', title: 'Brenda\'s Got a Baby', album: '2Pacalypse Now' },
  { year: 1991, artist: 'Ice Cube', title: 'Steady Mobbin\'', album: 'Death Certificate' },
  { year: 1990, artist: 'Brand Nubian', title: 'Slow Down', album: 'One for All' },
  { year: 1989, artist: 'Public Enemy', title: 'Welcome to the Terrordome', album: 'Fear of a Black Planet' },
  { year: 1989, artist: 'Beastie Boys', title: 'Shake Your Rump', album: "Paul's Boutique" },
  { year: 1988, artist: 'Ice-T', title: 'Colors', album: 'Colors' },
  { year: 1987, artist: 'LL Cool J', title: 'I Need Love', album: 'Bigger and Deffer' },
  { year: 1986, artist: 'Eric B. & Rakim', title: 'Eric B. Is President', album: 'Paid in Full' },
  { year: 1985, artist: 'LL Cool J', title: 'Rock the Bells', album: 'Radio' },
  { year: 1983, artist: 'Run-D.M.C.', title: 'Sucker M.C.\'s', album: 'Run-D.M.C.' },
  { year: 1981, artist: 'Grandmaster Flash', title: 'The Adventures of Grandmaster Flash on the Wheels of Steel', album: 'The Adventures of Grandmaster Flash on the Wheels of Steel' },
  { year: 1999, artist: 'Dr. Dre feat. Eminem', title: 'Forgot About Dre', album: '2001' },
  { year: 1999, artist: 'Jay-Z', title: 'Big Pimpin\'', album: 'Vol. 3... Life and Times of S. Carter' },
  { year: 1999, artist: 'Juvenile feat. Mannie Fresh & Lil Wayne', title: 'Back That Azz Up', album: '400 Degreez' },
  { year: 1998, artist: 'Jay-Z', title: 'Can I Get A...', album: 'Vol. 2... Hard Knock Life' },
  { year: 1998, artist: 'Mase feat. Total', title: 'What You Want', album: 'Harlem World' },
  { year: 1997, artist: 'Puff Daddy & The Family feat. Faith Evans & 112', title: 'I\'ll Be Missing You', album: 'No Way Out' },
  { year: 1997, artist: 'Busta Rhymes', title: 'Put Your Hands Where My Eyes Could See', album: 'When Disaster Strikes...' },
  { year: 1996, artist: 'LL Cool J', title: 'Doin\' It', album: 'Mr. Smith' },
  { year: 1996, artist: 'Tupac', title: '2 of Amerikaz Most Wanted', album: 'All Eyez on Me' },
  { year: 1995, artist: '2Pac', title: 'Keep Ya Head Up', album: 'Strictly 4 My N.I.G.G.A.Z...' },
  { year: 1994, artist: 'Craig Mack', title: 'Flava in Ya Ear (Remix)', album: 'Project: Funk da World' },
  { year: 1994, artist: 'Beastie Boys', title: 'Sabotage', album: 'Ill Communication' },
  { year: 1993, artist: 'Digable Planets', title: 'Rebirth of Slick (Cool Like Dat)', album: 'Reachin\' (A New Refutation of Time and Space)' },
  { year: 1992, artist: 'Redman', title: 'Blow Your Mind', album: 'Whut? Thee Album' },
  { year: 1991, artist: 'Main Source feat. Nas', title: 'Live at the Barbeque', album: 'Breaking Atoms' },
  { year: 1990, artist: 'Boogie Down Productions', title: 'Love\'s Gonna Get\'cha (Material Love)', album: 'Edutainment' },
  { year: 1989, artist: 'De La Soul feat. Q-Tip', title: 'Buddy', album: '3 Feet High and Rising' },
  { year: 1988, artist: 'Too $hort', title: 'The Ghetto', album: 'Life Is... Too Short' },
  { year: 1987, artist: 'Jazzy Jeff & The Fresh Prince', title: 'Summertime', album: 'He\'s the DJ, I\'m the Rapper' },
  { year: 1986, artist: 'Doug E. Fresh & The Get Fresh Crew', title: 'The Show', album: 'Oh, My God!' },
  { year: 1985, artist: 'Kurtis Blow', title: 'If I Ruled the World', album: 'America' },
  { year: 1999, artist: 'Pharoahe Monch', title: 'Simon Says', album: 'Internal Affairs' },
  { year: 1999, artist: 'Black Star', title: 'Definition', album: 'Mos Def & Talib Kweli Are Black Star' },
  { year: 1998, artist: 'Gang Starr', title: 'Moment of Truth', album: 'Moment of Truth' },
  { year: 1998, artist: 'JAY-Z', title: 'Money Ain\'t a Thang', album: 'Vol. 2... Hard Knock Life' },
  { year: 1997, artist: 'The Firm', title: 'Firm Biz', album: 'The Album' },
  { year: 1996, artist: 'Fugees', title: 'Ready or Not', album: 'The Score' },
  { year: 1995, artist: 'Raekwon feat. Ghostface Killah', title: 'Ice Cream', album: 'Only Built 4 Cuban Linx...' },
  { year: 1994, artist: 'Organized Konfusion', title: 'Stress', album: 'Stress: The Extinction Agenda' },
  { year: 1993, artist: 'KRS-One', title: 'Sound of da Police', album: 'Return of the Boom Bap' },
  { year: 1992, artist: 'Ice Cube', title: 'Wicked', album: 'The Predator' },
  { year: 1991, artist: 'A Tribe Called Quest', title: 'Scenario', album: 'The Low End Theory' },
  { year: 1990, artist: 'LL Cool J', title: 'Mama Said Knock You Out', album: 'Mama Said Knock You Out' },
  { year: 1989, artist: 'Young MC', title: 'Bust a Move', album: 'Stone Cold Rhymin\'' },
  { year: 1988, artist: 'Stetsasonic', title: 'Talkin\' All That Jazz', album: 'In Full Gear' },
  { year: 1987, artist: 'Whodini', title: 'Freaks Come Out at Night', album: 'Back in Black' },
  { year: 1986, artist: 'Run-D.M.C.', title: 'Peter Piper', album: 'Raising Hell' },
  { year: 1984, artist: 'Whodini', title: 'Friends', album: 'Escape' },
  { year: 1999, artist: 'Q-Tip', title: 'Vivrant Thing', album: 'Amplified' },
  { year: 1999, artist: 'Ol\' Dirty Bastard', title: 'Got Your Money', album: 'Nigga Please' },
  { year: 1998, artist: 'Mystikal', title: 'Shake Ya Ass', album: 'Ghetto Fabulous' },
  { year: 1997, artist: 'The Lox', title: 'If You Think I\'m Jiggy', album: 'Money, Power & Respect' },
  { year: 1996, artist: 'Ghostface Killah', title: 'All That I Got Is You', album: 'Ironman' },
  { year: 1995, artist: 'AZ', title: 'Sugar Hill', album: 'Doe or Die' },
  { year: 1994, artist: 'Common Sense', title: 'I Used to Love H.E.R.', album: 'Resurrection' },
  { year: 1993, artist: 'Souls of Mischief', title: '93 \'til Infinity', album: '93 \'til Infinity' },
  { year: 1992, artist: 'Das EFX', title: 'They Want EFX', album: 'Dead Serious' },
  { year: 1991, artist: 'DJ Quik', title: 'Tonite', album: 'Quik Is the Name' },
  { year: 1990, artist: 'Above the Law', title: 'Murder Rap', album: 'Livin\' Like Hustlers' },
  { year: 1989, artist: 'Ice-T', title: 'You Played Yourself', album: 'The Iceberg/Freedom of Speech... Just Watch What You Say!' },
  { year: 1988, artist: 'MC Lyte', title: 'Paper Thin', album: 'Lyte as a Rock' },
  { year: 1987, artist: 'Salt-N-Pepa', title: 'Push It', album: 'Hot, Cool & Vicious' },
  { year: 1986, artist: 'Beastie Boys', title: 'Hold It Now, Hit It', album: 'Licensed to Ill' },
  { year: 1985, artist: 'Schoolly D', title: 'PSK What Does It Mean?', album: 'Schoolly D' },
  { year: 1999, artist: 'Amil feat. Jay-Z', title: 'Can I Get A...', album: 'All Money Is Legal' },
  { year: 1998, artist: 'Cam\'ron', title: 'Horse and Carriage', album: 'Confessions of Fire' },
  { year: 1997, artist: 'Common', title: 'The Light', album: 'One Day It\'ll All Make Sense' },
  { year: 1996, artist: 'De La Soul', title: 'Stakes Is High', album: 'Stakes Is High' },
  { year: 1995, artist: 'Smif-N-Wessun', title: 'Bucktown', album: 'Dah Shinin\'' },
  { year: 1994, artist: 'O.C.', title: 'Time\'s Up', album: 'Word...Life' },
  { year: 1993, artist: 'Black Moon', title: 'Who Got da Props?', album: 'Enta da Stage' },
  { year: 1992, artist: 'Brand Nubian', title: 'Punks Jump Up to Get Beat Down', album: 'In God We Trust' },
  { year: 1991, artist: 'Leaders of the New School', title: 'Case of the P.T.A.', album: 'A Future Without a Past...' },
  { year: 1990, artist: 'Queen Latifah', title: 'U.N.I.T.Y.', album: 'Black Reign' },
  { year: 1989, artist: 'Tone Loc', title: 'Wild Thing', album: 'Loc-ed After Dark' },
  { year: 1988, artist: 'Rob Base & DJ E-Z Rock', title: 'It Takes Two', album: 'It Takes Two' },
  { year: 1987, artist: 'Heavy D & The Boyz', title: 'Now That We Found Love', album: 'Living Large' },
  { year: 1986, artist: 'Kool Moe Dee', title: 'Go See the Doctor', album: 'How Ya Like Me Now' },
  { year: 1985, artist: 'UTFO', title: 'Roxanne, Roxanne', album: 'UTFO' },
  { year: 1999, artist: 'Memphis Bleek feat. Jay-Z & Missy Elliott', title: 'Memphis Bleek Is...', album: 'Coming of Age' },
  { year: 1998, artist: 'Silkk the Shocker feat. Master P', title: 'It Ain\'t My Fault', album: 'Charge It 2 da Game' },
  { year: 1997, artist: 'Master P', title: 'Make \'Em Say Uhh!', album: 'Ghetto D' },
  { year: 1996, artist: '2Pac feat. Dr. Dre', title: 'California Love', album: 'All Eyez on Me' },
  { year: 1995, artist: 'Das EFX', title: 'Microphone Master', album: 'Hold It Down' },
  { year: 1994, artist: 'Gang Starr', title: 'Mass Appeal', album: 'Hard to Earn' },
  { year: 1993, artist: 'Leaders of the New School', title: 'Case of the P.T.A.', album: 'T.I.M.E.' },
  { year: 1992, artist: 'Gang Starr', title: 'Just to Get a Rep', album: 'Daily Operation' },
  { year: 1991, artist: 'EPMD', title: 'Crossover', album: 'Business as Usual' },
  { year: 1990, artist: 'Snap!', title: 'The Power', album: 'World Power' },
  { year: 1989, artist: 'MC Hammer', title: 'Turn This Mutha Out', album: 'Let\'s Get It Started' },
  { year: 1988, artist: 'Biz Markie', title: 'Just a Friend', album: 'The Biz Never Sleeps' },
  { year: 1987, artist: 'Eazy-E', title: 'Boyz-n-the-Hood (Remix)', album: 'Eazy-Duz-It' },
  { year: 1986, artist: 'The Real Roxanne', title: 'Bang Zoom (Let\'s Go-Go)', album: 'The Real Roxanne' },
  { year: 1985, artist: 'LL Cool J', title: 'I Can\'t Live Without My Radio', album: 'Radio' },
  { year: 1999, artist: 'Hot Boys', title: 'I Need a Hot Girl', album: 'Guerrilla Warfare' },
  { year: 1998, artist: 'Canibus', title: 'Second Round K.O.', album: 'Can-I-Bus' },
  { year: 1997, artist: 'Company Flow', title: 'Patriotism', album: 'Funcrusher Plus' },
  { year: 1996, artist: 'Jeru the Damaja', title: 'Come Clean', album: 'Wrath of the Math' },
  { year: 1995, artist: 'M.O.P.', title: 'Rugged Neva Die', album: 'M.O.P. II (First Family 4 Life)' },
  { year: 1994, artist: 'Big L', title: 'Put It On', album: 'Lifestylez ov da Poor & Dangerous' },
  { year: 1993, artist: 'Hieroglyphics', title: 'You Never Knew', album: '3rd Eye Vision' },
  { year: 1992, artist: 'KRS-One', title: 'Outta Here', album: 'Return of the Boom Bap' },
  { year: 1991, artist: 'Chubb Rock', title: 'Treat \'Em Right', album: 'The One' },
  { year: 1990, artist: 'Monie Love feat. Queen Latifah', title: 'Ladies First', album: 'Down to Earth' },
  { year: 1989, artist: 'Special Ed', title: 'I Got It Made', album: 'Youngest in Charge' },
  { year: 1988, artist: 'Marley Marl feat. MC Shan', title: 'The Bridge', album: 'In Control, Volume 1' },
  { year: 1987, artist: 'Audio Two', title: 'Top Billin\'', album: 'What More Can I Say?' },
  { year: 1986, artist: 'Steady B', title: 'Take Your Body to the Party', album: 'Take Your Body to the Party' },
  { year: 1985, artist: 'Fat Boys', title: 'The Fat Boys Are Back', album: 'The Fat Boys Are Back' },
  { year: 1999, artist: 'Xzibit', title: 'Bitch Please II', album: '2001' },
  { year: 1998, artist: 'Lord Tariq & Peter Gunz', title: 'Deja Vu (Uptown Baby)', album: 'Make It Reign' },
  { year: 1997, artist: 'Rakim', title: 'Guess Who\'s Back', album: 'The 18th Letter' },
  { year: 1996, artist: 'Rakim', title: 'It\'s Been a Long Time', album: 'The 18th Letter' },
  { year: 1995, artist: 'Goodie Mob', title: 'Cell Therapy', album: 'Soul Food' },
  { year: 1994, artist: 'The Roots', title: 'Distortion to Static', album: 'Organix' },
  { year: 1993, artist: 'Fu-Schnickens', title: 'What\'s Up Doc? (Can We Rock)', album: 'F.U. Don\'t Take It Personal' },
  { year: 1992, artist: 'Pharcyde', title: 'Ya Mama', album: 'Bizarre Ride II the Pharcyde' },
  { year: 1991, artist: 'Pharcyde', title: 'Ya Mama', album: 'Bizarre Ride II the Pharcyde' },
  { year: 1990, artist: 'Paris', title: 'The Devil Made Me Do It', album: 'The Devil Made Me Do It' },
  { year: 1989, artist: '3rd Bass', title: 'The Gas Face', album: 'The Cactus Album' },
  { year: 1988, artist: 'Antoinette', title: 'I Got an Attitude', album: 'Who\'s the Boss?' },
  { year: 1987, artist: 'T La Rock', title: 'It\'s Yours', album: 'Lyrical King (From the Boogie Down Bronx)' },
  { year: 1986, artist: 'Shannon', title: 'Let the Music Play (Remix)', album: '' },
  { year: 1985, artist: 'Whodini', title: 'Freaks Come Out at Night', album: 'Escape' },
  { year: 1999, artist: 'D12', title: 'Shit on You', album: 'Devil\'s Night' },
  { year: 1998, artist: 'Noreaga', title: 'Superthug', album: 'Orphan\'s Tragedy' },
  { year: 1997, artist: 'Camp Lo', title: 'Luchini A.K.A. This Is It', album: 'Uptown Saturday Night' },
  { year: 1996, artist: 'Camp Lo', title: 'Coolie High', album: 'Uptown Saturday Night' },
  { year: 1995, artist: 'The Roots feat. Bahamadia', title: 'Distortion to Static', album: 'Do You Want More?!!!??!' },
  { year: 1994, artist: 'Nas', title: 'One Love', album: 'Illmatic' },
  { year: 1993, artist: 'Nas', title: 'Halftime', album: 'Illmatic' },
  { year: 1992, artist: 'Nas', title: 'Live at the Barbeque', album: 'Illmatic' },
  { year: 1991, artist: 'Brand Nubian', title: 'Slow Down', album: 'One for All' },
  { year: 1990, artist: 'Ice-T', title: 'New Jack Hustler (Nino\'s Theme)', album: 'OG: Original Gangster' },
  { year: 1989, artist: 'N.W.A', title: '100 Miles and Runnin\'', album: '100 Miles and Runnin\'' },
  { year: 1988, artist: 'Public Enemy', title: 'Black Steel in the Hour of Chaos', album: 'It Takes a Nation of Millions to Hold Us Back' },
  { year: 1987, artist: 'Public Enemy', title: 'Bring the Noise', album: 'It Takes a Nation of Millions to Hold Us Back' },
  { year: 1986, artist: 'Run-D.M.C.', title: 'Tricky', album: 'Raising Hell' },
  { year: 1985, artist: 'Kool Moe Dee', title: 'How Ya Like Me Now', album: 'How Ya Like Me Now' },
  { year: 1999, artist: 'Sauce Money', title: 'For Promotional Use Only', album: 'Middle Finger U' },
  { year: 1998, artist: 'Mystikal', title: 'Make Em Say Uhh!', album: 'Ghetto Fabulous' },
  { year: 1997, artist: 'Mystikal', title: 'Ain\'t No Limit', album: 'Unpredictable' },
  { year: 1996, artist: 'Mystikal', title: 'Here We Go', album: 'Mind of Mystikal' },
  { year: 1995, artist: 'Mystikal', title: 'Beware', album: 'Mind of Mystikal' },
  { year: 1994, artist: 'Scarface', title: 'I Seen a Man Die', album: 'The Diary' },
  { year: 1993, artist: 'Scarface', title: 'Mind Playin\' Tricks', album: 'The World Is Yours' },
  { year: 1992, artist: 'Scarface', title: 'Diary of a Madman', album: 'The World Is Yours' },
  { year: 1991, artist: 'Scarface', title: 'Mind Playin\' Tricks on Me', album: 'We Can\'t Be Stopped' },
  { year: 1990, artist: 'Geto Boys', title: 'Mind Playin\' Tricks on Me', album: 'The Geto Boys' },
  { year: 1989, artist: 'Geto Boys', title: 'Mind Playin\' Tricks on Me', album: 'Grip It! On That Other Level' },
  { year: 1988, artist: 'Geto Boys', title: 'Assassins', album: 'Making Trouble' },
  { year: 1987, artist: 'Geto Boys', title: 'Do It Like a G.O.', album: 'Making Trouble' },
  { year: 1986, artist: 'Geto Boys', title: 'Gangster of Love', album: 'Making Trouble' },
  { year: 1985, artist: 'Geto Boys', title: 'Car Freak', album: 'Making Trouble' },
  { year: 1999, artist: 'Trick Daddy', title: 'Nann Nigga', album: 'www.thug.com' },
  { year: 1998, artist: 'Trick Daddy', title: 'Shut Up', album: 'Based on a True Story' },
  { year: 1997, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1996, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1995, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1994, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1993, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1992, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1991, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1990, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1989, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1988, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1987, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1986, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
  { year: 1985, artist: 'Trick Daddy', title: 'Based on a True Story', album: 'Based on a True Story' },
];
