TRACKS = [
    ('Zico', "What's Wrong?", "What's Wrong?"),
    ('Crush', 'WooAh', 'From Midnight to Sunrise'),
    ('Crush', "Fallin'", 'From Midnight to Sunrise'),
    ('Crush', 'From Midnight to Sunrise', 'From Midnight to Sunrise'),
    ('Crush', 'Mayday', 'From Midnight to Sunrise'),
    ('Crush', 'Wake Up', 'From Midnight to Sunrise'),
    ('Heize', 'HAPPEN', 'HAPPEN'),
    ('Heize', 'Undo', 'HAPPEN'),
    ('Heize', 'Can You See My Heart', 'HAPPEN'),
    ('Heize', 'Run to You', 'HAPPEN'),
    ('Dean', 'Pompeii', ''),
    ('Dean', 'DMT', ''),
    ('Sik-K', 'FL1X', 'FL1X'),
    ('Sik-K', 'NEONBEAM', 'FL1X'),
    ('Sik-K', 'WATER', 'FL1X'),
    ('Sik-K', 'LOVEADICT', 'FL1X'),
    ('Sik-K', 'Donut 2', 'FL1X'),
    ('Giriboy', 'Engineering', 'Engineering'),
    ('Giriboy', 'PlanetariuM', 'Engineering'),
    ('Swings', 'Upgrade III', 'Upgrade III'),
    ('Swings', 'V', 'Upgrade III'),
    ('Swings', 'Brand New Day', 'Upgrade III'),
    ('Mino', 'Trigger', 'XX'),
    ('Mino', 'Fiancé', 'XX'),
    ('Mino', 'XX', 'XX'),
    ('Mino', 'Uh Ahchoo', 'XX'),
    ('Loco', 'Hero', 'Hero'),
    ('Loco', 'Some', 'Hero'),
    ('Loco', 'Oceans', 'Hero'),
    ('Loco', 'Waiting For Love', 'Hero'),
    ('Gray', 'Tik Tak Tok', ''),
    ('Coogie', 'Coogie', 'Coogie'),
    ('Coogie', "Bouncin'", 'Coogie'),
    ('Coogie', 'Wifey', 'Emo #1'),
    ('Coogie', 'GPS', 'Emo #1'),
    ('Coogie', 'Glow', ''),
    ('Coogie', "I'mma Do", ''),
    ('HAON', 'Travel', 'Penumbra'),
    ('HAON', 'Blue', 'Penumbra'),
    ('HAON', 'Blossom', 'Penumbra'),
    ('Ash Island', 'Malibu', 'Ash Island'),
    ('Ash Island', 'Limousine Vision', 'Ash Island'),
    ('Ash Island', 'Howling', 'Ash Island'),
    ('Leellamarz', 'Don`t Call Me', 'To Be Continued'),
    ('Leellamarz', 'Profile', 'To Be Continued'),
    ('TOIL', '1989', '1989'),
    ('TOIL', 'Money', '1989'),
    ('TOIL', 'Rollin', '1989'),
    ('Woodie Gochild', 'Mood Swings', '#GOchild'),
    ('Woodie Gochild', 'Dirtbag', '#GOchild'),
    ('Woodie Gochild', 'GOchild', '#GOchild'),
    ('Jvcki Wai', 'Doughnet', 'Exposure'),
    ('Jvcki Wai', 'Neo Eve', 'Exposure'),
    ('Punchnello', 'Cool', 'Cool'),
    ('Tablo', 'Fantasy', 'Drill Presents: Tablo x Fantasy'),
    ('Tablo', 'Drill Presents', 'Drill Presents: Tablo x Fantasy'),
    ('Paloalto', 'Shangri-La', 'Shangri-La'),
    ('Simon Dominic', 'NO OPEN FLAME', 'NO OPEN FLAME'),
    ('Simon Dominic', 'ART OF PARTYING', 'NO OPEN FLAME'),
    ('Jay Park', 'Likes', ''),
    ('Jay Park', "Can't Be Saved", ''),
    ('Nafla', 'Natural Born Killers', 'Natural Born Killers'),
    ('Loopy', 'King Loopy', 'King Loopy'),
    ('Kid Milli', 'Yellow', 'Maiden Voyage'),
    ('PH-1', 'Homebody', 'YIN YANG'),
    ('Blase', 'Blue', ''),
    ('Mirani', 'Ticket', 'Ticket'),
    ('YUMDDA', 'Tic Toc', "I'm Good"),
    ('Jessi', 'Gucci', 'Show Me the Money 777'),
    ('D.Ark', 'Undercover', 'Show Me the Money 777'),
    ('D.Ark', 'Genius', 'Show Me the Money 777'),
    ('Zico', 'Any Song', ''),
    ('Zico', 'SoulMate', ''),
    ('Epik High', 'Rosario', 'Sleepless in __________'),
    ('Swings', 'Growing Pains 2', 'Growing Pains 2'),
    ('Sokodomo', 'Merry Go Round', 'Merry Go Round'),
    ('Owen Ovadoz', 'Drama', 'Drama'),
    ('Lil Moshpit', 'MOSHPIT', 'MOSHPIT'),
    ('Gaeko', 'Gajah', 'Gajah'),
    ('San E', 'a SONG of ICE and FIRE', 'a SONG of ICE and FIRE'),
    ('E-Sens', 'Gold', 'The Anecdote'),
    ('Leellamarz', 'Wavy', ''),
    ('Mirani', 'Bayer Dynamic', 'Ticket'),
    ('Blase', 'Love Me', 'Passionfruit'),
    ('Blase', 'Ride', 'Passionfruit'),
    ('TOIL', 'ON FIRE', '1989'),
    ('TOIL', 'Switch', '1989'),
    ('HAON', 'Swervin', 'ISLAND'),
    ('Ash Island', 'ISLAND', 'ISLAND'),
    ('Giriboy', 'heat', 'heat'),
    ('Changmo', 'Ghetto Kids', 'Ghetto Kids'),
    ('Nafla', 'C.R.E.A.M', 'C.R.E.A.M'),
    ('Kid Milli', 'BEANie', 'BEANie'),
    ('Woodie Gochild', 'Channel', '#GOchild'),
    ('Mudd the student', 'Sleepy Beauty', ''),
    ('Lil Boi', 'Empty Head', ''),
    ('Jvcki Wai', 'Taxi Blurr', 'Taxi Blurr'),
    ('Giriboy', 'Mechanical Album', 'Mechanical Album'),
    ('Sik-K', 'MAKE OUT', 'MAKE OUT'),
    ('Kid Milli', 'SIT', 'BEANie'),
]
