TRACKS = [
    ('E-Sens', 'Dice', 'The Anecdote'),
    ('E-Sens', 'A-G-E', 'The Anecdote'),
    ('E-Sens', "Writer's Block", 'The Anecdote'),
    ('E-Sens', 'Next Level', 'The Anecdote'),
    ('E-Sens', 'Wobble', 'The Anecdote'),
    ('E-Sens', '10.18.14', 'The Anecdote'),
    ('E-Sens', 'The Anecdote', 'The Anecdote'),
    ('E-Sens', 'Tick Tock', 'The Anecdote'),
    ('E-Sens', 'Unknown Verses', 'The Anecdote'),
    ('Dean', 'I Love It', ''),
    ('Dean', 'Pour Up', ''),
    ('Dean', 'Bonnie & Clyde', ''),
    ('Heize', 'And July', 'And July'),
    ('Heize', 'Because You', 'And July'),
    ('Heize', 'Underwater', 'And July'),
    ('Heize', 'No Way', 'And July'),
    ('Crush', 'Just', ''),
    ('Crush', 'Oasis', 'Crush on You'),
    ('Jay Park', 'WORLDWIDE', 'Worldwide'),
    ('Jay Park', "Don't Try Me", 'Worldwide'),
    ('Jay Park', 'My Last', 'Worldwide'),
    ('Jay Park', 'FAKE LOVE', 'Worldwide'),
    ('Jay Park', 'YOU KNOW', 'Worldwide'),
    ('Jay Park', 'WHEN', 'Worldwide'),
    ('Jay Park', 'Want It', 'Worldwide'),
    ('Jay Park', 'MY', 'Worldwide'),
    ('Jay Park', 'B-BOY STANCE', 'Worldwide'),
    ('Jay Park', 'LOTTO', 'Worldwide'),
    ('Jay Park', 'In This B*tch', 'Worldwide'),
    ('Jay Park', 'ON IT', 'Worldwide'),
    ('Jay Park', 'SEATTLE 2 SEOUL', 'Worldwide'),
    ('Jay Park', 'All I Wanna Do', 'Worldwide'),
    ('Zion.T', 'Complex', ''),
    ('Zion.T', 'No Make Up', ''),
    ('Beenzino', 'So What', ''),
    ('Beenzino', 'Break', '12'),
    ('Beenzino', 'We Are Going To', '12'),
    ('Dynamic Duo', 'Grand Carnival', 'Grand Carnival'),
    ('Dynamic Duo', 'AEAO', 'Grand Carnival'),
    ('Dynamic Duo', 'Jam', 'Grand Carnival'),
    ('Dynamic Duo', 'Oasis', 'Grand Carnival'),
    ('Dynamic Duo', 'Hot Tub Time Machine', 'Grand Carnival'),
    ('Dynamic Duo', 'Sign', 'Grand Carnival'),
    ('Loco', 'Respect', ''),
    ('Loco', 'Awesome', ''),
    ('Gray', 'Just Do It', ''),
    ('Gray', "We Don't Love", 'Gray Season 2'),
    ('Simon Dominic', 'Won & Only', 'Won & Only'),
    ('Simon Dominic', 'Simon Dominic', 'Won & Only'),
    ('Simon Dominic', "Money Don't Lie", 'Won & Only'),
    ('Simon Dominic', 'Lonely Night', 'Won & Only'),
    ('Simon Dominic', 'Make Her Dance', 'Won & Only'),
    ('Giriboy', 'Back and Forth 30 Min', 'Sexual Perceptions'),
    ('Giriboy', 'Wu Gyeol', 'Sexual Perceptions'),
    ('Giriboy', 'Why Do You Live Like This?', ''),
    ('Giriboy', 'Edited By Devil', ''),
    ('Punchnello', 'Loving You Girl', 'Loving You Girl'),
    ('Colde', 'Your Dog Loves You', 'Your Dog Loves You'),
    ('PH-1', 'Good Day', 'Good Day'),
    ('PH-1', 'Nineteen', 'Good Day'),
    ('Nafla', 'Natural High', 'Natural High'),
    ('Loopy', 'No More', 'Mmk'),
    ('Kid Milli', 'IndiGO', 'IndiGO'),
    ('Changmo', 'Maestro', 'Maestro'),
    ('The Quiett', 'Cut', ''),
    ('Zico', 'Boys and Girls', 'Breakthrough'),
    ('Zico', 'Breakthrough', 'Breakthrough'),
    ('Junggigo', 'Want U', ''),
    ('Okasian', 'Celebration', ''),
    ('BewhY', 'Day Day', 'The Movie Star'),
    ('BewhY', 'Forever', 'The Movie Star'),
    ('Sik-K', 'Romeo & Juliet', 'TRAP'),
    ('Sik-K', 'TRAP', 'TRAP'),
    ('Bobby', 'GO UP', 'WILD AND YOUNG'),
    ('Crush', 'Love You With All My Heart', ''),
    ('Dean', '1333', ''),
    ('Basick', 'Hold You', 'Show Me the Money 4'),
    ('Iron', 'Rain Shower', 'Show Me the Money 4'),
    ('Lil Boi', 'Good Day', 'Show Me the Money 4'),
    ('Olltii', 'TTM', ''),
    ('Verbal Jint', 'Rap Genius No. 9', 'Rap Genius No. 9'),
    ('Black Nut', '100', 'Show Me the Money 4'),
    ('Truedy', 'My Light', 'Show Me the Money 4'),
    ('Basick', 'Stand Up', 'Show Me the Money 4'),
    ('Louie', 'GO', 'Show Me the Money 4'),
    ('Outsider', 'Vol.2-Maestro', 'Vol.2-Maestro'),
    ('Kid Ash', 'Orca', 'Orca-Tape'),
    ('C Jamm', 'Monster', ''),
    ('Illinit', 'Real Talk Live', ''),
    ('Heize', 'Happen Ending', 'Heize'),
    ('Giriboy', 'Sensual Album', 'Sensual Album'),
    ('Beenzino', 'January', '12'),
    ('Zion.T', 'Just', ''),
    ('YUMDDA', "I'm Good", ''),
    ('Blase', 'Passionfruit', ''),
    ('Mirani', 'Pepsi', ''),
    ('Iron', 'Rock Bottom', 'Show Me the Money 4'),
    ('Basick', 'Pale Dream', 'Show Me the Money 4'),
    ('San E', 'A BILLIONAIRE', 'Show Me the Money 4'),
    ('Louie', 'Picture', 'Show Me the Money 4'),
]
