TRACKS = [
    ('Dean', 'half moon', '130 Mood : TRBL'),
    ('Dean', '21', '130 Mood : TRBL'),
    ('Dean', 'out the club', '130 Mood : TRBL'),
    ('Dean', 'what2do', '130 Mood : TRBL'),
    ('Dean', 'wrong', '130 Mood : TRBL'),
    ('Dean', "i'm not sorry", '130 Mood : TRBL'),
    ('Dean', '1303', '130 Mood : TRBL'),
    ('Dean', 'pleasure & pain', '130 Mood : TRBL'),
    ('Crush', "Don't Forget", 'Interlude'),
    ('Crush', 'Interlude', 'Interlude'),
    ('Crush', 'Woo Ah', 'Interlude'),
    ('Crush', '9 to 5', 'Interlude'),
    ('Crush', 'Your Dress', ''),
    ('Jay Park', 'Drive', 'Everything You Wanted'),
    ('Jay Park', 'Solo', 'Everything You Wanted'),
    ('Jay Park', 'Me Like Yuh', 'Everything You Wanted'),
    ('Jay Park', 'Turn Off Your Phone Remix', 'Everything You Wanted'),
    ('Jay Park', 'The Truth Is', 'Everything You Wanted'),
    ('Jay Park', 'Replay', 'Everything You Wanted'),
    ('Jay Park', 'Feature', 'Everything You Wanted'),
    ('Jay Park', 'Limousine', 'Everything You Wanted'),
    ('Jay Park', 'Alone Tonight', 'Everything You Wanted'),
    ('Jay Park', 'Only One', 'Everything You Wanted'),
    ('Jay Park', 'Aquaman', 'Everything You Wanted'),
    ('Jay Park', 'Who the X is U', 'Everything You Wanted'),
    ('Jay Park', 'Forever', 'Everything You Wanted'),
    ('Jay Park', 'I Got This', 'Everything You Wanted'),
    ('Jay Park', 'Everything', 'Everything You Wanted'),
    ('Jay Park', 'Stay With Me', 'Everything You Wanted'),
    ('Jay Park', 'FYE', 'Everything You Wanted'),
    ('Loco', 'You Too', ''),
    ('Loco', 'Still', ''),
    ('Gray', 'Good', ''),
    ('Gray', 'Late Night', ''),
    ('Zion.T', 'Knock', 'Show Me the Money 5'),
    ('Heize', 'Round and Round', ''),
    ('Heize', 'Listen To Me', 'Unpretty Rapstar 2'),
    ('Beenzino', 'Real Girl', ''),
    ('Dynamic Duo', 'Highfive', ''),
    ('Giriboy', 'Because', 'Mechanical Album'),
    ('Giriboy', "You're Pretty", 'Mechanical Album'),
    ('Giriboy', 'Infrared Radiation', 'Mechanical Album'),
    ('Giriboy', 'Used to Love You', 'Mechanical Album'),
    ('Punchnello', 'My Piece', 'My Piece'),
    ('Colde', 'Love Lessons', 'Love Lessons'),
    ('Sik-K', 'YESSIR', 'Trap Art'),
    ('Sik-K', 'Throw That', 'Trap Art'),
    ('Sik-K', 'Donut', 'Trap Art'),
    ('Sik-K', 'Fly', 'Trap Art'),
    ('Sik-K', 'Trap Art', 'Trap Art'),
    ('Simon Dominic', 'Simon Dominic Part 3', 'Show Me the Money 5'),
    ('C Jamm', 'The Last', 'Show Me the Money 5'),
    ('BewhY', 'The Fiery', 'The Fiery'),
    ('BewhY', 'Movie Star', 'The Fiery'),
    ('BewhY', 'Interlude', 'The Fiery'),
    ('BewhY', 'Blind', 'The Fiery'),
    ('Hanhae', 'Drop', 'Show Me the Money 5'),
    ('San E', 'Body', 'Show Me the Money 5'),
    ('Jinbo', 'Honey', 'Honey'),
    ('Primary', 'Planetarium', ''),
    ('Elo', 'Hood', 'Hood'),
    ('Elo', 'Trouble', 'Hood'),
    ('Swings', 'Growling', 'Growling'),
    ('Verbal Jint', 'Dooms Day', 'Rap Genius No. 9'),
    ('Verbal Jint', 'Numbers', 'Rap Genius No. 9'),
    ('Tablo', 'Hood', "Fever's End Pt. 2"),
    ('Dok2', 'Rich Forever', 'Thug Life Part 2'),
    ('Zico', "It Isn't Love", 'Show Me the Money 5'),
    ('Bobby', 'GO', 'MOBB'),
    ('Bobby', 'Wang Hola', 'MOBB'),
    ('Mino', 'Hit Me', 'MOBB'),
    ('Mino', 'Ready Or Not', 'MOBB'),
    ('Mino', 'Burning Up', 'MOBB'),
    ('Nafla', 'Crew Love', 'Natural High'),
    ('Loopy', 'Press It', 'Mmk'),
    ('Kid Milli', 'Linguistics', 'IndiGO'),
    ('Changmo', 'Ring Ding', 'Maestro'),
    ('Killagramz', 'Good Morning', 'Show Me the Money 5'),
    ('Flowsik', 'We On', 'Show Me the Money 5'),
    ('Basick', 'Nice Day', 'Show Me the Money 5'),
    ('Olltii', 'Creative Control', 'Creative Control'),
    ('Jerry.K', 'Thorn Crown', 'Thorn Crown'),
    ('Lil Boi', 'Credit', 'Good Day'),
    ('G2', 'Business', 'Business'),
    ('Owen Ovadoz', 'POEM', 'POEM'),
    ('Deepflow', 'Flow the Life 4', 'Flow the Life 4'),
    ('Don Mills', 'Don Mills Is Angry 4', 'Don Mills Is Angry 4'),
    ('Huckleberry P', 'Mantra 4', 'Mantra 4'),
    ('Illinit', 'Ill Street Live 2', ''),
    ('Jessi', 'China', 'Show Me the Money 5'),
    ('Cheetah', 'Keep It Movin', ''),
    ('KittiB', 'Nobody Knows', ''),
    ('Reddy', 'THINK', ''),
    ('B-Free', 'Best Seller', 'Best Seller'),
    ('Coogie', 'Woops', ''),
    ('Junggigo', "No Diggin'", ''),
    ('Gaeko', 'Pass', 'Pass'),
    ('Yoon Mirae', 'Gemini', ''),
    ('Bumkey', 'Single Life 2', 'Single Life 2'),
    ('Tiger JK', 'I Know', 'Feel gHood Muzik : The 8th Wonderland'),
]
