TRACKS = [
    ('Dean', 'instagram', ''),
    ('G-Dragon', 'Untitled, 2014', 'Kwon Ji Yong'),
    ('G-Dragon', 'Bullshit', 'Kwon Ji Yong'),
    ('G-Dragon', 'Middle Fingers-Up', 'Kwon Ji Yong'),
    ('G-Dragon', 'Super Star', 'Kwon Ji Yong'),
    ('G-Dragon', 'Divina Commedia', 'Kwon Ji Yong'),
    ('G-Dragon', 'Intro. Kwon Ji Yong', 'Kwon Ji Yong'),
    ('Zico', 'Television', 'Television'),
    ('Zico', 'Artist', 'Television'),
    ('Zico', 'No Idea', 'Television'),
    ('Zico', 'Fanatxy', 'Television'),
    ('Zico', 'Eureka', 'Television'),
    ('Zico', 'Design', 'Television'),
    ('Zico', 'Okey Dokey', 'Okey Dokey'),
    ('Crush', 'None', ''),
    ('Crush', 'Skip', ''),
    ('Crush', 'Fall', 'Wonderlust'),
    ('Crush', 'What Do You Want To Eat?', 'Wonderlust'),
    ('Crush', 'Wonderlust', 'Wonderlust'),
    ('Heize', 'Jenga', 'Jenga'),
    ('Heize', 'You, Clouds, Rain', '///'),
    ('Heize', 'First Snow', 'Jenga'),
    ('Heize', 'Goodbye', 'Jenga'),
    ('Heize', 'Ride', '///'),
    ('Heize', 'And Today', '///'),
    ('Jay Park', 'V', 'The Season: The Blue Bird'),
    ('Jay Park', 'All The Way Up', ''),
    ('Jay Park', 'Nothing Wrong', ''),
    ('Jay Park', 'The Season', 'The Season: The Blue Bird'),
    ('Jay Park', 'NEED YOU', ''),
    ('Jay Park', 'Forget About That', ''),
    ('Loco', 'Too Much', 'Bleached'),
    ('Loco', 'Bleached', 'Bleached'),
    ('Loco', 'It Takes Time', ''),
    ('Loco', 'Summer Go Loco', 'Summer Go Loco'),
    ('Loco', 'Waiting', 'Bleached'),
    ('Loco', 'A Little More', 'Bleached'),
    ('Gray', "I'm Fine", 'Hyena on the Keyboard'),
    ('Gray', 'Upside Down', ''),
    ('Gray', 'Real Love', ''),
    ('Zion.T', 'The Song', 'OO'),
    ('Zion.T', 'Evan', 'OO'),
    ('Zion.T', 'Sorry', 'OO'),
    ('Zion.T', 'Snow', ''),
    ('Beenzino', 'Damnato', 'Damnato'),
    ('Beenzino', 'Holiday', 'Damnato'),
    ('Beenzino', "Nike's Song", 'Damnato'),
    ('Beenzino', 'Profanity', 'Damnato'),
    ('Simon Dominic', 'DAx4', 'DAx4'),
    ('Punchnello', 'Everyday', 'Everyday'),
    ('PH-1', 'YIN YANG', 'YIN YANG'),
    ('PH-1', 'Platonic', 'YIN YANG'),
    ('PH-1', 'Romeo and Juliet', 'YIN YANG'),
    ('Nafla', 'Jazz Freestyle', '[ Album ]'),
    ('Nafla', 'What', '[ Album ]'),
    ('Nafla', "You Gon' Need It", '[ Album ]'),
    ('Nafla', 'MVP', '[ Album ]'),
    ('Nafla', 'Bandage on My Shoulder', '[ Album ]'),
    ('Loopy', 'Portrait Mode', '[ Album ]'),
    ('Loopy', 'Save', '[ Album ]'),
    ('Loopy', 'Great Hour', '[ Album ]'),
    ('Loopy', 'No Loopy', '[ Album ]'),
    ('Loopy', 'Recipe', '[ Album ]'),
    ('Kid Milli', 'Cappuccino', ''),
    ('Kid Milli', 'Maiden Voyage', 'Maiden Voyage'),
    ('Kid Milli', 'Cabbage', 'Maiden Voyage'),
    ('Changmo', 'Boyhood', 'Boyhood'),
    ('Changmo', 'Meteor', 'Boyhood'),
    ('Changmo', 'Sufferer', 'Boyhood'),
    ('Giriboy', '914', '914'),
    ('Giriboy', 'Traffic Control', '914'),
    ('Giriboy', 'Maybe', '914'),
    ('Giriboy', 'Invasion', '914'),
    ('The Quiett', 'Glow', ''),
    ('Epik High', 'Lesson 1', 'Lesson 0'),
    ('Epik High', 'Lesson 2', 'Lesson 0'),
    ('Epik High', 'Lesson 3', 'Lesson 0'),
    ('Epik High', 'Ros Blanco', 'Lesson 0'),
    ('Epik High', "C'est La Vie", 'Lesson 0'),
    ('Sik-K', 'Party', 'Trap Art'),
    ('Sik-K', 'WEGO', 'YACHT'),
    ('Sik-K', 'YACHT', 'YACHT'),
    ('Sik-K', 'CRRWD', 'YACHT'),
    ('Sik-K', 'WHISTLE', 'YACHT'),
    ('Penomeco', 'COCO BOTTLE', ''),
    ('Penomeco', 'OFM', ''),
    ('Jessi', 'Unpretty Dreams', 'Unpretty Dreams'),
    ('Hash Swan', 'Hash Brand 2', 'Hash Brand 2'),
    ('Primary', 'Morning Glory', ''),
    ('Elo', 'Tattoo On My Heart', 'Tattoo On My Heart'),
    ('Swings', 'Remedy', 'Remedy'),
    ('Dok2', 'All I Know Is', 'Thug Life Part 2'),
    ('Paloalto', 'Sunday Service', 'Sunday Service'),
    ('Bobby', 'Y.G.G', 'Y.G.G'),
    ('Coogie', 'PICK UP THE PHONE', ''),
    ('Coogie', 'Money & Fame', ''),
    ('BewhY', 'Cult of Curiosity', 'Cult of Curiosity'),
    ('Leellamarz', 'To Be Continued', 'To Be Continued'),
    ('Hash Swan', 'Hash Brand', 'Hash Brand'),
    ('NO:EL', 'Rain Drop', 'Rain Drop'),
]
