TRACKS = [
    ("G-Dragon", "One of a Kind", "One of a Kind"),
    ("G-Dragon", "That XX", "One of a Kind"),
    ("G-Dragon", "Crayon", "One of a Kind"),
    ("G-Dragon", "Missing You", "One of a Kind"),
    ("G-Dragon", "Without You", "One of a Kind"),
    ("Epik High", "99", "99"),
    ("Epik High", "It's Cold", "99"),
    ("Epik High", "Friend?", "99"),
    ("Epik High", "Map of the Human Mind", "99"),
    ("Epik High", "Bouncer", "99"),
    ("Epik High", "Obligation", "99"),
    ("Dynamic Duo", "Eunhaeng", "A Giant Step"),
    ("Dynamic Duo", "Solo", "A Giant Step"),
    ("Dynamic Duo", "Pledge", "A Giant Step"),
    ("Dynamic Duo", "Gao", "A Giant Step"),
    ("Jay Park", "New Breed", "New Breed"),
    ("Jay Park", "Girlfriend", "New Breed"),
    ("Jay Park", "Star", "New Breed"),
    ("Jay Park", "Turn Off Your Phone", "New Breed"),
    ("Jay Park", "Level Up", "New Breed"),
    ("Jay Park", "Ride or Die", "New Breed"),
    ("Beenzino", "247", "247"),
    ("Beenzino", "Perfect Lover", "247"),
    ("Beenzino", "Slow Down", "247"),
    ("Beenzino", "Hot Spring", "247"),
    ("Verbal Jint", "Mainstream", "Mainstream"),
    ("Verbal Jint", "No Scope", "Mainstream"),
    ("Verbal Jint", "Good Morning Pt.2", "Mainstream"),
    ("Simon Dominic", "Cheer Up to You", "Consolation"),
    ("Simon Dominic", "Consolation", "Consolation"),
    ("Simon Dominic", "Simplize", "Consolation"),
    ("Simon Dominic", "I2", "Consolation"),
    ("Zion.T", "I Need U", "Zion.T Special: ZIP"),
    ("Zion.T", "Babylon", "Zion.T Special: ZIP"),
    ("Zion.T", "EPIC", "Zion.T Special: ZIP"),
    ("Zion.T", "Miss Kim", "Zion.T Special: ZIP"),
    ("Crush", "Crush on You", "Crush on You"),
    ("Crush", "Hug Me", "Crush on You"),
    ("Crush", "I'm Yours", "Crush on You"),
    ("Crush", "Beautiful", "Crush on You"),
    ("Loco", "See You", "Blonote"),
    ("Loco", "Hold Me", "Blonote"),
    ("Loco", "Blonote", "Blonote"),
    ("Loco", "Thinking About You", "Blonote"),
    ("Gray", "Call Me Yours", "Gray Season 1"),
    ("Gray", "Dangerous", "Gray Season 1"),
    ("Gray", "Stay the Night", "Gray Season 1"),
    ("Gray", "Swim", "Gray Season 1"),
    ("Primary", "Roller Coaster", "Primary and the Messengers LP 2"),
    ("Primary", "JohnLegend", "Primary and the Messengers LP 2"),
    ("Primary", "Mission", "Primary and the Messengers LP 2"),
    ("Primary", "Think About It", "Primary and the Messengers LP 2"),
    ("Primary", "Don't Stop", "Primary and the Messengers LP 2"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Junggigo", "Because", "Rookie"),
    ("Junggigo", "Looking Star", "Rookie"),
    ("Gaeko", "West Coast", "Redingray"),
    ("Gaeko", "Redingray", "Redingray"),
    ("Gaeko", "Rhythm and Poetry", "Redingray"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Bumkey", "Attraction", "Single Life"),
    ("Zico", "Battle Royale", "Zico on the Block 1.5"),
    ("Zico", "Hurricane Venus", "Zico on the Block 1.5"),
    ("Zico", "Human", "Zico on the Block 1.5"),
    ("E-Sens", "Anonymous Letters", "Anonymous Letters"),
    ("E-Sens", "The Song of the Sword", "Anonymous Letters"),
    ("E-Sens", "New York", "Anonymous Letters"),
    ("Dok2", "Rich", "Dok2ocracy"),
    ("Dok2", "We Online", "Dok2ocracy"),
    ("Dok2", "Crown City", "Dok2ocracy"),
    ("The Quiett", "Q Train", "Q Train"),
    ("The Quiett", "Guilty Conscience", "Q Train"),
    ("The Quiett", "Can't Go Home", "Q Train"),
    ("Paloalto", "Shining Diamond", "Shining Diamond"),
    ("Paloalto", "Good Morning", "Shining Diamond"),
    ("Paloalto", "Lonely", "Shining Diamond"),
    ("Mad Clown", "Potato", "Potato"),
    ("Mad Clown", "Maximum", "Potato"),
    ("Yoon Mirae", "Touch Love", ""),
    ("Tablo", "Baddest Female", "Fever's End Pt. 1"),
    ("Tablo", "Tomorrow Is Coming", "Fever's End Pt. 1"),
    ("Jinbo", "Deeper", "555"),
    ("Jinbo", "O.S.T.", "555"),
    ("Swings", "I'll Give You Everything", ""),
    ("Swings", "Sleep Well", ""),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Deepflow", "Flow the Life 3", "Flow the Life 3"),
    ("Deepflow", "Intro", "Flow the Life 3"),
    ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
    ("Huckleberry P", "Mantra 3", "Mantra 3"),
    ("Kebee", "Rhythm and Poetry", "Rhythm and Poetry"),
    ("Myun Do One", "Myun Do One Is Back 2", "Myun Do One Is Back 2"),
    ("J'Kyun", "Ready to Fly 2", "Ready to Fly 2"),
    ("Illinit", "Real Talk", "Ill Street Live"),
    ("Sean2Slow", "Slow Jam 2", "Slow Jam 2"),
    ("Skull", "Love U", "Skull & Haha 2"),
    ("Double K", "Fly High 2", "Fly High 2"),
    ("Pe2ny", "Pe2ny Maker 2", "Pe2ny Maker 2"),
    ("TBNY", "Million 2", "Million 2"),
    ("Stuck B", "Stuck B 2", "Stuck B 2"),
    ("Crown J", "My Friend 2", "My Friend 2"),
    ("L.E.O.", "Show Must Go On 2", "Show Must Go On 2"),
    ("Tiger JK", "The Hidden Tiger", "The Hidden Tiger"),
    ("Leessang", "Healer", ""),
]
