TRACKS = [
    ("Epik High", "Encore", "Shoebox"),
    ("Epik High", "Happen Ending", "Shoebox"),
    ("Epik High", "Rich", "Shoebox"),
    ("Epik High", "Spoiler", "Shoebox"),
    ("Epik High", "Burj Khalifa", "Shoebox"),
    ("Epik High", "We Fight Ourselves", "Shoebox"),
    ("Epik High", "Amor Fati", "Shoebox"),
    ("Epik High", "Born Hater", "Shoebox"),
    ("Epik High", "Lesson 5", "Shoebox"),
    ("Epik High", "Life Is Good", "Shoebox"),
    ("Epik High", "Eyes, Nose, Lips", "Shoebox"),
    ("Epik High", "Shoebox", "Shoebox"),
    ("Jay Park", "Evolution", "Evolution"),
    ("Jay Park", "Joah", "Evolution"),
    ("Jay Park", "So Good", "Evolution"),
    ("Jay Park", "2nd Thots", "Evolution"),
    ("Jay Park", "I Like You", "Evolution"),
    ("Jay Park", "Zero", "Evolution"),
    ("Jay Park", "Yacht", "Evolution"),
    ("Jay Park", "Metronome", "Evolution"),
    ("Jay Park", "I Like 2 Party", "Evolution"),
    ("Jay Park", "The Promise", "Evolution"),
    ("Jay Park", "100 Years Hip-Hop", "Evolution"),
    ("Jay Park", "Body 2 Body", "Evolution"),
    ("Crush", "Sometimes", "Crush on You"),
    ("Crush", "Sofa", ""),
    ("Crush", "Give It to Me", "Crush on You"),
    ("Crush", "Memories", "Crush on You"),
    ("Beenzino", "Jackson Pollock Dick", "Up All Night"),
    ("Beenzino", "How Do I Look?", "Up All Night"),
    ("Beenzino", "Crazy", "Up All Night"),
    ("Beenzino", "Up All Night", "Up All Night"),
    ("Beenzino", "I Don't Have To Work", "Up All Night"),
    ("Beenzino", "Life Is Good", "12"),
    ("Zion.T", "Yanghwa Bridge", ""),
    ("Zion.T", "Zero Gravity", ""),
    ("Bobby", "Secret", "Secret"),
    ("Bobby", "Holup!", "Secret"),
    ("Bobby", "Shake It", "Secret"),
    ("Bobby", "Wedding Dress", "Secret"),
    ("Mino", "Fear", "Fear"),
    ("Mino", "Body", "Fear"),
    ("Mino", "Freak From Da Soul", "Fear"),
    ("Heize", "After I've Wandered A Bit", ""),
    ("Heize", "Heize", "HEIZE"),
    ("Heize", "Because I Touched You", "HEIZE"),
    ("Dean", "Put My Hands on You", ""),
    ("Loco", "Hands Up", "Locomotive"),
    ("Loco", "Act Serious", "Locomotive"),
    ("Loco", "You Don't Know", "Locomotive"),
    ("Loco", "No Manners", "Locomotive"),
    ("Loco", "High", "Locomotive"),
    ("Loco", "If I", "Locomotive"),
    ("Loco", "Growing Up", "Locomotive"),
    ("Loco", "Hold Me Tight", "Locomotive"),
    ("Gray", "Let's Fall in Love", "Gray Season 2"),
    ("Gray", "Smile", "Gray Season 2"),
    ("Gray", "Remix 2 Me", "Gray Season 2"),
    ("Giriboy", "Camp", ""),
    ("Giriboy", "Different", "Different"),
    ("Giriboy", "Take a Trip", "Different"),
    ("Swings", "Rain Showers", ""),
    ("Swings", "Hongkiyoung", ""),
    ("Swings", "Remember We", "Growing Pains"),
    ("E-Sens", "Back In Time", "The Anecdote"),
    ("Dynamic Duo", "A Giant Step", ""),
    ("Primary", "Da Capo", "Da Capo"),
    ("Primary", "JohnLegend", "Da Capo"),
    ("Primary", "Mission", "Da Capo"),
    ("Punchnello", "If You", "If You"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Gaeko", "Going Home", "Going Home"),
    ("Zico", "Adult Ceremony", ""),
    ("Zico", "Well Done", "Zico on the Block 1.5"),
    ("San E", "Bananas", "Show Me the Money 3"),
    ("Mad Clown", "Maximum", "Potato"),
    ("Dok2", "We Online", "Dok2ocracy"),
    ("Junggigo", "Warm", ""),
    ("Leessang", "Coming of Age Story", ""),
    ("Yoon Mirae", "Angel", ""),
    ("Simon Dominic", "No Stress", ""),
    ("Simon Dominic", "New Year New Me", ""),
    ("Simon Dominic", "Samba Rhythm", ""),
    ("Tablo", "Fever", "Fever's End Pt. 2"),
    ("Tablo", "Timeless", "Fever's End Pt. 2"),
    ("Verbal Jint", "Good Morning Pt.3", "Rap Genius No. 8"),
    ("Verbal Jint", "Rap Genius No. 8", "Rap Genius No. 8"),
    ("Bumkey", "Don't Know What to Do", ""),
    ("Zion.T", "Eat", ""),
    ("Beenzino", "12", "12"),
    ("Crush", "Electric Kiss", ""),
    ("Loco", "Thinking About You", "Locomotive"),
    ("Gray", "Summer Night", "Gray Season 2"),
    ("Giriboy", "Square", "Square"),
    ("Okasian", "Airplane Mode", ""),
    ("PH-1", "PH1's Day Off", ""),
    ("Nafla", "Mood Indigo", ""),
    ("Loopy", "Mmk", ""),
    ("Kid Milli", "A Swaggy Song Called Kidd", ""),
]
