TRACKS = [
    ("Dynamic Duo", "Return Of The Kings", "Lucky Numbers"),
    ("Dynamic Duo", "Three Dopeboyz", "Lucky Numbers"),
    ("Dynamic Duo", "Life Is Good", "Lucky Numbers"),
    ("Dynamic Duo", "BAAAM", "Lucky Numbers"),
    ("Dynamic Duo", "Airplane Mode", "Lucky Numbers"),
    ("Dynamic Duo", "Lee Dae Ho", "Lucky Numbers"),
    ("Dynamic Duo", "Shoot Goal In", "Lucky Numbers"),
    ("Dynamic Duo", "Hot Wings", "Lucky Numbers"),
    ("Dynamic Duo", "Good Morning Love", "Lucky Numbers"),
    ("Dynamic Duo", "Tragedy Part 2", "Lucky Numbers"),
    ("Dynamic Duo", "Crime Scene", "Lucky Numbers"),
    ("Dean", "130613", ""),
    ("Beenzino", "Profile", "11:11"),
    ("Zion.T", "O", "Red Light"),
    ("Zion.T", "Doop", "Red Light"),
    ("Zion.T", "Dodohae", "Red Light"),
    ("Zion.T", "She", "Red Light"),
    ("Zion.T", "Neon", "Red Light"),
    ("Zion.T", "Babay", "Red Light"),
    ("Zion.T", "Global Warming", "Red Light"),
    ("Zion.T", "Two Melodies", "Red Light"),
    ("Zion.T", "Spin Spin", "Mirrorball"),
    ("Zion.T", "Modern Boy", "Mirrorball"),
    ("Zion.T", "Madame", "Mirrorball"),
    ("Giriboy", "Skit", ""),
    ("Giriboy", "Wake Up", ""),
    ("Giriboy", "Lowlife", ""),
    ("Gray", "In My Head", "Call Me Gray"),
    ("Gray", "Dream Chaser", "Call Me Gray"),
    ("Gray", "Summer Night", "Call Me Gray"),
    ("Loco", "Take Care", ""),
    ("Zico", "I Got 97 on My Test", ""),
    ("Primary", "eeee", ""),
    ("Primary", "Amigo", ""),
    ("Dok2", "Good Vibes Only", "Ruthless, The Album"),
    ("Dok2", "1LLIN", "Ruthless, The Album"),
    ("Dok2", "Hell Yeah", "Ruthless, The Album"),
    ("Dok2", "All I Know", "Ruthless, The Album"),
    ("Dok2", "Outchea", "Ruthless, The Album"),
    ("Dok2", "Zero", "Ruthless, The Album"),
    ("Dok2", "No More", "Ruthless, The Album"),
    ("Dok2", "My Dreams Do Come True", "Ruthless, The Album"),
    ("Dok2", "Oh Yeah", "Ruthless, The Album"),
    ("Dok2", "Runnin'", "Ruthless, The Album"),
    ("Dok2", "Bandz & Benz", "Ruthless, The Album"),
    ("Dok2", "Handz Up", "Ruthless, The Album"),
    ("Jinbo", "Neon Pink Ocean", "Fantasy"),
    ("Jinbo", "Fantasy", "Fantasy"),
    ("Jinbo", "Cops Come Knock", "Fantasy"),
    ("Jinbo", "Tape It Slow Baby", "Fantasy"),
    ("Jinbo", "Loverbot", "Fantasy"),
    ("Jinbo", "Traumatic", "Fantasy"),
    ("Jinbo", "Delete It Deal It", "Fantasy"),
    ("Jinbo", "Reboot My Universe", "Fantasy"),
    ("Jinbo", "Don't Be Sad When You're Sad", "Fantasy"),
    ("Jinbo", "It's Over", "Fantasy"),
    ("Jinbo", "Be My Friend", "Fantasy"),
    ("Crush", "Where Do You Wanna Go", ""),
    ("Gaeko", "Geon Gangs", "Geon Gangs"),
    ("B-Free", "Hot Summer", ""),
    ("B-Free", "Korean Dream Team", ""),
    ("San E", "Show Me the Money", "Show Me the Money 2"),
    ("San E", "Bad Year", ""),
    ("Okasian", "Check-in", "Orca-Tape"),
    ("Okasian", "Don't Front", "Orca-Tape"),
    ("Reddy", "Commitment", "Orca-Tape"),
    ("Jerry.K", "V", "V"),
    ("Jerry.K", "Ready", "V"),
    ("Vasco", "Exodus Announcement", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "Guerrilla Muzik", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "No More War", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "Revolution", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "The End", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "Exodus", "Guerrilla Muzik Vol.3 Exodos"),
    ("The Quiett", "Green Light", ""),
    ("The Quiett", "11:11", "11:11"),
    ("Paloalto", "Good Morning Seoul", ""),
    ("Paloalto", "Sunday", ""),
    ("Mad Clown", "Oppa Thoughts", ""),
    ("Leessang", "Ballerino", ""),
    ("Tiger JK", "Monologue", ""),
    ("Swings", "Swings #1 Vol. II", ""),
    ("E-Sens", "Black Suit", ""),
    ("Lil Boi", "Ferris Wheel", ""),
    ("G2", "Online", ""),
    ("Owen Ovadoz", "P", ""),
    ("Deepflow", "Good Day", ""),
    ("Don Mills", "Zero", ""),
    ("Kebee", "Call Me", ""),
    ("Beenzino", "Illionaire Gang", "11:11"),
    ("Gray", "Blink", ""),
    ("Bumkey", "When I Wake Up", ""),
    ("Junggigo", "Going Crazy", ""),
    ("Verbal Jint", "Rap Genius No. 8 Intro", "Rap Genius No. 8"),
    ("Illinit", "Real Talk", ""),
    ("Outsider", "Loner 2", "Vol.2-Maestro"),
    ("NO:EL", "Super Saiyan", ""),
    ("Coogie", "PLAY", ""),
    ("Hash Swan", "Hash X Kash", ""),
    ("Changmo", "Rebels", ""),
]
