TRACKS = [
    ('Epik High', 'Sleeping Beauty', 'Sleepless in __________'),
    ('Epik High', 'Eternal Sunshine', 'Sleepless in __________'),
    ('Epik High', 'Lost One', 'Sleepless in __________'),
    ('Epik High', 'Leica', 'Sleepless in __________'),
    ('Epik High', 'No Different', 'Sleepless in __________'),
    ('Epik High', 'In Seoul', 'Sleepless in __________'),
    ('Epik High', 'Bleed', 'Sleepless in __________'),
    ('Epik High', 'Tik Tik Tik', 'Sleepless in __________'),
    ('Epik High', 'Indigo', 'Sleepless in __________'),
    ('Epik High', 'Gray', 'Sleepless in __________'),
    ('Epik High', 'Fry Me', 'Sleepless in __________'),
    ('Epik High', 'Crescendo', 'Sleepless in __________'),
    ('Epik High', 'Kill Me', 'Sleepless in __________'),
    ('Epik High', 'Love Story', 'Sleepless in __________'),
    ('Beenzino', '24:26', '24:26'),
    ('Beenzino', 'Mozart', '24:26'),
    ('Beenzino', 'Akin to the Stove', '24:26'),
    ('Beenzino', "Philosopher's Stone", '24:26'),
    ('Beenzino', 'LIFEGUARD', '24:26'),
    ('Dean', "howlin' 404", "howlin' 404"),
    ('Crush', 'NAPPA', 'NAPPA'),
    ('Crush', 'Lay Your Head on Me', 'NAPPA'),
    ('Crush', 'Be By My Side', 'NAPPA'),
    ('Heize', 'She Drive', 'She Drive'),
    ('Heize', "We Don't Talk Together", 'She Drive'),
    ('Heize', 'Only You', 'She Drive'),
    ('Jay Park', 'These Days', 'The Season: The Blue Bird'),
    ('Sokodomo', 'coffee', 'Show Me the Money 8'),
    ('Loco', 'OFFICIAL', 'OFFICIAL'),
    ('Loco', 'Thinking of You', 'OFFICIAL'),
    ('Loco', 'Party Band', 'OFFICIAL'),
    ('Gray', 'Remedy', 'Remedy'),
    ('Zico', 'Summer Hate', 'Human'),
    ('Zico', 'Balloon', 'Human'),
    ('Sik-K', 'Wet', 'MAKE OUT'),
    ('Sik-K', 'Out of Ink', 'MAKE OUT'),
    ('Kid Milli', 'BOON', 'BEANie'),
    ('Kid Milli', 'WHY TRIP', 'BEANie'),
    ('Nafla', 'Swervin', 'C.R.E.A.M'),
    ('Nafla', 'cashrules', 'C.R.E.A.M'),
    ('Changmo', 'Thrift Shop', 'Ghetto Kids'),
    ('Coogie', 'Save the Day', 'Save the Day'),
    ('Coogie', 'Alone', 'Save the Day'),
    ('PH-1', "Cupid's Arrow", 'Good Day'),
    ('Giriboy', 'Aquadotted', 'heat'),
    ('Giriboy', 'SEOUL CITY G', 'heat'),
    ('Giriboy', 'Drama King', 'heat'),
    ('Ash Island', 'Floating', 'ISLAND'),
    ('HAON', 'HAON', 'ISLAND'),
    ('Leellamarz', '3AM in Seoul', 'To Be Continued'),
    ('Mudd the student', 'OG', ''),
    ('YUMDDA', 'Shake', "I'm Good"),
    ('NO:EL', 'Rain Drop 2', 'Rain Drop 2'),
    ('D.Ark', 'Genius (Remix)', 'Genius'),
    ('Paloalto', 'Mood Indigo', 'Mood Indigo'),
    ('Blued', 'Blue', 'Blue'),
    ('J Soul', 'Soul', 'Soul'),
    ('Jay Soul', 'Soul Food', 'Soul Food'),
    ('Primary', '2', '2'),
    ('Outsider', 'Vol.2-Maestro 3', 'Vol.2-Maestro 3'),
    ('Jessi', 'Who Dat B', 'Who Dat B'),
    ('Penomeco', 'Shy (수줍)', 'Shy'),
    ('Penomeco', 'Lovers', 'Shy'),
    ('Dean', 'DIE 4 YOU', "howlin' 404"),
    ('Koonta', 'Unbreakable', 'Show Me the Money 8'),
    ('Lil Boi', 'On My Way', 'Show Me the Money 8'),
    ('Mudd the student', 'Open', 'Show Me the Money 8'),
    ('Leellamarz', 'Barcode', 'Show Me the Money 8'),
    ('TOIL', 'Panorama', 'Show Me the Money 8'),
    ('Blase', 'Tic Tac', 'Show Me the Money 8'),
    ('Woodie Gochild', 'WaRRior', 'Show Me the Money 8'),
    ('Sokodomo', 'IF I', 'Show Me the Money 8'),
    ('Koonta', 'Grandma', 'Show Me the Money 8'),
    ('Owen Ovadoz', '119 REMIX', 'Show Me the Money 8'),
    ('Giriboy', 'on my way', 'Show Me the Money 8'),
    ('Lil Moshpit', 'BITE', 'Show Me the Money 8'),
    ('Mudd the student', 'MEMORIES', 'Show Me the Money 8'),
    ('Mirani', 'VANS', 'Show Me the Money 8'),
    ('Blase', 'Fill It', 'Show Me the Money 8'),
    ('Lil Boi', 'Only', 'Show Me the Money 8'),
    ('Lil Boi', 'Gigantic', 'Show Me the Money 8'),
    ('YunB', 'Piano', 'Show Me the Money 8'),
    ('Swings', 'IndiGO', 'Show Me the Money 8'),
    ('Code Kunst', 'ARCHIVE', 'Code Kunst Archive Pack 02'),
    ('Swings', 'The King', 'Growing Pains 2'),
    ('Primary', 'eee', '2'),
    ('Dynamic Duo', 'A DynamicAffair', 'A DynamicAffair'),
    ('Mino', 'Do It', 'Do It'),
    ('Bobby', 'One Shot', 'One Shot'),
    ('Penomeco', 'Shy (Suup)', 'Shy'),
    ('Kid Milli', 'A List', 'Show Me the Money 8'),
    ('PH-1', 'RUBBER', 'Show Me the Money 8'),
    ('Lil Boi', 'VVS', 'Show Me the Money 8'),
    ('Mudd the student', 'IndiGO', 'Show Me the Money 8'),
    ('Leellamarz', 'Change', 'Show Me the Money 8'),
    ('Mirani', 'VVS', 'Show Me the Money 8'),
    ('Lil Moshpit', 'VVS', 'Show Me the Money 8'),
    ('YunB', 'VVS', 'Show Me the Money 8'),
    ('Koonta', 'VVS', 'Show Me the Money 8'),
]
