TRACKS = [
    ('Beenzino', 'Trippy', ''),
    ('Beenzino', 'In Bed/Makgulli', 'NOWITZKI'),
    ('Beenzino', 'Travel Again', 'NOWITZKI'),
    ('Beenzino', 'Coca Cola Red', 'NOWITZKI'),
    ('Beenzino', '990', 'NOWITZKI'),
    ('Beenzino', 'Lemon', 'NOWITZKI'),
    ('Beenzino', 'Like A Fool', 'NOWITZKI'),
    ('Beenzino', 'Crime', 'NOWITZKI'),
    ('Beenzino', 'Camp', 'NOWITZKI'),
    ('Beenzino', 'Change', 'NOWITZKI'),
    ('Beenzino', 'Just One Day', 'NOWITZKI'),
    ('Beenzino', 'Sandman', 'NOWITZKI'),
    ('Beenzino', 'Radio', 'NOWITZKI'),
    ('Beenzino', 'Gym', 'NOWITZKI'),
    ('Jay Park', 'Candy', ''),
    ('Jay Park', 'Sunday Night Drive', ''),
    ('Loco', 'VOLVO', ''),
    ('Loco', 'INEEDYOURLOVE', ''),
    ('Loco', 'Pick Pick', 'WEAK'),
    ('Loco', 'BROKEN IPHONE', 'WEAK'),
    ('Loco', 'NOT OK', 'WEAK'),
    ('Loco', 'Window Overlooking the Sea', 'WEAK'),
    ('Loco', 'HEEE !', 'WEAK'),
    ('Loco', 'Just like this', 'WEAK'),
    ('Loco', '4 U', 'WEAK'),
    ('Loco', 'Bonus', 'WEAK'),
    ('Epik High', 'Strawberry', 'Strawberry'),
    ('Epik High', 'On My Way', 'Strawberry'),
    ('Epik High', 'Catch', 'Strawberry'),
    ('Epik High', 'Down Bad Freestyle', 'Strawberry'),
    ('Epik High', "God's Latte", 'Strawberry'),
    ('Crush', 'Hmm-cheat', 'wonderego'),
    ('Crush', 'EZPZ', 'wonderego'),
    ('Crush', 'Ego', 'wonderego'),
    ('Crush', 'A Man Like Me', 'wonderego'),
    ('Crush', 'New Day', 'wonderego'),
    ('Crush', 'No Break', 'wonderego'),
    ('Crush', 'Me Myself & I', 'wonderego'),
    ('Crush', 'Satisfied', 'wonderego'),
    ('Crush', 'Nothing Else', 'wonderego'),
    ('Kid Milli', 'BEIGE theme', 'BEIGE'),
    ('Kid Milli', 'HONDA!', 'BEIGE'),
    ('Kid Milli', 'Simple Poem', 'BEIGE'),
    ('Kid Milli', 'Still friend?', 'BEIGE'),
    ('Kid Milli', 'R.I.P', 'BEIGE'),
    ('Kid Milli', 'Test me?', 'BEIGE'),
    ('Kid Milli', 'BNC', 'BEIGE'),
    ('Kid Milli', 'Coupe!', 'BEIGE'),
    ('Kid Milli', 'Lost and found freestyle', 'BEIGE'),
    ('Kid Milli', 'Let Me Down!', 'BEIGE'),
    ('Kid Milli', '25', 'BEIGE'),
    ('Kid Milli', 'BORA', 'BEIGE'),
    ('Coogie', 'Buck', 'DIFF'),
    ('Coogie', 'Just For Fun', 'DIFF'),
    ('Coogie', 'I Go', 'DIFF'),
    ('Coogie', 'D.O.D', 'DIFF'),
    ('Coogie', 'LOCO', 'DIFF'),
    ('Coogie', 'Hold It Down', 'DIFF'),
    ('Dean', 'Die 4 You', ''),
    ('Heize', 'Perhaps Happy Ending', 'Last Winter'),
    ('Heize', 'Lips', 'Last Winter'),
    ('Heize', 'From Autumn to Winter', 'Last Winter'),
    ('Heize', 'Forgotten Love', 'Last Winter'),
    ('Heize', 'Dance with Me', 'Last Winter'),
    ('Heize', 'Connection', 'Last Winter'),
    ('Heize', 'Love goes around comes around', 'Last Winter'),
    ('Zion.T', 'UNLOVE', 'Zip'),
    ('Zion.T', 'Stranger', 'Zip'),
    ('Zion.T', 'The Things I Like', 'Zip'),
    ('Zion.T', 'V (Peace)', 'Zip'),
    ('Zion.T', 'NOT FOR SALE', 'Zip'),
    ('Zion.T', 'Invisible Person', 'Zip'),
    ('Zion.T', 'Inside a Dark Room', 'Zip'),
    ('Zion.T', 'Whale', 'Zip'),
    ('Zion.T', 'Happy Ending', 'Zip'),
    ('Bobby', 'Drowning', 'S.i.R'),
    ('Bobby', 'Cherry Blossom', 'S.i.R'),
    ('Lil Moshpit', 'TO GO', ''),
    ('Lil Moshpit', 'Money Only Shows Hustle', ''),
    ('Leellamarz', "I don't know a single thing", ''),
    ('Leellamarz', "Can't stop", 'DAYDATE'),
    ('Leellamarz', 'Wave', 'DAYDATE'),
    ('Leellamarz', 'Moshpit', 'DAYDATE'),
    ('Leellamarz', 'We like to party', 'DAYDATE'),
    ('Leellamarz', 'Money dance', 'DAYDATE'),
    ('Leellamarz', 'Tsunami', 'DAYDATE'),
    ('Kid Milli', 'Overtake', 'BEIGE'),
    ('Mino', 'Smoke', 'BODY'),
    ('Changmo', 'VOOM', ''),
    ('Leellamarz', 'Russian Roulette', 'Life is Once'),
    ('Leellamarz', 'Boys Like Girls', 'Life is Once'),
    ('Leellamarz', 'Masquerade Ball', 'Life is Once'),
    ('Paloalto', 'Issues', 'BUT FOR NOW LEAVE ME ALONE'),
    ('Jay Park', 'Why', ''),
    ('Dean', 'NO FUN', "howlin' 404"),
    ('Heize', 'Midnight', 'Last Winter'),
    ('Mino', 'Aero', 'BODY'),
    ('Changmo', 'FWB', ''),
    ('Punchnello', 'Motive', ''),
    ('Colde', 'Wave', ''),
]
