TRACKS = [
    ('Beenzino', 'Monet', ''),
    ('Zico', 'New Thing', ''),
    ('Zico', 'Grown Ass Kid', 'Grown Ass Kid'),
    ('Zico', 'Seoul Drift', 'Grown Ass Kid'),
    ('Zico', 'Being Human', 'Grown Ass Kid'),
    ('Zico', 'Curriculum', 'Grown Ass Kid'),
    ('Zico', 'OMJT', 'Grown Ass Kid'),
    ('Zico', 'Trash Talk', 'Grown Ass Kid'),
    ('Zico', 'That Guy', 'Grown Ass Kid'),
    ('Kid Milli', 'Lightly', ''),
    ('PH-1', 'BUT FOR NOW LEAVE ME ALONE', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Zombies', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'TGIF', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Yuppie Ting', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Tipsy', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Mr. Bad', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Juliette!', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Run Away', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Dead Girl', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Shrink Told Me', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Issues', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Break the Glass', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Final Bout', 'BUT FOR NOW LEAVE ME ALONE'),
    ('PH-1', 'Bve', 'BUT FOR NOW LEAVE ME ALONE'),
    ('Epik High', 'Here', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Prequel', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Super Rare', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Gray So Gray', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'BRB', 'Epik High Is Here 下, Part 2'),
    ('Epik High', "I Hated Myself (Tablo's Word)", 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Rain Song', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Rich Kids Anthem', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Face ID', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Family Portrait', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Champagne', 'Epik High Is Here 下, Part 2'),
    ('Epik High', 'Piano for Sale', 'Epik High Is Here 下, Part 2'),
    ('Leellamarz', 'STORY', 'Toystory3'),
    ('Leellamarz', 'Last Chance', 'Toystory3'),
    ('Leellamarz', 'Don`t do That', 'Toystory3'),
    ('Leellamarz', 'Seperation Anxiety', 'Toystory3'),
    ('Leellamarz', 'Never Ending Story', 'Toystory3'),
    ('Leellamarz', 'Aftermath', 'Toystory3'),
    ('Leellamarz', 'B.B.B', 'Toystory3'),
    ('Leellamarz', 'Flower Age', 'Toystory3'),
    ('Leellamarz', '1,2,3', 'Toystory3'),
    ('Leellamarz', '2AM', 'Toystory3'),
    ('Leellamarz', 'Zero Coke', 'Toystory3'),
    ('Leellamarz', 'Iris', 'Toystory3'),
    ('Leellamarz', 'Number', 'MaRz&B'),
    ('Leellamarz', 'Uncomfortable', 'MaRz&B'),
    ('Leellamarz', 'Ex', 'MaRz&B'),
    ('Leellamarz', 'Chrome Hearts', 'MaRz&B'),
    ('Leellamarz', 'Down', 'MaRz&B'),
    ('Leellamarz', 'Muse', 'MaRz&B'),
    ('Leellamarz', 'Meet me at the London', 'MaRz&B'),
    ('Leellamarz', 'CTRL+Z', 'VIOLINIST2'),
    ('Leellamarz', 'OUT OF MY SIGHT', 'VIOLINIST2'),
    ('Leellamarz', 'Left hand to Right hand', 'VIOLINIST2'),
    ('Leellamarz', 'a single word', 'VIOLINIST2'),
    ('Leellamarz', 'This is not what I want', 'VIOLINIST2'),
    ('Leellamarz', 'Selfish', 'VIOLINIST2'),
    ('Leellamarz', 'Sisi La Famille', 'VIOLINIST2'),
    ('Leellamarz', '30 minutes', 'VIOLINIST2'),
    ('Leellamarz', 'Without You (Encore)', 'VIOLINIST2'),
    ('Lil Moshpit', 'Moshpit Only', 'AAA'),
    ('Lil Moshpit', 'Gotta Lotta Shit', 'AAA'),
    ('Lil Moshpit', 'Yooooo', 'AAA'),
    ('Lil Moshpit', 'A-Team Freestyle', 'AAA'),
    ('Lil Moshpit', 'Slatty Slut', 'AAA'),
    ('Lil Moshpit', 'ON THE BLOCK', 'AAA'),
    ('Lil Moshpit', 'DIE HARD', 'AAA'),
    ('Lil Moshpit', 'BO$$', 'AAA'),
    ('Lil Moshpit', 'Back In My AREA', 'AAA'),
    ('Paloalto', 'Valentina', ''),
    ('TOIL', 'like when we first met', ''),
    ('The Quiett', 'Bentley', ''),
    ('Coogie', 'Good Night', 'Re:Up'),
    ('Beenzino', 'Dumbo', 'Dumbo'),
    ('Lil Moshpit', 'ACHOO', 'ACHOO'),
    ('Giriboy', 'Vice Versa', 'Vice Versa'),
    ('Giriboy', 'Braille', 'Vice Versa'),
    ('Giriboy', 'Lingering', 'Vice Versa'),
    ('Swings', 'Per se', 'Per se'),
    ('Swings', 'Blueprint 2015', 'Per se'),
    ('Loco', 'WIN', ''),
    ('Ash Island', 'Safety Zone', 'Safety Zone'),
    ('Mirani', 'Drama', 'Drama'),
    ('Dynamic Duo', 'ECO', 'ECO'),
    ('Woodie Gochild', 'Channel Surfing', '#GOchild'),
    ('Woodie Gochild', 'Roller Coaster', '#GOchild'),
    ('Owen Ovadoz', '119', '119'),
    ('Owen Ovadoz', 'Diamond', '119'),
    ('Coogie', 'Re:Up', 'Re:Up'),
    ('Loco', 'Focus', ''),
    ('Swings', 'Reset', 'Per se'),
    ('Ash Island', 'Malibu Night', 'Safety Zone'),
    ('Mirani', 'Kangaroo', 'Drama'),
    ('Dynamic Duo', 'Smoke', 'ECO'),
    ('Woodie Gochild', 'Honest', '#GOchild'),
    ('Owen Ovadoz', 'Freeze', '119'),
]
