TRACKS = [
    ('Changmo', 'MORAESIGYE', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'TAIJI', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Rockstar Lifestyle', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Beretta', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Chronic Love', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Vivienne', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Little Brothers', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Hyperstar', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Hotel Room', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'No Regret', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'Supernova', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'UNDERGROUND ROCKSTAR', 'UNDERGROUND ROCKSTAR'),
    ('Kid Milli', 'Cliché', 'Cliché'),
    ('Kid Milli', 'OFF KEY', 'Cliché'),
    ('Kid Milli', 'BAD BAD', 'Cliché'),
    ('Kid Milli', 'J J J', 'Cliché'),
    ('Kid Milli', 'SIDE FILM', 'Cliché'),
    ('Kid Milli', 'MORE', 'Cliché'),
    ('Kid Milli', 'TAKE IT', 'Cliché'),
    ('Coogie', 'I Got A Feeling', 'I Got A Feeling'),
    ('Beenzino', 'MODERN', 'MODERN'),
    ('Beenzino', "Walkin' on Water", 'MODERN'),
    ('Beenzino', 'Break Down', 'MODERN'),
    ('Beenzino', 'Traveling', 'MODERN'),
    ('PH-1', 'Ninth', 'Ninth'),
    ('PH-1', 'Ninth Sense', 'Ninth'),
    ('Epik High', 'Preach', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Rich Man', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Fan', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Map of the Human Soul', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Lesson Zero', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Middle School Teacher', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'High Technology', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Thank You', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Free Love', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Let Me Hold You', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Hate', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Kill', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Open Your Eyes', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Remember Me?', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Fool', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Wicked', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Am I Wrong', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Criminal Record', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Can You Hear My Heart', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'End of the World', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'The Bad in You', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Self Control', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Passionate Goodbye', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Love Fever', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'We Are One', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Umbrella', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', '1 Minute 1 Second', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Nocturnal Animals', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Caffeine', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Acceptance Speech', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'The Road Not Taken', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'The Cure', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Breathe', 'Epilogue Pt.2'),
    ('Epik High', 'Sleep Tight', 'Epilogue Pt.2'),
    ('Epik High', 'You Are The One For Me', 'Epilogue Pt.2'),
    ('Epik High', 'Catch the Shadow', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'One', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Fly', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Lesson One', 'Epik High Is Epik High Pt. 2'),
    ('Epik High', 'Love Love Love', 'Epik High Is Epik High Pt. 2'),
    ("be'O", 'Countdown', 'Show Me the Money 10'),
    ("be'O", 'Luxury', 'Show Me the Money 10'),
    ("be'O", 'Momentum', 'Show Me the Money 10'),
    ("be'O", 'Healing', 'Show Me the Money 10'),
    ('Koonta', 'KOONTA', 'Show Me the Money 10'),
    ('Dynamic Duo', 'Untouchable', 'Untouchable'),
    ('Lee Young Ji', 'Untouchable', 'Untouchable'),
    ('Crush', 'Rush Hour', 'Rush Hour'),
    ('Ash Island', 'Me n Mine', 'Show Me the Money 10'),
    ('Mirani', 'Villain', 'Show Me the Money 10'),
    ('Mudd the student', 'Nectar', 'Show Me the Money 10'),
    ('Lil Moshpit', 'Good Day', 'Show Me the Money 10'),
    ('Blase', 'ONOFF', 'Show Me the Money 10'),
    ('Woodie Gochild', 'Mud', 'Show Me the Money 10'),
    ('Sokodomo', 'SIGNATURE', 'Show Me the Money 10'),
    ('Owen Ovadoz', 'Diana', 'Show Me the Money 10'),
    ('Lil Boi', 'ONFleek', 'Show Me the Money 10'),
    ('Mino', 'Do You Remember', 'Do You Remember'),
    ('Jay Park', 'To Life', 'To Life'),
    ('Gray', 'Summer Surf', 'Summer Surf'),
    ('Lee Young Ji', 'Witch', 'Witch'),
    ('Jessi', 'Cold Blooded', 'Cold Blooded'),
    ('GroovyRoom', 'Brought the Heat Back', 'Brought the Heat Back'),
    ('Sik-K', 'Brought the Heat Back', 'Brought the Heat Back'),
    ('Paloalto', 'Brought the Heat Back', 'Brought the Heat Back'),
    ('Lee Young Ji', 'O.K?', 'O.K?'),
    ('Dean', '4:44', '4:44'),
    ('Lil Boi', 'Wave', 'Show Me the Money 10'),
    ('Koonta', 'Ambition', 'Show Me the Money 10'),
    ('Mirani', 'Baby Steps', 'Show Me the Money 10'),
    ('Sokodomo', 'Winner', 'Show Me the Money 10'),
    ("be'O", 'Curtain Call', 'Show Me the Money 10'),
    ('Lee Young Ji', 'Yumeyo', '16'),
    ('Lee Young Ji', 'Not Sure', '16'),
]
