TRACKS = [
    ('PH-1', 'MEET N GREET', 'X'),
    ('PH-1', 'OKAY', 'X'),
    ('PH-1', 'PACKITUP!', 'X'),
    ('PH-1', 'CIRCLE', 'X'),
    ('PH-1', 'FLARE', 'X'),
    ('PH-1', 'ZOMBIE', 'X'),
    ('PH-1', 'MALIBU', 'X'),
    ('PH-1', 'PARTY PEEPS', 'X'),
    ('PH-1', 'STAY WITH ME', 'X'),
    ('PH-1', 'GLASS', 'X'),
    ('Coogie', 'Up!', 'Up!'),
    ('Coogie', 'Alright', 'Up!'),
    ('Coogie', 'Money', 'Up!'),
    ('Coogie', 'Loyalty', 'Up!'),
    ('Coogie', 'Justin Bieber', 'Up!'),
    ('Coogie', 'Show Me the Money', 'Up!'),
    ('Coogie', 'Palette', 'Up!'),
    ('Coogie', 'Pick up your phone', 'Up!'),
    ('Kid Milli', 'Beige 0.5', 'Beige 0.5'),
    ('Kid Milli', 'BOOK TRAILER', 'Beige 0.5'),
    ('Kid Milli', 'PROUD', 'Beige 0.5'),
    ('Kid Milli', 'flex', 'Beige 0.5'),
    ('Kid Milli', 'AHHHHHHHHHH', 'Beige 0.5'),
    ('Kid Milli', 'SCORPION', 'Beige 0.5'),
    ('Kid Milli', 'Benzo', ''),
    ('Beenzino', 'Reset', 'Reset'),
    ('Beenzino', 'Melody', 'Reset'),
    ('Beenzino', 'Broken Clock', 'Reset'),
    ('Beenzino', 'Nowitzki', 'Nowitzki'),
    ('Beenzino', 'Statue of Limitations', 'Nowitzki'),
    ('Beenzino', 'Scent of Rain', 'Nowitzki'),
    ('Beenzino', 'Fashion Hoarder', 'Modiversity'),
    ('Beenzino', 'Modiversity', 'Modiversity'),
    ('Changmo', 'METEORITE', 'Meteor'),
    ('Changmo', 'MMMM', 'Meteor'),
    ('Changmo', 'Hip Hop Baby', 'Meteor'),
    ('Changmo', 'Swoosh!', 'Meteor'),
    ('Changmo', 'BAND', 'Meteor'),
    ('Changmo', 'Band Up', 'Band Up'),
    ('Changmo', 'METAVERS', 'Band Up'),
    ('Ash Island', 'Melodies', 'Melodies'),
    ('Ash Island', 'Melody', 'Melodies'),
    ('Ash Island', 'Rainbow', 'Melodies'),
    ('Ash Island', 'Sculpture', 'Melodies'),
    ('Ash Island', 'Nightmare', 'Melodies'),
    ('HAON', 'You and I', 'Melodies'),
    ('HAON', 'Melody', 'Melodies'),
    ('Leellamarz', 'Ale', 'Marz & Ale'),
    ('Leellamarz', '1,2', 'Marz & Ale'),
    ('Leellamarz', 'Marz', 'Marz & Ale'),
    ('Leellamarz', 'Don`t Say That', 'Don`t Say That'),
    ('Giriboy', 'Lonely', 'Lonely'),
    ('Giriboy', 'Because I Love You', 'Lonely'),
    ('Giriboy', 'Band', 'Lonely'),
    ('Nafla', 'understand', 'understand'),
    ('Nafla', 'what is your name', 'understand'),
    ('Loopy', 'ON THE Radar', 'ON THE Radar'),
    ('Loopy', 'Radar', 'ON THE Radar'),
    ('Jay Park', 'Forget About Tomorrow', 'Forget About Tomorrow'),
    ('Jay Park', 'Need That', 'Forget About Tomorrow'),
    ('Jay Park', 'Gonzo', 'Gonzo'),
    ('Loco', 'Hello', 'Hello'),
    ('Loco', 'The Show', 'Hello'),
    ('Loco', 'Warning', 'Hello'),
    ('Loco', 'My Favorite', 'My Favorite'),
    ('Gray', 'summer', 'summer'),
    ('Gray', '00 XX', '00 XX'),
    ('Gray', 'Adios', '00 XX'),
    ('Sik-K', 'Bungee', 'Bungee'),
    ('Sik-K', 'STOPTHAT', ''),
    ('Crush', 'Click Like', 'Click Like'),
    ('Paul Blanco', 'Click Like', 'Click Like'),
    ('Dean', 'Peace', 'Peace'),
    ('Punchnello', 'Winter Blossom', 'Winter Blossom'),
    ('Colde', 'Star', 'Star'),
    ('Colde', 'honestly', 'Star'),
    ('Swings', 'Shook Ones', 'Shook Ones'),
    ('Simon Dominic', 'GOTT', 'GOTT'),
    ('Gaeko', 'Rosetta', 'Rosetta'),
    ('Bobby', 'Lalala', 'Lalala'),
    ('Mino', 'Booker', 'Booker'),
    ('Tablo', 'Birthday', 'Birthday'),
    ('Code Kunst', 'Buckle Up', 'Code Kunst Archive Pack 02'),
    ('Code Kunst', 'Jungle', 'Code Kunst Archive Pack 02'),
    ('Zion.T', 'Spring Dream', 'Zionic'),
    ('TOIL', 'MAZE', 'MAZE'),
    ('Mudd the student', 'Do You Like Haeseon', 'Show Me the Money 9'),
    ('Mudd the student', 'Mockingbird', 'Show Me the Money 9'),
    ('Kid Milli', 'Summer', ''),
    ('Changmo', 'Just the Two of Us', ''),
    ('Changmo', 'SMF', ''),
    ('Loco', 'Wedding', ''),
    ('Loco', 'Aniya', ''),
    ('Jay Park', 'McNasty', ''),
    ('Jay Park', 'B Day', ''),
    ('Zion.T', 'Lonely Christmas', ''),
    ('Punchnello', 'Loveseat', ''),
    ('Punchnello', 'Cream Cheese', ''),
    ('Blase', 'Quote That', ''),
    ('The Quiett', 'Nike', ''),
]
