TRACKS = [
    ('Beenzino', 'Train', ''),
    ('Zico', 'SPOT!', ''),
    ('Zico', 'Earthquake', ''),
    ('Zico', 'ZOOM', ''),
    ('Dean', 'NASA', '3:33'),
    ('Dean', 'Ctrl', '3:33'),
    ('G-Dragon', 'HOME SWEET HOME', ''),
    ('G-Dragon', 'POWER', ''),
    ('G-Dragon', 'TAKE ME', ''),
    ('Changmo', 'Wonderful Days', ''),
    ('Changmo', 'ZOOM', ''),
    ('Heize', 'Fallin\'', ''),
    ('Jay Park', 'Taxi Blurr', ''),
    ('Jay Park', 'Stand Out', ''),
    ('Jay Park', 'Mayday', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Gimme A Minute', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Piece Of Heaven', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Ohx3', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Like I Do', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Dedicated 2 U', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Need To Know', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Sip Ona Lil Sum\'', 'THE ONE YOU WANTED'),
    ('Jay Park', '100 Days', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Foreign', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Never Again', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Love Is Ugly', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Recall', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Chapter', 'THE ONE YOU WANTED'),
    ('Jay Park', 'Your/My', 'THE ONE YOU WANTED'),
    ('Loco', 'random summer night', ''),
    ('Loco', 'Smeraldo Garden Marching Band', ''),
    ('Loco', 'ON FIRE', ''),
    ('Leellamarz', 'Let me go to heaven', ''),
    ('Leellamarz', 'GONE', ''),
    ('Leellamarz', 'Two Pills', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'Japan', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'Fucked', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'Desert Flower', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'Miss Me', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'Can\'t you see me?', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'I Like U', 'STILL YOUNG BOY L'),
    ('Leellamarz', 'Hell yea', 'L&B'),
    ('Leellamarz', 'Let off steam', 'L&B'),
    ('Leellamarz', 'Rise and fall', 'L&B'),
    ('Leellamarz', 'On the top', 'L&B'),
    ('Leellamarz', 'L & B', 'L&B'),
    ('The Quiett', 'LF Intro', 'Luxury Flow'),
    ('The Quiett', 'King Is Back', 'Luxury Flow'),
    ('The Quiett', 'Look Inside', 'Luxury Flow'),
    ('The Quiett', 'UGRS', 'Luxury Flow'),
    ('The Quiett', 'I Won\'t RMX', 'Luxury Flow'),
    ('The Quiett', 'Crystal Crates', 'Luxury Flow'),
    ('The Quiett', 'Mercedes', 'Luxury Flow'),
    ('The Quiett', 'Selfie', 'Luxury Flow'),
    ('The Quiett', 'Last Of Us', 'Luxury Flow'),
    ('The Quiett', 'What\'s Love Now', 'Luxury Flow'),
    ('The Quiett', 'Visionaire', 'Luxury Flow'),
    ('The Quiett', 'Dream', 'Luxury Flow'),
    ('The Quiett', 'After Party', 'Luxury Flow'),
    ('The Quiett', 'Ocean View', 'Luxury Flow'),
    ('The Quiett', 'Usual Suspect', 'Luxury Flow'),
    ('The Quiett', 'Someone Else', 'Luxury Flow'),
    ('Bobby', 'Intro', 'Sir.Robert'),
    ('Bobby', 'Sae', 'Sir.Robert'),
    ('Bobby', 'Why Stop Now', 'Sir.Robert'),
    ('Bobby', 'Harmless', 'Sir.Robert'),
    ('Bobby', 'Hercules!', 'Sir.Robert'),
    ('Bobby', 'Moon', 'Sir.Robert'),
    ('Bobby', 'I\'ll Do That', 'Sir.Robert'),
    ('Bobby', '20s 30s', 'Sir.Robert'),
    ('Bobby', 'Help Me Out O Kill Me Not', 'Sir.Robert'),
    ('Bobby', 'F', 'Sir.Robert'),
    ('Kid Milli', '5AM', 'RAD MILLI'),
    ('Kid Milli', 'Summer Time', 'RAD MILLI'),
    ('Kid Milli', 'Feel Good', 'RAD MILLI'),
    ('Kid Milli', 'Apollo', 'RAD MILLI'),
    ('Kid Milli', 'S/S', 'RAD MILLI'),
    ('Kid Milli', 'Twilight Interlude', 'RAD MILLI'),
    ('Kid Milli', 'Million / Warrior', 'RAD MILLI'),
    ('Kid Milli', 'Foxy Plush', 'RAD MILLI'),
    ('Kid Milli', 'Need U', 'RAD MILLI'),
    ('Kid Milli', 'Talk Too Much', 'RAD MILLI'),
    ('Kid Milli', '술', 'RAD MILLI'),
    ('Kid Milli', 'Silence', 'RAD MILLI'),
    ('Kid Milli', 'Jab', '+'),
    ('Kid Milli', 'Link in Bio', '+'),
    ('Kid Milli', 'Freestylin\'', '+'),
    ('Kid Milli', 'High Fashion', '+'),
    ('Kid Milli', 'MMM', '+'),
    ('Kid Milli', 'Downtown', '+'),
    ('Kid Milli', 'Revenge Season', '+'),
    ('Kid Milli', 'Bet', '++'),
    ('Coogie', 'ON FIRE', ''),
    ('Coogie', 'Crystal Crates', 'Luxury Flow'),
    ('Changmo', 'UGRS', 'Luxury Flow'),
    ('PH-1', 'FLAT COKE', ''),
    ('Crush', 'Yes or No', ''),
    ('Paloalto', 'GONE', ''),
    ('Punchnello', 'before you', ''),
    ('Leellamarz', 'Mercedes', 'Luxury Flow'),
]
