TRACKS = [
    ('G-Dragon', 'Too Bad', 'Übermensch'),
    ('G-Dragon', 'Drama', 'Übermensch'),
    ('G-Dragon', 'Ibelongiiu', 'Übermensch'),
    ('G-Dragon', 'Bonamana', 'Übermensch'),
    ('G-Dragon', 'Gyro-Drop', 'Übermensch'),
    ('PH-1', 'GOSHA', 'WHAT HAVE WE DONE'),
    ('PH-1', 'Show Must Go On', ''),
    ('PH-1', 'WHAT HAVE WE DONE', 'WHAT HAVE WE DONE'),
    ('PH-1', 'PARTY PPL', 'WHAT HAVE WE DONE'),
    ('PH-1', 'KEEP IT ON THE LOW', 'WHAT HAVE WE DONE'),
    ('PH-1', 'MY B', 'WHAT HAVE WE DONE'),
    ('PH-1', 'BAKA', 'WHAT HAVE WE DONE'),
    ('PH-1', 'CRASHINNN OUTTT!!!', 'WHAT HAVE WE DONE'),
    ('PH-1', 'ERYKAH BADU', 'WHAT HAVE WE DONE'),
    ('PH-1', 'DRUGGED2THRILLS', 'WHAT HAVE WE DONE'),
    ('PH-1', '54321', 'WHAT HAVE WE DONE'),
    ('PH-1', 'EASY', 'WHAT HAVE WE DONE'),
    ('PH-1', 'SUMMER FEVER', 'WHAT HAVE WE DONE'),
    ('PH-1', 'COVERED IN RAIN', 'WHAT HAVE WE DONE'),
    ('PH-1', 'HAD I KNOWN', 'WHAT HAVE WE DONE'),
    ('PH-1', 'SOAK IN BLUE', 'WHAT HAVE WE DONE'),
    ('Coogie', 'Flame', 'UPSET'),
    ('Coogie', 'Shut Up', 'UPSET'),
    ('Coogie', 'Spaceship', 'UPSET'),
    ('Coogie', 'Two Pills', 'UPSET'),
    ('Coogie', 'BABYFACE', 'UPSET'),
    ('Coogie', 'Arikari', 'UPSET'),
    ('Coogie', 'Sober', 'UPSET'),
    ('Coogie', 'Focus on me', 'UPSET'),
    ('Coogie', 'Can\'t get enough', 'UPSET'),
    ('Coogie', 'What u say?', 'UPSET'),
    ('Coogie', 'Coogie and I', 'UPSET'),
    ('Zico', 'Shut Up', 'UPSET'),
    ('Loco', 'Can\'t get enough', 'UPSET'),
    ('The Quiett', 'BABYFACE', 'UPSET'),
    ('Loco', 'Matcha High', ''),
    ('Loco', 'work++', 'SCRAPS'),
    ('Loco', 'Dam', 'SCRAPS'),
    ('Loco', 'Eh freestyle', 'SCRAPS'),
    ('Loco', 'OMG', 'SCRAPS'),
    ('Loco', 'No where', 'SCRAPS'),
    ('Loco', 'radio', 'SCRAPS'),
    ('Loco', 'automatic', 'SCRAPS'),
    ('Loco', 'Papago', 'SCRAPS'),
    ('Loco', 'Skoo / S.A', 'SCRAPS'),
    ('Jay Park', 'Keep It Sexy', ''),
    ('Jay Park', 'Remedy', ''),
    ('Crush', 'UP ALL NITE', 'FANG'),
    ('Crush', '2-5-1', 'FANG'),
    ('Crush', 'FREQUENCY', 'FANG'),
    ('Crush', 'MALIBU', 'FANG'),
    ('Crush', 'MAMMAMIA', 'FANG'),
    ('Crush', 'OVERLAP', 'FANG'),
    ('Blase', 'INDUSTRY', 'SELF MADE'),
    ('Blase', '12345678', 'SELF MADE'),
    ('Blase', 'KKUCKDARI', 'SELF MADE'),
    ('Blase', 'BREAKERS', 'SELF MADE'),
    ('Blase', 'CANVAS', 'SELF MADE'),
    ('Blase', 'HIDE IN MA DAY', 'SELF MADE'),
    ('Blase', 'MANIFESTER', 'SELF MADE'),
    ('Heize', 'Love Virus', 'LOVE VIRUS Pt.1'),
    ('Heize', 'Last Taxi', 'LOVE VIRUS Pt.1'),
    ('Heize', 'All Because of You', 'LOVE VIRUS Pt.1'),
    ('Heize', 'You made Me', 'LOVE VIRUS Pt.1'),
    ('Heize', 'The Last Hello', 'LOVE VIRUS Pt.1'),
    ('Heize', 'Forget me not until you die.', 'LOVE VIRUS Pt.1'),
    ('Heize', 'Even if', ''),
    ('Gray', 'SLIDIN\'', ''),
    ('Dean', 'Nocturne 07 (for aerse)', ''),
    ('Changmo', 'HOLDUP', 'Op.1'),
    ('Changmo', 'ANTHEM', 'Op.1'),
    ('Changmo', 'Fadeout', 'Op.2'),
    ('Changmo', 'Intermezzo', 'Op.2'),
    ('Changmo', 'If I Had Time', 'Op.2'),
    ('Zion.T', 'LOVE ME', 'POSER'),
    ('Zion.T', 'Heroine', 'POSER'),
    ('Zion.T', 'Suspicious', 'POSER'),
    ('Zion.T', 'Fish', 'POSER'),
    ('Zion.T', 'CLOSER', 'POSER'),
    ('Lil Moshpit', 'K-FLIP', 'K-FLIP+'),
    ('Lil Moshpit', 'KC2', 'K-FLIP+'),
    ('Lil Moshpit', 'LALALA', 'K-FLIP+'),
    ('Lil Moshpit', 'INTERLUDE', 'K-FLIP+'),
    ('Lil Moshpit', 'SELF HATE', 'K-FLIP+'),
    ('Lil Moshpit', 'PUBLIC ENEMY', 'K-FLIP+'),
    ('Lil Moshpit', 'MADE IN KCOREA', 'K-FLIP+'),
    ('Lil Moshpit', 'LOV3', 'K-FLIP+'),
    ('Lil Moshpit', 'NEW ANTHEM', 'K-FLIP+'),
    ('Tablo', 'Stop the Rain', ''),
    ('Epik High', 'Stop the Rain', ''),
    ('Colde', 'Reno', ''),
    ('Punchnello', 'F', ''),
    ('TOIL', '염염상망', ''),
    ('Loopy', 'DOPE', 'SEOUL pt.A'),
    ('Loopy', 'DEAD MAN WALKING', 'SEOUL pt.A'),
    ('Loopy', 'BAD KUROMI GAL', 'SEOUL pt.A'),
    ('Loopy', 'PINK SPILL', 'SEOUL pt.A'),
    ('Loopy', 'YOU\'D BETTER', 'SEOUL pt.A'),
    ('Loopy', 'CROWN', 'SEOUL pt.A'),
    ('Punchnello', 'Midnight Glow', ''),
]
