// Auto-generated by app/scripts/sync-nrm-brand.mjs — do not edit by hand.
enum NrmBrand {
  static let storageFolderName = "NullReferenceMusic"
  static func userAgent(version: String) -> String {
    "\(storageFolderName)/\(version)"
  }
}
