export default [
  ["Epik High", "Run", "Epilogue"],
  ["Dynamic Duo", "Without You", "Band of Dynamic Brothers"],
  ["Leessang", "Appetite for Life", "Hexagonal"],
  ["Tiger JK", "Monster", "Feel gHood Muzik : The 8th Wonderland"],
  ["Yoon Mirae", "Get It In", ""],
  ["Supreme Team", "Then Then Then", "Supreme Team Guide to Absolute Respect"],
  ["Verbal Jint", "Ready to Die", "Going Down Under"],
  ["Swings", "Tomorrow", "Upgrade"],
  ["Beenzino", "Retro Love", "24:26"],
  ["Primary", "2 Weeks", "Primary And The Messengers LP"],
  ["Dok2", "Yaezy Walks", "Thug Life"],
  ["Simon Dominic", "Simon Dominic Part 2", "Simon Dominic Part 2"],
  ["Zico", "Tough Cookie", "O.M.M"],
  ["Mad Clown", "Loving U", "Heoteoge Sarang"],
  ["Dynamic Duo", "Think", "Band of Dynamic Brothers"],
  ["Leessang", "Can't Break Up", "Hexagonal"],
  ["Yoon Mirae", "Where My Heart Is", ""],
  ["Supreme Team", "Dding Ddong Dding Ddong", "Supreme Team Guide to Absolute Respect"],
  ["Verbal Jint", "The Great", "Going Down Under"],
  ["Beenzino", "Starlight", "24:26"],
  ["Primary", "Ticket", "Primary And The Messengers LP"],
  ["Simon Dominic", "180 Degree Turn", "Simon Dominic Part 2"],
  ["Zico", "O.M.M", "O.M.M"],
  ["Baechigi", "Shark's Tale", "Shark's Tale"],
  ["Vasco", "The Bill", "The Bill"],
  ["JJK", "Go-Back", "Go-Back"],
  ["Outsider", "Loner", "Vol.2-Maestro"],
  ["Ga Eun", "Tears", ""],
  ["Geologic", "Hero", "Hero"],
  ["MC Meta", "Icarus", "The Blue Printz"],
  ["Rhymer", "You and I", "Rhymer Trax Vol.1"],
  ["Deepflow", "Come Back Home", "Flow the Life"],
  ["The Quiett", "Can You?", "Can You?"],
  ["Don Mills", "Don Mills Is Angry", "Don Mills Is Angry"],
  ["Huckleberry P", "Mantra", "Mantra"],
  ["Paloalto", "Imagination", "Imagination"],
  ["Kebee", "On Our Own", "On Our Own"],
  ["Myun Do One", "Myun Do One Is Back", "Myun Do One Is Back"],
  ["J'Kyun", "Ready to Fly", "Ready to Fly"],
  ["Illinit", "Illmatic", "Illmatic"],
  ["Sean2Slow", "Slow Jam", "Slow Jam"],
  ["Skull", "La La La", "Skull & Haha"],
  ["Mighty Mouth", "Good Good Feeling", "Mighty Style"],
  ["San E", "LoveSick", "Ready for Showtime"],
  ["Swings", "I'll Be There", "Upgrade"],
  ["Jinbo", "555", "555"],
  ["E-Sens", "Poison", ""],
  ["Tablo", "Tomorrow", "Tomorrow"],
  ["Epik High", "Clutch", "Epilogue"],
  ["Dynamic Duo", "Go Away", "Band of Dynamic Brothers"],
  ["Leessang", "Hexagonal", "Hexagonal"],
  ["Tiger JK", "8th Wonderland", "Feel gHood Muzik : The 8th Wonderland"],
  ["Yoon Mirae", "Black Happiness", ""],
  ["Supreme Team", "Super Supremes", "Supreme Team Guide to Absolute Respect"],
  ["Verbal Jint", "Desperado", "Going Down Under"],
  ["Beenzino", "Dali, Van, Picasso", "24:26"],
  ["Primary", "Love Me or Leave Me", "Primary And The Messengers LP"],
  ["Dok2", "Thug Life", "Thug Life"],
  ["Simon Dominic", "Cheongdamdong Madonna", "Simon Dominic Part 2"],
  ["Zico", "I Love U", "O.M.M"],
  ["Mad Clown", "Fire", "Heoteoge Sarang"],
  ["Baechigi", "Time to Love", "Shark's Tale"],
  ["Vasco", "Money", "The Bill"],
  ["JJK", "My Story", "Go-Back"],
  ["Outsider", "Maestro", "Vol.2-Maestro"],
  ["Geologic", "The Geologic", "Hero"],
  ["MC Meta", "The Blue Printz", "The Blue Printz"],
  ["Rhymer", "Brand New Day", "Rhymer Trax Vol.1"],
  ["Deepflow", "Flow the Life", "Flow the Life"],
  ["The Quiett", "Money and the Power", "Can You?"],
  ["Don Mills", "Bang", "Don Mills Is Angry"],
  ["Huckleberry P", "The Great Escape", "Mantra"],
  ["Paloalto", "Top Primary", "Imagination"],
  ["Kebee", "Ecstasy", "On Our Own"],
  ["Myun Do One", "One Mic", "Myun Do One Is Back"],
  ["J'Kyun", "Fly Away", "Ready to Fly"],
  ["Illinit", "Real Talk", "Illmatic"],
  ["Sean2Slow", "Slow Down", "Slow Jam"],
  ["Skull", "Haha Song", "Skull & Haha"],
  ["Mighty Mouth", "Mighty Style", "Mighty Style"],
  ["San E", "Ready for Showtime", "Ready for Showtime"],
  ["Swings", "Upgrade", "Upgrade"],
  ["Jinbo", "V", "555"],
  ["E-Sens", "You Can't Control Me", ""],
  ["Tablo", "Bad", "Tomorrow"],
  ["Epik High", "Breakdown", "Epilogue"],
  ["Dynamic Duo", "Valuable Player", "Band of Dynamic Brothers"],
  ["Leessang", "The Girl Who Can't Break Up", "Hexagonal"],
  ["Tiger JK", "Push It", "Feel gHood Muzik : The 8th Wonderland"],
  ["Yoon Mirae", "Goodbye", ""],
  ["Supreme Team", "Respect", "Supreme Team Guide to Absolute Respect"],
  ["Verbal Jint", "Walking in the Rain", "Going Down Under"],
  ["Beenzino", "I'll Be There", "24:26"],
  ["Primary", "Happy Ending", "Primary And The Messengers LP"],
  ["Dok2", "88", "Thug Life"],
  ["Simon Dominic", "Gotta Do", "Simon Dominic Part 2"],
  ["Zico", "Dead Inside", "O.M.M"],
  ["Mad Clown", "Insane Love", "Heoteoge Sarang"],
  ["Baechigi", "Face Off", "Shark's Tale"],
  ["Vasco", "Real Talk", "The Bill"],
];
