export default [
  ["Beenzino", "Nike Shoes", "City Life"],
  ["Beenzino", "City Life", "City Life"],
  ["Beenzino", "Drowning", "City Life"],
  ["Verbal Jint", "Good Morning", "Rap Genius No. 7"],
  ["Verbal Jint", "You Deserve Better", "Rap Genius No. 7"],
  ["Verbal Jint", "If I Die", "Rap Genius No. 7"],
  ["Swings", "Witch Hunt", "Upgrade II"],
  ["Swings", "Heavy Smoker", "Upgrade II"],
  ["Swings", "Silence", "Upgrade II"],
  ["Zico", "See My Rap", "Zico on the Block"],
  ["Zico", "Tick Tock", "Zico on the Block"],
  ["Zico", "No Limit", "Zico on the Block"],
  ["Leessang", "The Rain", "Unplugged on the Sofa"],
  ["Leessang", "Recollection", "Unplugged on the Sofa"],
  ["Leessang", "Wipe", "Unplugged on the Sofa"],
  ["Epik High", "Up", "Epilogue"],
  ["Jay Park", "Mommae", "Take a Deeper Look"],
  ["Jay Park", "Abandoned", "Take a Deeper Look"],
  ["Jay Park", "Bestie", "Take a Deeper Look"],
  ["Jay Park", "Know Your Name", "Take a Deeper Look"],
  ["Jay Park", "Welcome to the Concrete", "Take a Deeper Look"],
  ["Primary", "Johnny", "Primary And The Messengers LP"],
  ["Primary", "Question Mark", "Primary And The Messengers LP"],
  ["Dok2", "It's All Good", "Thug Life Part 2"],
  ["Dok2", "Thug Life Part 2", "Thug Life Part 2"],
  ["Simon Dominic", "I Just Want You", "Simon Dominic Part 2"],
  ["Simon Dominic", "Latte", "Simon Dominic Part 2"],
  ["E-Sens", "The New One", ""],
  ["Dynamic Duo", "Animal", "Band of Dynamic Brothers"],
  ["Geologic", "Geologic", "Geologic"],
  ["San E", "Story of Someone I Know", "Ready for Showtime"],
  ["San E", "Not Cute", "Ready for Showtime"],
  ["Tiger JK", "Payback", "Feel gHood Muzik : The 8th Wonderland"],
  ["Yoon Mirae", "Always", ""],
  ["Mad Clown", "The Quiett Smiles", "Heoteoge Sarang"],
  ["Phantom", "Bubble Love", "Phantom City"],
  ["MellowD", "On My Way", "On My Way"],
  ["Deepflow", "Flow the Life 2", "Flow the Life 2"],
  ["Deepflow", "Come Back Home Pt.2", "Flow the Life 2"],
  ["The Quiett", "Freeze", "Can You?"],
  ["Don Mills", "Go Away", "Don Mills Is Angry 2"],
  ["Huckleberry P", "Woofer", "Mantra 2"],
  ["Paloalto", "Nomad", "Nomad"],
  ["Kebee", "On Our Own Pt.2", "On Our Own"],
  ["Myun Do One", "Bulldozer", "Myun Do One Is Back"],
  ["Illinit", "Ill Street", "Illmatic"],
  ["Sean2Slow", "Slow Jam Pt.2", "Slow Jam"],
  ["Skull", "I'm Your Man", "Skull & Haha"],
  ["Mighty Mouth", "San", "Mighty Style"],
  ["Jinbo", "Call Me", "555"],
  ["Tablo", "Tomorrow's Today", "Tomorrow"],
  ["Baechigi", "Shark's Tale Pt.2", "Shark's Tale"],
  ["Vasco", "Vasco", "The Bill"],
  ["JJK", "Go Back Pt.2", "Go-Back"],
  ["Outsider", "Hero", "Vol.2-Maestro"],
  ["Ga Eun", "Because of You", ""],
  ["MC Meta", "On My Own", "The Blue Printz"],
  ["Rhymer", "Brand New Day Pt.2", "Rhymer Trax Vol.1"],
  ["Double K", "Fly High", "Fly High"],
  ["Pe2ny", "Pe2ny Maker", "Pe2ny Maker"],
  ["TBNY", "Million", "Million"],
  ["Stuck B", "Stuck B", "Stuck B"],
  ["Crown J", "My Friend", "My Friend"],
  ["L.E.O.", "Show Must Go On", "Show Must Go On"],
  ["Swings", "Bulldozer", "Upgrade II"],
  ["Zico", "Extraordinary", "Zico on the Block"],
  ["Beenzino", "Jazz Cafe", "City Life"],
  ["Verbal Jint", "Walking in the Rain (2011 Mix)", "Rap Genius No. 7"],
  ["Jay Park", "Demo", "Take a Deeper Look"],
  ["Primary", "Happy Ending (2011 Mix)", "Primary And The Messengers LP"],
  ["Simon Dominic", "Cheongdamdong Madonna (2011 Mix)", "Simon Dominic Part 2"],
  ["E-Sens", "You Can't Control Me (2011 Mix)", ""],
  ["Dynamic Duo", "Go Away (2011 Mix)", "Band of Dynamic Brothers"],
  ["Geologic", "Blaze", "Geologic"],
  ["San E", "Rap Genius", "Ready for Showtime"],
  ["Tiger JK", "Push It (2011 Mix)", "Feel gHood Muzik : The 8th Wonderland"],
  ["Yoon Mirae", "Goodbye (2011 Mix)", ""],
  ["Mad Clown", "Fire (2011 Mix)", "Heoteoge Sarang"],
  ["Phantom", "Phantom City", "Phantom City"],
  ["MellowD", "MellowD", "On My Way"],
  ["Deepflow", "Flow the Life (2011 Mix)", "Flow the Life 2"],
  ["The Quiett", "Can You? (2011 Mix)", "Can You?"],
  ["Don Mills", "Don Mills Is Angry (2011 Mix)", "Don Mills Is Angry 2"],
  ["Huckleberry P", "Mantra (2011 Mix)", "Mantra 2"],
  ["Paloalto", "Imagination (2011 Mix)", "Nomad"],
  ["Kebee", "Ecstasy (2011 Mix)", "On Our Own"],
  ["Myun Do One", "One Mic (2011 Mix)", "Myun Do One Is Back"],
  ["J'Kyun", "Fly Away (2011 Mix)", "Ready to Fly"],
  ["Illinit", "Real Talk (2011 Mix)", "Illmatic"],
  ["Sean2Slow", "Slow Down (2011 Mix)", "Slow Jam"],
  ["Skull", "Haha Song (2011 Mix)", "Skull & Haha"],
  ["Mighty Mouth", "Good Good Feeling (2011 Mix)", "Mighty Style"],
  ["Jinbo", "V (2011 Mix)", "555"],
  ["Tablo", "Bad (2011 Mix)", "Tomorrow"],
  ["Baechigi", "Time to Love (2011 Mix)", "Shark's Tale"],
  ["Vasco", "Money (2011 Mix)", "The Bill"],
  ["JJK", "My Story (2011 Mix)", "Go-Back"],
  ["Outsider", "Maestro (2011 Mix)", "Vol.2-Maestro"],
  ["Ga Eun", "Tears (2011 Mix)", ""],
  ["MC Meta", "Icarus (2011 Mix)", "The Blue Printz"],
];
