export default [
  { artist: "Epik High", title: "Run", album: "Epilogue" },
  { artist: "Dynamic Duo", title: "Without You", album: "Band of Dynamic Brothers" },
  { artist: "Leessang", title: "Appetite for Life", album: "Hexagonal" },
  { artist: "Tiger JK", title: "Monster", album: "Feel gHood Muzik : The 8th Wonderland" },
  { artist: "Yoon Mirae", title: "Get It In", album: "" },
  { artist: "Supreme Team", title: "Then Then Then", album: "Supreme Team Guide to Absolute Respect" },
  { artist: "Verbal Jint", title: "Ready to Die", album: "Going Down Under" },
  { artist: "Swings", title: "Tomorrow", album: "Upgrade" },
  { artist: "Beenzino", title: "Retro Love", album: "24:26" },
  { artist: "Primary", title: "2 Weeks", album: "Primary And The Messengers LP" },
  { artist: "Dok2", title: "Yaezy Walks", album: "Thug Life" },
  { artist: "Simon Dominic", title: "Simon Dominic Part 2", album: "Simon Dominic Part 2" },
  { artist: "Zico", title: "Tough Cookie", album: "O.M.M" },
  { artist: "Mad Clown", title: "Loving U", album: "Heoteoge Sarang" },
  { artist: "Dynamic Duo", title: "Think", album: "Band of Dynamic Brothers" },
  { artist: "Leessang", title: "Can't Break Up", album: "Hexagonal" },
  { artist: "Yoon Mirae", title: "Where My Heart Is", album: "" },
  { artist: "Supreme Team", title: "Dding Ddong Dding Ddong", album: "Supreme Team Guide to Absolute Respect" },
  { artist: "Verbal Jint", title: "The Great", album: "Going Down Under" },
  { artist: "Beenzino", title: "Starlight", album: "24:26" },
  { artist: "Primary", title: "Ticket", album: "Primary And The Messengers LP" },
  { artist: "Simon Dominic", title: "180 Degree Turn", album: "Simon Dominic Part 2" },
  { artist: "Zico", title: "O.M.M", album: "O.M.M" },
  { artist: "Baechigi", title: "Shark's Tale", album: "Shark's Tale" },
  { artist: "Vasco", title: "The Bill", album: "The Bill" },
  { artist: "JJK", title: "Go-Back", album: "Go-Back" },
  { artist: "Outsider", title: "Loner", album: "Vol.2-Maestro" },
  { artist: "Ga Eun", title: "Tears", album: "" },
  { artist: "Geologic", title: "Hero", album: "Hero" },
  { artist: "MC Meta", title: "Icarus", album: "The Blue Printz" },
  { artist: "Rhymer", title: "You and I", album: "Rhymer Trax Vol.1" },
  { artist: "Deepflow", title: "Come Back Home", album: "Flow the Life" },
  { artist: "The Quiett", title: "Can You?", album: "Can You?" },
  { artist: "Don Mills", title: "Don Mills Is Angry", album: "Don Mills Is Angry" },
  { artist: "Huckleberry P", title: "Mantra", album: "Mantra" },
  { artist: "Paloalto", title: "Imagination", album: "Imagination" },
  { artist: "Kebee", title: "On Our Own", album: "On Our Own" },
  { artist: "Myun Do One", title: "Myun Do One Is Back", album: "Myun Do One Is Back" },
  { artist: "J'Kyun", title: "Ready to Fly", album: "Ready to Fly" },
  { artist: "Illinit", title: "Illmatic", album: "Illmatic" },
  { artist: "Sean2Slow", title: "Slow Jam", album: "Slow Jam" },
  { artist: "Skull", title: "La La La", album: "Skull & Haha" },
  { artist: "Mighty Mouth", title: "Good Good Feeling", album: "Mighty Style" },
  { artist: "San E", title: "LoveSick", album: "Ready for Showtime" },
  { artist: "Swings", title: "I'll Be There", album: "Upgrade" },
  { artist: "Jinbo", title: "555", album: "555" },
  { artist: "E-Sens", title: "Poison", album: "" },
  { artist: "Tablo", title: "Tomorrow", album: "Tomorrow" },
  { artist: "Epik High", title: "Clutch", album: "Epilogue" },
  { artist: "Dynamic Duo", title: "Go Away", album: "Band of Dynamic Brothers" },
  { artist: "Leessang", title: "Hexagonal", album: "Hexagonal" },
  { artist: "Tiger JK", title: "8th Wonderland", album: "Feel gHood Muzik : The 8th Wonderland" },
  { artist: "Yoon Mirae", title: "Black Happiness", album: "" },
  { artist: "Supreme Team", title: "Super Supremes", album: "Supreme Team Guide to Absolute Respect" },
  { artist: "Verbal Jint", title: "Desperado", album: "Going Down Under" },
  { artist: "Beenzino", title: "Dali, Van, Picasso", album: "24:26" },
  { artist: "Primary", title: "Love Me or Leave Me", album: "Primary And The Messengers LP" },
  { artist: "Dok2", title: "Thug Life", album: "Thug Life" },
  { artist: "Simon Dominic", title: "Cheongdamdong Madonna", album: "Simon Dominic Part 2" },
  { artist: "Zico", title: "I Love U", album: "O.M.M" },
  { artist: "Mad Clown", title: "Fire", album: "Heoteoge Sarang" },
  { artist: "Baechigi", title: "Time to Love", album: "Shark's Tale" },
  { artist: "Vasco", title: "Money", album: "The Bill" },
  { artist: "JJK", title: "My Story", album: "Go-Back" },
  { artist: "Outsider", title: "Maestro", album: "Vol.2-Maestro" },
  { artist: "Geologic", title: "The Geologic", album: "Hero" },
  { artist: "MC Meta", title: "The Blue Printz", album: "The Blue Printz" },
  { artist: "Rhymer", title: "Brand New Day", album: "Rhymer Trax Vol.1" },
  { artist: "Deepflow", title: "Flow the Life", album: "Flow the Life" },
  { artist: "The Quiett", title: "Money and the Power", album: "Can You?" },
  { artist: "Don Mills", title: "Bang", album: "Don Mills Is Angry" },
  { artist: "Huckleberry P", title: "The Great Escape", album: "Mantra" },
  { artist: "Paloalto", title: "Top Primary", album: "Imagination" },
  { artist: "Kebee", title: "Ecstasy", album: "On Our Own" },
  { artist: "Myun Do One", title: "One Mic", album: "Myun Do One Is Back" },
  { artist: "J'Kyun", title: "Fly Away", album: "Ready to Fly" },
  { artist: "Illinit", title: "Real Talk", album: "Illmatic" },
  { artist: "Sean2Slow", title: "Slow Down", album: "Slow Jam" },
  { artist: "Skull", title: "Haha Song", album: "Skull & Haha" },
  { artist: "Mighty Mouth", title: "Mighty Style", album: "Mighty Style" },
  { artist: "San E", title: "Ready for Showtime", album: "Ready for Showtime" },
  { artist: "Swings", title: "Upgrade", album: "Upgrade" },
  { artist: "Jinbo", title: "V", album: "555" },
  { artist: "E-Sens", title: "You Can't Control Me", album: "" },
  { artist: "Tablo", title: "Bad", album: "Tomorrow" },
  { artist: "Epik High", title: "Breakdown", album: "Epilogue" },
  { artist: "Dynamic Duo", title: "Valuable Player", album: "Band of Dynamic Brothers" },
  { artist: "Leessang", title: "The Girl Who Can't Break Up", album: "Hexagonal" },
  { artist: "Tiger JK", title: "Push It", album: "Feel gHood Muzik : The 8th Wonderland" },
  { artist: "Yoon Mirae", title: "Goodbye", album: "" },
  { artist: "Supreme Team", title: "Respect", album: "Supreme Team Guide to Absolute Respect" },
  { artist: "Verbal Jint", title: "Walking in the Rain", album: "Going Down Under" },
  { artist: "Beenzino", title: "I'll Be There", album: "24:26" },
  { artist: "Primary", title: "Happy Ending", album: "Primary And The Messengers LP" },
  { artist: "Dok2", title: "88", album: "Thug Life" },
  { artist: "Simon Dominic", title: "Gotta Do", album: "Simon Dominic Part 2" },
  { artist: "Zico", title: "Dead Inside", album: "O.M.M" },
  { artist: "Mad Clown", title: "Insane Love", album: "Heoteoge Sarang" },
  { artist: "Baechigi", title: "Face Off", album: "Shark's Tale" },
  { artist: "Vasco", title: "Real Talk", album: "The Bill" },
];
