#!/usr/bin/env python3
"""One-shot builder for y2013-y2017 real catalog modules."""
from __future__ import annotations
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), "real_catalog_data")

REAL_YEARS: dict[int, list[tuple[str, str, str]]] = {
    2013: [
        ("Dynamic Duo", "Return Of The Kings", "Lucky Numbers"),
        ("Dynamic Duo", "Three Dopeboyz", "Lucky Numbers"),
        ("Dynamic Duo", "Life Is Good", "Lucky Numbers"),
        ("Dynamic Duo", "BAAAM", "Lucky Numbers"),
        ("Dynamic Duo", "Airplane Mode", "Lucky Numbers"),
        ("Dynamic Duo", "Lee Dae Ho", "Lucky Numbers"),
        ("Dynamic Duo", "Shoot Goal In", "Lucky Numbers"),
        ("Dynamic Duo", "Hot Wings", "Lucky Numbers"),
        ("Dynamic Duo", "Good Morning Love", "Lucky Numbers"),
        ("Dynamic Duo", "Tragedy Part 2", "Lucky Numbers"),
        ("Dynamic Duo", "Crime Scene", "Lucky Numbers"),
        ("Dean", "130613", ""),
        ("Beenzino", "Dali, Van, Picasso", ""),
        ("Zion.T", "O", "Red Light"),
        ("Zion.T", "Doop", "Red Light"),
        ("Zion.T", "Dodohae", "Red Light"),
        ("Zion.T", "She", "Red Light"),
        ("Zion.T", "Neon", "Red Light"),
        ("Zion.T", "Babay", "Red Light"),
        ("Zion.T", "Global Warming", "Red Light"),
        ("Zion.T", "Two Melodies", "Red Light"),
        ("Zion.T", "Spin Spin", "Mirrorball"),
        ("Zion.T", "Modern Boy", "Mirrorball"),
        ("Zion.T", "Miss Kim", "Mirrorball"),
        ("Zion.T", "Madame", "Mirrorball"),
        ("Giriboy", "Skit", ""),
        ("Giriboy", "Wake Up", ""),
        ("Giriboy", "Lowlife", ""),
        ("Gray", "In My Head", "Call Me Gray"),
        ("Gray", "Dream Chaser", "Call Me Gray"),
        ("Gray", "Summer Night", "Call Me Gray"),
        ("Loco", "Take Care", ""),
        ("Zico", "I Got 97 on My Test", ""),
        ("Primary", "eeee", ""),
        ("Primary", "Amigo", ""),
        ("Dok2", "Good Vibes Only", "Ruthless, The Album"),
        ("Dok2", "1LLIN", "Ruthless, The Album"),
        ("Dok2", "Hell Yeah", "Ruthless, The Album"),
        ("Dok2", "All I Know", "Ruthless, The Album"),
        ("Dok2", "Outchea", "Ruthless, The Album"),
        ("Dok2", "Zero", "Ruthless, The Album"),
        ("Dok2", "No More", "Ruthless, The Album"),
        ("Dok2", "My Dreams Do Come True", "Ruthless, The Album"),
        ("Dok2", "Oh Yeah", "Ruthless, The Album"),
        ("Dok2", "Runnin'", "Ruthless, The Album"),
        ("Dok2", "Bandz & Benz", "Ruthless, The Album"),
        ("Dok2", "Handz Up", "Ruthless, The Album"),
        ("Jinbo", "Neon Pink Ocean", "Fantasy"),
        ("Jinbo", "Fantasy", "Fantasy"),
        ("Jinbo", "Cops Come Knock", "Fantasy"),
        ("Jinbo", "Tape It Slow Baby", "Fantasy"),
        ("Jinbo", "Loverbot", "Fantasy"),
        ("Jinbo", "Traumatic", "Fantasy"),
        ("Jinbo", "Delete It Deal It", "Fantasy"),
        ("Jinbo", "Reboot My Universe", "Fantasy"),
        ("Jinbo", "Don't Be Sad When You're Sad", "Fantasy"),
        ("Jinbo", "It's Over", "Fantasy"),
        ("Jinbo", "Be My Friend", "Fantasy"),
        ("Crush", "Crush on You", ""),
        ("Crush", "Where Do You Wanna Go", ""),
        ("Gaeko", "Geon Gangs", "Geon Gangs"),
        ("B-Free", "Hot Summer", ""),
        ("B-Free", "Korean Dream Team", ""),
        ("San E", "Show Me the Money", "Show Me the Money 2"),
        ("San E", "Bad Year", ""),
        ("Okasian", "Check-in", "Orca-Tape"),
        ("Okasian", "Don't Front", "Orca-Tape"),
        ("Reddy", "Commitment", "Orca-Tape"),
        ("Jerry.K", "V", "V"),
        ("Jerry.K", "Ready", "V"),
        ("Vasco", "Exodus Announcement", "Guerrilla Muzik Vol.3 Exodos"),
        ("Vasco", "Guerrilla Muzik", "Guerrilla Muzik Vol.3 Exodos"),
        ("Vasco", "No More War", "Guerrilla Muzik Vol.3 Exodos"),
        ("Vasco", "Revolution", "Guerrilla Muzik Vol.3 Exodos"),
        ("Vasco", "The End", "Guerrilla Muzik Vol.3 Exodos"),
        ("Vasco", "Exodus", "Guerrilla Muzik Vol.3 Exodos"),
        ("The Quiett", "Green Light", ""),
        ("The Quiett", "11:11", "11:11"),
        ("Paloalto", "Good Morning Seoul", ""),
        ("Paloalto", "Sunday", ""),
        ("Mad Clown", "Oppa Thoughts", ""),
        ("Leessang", "Ballerino", ""),
        ("Tiger JK", "Monologue", ""),
        ("Swings", "Swings #1 Vol. II", ""),
        ("E-Sens", "Black Suit", ""),
        ("Lil Boi", "Ferris Wheel", ""),
        ("G2", "Online", ""),
        ("Owen Ovadoz", "P", ""),
        ("Deepflow", "Good Day", ""),
        ("Don Mills", "Zero", ""),
        ("Kebee", "Call Me", ""),
        ("Beenzino", "Illionaire Gang", "11:11"),
        ("Gray", "Blink", ""),
        ("Bumkey", "When I Wake Up", ""),
        ("Junggigo", "Going Crazy", ""),
        ("Verbal Jint", "Rap Genius No. 8 Intro", "Rap Genius No. 8"),
        ("Verbal Jint", "Desperado", "Rap Genius No. 8"),
        ("Verbal Jint", "Walking in the Rain", "Rap Genius No. 8"),
        ("Illinit", "Ill Street Live", ""),
        ("Outsider", "Loner 2", "Vol.2-Maestro"),
        ("Phantom", "Bubble Love", "Phantom City"),
        ("MellowD", "MellowD", "On My Way"),
        ("Geologic", "Blaze", "Geologic"),
        ("MC Meta", "On My Own", "The Blue Printz"),
        ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        ("J'Kyun", "Fly Away", "Ready to Fly"),
        ("Sean2Slow", "Slow Down", "Slow Jam"),
        ("Skull", "I'm Your Man", "Skull & Haha"),
        ("Mighty Mouth", "San", "Mighty Style"),
    ],
    2014: [
        ("Epik High", "Encore", "Shoebox"),
        ("Epik High", "Happen Ending", "Shoebox"),
        ("Epik High", "Rich", "Shoebox"),
        ("Epik High", "Spoiler", "Shoebox"),
        ("Epik High", "Burj Khalifa", "Shoebox"),
        ("Epik High", "We Fight Ourselves", "Shoebox"),
        ("Epik High", "Amor Fati", "Shoebox"),
        ("Epik High", "Born Hater", "Shoebox"),
        ("Epik High", "Lesson 5", "Shoebox"),
        ("Epik High", "Life Is Good", "Shoebox"),
        ("Epik High", "Eyes, Nose, Lips", "Shoebox"),
        ("Epik High", "Shoebox", "Shoebox"),
        ("Jay Park", "Evolution", "Evolution"),
        ("Jay Park", "Joah", "Evolution"),
        ("Jay Park", "So Good", "Evolution"),
        ("Jay Park", "Welcome to the Concrete", "Evolution"),
        ("Jay Park", "I Like You", "Evolution"),
        ("Jay Park", "Zero", "Evolution"),
        ("Jay Park", "Yacht", "Evolution"),
        ("Jay Park", "Metronome", "Evolution"),
        ("Jay Park", "I Like 2 Party", "Evolution"),
        ("Jay Park", "The Promise", "Evolution"),
        ("Jay Park", "100 Years Hip-Hop", "Evolution"),
        ("Jay Park", "Body 2 Body", "Evolution"),
        ("Crush", "Sometimes", "Crush on You"),
        ("Crush", "Hug Me", "Crush on You"),
        ("Crush", "Sofa", ""),
        ("Crush", "Give It to Me", "Crush on You"),
        ("Beenzino", "Jackson Pollock Dick", "Up All Night"),
        ("Beenzino", "How Do I Look?", "Up All Night"),
        ("Beenzino", "Crazy", "Up All Night"),
        ("Beenzino", "Up All Night", "Up All Night"),
        ("Beenzino", "I Don't Have To Work", "Up All Night"),
        ("Zion.T", "Yanghwa Bridge", ""),
        ("Zion.T", "Zero Gravity", ""),
        ("Bobby", "Secret", "Secret"),
        ("Bobby", "Intro", "Secret"),
        ("Bobby", "Holup!", "Secret"),
        ("Bobby", "Shake It", "Secret"),
        ("Bobby", "Wedding Dress", "Secret"),
        ("Mino", "Fear", "Fear"),
        ("Mino", "Intro", "Fear"),
        ("Mino", "Body", "Fear"),
        ("Mino", "Freak From Da Soul", "Fear"),
        ("Heize", "After I've Wandered A Bit", ""),
        ("Heize", "Heize", "HEIZE"),
        ("Heize", "Because I Touched You", "HEIZE"),
        ("Heize", "You, Me, Us", "HEIZE"),
        ("Dean", "Put My Hands on You", ""),
        ("Loco", "Hands Up", "Locomotive"),
        ("Loco", "Act Serious", "Locomotive"),
        ("Loco", "You Don't Know", "Locomotive"),
        ("Loco", "Thinking About You", "Locomotive"),
        ("Loco", "No Manners", "Locomotive"),
        ("Loco", "High", "Locomotive"),
        ("Loco", "If I", "Locomotive"),
        ("Loco", "Growing Up", "Locomotive"),
        ("Loco", "Hold Me Tight", "Locomotive"),
        ("Gray", "Let's Fall in Love", "Gray Season 2"),
        ("Gray", "Smile", "Gray Season 2"),
        ("Gray", "Remix 2 Me", "Gray Season 2"),
        ("Giriboy", "Camp", ""),
        ("Swings", "Rain Showers", ""),
        ("Swings", "Hongkiyoung", ""),
        ("E-Sens", "Back In Time", "The Anecdote"),
        ("Dynamic Duo", "A Giant Step", ""),
        ("Primary", "Da Capo", "Da Capo"),
        ("Primary", "JohnLegend", "Da Capo"),
        ("Primary", "Love Me or Leave Me", "Da Capo"),
        ("Primary", "Happy Ending", "Da Capo"),
        ("Punchnello", "If You", "If You"),
        ("Colde", "In Your Eyes", "In Your Eyes"),
        ("Gaeko", "Going Home", "Going Home"),
        ("Zico", "Adult Ceremony", ""),
        ("Zico", "Tough Cookie", "Zico on the Block 1.5"),
        ("San E", "Story of Someone I Know", "Show Me the Money 3"),
        ("Mad Clown", "Fire", "Heoteoge Sarang"),
        ("Dok2", "Thug Life", "Thug Life Part 2"),
        ("Dok2", "It's All Good", "Thug Life Part 2"),
        ("The Quiett", "Q Train", "Q Train"),
        ("Paloalto", "Shining Diamond", "Shining Diamond"),
        ("Deepflow", "Come Back Home", "Flow the Life 3"),
        ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
        ("Kebee", "Rhythm and Poetry", "Rhythm and Poetry"),
        ("Swings", "Growing Pains", "Growing Pains"),
        ("Giriboy", "Different", "Different"),
        ("Vasco", "The Vasco", "The Vasco"),
        ("Jerry.K", "V", "V"),
        ("Okasian", "Airplane Mode", ""),
        ("B-Free", "Hot Summer", ""),
        ("Tablo", "Bad", "Fever's End Pt. 1"),
        ("Tablo", "Tomorrow", "Fever's End Pt. 1"),
        ("Leessang", "Coming of Age Story", ""),
        ("Tiger JK", "Monologue", ""),
        ("Yoon Mirae", "Angel", ""),
        ("Primary", "Mission", "Primary and the Messengers LP 2"),
        ("Junggigo", "Warm", ""),
        ("Bumkey", "When I Wake Up", ""),
        ("Verbal Jint", "Mainstream", "Mainstream"),
        ("Simon Dominic", "Simplize", "Consolation"),
        ("Simon Dominic", "I2", "Consolation"),
        ("Simon Dominic", "Consolation", "Consolation"),
        ("PH-1", "PH1's Day Off", ""),
        ("Nafla", "Mood Indigo", ""),
        ("Loopy", "Mmk", ""),
        ("Kid Milli", "A Swaggy Song Called Kidd", ""),
        ("Changmo", "Rebels", ""),
    ],
    2015: [
        ("E-Sens", "Dice", "The Anecdote"),
        ("E-Sens", "A-G-E", "The Anecdote"),
        ("E-Sens", "Writer's Block", "The Anecdote"),
        ("E-Sens", "Next Level", "The Anecdote"),
        ("E-Sens", "Wobble", "The Anecdote"),
        ("E-Sens", "10.18.14", "The Anecdote"),
        ("E-Sens", "The Anecdote", "The Anecdote"),
        ("E-Sens", "Back In Time", "The Anecdote"),
        ("E-Sens", "Tick Tock", "The Anecdote"),
        ("E-Sens", "Unknown Verses", "The Anecdote"),
        ("Dean", "I Love It", ""),
        ("Dean", "Pour Up", ""),
        ("Dean", "Bonnie & Clyde", ""),
        ("Heize", "And July", "And July"),
        ("Heize", "Because You", "And July"),
        ("Heize", "Underwater", "And July"),
        ("Heize", "No Way", "And July"),
        ("Crush", "Just", ""),
        ("Crush", "Oasis", "Crush on You"),
        ("Jay Park", "WORLDWIDE", "Worldwide"),
        ("Jay Park", "Don't Try Me", "Worldwide"),
        ("Jay Park", "My Last", "Worldwide"),
        ("Jay Park", "MOMMAE", "Worldwide"),
        ("Jay Park", "YOU KNOW", "Worldwide"),
        ("Jay Park", "WHEN", "Worldwide"),
        ("Jay Park", "Want It", "Worldwide"),
        ("Jay Park", "MY", "Worldwide"),
        ("Jay Park", "B-BOY STANCE", "Worldwide"),
        ("Jay Park", "LOTTO", "Worldwide"),
        ("Jay Park", "In This B*tch", "Worldwide"),
        ("Jay Park", "ON IT", "Worldwide"),
        ("Jay Park", "SEATTLE 2 SEOUL", "Worldwide"),
        ("Jay Park", "All I Wanna Do", "Worldwide"),
        ("Zion.T", "Eat", ""),
        ("Zion.T", "No Make Up", ""),
        ("Beenzino", "So What", ""),
        ("Beenzino", "Break", "12"),
        ("Beenzino", "We Are Going To", "12"),
        ("Dynamic Duo", "Grand Carnival", "Grand Carnival"),
        ("Dynamic Duo", "AEAO", "Grand Carnival"),
        ("Dynamic Duo", "Jam", "Grand Carnival"),
        ("Dynamic Duo", "Oasis", "Grand Carnival"),
        ("Dynamic Duo", "Hot Tub Time Machine", "Grand Carnival"),
        ("Loco", "Respect", ""),
        ("Loco", "Awesome", ""),
        ("Gray", "Just Do It", ""),
        ("Gray", "We Don't Love", "Gray Season 2"),
        ("Simon Dominic", "Won & Only", "Won & Only"),
        ("Simon Dominic", "Simon Dominic", "Won & Only"),
        ("Simon Dominic", "Money Don't Lie", "Won & Only"),
        ("Simon Dominic", "Lonely Night", "Won & Only"),
        ("Giriboy", "Back and Forth 30 Min", "Sexual Perceptions"),
        ("Giriboy", "Wu Gyeol", "Sexual Perceptions"),
        ("Giriboy", "Why Do You Live Like This?", ""),
        ("Swings", "I'll Give You Everything", ""),
        ("Punchnello", "Loving You Girl", "Loving You Girl"),
        ("Colde", "Your Dog Loves You", "Your Dog Loves You"),
        ("PH-1", "Good Day", "Good Day"),
        ("PH-1", "Nineteen", "Good Day"),
        ("Nafla", "Natural High", "Natural High"),
        ("Nafla", "Mood Indigo", "Natural High"),
        ("Loopy", "Mmk", "Mmk"),
        ("Loopy", "No More", "Mmk"),
        ("Kid Milli", "A Swaggy Song Called Kidd", "A Swaggy Song Called Kidd"),
        ("Kid Milli", "IndiGO", "IndiGO"),
        ("Changmo", "Rebels", "Rebels"),
        ("Changmo", "Maestro", "Maestro"),
        ("The Quiett", "Green Light", ""),
        ("Paloalto", "Nomad", "Nomad"),
        ("Dok2", "Thug Life", "Thug Life Part 2"),
        ("Zico", "Boys and Girls", "Breakthrough"),
        ("Zico", "Breakthrough", "Breakthrough"),
        ("Bobby", "Holup!", "Holup!"),
        ("Mino", "Fear", "Fear"),
        ("San E", "Not Cute", "Show Me the Money 4"),
        ("Mad Clown", "Fire", "Fire"),
        ("Bumkey", "Attraction", "Single Life"),
        ("Junggigo", "Want U", ""),
        ("Gaeko", "West Coast", "Redingray"),
        ("Okasian", "Celebration", ""),
        ("B-Free", "Korean Dream Team", ""),
        ("Jerry.K", "Ready", "V"),
        ("Huckleberry P", "Mantra 3", "Mantra 3"),
        ("Don Mills", "Go Away", "Don Mills Is Angry 3"),
        ("Tablo", "Eyes, Nose, Lips", "Fever's End Pt. 1"),
        ("Leessang", "Ballerino", ""),
        ("Tiger JK", "Monologue", ""),
        ("Yoon Mirae", "Touch Love", ""),
        ("Primary", "Roller Coaster", "Primary and the Messengers LP 2"),
        ("Simon Dominic", "Make Her Dance", "Won & Only"),
        ("Vasco", "Real Talk", "The Vasco"),
        ("Deepflow", "Flow the Life 3", "Flow the Life 3"),
        ("Kebee", "On Our Own", "On Our Own"),
        ("Verbal Jint", "Good Morning", "Rap Genius No. 8"),
        ("Illinit", "Ill Street Live", ""),
        ("Outsider", "Loner 2", "Vol.2-Maestro"),
        ("Phantom", "Bubble Love", "Phantom City"),
        ("MellowD", "MellowD", "On My Way"),
        ("Geologic", "Blaze", "Geologic"),
        ("MC Meta", "On My Own", "The Blue Printz"),
        ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        ("J'Kyun", "Fly Away", "Ready to Fly"),
        ("Sean2Slow", "Slow Down", "Slow Jam"),
        ("Skull", "I'm Your Man", "Skull & Haha"),
        ("Mighty Mouth", "San", "Mighty Style"),
    ],
    2016: [
        ("Dean", "D (Half Moon)", "130 Mood: TRBL"),
        ("Dean", "Bonnie & Clyde", "130 Mood: TRBL"),
        ("Dean", "21", "130 Mood: TRBL"),
        ("Dean", "Pour Up", "130 Mood: TRBL"),
        ("Dean", "I Love It", "130 Mood: TRBL"),
        ("Dean", "what2do", "130 Mood: TRBL"),
        ("Dean", "Put My Hands on You", "130 Mood: TRBL"),
        ("Crush", "Don't Forget", "Interlude"),
        ("Crush", "9 to 5", "Interlude"),
        ("Crush", "Woo Ah", "Interlude"),
        ("Crush", "Interlude", "Interlude"),
        ("Jay Park", "Drive", "Everything You Wanted"),
        ("Jay Park", "Me Like Yuh", "Everything You Wanted"),
        ("Jay Park", "All I Wanna Do", "Everything You Wanted"),
        ("Jay Park", "Stay With Me", "Everything You Wanted"),
        ("Jay Park", "Solo", "Everything You Wanted"),
        ("Jay Park", "The Truth Is", "Everything You Wanted"),
        ("Jay Park", "Replay", "Everything You Wanted"),
        ("Jay Park", "I Don't Disappoint", "Everything You Wanted"),
        ("Jay Park", "Feature", "Everything You Wanted"),
        ("Jay Park", "Limousine", "Everything You Wanted"),
        ("Jay Park", "Alone Tonight", "Everything You Wanted"),
        ("Jay Park", "Only One", "Everything You Wanted"),
        ("Jay Park", "Aquaman", "Everything You Wanted"),
        ("Jay Park", "2nd Thots", "Everything You Wanted"),
        ("Jay Park", "Forever", "Everything You Wanted"),
        ("Jay Park", "I Got This", "Everything You Wanted"),
        ("Jay Park", "Turn Off Your Phone Remix", "Everything You Wanted"),
        ("Heize", "And July", "And July"),
        ("Heize", "No Way", "And July"),
        ("Zion.T", "Knock", "Show Me the Money 5"),
        ("Beenzino", "12", "12"),
        ("Beenzino", "Break", "12"),
        ("Beenzino", "We Are Going To", "12"),
        ("Beenzino", "Saturday", "12"),
        ("Beenzino", "January", "12"),
        ("Beenzino", "Time Travel", "12"),
        ("Beenzino", "Dali, Van, Picasso", "12"),
        ("Loco", "You Too", ""),
        ("Loco", "Still", ""),
        ("Gray", "Good", ""),
        ("Gray", "Comfortable", "Show Me the Money 5"),
        ("Dynamic Duo", "Highfive", ""),
        ("Primary", "JohnLegend", "Da Capo"),
        ("Crush", "highfive", ""),
        ("Simon Dominic", "Make Her Dance", "Won & Only"),
        ("Punchnello", "If You", "If You"),
        ("Colde", "In Your Eyes", "In Your Eyes"),
        ("Giriboy", "Because", "Mechanical Album"),
        ("Giriboy", "You're Pretty", "Mechanical Album"),
        ("Swings", "Growing Pains", "Growing Pains"),
        ("PH-1", "Good Day", "Good Day"),
        ("PH-1", "Nineteen", "Good Day"),
        ("Nafla", "Natural High", "Natural High"),
        ("Loopy", "Mmk", "Mmk"),
        ("Kid Milli", "IndiGO", "IndiGO"),
        ("Changmo", "Maestro", "Maestro"),
        ("The Quiett", "Green Light", ""),
        ("Paloalto", "Nomad", "Nomad"),
        ("Dok2", "Thug Life", "Thug Life Part 2"),
        ("Zico", "Boys and Girls", "Breakthrough"),
        ("Bobby", "Holup!", "Holup!"),
        ("Mino", "Fear", "Fear"),
        ("San E", "Story of Someone I Know", "Show Me the Money 5"),
        ("Mad Clown", "Fire", "Fire"),
        ("Bumkey", "When I Wake Up", ""),
        ("Junggigo", "Warm", ""),
        ("Gaeko", "Going Home", "Going Home"),
        ("Okasian", "Airplane Mode", ""),
        ("B-Free", "Hot Summer", ""),
        ("Jerry.K", "V", "V"),
        ("Huckleberry P", "Mantra 3", "Mantra 3"),
        ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
        ("Tablo", "Bad", "Fever's End Pt. 1"),
        ("Leessang", "Ballerino", ""),
        ("Tiger JK", "Monologue", ""),
        ("Yoon Mirae", "Angel", ""),
        ("Primary", "Mission", "Primary and the Messengers LP 2"),
        ("Vasco", "The Vasco", "The Vasco"),
        ("Deepflow", "Flow the Life 3", "Flow the Life 3"),
        ("Kebee", "Rhythm and Poetry", "Rhythm and Poetry"),
        ("Verbal Jint", "Mainstream", "Mainstream"),
        ("Illinit", "Ill Street Live", ""),
        ("Outsider", "Loner 2", "Vol.2-Maestro"),
        ("Phantom", "Bubble Love", "Phantom City"),
        ("MellowD", "MellowD", "On My Way"),
        ("Geologic", "Blaze", "Geologic"),
        ("MC Meta", "On My Own", "The Blue Printz"),
        ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        ("J'Kyun", "Fly Away", "Ready to Fly"),
        ("Sean2Slow", "Slow Down", "Slow Jam"),
        ("Skull", "I'm Your Man", "Skull & Haha"),
        ("Mighty Mouth", "San", "Mighty Style"),
        ("E-Sens", "The Anecdote", "The Anecdote"),
        ("Epik High", "Born Hater", "Shoebox"),
        ("Dynamic Duo", "Grand Carnival", "Grand Carnival"),
        ("Dean", "130613", "130 Mood: TRBL"),
        ("Crush", "Just", ""),
        ("Jay Park", "WORLDWIDE", "Worldwide"),
        ("Heize", "Underwater", "And July"),
        ("Zion.T", "Eat", ""),
        ("Beenzino", "So What", ""),
        ("Loco", "Respect", ""),
        ("Gray", "Just Do It", ""),
        ("Simon Dominic", "Simon Dominic", "Won & Only"),
        ("Giriboy", "Back and Forth 30 Min", "Sexual Perceptions"),
        ("Swings", "Remember We", "Growing Pains"),
        ("PH-1", "PH1's Day Off", "PH1's Day Off"),
        ("Nafla", "Mood Indigo", "Natural High"),
        ("Loopy", "No More", "Mmk"),
        ("Kid Milli", "A Swaggy Song Called Kidd", "A Swaggy Song Called Kidd"),
        ("Changmo", "Rebels", "Rebels"),
    ],
    2017: [
        ("Dean", "instagram", ""),
        ("G-Dragon", "Untitled, 2014", "Kwon Ji Yong"),
        ("G-Dragon", "Bullshit", "Kwon Ji Yong"),
        ("G-Dragon", "Middle Fingers-Up", "Kwon Ji Yong"),
        ("G-Dragon", "Super Star", "Kwon Ji Yong"),
        ("G-Dragon", "Divina Commedia", "Kwon Ji Yong"),
        ("Zico", "Television", "Television"),
        ("Zico", "Artist", "Television"),
        ("Zico", "No Way", "Television"),
        ("Zico", "Bermuda Triangle", "Television"),
        ("Zico", "Extreme", "Television"),
        ("Crush", "None", ""),
        ("Crush", "Skip", ""),
        ("Crush", "Fall", "Wonderlust"),
        ("Heize", "Jenga", "Jenga"),
        ("Heize", "You, Clouds, Rain", "///"),
        ("Heize", "Round and Round", "Jenga"),
        ("Jay Park", "All I Wanna Do", "Worldwide"),
        ("Jay Park", "Me Like Yuh", "Everything You Wanted"),
        ("Jay Park", "Drive", "Everything You Wanted"),
        ("Jay Park", "Solo", "Everything You Wanted"),
        ("Jay Park", "Stay With Me", "Everything You Wanted"),
        ("Loco", "Too Much", "Bleached"),
        ("Loco", "Summer Go Loco", "Summer Go Loco"),
        ("Loco", "Post It", ""),
        ("Gray", "I'm Fine", "Hyena on the Keyboard"),
        ("Gray", "Upside Down", ""),
        ("Zion.T", "The Song", "OO"),
        ("Zion.T", "Complex", "OO"),
        ("Zion.T", "Sorry", "OO"),
        ("Zion.T", "Snow", ""),
        ("Zion.T", "No Make Up", "OO"),
        ("Zion.T", "Eat", "OO"),
        ("Beenzino", "Time Travel", "12"),
        ("Beenzino", "January", "12"),
        ("Beenzino", "Saturday", "12"),
        ("PH-1", "Good Day", "Good Day"),
        ("PH-1", "Nineteen", "Good Day"),
        ("Nafla", "Angel", "Angel"),
        ("Nafla", "Natural High", "Natural High"),
        ("Loopy", "Mmk", "Mmk"),
        ("Loopy", "No More", "Mmk"),
        ("Kid Milli", "IndiGO", "IndiGO"),
        ("Kid Milli", "A Swaggy Song Called Kidd", "A Swaggy Song Called Kidd"),
        ("Changmo", "Maestro", "Maestro"),
        ("Changmo", "Rebels", "Rebels"),
        ("Giriboy", "Because", "Mechanical Album"),
        ("Giriboy", "You're Pretty", "Mechanical Album"),
        ("Swings", "Growing Pains", "Growing Pains"),
        ("Punchnello", "If You", "If You"),
        ("Colde", "In Your Eyes", "In Your Eyes"),
        ("Simon Dominic", "Make Her Dance", "Won & Only"),
        ("Simon Dominic", "DAx4", "DAx4"),
        ("The Quiett", "Green Light", ""),
        ("Paloalto", "Nomad", "Nomad"),
        ("Dok2", "Thug Life", "Thug Life Part 2"),
        ("Verbal Jint", "Mainstream", "Mainstream"),
        ("Bobby", "Holup!", "Holup!"),
        ("Mino", "Fear", "Fear"),
        ("Epik High", "Born Hater", "Shoebox"),
        ("Dynamic Duo", "Grand Carnival", "Grand Carnival"),
        ("E-Sens", "The Anecdote", "The Anecdote"),
        ("Primary", "JohnLegend", "Da Capo"),
        ("Crush", "Oasis", "Crush on You"),
        ("Dean", "I Love It", "130 Mood: TRBL"),
        ("Heize", "And July", "And July"),
        ("Jay Park", "WORLDWIDE", "Worldwide"),
        ("Loco", "It Takes Time", ""),
        ("Gray", "Good", ""),
        ("Zion.T", "Just", ""),
        ("Beenzino", "Break", "12"),
        ("PH-1", "PH1's Day Off", "PH1's Day Off"),
        ("Nafla", "Mood Indigo", "Natural High"),
        ("Loopy", "Mmk", "Mmk"),
        ("Kid Milli", "IndiGO", "IndiGO"),
        ("Changmo", "Rebels", "Rebels"),
        ("San E", "Story of Someone I Know", "Show Me the Money 5"),
        ("Mad Clown", "Fire", "Fire"),
        ("Bumkey", "When I Wake Up", ""),
        ("Junggigo", "Warm", ""),
        ("Gaeko", "Going Home", "Going Home"),
        ("Deepflow", "Flow the Life 3", "Flow the Life 3"),
        ("Kebee", "Rhythm and Poetry", "Rhythm and Poetry"),
        ("Vasco", "The Vasco", "The Vasco"),
        ("Okasian", "Airplane Mode", ""),
        ("B-Free", "Hot Summer", ""),
        ("Jerry.K", "V", "V"),
        ("Huckleberry P", "Mantra 3", "Mantra 3"),
        ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
        ("Tablo", "Bad", "Fever's End Pt. 1"),
        ("Leessang", "Ballerino", ""),
        ("Tiger JK", "Monologue", ""),
        ("Yoon Mirae", "Angel", ""),
        ("Primary", "Mission", "Primary and the Messengers LP 2"),
        ("Punchnello", "Loving You Girl", "Loving You Girl"),
        ("Colde", "Your Dog Loves You", "Your Dog Loves You"),
        ("Illinit", "Ill Street Live", ""),
        ("Outsider", "Loner 2", "Vol.2-Maestro"),
        ("Phantom", "Bubble Love", "Phantom City"),
        ("MellowD", "MellowD", "On My Way"),
        ("Geologic", "Blaze", "Geologic"),
        ("MC Meta", "On My Own", "The Blue Printz"),
        ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        ("J'Kyun", "Fly Away", "Ready to Fly"),
        ("Sean2Slow", "Slow Down", "Slow Jam"),
        ("Skull", "I'm Your Man", "Skull & Haha"),
        ("Mighty Mouth", "San", "Mighty Style"),
    ],
}


def norm_key(artist: str, title: str) -> str:
    def norm(s: str) -> str:
        s = s.lower().strip()
        s = s.replace("&", " and ")
        s = re.sub(r"\bfeat\.?\b|\bft\.?\b|\bfeaturing\b", " ", s)
        s = re.sub(r"[^\w\s가-힣]+", " ", s, flags=re.UNICODE)
        return re.sub(r"\s+", " ", s).strip()

    return f"{norm(artist)}|{norm(title)}"


def write_module(year: int, tracks: list[tuple[str, str, str]]) -> None:
    lines = ["TRACKS = ["]
    for a, t, al in tracks:
        lines.append(f"    ({a!r}, {t!r}, {al!r}),")
    lines.append("]")
    lines.append("")
    path = os.path.join(ROOT, f"y{year}.py")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {path} ({len(tracks)})")


def main() -> None:
    bad_suffix = re.compile(r"\(\d{4}(?:\s+Mix)?\)\s*$")
    used: dict[str, int] = {}

    sys.path.insert(0, ROOT)
    from y2012 import TRACKS as T2012  # noqa: E402

    for a, t, _ in T2012:
        used[norm_key(a, t)] = 2012

    for year, tracks in sorted(REAL_YEARS.items()):
        if len(tracks) != 100:
            raise SystemExit(f"{year}: expected 100, got {len(tracks)}")
        seen: set[str] = set()
        for a, t, al in tracks:
            if bad_suffix.search(t):
                raise SystemExit(f"bad suffix: {year} {a} - {t}")
            k = norm_key(a, t)
            if k in seen:
                raise SystemExit(f"dup in year: {year} {a} - {t}")
            if k in used:
                raise SystemExit(f"dup vs {used[k]}: {year} {a} - {t}")
            seen.add(k)
            used[k] = year
        write_module(year, tracks)

    print(f"OK: {len(used) - len(T2012)} new tracks across 2013-2017")


if __name__ == "__main__":
    main()
