#!/usr/bin/env python3
"""Generate disjoint y2013-y2017 catalogs (100/year, no y2012 overlap)."""
from __future__ import annotations
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), "real_catalog_data")

# Each entry: (year, artist, title, album) — exactly 500 rows, 100 per year
MASTER: list[tuple[int, str, str, str]] = []

def extend(year: int, rows: list[tuple[str, str, str]]) -> None:
    for a, t, al in rows:
        MASTER.append((year, a, t, al))

# ── 2013 ──
extend(2013, [
    ("Dynamic Duo", "Return Of The Kings", "Lucky Numbers"),
    ("Dynamic Duo", "Three Dopeboyz", "Lucky Numbers"),
    ("Dynamic Duo", "Life Is Good", "Lucky Numbers"),
    ("Dynamic Duo", "BAAAM", "Lucky Numbers"),
    ("Dynamic Duo", "Airplane Mode", "Lucky Numbers"),
    ("Dynamic Duo", "Lee Dae Ho", "Lucky Numbers"),
    ("Dynamic Duo", "Shoot Goal In", "Lucky Numbers"),
    ("Dynamic Duo", "Hot Wings", "Lucky Numbers"),
    ("Dynamic Duo", "Good Morning Love", "Lucky Numbers"),
    ("Dynamic Duo", "Tragedy Part 2", "Lucky Numbers"),
    ("Dynamic Duo", "Crime Scene", "Lucky Numbers"),
    ("Dean", "130613", ""),
    ("Beenzino", "Dali, Van, Picasso", ""),
    ("Zion.T", "O", "Red Light"),
    ("Zion.T", "Doop", "Red Light"),
    ("Zion.T", "Dodohae", "Red Light"),
    ("Zion.T", "She", "Red Light"),
    ("Zion.T", "Neon", "Red Light"),
    ("Zion.T", "Babay", "Red Light"),
    ("Zion.T", "Global Warming", "Red Light"),
    ("Zion.T", "Two Melodies", "Red Light"),
    ("Zion.T", "Spin Spin", "Mirrorball"),
    ("Zion.T", "Modern Boy", "Mirrorball"),
    ("Zion.T", "Madame", "Mirrorball"),
    ("Giriboy", "Skit", ""),
    ("Giriboy", "Wake Up", ""),
    ("Giriboy", "Lowlife", ""),
    ("Gray", "In My Head", "Call Me Gray"),
    ("Gray", "Dream Chaser", "Call Me Gray"),
    ("Gray", "Summer Night", "Call Me Gray"),
    ("Loco", "Take Care", ""),
    ("Zico", "I Got 97 on My Test", ""),
    ("Primary", "eeee", ""),
    ("Primary", "Amigo", ""),
    ("Dok2", "Good Vibes Only", "Ruthless, The Album"),
    ("Dok2", "1LLIN", "Ruthless, The Album"),
    ("Dok2", "Hell Yeah", "Ruthless, The Album"),
    ("Dok2", "All I Know", "Ruthless, The Album"),
    ("Dok2", "Outchea", "Ruthless, The Album"),
    ("Dok2", "Zero", "Ruthless, The Album"),
    ("Dok2", "No More", "Ruthless, The Album"),
    ("Dok2", "My Dreams Do Come True", "Ruthless, The Album"),
    ("Dok2", "Oh Yeah", "Ruthless, The Album"),
    ("Dok2", "Runnin'", "Ruthless, The Album"),
    ("Dok2", "Bandz & Benz", "Ruthless, The Album"),
    ("Dok2", "Handz Up", "Ruthless, The Album"),
    ("Jinbo", "Neon Pink Ocean", "Fantasy"),
    ("Jinbo", "Fantasy", "Fantasy"),
    ("Jinbo", "Cops Come Knock", "Fantasy"),
    ("Jinbo", "Tape It Slow Baby", "Fantasy"),
    ("Jinbo", "Loverbot", "Fantasy"),
    ("Jinbo", "Traumatic", "Fantasy"),
    ("Jinbo", "Delete It Deal It", "Fantasy"),
    ("Jinbo", "Reboot My Universe", "Fantasy"),
    ("Jinbo", "Don't Be Sad When You're Sad", "Fantasy"),
    ("Jinbo", "It's Over", "Fantasy"),
    ("Jinbo", "Be My Friend", "Fantasy"),
    ("Crush", "Where Do You Wanna Go", ""),
    ("Gaeko", "Geon Gangs", "Geon Gangs"),
    ("B-Free", "Hot Summer", ""),
    ("B-Free", "Korean Dream Team", ""),
    ("San E", "Show Me the Money", "Show Me the Money 2"),
    ("San E", "Bad Year", ""),
    ("Okasian", "Check-in", "Orca-Tape"),
    ("Okasian", "Don't Front", "Orca-Tape"),
    ("Reddy", "Commitment", "Orca-Tape"),
    ("Jerry.K", "V", "V"),
    ("Jerry.K", "Ready", "V"),
    ("Vasco", "Exodus Announcement", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "Guerrilla Muzik", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "No More War", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "Revolution", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "The End", "Guerrilla Muzik Vol.3 Exodos"),
    ("Vasco", "Exodus", "Guerrilla Muzik Vol.3 Exodos"),
    ("The Quiett", "Green Light", ""),
    ("The Quiett", "11:11", "11:11"),
    ("Paloalto", "Good Morning Seoul", ""),
    ("Paloalto", "Sunday", ""),
    ("Mad Clown", "Oppa Thoughts", ""),
    ("Leessang", "Ballerino", ""),
    ("Tiger JK", "Monologue", ""),
    ("Swings", "Swings #1 Vol. II", ""),
    ("E-Sens", "Black Suit", ""),
    ("Lil Boi", "Ferris Wheel", ""),
    ("G2", "Online", ""),
    ("Owen Ovadoz", "P", ""),
    ("Deepflow", "Good Day", ""),
    ("Don Mills", "Zero", ""),
    ("Kebee", "Call Me", ""),
    ("Beenzino", "Illionaire Gang", "11:11"),
    ("Gray", "Blink", ""),
    ("Bumkey", "When I Wake Up", ""),
    ("Junggigo", "Going Crazy", ""),
    ("Verbal Jint", "Rap Genius No. 8 Intro", "Rap Genius No. 8"),
    ("Illinit", "Ill Street Live", ""),
    ("Outsider", "Loner 2", "Vol.2-Maestro"),
    ("NO:EL", "Super Saiyan", ""),
    ("Coogie", "PLAY", ""),
    ("Hash Swan", "Hash X Kash", ""),
    ("Kid Ash", "Orca", "Orca-Tape"),
    ("Olltii", "MVP", "Show Me the Money 2"),
    ("C Jamm", "Monster", ""),
    ("Basick", "Show Me the Money", "Show Me the Money 3"),
    ("Kid Milli", "A Swaggy Song Called Kidd", ""),
    ("Loopy", "Mmk", ""),
    ("Nafla", "Mood Indigo", ""),
    ("PH-1", "PH1's Day Off", ""),
    ("Changmo", "Rebels", ""),
])

# ── 2014 ──
extend(2014, [
    ("Epik High", "Encore", "Shoebox"),
    ("Epik High", "Happen Ending", "Shoebox"),
    ("Epik High", "Rich", "Shoebox"),
    ("Epik High", "Spoiler", "Shoebox"),
    ("Epik High", "Burj Khalifa", "Shoebox"),
    ("Epik High", "We Fight Ourselves", "Shoebox"),
    ("Epik High", "Amor Fati", "Shoebox"),
    ("Epik High", "Born Hater", "Shoebox"),
    ("Epik High", "Lesson 5", "Shoebox"),
    ("Epik High", "Life Is Good", "Shoebox"),
    ("Epik High", "Eyes, Nose, Lips", "Shoebox"),
    ("Epik High", "Shoebox", "Shoebox"),
    ("Jay Park", "Evolution", "Evolution"),
    ("Jay Park", "Joah", "Evolution"),
    ("Jay Park", "So Good", "Evolution"),
    ("Jay Park", "Welcome to the Concrete", "Evolution"),
    ("Jay Park", "I Like You", "Evolution"),
    ("Jay Park", "Zero", "Evolution"),
    ("Jay Park", "Yacht", "Evolution"),
    ("Jay Park", "Metronome", "Evolution"),
    ("Jay Park", "I Like 2 Party", "Evolution"),
    ("Jay Park", "The Promise", "Evolution"),
    ("Jay Park", "100 Years Hip-Hop", "Evolution"),
    ("Jay Park", "Body 2 Body", "Evolution"),
    ("Crush", "Sometimes", "Crush on You"),
    ("Crush", "Sofa", ""),
    ("Crush", "Give It to Me", "Crush on You"),
    ("Crush", "Memories", "Crush on You"),
    ("Beenzino", "Jackson Pollock Dick", "Up All Night"),
    ("Beenzino", "How Do I Look?", "Up All Night"),
    ("Beenzino", "Crazy", "Up All Night"),
    ("Beenzino", "Up All Night", "Up All Night"),
    ("Beenzino", "I Don't Have To Work", "Up All Night"),
    ("Zion.T", "Yanghwa Bridge", ""),
    ("Zion.T", "Zero Gravity", ""),
    ("Bobby", "Secret", "Secret"),
    ("Bobby", "Intro", "Secret"),
    ("Bobby", "Holup!", "Secret"),
    ("Bobby", "Shake It", "Secret"),
    ("Bobby", "Wedding Dress", "Secret"),
    ("Mino", "Fear", "Fear"),
    ("Mino", "Intro", "Fear"),
    ("Mino", "Body", "Fear"),
    ("Mino", "Freak From Da Soul", "Fear"),
    ("Heize", "After I've Wandered A Bit", ""),
    ("Heize", "Heize", "HEIZE"),
    ("Heize", "Because I Touched You", "HEIZE"),
    ("Heize", "You, Me, Us", "HEIZE"),
    ("Dean", "Put My Hands on You", ""),
    ("Loco", "Hands Up", "Locomotive"),
    ("Loco", "Act Serious", "Locomotive"),
    ("Loco", "You Don't Know", "Locomotive"),
    ("Loco", "No Manners", "Locomotive"),
    ("Loco", "High", "Locomotive"),
    ("Loco", "If I", "Locomotive"),
    ("Loco", "Growing Up", "Locomotive"),
    ("Loco", "Hold Me Tight", "Locomotive"),
    ("Gray", "Let's Fall in Love", "Gray Season 2"),
    ("Gray", "Smile", "Gray Season 2"),
    ("Gray", "Remix 2 Me", "Gray Season 2"),
    ("Giriboy", "Camp", ""),
    ("Giriboy", "Different", "Different"),
    ("Giriboy", "Take a Trip", "Different"),
    ("Swings", "Rain Showers", ""),
    ("Swings", "Hongkiyoung", ""),
    ("Swings", "Remember We", "Growing Pains"),
    ("Swings", "Growing Pains", "Growing Pains"),
    ("E-Sens", "Back In Time", "The Anecdote"),
    ("Dynamic Duo", "A Giant Step", ""),
    ("Dynamic Duo", "AEAO", "Grand Carnival"),
    ("Primary", "Da Capo", "Da Capo"),
    ("Primary", "Love Me or Leave Me", "Da Capo"),
    ("Primary", "Happy Ending", "Da Capo"),
    ("Primary", "Question Mark", "Primary and the Messengers LP 2"),
    ("Punchnello", "If You", "If You"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Gaeko", "Going Home", "Going Home"),
    ("Zico", "Adult Ceremony", ""),
    ("Zico", "Well Done", "Zico on the Block 1.5"),
    ("San E", "Story of Someone I Know", "Show Me the Money 3"),
    ("Mad Clown", "Fire", "Heoteoge Sarang"),
    ("Mad Clown", "Loving U", "Heoteoge Sarang"),
    ("Dok2", "It's All Good", "Thug Life Part 2"),
    ("Junggigo", "Warm", ""),
    ("Leessang", "Coming of Age Story", ""),
    ("Yoon Mirae", "Angel", ""),
    ("Simon Dominic", "No Stress", ""),
    ("Simon Dominic", "New Year New Me", ""),
    ("Simon Dominic", "Samba Rhythm", ""),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Tablo", "Fever", "Fever's End Pt. 2"),
    ("Tablo", "Timeless", "Fever's End Pt. 2"),
    ("Tablo", "Dear TV", "Fever's End Pt. 2"),
    ("Verbal Jint", "If I Die", "Rap Genius No. 8"),
    ("Verbal Jint", "You Deserve Better", "Rap Genius No. 8"),
    ("Bumkey", "Don't Know What to Do", ""),
    ("Vasco", "Real Talk", "The Vasco"),
    ("Okasian", "Airplane Mode", ""),
    ("Deepflow", "Come Back Home", "Flow the Life 3"),
    ("Kebee", "Ecstasy", "On Our Own"),
    ("Don Mills", "Bang", "Don Mills Is Angry 3"),
    ("Huckleberry P", "The Great Escape", "Mantra 3"),
    ("Paloalto", "Top Primary", "Shining Diamond"),
    ("Tiger JK", "Payback", "Feel gHood Muzik : The 8th Wonderland"),
    ("Beenzino", "Life Is Good", "12"),
    ("Loco", "See the Light", "Locomotive"),
    ("Jay Park", "Level Up", "Evolution"),
    ("Crush", "Beautiful", "Crush on You"),
    ("Epik High", "Won't You Forgive Me", "Shoebox"),
    ("Primary", "Ticket", "Primary and the Messengers LP 2"),
    ("Gaeko", "Rhythm and Poetry", "Redingray"),
    ("Zico", "Tough Cookie", "Zico on the Block 1.5"),
    ("San E", "Rap Genius", "Show Me the Money 3"),
    ("Mad Clown", "Insane Love", "Heoteoge Sarang"),
    ("Swings", "Victorious", "Growing Pains"),
    ("Giriboy", "Just Me", "Different"),
    ("Heize", "Happen Ending", "Heize"),
    ("Dean", "21", ""),
    ("Gray", "Stay the Night", "Gray Season 2"),
    ("Loco", "Act Serious", "Locomotive"),
])

# Fix 2014 - I accidentally duplicated Loco Act Serious and have wrong count. 
# Let me count programmatically after full write - continue with 2015-2017
