#!/usr/bin/env python3
"""Write catalog/y2014-y2017.py with scored candidate pools."""
from __future__ import annotations

import os
import re

OUT = os.path.join(os.path.dirname(__file__), "catalog")

CATALOGS: dict[int, list[tuple[int, str, str, str]]] = {
    2014: [
        (135, "Mad Clown", "화 (Fire)", "허튼 소망"),
        (134, "Epik High", "눈, 코, 입", "Shoebox"),
        (133, "Zion.T", "양화대교", ""),
        (132, "Crush", "소파", ""),
        (131, "Epik High", "헤픈 엔딩", "Shoebox"),
        (130, "BTS", "Danger", "DARK & WILD"),
        (129, "Epik High", "Born Hater", "Shoebox"),
        (128, "Gaeko", "집으로", "집으로"),
        (127, "Loco", "너를 생각해", "Locomotive"),
        (126, "Bobby", "Holup!", "SECRET"),
        (125, "Swings", "홍키영", "Show Me the Money 3"),
        (124, "Jay Park", "좋아", "Evolution"),
        (123, "Mad Clown", "Maximum", "Potato"),
        (122, "Bobby", "감동 (Secret)", "SECRET"),
        (121, "Mino", "겁", "Fear"),
        (120, "Swings", "우리를 기억해", "Growing Pains"),
        (119, "Crush", "가끔", "Crush on You"),
        (118, "Loco", "장갑", "Locomotive"),
        (117, "Epik High", "Rich", "Shoebox"),
        (116, "Jay Park", "So Good", "Evolution"),
        (115, "Beenzino", "Up All Night", "Up All Night"),
        (114, "San E", "Story of Someone I Know", "Show Me the Money 3"),
        (113, "Zico", "Tough Cookie", "Zico on the Block 1.5"),
        (112, "Dean", "Put My Hands on You", ""),
        (111, "Heize", "조금만 더 걸을래", ""),
        (110, "Dynamic Duo", "A Giant Step", ""),
        (109, "Primary", "JohnLegend", "Da Capo"),
        (108, "Giriboy", "Camp", ""),
        (107, "Swings", "비", ""),
        (106, "Zion.T", "Zero Gravity", ""),
        (105, "Beenzino", "How Do I Look?", "Up All Night"),
        (104, "Crush", "Give It to Me", "Crush on You"),
        (103, "Jay Park", "Evolution", "Evolution"),
        (102, "Epik High", "Spoiler", "Shoebox"),
        (101, "BTS", "호르몬 전쟁", "DARK & WILD"),
        (100, "Loco", "진지해", "Locomotive"),
        (99, "Mino", "Body", "Fear"),
        (98, "Bobby", "Shake It", "SECRET"),
        (97, "Zion.T", "Eat", ""),
        (96, "Giriboy", "Different", "Different"),
        (95, "Primary", "Mission", "Da Capo"),
        (94, "Punchnello", "If You", "If You"),
        (93, "Colde", "In Your Eyes", "In Your Eyes"),
        (92, "Zico", "성인식", ""),
        (91, "Dok2", "Thug Life", "Thug Life Part 2"),
        (90, "Tablo", "Bad", "Fever's End Pt. 2"),
        (89, "Verbal Jint", "Good Morning Pt.3", "Rap Genius No. 8"),
        (88, "Simon Dominic", "사이먼 도미닉", "Consolation"),
        (87, "Leessang", "Coming of Age Story", ""),
        (86, "Yoon Mirae", "Angel", ""),
        (85, "Junggigo", "Warm", ""),
        (84, "Bumkey", "When I Wake Up", ""),
        (83, "Okasian", "Airplane Mode", ""),
        (82, "PH-1", "PH1's Day Off", ""),
        (81, "Nafla", "Mood Indigo", ""),
        (80, "Loopy", "Mmk", ""),
        (79, "Kid Milli", "A Swaggy Song Called Kidd", ""),
        (78, "Changmo", "Rebels", ""),
        (77, "The Quiett", "Q Train", "Q Train"),
        (76, "Paloalto", "Shining Diamond", "Shining Diamond"),
        (75, "Deepflow", "Come Back Home", "Flow the Life 3"),
        (74, "Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
        (73, "Kebee", "Rhythm and Poetry", "Rhythm and Poetry"),
        (72, "Vasco", "The Vasco", "The Vasco"),
        (71, "Jerry.K", "V", "V"),
        (70, "B-Free", "Hot Summer", ""),
        (69, "Tiger JK", "Monologue", ""),
        (68, "Swings", "Growing Pains", "Growing Pains"),
        (67, "E-Sens", "Back In Time", "The Anecdote"),
        (66, "Gray", "Let's Fall in Love", "Gray Season 2"),
        (65, "Gray", "Smile", "Gray Season 2"),
        (64, "Loco", "High", "Locomotive"),
        (63, "Loco", "No Manners", "Locomotive"),
        (62, "Beenzino", "Crazy", "Up All Night"),
        (61, "Beenzino", "12", "12"),
        (60, "Heize", "Heize", "HEIZE"),
        (59, "Heize", "Because I Touched You", "HEIZE"),
        (58, "Jay Park", "Zero", "Evolution"),
        (57, "Jay Park", "Metronome", "Evolution"),
        (56, "Epik High", "Amor Fati", "Shoebox"),
        (55, "Epik High", "Burj Khalifa", "Shoebox"),
        (54, "Epik High", "We Fight Ourselves", "Shoebox"),
        (53, "Epik High", "Life Is Good", "Shoebox"),
        (52, "Epik High", "Encore", "Shoebox"),
        (51, "Primary", "Da Capo", "Da Capo"),
        (50, "Primary", "Happy Ending", "Da Capo"),
        (49, "Giriboy", "Square", "Square"),
        (48, "Giriboy", "Take a Trip", "Different"),
        (47, "Iron", "Rock Bottom", "Show Me the Money 3"),
        (46, "Basick", "Hold You", "Show Me the Money 3"),
        (45, "Black Nut", "100", "Show Me the Money 3"),
        (44, "C Jamm", "Monster", ""),
        (43, "Illinit", "Ill Street Live", ""),
        (42, "Outsider", "Vol.2-Maestro", "Vol.2-Maestro"),
        (41, "Phantom", "Bubble Love", "Phantom City"),
        (40, "Mighty Mouth", "San", "Mighty Style"),
        (39, "Skull", "I'm Your Man", "Skull & Haha"),
        (38, "Sean2Slow", "Slow Down", "Slow Jam"),
        (37, "J'Kyun", "Fly Away", "Ready to Fly"),
        (36, "Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        (35, "MC Meta", "On My Own", "The Blue Printz"),
        (34, "Geologic", "Blaze", "Geologic"),
        (33, "MellowD", "MellowD", "On My Way"),
        (32, "Huckleberry P", "Mantra 3", "Mantra 3"),
        (31, "Lil Boi", "Ferris Wheel", ""),
        (30, "G2", "Online", ""),
        (29, "Owen Ovadoz", "P", ""),
        (28, "Reddy", "Commitment", "Orca-Tape"),
        (27, "Kid Ash", "Orca", "Orca-Tape"),
        (26, "Olltii", "TTM", ""),
        (25, "Louie", "GO", "Show Me the Money 3"),
        (24, "Truedy", "My Light", "Show Me the Money 3"),
        (23, "Bobby", "Wedding Dress", "SECRET"),
        (22, "Mino", "Freak From Da Soul", "Fear"),
        (21, "Crush", "Electric Kiss", ""),
        (20, "Zion.T", "Two Melodies", "Red Light"),
        (19, "Beenzino", "Jackson Pollock Dick", "Up All Night"),
        (18, "Loco", "Growing Up", "Locomotive"),
        (17, "Loco", "Hold Me Tight", "Locomotive"),
        (16, "Gray", "Remix 2 Me", "Gray Season 2"),
        (15, "Simon Dominic", "No Stress", ""),
        (14, "Simon Dominic", "New Year New Me", ""),
        (13, "Tablo", "Timeless", "Fever's End Pt. 2"),
        (12, "Dok2", "It's All Good", "Thug Life Part 2"),
        (11, "Verbal Jint", "Rap Genius No. 8", "Rap Genius No. 8"),
        (10, "Mad Clown", "Potato", "Potato"),
        (9, "San E", "Bananas", "Show Me the Money 3"),
        (8, "Dynamic Duo", "Return Of The Kings", "Lucky Numbers"),
        (7, "Primary", "Love Me or Leave Me", "Da Capo"),
        (6, "Jay Park", "I Like You", "Evolution"),
        (5, "Jay Park", "Yacht", "Evolution"),
        (4, "Epik High", "Lesson 5", "Shoebox"),
        (3, "BTS", "Let Me Know", "DARK & WILD"),
        (2, "Swings", "Sleep Well", ""),
        (1, "Elo", "Hood", "Hood"),
    ],
    2015: [
        (135, "iKON", "MY TYPE", "WELCOME BACK"),
        (134, "BTS", "뱁새", "The Most Beautiful Moment in Life Pt.1"),
        (133, "BTS", "I NEED U", "The Most Beautiful Moment in Life Pt.1"),
        (132, "BTS", "RUN", "The Most Beautiful Moment in Life Pt.2"),
        (131, "Dynamic Duo", "AEAO", "Grand Carnival"),
        (130, "Zion.T", "노메이크업", ""),
        (129, "Dean", "Pour Up", ""),
        (128, "Heize", "And July", "And July"),
        (127, "Crush", "Just", ""),
        (126, "E-Sens", "이상형", "The Anecdote"),
        (125, "Loco", "Respect", ""),
        (124, "Loco", "Awesome", ""),
        (123, "Gray", "Just Do It", ""),
        (122, "Jay Park", "MOMMAE", "Worldwide"),
        (121, "Beenzino", "So What", ""),
        (120, "Simon Dominic", "사이먼 도미닉", "Won & Only"),
        (119, "Zico", "Boys and Girls", "Breakthrough"),
        (118, "Giriboy", "Why Do You Live Like This?", ""),
        (117, "Heize", "No Way", "And July"),
        (116, "Dean", "I Love It", ""),
        (115, "Dean", "Bonnie & Clyde", ""),
        (114, "Crush", "Oasis", "Crush on You"),
        (113, "Dynamic Duo", "Grand Carnival", "Grand Carnival"),
        (112, "Zion.T", "Complex", ""),
        (111, "Jay Park", "WORLDWIDE", "Worldwide"),
        (110, "Jay Park", "All I Wanna Do", "Worldwide"),
        (109, "Beenzino", "Break", "12"),
        (108, "Beenzino", "We Are Going To", "12"),
        (107, "Gray", "We Don't Love", "Gray Season 2"),
        (106, "Simon Dominic", "Won & Only", "Won & Only"),
        (105, "Simon Dominic", "Make Her Dance", "Won & Only"),
        (104, "Giriboy", "Back and Forth 30 Min", "Sexual Perceptions"),
        (103, "Giriboy", "Wu Gyeol", "Sexual Perceptions"),
        (102, "E-Sens", "Dice", "The Anecdote"),
        (101, "E-Sens", "Tick Tock", "The Anecdote"),
        (100, "BTS", "쩔어", "The Most Beautiful Moment in Life Pt.1"),
        (99, "BTS", "Dope", "The Most Beautiful Moment in Life Pt.1"),
        (98, "BTS", "Butterfly", "The Most Beautiful Moment in Life Pt.1"),
        (97, "Heize", "Because You", "And July"),
        (96, "Heize", "Underwater", "And July"),
        (95, "Heize", "Happen Ending", "Heize"),
        (94, "Crush", "Love You With All My Heart", ""),
        (93, "Jay Park", "YOU KNOW", "Worldwide"),
        (92, "Jay Park", "My Last", "Worldwide"),
        (91, "Dynamic Duo", "Jam", "Grand Carnival"),
        (90, "Dynamic Duo", "Oasis", "Grand Carnival"),
        (89, "Zico", "Breakthrough", "Breakthrough"),
        (88, "BewhY", "Day Day", "The Movie Star"),
        (87, "BewhY", "Forever", "The Movie Star"),
        (86, "Sik-K", "TRAP", "TRAP"),
        (85, "Sik-K", "Romeo & Juliet", "TRAP"),
        (84, "Bobby", "GO UP", "WILD AND YOUNG"),
        (83, "Basick", "Hold You", "Show Me the Money 4"),
        (82, "Iron", "Rain Shower", "Show Me the Money 4"),
        (81, "Lil Boi", "Good Day", "Show Me the Money 4"),
        (80, "Louie", "GO", "Show Me the Money 4"),
        (79, "Black Nut", "100", "Show Me the Money 4"),
        (78, "Truedy", "My Light", "Show Me the Money 4"),
        (77, "San E", "A BILLIONAIRE", "Show Me the Money 4"),
        (76, "Punchnello", "Loving You Girl", "Loving You Girl"),
        (75, "Colde", "Your Dog Loves You", "Your Dog Loves You"),
        (74, "PH-1", "Good Day", "Good Day"),
        (73, "PH-1", "Nineteen", "Good Day"),
        (72, "Nafla", "Natural High", "Natural High"),
        (71, "Loopy", "No More", "Mmk"),
        (70, "Kid Milli", "IndiGO", "IndiGO"),
        (69, "Changmo", "Maestro", "Maestro"),
        (68, "Junggigo", "Want U", ""),
        (67, "Okasian", "Celebration", ""),
        (66, "The Quiett", "Cut", ""),
        (65, "Verbal Jint", "Rap Genius No. 9", "Rap Genius No. 9"),
        (64, "C Jamm", "Monster", ""),
        (63, "Giriboy", "Sensual Album", "Sensual Album"),
        (62, "Giriboy", "Edited By Devil", ""),
        (61, "Beenzino", "January", "12"),
        (60, "Zion.T", "Just", ""),
        (59, "YUMDDA", "I'm Good", ""),
        (58, "Blase", "Passionfruit", ""),
        (57, "Mirani", "Pepsi", ""),
        (56, "Iron", "Rock Bottom", "Show Me the Money 4"),
        (55, "Basick", "Pale Dream", "Show Me the Money 4"),
        (54, "Basick", "Stand Up", "Show Me the Money 4"),
        (53, "Louie", "Picture", "Show Me the Money 4"),
        (52, "Simon Dominic", "Lonely Night", "Won & Only"),
        (51, "Simon Dominic", "Money Don't Lie", "Won & Only"),
        (50, "Jay Park", "WHEN", "Worldwide"),
        (49, "Jay Park", "LOTTO", "Worldwide"),
        (48, "Jay Park", "SEATTLE 2 SEOUL", "Worldwide"),
        (47, "Dynamic Duo", "Hot Tub Time Machine", "Grand Carnival"),
        (46, "Dynamic Duo", "Sign", "Grand Carnival"),
        (45, "Dean", "1333", ""),
        (44, "E-Sens", "A-G-E", "The Anecdote"),
        (43, "E-Sens", "Next Level", "The Anecdote"),
        (42, "E-Sens", "Wobble", "The Anecdote"),
        (41, "E-Sens", "The Anecdote", "The Anecdote"),
        (40, "Loco", "Thinking About You", "Locomotive"),
        (39, "Loco", "Hands Up", "Locomotive"),
        (38, "Gray", "Smile", "Gray Season 2"),
        (37, "Kid Ash", "Orca", "Orca-Tape"),
        (36, "Olltii", "TTM", ""),
        (35, "Illinit", "Real Talk Live", ""),
        (34, "Outsider", "Vol.2-Maestro", "Vol.2-Maestro"),
        (33, "Mad Clown", "화 (Fire)", "Fire"),
        (32, "Gaeko", "West Coast", "Redingray"),
        (31, "Primary", "Roller Coaster", "Primary and the Messengers LP 2"),
        (30, "Tablo", "Eyes, Nose, Lips", "Fever's End Pt. 1"),
        (29, "Leessang", "Ballerino", ""),
        (28, "Tiger JK", "Monologue", ""),
        (27, "Yoon Mirae", "Touch Love", ""),
        (26, "Dok2", "Thug Life", "Thug Life Part 2"),
        (25, "Paloalto", "Nomad", "Nomad"),
        (24, "Deepflow", "Flow the Life 3", "Flow the Life 3"),
        (23, "Kebee", "On Our Own", "On Our Own"),
        (22, "Vasco", "Real Talk", "The Vasco"),
        (21, "Huckleberry P", "Mantra 3", "Mantra 3"),
        (20, "Don Mills", "Go Away", "Don Mills Is Angry 3"),
        (19, "B-Free", "Korean Dream Team", ""),
        (18, "Jerry.K", "Ready", "V"),
        (17, "Mighty Mouth", "San", "Mighty Style"),
        (16, "Skull", "I'm Your Man", "Skull & Haha"),
        (15, "Sean2Slow", "Slow Down", "Slow Jam"),
        (14, "J'Kyun", "Fly Away", "Ready to Fly"),
        (13, "Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        (12, "MC Meta", "On My Own", "The Blue Printz"),
        (11, "Geologic", "Blaze", "Geologic"),
        (10, "MellowD", "MellowD", "On My Way"),
        (9, "Phantom", "Bubble Love", "Phantom City"),
        (8, "Swings", "I'll Give You Everything", ""),
        (7, "Zion.T", "Yanghwa Bridge", ""),
        (6, "Crush", "Sofa", ""),
        (5, "Epik High", "Born Hater", "Shoebox"),
        (4, "iKON", "AIRPLANE", "WELCOME BACK"),
        (3, "iKON", "ANTHEM", "WELCOME BACK"),
        (2, "BTS", "Hold Me Tight", "The Most Beautiful Moment in Life Pt.1"),
        (1, "BTS", "Intro: The Most Beautiful Moment in Life", "The Most Beautiful Moment in Life Pt.1"),
    ],
    2016: [
        (135, "BTS", "피 땀 눈물", "WINGS"),
        (134, "Dean", "D (Half Moon)", "130 Mood : TRBL"),
        (133, "Crush", "Don't Forget", "Interlude"),
        (132, "Zion.T", "Knock", "Show Me the Money 5"),
        (131, "Heize", "너, 나, 우리", ""),
        (130, "Jay Park", "Me Like Yuh", "EVERYTHING YOU WANTED"),
        (129, "Jay Park", "Drive", "EVERYTHING YOU WANTED"),
        (128, "Beenzino", "Real Girl", ""),
        (127, "Loco", "You Too", ""),
        (126, "C Jamm", "The Last", "Show Me the Money 5"),
        (125, "BewhY", "Movie Star", "The Fiery"),
        (124, "Simon Dominic", "Simon Dominic Part 3", "Show Me the Money 5"),
        (123, "Crush", "Woo Ah", "Interlude"),
        (122, "Dean", "what2do", "130 Mood : TRBL"),
        (121, "Dean", "21", "130 Mood : TRBL"),
        (120, "Heize", "Listen To Me", "Unpretty Rapstar 2"),
        (119, "Gray", "Good", ""),
        (118, "Gray", "Late Night", ""),
        (117, "Dynamic Duo", "Highfive", ""),
        (116, "Giriboy", "Because", "Mechanical Album"),
        (115, "Punchnello", "My Piece", "My Piece"),
        (114, "Sik-K", "YESSIR", "Trap Art"),
        (113, "BewhY", "The Fiery", "The Fiery"),
        (112, "BewhY", "Day Day", "The Movie Star"),
        (111, "Nucksal", "180°", ""),
        (110, "BTS", "불타오르네", "The Most Beautiful Moment in Life : Young Forever"),
        (109, "BTS", "Save ME", "The Most Beautiful Moment in Life : Young Forever"),
        (108, "BTS", "Fire", "The Most Beautiful Moment in Life : Young Forever"),
        (107, "Jay Park", "Solo", "EVERYTHING YOU WANTED"),
        (106, "Jay Park", "Stay With Me", "EVERYTHING YOU WANTED"),
        (105, "Jay Park", "Turn Off Your Phone Remix", "EVERYTHING YOU WANTED"),
        (104, "Loco", "Still", ""),
        (103, "Crush", "9 to 5", "Interlude"),
        (102, "Crush", "Your Dress", ""),
        (101, "Dean", "out the club", "130 Mood : TRBL"),
        (100, "Dean", "wrong", "130 Mood : TRBL"),
        (99, "Dean", "i'm not sorry", "130 Mood : TRBL"),
        (98, "Dean", "1303", "130 Mood : TRBL"),
        (97, "Dean", "pleasure & pain", "130 Mood : TRBL"),
        (96, "Zico", "It Isn't Love", "Show Me the Money 5"),
        (95, "Hanhae", "Drop", "Show Me the Money 5"),
        (94, "San E", "Body", "Show Me the Money 5"),
        (93, "Killagramz", "Good Morning", "Show Me the Money 5"),
        (92, "Flowsik", "We On", "Show Me the Money 5"),
        (91, "Basick", "Nice Day", "Show Me the Money 5"),
        (90, "Jessi", "China", "Show Me the Money 5"),
        (89, "Gray", "Comfortable", "Show Me the Money 5"),
        (88, "Bobby", "GO", "MOBB"),
        (87, "Mino", "Hit Me", "MOBB"),
        (86, "Mino", "Burning Up", "MOBB"),
        (85, "Bobby", "Wang Hola", "MOBB"),
        (84, "Mino", "Ready Or Not", "MOBB"),
        (83, "Giriboy", "You're Pretty", "Mechanical Album"),
        (82, "Giriboy", "Infrared Radiation", "Mechanical Album"),
        (81, "Giriboy", "Used to Love You", "Mechanical Album"),
        (80, "Colde", "Love Lessons", "Love Lessons"),
        (79, "Sik-K", "Throw That", "Trap Art"),
        (78, "Sik-K", "Donut", "Trap Art"),
        (77, "Sik-K", "Fly", "Trap Art"),
        (76, "Sik-K", "Trap Art", "Trap Art"),
        (75, "Nafla", "Crew Love", "Natural High"),
        (74, "Loopy", "Press It", "Mmk"),
        (73, "Kid Milli", "Linguistics", "IndiGO"),
        (72, "Changmo", "Ring Ding", "Maestro"),
        (71, "Olltii", "Creative Control", "Creative Control"),
        (70, "Jerry.K", "Thorn Crown", "Thorn Crown"),
        (69, "Lil Boi", "Credit", "Good Day"),
        (68, "G2", "Business", "Business"),
        (67, "Owen Ovadoz", "POEM", "POEM"),
        (66, "Deepflow", "Flow the Life 4", "Flow the Life 4"),
        (65, "Don Mills", "Don Mills Is Angry 4", "Don Mills Is Angry 4"),
        (64, "Huckleberry P", "Mantra 4", "Mantra 4"),
        (63, "Illinit", "Ill Street Live 2", ""),
        (62, "Cheetah", "Keep It Movin", ""),
        (61, "KittiB", "Nobody Knows", ""),
        (60, "Reddy", "THINK", ""),
        (59, "B-Free", "Best Seller", "Best Seller"),
        (58, "Coogie", "Woops", ""),
        (57, "Junggigo", "No Diggin'", ""),
        (56, "Gaeko", "Pass", "Pass"),
        (55, "Yoon Mirae", "Gemini", ""),
        (54, "Bumkey", "Single Life 2", "Single Life 2"),
        (53, "Tiger JK", "I Know", "Feel gHood Muzik : The 8th Wonderland"),
        (52, "Verbal Jint", "Dooms Day", "Rap Genius No. 9"),
        (51, "Verbal Jint", "Numbers", "Rap Genius No. 9"),
        (50, "Tablo", "Hood", "Fever's End Pt. 2"),
        (49, "Dok2", "Rich Forever", "Thug Life Part 2"),
        (48, "Primary", "Planetarium", ""),
        (47, "Elo", "Hood", "Hood"),
        (46, "Elo", "Trouble", "Hood"),
        (45, "Swings", "Growling", "Growling"),
        (44, "Jinbo", "Honey", "Honey"),
        (43, "Jay Park", "The Truth Is", "EVERYTHING YOU WANTED"),
        (42, "Jay Park", "Replay", "EVERYTHING YOU WANTED"),
        (41, "Jay Park", "Feature", "EVERYTHING YOU WANTED"),
        (40, "Jay Park", "Limousine", "EVERYTHING YOU WANTED"),
        (39, "Jay Park", "Alone Tonight", "EVERYTHING YOU WANTED"),
        (38, "Jay Park", "Only One", "EVERYTHING YOU WANTED"),
        (37, "Jay Park", "Aquaman", "EVERYTHING YOU WANTED"),
        (36, "Jay Park", "Forever", "EVERYTHING YOU WANTED"),
        (35, "Jay Park", "I Got This", "EVERYTHING YOU WANTED"),
        (34, "Jay Park", "Everything", "EVERYTHING YOU WANTED"),
        (33, "Jay Park", "FYE", "EVERYTHING YOU WANTED"),
        (32, "BewhY", "Blind", "The Fiery"),
        (31, "BewhY", "Interlude", "The Fiery"),
        (30, "Beenzino", "12", "12"),
        (29, "Beenzino", "Break", "12"),
        (28, "Beenzino", "Saturday", "12"),
        (27, "Beenzino", "Time Travel", "12"),
        (26, "Crush", "highfive", ""),
        (25, "Simon Dominic", "Make Her Dance", "Won & Only"),
        (24, "PH-1", "Good Day", "Good Day"),
        (23, "Changmo", "Maestro", "Maestro"),
        (22, "The Quiett", "Green Light", ""),
        (21, "Paloalto", "Nomad", "Nomad"),
        (20, "Zico", "Boys and Girls", "Breakthrough"),
        (19, "Mad Clown", "화 (Fire)", "Fire"),
        (18, "Loco", "Respect", ""),
        (17, "Gray", "Just Do It", ""),
        (16, "Heize", "And July", "And July"),
        (15, "Dean", "Pour Up", "130 Mood : TRBL"),
        (14, "Dean", "I Love It", "130 Mood : TRBL"),
        (13, "Dynamic Duo", "AEAO", "Grand Carnival"),
        (12, "Zion.T", "노메이크업", ""),
        (11, "Crush", "Just", ""),
        (10, "iKON", "MY TYPE", "WELCOME BACK"),
        (9, "BTS", "RUN", "The Most Beautiful Moment in Life Pt.2"),
        (8, "BTS", "뱁새", "The Most Beautiful Moment in Life Pt.1"),
        (7, "Epik High", "Born Hater", "Shoebox"),
        (6, "Swings", "Remember We", "Growing Pains"),
        (5, "Giriboy", "Traffic Control", "914"),
        (4, "Penomeco", "COCO BOTTLE", ""),
        (3, "Hash Swan", "Retro Love", ""),
        (2, "Woo", "We Are", ""),
        (1, "Leellamarz", "To Be Continued", "To Be Continued"),
    ],
    2017: [
        (135, "BTS", "DNA", "LOVE YOURSELF 承 'Her'"),
        (134, "Dean", "instagram", ""),
        (133, "Heize", "비도 오고 그래서", "///"),
        (132, "Crush", "None", ""),
        (131, "Loco", "Too Much", "Bleached"),
        (130, "Jay Park", "V", "The Season: The Blue Bird"),
        (129, "Zion.T", "Snow", ""),
        (128, "Punchnello", "Everyday", "Everyday"),
        (127, "Penomeco", "Famous", ""),
        (126, "Hash Swan", "Retro Love", ""),
        (125, "Woo", "We Are", ""),
        (124, "Hwang Kwanghee", "Yellow Boots", "프로듀스 101 Season 2"),
        (123, "G-Dragon", "Untitled, 2014", "권지용"),
        (122, "Zico", "Artist", "Television"),
        (121, "Loco", "Summer Go Loco", "Summer Go Loco"),
        (120, "Gray", "I'm Fine", "Hyena on the Keyboard"),
        (119, "Heize", "Jenga", "Jenga"),
        (118, "Crush", "Skip", ""),
        (117, "Jay Park", "All The Way Up", ""),
        (116, "Zion.T", "Sorry", "OO"),
        (115, "Zion.T", "The Song", "OO"),
        (114, "Beenzino", "Damnato", "Damnato"),
        (113, "Beenzino", "Holiday", "Damnato"),
        (112, "Simon Dominic", "DAx4", "DAx4"),
        (111, "PH-1", "YIN YANG", "YIN YANG"),
        (110, "Nafla", "MVP", "[ Album ]"),
        (109, "Loopy", "Portrait Mode", "[ Album ]"),
        (108, "Kid Milli", "Cappuccino", ""),
        (107, "Changmo", "Meteor", "Boyhood"),
        (106, "Giriboy", "914", "914"),
        (105, "Sik-K", "YACHT", "YACHT"),
        (104, "Sik-K", "CRRWD", "YACHT"),
        (103, "Penomeco", "COCO BOTTLE", ""),
        (102, "Epik High", "Lesson 1", "Lesson 0"),
        (101, "BTS", "MIC Drop", "LOVE YOURSELF 承 'Her'"),
        (100, "BTS", "Go Go", "LOVE YOURSELF 承 'Her'"),
        (99, "BTS", "Best Of Me", "LOVE YOURSELF 承 'Her'"),
        (98, "BTS", "Dimple", "LOVE YOURSELF 承 'Her'"),
        (97, "G-Dragon", "Bullshit", "권지용"),
        (96, "G-Dragon", "Super Star", "권지용"),
        (95, "Zico", "Television", "Television"),
        (94, "Zico", "No Idea", "Television"),
        (93, "Zico", "Fanatxy", "Television"),
        (92, "Zico", "Eureka", "Television"),
        (93, "Zico", "Design", "Television"),
        (91, "Zico", "Okey Dokey", "Okey Dokey"),
        (90, "Crush", "Fall", "Wonderlust"),
        (89, "Crush", "What Do You Want To Eat?", "Wonderlust"),
        (88, "Heize", "First Snow", "Jenga"),
        (87, "Heize", "Goodbye", "Jenga"),
        (86, "Heize", "Ride", "///"),
        (85, "Heize", "And Today", "///"),
        (84, "Jay Park", "Nothing Wrong", ""),
        (83, "Jay Park", "NEED YOU", ""),
        (82, "Jay Park", "Forget About That", ""),
        (81, "Jay Park", "The Season", "The Season: The Blue Bird"),
        (80, "Loco", "Bleached", "Bleached"),
        (79, "Loco", "It Takes Time", ""),
        (78, "Loco", "Waiting", "Bleached"),
        (77, "Loco", "A Little More", "Bleached"),
        (76, "Gray", "Upside Down", ""),
        (75, "Gray", "Real Love", ""),
        (74, "Zion.T", "Evan", "OO"),
        (73, "Beenzino", "Nike's Song", "Damnato"),
        (72, "Beenzino", "Profanity", "Damnato"),
        (71, "Punchnello", "My Piece", "My Piece"),
        (70, "PH-1", "Platonic", "YIN YANG"),
        (69, "PH-1", "Romeo and Juliet", "YIN YANG"),
        (68, "Nafla", "Jazz Freestyle", "[ Album ]"),
        (67, "Nafla", "What", "[ Album ]"),
        (66, "Nafla", "You Gon' Need It", "[ Album ]"),
        (65, "Nafla", "Bandage on My Shoulder", "[ Album ]"),
        (64, "Loopy", "Save", "[ Album ]"),
        (63, "Loopy", "Great Hour", "[ Album ]"),
        (62, "Loopy", "No Loopy", "[ Album ]"),
        (61, "Loopy", "Recipe", "[ Album ]"),
        (60, "Kid Milli", "Maiden Voyage", "Maiden Voyage"),
        (59, "Kid Milli", "Cabbage", "Maiden Voyage"),
        (58, "Changmo", "Boyhood", "Boyhood"),
        (57, "Changmo", "Sufferer", "Boyhood"),
        (56, "Giriboy", "Traffic Control", "914"),
        (55, "Giriboy", "Maybe", "914"),
        (54, "Giriboy", "Invasion", "914"),
        (53, "The Quiett", "Glow", ""),
        (52, "Epik High", "Lesson 2", "Lesson 0"),
        (51, "Epik High", "Lesson 3", "Lesson 0"),
        (50, "Epik High", "Ros Blanco", "Lesson 0"),
        (49, "Epik High", "C'est La Vie", "Lesson 0"),
        (48, "Sik-K", "Party", "Trap Art"),
        (47, "Sik-K", "WEGO", "YACHT"),
        (46, "Sik-K", "WHISTLE", "YACHT"),
        (45, "Penomeco", "OFM", ""),
        (44, "Jessi", "Unpretty Dreams", "Unpretty Dreams"),
        (43, "Hash Swan", "Hash Brand 2", "Hash Brand 2"),
        (42, "Primary", "Morning Glory", ""),
        (41, "Elo", "Tattoo On My Heart", "Tattoo On My Heart"),
        (40, "Swings", "Remedy", "Remedy"),
        (39, "Dok2", "All I Know Is", "Thug Life Part 2"),
        (38, "Paloalto", "Sunday Service", "Sunday Service"),
        (37, "Bobby", "Y.G.G", "Y.G.G"),
        (36, "Coogie", "PICK UP THE PHONE", ""),
        (35, "Coogie", "Money & Fame", ""),
        (34, "BewhY", "Cult of Curiosity", "Cult of Curiosity"),
        (33, "Leellamarz", "To Be Continued", "To Be Continued"),
        (32, "Hash Swan", "Hash Brand", "Hash Brand"),
        (31, "NO:EL", "Rain Drop", "Rain Drop"),
        (30, "Dean", "D (Half Moon)", "130 Mood : TRBL"),
        (29, "Crush", "Don't Forget", "Interlude"),
        (28, "Loco", "You Too", ""),
        (27, "Jay Park", "Me Like Yuh", "EVERYTHING YOU WANTED"),
        (26, "BTS", "피 땀 눈물", "WINGS"),
        (25, "Dynamic Duo", "Highfive", ""),
        (24, "Giriboy", "Because", "Mechanical Album"),
        (23, "C Jamm", "The Last", "Show Me the Money 5"),
        (22, "BewhY", "Movie Star", "The Fiery"),
        (21, "Simon Dominic", "Simon Dominic Part 3", "Show Me the Money 5"),
        (20, "Nucksal", "180°", ""),
        (19, "Heize", "너, 나, 우리", ""),
        (18, "Zion.T", "Knock", "Show Me the Money 5"),
        (17, "Beenzino", "Real Girl", ""),
        (16, "Gray", "Good", ""),
        (15, "Sik-K", "YESSIR", "Trap Art"),
        (14, "Punchnello", "Loving You Girl", "Loving You Girl"),
        (13, "Colde", "Love Lessons", "Love Lessons"),
        (12, "Mirani", "Pepsi", ""),
        (11, "Blase", "Passionfruit", ""),
        (10, "YUMDDA", "I'm Good", ""),
        (9, "Basick", "Nice Day", "Show Me the Money 5"),
        (8, "Flowsik", "We On", "Show Me the Money 5"),
        (7, "Hanhae", "Drop", "Show Me the Money 5"),
        (6, "Killagramz", "Good Morning", "Show Me the Money 5"),
        (5, "Iron", "Rain Shower", "Show Me the Money 4"),
        (4, "Louie", "GO", "Show Me the Money 4"),
        (3, "Giriboy", "Why Do You Live Like This?", ""),
        (2, "E-Sens", "이상형", "The Anecdote"),
        (1, "iKON", "MY TYPE", "WELCOME BACK"),
    ],
}


def norm_key(artist: str, title: str) -> str:
    def norm(s: str) -> str:
        s = s.lower().strip()
        s = s.replace("&", " and ")
        s = re.sub(r"\bfeat\.?\b|\bft\.?\b|\bfeaturing\b", " ", s)
        s = re.sub(r"[^\w\s가-힣]+", " ", s, flags=re.UNICODE)
        return re.sub(r"\s+", " ", s).strip()

    return f"{norm(artist)}|{norm(title)}"


def has_hangul(s: str) -> bool:
    return bool(re.search(r"[\uAC00-\uD7A3]", s))


def write_year(year: int, tracks: list[tuple[int, str, str, str]]) -> None:
    if len(tracks) < 130:
        raise SystemExit(f"{year}: need 130+, got {len(tracks)}")

    keys: set[str] = set()
    for _, artist, title, _ in tracks:
        k = norm_key(artist, title)
        if k in keys:
            raise SystemExit(f"{year}: duplicate {artist} / {title}")
        keys.add(k)

    ko = sum(1 for _, _, title, _ in tracks if has_hangul(title))
    if ko / len(tracks) < 0.45:
        raise SystemExit(f"{year}: hangul ratio {ko}/{len(tracks)} too low")

    lines = ["TRACKS = ["]
    for score, artist, title, album in tracks:
        lines.append(f'    ({score}, {artist!r}, {title!r}, {album!r}),')
    lines.append("]")
    lines.append("")

    path = os.path.join(OUT, f"y{year}.py")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {path} ({len(tracks)} tracks, {ko} hangul titles)")


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    for year in (2014, 2015, 2016, 2017):
        write_year(year, CATALOGS[year])


if __name__ == "__main__":
    main()
