#!/usr/bin/env python3
"""Build dedupe-safe y2021.py."""
from __future__ import annotations
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from build_y2018 import build_used_through
from fix_and_emit import norm_key, has_bad_suffix

CANDIDATES = [
    ("Changmo", "MORAESIGYE", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "TAIJI", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Rockstar Lifestyle", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Beretta", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Chronic Love", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Vivienne", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Little Brothers", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Hyperstar", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Hotel Room", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "No Regret", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "Supernova", "UNDERGROUND ROCKSTAR"),
    ("Changmo", "UNDERGROUND ROCKSTAR", "UNDERGROUND ROCKSTAR"),
    ("Kid Milli", "Cliché", "Cliché"),
    ("Kid Milli", "OFF KEY", "Cliché"),
    ("Kid Milli", "BAD BAD", "Cliché"),
    ("Kid Milli", "J J J", "Cliché"),
    ("Kid Milli", "SIDE FILM", "Cliché"),
    ("Kid Milli", "MORE", "Cliché"),
    ("Kid Milli", "TAKE IT", "Cliché"),
    ("Coogie", "I Got A Feeling", "I Got A Feeling"),
    ("Beenzino", "MODERN", "MODERN"),
    ("Beenzino", "Walkin' on Water", "MODERN"),
    ("Beenzino", "Break Down", "MODERN"),
    ("Beenzino", "Traveling", "MODERN"),
    ("PH-1", "Ninth", "Ninth"),
    ("PH-1", "Ninth Sense", "Ninth"),
    ("Epik High", "Preach", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Rich Man", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Fan", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Map of the Human Soul", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Lesson Zero", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Middle School Teacher", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "High Technology", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Thank You", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Free Love", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Let Me Hold You", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Hate", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Kill", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Open Your Eyes", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Remember Me?", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Fool", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Wicked", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Am I Wrong", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Criminal Record", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Can You Hear My Heart", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "End of the World", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "The Bad in You", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Self Control", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Passionate Goodbye", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Love Fever", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "We Are One", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Umbrella", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "1 Minute 1 Second", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Nocturnal Animals", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Caffeine", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Acceptance Speech", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "The Road Not Taken", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "The Cure", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Breathe", "Epilogue Pt.2"),
    ("Epik High", "Sleep Tight", "Epilogue Pt.2"),
    ("Epik High", "You Are The One For Me", "Epilogue Pt.2"),
    ("Epik High", "Catch the Shadow", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "One", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Fly", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Lesson One", "Epik High Is Epik High Pt. 2"),
    ("Epik High", "Love Love Love", "Epik High Is Epik High Pt. 2"),
    ("be'O", "Countdown", "Show Me the Money 10"),
    ("be'O", "Luxury", "Show Me the Money 10"),
    ("be'O", "Momentum", "Show Me the Money 10"),
    ("be'O", "Healing", "Show Me the Money 10"),
    ("Koonta", "KOONTA", "Show Me the Money 10"),
    ("Dynamic Duo", "Untouchable", "Untouchable"),
    ("Lee Young Ji", "Untouchable", "Untouchable"),
    ("Crush", "Rush Hour", "Rush Hour"),
    ("Ash Island", "Me n Mine", "Show Me the Money 10"),
    ("Mirani", "Villain", "Show Me the Money 10"),
    ("Mudd the student", "Nectar", "Show Me the Money 10"),
    ("Lil Moshpit", "ACHOO", "Show Me the Money 10"),
    ("Blase", "ONOFF", "Show Me the Money 10"),
    ("Woodie Gochild", "Mud", "Show Me the Money 10"),
    ("Sokodomo", "SIGNATURE", "Show Me the Money 10"),
    ("Owen Ovadoz", "Diana", "Show Me the Money 10"),
    ("Lil Boi", "ONFleek", "Show Me the Money 10"),
    ("Mino", "Do You Remember", "Do You Remember"),
    ("Jay Park", "To Life", "To Life"),
    ("Gray", "Summer Surf", "Summer Surf"),
    ("Lee Young Ji", "Witch", "Witch"),
    ("Jessi", "Cold Blooded", "Cold Blooded"),
    ("GroovyRoom", "Brought the Heat Back", "Brought the Heat Back"),
    ("Sik-K", "Brought the Heat Back", "Brought the Heat Back"),
    ("Paloalto", "Brought the Heat Back", "Brought the Heat Back"),
    ("Heize", "Midnight", "Midnight"),
    ("Zion.T", "Just", "Just"),
    ("Nafla", "what is your name", "understand"),
    ("Colde", "honestly", "Star"),
    ("YUMDDA", "I'm Good", ""),
    ("Loopy", "Radar", "ON THE Radar"),
    ("Giriboy", "Because I Love You", "Lonely"),
    ("Dean", "Peace", "Peace"),
    ("Gray", "summer", "summer"),
    ("Loco", "Hello", "Hello"),
    ("Jay Park", "Forget About Tomorrow", "Forget About Tomorrow"),
    ("Zion.T", "Spring Dream", "Zionic"),
    ("Punchnello", "Winter Blossom", "Winter Blossom"),
    ("Loco", "Summer Go Loco", "Summer Go Loco"),
    ("Giriboy", "Lonely", "Lonely"),
    ("Nafla", "understand", "understand"),
    ("Loopy", "ON THE Radar", "ON THE Radar"),
    ("Leellamarz", "Ale", "Marz & Ale"),
    ("TOIL", "MAZE", "MAZE"),
    ("Dean", "4:44", "4:44"),
    ("Colde", "Star", "Star"),
    ("Swings", "Shook Ones", "Shook Ones"),
    ("Simon Dominic", "GOTT", "GOTT"),
    ("Code Kunst", "Buckle Up", "Code Kunst Archive Pack 02"),
    ("Tablo", "Birthday", "Birthday"),
    ("Bobby", "Lalala", "Lalala"),
    ("Mino", "Booker", "Booker"),
    ("Gaeko", "Rosetta", "Rosetta"),
    ("Primary", "Morning Glory", ""),
    ("Dok2", "All I Know Is", "Thug Life Part 2"),
    ("Kid Milli", "Summer", ""),
    ("Changmo", "Just the Two of Us", ""),
    ("Changmo", "SMF", ""),
    ("Loco", "Wedding", ""),
    ("Loco", "Aniya", ""),
    ("Jay Park", "McNasty", ""),
    ("Jay Park", "B Day", ""),
    ("Zion.T", "Lonely Christmas", ""),
    ("Punchnello", "Loveseat", ""),
    ("Punchnello", "Cream Cheese", ""),
    ("Blase", "Quote That", ""),
    ("The Quiett", "Nike", ""),
    ("Paloalto", "Valentina", ""),
    ("TOIL", "like when we first met", ""),
    ("Lil Moshpit", "Moshpit Only", "AAA"),
    ("Lil Moshpit", "Gotta Lotta Shit", "AAA"),
    ("Lil Moshpit", "Yooooo", "AAA"),
    ("Lil Moshpit", "A-Team Freestyle", "AAA"),
    ("Lil Moshpit", "Slatty Slut", "AAA"),
    ("Lil Moshpit", "ON THE BLOCK", "AAA"),
    ("Lil Moshpit", "DIE HARD", "AAA"),
    ("Lil Moshpit", "BO$$", "AAA"),
    ("Lil Moshpit", "Back In My AREA", "AAA"),
    ("The Quiett", "Bentley", ""),
    ("Kid Milli", "Lightly", ""),
    ("Changmo", "FWB", ""),
    ("Punchnello", "Motive", ""),
    ("Colde", "Wave", ""),
    ("Leellamarz", "STORY", "Toystory3"),
    ("Leellamarz", "Last Chance", "Toystory3"),
    ("Leellamarz", "Don`t do That", "Toystory3"),
    ("Leellamarz", "Separation Anxiety", "Toystory3"),
    ("Leellamarz", "Never Ending Story", "Toystory3"),
    ("Leellamarz", "Aftermath", "Toystory3"),
    ("Leellamarz", "B.B.B", "Toystory3"),
    ("Leellamarz", "Flower Age", "Toystory3"),
    ("Leellamarz", "1,2,3", "Toystory3"),
    ("Leellamarz", "2AM", "Toystory3"),
    ("Leellamarz", "Zero Coke", "Toystory3"),
    ("Leellamarz", "Iris", "Toystory3"),
    ("Epik High", "Here", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Prequel", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Super Rare", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Gray So Gray", "Epik High Is Here 下, Part 2"),
    ("Epik High", "BRB", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Rain Song", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Rich Kids Anthem", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Face ID", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Family Portrait", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Champagne", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Piano for Sale", "Epik High Is Here 下, Part 2"),
    ("Tablo", "I Hated Myself (Tablo's Word)", "Epik High Is Here 下, Part 2"),
    ("Zico", "New Thing", ""),
    ("Zico", "Grown Ass Kid", "Grown Ass Kid"),
    ("Zico", "Seoul Drift", "Grown Ass Kid"),
    ("Zico", "Being Human", "Grown Ass Kid"),
    ("Zico", "Curriculum", "Grown Ass Kid"),
    ("Zico", "OMJT", "Grown Ass Kid"),
    ("Zico", "Trash Talk", "Grown Ass Kid"),
    ("Zico", "That Guy", "Grown Ass Kid"),
    ("Beenzino", "Monet", ""),
    ("Jay Park", "Why", ""),
    ("Loco", "Focus", ""),
    ("Dean", "Die 4 You", ""),
    ("Mino", "Aero", "BODY"),
    ("Punchnello", "Motive", ""),
    ("Colde", "Wave", ""),
    ("Leellamarz", "Number", "MaRz&B"),
    ("Leellamarz", "Uncomfortable", "MaRz&B"),
    ("Leellamarz", "Ex", "MaRz&B"),
    ("Leellamarz", "Chrome Hearts", "MaRz&B"),
    ("Leellamarz", "Down", "MaRz&B"),
    ("Leellamarz", "Muse", "MaRz&B"),
    ("Leellamarz", "Meet me at the London", "MaRz&B"),
    ("Leellamarz", "CTRL+Z", "VIOLINIST2"),
    ("Leellamarz", "OUT OF MY SIGHT", "VIOLINIST2"),
    ("Leellamarz", "Left hand to Right hand", "VIOLINIST2"),
    ("Leellamarz", "a single word", "VIOLINIST2"),
    ("Leellamarz", "This is not what I want", "VIOLINIST2"),
    ("Leellamarz", "Selfish", "VIOLINIST2"),
    ("Leellamarz", "Sisi La Famille", "VIOLINIST2"),
    ("Leellamarz", "30 minutes", "VIOLINIST2"),
    ("Leellamarz", "Without You (Encore)", "VIOLINIST2"),
]


def main() -> None:
    used, exclude = build_used_through(2021)
    picked: list[tuple[str, str, str]] = []
    for a, t, al in CANDIDATES:
        if has_bad_suffix(t):
            continue
        k = norm_key(a, t)
        if k in used or k in exclude:
            continue
        used.add(k)
        picked.append((a, t, al))
        if len(picked) == 100:
            break
    print(f"picked {len(picked)}")
    if len(picked) != 100:
        raise SystemExit("failed")
    lines = ["TRACKS = ["]
    for a, t, al in picked:
        lines.append(f"    ({a!r}, {t!r}, {al!r}),")
    lines.append("]")
    lines.append("")
    path = os.path.join(os.path.dirname(__file__), "real_catalog_data", "y2021.py")
    open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
