#!/usr/bin/env python3
"""Find 11+ unique tracks to complete y2022.py."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_y2018 import build_used_through
from fix_and_emit import norm_key
from real_catalog_data import REAL_CATALOG

used, exclude = build_used_through(2022)
for a, t, al in REAL_CATALOG[2022]:
    k = norm_key(a, t)
    if k not in used and k not in exclude:
        used.add(k)

EXTRA = [
    ("Blase", "Tic Tac", "Tic Tac"),
    ("Lil Moshpit", "ACHOO", "ACHOO"),
    ("Woodie Gochild", "WaRRior", "Show Me the Money 9"),
    ("Sokodomo", "IF I", "Show Me the Money 9"),
    ("Koonta", "Grandma", "Show Me the Money 9"),
    ("Owen Ovadoz", "119 REMIX", "Show Me the Money 9"),
    ("Giriboy", "on my way", "Show Me the Money 9"),
    ("Lil Moshpit", "BITE", "Show Me the Money 9"),
    ("Blase", "Fill It", "Show Me the Money 9"),
    ("Mirani", "VANS", "Show Me the Money 9"),
    ("Mudd the student", "Do You Like Haeseon", "Show Me the Money 9"),
    ("Mudd the student", "Mockingbird", "Show Me the Money 9"),
    ("Lil Boi", "On My Way", "Show Me the Money 9"),
    ("Kid Milli", "Beige 0.5", "Beige 0.5"),
    ("PH-1", "MEET N GREET", "X"),
    ("Coogie", "Up!", "Up!"),
    ("Changmo", "METEORITE", "Meteor"),
    ("Beenzino", "Reset", "Reset"),
    ("Ash Island", "Melodies", "Melodies"),
    ("Jay Park", "Forget About Tomorrow", "Forget About Tomorrow"),
    ("Loco", "Hello", "Hello"),
    ("Gray", "summer", "summer"),
    ("Sik-K", "Bungee", "Bungee"),
    ("Crush", "Click Like", "Click Like"),
    ("Heize", "Run to You", "Run to You"),
    ("Dean", "Peace", "Peace"),
    ("Punchnello", "Winter Blossom", "Winter Blossom"),
    ("Colde", "Star", "Star"),
    ("Swings", "Shook Ones", "Shook Ones"),
    ("Simon Dominic", "GOTT", "GOTT"),
    ("Primary", "2", "2"),
    ("Gaeko", "Rosetta", "Rosetta"),
    ("Bobby", "Lalala", "Lalala"),
    ("Mino", "Booker", "Booker"),
    ("Tablo", "Birthday", "Birthday"),
    ("Code Kunst", "Buckle Up", "Code Kunst Archive Pack 02"),
    ("Zion.T", "Spring Dream", "Zionic"),
    ("Gray", "00 XX", "00 XX"),
    ("Coogie", "Pick up your phone", "Up!"),
    ("Jay Park", "Gonzo", "Gonzo"),
    ("Bumkey", "Single Life 2", "Single Life 2"),
    ("Loco", "The Show", "Hello"),
    ("Leellamarz", "Marz", "Marz & Ale"),
    ("HAON", "Melody", "Melodies"),
    ("Loco", "Warning", "Hello"),
    ("Dynamic Duo", "ECO", "ECO"),
    ("Swings", "IndiGO", "Show Me the Money 8"),
    ("Primary", "Morning Glory", ""),
    ("Dok2", "All I Know Is", "Thug Life Part 2"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("D.Ark", "Genius", "Genius"),
    ("E-Sens", "Gold", "The Anecdote"),
    ("Tablo", "Fantasy", "Drill Presents: Tablo x Fantasy"),
    ("Paloalto", "Shangri-La", "Shangri-La"),
    ("Sik-K", "FL1X", "FL1X"),
    ("Kid Milli", "Yellow", "Maiden Voyage"),
    ("Coogie", "Coogie", "Coogie"),
    ("HAON", "Travel", "Penumbra"),
    ("Ash Island", "Malibu", "Ash Island"),
    ("Leellamarz", "Profile", "To Be Continued"),
    ("TOIL", "1989", "1989"),
    ("Blase", "Blue", ""),
    ("Mirani", "Pepsi", ""),
    ("YUMDDA", "I'm Good", ""),
    ("Kid Ash", "Orca", "Orca-Tape"),
    ("C Jamm", "Monster", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Flowsik", "We On", "Show Me the Money 777"),
    ("Reddy", "Think", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Jessi", "Gucci", "Show Me the Money 777"),
    ("D.Ark", "Undercover", "Show Me the Money 777"),
    ("Verbal Jint", "Rap Genius No. 9", "Rap Genius No. 9"),
    ("Deepflow", "Flow the Life 4", "Flow the Life 4"),
    ("Don Mills", "Don Mills Is Angry 4", "Don Mills Is Angry 4"),
    ("Huckleberry P", "Mantra 4", "Mantra 4"),
    ("Elo", "Tattoo On My Heart", "Tattoo On My Heart"),
    ("Swings", "Remedy", "Remedy"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("NO:EL", "Rain Drop", "Rain Drop"),
    ("Woodie Gochild", "GOchild", "#GOchild"),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Owen Ovadoz", "Drama", "Drama"),
    ("Lil Moshpit", "MOSHPIT", "MOSHPIT"),
    ("Gaeko", "Gajah", "Gajah"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Blued", "Blue", "Blue"),
    ("J Soul", "Soul", "Soul"),
    ("Jay Soul", "Soul Food", "Soul Food"),
    ("BewhY", "Day Day", "The Movie Star"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Everyday", "Everyday"),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Primary", "2 Weeks", "2"),
    ("Dynamic Duo", "AEAO", "A DynamicAffair"),
    ("Dynamic Duo", "BAAAM", "A DynamicAffair"),
    ("Penomeco", "Shy", "Shy"),
    ("Penomeco", "Lovers", "Shy"),
    ("Jessi", "Who Dat B", "Who Dat B"),
    ("Epik High", "Timeless", "Sleepless in __________"),
    ("Epik High", "Loved", "Sleepless in __________"),
    ("Mudd the student", "Open", "Show Me the Money 8"),
    ("Leellamarz", "Barcode", "Show Me the Money 8"),
    ("TOIL", "Panorama", "Show Me the Money 8"),
    ("YunB", "Piano", "Show Me the Money 8"),
    ("Swings", "VVS", "Show Me the Money 8"),
    ("BewhY", "VVS", "Show Me the Money 8"),
    ("Giriboy", "VVS", "Show Me the Money 8"),
    ("Nafla", "VVS", "Show Me the Money 8"),
    ("Loopy", "VVS", "Show Me the Money 8"),
    ("Changmo", "VVS", "Show Me the Money 8"),
    ("Coogie", "VVS", "Show Me the Money 8"),
    ("Ash Island", "VVS", "Show Me the Money 8"),
    ("HAON", "VVS", "Show Me the Money 8"),
    ("TOIL", "VVS", "Show Me the Money 8"),
    ("Blase", "VVS", "Show Me the Money 8"),
    ("Woodie Gochild", "VVS", "Show Me the Money 8"),
    ("Sokodomo", "VVS", "Show Me the Money 8"),
    ("Owen Ovadoz", "VVS", "Show Me the Money 8"),
    ("Koonta", "VVS", "Show Me the Money 8"),
    ("Mirani", "VVS", "Show Me the Money 8"),
    ("Lil Moshpit", "VVS", "Show Me the Money 8"),
    ("Kid Milli", "A List", "Show Me the Money 8"),
    ("PH-1", "RUBBER", "Show Me the Money 8"),
    ("Lil Boi", "VVS", "Show Me the Money 8"),
    ("Mudd the student", "IndiGO", "Show Me the Money 8"),
    ("Leellamarz", "Change", "Show Me the Money 8"),
    ("Black Nut", "100", "Show Me the Money 4"),
    ("Louie", "GO", "Show Me the Money 4"),
    ("Truedy", "My Light", "Show Me the Money 4"),
    ("Basick", "Stand Up", "Show Me the Money 4"),
    ("Iron", "Rain Shower", "Show Me the Money 4"),
    ("Killagramz", "Good Morning", "Show Me the Money 5"),
    ("Hanhae", "Drop", "Show Me the Money 5"),
    ("C Jamm", "The Last", "Show Me the Money 5"),
    ("BewhY", "The Fiery", "The Fiery"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Crush", "Your Dress", ""),
    ("Heize", "Round and Round", ""),
    ("Zion.T", "Knock", "Show Me the Money 5"),
    ("Simon Dominic", "DAx4", "DAx4"),
    ("Punchnello", "Cool", "Cool"),
    ("Gray", "Tik Tak Tok", ""),
    ("Dean", "Pompeii", ""),
    ("Heize", "HAPPEN", "HAPPEN"),
    ("Sik-K", "NEONBEAM", "FL1X"),
    ("Giriboy", "Engineering", "Engineering"),
    ("Swings", "Upgrade III", "Upgrade III"),
    ("Mino", "Trigger", "XX"),
    ("Loco", "Hero", "Hero"),
    ("Jay Park", "Likes", ""),
    ("Nafla", "Natural Born Killers", "Natural Born Killers"),
    ("Loopy", "King Loopy", "King Loopy"),
    ("Changmo", "Ring Ding", "Maestro"),
    ("PH-1", "Homebody", "YIN YANG"),
    ("Coogie", "Bouncin'", "Coogie"),
    ("HAON", "Blue", "Penumbra"),
    ("Ash Island", "Howling", "Ash Island"),
    ("Leellamarz", "Don`t Call Me", "To Be Continued"),
    ("TOIL", "Money", "1989"),
    ("Blase", "Passionfruit", ""),
    ("Woodie Gochild", "Dirtbag", "#GOchild"),
    ("Jvcki Wai", "Doughnet", "Exposure"),
    ("Punchnello", "Cool", "Cool"),
    ("Tablo", "Drill Presents", "Drill Presents: Tablo x Fantasy"),
    ("Paloalto", "Sunday Service", "Shangri-La"),
    ("Simon Dominic", "NO OPEN FLAME", "NO OPEN FLAME"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("NO:EL", "Rain Drop", "Rain Drop"),
    ("Kid Ash", "Orca", "Orca-Tape"),
    ("Flowsik", "We On", "Show Me the Money 777"),
    ("Reddy", "Think", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Jessi", "Gucci", "Show Me the Money 777"),
    ("Punchnello", "If You", "Show Me the Money 777"),
    ("Loopy", "No Loopy", "Show Me the Money 777"),
    ("Nafla", "What", "Show Me the Money 777"),
    ("Mino", "Fear", "Show Me the Money 777"),
    ("D.Ark", "Undercover", "Show Me the Money 777"),
    ("Verbal Jint", "Rap Genius No. 9", "Rap Genius No. 9"),
    ("Primary", "Planetarium", ""),
    ("Elo", "Tattoo On My Heart", "Tattoo On My Heart"),
    ("Swings", "Remedy", "Remedy"),
    ("Deepflow", "Flow the Life 4", "Flow the Life 4"),
    ("Don Mills", "Don Mills Is Angry 4", "Don Mills Is Angry 4"),
    ("Huckleberry P", "Mantra 4", "Mantra 4"),
    ("Zico", "What's Wrong?", "What's Wrong?"),
    ("Crush", "WooAh", "From Midnight to Sunrise"),
    ("Dean", "DMT", ""),
    ("Sik-K", "WATER", "FL1X"),
    ("Giriboy", "PlanetariuM", "Engineering"),
    ("Swings", "Brand New Day", "Upgrade III"),
    ("Mino", "Body", "XX"),
    ("Loco", "Some", "Hero"),
    ("Gray", "Late Night", "Gray Season 2.5"),
    ("Coogie", "Wifey", "Emo #1"),
    ("HAON", "Blossom", "Penumbra"),
    ("Ash Island", "Limousine Vision", "Ash Island"),
    ("Leellamarz", "Wavy", ""),
    ("TOIL", "Rollin", "1989"),
    ("Mirani", "Ticket", "Ticket"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("Punchnello", "If You", "Show Me the Money 777"),
    ("Dynamic Duo", "ECO", "ECO"),
    ("Swings", "Heavy Smoker", "Growing Pains"),
    ("Primary", "eee", "2"),
    ("Mino", "Do It", "Do It"),
    ("Bobby", "One Shot", "One Shot"),
    ("Penomeco", "Shy (Suup)", "Shy"),
    ("Kid Milli", "A List", "Show Me the Money 8"),
    ("PH-1", "RUBBER", "Show Me the Money 8"),
    ("Lil Boi", "VVS", "Show Me the Money 8"),
    ("Mudd the student", "IndiGO", "Show Me the Money 8"),
    ("Leellamarz", "Change", "Show Me the Money 8"),
    ("Mirani", "VVS", "Show Me the Money 8"),
    ("Lil Moshpit", "VVS", "Show Me the Money 8"),
    ("YunB", "VVS", "Show Me the Money 8"),
    ("Koonta", "VVS", "Show Me the Money 8"),
    ("Swings", "VVS", "Show Me the Money 8"),
    ("BewhY", "VVS", "Show Me the Money 8"),
    ("Giriboy", "VVS", "Show Me the Money 8"),
    ("Nafla", "VVS", "Show Me the Money 8"),
    ("Loopy", "VVS", "Show Me the Money 8"),
    ("Changmo", "VVS", "Show Me the Money 8"),
    ("Coogie", "VVS", "Show Me the Money 8"),
    ("Ash Island", "VVS", "Show Me the Money 8"),
    ("HAON", "VVS", "Show Me the Money 8"),
    ("TOIL", "VVS", "Show Me the Money 8"),
    ("Blase", "VVS", "Show Me the Money 8"),
    ("Woodie Gochild", "VVS", "Show Me the Money 8"),
    ("Sokodomo", "VVS", "Show Me the Money 8"),
    ("Owen Ovadoz", "VVS", "Show Me the Money 8"),
    ("Epik High", "On Bended Knee", "Sleepless in __________"),
    ("Epik High", "Daylight", "Sleepless in __________"),
    ("Epik High", "Another Winter", "Sleepless in __________"),
    ("Epik High", "Sleepless in __________", "Sleepless in __________"),
    ("Crush", "Ego", "wonderego"),
    ("Dynamic Duo", "A DynamicAffair", "A DynamicAffair"),
    ("Swings", "The King", "Growing Pains 2"),
    ("Primary", "eee", "2"),
    ("Mino", "Do It", "Do It"),
    ("Bobby", "One Shot", "One Shot"),
    ("Code Kunst", "ARCHIVE", "Code Kunst Archive Pack 02"),
    ("Crush", "None", "From Midnight To Sunrise"),
    ("Zico", "Human", "Human"),
    ("Mudd the student", "Open", "Show Me the Money 8"),
    ("Leellamarz", "Barcode", "Show Me the Money 8"),
    ("TOIL", "Panorama", "Show Me the Money 8"),
    ("Blase", "Tic Tac", "Show Me the Money 8"),
    ("Woodie Gochild", "WaRRior", "Show Me the Money 8"),
    ("Sokodomo", "IF I", "Show Me the Money 8"),
    ("Koonta", "Grandma", "Show Me the Money 8"),
    ("Owen Ovadoz", "119 REMIX", "Show Me the Money 8"),
    ("Giriboy", "on my way", "Show Me the Money 8"),
    ("Lil Moshpit", "BITE", "Show Me the Money 8"),
    ("Mudd the student", "MEMORIES", "Show Me the Money 8"),
    ("Mirani", "VANS", "Show Me the Money 8"),
    ("Blase", "Fill It", "Show Me the Money 8"),
    ("Lil Boi", "Only", "Show Me the Money 8"),
    ("Lil Boi", "Gigantic", "Show Me the Money 8"),
    ("YunB", "Piano", "Show Me the Money 8"),
    ("Swings", "IndiGO", "Show Me the Money 8"),
]

free = []
seen = set()
for a, t, al in EXTRA:
    k = norm_key(a, t)
    if k in seen:
        continue
    seen.add(k)
    if k in used or k in exclude:
        continue
    used.add(k)
    free.append((a, t, al))
print("free", len(free))
for x in free[:15]:
    print(x)
