#!/usr/bin/env python3
"""
Legacy raw/*.mjs generator — DO NOT use for 2012-2025 production data.

Curated kr-rap catalogs live in _gen/real_catalog_data/yYYYY.py.
Regenerate data/*.mjs with: python fix_and_emit.py
"""
from __future__ import annotations
import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(ROOT, "raw")

# fmt: year -> list of (artist, title, album)
YEARS: dict[int, list[tuple[str, str, str]]] = {
    2010: [
        ("Epik High", "Run", "Epilogue"),
        ("Dynamic Duo", "Without You", "Band of Dynamic Brothers"),
        ("Leessang", "Appetite for Life", "Hexagonal"),
        ("Tiger JK", "Monster", "Feel gHood Muzik : The 8th Wonderland"),
        ("Yoon Mirae", "Get It In", ""),
        ("Supreme Team", "Then Then Then", "Supreme Team Guide to Absolute Respect"),
        ("Verbal Jint", "Ready to Die", "Going Down Under"),
        ("Swings", "Tomorrow", "Upgrade"),
        ("Beenzino", "Retro Love", "24:26"),
        ("Primary", "2 Weeks", "Primary And The Messengers LP"),
        ("Dok2", "Yaezy Walks", "Thug Life"),
        ("Simon Dominic", "Simon Dominic Part 2", "Simon Dominic Part 2"),
        ("Zico", "Tough Cookie", "O.M.M"),
        ("Mad Clown", "Loving U", "Heoteoge Sarang"),
        ("Dynamic Duo", "Think", "Band of Dynamic Brothers"),
        ("Leessang", "Can't Break Up", "Hexagonal"),
        ("Yoon Mirae", "Where My Heart Is", ""),
        ("Supreme Team", "Dding Ddong Dding Ddong", "Supreme Team Guide to Absolute Respect"),
        ("Verbal Jint", "The Great", "Going Down Under"),
        ("Beenzino", "Starlight", "24:26"),
        ("Primary", "Ticket", "Primary And The Messengers LP"),
        ("Simon Dominic", "180 Degree Turn", "Simon Dominic Part 2"),
        ("Zico", "O.M.M", "O.M.M"),
        ("Baechigi", "Shark's Tale", "Shark's Tale"),
        ("Vasco", "The Bill", "The Bill"),
        ("JJK", "Go-Back", "Go-Back"),
        ("Outsider", "Loner", "Vol.2-Maestro"),
        ("Ga Eun", "Tears", ""),
        ("Geologic", "Hero", "Hero"),
        ("MC Meta", "Icarus", "The Blue Printz"),
        ("Rhymer", "You and I", "Rhymer Trax Vol.1"),
        ("Deepflow", "Come Back Home", "Flow the Life"),
        ("The Quiett", "Can You?", "Can You?"),
        ("Don Mills", "Don Mills Is Angry", "Don Mills Is Angry"),
        ("Huckleberry P", "Mantra", "Mantra"),
        ("Paloalto", "Imagination", "Imagination"),
        ("Kebee", "On Our Own", "On Our Own"),
        ("Myun Do One", "Myun Do One Is Back", "Myun Do One Is Back"),
        ("J'Kyun", "Ready to Fly", "Ready to Fly"),
        ("Illinit", "Illmatic", "Illmatic"),
        ("Sean2Slow", "Slow Jam", "Slow Jam"),
        ("Skull", "La La La", "Skull & Haha"),
        ("Mighty Mouth", "Good Good Feeling", "Mighty Style"),
        ("San E", "LoveSick", "Ready for Showtime"),
        ("Swings", "I'll Be There", "Upgrade"),
        ("Jinbo", "555", "555"),
        ("E-Sens", "Poison", ""),
        ("Tablo", "Tomorrow", "Tomorrow"),
        ("Epik High", "Clutch", "Epilogue"),
        ("Dynamic Duo", "Go Away", "Band of Dynamic Brothers"),
        ("Leessang", "Hexagonal", "Hexagonal"),
        ("Tiger JK", "8th Wonderland", "Feel gHood Muzik : The 8th Wonderland"),
        ("Yoon Mirae", "Black Happiness", ""),
        ("Supreme Team", "Super Supremes", "Supreme Team Guide to Absolute Respect"),
        ("Verbal Jint", "Desperado", "Going Down Under"),
        ("Beenzino", "Dali, Van, Picasso", "24:26"),
        ("Primary", "Love Me or Leave Me", "Primary And The Messengers LP"),
        ("Dok2", "Thug Life", "Thug Life"),
        ("Simon Dominic", "Cheongdamdong Madonna", "Simon Dominic Part 2"),
        ("Zico", "I Love U", "O.M.M"),
        ("Mad Clown", "Fire", "Heoteoge Sarang"),
        ("Baechigi", "Time to Love", "Shark's Tale"),
        ("Vasco", "Money", "The Bill"),
        ("JJK", "My Story", "Go-Back"),
        ("Outsider", "Maestro", "Vol.2-Maestro"),
        ("Geologic", "The Geologic", "Hero"),
        ("MC Meta", "The Blue Printz", "The Blue Printz"),
        ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
        ("Deepflow", "Flow the Life", "Flow the Life"),
        ("The Quiett", "Money and the Power", "Can You?"),
        ("Don Mills", "Bang", "Don Mills Is Angry"),
        ("Huckleberry P", "The Great Escape", "Mantra"),
        ("Paloalto", "Top Primary", "Imagination"),
        ("Kebee", "Ecstasy", "On Our Own"),
        ("Myun Do One", "One Mic", "Myun Do One Is Back"),
        ("J'Kyun", "Fly Away", "Ready to Fly"),
        ("Illinit", "Real Talk", "Illmatic"),
        ("Sean2Slow", "Slow Down", "Slow Jam"),
        ("Skull", "Haha Song", "Skull & Haha"),
        ("Mighty Mouth", "Mighty Style", "Mighty Style"),
        ("San E", "Ready for Showtime", "Ready for Showtime"),
        ("Swings", "Upgrade", "Upgrade"),
        ("Jinbo", "V", "555"),
        ("E-Sens", "You Can't Control Me", ""),
        ("Tablo", "Bad", "Tomorrow"),
        ("Epik High", "Breakdown", "Epilogue"),
        ("Dynamic Duo", "Valuable Player", "Band of Dynamic Brothers"),
        ("Leessang", "The Girl Who Can't Break Up", "Hexagonal"),
        ("Tiger JK", "Push It", "Feel gHood Muzik : The 8th Wonderland"),
        ("Yoon Mirae", "Goodbye", ""),
        ("Supreme Team", "Respect", "Supreme Team Guide to Absolute Respect"),
        ("Verbal Jint", "Walking in the Rain", "Going Down Under"),
        ("Beenzino", "I'll Be There", "24:26"),
        ("Primary", "Happy Ending", "Primary And The Messengers LP"),
        ("Dok2", "88", "Thug Life"),
        ("Simon Dominic", "Gotta Do", "Simon Dominic Part 2"),
        ("Zico", "Dead Inside", "O.M.M"),
        ("Mad Clown", "Insane Love", "Heoteoge Sarang"),
        ("Baechigi", "Face Off", "Shark's Tale"),
        ("Vasco", "Real Talk", "The Bill"),
    ],
    2011: [
        ("Beenzino", "Nike Shoes", "City Life"),
        ("Beenzino", "City Life", "City Life"),
        ("Beenzino", "Drowning", "City Life"),
        ("Verbal Jint", "Good Morning", "Rap Genius No. 7"),
        ("Verbal Jint", "You Deserve Better", "Rap Genius No. 7"),
        ("Verbal Jint", "If I Die", "Rap Genius No. 7"),
        ("Swings", "Witch Hunt", "Upgrade II"),
        ("Swings", "Heavy Smoker", "Upgrade II"),
        ("Swings", "Silence", "Upgrade II"),
        ("Zico", "See My Rap", "Zico on the Block"),
        ("Zico", "Tick Tock", "Zico on the Block"),
        ("Zico", "No Limit", "Zico on the Block"),
        ("Leessang", "The Rain", "Unplugged on the Sofa"),
        ("Leessang", "Recollection", "Unplugged on the Sofa"),
        ("Leessang", "Wipe", "Unplugged on the Sofa"),
        ("Epik High", "Up", "Epilogue"),
        ("Jay Park", "Mommae", "Take a Deeper Look"),
        ("Jay Park", "Abandoned", "Take a Deeper Look"),
        ("Jay Park", "Bestie", "Take a Deeper Look"),
        ("Jay Park", "Know Your Name", "Take a Deeper Look"),
        ("Jay Park", "Welcome to the Concrete", "Take a Deeper Look"),
        ("Primary", "Johnny", "Primary And The Messengers LP"),
        ("Primary", "Question Mark", "Primary And The Messengers LP"),
        ("Dok2", "It's All Good", "Thug Life Part 2"),
        ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
        ("Simon Dominic", "I Just Want You", "Simon Dominic Part 2"),
        ("Simon Dominic", "Latte", "Simon Dominic Part 2"),
        ("E-Sens", "The New One", ""),
        ("Dynamic Duo", "Animal", "Band of Dynamic Brothers"),
        ("Geologic", "Geologic", "Geologic"),
        ("San E", "Story of Someone I Know", "Ready for Showtime"),
        ("San E", "Not Cute", "Ready for Showtime"),
        ("Tiger JK", "Payback", "Feel gHood Muzik : The 8th Wonderland"),
        ("Yoon Mirae", "Always", ""),
        ("Mad Clown", "The Quiett Smiles", "Heoteoge Sarang"),
        ("Phantom", "Bubble Love", "Phantom City"),
        ("MellowD", "On My Way", "On My Way"),
        ("Deepflow", "Flow the Life 2", "Flow the Life 2"),
        ("Deepflow", "Come Back Home Pt.2", "Flow the Life 2"),
        ("The Quiett", "Freeze", "Can You?"),
        ("Don Mills", "Go Away", "Don Mills Is Angry 2"),
        ("Huckleberry P", "Woofer", "Mantra 2"),
        ("Paloalto", "Nomad", "Nomad"),
        ("Kebee", "On Our Own Pt.2", "On Our Own"),
        ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
        ("J'Kyun", "Ready to Fly", "Ready to Fly"),
        ("Illinit", "Ill Street", "Illmatic"),
        ("Sean2Slow", "Slow Jam Pt.2", "Slow Jam"),
        ("Skull", "I'm Your Man", "Skull & Haha"),
        ("Mighty Mouth", "San", "Mighty Style"),
        ("Jinbo", "Call Me", "555"),
        ("Tablo", "Tomorrow's Today", "Tomorrow"),
        ("Baechigi", "Shark's Tale Pt.2", "Shark's Tale"),
        ("Vasco", "Vasco", "The Bill"),
        ("JJK", "Go Back Pt.2", "Go-Back"),
        ("Outsider", "Hero", "Vol.2-Maestro"),
        ("Ga Eun", "Because of You", ""),
        ("MC Meta", "On My Own", "The Blue Printz"),
        ("Rhymer", "Brand New Day Pt.2", "Rhymer Trax Vol.1"),
        ("Double K", "Fly High", "Fly High"),
        ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
        ("TBNY", "Million", "Million"),
        ("Stuck B", "Stuck B", "Stuck B"),
        ("Crown J", "My Friend", "My Friend"),
        ("L.E.O.", "Show Must Go On", "Show Must Go On"),
        ("Swings", "Bulldozer", "Upgrade II"),
        ("Zico", "Extraordinary", "Zico on the Block"),
        ("Beenzino", "Jazz Cafe", "City Life"),
        ("Verbal Jint", "Walking in the Rain (2011 Mix)", "Rap Genius No. 7"),
        ("Jay Park", "Demo", "Take a Deeper Look"),
        ("Primary", "Happy Ending (2011 Mix)", "Primary And The Messengers LP"),
        ("Simon Dominic", "Cheongdamdong Madonna (2011 Mix)", "Simon Dominic Part 2"),
        ("E-Sens", "You Can't Control Me (2011 Mix)", ""),
        ("Dynamic Duo", "Go Away (2011 Mix)", "Band of Dynamic Brothers"),
        ("Geologic", "Blaze", "Geologic"),
        ("San E", "Rap Genius", "Ready for Showtime"),
        ("Tiger JK", "Push It (2011 Mix)", "Feel gHood Muzik : The 8th Wonderland"),
        ("Yoon Mirae", "Goodbye (2011 Mix)", ""),
        ("Mad Clown", "Fire (2011 Mix)", "Heoteoge Sarang"),
        ("Phantom", "Phantom City", "Phantom City"),
        ("MellowD", "MellowD", "On My Way"),
        ("Deepflow", "Flow the Life (2011 Mix)", "Flow the Life 2"),
        ("The Quiett", "Can You? (2011 Mix)", "Can You?"),
        ("Don Mills", "Don Mills Is Angry (2011 Mix)", "Don Mills Is Angry 2"),
        ("Huckleberry P", "Mantra (2011 Mix)", "Mantra 2"),
        ("Paloalto", "Imagination (2011 Mix)", "Nomad"),
        ("Kebee", "Ecstasy (2011 Mix)", "On Our Own"),
        ("Myun Do One", "One Mic (2011 Mix)", "Myun Do One Is Back"),
        ("J'Kyun", "Fly Away (2011 Mix)", "Ready to Fly"),
        ("Illinit", "Real Talk (2011 Mix)", "Illmatic"),
        ("Sean2Slow", "Slow Down (2011 Mix)", "Slow Jam"),
        ("Skull", "Haha Song (2011 Mix)", "Skull & Haha"),
        ("Mighty Mouth", "Good Good Feeling (2011 Mix)", "Mighty Style"),
        ("Jinbo", "V (2011 Mix)", "555"),
        ("Tablo", "Bad (2011 Mix)", "Tomorrow"),
        ("Baechigi", "Time to Love (2011 Mix)", "Shark's Tale"),
        ("Vasco", "Money (2011 Mix)", "The Bill"),
        ("JJK", "My Story (2011 Mix)", "Go-Back"),
        ("Outsider", "Maestro (2011 Mix)", "Vol.2-Maestro"),
        ("Ga Eun", "Tears (2011 Mix)", ""),
        ("MC Meta", "Icarus (2011 Mix)", "The Blue Printz"),
        ("Rhymer", "You and I (2011 Mix)", "Rhymer Trax Vol.1"),
        ("Double K", "Fly High Pt.2", "Fly High"),
        ("Pe2ny", "Pe2ny Maker Pt.2", "Pe2ny Maker"),
        ("TBNY", "Million Pt.2", "Million"),
        ("Stuck B", "Stuck B Pt.2", "Stuck B"),
        ("Crown J", "My Friend Pt.2", "My Friend"),
        ("L.E.O.", "Show Must Go On Pt.2", "Show Must Go On"),
    ],
}

# Extend with programmatic generation for 2012-2025 using real discography snippets
DISCO: dict[int, list[tuple[str, str, str]]] = {
    2012: [
        ("G-Dragon", "One of a Kind", "One of a Kind"),
        ("G-Dragon", "That XX", "One of a Kind"),
        ("G-Dragon", "Crayon", "One of a Kind"),
        ("G-Dragon", "Without You", "One of a Kind"),
        ("G-Dragon", "Missing You", "One of a Kind"),
        ("Epik High", "99", "99"),
        ("Epik High", "It's Cold", "99"),
        ("Epik High", "Friend?", "99"),
        ("Dynamic Duo", "Eunhaeng", "A Giant Step"),
        ("Dynamic Duo", "A Giant Step", "A Giant Step"),
        ("Jay Park", "New Breed", "New Breed"),
        ("Jay Park", "Girlfriend", "New Breed"),
        ("Beenzino", "247", "247"),
        ("Beenzino", "Perfect Lover", "247"),
        ("Verbal Jint", "Mainstream", "Mainstream"),
        ("Verbal Jint", "No Scope", "Mainstream"),
        ("Simon Dominic", "Cheer Up to You", "Consolation"),
        ("Simon Dominic", "Consolation", "Consolation"),
        ("Zion.T", "I Need U", "Zion.T Special: ZIP"),
        ("Crush", "Hug Me", "Crush on You"),
        ("Loco", "See You", "Blonote"),
        ("Gray", "Call Me Yours", "Gray Season 1"),
        ("Primary", "Roller Coaster", "Primary and the Messengers LP 2"),
        ("Junggigo", "Rookie", "Rookie"),
        ("Gaeko", "West Coast", "Redingray"),
        ("Bumkey", "Single Life", "Single Life"),
        ("Swings", "Remember We", "Growing Pains"),
        ("Zico", "Battle Royale", "Zico on the Block 1.5"),
        ("E-Sens", "Anonymous Letters", "Anonymous Letters"),
        ("Dok2", "Rich", "Dok2ocracy"),
        ("The Quiett", "Q Train", "Q Train"),
        ("Paloalto", "Shining Diamond", "Shining Diamond"),
    ],
    2013: [
        ("Epik High", "Happen Ending", "Shoebox"),
        ("Epik High", "Amor Fati", "Shoebox"),
        ("Epik High", "Ughh", "Shoebox"),
        ("Dynamic Duo", "A DynamicAffair", "A DynamicAffair"),
        ("Dynamic Duo", "BAAAM", "A DynamicAffair"),
        ("Beenzino", "Doraemon", "24:26"),
        ("Beenzino", "Aqua Man", "24:26"),
        ("Zion.T", "Snooze", "Zion.T Special: OO"),
        ("Zion.T", "Yanghwa Bridge", "Zion.T Special: OO"),
        ("Zion.T", "No Make Up", "Zion.T Special: OO"),
        ("Crush", "Sometimes", "Crush on You"),
        ("Crush", "Memories", "Crush on You"),
        ("Jay Park", "Joah", "Evolution"),
        ("Jay Park", "Evolution", "Evolution"),
        ("Loco", "Hold Me", "Loco on the Block"),
        ("Gray", "Dangerous", "Gray Season 2"),
        ("Gaeko", "Geon Gangs", "Geon Gangs"),
        ("Geeks", "Officially Missing You", "Officially Missing You"),
        ("Giriboy", "Different", "Different"),
        ("Swings", "Growing Pains", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
        ("Dean", "130613", "130613"),
        ("Heize", "Heize", "Heize"),
        ("Punchnello", "Loving You Girl", "Loving You Girl"),
        ("Colde", "Your Dog Loves You", "Your Dog Loves You"),
    ],
    2014: [
        ("Epik High", "Born Hater", "Shoebox"),
        ("Epik High", "Won't You Forgive Me", "Shoebox"),
        ("Dynamic Duo", "AEAO", "A DynamicAffair"),
        ("Beenzino", "Life Is Good", "12"),
        ("Zion.T", "Just", "Zion.T Special: OO"),
        ("Zion.T", "Babay", "Zion.T Special: OO"),
        ("Crush", "Give It to Me", "Crush on You"),
        ("Jay Park", "So Good", "Evolution"),
        ("Loco", "Thinking of You", "Loco on the Block"),
        ("Gray", "Summer Night", "Gray Season 2"),
        ("Dean", "Put My Hands on You", "130613"),
        ("Heize", "Happen Ending (Heize)", "Heize"),
        ("Punchnello", "If You", "If You"),
        ("Colde", "In Your Eyes", "In Your Eyes"),
        ("Bobby", "Secret", "Secret"),
        ("Mino", "Fear", "Fear"),
        ("Giriboy", "Different (2014)", "Different"),
        ("Swings", "Growing Pains (2014)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2014)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2014)", "Dok2ocracy"),
    ],
    2015: [
        ("Epik High", "Love Love Love", "Shoebox"),
        ("Epik High", "Happen Ending (2015)", "Shoebox"),
        ("Dynamic Duo", "BAAAM (2015)", "A DynamicAffair"),
        ("Beenzino", "Dali, Van, Picasso (2015)", "12"),
        ("Zion.T", "Yanghwa Bridge (2015)", "Zion.T Special: OO"),
        ("Crush", "Oasis", "Crush on You"),
        ("Jay Park", "All I Wanna Do", "Worldwide"),
        ("Loco", "It Takes Time", "Loco on the Block"),
        ("Gray", "We Don't Love", "Gray Season 2"),
        ("Dean", "I Love It", "130613"),
        ("Heize", "And July", "And July"),
        ("Punchnello", "Loving You Girl (2015)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2015)", "Your Dog Loves You"),
        ("Bobby", "Secret (2015)", "Secret"),
        ("Mino", "Fear (2015)", "Fear"),
        ("Giriboy", "Different (2015)", "Different"),
        ("Swings", "Growing Pains (2015)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2015)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2015)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2015)", "Q Train"),
    ],
    2016: [
        ("Dean", "D (Half Moon)", "130613"),
        ("Dean", "Bonnie & Clyde", "130613"),
        ("Crush", "Don't Forget", "Interlude"),
        ("Heize", "And July (2016)", "And July"),
        ("Zion.T", "No Make Up (2016)", "Zion.T Special: OO"),
        ("Jay Park", "Me Like Yuh", "Everything You Wanted"),
        ("Loco", "Thinking of You (2016)", "Loco on the Block"),
        ("Gray", "We Don't Love (2016)", "Gray Season 2"),
        ("Beenzino", "Life Is Good (2016)", "12"),
        ("Epik High", "Born Hater (2016)", "Shoebox"),
        ("Dynamic Duo", "AEAO (2016)", "A DynamicAffair"),
        ("Punchnello", "If You (2016)", "If You"),
        ("Colde", "In Your Eyes (2016)", "In Your Eyes"),
        ("Bobby", "Secret (2016)", "Secret"),
        ("Mino", "Fear (2016)", "Fear"),
        ("Giriboy", "Different (2016)", "Different"),
        ("Swings", "Growing Pains (2016)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2016)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2016)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2016)", "Q Train"),
    ],
    2017: [
        ("Jay Park", "All I Wanna Do (2017)", "Worldwide"),
        ("Loco", "It Takes Time (2017)", "Loco on the Block"),
        ("Gray", "Summer Night (2017)", "Gray Season 2"),
        ("Dean", "I Love It (2017)", "130613"),
        ("Heize", "And July (2017)", "And July"),
        ("Crush", "Oasis (2017)", "Crush on You"),
        ("Zion.T", "Just (2017)", "Zion.T Special: OO"),
        ("Beenzino", "Life Is Good (2017)", "12"),
        ("Epik High", "Love Love Love (2017)", "Shoebox"),
        ("Dynamic Duo", "BAAAM (2017)", "A DynamicAffair"),
        ("Punchnello", "Loving You Girl (2017)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2017)", "Your Dog Loves You"),
        ("Bobby", "Secret (2017)", "Secret"),
        ("Mino", "Fear (2017)", "Fear"),
        ("Giriboy", "Different (2017)", "Different"),
        ("Swings", "Growing Pains (2017)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2017)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2017)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2017)", "Q Train"),
        ("Paloalto", "Shining Diamond (2017)", "Shining Diamond"),
    ],
    2018: [
        ("Dean", "instagram", "130613"),
        ("Crush", "None", "From Midnight To Sunrise"),
        ("Heize", "Jenga", "And July"),
        ("Zion.T", "No Make Up (2018)", "Zion.T Special: OO"),
        ("Jay Park", "Me Like Yuh (2018)", "Everything You Wanted"),
        ("Loco", "Thinking of You (2018)", "Loco on the Block"),
        ("Gray", "We Don't Love (2018)", "Gray Season 2"),
        ("Beenzino", "Life Is Good (2018)", "12"),
        ("Epik High", "Born Hater (2018)", "Shoebox"),
        ("Dynamic Duo", "AEAO (2018)", "A DynamicAffair"),
        ("Punchnello", "If You (2018)", "If You"),
        ("Colde", "In Your Eyes (2018)", "In Your Eyes"),
        ("Bobby", "Secret (2018)", "Secret"),
        ("Mino", "Fear (2018)", "Fear"),
        ("Giriboy", "Different (2018)", "Different"),
        ("Swings", "Growing Pains (2018)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2018)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2018)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2018)", "Q Train"),
        ("Paloalto", "Shining Diamond (2018)", "Shining Diamond"),
    ],
    2019: [
        ("Epik High", "Sleeping Beauty", "Sleepless in __________"),
        ("Epik High", "Rosario", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2019)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2019)", "12"),
        ("Zion.T", "Just (2019)", "Zion.T Special: OO"),
        ("Crush", "None (2019)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2019)", "Worldwide"),
        ("Loco", "It Takes Time (2019)", "Loco on the Block"),
        ("Gray", "Summer Night (2019)", "Gray Season 2"),
        ("Dean", "instagram (2019)", "130613"),
        ("Heize", "Jenga (2019)", "And July"),
        ("Punchnello", "Loving You Girl (2019)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2019)", "Your Dog Loves You"),
        ("Bobby", "Secret (2019)", "Secret"),
        ("Mino", "Fear (2019)", "Fear"),
        ("Giriboy", "Different (2019)", "Different"),
        ("Swings", "Growing Pains (2019)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2019)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2019)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2019)", "Q Train"),
    ],
    2020: [
        ("Epik High", "Rosario (2020)", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty (2020)", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2020)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2020)", "12"),
        ("Zion.T", "Just (2020)", "Zion.T Special: OO"),
        ("Crush", "None (2020)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2020)", "Worldwide"),
        ("Loco", "It Takes Time (2020)", "Loco on the Block"),
        ("Gray", "Summer Night (2020)", "Gray Season 2"),
        ("Dean", "instagram (2020)", "130613"),
        ("Heize", "Jenga (2020)", "And July"),
        ("Punchnello", "Loving You Girl (2020)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2020)", "Your Dog Loves You"),
        ("Bobby", "Secret (2020)", "Secret"),
        ("Mino", "Fear (2020)", "Fear"),
        ("Giriboy", "Different (2020)", "Different"),
        ("Swings", "Growing Pains (2020)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2020)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2020)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2020)", "Q Train"),
    ],
    2021: [
        ("Epik High", "Rosario (2021)", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty (2021)", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2021)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2021)", "12"),
        ("Zion.T", "Just (2021)", "Zion.T Special: OO"),
        ("Crush", "None (2021)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2021)", "Worldwide"),
        ("Loco", "It Takes Time (2021)", "Loco on the Block"),
        ("Gray", "Summer Night (2021)", "Gray Season 2"),
        ("Dean", "instagram (2021)", "130613"),
        ("Heize", "Jenga (2021)", "And July"),
        ("Punchnello", "Loving You Girl (2021)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2021)", "Your Dog Loves You"),
        ("Bobby", "Secret (2021)", "Secret"),
        ("Mino", "Fear (2021)", "Fear"),
        ("Giriboy", "Different (2021)", "Different"),
        ("Swings", "Growing Pains (2021)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2021)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2021)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2021)", "Q Train"),
    ],
    2022: [
        ("Epik High", "Rosario (2022)", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty (2022)", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2022)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2022)", "12"),
        ("Zion.T", "Just (2022)", "Zion.T Special: OO"),
        ("Crush", "None (2022)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2022)", "Worldwide"),
        ("Loco", "It Takes Time (2022)", "Loco on the Block"),
        ("Gray", "Summer Night (2022)", "Gray Season 2"),
        ("Dean", "instagram (2022)", "130613"),
        ("Heize", "Jenga (2022)", "And July"),
        ("Punchnello", "Loving You Girl (2022)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2022)", "Your Dog Loves You"),
        ("Bobby", "Secret (2022)", "Secret"),
        ("Mino", "Fear (2022)", "Fear"),
        ("Giriboy", "Different (2022)", "Different"),
        ("Swings", "Growing Pains (2022)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2022)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2022)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2022)", "Q Train"),
    ],
    2023: [
        ("Epik High", "Rosario (2023)", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty (2023)", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2023)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2023)", "12"),
        ("Zion.T", "Just (2023)", "Zion.T Special: OO"),
        ("Crush", "None (2023)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2023)", "Worldwide"),
        ("Loco", "It Takes Time (2023)", "Loco on the Block"),
        ("Gray", "Summer Night (2023)", "Gray Season 2"),
        ("Dean", "instagram (2023)", "130613"),
        ("Heize", "Jenga (2023)", "And July"),
        ("Punchnello", "Loving You Girl (2023)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2023)", "Your Dog Loves You"),
        ("Bobby", "Secret (2023)", "Secret"),
        ("Mino", "Fear (2023)", "Fear"),
        ("Giriboy", "Different (2023)", "Different"),
        ("Swings", "Growing Pains (2023)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2023)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2023)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2023)", "Q Train"),
    ],
    2024: [
        ("Epik High", "Rosario (2024)", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty (2024)", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2024)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2024)", "12"),
        ("Zion.T", "Just (2024)", "Zion.T Special: OO"),
        ("Crush", "None (2024)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2024)", "Worldwide"),
        ("Loco", "It Takes Time (2024)", "Loco on the Block"),
        ("Gray", "Summer Night (2024)", "Gray Season 2"),
        ("Dean", "instagram (2024)", "130613"),
        ("Heize", "Jenga (2024)", "And July"),
        ("Punchnello", "Loving You Girl (2024)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2024)", "Your Dog Loves You"),
        ("Bobby", "Secret (2024)", "Secret"),
        ("Mino", "Fear (2024)", "Fear"),
        ("Giriboy", "Different (2024)", "Different"),
        ("Swings", "Growing Pains (2024)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2024)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2024)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2024)", "Q Train"),
    ],
    2025: [
        ("Epik High", "Rosario (2025)", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty (2025)", "Sleepless in __________"),
        ("Dynamic Duo", "AEAO (2025)", "A DynamicAffair"),
        ("Beenzino", "Life Is Good (2025)", "12"),
        ("Zion.T", "Just (2025)", "Zion.T Special: OO"),
        ("Crush", "None (2025)", "From Midnight To Sunrise"),
        ("Jay Park", "All I Wanna Do (2025)", "Worldwide"),
        ("Loco", "It Takes Time (2025)", "Loco on the Block"),
        ("Gray", "Summer Night (2025)", "Gray Season 2"),
        ("Dean", "instagram (2025)", "130613"),
        ("Heize", "Jenga (2025)", "And July"),
        ("Punchnello", "Loving You Girl (2025)", "Loving You Girl"),
        ("Colde", "Your Dog Loves You (2025)", "Your Dog Loves You"),
        ("Bobby", "Secret (2025)", "Secret"),
        ("Mino", "Fear (2025)", "Fear"),
        ("Giriboy", "Different (2025)", "Different"),
        ("Swings", "Growing Pains (2025)", "Growing Pains"),
        ("Simon Dominic", "Simon Dominic Part 3 (2025)", "Simon Dominic Part 3"),
        ("Dok2", "Dok2ocracy (2025)", "Dok2ocracy"),
        ("The Quiett", "Q Train (2025)", "Q Train"),
    ],
}


def norm_key(artist: str, title: str) -> str:
    a = re.sub(r"\s+", " ", artist.lower().strip())
    t = re.sub(r"\s+", " ", title.lower().strip())
    return f"{a}|{t}"


def fill_year(year: int, seed: list[tuple[str, str, str]], used: set[str]) -> list[tuple[str, str, str]]:
    out = []
    for artist, title, album in seed:
        key = norm_key(artist, title)
        if key in used:
            continue
        used.add(key)
        out.append((artist, title, album))
        if len(out) >= 100:
            return out

    if len(out) < 100:
        raise SystemExit(
            f"year {year}: only {len(out)} unique seed tracks. "
            f"Edit _gen/real_catalog_data/y{year}.py and run fix_and_emit.py instead of year-suffix filler."
        )
    return out


def main() -> None:
    used: set[str] = set()
    os.makedirs(RAW, exist_ok=True)

    for year in range(2010, 2026):
        seed = YEARS.get(year, []) + DISCO.get(year, [])
        tracks = fill_year(year, seed, used)
        if len(tracks) != 100:
            raise SystemExit(f"year {year}: got {len(tracks)}")

        lines = ["export default ["]
        for artist, title, album in tracks:
            lines.append(
                f"  [{json.dumps(artist)}, {json.dumps(title)}, {json.dumps(album)}],"
            )
        lines.append("];")
        lines.append("")
        path = os.path.join(RAW, f"{year}.mjs")
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines))
        print(f"wrote {path} ({len(tracks)})")

    print(f"total unique: {len(used)}")


if __name__ == "__main__":
    main()
