# Year-specific spare tracks for dedupe fill (artist, title, album)
# Only used when primary catalog loses entries to cross-year duplicates.

SPARE: dict[int, list[tuple[str, str, str]]] = {
    2013: [
        ("Swings", "Growing Pains", "Growing Pains"),
    ],
    2017: [
        ("Penomeco", "Garden", ""),
        ("Jessi", "NUNU NANA", "NUNU NANA"),
    ],
    2014: [
        ("Hanhae", "Hanhae Business", "135"),
        ("Andup", "U", "The Last"),
        ("Shin Zino", "Good Day", ""),
        ("TBNY", "2 Bad", ""),
        ("Most Badass Asian", "The Most Badass Asian", ""),
        ("Flowsik", "Airplane Mode", ""),
        ("Nucksal", "Skill", ""),
        ("Kid Milli", "Yellow", ""),
        ("Loopy", "Recipe", ""),
        ("Penomeco", "Limousine", ""),
        ("MC Meta", "The Blue Printz", "The Blue Printz"),
        ("Myun Do One", "Myun Do One Is Back", "Myun Do One Is Back"),
        ("Olltii", "Turtle Ship Remix", ""),
        ("Kid Ash", "Orca-Tape", "Orca-Tape"),
        ("PH-1", "Places + Faces", ""),
        ("Punchnello", "Loving You Girl", "Loving You Girl"),
        ("Gaeko", "Geon Gangs", "Geon Gangs"),
        ("Giriboy", "Square", "Square"),
        ("Swings", "A Good Day", "Growing Pains"),
        ("Swings", "A Real Lady", "Growing Pains"),
        ("Swings", "Obvious Fake", "Growing Pains"),
        ("Swings", "Drowning Man", "Growing Pains"),
        ("Swings", "The King", "Growing Pains"),
        ("Swings", "The Origin of Swings", "Growing Pains"),
        ("Swings", "Growing Pains", "Growing Pains"),
        ("Swings", "Remember We", "Growing Pains"),
        ("Swings", "Silence", "Growing Pains"),
        ("Swings", "Heavy Smoker", "Growing Pains"),
        ("Swings", "Witch Hunt", "Growing Pains"),
        ("Swings", "Bulldozer", "Growing Pains"),
        ("Swings", "I'll Give You Everything", "Growing Pains"),
        ("Swings", "Sleep Well", "Growing Pains"),
        ("Swings", "Upgrade II", "Growing Pains"),
        ("Swings", "Tomorrow", "Growing Pains"),
    ],
    2015: [
        ("San E", "Show Me the Money", "Show Me the Money 4"),
    ],
    2018: [
        ("E Sens", "Mona Lisa", "Mona Lisa"),
        ("Penomeco", "Work", "Work"),
        ("GroovyRoom", "Champion", "Champion"),
        ("DPR LIVE", "Jasmine", "Jasmine"),
        ("DPR LIVE", "Martini Blue", "Martini Blue"),
        ("Zion.T", "MMM", "Repetition"),
        ("Beenzino", "January", ""),
        ("MoonMoon", "Tourist", "Tourist"),
        ("BIG Naughty", "Singapore", "Singapore"),
        ("Bobby", "U MAD", "THE MADMAN"),
        ("Thama", "In My Room", "In My Room"),
        ("Primary", "When Where What How Why", "Planetarium"),
        ("Gray", "Remedy", "Gray Season 2.5"),
        ("Dean", "I Think U", ""),
        ("Hanhae", "Domesticated Mode", "135"),
        ("Penomeco", "Shy", "Work"),
        ("GroovyRoom", "Wavy", "Champion"),
        ("Bobby", "Falling In Love", "THE MADMAN"),
        ("Ash Island", "Limousine Vision", "Ash Island"),
        ("TOIL", "Rollin", "1989"),
        ("Woodie Gochild", "Dirtbag", "#GOchild"),
    ],
    2019: [
        ("Zion.T", "No Make Up (feat. Wonstein)", "No Make Up"),
        ("DPR LIVE", "Coming To You Live", "Coming to You Live"),
        ("GroovyRoom", "Thinkin About You", "Thinkin About You"),
        ("GroovyRoom", "Sunny", "Thinkin About You"),
        ("Flowsik", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
        ("BIG Naughty", "Relationship", "Relationship"),
        ("Rohann", "Problem", "Problem"),
        ("Thama", "Long Time No See", "Long Time No See"),
        ("Jvcki Wai", "Mood", "Exposure"),
        ("Woo Won Jae", "We Are", "We Are"),
    ],
    2020: [
        ("Rad Museum", "Life", "Life"),
        ("Woo Won Jae", "Hourglass", "Hourglass"),
        ("Sumin", "Mirrorball", "Mirrorball"),
        ("Trade L", "Rush", "Rush"),
        ("Blued", "Blue", "Blue"),
        ("Queenpia", "Queenpia", "Queenpia"),
        ("Paul Blanco", "Summer", "Summer"),
        ("B.I", "One and Only", ""),
    ],
    2021: [
        ("PLT", "Summer", "Summer"),
        ("Rad Museum", "Girls", "Life"),
        ("Sumin", "Mirrorball", "Mirrorball"),
        ("Trade L", "Rush", "Rush"),
        ("Blued", "Blue", "Blue"),
    ],
    2022: [
        ("The Quiett", "Luxury Flow", "Luxury Flow"),
        ("Changmo", "ANTHEM", "Op.1"),
        ("BRADYSTREET", "Heavy", ""),
        ("Gist", "Engagement", ""),
        ("Blued", "Melody", "Melody"),
        ("Sokodomo", "Winner", "Show Me the Money 10"),
        ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
        ("Lee Young Ji", "Yumeyo", "16"),
        ("Jessi", "Who Dat B", "Who Dat B"),
        ("Tablo", "Fantasy", "Drill Presents: Tablo x Fantasy"),
        ("Nafla", "Swervin", "C.R.E.A.M"),
        ("Kid Milli", "Simple Poem", "BEIGE"),
        ("Huckleberry P", "우퍼", "Mantra 3"),
        ("Koonta", "Grandma", "Show Me the Money 8"),
    ],
    2023: [
        ("CAMO", "Melody", "Melody"),
        ("Lee Young Ji", "Not Sure", "16"),
        ("Jessi", "Cold Blooded", "Cold Blooded"),
        ("Mudd the student", "Sleepy Beauty", ""),
        ("Olltii", "Turtle Ship Remix", ""),
    ],
    2024: [
        ("Beenzino", "Train", ""),
        ("Jay Park", "Need To Know", "THE ONE YOU WANTED"),
    ],
    2025: [
        ("BlackNut", "0", ""),
        ("Bassagong", "Comfort", ""),
        ("Bassagong", "Rock N Roll Baby (Feat. G2 & CHANGMO)", ""),
        ("YANGHONGWON", "LEAN", ""),
        ("Nosun", "Exit Wounds", "Exit Wounds"),
        ("B-Free", "Free The Mane 3", "Free The Mane 3"),
        ("Wuuslime", "Wuuslime", ""),
        ("Marv", "Marv", ""),
        ("Nieah", "Nieah", ""),
        ("GV", "GV", "YAHO"),
        ("Jeremy Que$t", "Jeremy Que$t", "YAHO"),
        ("MILLHAM", "MILLHAM", "YAHO"),
        ("GGM Kimbo", "GGM Kimbo", "We Got What You Need"),
        ("Kimeen", "Kimeen", ""),
        ("xorf1nn", "xorf1nn", ""),
        ("lahaine", "lahaine", ""),
        ("Pank", "Pank", ""),
        ("Royal 44", "EVOL", "EVOL"),
        ("Yung Blesh", "M.D.M.A 2", ""),
        ("Owen Ovadoz", "TANG", "POEMV"),
        ("Owen Ovadoz", "TREND", "POEMV"),
        ("EK", "YAHO", "YAHO"),
        ("EK", "FLY", "YAHO"),
        ("Don Malik", "Spinboutu", "Love is a Song"),
        ("DeVita", "Spinboutu", "Love is a Song"),
        ("Royal 44", "Classical Freestyle", "We Got What You Need"),
        ("Yung Blesh", "Classical Freestyle", "We Got What You Need"),
        ("Owen Ovadoz", "SUCCEEDING", "POEMV"),
        ("EK", "Supernova", "YAHO"),
        ("Don Malik", "oh wow", "Love is a Song"),
        ("DeVita", "oh wow", "Love is a Song"),
        ("Royal 44", "2025 (U Got It)", "We Got What You Need"),
        ("Owen Ovadoz", "TRUTH (feat. Marv, Nieah)", "POEMV"),
        ("EK", "Machine", "YAHO"),
        ("Don Malik", "White T", "Love is a Song"),
        ("Royal 44", "Dolce & Gabbana", "We Got What You Need"),
        ("Owen Ovadoz", "5AM IN SYDNEY", "POEMV"),
        ("EK", "Same (feat. YUMDDA)", "YAHO"),
        ("Don Malik", "chuum", "Love is a Song"),
        ("Royal 44", "City Girls", "We Got What You Need"),
        ("Owen Ovadoz", "BE MY LOVE (feat. Seo Ja Yeong)", "POEMV"),
        ("EK", "AFTER PARTY", "YAHO"),
        ("Don Malik", "DAP", "Love is a Song"),
        ("Royal 44", "Sexy Club", "We Got What You Need"),
        ("Owen Ovadoz", "TUNED IN", "POEMV"),
        ("EK", "BE GOOD", "YAHO"),
        ("Don Malik", "How To Make Love Song", "Love is a Song"),
        ("Royal 44", "Beautiful Life", "We Got What You Need"),
        ("Owen Ovadoz", "ALL ALIKE", "POEMV"),
        ("EK", "MR.P", "YAHO"),
        ("Don Malik", "name cost", "Love is a Song"),
        ("Royal 44", "Supertrap (feat. Wuuslime)", "We Got What You Need"),
        ("Owen Ovadoz", "TILL I DIE (feat. EK)", "POEMV"),
        ("EK", "Coming Sunny Days", "YAHO"),
        ("Don Malik", "Savio, Draco", "Love is a Song"),
        ("Royal 44", "Racks (feat. ShyboiiTobii, GGM Kimbo)", "We Got What You Need"),
        ("Owen Ovadoz", "ALL IS FINE", "POEMV"),
        ("EK", "Religion True (feat. MILLHAM)", "YAHO"),
        ("Don Malik", "Pornography", "Love is a Song"),
        ("Royal 44", "Party Shit (feat. Wuuslime, JMIN)", "We Got What You Need"),
        ("Owen Ovadoz", "BONAFIED", "POEMV"),
        ("Don Malik", "Ew", "Love is a Song"),
        ("Owen Ovadoz", "TWELVE (feat. Wuuslime)", "POEMV"),
        ("Don Malik", "Winter is Coming", "Love is a Song"),
        ("Owen Ovadoz", "TEARS", "POEMV"),
        ("Owen Ovadoz", "ANGEL", "POEMV"),
        ("Owen Ovadoz", "TANTRUM (feat. The Quiett)", "POEMV"),
        ("Owen Ovadoz", "INTENTIONS", "POEMV"),
        ("Owen Ovadoz", "MUST BE KIDDING (feat. Paloalto)", "POEMV"),
        ("Owen Ovadoz", "FOREVER YOUNG (feat. foggyatthebottom)", "POEMV"),
        ("foggyatthebottom", "FOREVER YOUNG", "POEMV"),
        ("ShyboiiTobii", "ShyboiiTobii", "We Got What You Need"),
        ("JMIN", "JMIN", "We Got What You Need"),
        ("Penomeco", "When I Siege", ""),
        ("Hoody", "Us", ""),
        ("Seo Ja Yeong", "BE MY LOVE", "POEMV"),
        ("CHIO CHICANO", "Big Squad", ""),
        ("Panda Gomm", "Home Vacation", "Home Vacation"),
        ("Junoflo", "Love Like This", ""),
        ("DPR ARTIC", "KINEMA", "KINEMA"),
        ("CK", "Verses", "Verses"),
        ("lil9ap", "Drama/R&B", "Drama/R&B"),
        ("basecamp", "camp", ""),
        ("noisemasterminsu", "I KNOW YOU LOVE ME", ""),
        ("Moon Sujin", "Better", "Better"),
        ("AP Alchemy", "Monthly AP – January, 2024", "Monthly AP – January, 2024"),
        ("Leebido", "A prescription for 2", "A prescription for 2"),
        ("GwangilJo", "Light Adaptation", "Light Adaptation"),
        ("Garion", "Garion 3", "Garion 3"),
        ("QM", "개미", "개미"),
        ("Paloalto", "Lovers Turn to Haters", "Lovers Turn to Haters"),
        ("Dbo", "Be Back Soon", "Be Back Soon"),
        ("Homies", "Yains", "Yains"),
        ("Los", "Skandalouz 2", "Skandalouz 2"),
        ("Skinny Chase", "Journey to the West", "Journey to the West"),
        ("Fredi Casso", "Death Therapy", "Death Therapy"),
        ("Ambid Jack", "Death Therapy", "Death Therapy"),
        ("Ja Mezz", "Only", "Only"),
        ("Bangroz", "Only", "Only"),
        ("Hyeminsong", "Reborn", "Reborn"),
        ("Untell", "Animal", "Animal"),
        ("Dabin", "Giggles", "Giggles"),
        ("Tiger JK", "T.K.D", "T.K.D"),
        ("YUGYEOM", "LA SOL MI", ""),
        ("Ash-B", "Wish", ""),
        ("XWALLY", "BORN2RAVE", "BORN2RAVE"),
        ("1300", "Ape Sh*t", ""),
        ("BIGONE", "COLORFUL ZEBRA", ""),
        ("BOYCOLD", "Sick of Love", "Sick of Love"),
        ("Crucial Star", "Nihilism Watch", ""),
        ("ChaMane", "BATON PASS", "BATON PASS"),
        ("Chillin Homie", "Maze Runner", "Maze Runner"),
        ("Knoxx", "Knoxx", ""),
        ("Polodared", "Multiverse", ""),
        ("Hej!", "Drive", ""),
        ("Futuristic Swaver", "Villain", ""),
        ("Hodaky", "Yellow", ""),
        ("Bluso", "Fade Away", ""),
        ("LeyonC", "Fall", ""),
        ("Hyunsang", "Take Care", ""),
        ("Woo", "Rain Drop", "Rain Drop"),
        ("Rohann", "Sunday", ""),
        ("Thama", "Long Time No See", "Long Time No See"),
        ("Queenpia", "Queenpia", "Queenpia"),
        ("Sumin", "Mirrorball", "Mirrorball"),
        ("MoonMoon", "Tourist", "Tourist"),
        ("E Sens", "Mona Lisa", "Mona Lisa"),
        ("DPR LIVE", "Jasmine", "Jasmine"),
        ("Woo Won Jae", "Hourglass", "Hourglass"),
        ("Rad Museum", "Life", "Life"),
        ("CAMO", "Melody", "Melody"),
        ("Mudd the student", "Sleepy Beauty", ""),
        ("Olltii", "Turtle Ship Remix", ""),
        ("Jessi", "Cold Blooded", "Cold Blooded"),
        ("Lee Young Ji", "O.K?", "O.K?"),
        # 2025 신규 아티스트·미사용 트랙 (global 2010-2024 미포함)
        ("Mushvenom", "돌림판 (Feat. 신빠람 이박사)", "얼"),
        ("Mushvenom", "몰러유", "얼"),
        ("Penomeco", "EGGE (Feat. YDG)", "RNSSNC TAPE"),
        ("Penomeco", "BOLO (Feat. YDG)", "RNSSNC TAPE"),
        ("Kmjae", "비폴라", "비폴라"),
        ("Hebi", "시바세키", "Odyssey"),
        ("BeeFree", "Odyssey", "Odyssey"),
        ("SINCE", "New New New", ""),
        ("SINCE", "Wavy", ""),
        ("Liloyoung", "Liloyoung", ""),
        ("RPT Kaigo", "Kaigo", ""),
        ("YUNGIN", "YUNGIN", ""),
        ("O'koye", "Hallelujah", "Whether the Weather Changes or Not"),
        ("Minit", "He♡rt", "He♡rt"),
        ("Okashii", "Orton", "Orton"),
        ("Ted Park", "Home Alone 2.0", "Home Alone 2.0"),
        ("EK", "Escape", "Escape"),
        ("Bryn", "Supercharged", "Supercharged"),
        ("Balming Tiger", "Greatest Hits", "Greatest Hits"),
        ("RM", "Right Place, Wrong Person", "Right Place, Wrong Person"),
        ("Gray", "Real Love", "Remedy"),
        ("Giriboy", "Mechanical Album", "Mechanical Album"),
        ("Loopy", "CROWN", "SEOUL pt.A"),
        ("Loopy", "MARNI", "MARNI"),
        ("Owen Ovadoz", "P.O.E.M.", "P.O.E.M."),
        ("The Quiett", "Crystal Crates", "Luxury Flow"),
        ("Leellamarz", "Hell yea", "L&B"),
        ("Leellamarz", "GONE", ""),
        ("Qwala", "DISTORTED", "DISTORTED"),
        ("Epik High", "Frost", "Strawberry"),
        ("Epik High", "Pump", "Pump"),
        ("BIG Naughty", "+", "+"),
        ("Kid Milli", "+", "+"),
        ("Haon", "Haonoah", "Haonoah"),
        ("Flowsik", "Worlds Apart", "Worlds Apart"),
        ("Khundi Panda", "MODM 2 : The Bento Knight", "MODM 2 : The Bento Knight"),
        ("HD BL4CK", "Vantablack Dreams", "Vantablack Dreams"),
        ("viceversa", "I'M UP", ""),
        ("ShyboiiTobii", "Breaking Bad", ""),
        ("KAMBO", "Dreamatic", "Dreamatic"),
        ("Blase", "KKUCKDARI", "SELF MADE"),
        ("BE'O", "Healing", "Show Me the Money 10"),
        ("Sik-K", "KC (BUST IT DOWN)", ""),
        ("Mushvenom", "오랫동안 (Feat. 거북이)", "얼"),
        ("Mushvenom", "오토매틱 (Feat. 코요태)", "얼"),
        ("Kmjae", "Polar", "비폴라"),
        ("Hebi", "Hebi", ""),
        ("Mushvenom", "날다람쥐", "얼"),
        ("Verbal Jint", "Replay (Feat. Heize)", ""),
    ],
}
