# Year-specific spare tracks for dedupe fill (artist, title, album)
# Only used when primary catalog loses entries to cross-year duplicates.

SPARE: dict[int, list[tuple[str, str, str]]] = {
    2013: [
        ("Swings", "Growing Pains", "Growing Pains"),
    ],
    2017: [
        ("Penomeco", "Garden", ""),
        ("Jessi", "NUNU NANA", "NUNU NANA"),
    ],
    2014: [
        ("Gaeko", "Geon Gangs", "Geon Gangs"),
        ("Giriboy", "Square", "Square"),
        ("Swings", "A Good Day", "Growing Pains"),
        ("Swings", "A Real Lady", "Growing Pains"),
        ("Swings", "Obvious Fake", "Growing Pains"),
        ("Swings", "Drowning Man", "Growing Pains"),
        ("Swings", "The King", "Growing Pains"),
        ("Swings", "The Origin of Swings", "Growing Pains"),
        ("Swings", "Growing Pains", "Growing Pains"),
        ("Swings", "Remember We", "Growing Pains"),
        ("Swings", "Silence", "Growing Pains"),
        ("Swings", "Heavy Smoker", "Growing Pains"),
        ("Swings", "Witch Hunt", "Growing Pains"),
        ("Swings", "Bulldozer", "Growing Pains"),
        ("Swings", "I'll Give You Everything", "Growing Pains"),
        ("Swings", "Sleep Well", "Growing Pains"),
        ("Swings", "Upgrade II", "Growing Pains"),
        ("Swings", "Tomorrow", "Growing Pains"),
    ],
    2015: [
        ("San E", "Show Me the Money", "Show Me the Money 4"),
    ],
    2018: [
        ("Zico", "Any Song", ""),
        ("Zico", "SoulMate", ""),
        ("Beenzino", "Damnato", "Damnato"),
        ("Beenzino", "We Are Going", "Damnato"),
        ("Crush", "WooAh", "From Midnight to Sunrise"),
        ("Crush", "Fallin'", "From Midnight to Sunrise"),
        ("Crush", "From Midnight to Sunrise", "From Midnight to Sunrise"),
        ("Crush", "Mayday", "From Midnight to Sunrise"),
        ("Crush", "Wake Up", "From Midnight to Sunrise"),
        ("Coogie", "Coogie", "Coogie"),
        ("Coogie", "Bouncin'", "Coogie"),
        ("Coogie", "Wifey", "Emo #1"),
        ("Coogie", "GPS", "Emo #1"),
        ("Coogie", "Glow", ""),
        ("Coogie", "I'mma Do", ""),
        ("HAON", "Travel", ""),
        ("HAON", "Blue", ""),
        ("HAON", "Blossom", ""),
        ("Ash Island", "Malibu", ""),
        ("Ash Island", "Limousine Vision", ""),
        ("Ash Island", "Howling", ""),
        ("Ash Island", "Nightmare", ""),
        ("Kid Milli", "Cappuccino", ""),
        ("Kid Milli", "Yellow", "Maiden Voyage"),
        ("Kid Milli", "Maiden Voyage", "Maiden Voyage"),
        ("Loco", "Hero", "Hero"),
        ("Loco", "Some", "Hero"),
        ("Loco", "Oceans", "Hero"),
        ("Loco", "Waiting For Love", "Hero"),
        ("Changmo", "Boyhood", "Boyhood"),
        ("Changmo", "Ring Ding", "Boyhood"),
        ("PH-1", "YIN YANG", "YIN YANG"),
        ("PH-1", "Homebody", "YIN YANG"),
        ("Giriboy", "914", "914"),
        ("Leellamarz", "To Be Continued", "To Be Continued"),
        ("Leellamarz", "Don`t Call Me", "To Be Continued"),
        ("Leellamarz", "Profile", "To Be Continued"),
        ("TOIL", "1989", "1989"),
        ("TOIL", "Money", "1989"),
        ("TOIL", "Rollin", "1989"),
        ("Blase", "Passionfruit", ""),
        ("Blase", "Blue", ""),
        ("Mino", "Trigger", "XX"),
        ("Mino", "Fiancé", "XX"),
        ("Mino", "XX", "XX"),
        ("Mino", "Uh Ahchoo", "XX"),
        ("Jay Park", "Nothing Wrong", ""),
        ("Jay Park", "All The Way Up", ""),
        ("Jay Park", "V", "The Season: The Blue Bird"),
        ("Dean", "Pompeii", ""),
        ("Dean", "I'm Not Sorry", ""),
        ("Heize", "HAPPEN", "HAPPEN"),
        ("Heize", "Undo", "HAPPEN"),
        ("Heize", "Can You See My Heart", "HAPPEN"),
        ("Gray", "Tik Tak Tok", ""),
        ("Gray", "Late Night", "Gray Season 2.5"),
        ("Tablo", "Fantasy", "Drill Presents: Tablo x Fantasy"),
        ("Tablo", "Drill Presents", "Drill Presents: Tablo x Fantasy"),
        ("Paloalto", "Shangri-La", "Shangri-La"),
        ("Woodie Gochild", "Mood Swings", "#GOchild"),
        ("Woodie Gochild", "Dirtbag", "#GOchild"),
        ("YUMDDA", "I'm Good", ""),
        ("Mirani", "Pepsi", ""),
        ("Nafla", "Natural Born Killers", "Natural Born Killers"),
        ("Nafla", "What", "Natural Born Killers"),
        ("Nafla", "You Gon' Need It", "Natural Born Killers"),
        ("Nafla", "Bandage on My Shoulder", "Natural Born Killers"),
        ("Sik-K", "TRAP", "TRAP"),
        ("Sik-K", "Romeo & Juliet", "TRAP"),
        ("BewhY", "Forever", "The Movie Star"),
        ("BewhY", "Day Day", "The Movie Star"),
        ("Jvcki Wai", "Doughnet", "Exposure"),
        ("Jvcki Wai", "Neo Eve", "Exposure"),
    ],
    2019: [
        ("Epik High", "Rosario", "Sleepless in __________"),
        ("Epik High", "Sleeping Beauty", "Sleepless in __________"),
        ("Epik High", "Eternal Sunshine", "Sleepless in __________"),
        ("Epik High", "Timeless", "Sleepless in __________"),
        ("Epik High", "No Different", "Sleepless in __________"),
        ("Epik High", "Loved", "Sleepless in __________"),
        ("Epik High", "Leica", "Sleepless in __________"),
        ("Epik High", "On Bended Knee", "Sleepless in __________"),
        ("Epik High", "Daylight", "Sleepless in __________"),
        ("Epik High", "Another Winter", "Sleepless in __________"),
        ("Epik High", "Lost One", "Sleepless in __________"),
        ("Epik High", "In Seoul", "Sleepless in __________"),
        ("Epik High", "Sleepless in __________", "Sleepless in __________"),
        ("Epik High", "Tik Tik Tik", "Sleepless in __________"),
        ("Epik High", "Rich", "Sleepless in __________"),
        ("Epik High", "Indigo", "Sleepless in __________"),
        ("Epik High", "Gray", "Sleepless in __________"),
        ("Epik High", "Fry Me", "Sleepless in __________"),
        ("Epik High", "Crescendo", "Sleepless in __________"),
        ("Epik High", "Kill Me", "Sleepless in __________"),
        ("Epik High", "Love Story", "Sleepless in __________"),
        ("Coogie", "Alone", ""),
    ],
    2021: [
        ("Changmo", "MORAESIGYE", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "TAIJI", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Rockstar Lifestyle", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Beretta", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Chronic Love", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Vivienne", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Little Brothers", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Hyperstar", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Hotel Room", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "No Regret", "UNDERGROUND ROCKSTAR"),
        ("Changmo", "Supernova", "UNDERGROUND ROCKSTAR"),
        ("Kid Milli", "Cliché", "Cliché"),
        ("Coogie", "I Got A Feeling", "I Got A Feeling"),
        ("Beenzino", "Reset", "Nowitzki"),
        ("Beenzino", "Nowitzki", "Nowitzki"),
        ("Epik High", "Breathe", "Epilogue Pt.2"),
        ("Epik High", "Sleep Tight", "Epilogue Pt.2"),
        ("Epik High", "You Are The One For Me", "Epilogue Pt.2"),
    ],
    2022: [
        ("Coogie", "Good Night", "Re:Up"),
        ("Changmo", "METAVERS", "Band Up"),
        ("Changmo", "Band Up", "Band Up"),
        ("Kid Milli", "Benzo", ""),
        ("Leellamarz", "Don`t Say That", "Don`t Say That"),
        ("TOIL", "MAZE", "MAZE"),
        ("Beenzino", "Fashion Hoarder", "Modiversity"),
        ("Beenzino", "Modiversity", "Modiversity"),
        ("Beenzino", "Dumbo", "Dumbo"),
        ("Loco", "Focus", ""),
        ("Giriboy", "Vice Versa", "Vice Versa"),
        ("Swings", "Per se", "Per se"),
        ("Loco", "WIN", ""),
        ("Ash Island", "Safety Zone", "Safety Zone"),
        ("Mirani", "Drama", "Drama"),
        ("Dynamic Duo", "ECO", "ECO"),
        ("Kid Milli", "Summer", ""),
        ("Kid Milli", "Lightly", ""),
        ("Changmo", "Just the Two of Us", ""),
        ("Changmo", "SMF", ""),
        ("Jay Park", "McNasty", ""),
        ("Jay Park", "B Day", ""),
        ("Loco", "Wedding", ""),
        ("Loco", "Aniya", ""),
        ("Zion.T", "Lonely Christmas", ""),
        ("Punchnello", "Loveseat", ""),
        ("Punchnello", "Cream Cheese", ""),
        ("Blase", "Quote That", ""),
        ("The Quiett", "Nike", ""),
        ("Paloalto", "Valentina", ""),
        ("TOIL", "like when we first met", ""),
        ("The Quiett", "Bentley", ""),
        ("Beenzino", "Monet", ""),
        ("Zico", "Grown Ass Kid", "Grown Ass Kid"),
        ("Zico", "Seoul Drift", "Grown Ass Kid"),
        ("Zico", "Being Human", "Grown Ass Kid"),
        ("Zico", "Curriculum", "Grown Ass Kid"),
        ("Zico", "OMJT", "Grown Ass Kid"),
        ("Zico", "Trash Talk", "Grown Ass Kid"),
        ("Zico", "That Guy", "Grown Ass Kid"),
        ("Lil Moshpit", "Moshpit Only", "AAA"),
        ("Lil Moshpit", "Gotta Lotta Shit", "AAA"),
        ("Lil Moshpit", "Yooooo", "AAA"),
        ("Lil Moshpit", "A-Team Freestyle", "AAA"),
        ("Lil Moshpit", "Slatty Slut", "AAA"),
        ("Lil Moshpit", "ON THE BLOCK", "AAA"),
        ("Lil Moshpit", "DIE HARD", "AAA"),
        ("Lil Moshpit", "BO$$", "AAA"),
        ("Lil Moshpit", "Back In My AREA", "AAA"),
        ("Leellamarz", "STORY", "Toystory3"),
        ("Leellamarz", "Last Chance", "Toystory3"),
        ("Leellamarz", "Don`t do That", "Toystory3"),
        ("Leellamarz", "Seperation Anxiety", "Toystory3"),
        ("Leellamarz", "Never Ending Story", "Toystory3"),
        ("Leellamarz", "Aftermath", "Toystory3"),
        ("Leellamarz", "B.B.B", "Toystory3"),
        ("Leellamarz", "Flower Age", "Toystory3"),
        ("Leellamarz", "1,2,3", "Toystory3"),
        ("Leellamarz", "2AM", "Toystory3"),
        ("Leellamarz", "Zero Coke", "Toystory3"),
        ("Leellamarz", "Iris", "Toystory3"),
        ("Leellamarz", "Number", "MaRz&B"),
        ("Leellamarz", "Uncomfortable", "MaRz&B"),
        ("Leellamarz", "Ex", "MaRz&B"),
        ("Leellamarz", "Chrome Hearts", "MaRz&B"),
        ("Leellamarz", "Down", "MaRz&B"),
        ("Leellamarz", "Muse", "MaRz&B"),
        ("Leellamarz", "Meet me at the London", "MaRz&B"),
        ("Leellamarz", "CTRL+Z", "VIOLINIST2"),
        ("Leellamarz", "OUT OF MY SIGHT", "VIOLINIST2"),
        ("Leellamarz", "Left hand to Right hand", "VIOLINIST2"),
        ("Leellamarz", "a single word", "VIOLINIST2"),
        ("Leellamarz", "This is not what I want", "VIOLINIST2"),
        ("Leellamarz", "Selfish", "VIOLINIST2"),
        ("Leellamarz", "Sisi La Famille", "VIOLINIST2"),
        ("Leellamarz", "30 minutes", "VIOLINIST2"),
        ("Epik High", "Here", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Prequel", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Super Rare", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Gray So Gray", "Epik High Is Here 下, Part 2"),
        ("Epik High", "BRB", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Rain Song", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Rich Kids Anthem", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Face ID", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Family Portrait", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Champagne", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Piano for Sale", "Epik High Is Here 下, Part 2"),
        ("PH-1", "BUT FOR NOW LEAVE ME ALONE", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Zombies", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "TGIF", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Yuppie Ting", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Tipsy", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Mr. Bad", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Juliette!", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Run Away", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Dead Girl", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Shrink Told Me", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Issues", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Break the Glass", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Final Bout", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Bve", "BUT FOR NOW LEAVE ME ALONE"),
    ],
    2023: [
        ("PH-1", "Rosario", "But For Now Leave Me Alone 2"),
        ("BIG Naughty", "Você", "Você"),
        ("Zion.T", "No Make Up", "Zip"),
        ("Crush", "Rush Hour", "Rush Hour"),
        ("Giriboy", "Girlfriend", ""),
        ("Ash Island", "Melody", "Melody"),
        ("Blase", "City Life", ""),
        ("Mirani", "Baby", ""),
        ("Woodie Gochild", "Mood", ""),
        ("Owen Ovadoz", "Drama", ""),
    ],
    2024: [
        ("Beenzino", "Train", ""),
        ("Jay Park", "Need To Know", "THE ONE YOU WANTED"),
    ],
}
