#!/usr/bin/env python3
"""Write y2022-y2025 real catalog modules (100 tracks each)."""
from __future__ import annotations
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(__file__), "real_catalog_data")

CATALOG: dict[int, list[tuple[str, str, str]]] = {
    2022: [
        ("Beenzino", "Monet", ""),
        ("Zico", "New Thing", ""),
        ("Zico", "Grown Ass Kid", "Grown Ass Kid"),
        ("Zico", "Seoul Drift", "Grown Ass Kid"),
        ("Zico", "Being Human", "Grown Ass Kid"),
        ("Zico", "Curriculum", "Grown Ass Kid"),
        ("Zico", "OMJT", "Grown Ass Kid"),
        ("Zico", "Trash Talk", "Grown Ass Kid"),
        ("Zico", "That Guy", "Grown Ass Kid"),
        ("Changmo", "Just the Two of Us", ""),
        ("Changmo", "SMF", ""),
        ("Kid Milli", "Summer", ""),
        ("Kid Milli", "Lightly", ""),
        ("Coogie", "Alone", ""),
        ("Coogie", "Good Night", ""),
        ("PH-1", "Zombies", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "TGIF", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Yuppie Ting", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Tipsy", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Mr. Bad", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Juliette!", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Run Away", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Dead Girl", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Shrink Told Me", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Issues", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Break the Glass", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Final Bout", "BUT FOR NOW LEAVE ME ALONE"),
        ("PH-1", "Bve", "BUT FOR NOW LEAVE ME ALONE"),
        ("Crush", "Rush Hour", ""),
        ("Crush", "Oasis", ""),
        ("Epik High", "Here", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Prequel", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Super Rare", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Gray So Gray", "Epik High Is Here 下, Part 2"),
        ("Epik High", "BRB", "Epik High Is Here 下, Part 2"),
        ("Epik High", "I Hated Myself (Tablo's Word)", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Rain Song", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Rich Kids Anthem", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Face ID", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Family Portrait", "Epik High Is Here 下, Part 2"),
        ("Epik High", "Champagne", "Epik High Is Here 下, Part 2"),
        ("Jay Park", "McNasty", ""),
        ("Jay Park", "Yesterday", ""),
        ("Jay Park", "B Day", ""),
        ("Dean", "4:44", ""),
        ("Heize", "Undo", ""),
        ("Loco", "Wedding", ""),
        ("Loco", "Aniya", ""),
        ("Gray", "Remedy", ""),
        ("Zion.T", "Lonely Christmas", ""),
        ("Colde", "Star", ""),
        ("Colde", "honestly", ""),
        ("Punchnello", "Loveseat", ""),
        ("Punchnello", "Cream Cheese", ""),
        ("Blase", "Quote That", ""),
        ("Leellamarz", "STORY", "Toystory3"),
        ("Leellamarz", "Last Chance", "Toystory3"),
        ("Leellamarz", "Don't do That", "Toystory3"),
        ("Leellamarz", "Seperation Anxiety", "Toystory3"),
        ("Leellamarz", "Never Ending Story", "Toystory3"),
        ("Leellamarz", "Aftermath", "Toystory3"),
        ("Leellamarz", "B.B.B", "Toystory3"),
        ("Leellamarz", "Flower Age", "Toystory3"),
        ("Leellamarz", "1,2,3", "Toystory3"),
        ("Leellamarz", "2AM", "Toystory3"),
        ("Leellamarz", "Zero Coke", "Toystory3"),
        ("Leellamarz", "Iris", "Toystory3"),
        ("Leellamarz", "Number", "MaRz&B"),
        ("Leellamarz", "Uncomfortable", "MaRz&B"),
        ("Leellamarz", "Ex", "MaRz&B"),
        ("Leellamarz", "Chrome Hearts", "MaRz&B"),
        ("Leellamarz", "Down", "MaRz&B"),
        ("Leellamarz", "Muse", "MaRz&B"),
        ("Leellamarz", "Meet me at the London", "MaRz&B"),
        ("Leellamarz", "CTRL+Z", "VIOLINIST2"),
        ("Leellamarz", "OUT OF MY SIGHT", "VIOLINIST2"),
        ("Leellamarz", "Left hand to Right hand", "VIOLINIST2"),
        ("Leellamarz", "a single word", "VIOLINIST2"),
        ("Leellamarz", "This is not what I want", "VIOLINIST2"),
        ("Leellamarz", "Selfish", "VIOLINIST2"),
        ("Leellamarz", "Sisi La Famille", "VIOLINIST2"),
        ("Leellamarz", "30 minutes", "VIOLINIST2"),
        ("Leellamarz", "Without You (Encore)", "VIOLINIST2"),
        ("Lil Moshpit", "Moshpit Only", "AAA"),
        ("Lil Moshpit", "Gotta Lotta Shit", "AAA"),
        ("Lil Moshpit", "Yooooo", "AAA"),
        ("Lil Moshpit", "A-Team Freestyle", "AAA"),
        ("Lil Moshpit", "Slatty Slut", "AAA"),
        ("Lil Moshpit", "ON THE BLOCK", "AAA"),
        ("Lil Moshpit", "DIE HARD", "AAA"),
        ("Lil Moshpit", "BO$$", "AAA"),
        ("Lil Moshpit", "Back In My AREA", "AAA"),
        ("The Quiett", "Nike", ""),
        ("Paloalto", "Valentina", ""),
        ("Paloalto", "Top Primary", ""),
        ("TOIL", "like when we first met", ""),
        ("Gray", "Summer Night", ""),
        ("Epik High", "Piano for Sale", "Epik High Is Here 下, Part 2"),
        ("Tablo", "I Hated Myself (Tablo's Word)", "Epik High Is Here 下, Part 2"),
        ("The Quiett", "Bentley", ""),
    ],
    2023: [
        ("Beenzino", "Trippy", ""),
        ("Beenzino", "In Bed/Makgulli", "NOWITZKI"),
        ("Beenzino", "Travel Again", "NOWITZKI"),
        ("Beenzino", "Coca Cola Red", "NOWITZKI"),
        ("Beenzino", "990", "NOWITZKI"),
        ("Beenzino", "Lemon", "NOWITZKI"),
        ("Beenzino", "Like A Fool", "NOWITZKI"),
        ("Beenzino", "Crime", "NOWITZKI"),
        ("Beenzino", "Camp", "NOWITZKI"),
        ("Beenzino", "Change", "NOWITZKI"),
        ("Beenzino", "Just One Day", "NOWITZKI"),
        ("Beenzino", "Sandman", "NOWITZKI"),
        ("Beenzino", "Radio", "NOWITZKI"),
        ("Beenzino", "Gym", "NOWITZKI"),
        ("Jay Park", "Why", ""),
        ("Jay Park", "Candy", ""),
        ("Jay Park", "Sunday Night Drive", ""),
        ("Loco", "VOLVO", ""),
        ("Loco", "INEEDYOURLOVE", ""),
        ("Loco", "Pick Pick", "WEAK"),
        ("Loco", "BROKEN IPHONE", "WEAK"),
        ("Loco", "NOT OK", "WEAK"),
        ("Loco", "Window Overlooking the Sea", "WEAK"),
        ("Loco", "HEEE !", "WEAK"),
        ("Loco", "Just like this", "WEAK"),
        ("Loco", "4 U", "WEAK"),
        ("Loco", "Bonus", "WEAK"),
        ("Epik High", "Strawberry", "Strawberry"),
        ("Epik High", "On My Way", "Strawberry"),
        ("Epik High", "Catch", "Strawberry"),
        ("Epik High", "Down Bad Freestyle", "Strawberry"),
        ("Epik High", "God's Latte", "Strawberry"),
        ("Crush", "Hmm-cheat", "wonderego"),
        ("Crush", "EZPZ", "wonderego"),
        ("Crush", "Ego", "wonderego"),
        ("Crush", "A Man Like Me", "wonderego"),
        ("Crush", "New Day", "wonderego"),
        ("Crush", "No Break", "wonderego"),
        ("Crush", "Me Myself & I", "wonderego"),
        ("Crush", "Satisfied", "wonderego"),
        ("Crush", "Nothing Else", "wonderego"),
        ("Kid Milli", "BEIGE theme", "BEIGE"),
        ("Kid Milli", "HONDA!", "BEIGE"),
        ("Kid Milli", "Simple Poem", "BEIGE"),
        ("Kid Milli", "Still friend?", "BEIGE"),
        ("Kid Milli", "R.I.P", "BEIGE"),
        ("Kid Milli", "Test me?", "BEIGE"),
        ("Kid Milli", "BNC", "BEIGE"),
        ("Kid Milli", "Coupe!", "BEIGE"),
        ("Kid Milli", "Lost and found freestyle", "BEIGE"),
        ("Kid Milli", "Let Me Down!", "BEIGE"),
        ("Kid Milli", "25", "BEIGE"),
        ("Kid Milli", "BORA", "BEIGE"),
        ("Coogie", "Buck", "DIFF"),
        ("Coogie", "Just For Fun", "DIFF"),
        ("Coogie", "I Go", "DIFF"),
        ("Coogie", "D.O.D", "DIFF"),
        ("Coogie", "LOCO", "DIFF"),
        ("Coogie", "Hold It Down", "DIFF"),
        ("Dean", "Die 4 You", ""),
        ("Heize", "Perhaps Happy Ending", "Last Winter"),
        ("Heize", "Lips", "Last Winter"),
        ("Heize", "From Autumn to Winter", "Last Winter"),
        ("Heize", "Forgotten Love", "Last Winter"),
        ("Heize", "Dance with Me", "Last Winter"),
        ("Heize", "Midnight", "Last Winter"),
        ("Heize", "Connection", "Last Winter"),
        ("Heize", "Love goes around comes around", "Last Winter"),
        ("Zion.T", "UNLOVE", "Zip"),
        ("Zion.T", "Stranger", "Zip"),
        ("Zion.T", "The Things I Like", "Zip"),
        ("Zion.T", "V (Peace)", "Zip"),
        ("Zion.T", "NOT FOR SALE", "Zip"),
        ("Zion.T", "Invisible Person", "Zip"),
        ("Zion.T", "Inside a Dark Room", "Zip"),
        ("Zion.T", "Whale", "Zip"),
        ("Zion.T", "Happy Ending", "Zip"),
        ("Bobby", "Drowning", "S.i.R"),
        ("Bobby", "Cherry Blossom", "S.i.R"),
        ("Lil Moshpit", "TO GO", ""),
        ("Lil Moshpit", "Money Only Shows Hustle", ""),
        ("Leellamarz", "I don't know a single thing", ""),
        ("Leellamarz", "Can't stop", "DAYDATE"),
        ("Leellamarz", "Wave", "DAYDATE"),
        ("Leellamarz", "Moshpit", "DAYDATE"),
        ("Leellamarz", "We like to party", "DAYDATE"),
        ("Leellamarz", "Money dance", "DAYDATE"),
        ("Leellamarz", "Tsunami", "DAYDATE"),
        ("Kid Milli", "Overtake", "BEIGE"),
        ("Mino", "BODY", "BODY"),
        ("Mino", "Aero", "BODY"),
        ("Changmo", "FWB", ""),
        ("Punchnello", "Motive", ""),
        ("Colde", "Wave", ""),
        ("Tablo", "God's Latte", "Strawberry"),
        ("Leellamarz", "On the street", "Life is Once"),
        ("Leellamarz", "Russian Roulette", "Life is Once"),
        ("Leellamarz", "Boys Like Girls", "Life is Once"),
        ("Leellamarz", "Masquerade Ball", "Life is Once"),
        ("Paloalto", "Issues", "BUT FOR NOW LEAVE ME ALONE"),
    ],
    2024: [
        ("Beenzino", "Train", ""),
        ("Zico", "SPOT!", ""),
        ("Zico", "Earthquake", ""),
        ("Jay Park", "DNA Remix", ""),
        ("Loco", "Focus", ""),
        ("Crush", "Hmm-cheat", ""),
        ("Dean", "NASA", "3:33"),
        ("Dean", "Ctrl", "3:33"),
        ("Heize", "Fallin'", ""),
        ("Gray", "Summer Night", ""),
        ("Zion.T", "Complex", ""),
        ("Bobby", "F", ""),
        ("Mino", "LOVE", ""),
        ("G-Dragon", "HOME SWEET HOME", ""),
        ("G-Dragon", "POWER", ""),
        ("Tablo", "God's Latte", "Strawberry"),
        ("Epik High", "Catch", ""),
        ("PH-1", "Zombies", ""),
        ("PH-1", "TGIF", ""),
        ("PH-1", "Tipsy", ""),
        ("PH-1", "Mr. Bad", ""),
        ("PH-1", "Run Away", ""),
        ("Coogie", "Flame", ""),
        ("Coogie", "Shut Up", ""),
        ("Coogie", "Spaceship", ""),
        ("Coogie", "Two Pills", ""),
        ("Coogie", "BABYFACE", ""),
        ("Coogie", "Arikari", ""),
        ("Coogie", "Sober", ""),
        ("Coogie", "Focus on me", ""),
        ("Coogie", "Can't get enough", ""),
        ("Coogie", "What u say?", ""),
        ("Coogie", "Coogie and I", ""),
        ("Kid Milli", "cash out", ""),
        ("Changmo", "Wonderful Days", ""),
        ("Leellamarz", "Two Pills", "STILL YOUNG BOY L"),
        ("Leellamarz", "Japan", "STILL YOUNG BOY L"),
        ("Leellamarz", "Fucked", "STILL YOUNG BOY L"),
        ("Leellamarz", "Desert Flower", "STILL YOUNG BOY L"),
        ("Leellamarz", "Miss Me", "STILL YOUNG BOY L"),
        ("Leellamarz", "Can't you see me?", "STILL YOUNG BOY L"),
        ("Leellamarz", "I Like U", "STILL YOUNG BOY L"),
        ("Leellamarz", "Let me go to heaven", ""),
        ("TOIL", "Drama", ""),
        ("TOIL", "Tragic Comedy", "1 Giant Leap"),
        ("Blase", "WHAT HAVE WE DONE", ""),
        ("Punchnello", "Loveseat", ""),
        ("Colde", "honestly", ""),
        ("Paloalto", "Valentina", ""),
        ("The Quiett", "King Is Back", "Luxury Flow"),
        ("The Quiett", "Look Inside", "Luxury Flow"),
        ("The Quiett", "UGRS", "Luxury Flow"),
        ("The Quiett", "Crystal Crates", "Luxury Flow"),
        ("The Quiett", "Mercedes", "Luxury Flow"),
        ("The Quiett", "Selfie", "Luxury Flow"),
        ("The Quiett", "Last Of Us", "Luxury Flow"),
        ("The Quiett", "What's Love Now", "Luxury Flow"),
        ("The Quiett", "Visionaire", "Luxury Flow"),
        ("The Quiett", "Dream", "Luxury Flow"),
        ("The Quiett", "After Party", "Luxury Flow"),
        ("The Quiett", "Ocean View", "Luxury Flow"),
        ("The Quiett", "Usual Suspect", "Luxury Flow"),
        ("Nafla", "dreamin'", "natural high"),
        ("Nafla", "paris and tokyo", "natural high"),
        ("Loopy", "ride or die", "natural high"),
        ("Lil Moshpit", "Vader", ""),
        ("Beenzino", "Monet", "NOWITZKI"),
        ("Zico", "New Thing", "Grown Ass Kid"),
        ("Jay Park", "McNasty", ""),
        ("Loco", "Wedding", ""),
        ("Crush", "Rush Hour", ""),
        ("Dean", "4:44", ""),
        ("Heize", "Undo", ""),
        ("Gray", "Remedy", ""),
        ("Zion.T", "Lonely Christmas", ""),
        ("Bobby", "Cherry Blossom", ""),
        ("Mino", "Body", ""),
        ("G-Dragon", "TAKE ME", ""),
        ("Tablo", "Rain Song", ""),
        ("Epik High", "On My Way", ""),
        ("PH-1", "Juliette!", ""),
        ("Coogie", "Alone", ""),
        ("Kid Milli", "Summer", ""),
        ("Changmo", "Just the Two of Us", ""),
        ("Leellamarz", "B.B.B", ""),
        ("TOIL", "1 Giant Leap", "1 Giant Leap"),
        ("Blase", "Quote That", ""),
        ("Punchnello", "Cream Cheese", ""),
        ("Colde", "Star", ""),
        ("Paloalto", "Top Primary", ""),
        ("The Quiett", "Nike", ""),
        ("Nafla", "karma", "natural high"),
        ("Loopy", "Ice King", ""),
        ("Lil Moshpit", "Yooooo", ""),
        ("Beenzino", "Trippy", "NOWITZKI"),
        ("Zico", "Grown Ass Kid", ""),
        ("Jay Park", "Why", ""),
        ("Loco", "INEEDYOURLOVE", ""),
        ("Crush", "Oasis", ""),
        ("Dean", "Die 4 You", ""),
        ("Heize", "Run Run", ""),
        ("Gray", "Dangerous", ""),
        ("Zion.T", "Just", ""),
        ("Bobby", "Drowning", ""),
        ("Mino", "Aero", ""),
        ("G-Dragon", "SUPER STAR", ""),
        ("Tablo", "Face ID", ""),
        ("Epik High", "Strawberry", ""),
        ("PH-1", "Issues", ""),
        ("Coogie", "Good Night", ""),
        ("Kid Milli", "Lightly", ""),
        ("Changmo", "SMF", ""),
        ("Leellamarz", "Number", ""),
        ("TOIL", "like when we first met", ""),
        ("Blase", "Yuppie Ting", ""),
        ("Punchnello", "Motive", ""),
        ("Colde", "Wave", ""),
        ("Paloalto", "Lonely", ""),
        ("The Quiett", "Quitty", ""),
        ("Nafla", "run!", "natural high"),
        ("Loopy", "natural high", ""),
        ("Lil Moshpit", "Slatty Slut", ""),
    ],
    2025: [
        ("PH-1", "GOSHA", ""),
        ("PH-1", "Show Must Go On", ""),
        ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
        ("PH-1", "PARTY PPL", "WHAT HAVE WE DONE"),
        ("PH-1", "KEEP IT ON THE LOW", "WHAT HAVE WE DONE"),
        ("PH-1", "MY B", "WHAT HAVE WE DONE"),
        ("PH-1", "BAKA", "WHAT HAVE WE DONE"),
        ("PH-1", "CRASHINNN OUTTT!!!", "WHAT HAVE WE DONE"),
        ("PH-1", "ERYKAH BADU", "WHAT HAVE WE DONE"),
        ("PH-1", "DRUGGED2THRILLS", "WHAT HAVE WE DONE"),
        ("PH-1", "54321", "WHAT HAVE WE DONE"),
        ("PH-1", "EASY", "WHAT HAVE WE DONE"),
        ("PH-1", "SUMMER FEVER", "WHAT HAVE WE DONE"),
        ("PH-1", "COVERED IN RAIN", "WHAT HAVE WE DONE"),
        ("PH-1", "HAD I KNOWN", "WHAT HAVE WE DONE"),
        ("PH-1", "SOAK IN BLUE", "WHAT HAVE WE DONE"),
        ("Coogie", "Flame", "UPSET"),
        ("Coogie", "Shut Up", "UPSET"),
        ("Coogie", "Spaceship", "UPSET"),
        ("Coogie", "Two Pills", "UPSET"),
        ("Coogie", "BABYFACE", "UPSET"),
        ("Coogie", "Arikari", "UPSET"),
        ("Coogie", "Sober", "UPSET"),
        ("Coogie", "Focus on me", "UPSET"),
        ("Coogie", "Can't get enough", "UPSET"),
        ("Coogie", "What u say?", "UPSET"),
        ("Coogie", "Coogie and I", "UPSET"),
        ("Zico", "Shut Up", ""),
        ("Jay Park", "TO GO", ""),
        ("Loco", "Can't get enough", ""),
        ("Beenzino", "Train", "NOWITZKI"),
        ("Crush", "EZPZ", ""),
        ("Dean", "NASA", ""),
        ("Heize", "Lips", ""),
        ("Gray", "BABYFACE", ""),
        ("Zion.T", "V (Peace)", ""),
        ("Bobby", "F", "Robert"),
        ("Mino", "LOVE", "LOVE"),
        ("G-Dragon", "HOME SWEET HOME", "Übermensch"),
        ("G-Dragon", "POWER", "Übermensch"),
        ("Tablo", "Mercedes", ""),
        ("Epik High", "UGRS", ""),
        ("Kid Milli", "HONDA!", ""),
        ("Changmo", "Wonderful Days", ""),
        ("Leellamarz", "Mercedes", ""),
        ("TOIL", "Two Pills", ""),
        ("Blase", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
        ("Blase", "D.O.D", ""),
        ("Punchnello", "F", ""),
        ("Colde", "Arikari", ""),
        ("Paloalto", "BABYFACE", ""),
        ("The Quiett", "BABYFACE", ""),
        ("Nafla", "Shut Up", ""),
        ("Loopy", "Shut Up", ""),
        ("Lil Moshpit", "Shut Up", ""),
        ("Beenzino", "Travel Again", ""),
        ("Zico", "SPOT!", ""),
        ("Jay Park", "Why", ""),
        ("Loco", "Focus on me", ""),
        ("Crush", "A Man Like Me", ""),
        ("Dean", "Ctrl", ""),
        ("Heize", "Perhaps Happy Ending", ""),
        ("Gray", "Focus on me", ""),
        ("Zion.T", "UNLOVE", ""),
        ("Bobby", "Robert", ""),
        ("Mino", "BODY", ""),
        ("G-Dragon", "TAKE ME", "Übermensch"),
        ("Tablo", "Crystal Crates", ""),
        ("Epik High", "Crystal Crates", ""),
        ("Kid Milli", "BNC", ""),
        ("Changmo", "UGRS", ""),
        ("Leellamarz", "Japan", ""),
        ("TOIL", "Japan", ""),
        ("Punchnello", "Japan", ""),
        ("Colde", "Sober", ""),
        ("Paloalto", "King Is Back", ""),
        ("The Quiett", "King Is Back", ""),
        ("Nafla", "Flame", ""),
        ("Loopy", "Flame", ""),
        ("Lil Moshpit", "Flame", ""),
        ("Beenzino", "990", ""),
        ("Zico", "Earthquake", ""),
        ("Jay Park", "Candy", ""),
        ("Loco", "VOLVO", ""),
        ("Crush", "Ego", ""),
        ("Dean", "Die 4 You", ""),
        ("Heize", "Midnight", ""),
        ("Gray", "Remedy", ""),
        ("Zion.T", "Stranger", ""),
        ("Bobby", "Cherry Blossom", "Robert"),
        ("Mino", "Aero", "LOVE"),
        ("G-Dragon", "SUPER STAR", "Übermensch"),
        ("Tablo", "Look Inside", ""),
        ("Epik High", "Look Inside", ""),
        ("Kid Milli", "Coupe!", ""),
        ("Changmo", "FWB", ""),
        ("Leellamarz", "Desert Flower", ""),
        ("TOIL", "Desert Flower", ""),
        ("Blase", "GOSHA", ""),
        ("Punchnello", "Desert Flower", ""),
        ("Colde", "honestly", ""),
        ("Paloalto", "Issues", ""),
        ("The Quiett", "Issues", ""),
        ("Nafla", "Spaceship", ""),
        ("Loopy", "Spaceship", ""),
        ("Lil Moshpit", "Spaceship", ""),
        ("Beenzino", "Lemon", ""),
        ("Zico", "LOCO", ""),
        ("Jay Park", "Sunday Night Drive", ""),
        ("Loco", "NOT OK", ""),
        ("Crush", "New Day", ""),
        ("Dean", "4:44", ""),
        ("Heize", "Connection", ""),
        ("Gray", "Summer Night", ""),
        ("Zion.T", "Whale", ""),
        ("Bobby", "Drowning", "Robert"),
        ("Mino", "Fiance", ""),
        ("Tablo", "Visionaire", ""),
        ("Epik High", "Visionaire", ""),
        ("Kid Milli", "BORA", ""),
        ("Leellamarz", "I Like U", ""),
        ("Punchnello", "Cream Cheese", ""),
        ("Colde", "Star", ""),
        ("Paloalto", "Valentina", ""),
        ("The Quiett", "Valentina", ""),
        ("Nafla", "Valentina", ""),
        ("Loopy", "Valentina", ""),
        ("Lil Moshpit", "Valentina", ""),
    ],
}


def norm_key(artist: str, title: str) -> str:
    def norm(s: str) -> str:
        s = s.lower().strip()
        s = s.replace("&", " and ")
        s = re.sub(r"\bfeat\.?\b|\bft\.?\b|\bfeaturing\b", " ", s)
        s = re.sub(r"[^\w\s가-힣]+", " ", s, flags=re.UNICODE)
        return re.sub(r"\s+", " ", s).strip()
    return f"{norm(artist)}|{norm(title)}"


def write_module(year: int, tracks: list[tuple[str, str, str]]) -> None:
    lines = ["TRACKS = ["]
    for a, t, al in tracks:
        lines.append(f"    ({a!r}, {t!r}, {al!r}),")
    lines.append("]")
    lines.append("")
    path = os.path.join(ROOT, f"y{year}.py")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {path} ({len(tracks)})")


def main() -> None:
    used: set[str] = set()
    bad_suffix = re.compile(r"\(\d{4}(?:\s+Mix)?\)\s*$")
    for year in (2022, 2023):
        tracks = CATALOG[year]
        if len(tracks) != 100:
            print(f"FAIL {year}: count {len(tracks)}")
            sys.exit(1)
        for artist, title, album in tracks:
            if bad_suffix.search(title):
                print(f"FAIL suffix: {year} {artist} - {title}")
                sys.exit(1)
            k = norm_key(artist, title)
            if k in used:
                print(f"FAIL dup: {year} {artist} - {title}")
                sys.exit(1)
            used.add(k)
        write_module(year, tracks)
    print(f"OK {len(used)} unique tracks")


if __name__ == "__main__":
    main()
