/**
 * Curated global (non hip-hop/rap) tracks by release year.
 * Rank order: Billboard Hot 100 year-end + critical acclaim + consensus.
 */
export const YEAR_DATA = {
  2000: [
    { artist: "Faith Hill", title: "Breathe", album: "Breathe" },
    { artist: "Santana feat. Rob Thomas", title: "Smooth", album: "Supernatural" },
    { artist: "Santana feat. The Product G&B", title: "Maria Maria", album: "Supernatural" },
    { artist: "Joe", title: "I Wanna Know", album: "My Name Is Joe" },
    { artist: "Vertical Horizon", title: "Everything You Want", album: "Everything You Want" },
    { artist: "Destiny's Child", title: "Say My Name", album: "The Writing's on the Wall" },
    { artist: "Savage Garden", title: "I Knew I Loved You", album: "Affirmation" },
    { artist: "Lonestar", title: "Amazed", album: "Lonely Grill" },
    { artist: "Matchbox Twenty", title: "Bent", album: "Mad Season" },
    { artist: "Toni Braxton", title: "He Wasn't Man Enough", album: "The Heat" },
    { artist: "Creed", title: "Higher", album: "Human Clay" },
    { artist: "Aaliyah", title: "Try Again", album: "Romeo Must Die" },
    { artist: "Destiny's Child", title: "Jumpin', Jumpin'", album: "The Writing's on the Wall" },
    { artist: "Sisqó", title: "Thong Song", album: "Unleash the Dragon" },
    { artist: "*NSYNC", title: "Bye Bye Bye", album: "No Strings Attached" },
    { artist: "Britney Spears", title: "Oops!... I Did It Again", album: "Oops!... I Did It Again" },
    { artist: "Marc Anthony", title: "I Need to Know", album: "Marc Anthony" },
    { artist: "Montell Jordan", title: "Get It On Tonite", album: "Get It On... Tonite" },
    { artist: "Sisqó", title: "Incomplete", album: "Unleash the Dragon" },
    { artist: "*NSYNC", title: "It's Gonna Be Me", album: "No Strings Attached" },
    { artist: "Christina Aguilera", title: "What a Girl Wants", album: "Christina Aguilera" },
    { artist: "Brian McKnight", title: "Back at One", album: "Back at One" },
    { artist: "Mýa", title: "Case of the Ex (Whatcha Gonna Do)", album: "Fear of Flying" },
    { artist: "Donell Jones", title: "U Know What's Up", album: "Where I Wanna Be" },
    { artist: "Train", title: "Meet Virginia", album: "Drops of Jupiter" },
    { artist: "Jessica Simpson", title: "I Wanna Love You Forever", album: "Sweet Kisses" },
    { artist: "Creed", title: "With Arms Wide Open", album: "Human Clay" },
    { artist: "Jennifer Lopez", title: "Love Don't Cost a Thing", album: "J.Lo" },
    { artist: "Sonique", title: "It Feels So Good", album: "Hear My Cry" },
    { artist: "Christina Aguilera", title: "I Turn to You", album: "Christina Aguilera" },
    { artist: "Madonna", title: "Music", album: "Music" },
    { artist: "Janet Jackson", title: "Doesn't Really Matter", album: "Nutty Professor II: The Klumps" },
    { artist: "3 Doors Down", title: "Kryptonite", album: "The Better Life" },
    { artist: "98 Degrees", title: "Give Me Just One Night (Una Noche)", album: "Revelation" },
    { artist: "Filter", title: "Take a Picture", album: "Title of Record" },
    { artist: "TLC", title: "Unpretty", album: "FanMail" },
    { artist: "P!nk", title: "Most Girls", album: "Can't Take Me Home" },
    { artist: "Backstreet Boys", title: "Show Me the Meaning of Being Lonely", album: "Black & Blue" },
    { artist: "BBMak", title: "Back Here", album: "Sooner or Later" },
    { artist: "P!nk", title: "There You Go", album: "Can't Take Me Home" },
    { artist: "U2", title: "Beautiful Day", album: "All That You Can't Leave Behind" },
    { artist: "Bon Jovi", title: "It's My Life", album: "Crush" },
    { artist: "Blink-182", title: "All the Small Things", album: "Enema of the State" },
    { artist: "Shaggy feat. RikRok", title: "It Wasn't Me", album: "Hot Shot" },
    { artist: "Shaggy feat. Rayvon", title: "Angel", album: "Hot Shot" },
    { artist: "Enrique Iglesias", title: "Be with You", album: "Enrique" },
    { artist: "Enrique Iglesias", title: "Rhythm Divine", album: "Enrique" },
    { artist: "Macy Gray", title: "I Try", album: "On How Life Is" },
    { artist: "Westlife", title: "Swear It Again", album: "Westlife" },
    { artist: "Westlife", title: "Fool Again", album: "Westlife" },
    { artist: "Christina Aguilera", title: "Come On Over Baby (All I Want Is You)", album: "Christina Aguilera" },
    { artist: "Backstreet Boys", title: "The One", album: "Black & Blue" },
    { artist: "Backstreet Boys", title: "Shape of My Heart", album: "Black & Blue" },
    { artist: "Eiffel 65", title: "Blue (Da Ba Dee)", album: "Europop" },
    { artist: "Moby", title: "Porcelain", album: "Play" },
    { artist: "Moby", title: "Natural Blues", album: "Play" },
    { artist: "Red Hot Chili Peppers", title: "Otherside", album: "Californication" },
    { artist: "Red Hot Chili Peppers", title: "Californication", album: "Californication" },
    { artist: "Limp Bizkit", title: "Break Stuff", album: "Significant Other" },
    { artist: "Limp Bizkit", title: "My Generation", album: "Chocolate Starfish and the Hot Dog Flavored Water" },
    { artist: "Metallica", title: "I Disappear", album: "Mission: Impossible 2" },
    { artist: "Metallica", title: "No Leaf Clover", album: "S&M" },
    { artist: "Radiohead", title: "Everything in Its Right Place", album: "Kid A" },
    { artist: "Radiohead", title: "Optimistic", album: "Kid A" },
    { artist: "Coldplay", title: "Yellow", album: "Parachutes" },
    { artist: "Travis", title: "Why Does It Always Rain on Me?", album: "The Man Who" },
    { artist: "Foo Fighters", title: "Learn to Fly", album: "There Is Nothing Left to Lose" },
    { artist: "Foo Fighters", title: "Stacked Actors", album: "There Is Nothing Left to Lose" },
    { artist: "Green Day", title: "Minority", album: "Warning" },
    { artist: "Green Day", title: "Warning", album: "Warning" },
    { artist: "Ricky Martin", title: "She Bangs", album: "Sound Loaded" },
    { artist: "Ricky Martin", title: "She's All I Ever Had", album: "Sound Loaded" },
    { artist: "Marc Anthony", title: "You Sang to Me", album: "Marc Anthony" },
    { artist: "Marc Anthony", title: "My Baby You", album: "Marc Anthony" },
    { artist: "Tim McGraw", title: "My Best Friend", album: "A Place in the Sun" },
    { artist: "Tim McGraw", title: "Something Like That", album: "A Place in the Sun" },
    { artist: "Tim McGraw", title: "Grown Men Don't Cry", album: "Set This Circus Down" },
    { artist: "Carrie Underwood", title: "Before He Cheats", album: "" },
    { artist: "LeAnn Rimes", title: "I Need You", album: "I Need You" },
    { artist: "LeAnn Rimes", title: "Can't Fight the Moonlight", album: "Coyote Ugly" },
    { artist: "Deborah Cox", title: "Nobody's Supposed to Be Here", album: "One Wish" },
    { artist: "Deborah Cox", title: "We Can't Be Friends", album: "One Wish" },
    { artist: "Carl Thomas", title: "I Wish", album: "Emotional" },
    { artist: "Carl Thomas", title: "Emotional", album: "Emotional" },
    { artist: "Usher", title: "U Remind Me", album: "8701" },
    { artist: "Usher", title: "U Got It Bad", album: "" },
    { artist: "Usher", title: "Pop Ya Collar", album: "" },
    { artist: "Usher", title: "Nice & Slow", album: "" },
    { artist: "Usher", title: "Confessions Part II", album: "" },
    { artist: "Usher", title: "Burn", album: "" },
    { artist: "Usher", title: "Yeah!", album: "" },
    { artist: "Usher", title: "Caught Up", album: "" },
    { artist: "Usher", title: "My Boo", album: "" },
    { artist: "Usher", title: "Love in This Club", album: "" },
    { artist: "Usher", title: "OMG", album: "" },
    { artist: "Usher", title: "DJ Got Us Fallin' in Love", album: "" },
    { artist: "Usher", title: "Scream", album: "" },
    { artist: "Usher", title: "Climax", album: "" },
    { artist: "Usher", title: "Good Kisser", album: "" },
    { artist: "Usher", title: "No Limit", album: "" },
    { artist: "Usher", title: "Crash", album: "" },
    { artist: "Usher", title: "Bad Habits", album: "" },
    { artist: "Usher", title: "Don't Waste My Time", album: "" },
  ],
};
