package com.nullrefer.music.ondevice

import android.net.Uri
import android.os.Handler
import android.os.Looper
import android.provider.DocumentsContract
import android.webkit.CookieManager
import com.chaquo.python.Python
import com.chaquo.python.android.AndroidPlatform
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.File
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

class OnDeviceDownloadModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  override fun getName(): String = "NrmOnDeviceDownload"

  /** 앱 시작·다운로드 전 ffmpeg+libffmpeg.so 예열 (백그라운드) */
  @ReactMethod
  fun prefetchFfmpeg(promise: Promise) {
    Thread {
      try {
        val ctx = reactApplicationContext.applicationContext
        val paths = FfmpegBootstrap.ensure(ctx)
        val map = Arguments.createMap()
        map.putBoolean("ready", paths?.isReady() == true)
        if (paths != null) {
          map.putString("path", paths.binaryPath())
        }
        promise.resolve(map)
      } catch (e: Exception) {
        NrmFileLogger.error("ffmpeg", "prefetchFfmpeg 실패", e)
        promise.reject("E_FFMPEG_PREFETCH", e.message ?: e.toString(), e)
      }
    }.start()
  }

  private fun ensurePython() {
    val ctx = reactApplicationContext.applicationContext
    NrmFileLogger.log("yt-dlp", "ensurePython 시작 started=${Python.isStarted()}")
    if (!Python.isStarted()) {
      try {
        Python.start(AndroidPlatform(ctx))
        NrmFileLogger.log("yt-dlp", "Chaquopy Python 시작 완료")
      } catch (e: Exception) {
        NrmFileLogger.error("yt-dlp", "Chaquopy Python 시작 실패", e)
        throw e
      }
    }
  }

  // ── 쿠키 추출 ──────────────────────────────────────────────────────────────
  private fun saveCookiesToTempFile(): String {
    val cookieManager = CookieManager.getInstance()
    val rawCookies =
      cookieManager.getCookie("https://www.youtube.com")
        ?.takeIf { it.isNotBlank() }
        ?: cookieManager.getCookie("https://youtube.com")
          ?.takeIf { it.isNotBlank() }
        ?: return ""

    val sb = StringBuilder()
    sb.appendLine("# Netscape HTTP Cookie File")
    sb.appendLine("# Generated by NullReferenceMusic for yt-dlp")
    sb.appendLine()

    for (pair in rawCookies.split(";")) {
      val trimmed = pair.trim()
      val eqIdx = trimmed.indexOf('=')
      if (eqIdx <= 0) continue
      val name = trimmed.substring(0, eqIdx).trim()
      val value = trimmed.substring(eqIdx + 1).trim()
      if (name.isEmpty()) continue
      sb.appendLine(".youtube.com\tTRUE\t/\tTRUE\t0\t$name\t$value")
    }

    val ctx = reactApplicationContext.applicationContext
    val tmpFile = File(ctx.cacheDir, "nrm_yt_cookies_${System.currentTimeMillis()}.txt")
    tmpFile.writeText(sb.toString())
    val lineCount = sb.lines().count { it.isNotBlank() && !it.startsWith("#") }
    NrmFileLogger.log("yt-dlp", "쿠키 파일 생성 path=${tmpFile.absolutePath} entries=$lineCount")
    return tmpFile.absolutePath
  }

  private fun getCookieFilePathSync(): String {
    if (Looper.myLooper() == Looper.getMainLooper()) {
      return saveCookiesToTempFile()
    }
    var result = ""
    val latch = CountDownLatch(1)
    Handler(Looper.getMainLooper()).post {
      try {
        result = saveCookiesToTempFile()
      } finally {
        latch.countDown()
      }
    }
    latch.await(3, TimeUnit.SECONDS)
    return result
  }

  // ── 스트림 URL 추출 ──────────────────────────────────────────────────────────
  @ReactMethod
  fun getAudioStreamUrl(videoId: String, promise: Promise) {
    Thread {
      var cookieFilePath = ""
      NrmFileLogger.log("yt-dlp", "getAudioStreamUrl videoId=$videoId")
      try {
        ensurePython()
        cookieFilePath = getCookieFilePathSync()
        val py = Python.getInstance().getModule("nrm_ytdlp_bridge")
        val streamUrl = py.callAttr("get_audio_stream_url", videoId, cookieFilePath).toString()
        if (streamUrl.isBlank()) {
          throw Exception("스트림 URL이 비어 있습니다.")
        }
        NrmFileLogger.log("yt-dlp", "getAudioStreamUrl OK len=${streamUrl.length}")
        promise.resolve(streamUrl)
      } catch (e: Exception) {
        NrmFileLogger.error("yt-dlp", "getAudioStreamUrl 실패 videoId=$videoId", e)
        promise.reject("E_STREAM_URL", e.message ?: e.toString(), e)
      } finally {
        if (cookieFilePath.isNotBlank()) {
          try { File(cookieFilePath).delete() } catch (_: Exception) {}
        }
      }
    }.start()
  }

  // ── 다운로드 ────────────────────────────────────────────────────────────────
  @ReactMethod
  @Suppress("UNUSED_PARAMETER")
  fun downloadAudio(
    url: String,
    noPlaylist: Boolean,
    audioFormat: String,
    audioQuality: Int,
    promise: Promise,
  ) {
    Thread {
      var cookieFilePath = ""
      NrmFileLogger.log(
        "yt-dlp",
        "downloadAudio url=$url format=$audioFormat quality=$audioQuality",
      )
      try {
        if (url.isBlank()) {
          promise.reject("E_ARG", "URL이 비어 있습니다.")
          return@Thread
        }

        val ctx = reactApplicationContext.applicationContext
        ensurePython()
        cookieFilePath = getCookieFilePathSync()
        val ffmpegPath = FfmpegBootstrap.binaryPath(ctx)
        val ffmpegLibDir = FfmpegBootstrap.libDirPath(ctx)
        NrmFileLogger.log(
          "yt-dlp",
          "downloadAudio ffmpegPath=${ffmpegPath.ifBlank { "(없음)" }} libDir=${ffmpegLibDir.ifBlank { "(없음)" }}",
        )
        val outDir = File(ctx.cacheDir, "nrm-ytdlp-tmp").apply { mkdirs() }
        val py = Python.getInstance().getModule("nrm_ytdlp_bridge")
        val fmt = audioFormat.trim().ifBlank { "mp3" }
        val quality = audioQuality.coerceIn(0, 9)
        val outPath =
          py.callAttr(
            "download_audio",
            url,
            outDir.absolutePath,
            cookieFilePath,
            fmt,
            quality.toString(),
            ffmpegPath,
            ffmpegLibDir,
          ).toString()
        val outFile = File(outPath)
        if (!outFile.exists()) {
          throw Exception("다운로드 결과 파일을 찾지 못했습니다.")
        }
        NrmFileLogger.log(
          "yt-dlp",
          "downloadAudio OK path=${outFile.absolutePath} size=${outFile.length()}",
        )
        val map = Arguments.createMap()
        map.putString("path", outFile.absolutePath)
        map.putString("message", "기기에 저장되었습니다.")
        promise.resolve(map)
      } catch (e: Exception) {
        NrmFileLogger.error("yt-dlp", "downloadAudio 실패 url=$url", e)
        promise.reject("E_ONDEVICE", e.message ?: e.toString(), e)
      } finally {
        if (cookieFilePath.isNotBlank()) {
          try { File(cookieFilePath).delete() } catch (_: Exception) {}
        }
      }
    }.start()
  }

  /** innertube 등 원본 포맷 파일을 설정 확장자로 ffmpeg 변환 */
  @ReactMethod
  fun transcodeAudio(
    inputPath: String,
    audioFormat: String,
    audioQuality: Int,
    promise: Promise,
  ) {
    Thread {
      NrmFileLogger.log(
        "yt-dlp",
        "transcodeAudio input=$inputPath format=$audioFormat quality=$audioQuality",
      )
      try {
        val srcPath = inputPath.removePrefix("file://")
        val src = File(srcPath)
        if (!src.isFile) {
          promise.reject("E_ARG", "입력 파일이 없습니다.")
          return@Thread
        }
        val ctx = reactApplicationContext.applicationContext
        val fmt = audioFormat.trim().ifBlank { "mp3" }
        val quality = audioQuality.coerceIn(0, 9)
        val result =
          FfmpegTranscode.transcode(
            ctx,
            src,
            fmt,
            quality,
          )
        val outFile = result.file
        if (result.fallbackReason != null) {
          NrmFileLogger.log(
            "yt-dlp",
            "transcodeAudio fallback reason=${result.fallbackReason} effective=${result.effectiveFormat}",
          )
        }
        NrmFileLogger.log(
          "yt-dlp",
          "transcodeAudio OK path=${outFile.absolutePath} size=${outFile.length()}",
        )
        val map = Arguments.createMap()
        map.putString("path", outFile.absolutePath)
        map.putString("format", result.effectiveFormat)
        if (result.fallbackReason != null) {
          map.putString("fallbackReason", result.fallbackReason)
        }
        promise.resolve(map)
      } catch (e: Exception) {
        NrmFileLogger.error("yt-dlp", "transcodeAudio 실패 input=$inputPath", e)
        promise.reject("E_TRANSCODE", e.message ?: e.toString(), e)
      }
    }.start()
  }

  private val safCopyLock = Any()

  /** SAF tree URI 아래에 로컬 파일을 스트리밍 복사 (JS base64 로드 없음). */
  @ReactMethod
  fun copyFileToSaf(
    sourcePath: String,
    treeUri: String,
    displayName: String,
    mimeType: String,
    promise: Promise,
  ) {
    Thread {
      try {
        val srcPath = sourcePath.removePrefix("file://")
        if (srcPath.startsWith("content:")) {
          promise.reject(
              "E_ARG",
              "소스는 로컬 파일 경로여야 합니다 (content URI 불가): ${srcPath.take(96)}",
          )
          return@Thread
        }
        synchronized(safCopyLock) {
        val src = File(srcPath)
        if (!src.isFile) {
          promise.reject("E_ARG", "소스 파일이 없습니다.")
          return@Thread
        }
        val tree = Uri.parse(treeUri)
        val resolver = reactApplicationContext.contentResolver
        val destUri =
          DocumentsContract.createDocument(
            resolver,
            tree,
            mimeType.trim().ifBlank { "audio/mpeg" },
            displayName.trim().ifBlank { src.name },
          ) ?: throw Exception("SAF 파일을 만들지 못했습니다.")
        resolver.openOutputStream(destUri)?.use { out ->
          src.inputStream().use { input -> input.copyTo(out) }
        } ?: throw Exception("SAF에 쓸 수 없습니다.")
        val map = Arguments.createMap()
        map.putString("uri", destUri.toString())
        promise.resolve(map)
        }
      } catch (e: Exception) {
        NrmFileLogger.error(
            "saf",
            "copyFileToSaf 실패 src=${sourcePath.take(80)} tree=${treeUri.take(80)} name=$displayName",
            e,
        )
        promise.reject("E_SAF_COPY", e.message ?: e.toString(), e)
      }
    }.start()
  }
}
