#!/usr/bin/env python3
"""Auto-fill year pools until finalize reaches 100 tracks per year."""
from __future__ import annotations

import importlib.util
from collections import Counter
from pathlib import Path

from top_up_pools import (
    MAX_PER,
    TARGET,
    dedupe,
    filter_new,
    get_raw,
    global_seen_through,
    track_key,
    write_catalog_2020_2025,
)

GEN = Path(__file__).parent

# Globally-unique filler — deep cuts / B-sides / 2024–2025 releases
FILLER = [
    # 2020 gap
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("aespa", "Black Mamba", ""),
    ("TWICE", "I Can't Stop Me", "Eyes wide open"),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Why Not?", "[12:00]"),
    ("Apink", "Dumhdurum", "Look"),
    ("CIX", "My My", ""),
    ("SuperM", "Tiger Inside", "Super One"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("Cherry Bullet", "Hands Up", ""),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Everglow", "LA DI DA", ""),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("Mamamoo", "Dingga", ""),
    ("TREASURE", "Boy", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
    ("STAYC", "ASAP", ""),
    ("Brave Girls", "Rollin'", ""),
    ("Weki Meki", "Dazzle Dazzle", ""),
    ("NCT U", "Make A Wish (Birthday Song)", "Resonance Pt. 1"),
    ("WayV", "Take Off", "Take Off"),
    ("The Boyz", "The Stealer", "THE STEALER"),
    ("KARD", "Dumb Litty", "KARD 4th Mini Album"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("ONEUS", "LIT", "LIVED"),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("woo!ah!", "Purple", ""),
    ("TRI.BE", "RUB-A-DUM", ""),
    ("PURPLE KISS", "Zombie", ""),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
    ("ENHYPEN", "Drunk-Dazed", "BORDER : CARNIVAL"),
    ("SuperM", "Jopping", "Super One"),
    ("Victon", "Nostalgia", "Nostalgia"),
    ("Secret Number", "Who Dis?", ""),
    ("Bvndit", "Jungle", "Carnival"),
    # 2024 unique
    ("Young Posse", "XX", "XX"),
    ("KISS OF LIFE", "Midas Touch", "Midas Touch"),
    ("(G)-IDLE", "Wife", "2"),
    ("Taeyeon", "To. X", "To. X - The 5th Mini Album"),
    ("IU", "Holssi", "The Winning"),
    ("Melomance", "Look In Love", "Look In Love"),
    ("BOYNEXTDOOR", "So let's go see the stars", "HOW?"),
    ("SEVENTEEN", "LOVE, MONEY, FAME", "SEVENTEENTH HEAVEN"),
    ("NCT WISH", "Songbird", "Steady - The 1st Mini Album"),
    ("Stray Kids", "Hall of Fame", "ATE"),
    ("NewJeans", "Supernatural", "Supernatural"),
    ("IVE", "Accendio", "IVE SWITCH"),
    ("N.Flying", "Bye Bye Bye", "FLY HIGH PROJECT #5"),
    ("VERIVERY", "Crazy Like That", "Lost and Found"),
    ("Apink", "Remind me", "Selfish"),
    ("BTOB", "Dear My Lover", "Be Together"),
    ("Highlight", "Always You", "The Blowing"),
    ("INFINITE", "The Origin", "13egin"),
    ("VIXX", "G.R.I.T.", "CONTACT"),
    ("TNX", "For What", "For What?"),
    ("TRENDZ", "Groove", "New Daybreak"),
    ("WEi", "Thriller", "2nd Mini Album [Love Syndrome]"),
    ("ONEWE", "Gravity", "Planet Nine : VOYAGER"),
    ("ONF", "Bye My Minimal", "Bye My Minimal"),
    ("DKZ", "Harmony", "Harmony"),
    ("TEMPEST", "My World", "TEMPEST Voyage"),
    ("DRIPPIN", "Home", "FIRST LOVE"),
    ("CRAVITY", "Now or Never", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("P1Harmony", "More Than Words", "Killin' It"),
    ("SF9", "Puzzle", "Sequence"),
    ("Golden Child", "Cocktail", "Feel Me"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("ARTMS", "Air", "Dall"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("tripleS", "Invincible", "ASSEMBLE24"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("UNIS", "Curious", "WE UNIS"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("DAY6", "Melt Down", "Fourever"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("MEOVV", "MEOW", "MEOW"),
    ("MEOVV", "BODY", "MEOW"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("Jimin", "Who", "MUSE"),
    ("Lisa", "Rockstar", "Alter Ego"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("TWS", "plot twist", "TWS 1st Mini Album 'Sparkling Blue'"),
    ("TWS", "hey hey hey", "TWS 2nd Mini Album 'SUMMER BEAT!'"),
    ("ILLIT", "Magnetic", "SUPER REAL ME"),
    ("ILLIT", "Lucky Girl Syndrome", "SUPER REAL ME"),
    ("ILLIT", "Cherish (My Love)", "I'll Like You"),
    ("Jennie", "Mantra", "Ruby"),
    ("Rosé & Bruno Mars", "APT.", ""),
    ("NewJeans", "How Sweet", "How Sweet"),
    ("NewJeans", "Bubble Gum", "How Sweet"),
    ("LE SSERAFIM", "Smart", "CRAZY"),
    ("LE SSERAFIM", "CRAZY", "CRAZY"),
    ("LE SSERAFIM", "EASY", "EASY"),
    ("aespa", "Supernova", "Armageddon - The 1st Album"),
    ("aespa", "Armageddon", "Armageddon - The 1st Album"),
    ("aespa", "Whiplash", "Whiplash - The 5th Mini Album"),
    ("aespa", "Dirty Work", "Whiplash - The 5th Mini Album"),
    ("IVE", "HEYA", "IVE EMPATHY"),
    ("(G)-IDLE", "Super Lady", "2"),
    ("(G)-IDLE", "Klaxon", "I SWAY"),
    ("Stray Kids", "Chk Chk Boom", "ATE"),
    ("Stray Kids", "Walkin On Water", "ATE"),
    ("SEVENTEEN", "MAESTRO", "17 IS RIGHT HERE"),
    ("NCT 127", "Walk", "WALK - The 6th Album"),
    ("NCT WISH", "Wish", "NCT WISH - The 1st Mini Album"),
    ("NCT DREAM", "Smoothie", "DREAM()SCAPE"),
    ("TXT", "Deja Vu", "The Name Chapter: FREEFALL"),
    ("ENHYPEN", "XO (Only If You Say Yes)", "ROMANCE : UNTOLD"),
    ("STAYC", "1 Thing", "…l"),
    ("STAYC", "GPT", "…l"),
    ("ITZY", "Untouchable", "BORN TO BE"),
    ("ITZY", "GOLD", "GOLD"),
    ("ITZY", "Imaginary Friend", "GOLD"),
    ("TWICE", "ONE SPARK", "With YOU-th"),
    ("TWICE", "Strategy", "STRATEGY"),
    ("TWICE", "Killing Me Good", "STRATEGY"),
    ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
    ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
    ("BABYMONSTER", "Sheesh", "DRIP"),
    ("BABYMONSTER", "Forever", "DRIP"),
    ("BABYMONSTER", "DRIP", "DRIP"),
    ("KISS OF LIFE", "Sticky", "Sticky"),
    ("KISS OF LIFE", "Igloo", "Sticky"),
    ("RIIZE", "Love 119", "Love 119"),
    ("RIIZE", "Impossible", "Impossible"),
    ("RIIZE", "Boom Boom Bass", "RIIZING"),
    ("BOYNEXTDOOR", "Earth, Wind & Fire", "HOW?"),
    ("BOYNEXTDOOR", "Nice Guy", "19.99"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Feel the POP", "You had me at HELLO"),
    ("ZEROBASEONE", "SWEAT", "You had me at HELLO"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "Soñar (Breaker)", "Fe3O4: BREAK"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("fromis_9", "Supersonic", "From"),
    ("fromis_9", "From", "From"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("Dreamcatcher", "Justice", "VillainS"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("OH MY GIRL", "Classified", "Dreamy Resonance"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("Apink", "Dilemma", "HORN"),
    ("TREASURE", "LAST NIGHT", "LAST NIGHT"),
    ("THE BOYZ", "MAESTRO", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "WORK", "THE WORLD EP.Fin : WILL"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    # 2025 unique
    ("IVE", "REBEL HEART", "IVE EMPATHY"),
    ("LE SSERAFIM", "HOT", "HOT"),
    ("Hearts2Hearts", "The Chase", "The Chase"),
    ("Hearts2Hearts", "Butterflies", "The Chase"),
    ("BOYNEXTDOOR", "If I Say, I Love You", "19.99"),
    ("NCT WISH", "Steady", "Steady - The 1st Mini Album"),
    ("NCT DREAM", "When I'm With You", "DREAM()SCAPE"),
    ("Jisoo", "Earthquake", "AMORTAGE"),
    ("Jisoo", "Your Love", "AMORTAGE"),
    ("BABYMONSTER", "WE GO UP", "WE GO UP"),
    ("BABYMONSTER", "CLIK CLAK", "WE GO UP"),
    ("ALLDAY PROJECT", "FAMOUS", "FAMOUS"),
    ("MEOVV", "TOXIC", "MY EYES OPEN VVIDE"),
    ("MEOVV", "Hands Up", "MY EYES OPEN VVIDE"),
    ("ILLIT", "IYKYK", "I'll Like You"),
    ("TWS", "OVERDRIVE", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("TWS", "Countdown!", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("KATSEYE", "My Way", "Touch"),
    ("KATSEYE", "Gameboy", "Touch"),
    ("Stray Kids", "CEREMONY", "合 (HOP)"),
    ("Stray Kids", "Railway (Bang Chan)", "合 (HOP)"),
    ("TWICE", "Strategy (feat. Megan Thee Stallion)", "STRATEGY"),
    ("NMIXX", "Know About Me", "Fe3O4: FORWARD"),
    ("NMIXX", "High Horse", "Fe3O4: FORWARD"),
    ("RIIZE", "Fly Up", "ODYSSEY - The 1st Album"),
    ("RIIZE", "Show Me Love", "ODYSSEY - The 1st Album"),
    ("ZEROBASEONE", "Blue", "You had me at HELLO"),
    ("ENHYPEN", "Bad Desire (With or Without You)", "DESIRE : UNLEASH"),
    ("TXT", "The Star Chapter: SANCTUARY", "The Star Chapter: SANCTUARY"),
    ("G-DRAGON", "HOME SWEET HOME (feat. TAEYANG & DAESUNG)", "Übermensch"),
    ("G-DRAGON", "TOO BAD (feat. Anderson .Paak)", "Übermensch"),
    ("G-DRAGON", "POWER", "Übermensch"),
    ("G-DRAGON", "TAKE ME", "Übermensch"),
    ("BOYNEXTDOOR", "Lucky Charm", "19.99"),
    ("ILLIT", "blink", "I'll Like You"),
    ("NCT WISH", "Steady", "Steady - The 1st Mini Album"),
    ("Hearts2Hearts", "Butterflies", "The Chase"),
    ("ALLDAY PROJECT", "WICKED", "FAMOUS"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("tripleS", "Invincible", "ASSEMBLE24"),
    ("QWER", "My Name is Dolores", "1st Mini Album 'MANITO'"),
    ("DAY6", "The Power of Love", "Fourever"),
    ("Young Posse", "Ate That", "Ate That"),
    ("KISS OF LIFE", "Igloo", "Sticky"),
    ("Apink", "Dilemma", "HORN"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("MEOVV", "MEOW", "MEOW"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("UNIS", "Curious", "WE UNIS"),
    ("ARTMS", "Air", "Dall"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("STAYC", "GPT", "…l"),
    ("ITZY", "Imaginary Friend", "GOLD"),
    ("TWICE", "Killing Me Good", "STRATEGY"),
    ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
    ("Dreamcatcher", "Justice", "VillainS"),
    ("fromis_9", "From", "From"),
    ("OH MY GIRL", "Classified", "Dreamy Resonance"),
    ("Apink", "Dilemma", "HORN"),
    ("KISS OF LIFE", "Sticky", "Sticky"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("fromis_9", "Supersonic", "From"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("Melomance", "Look In Love", "Look In Love"),
    ("IU", "Holssi", "The Winning"),
    ("Taeyeon", "To. X", "To. X - The 5th Mini Album"),
    ("(G)-IDLE", "Wife", "2"),
    ("KISS OF LIFE", "Midas Touch", "Midas Touch"),
    ("Young Posse", "XX", "XX"),
    ("NewJeans", "Supernatural", "Supernatural"),
    ("IVE", "Accendio", "IVE SWITCH"),
    ("N.Flying", "Bye Bye Bye", "FLY HIGH PROJECT #5"),
    ("VERIVERY", "Crazy Like That", "Lost and Found"),
    ("Apink", "Remind me", "Selfish"),
    ("BTOB", "Dear My Lover", "Be Together"),
    ("Highlight", "Always You", "The Blowing"),
    ("INFINITE", "The Origin", "13egin"),
    ("VIXX", "G.R.I.T.", "CONTACT"),
    ("TNX", "For What", "For What?"),
    ("TRENDZ", "Groove", "New Daybreak"),
    ("WEi", "Thriller", "2nd Mini Album [Love Syndrome]"),
    ("ONEWE", "Gravity", "Planet Nine : VOYAGER"),
    ("ONF", "Bye My Minimal", "Bye My Minimal"),
    ("DKZ", "Harmony", "Harmony"),
    ("TEMPEST", "My World", "TEMPEST Voyage"),
    ("DRIPPIN", "Home", "FIRST LOVE"),
    ("CRAVITY", "Now or Never", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("P1Harmony", "More Than Words", "Killin' It"),
    ("SF9", "Puzzle", "Sequence"),
    ("Golden Child", "Cocktail", "Feel Me"),
    ("Paul Kim", "Me After You", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Crush", "None", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Davichi", "First Winter", ""),
    ("Urban Zakapa", "When We Were Two", "02"),
    ("10CM", "Spring Snow", "4.3"),
    ("Punch", "Losing Sleep", ""),
    ("Roy Kim", "Only Then", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("VIVIZ", "PULL UP", "VarioUS"),
    ("fromis_9", "Menow", "Unlock My World"),
    ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
    ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("AKMU", "Love Lee", "Love Lee"),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
    ("Fifty Fifty", "Cupid", "The Beginning"),
    ("Jungkook", "Standing Next to You", "GOLDEN"),
    ("V", "Love Me Again", "Layover"),
    ("Jimin", "Like Crazy", "FACE"),
    ("Jisoo", "Flower", "ME"),
    ("STAYC", "Teddy Bear", "Teddy Bear"),
    ("ITZY", "CAKE", "KILL MY DOUBT"),
    ("TWICE", "SET ME FREE", "READY TO BE"),
    ("Red Velvet", "Chill Kill", "Chill Kill - The 3rd Album"),
    ("NMIXX", "Love Me Like This", "expérgo"),
    ("Kep1er", "Giddy", "Girls Planet - Kepler : THE 3rd Mini Album"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("SHINee", "Hard", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("NCT 127", "Fact Check", "Fact Check - The 5th Album"),
    ("ENHYPEN", "XO (Only If You Say Yes)", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu", "The Name Chapter: FREEFALL"),
    ("NCT DREAM", "Smoothie", "DREAM()SCAPE"),
    ("NCT WISH", "Wish", "NCT WISH - The 1st Mini Album"),
    ("SEVENTEEN", "MAESTRO", "17 IS RIGHT HERE"),
    ("Stray Kids", "Chk Chk Boom", "ATE"),
    ("STAYC", "1 Thing", "…l"),
    ("ITZY", "Untouchable", "BORN TO BE"),
    ("ITZY", "GOLD", "GOLD"),
    ("TWICE", "ONE SPARK", "With YOU-th"),
    ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
    ("BABYMONSTER", "Sheesh", "DRIP"),
    ("BABYMONSTER", "Forever", "DRIP"),
    ("BABYMONSTER", "DRIP", "DRIP"),
    ("RIIZE", "Love 119", "Love 119"),
    ("RIIZE", "Impossible", "Impossible"),
    ("RIIZE", "Boom Boom Bass", "RIIZING"),
    ("BOYNEXTDOOR", "Earth, Wind & Fire", "HOW?"),
    ("BOYNEXTDOOR", "Nice Guy", "19.99"),
    ("ZEROBASEONE", "Feel the POP", "You had me at HELLO"),
    ("ZEROBASEONE", "SWEAT", "You had me at HELLO"),
    ("NMIXX", "Soñar (Breaker)", "Fe3O4: BREAK"),
    ("LE SSERAFIM", "Smart", "CRAZY"),
    ("LE SSERAFIM", "CRAZY", "CRAZY"),
    ("LE SSERAFIM", "EASY", "EASY"),
    ("Jennie", "Mantra", "Ruby"),
    ("Rosé & Bruno Mars", "APT.", ""),
    ("NewJeans", "How Sweet", "How Sweet"),
    ("NewJeans", "Bubble Gum", "How Sweet"),
    ("aespa", "Supernova", "Armageddon - The 1st Album"),
    ("aespa", "Armageddon", "Armageddon - The 1st Album"),
    ("aespa", "Whiplash", "Whiplash - The 5th Mini Album"),
    ("aespa", "Dirty Work", "Whiplash - The 5th Mini Album"),
    ("IVE", "HEYA", "IVE EMPATHY"),
    ("(G)-IDLE", "Super Lady", "2"),
    ("(G)-IDLE", "Klaxon", "I SWAY"),
    ("TWS", "plot twist", "TWS 1st Mini Album 'Sparkling Blue'"),
    ("TWS", "hey hey hey", "TWS 2nd Mini Album 'SUMMER BEAT!'"),
    ("ILLIT", "Magnetic", "SUPER REAL ME"),
    ("ILLIT", "Lucky Girl Syndrome", "SUPER REAL ME"),
    ("TREASURE", "LAST NIGHT", "LAST NIGHT"),
    ("THE BOYZ", "MAESTRO", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "WORK", "THE WORLD EP.Fin : WILL"),
    ("Jimin", "Who", "MUSE"),
    ("Lisa", "Rockstar", "Alter Ego"),
]


def count_selected(raw: dict, year: int) -> int:
    seen = global_seen_through(raw, year - 1)
    ac: Counter[str] = Counter()
    n = 0
    for artist, title, album in raw.get(year, []):
        if n >= TARGET:
            break
        if ac[artist] >= MAX_PER:
            continue
        k = track_key(artist, title)
        if k in seen:
            continue
        n += 1
        ac[artist] += 1
        seen.add(k)
    return n


def autofill_year(raw: dict, year: int) -> None:
    seen = global_seen_through(raw, year - 1)
    pool = list(raw.get(year, []))
    extras = filter_new(FILLER, seen)
    pool = dedupe(pool + extras)
    # reorder: single-track artists first to reduce artist-cap waste
    ac_pre: Counter[str] = Counter()
    for a, t, _ in pool:
        ac_pre[a] += 1
    pool.sort(key=lambda x: (ac_pre[x[0]] > 2, ac_pre[x[0]]))
    raw[year] = pool


def main() -> None:
    # run top_up first
    import top_up_pools

    top_up_pools.main()

    raw = get_raw()
    for year in (2020, 2024, 2025):
        autofill_year(raw, year)
        print(f"after fill {year}: pool={len(raw[year])} select={count_selected(raw, year)}")

    write_catalog_2020_2025(raw)

    # rewrite 2017-2019 unchanged
    c1519 = load(GEN / "catalog_2015_2019.py")
    c1729 = load(GEN / "catalog_2017_2019.py")
    raw.update(c1519.CATALOG_2015_2019)
    raw.update(c1729.CATALOG_2017_2019)

    for year in range(2015, 2026):
        n = count_selected(raw, year)
        print(f"FINAL {year}: {n}/100")


def load(path: Path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


if __name__ == "__main__":
    main()
