#!/usr/bin/env python3
"""K-pop Top 100 candidate pools (2020-2025). Melon/Gaon/community ordered."""
from __future__ import annotations

CATALOG_2020_2025: dict[int, list[tuple[str, str, str]]] = {
    2020: [
        ('BTS', 'Dynamite', ''),
        ('BTS', 'Life Goes On', 'BE'),
        ('BTS', 'Blue & Grey', 'BE'),
        ('BTS', 'Telepathy', 'BE'),
        ('BTS', 'ON', 'Map of the Soul : 7'),
        ('BTS', 'Black Swan', 'Map of the Soul : 7'),
        ('BLACKPINK', 'How You Like That', ''),
        ('BLACKPINK', 'Lovesick Girls', 'THE ALBUM'),
        ('TWICE', 'More & More', ''),
        ('TWICE', 'Cry For Me', ''),
        ('TWICE', 'Fanfare', 'Fanfare'),
        ('ITZY', 'Not Shy', ''),
        ('(G)-IDLE', 'Oh my god', ''),
        ('(G)-IDLE', 'Dumdi Dumdi', 'Dumdi Dumdi'),
        ('Jessi', 'What Type of X', 'What Type of X'),
        ('Sunmi', 'Pporappippam', ''),
        ('Seventeen', 'Left & Right', 'Heng:garæ'),
        ('Seventeen', 'Home;run', 'Heng:garæ'),
        ('Seventeen', 'Fear', 'Heng:garæ'),
        ('Stray Kids', "God's Menu", 'GO LIVE'),
        ('Stray Kids', 'Back Door', 'IN LIFE'),
        ('NCT DREAM', "Ridin'", 'Reload'),
        ('NCT 127', 'Kick Back', 'NCT RESONANCE Pt. 2'),
        ('NCT U', "90's Love", 'Resonance Pt. 1'),
        ('NCT U', 'Work It', 'Resonance Pt. 1'),
        ('ATEEZ', 'THANXX', 'ZERO : FEVER Part.1'),
        ('TXT', 'Blue Hour', 'minisode1 : Blue Hour'),
        ('TXT', 'Eternally', 'The Dream Chapter: ETERNITY'),
        ('ENHYPEN', 'Given-Taken', 'BORDER : DAY ONE'),
        ('Everglow', 'Dun Dun Dance', ''),
        ('IZ*ONE', 'Secret Story of the Swan', 'Oneiric Diary'),
        ('IZ*ONE', 'Panorama', ''),
        ('Taeyeon', 'Dear Me', ''),
        ('Woo', 'Guilty', 'Guilty'),
        ('GOT7', 'Last Piece', 'Breath of Love : Last Piece'),
        ('GOT7', 'Breath', 'Breath of Love : Last Piece'),
        ('GFRIEND', 'MAGO', '回:Walpurgis Night'),
        ('CLC', 'HELICOPTER', 'HELICOPTER'),
        ('MOMOLAND', 'Ready or Not', 'Ready or Not'),
        ('Highlight', 'Not The End', 'The Blowing'),
        ('ASTRO', 'One', 'ONEWE'),
        ('Golden Child', 'ONE (Lucid Dream)', 'Golden Age'),
        ('LOONA', 'Star', '[#]'),
        ('DAY6', 'Zombie', 'The Book of Us : The Demon'),
        ('DAY6', 'Love me or Leave me', 'The Book of Us : The Demon'),
        ('BoA', 'Better', 'Better - The 10th Album'),
        ('aespa', 'Black Mamba', ''),
        ("NU'EST", "I Don't Care", 'The 2nd Album'),
        ('BTOB', 'Missing You', "Feel'eM"),
        ('WINNER', 'Hold', 'Remember'),
        ('SHINee', "Don't Call Me", "Don't Call Me"),
        ('Super Junior', '2YA2YAO!', 'TIMELESS'),
        ('WayV', 'Turn Back Time', ''),
        ('The Boyz', 'Reveal', 'Reveal'),
        ('KARD', 'GUNSHOT', ''),
        ('SF9', 'Summer Breeze', 'Summer Breeze'),
        ('AB6IX', 'The Answer', 'VIVID'),
        ('Bvndit', 'Jungle', 'Carnival'),
        ('TREASURE', 'Orange', 'THE FIRST STEP : CHAPTER TWO'),
        ('TREASURE', 'Beautiful', 'THE FIRST STEP : TREASURE EFFECT'),
        ('P1Harmony', 'Siren', 'DISHARMONY : Stand Out'),
        ('CRAVITY', 'Break all the Rules', 'HIDEOUT: REMEMBER WHO WE ARE - PT.1'),
        ('DRIPPIN', 'Young Blood', 'Boyhood'),
        ('WEi', "Dondododo (Don't Hold Back)", ''),
        ('MCND', 'nanana', 'EARTH AGE'),
        ('A.C.E', 'Favorite Boys', 'HIGHER'),
        ('woo!ah!', 'Purple', ''),
        ('TRI.BE', 'RUB-A-DUM', ''),
        ('PURPLE KISS', 'Zombie', ''),
        ('Billlie', 'GingaMingaYo (the strange world)', 'the Billage of perception: chapter two'),
        ('CLASS:y', 'SHUT DOWN', 'Day&Night'),
        ('YENA', 'SMARTPHONE', 'SMARTPHONE'),
        ('TEMPEST', 'Bad News', 'ON and ON'),
        ('Xdinary Heroes', 'Happy Death Day', 'Overload'),
        ('LIGHTSUM', 'Vivace', 'Into The Light AD MOMENTUM'),
        ('ENHYPEN', 'Let Me In (Crown)', 'BORDER : CARNIVAL'),
        ('VIXX', 'Revolution', 'CONTACT'),
        ('MONSTA X', 'FANTASY', 'FANTASIA X'),
        ('Weki Meki', 'Dazzle Dazzle', ''),
        ('Apink', 'Dumhdurum', 'Look'),
        ('OH MY GIRL', 'Nonstop', 'NONSTOP'),
        ('fromis_9', 'Feel Good (SECRET CODE)', 'My Little Society'),
        ('WJSN', 'Neverland', 'Neverland'),
        ('Dreamcatcher', 'Scream', 'Dystopia: The Tree of Language'),
        ('LOONA', 'Why Not?', '[12:00]'),
        ('LOONA', 'So What', '[#]'),
        ('CHUNG HA', 'Stay Tonight', 'Querencia'),
        ('CHUNG HA', 'Bicycle', 'Querencia'),
        ('STAYC', 'So Bad', 'Star To A Young Culture'),
        ('Secret Number', 'Who Dis?', ''),
        ('PENTAGON', 'Dr. Bebe', 'UNIVERSE : THE PROLOGUE'),
        ('Golden Child', 'Dun Dun Dun', 'Golden Age'),
        ('ONF', 'Summer Poem', 'ONF:MY NAME'),
        ('ONEUS', 'TO BE OR NOT TO BE', 'LIVED'),
        ('EXO', 'Let Me In', ''),
        ('Victon', 'Nostalgia', 'Nostalgia'),
        ('SuperM', 'Tiger Inside', 'Super One'),
        ('Red Velvet', 'Psycho', "'The ReVe Festival' Finale"),
        ('Mamamoo', 'Dingga', ''),
        ('Kang Daniel', 'Who U Are', ''),
        ('Punch', 'Through the Night', ''),
        ('Lee Hi', 'Hola', ''),
        ('Park Hyo Shin', 'Good Goodbye', ''),
        ('Crush', 'None', ''),
        ('Loco', 'Weak', ''),
        ('Gray', 'Real Love', ''),
        ('Epik High', 'Rosario', 'Epik High Is Here 上 (Part 1)'),
        ('10CM', 'Your Mountain', '4.3'),
        ('Weeekly', 'Tag Me (@Me)', 'We are'),
        ('SECRET NUMBER', 'Who Dis?', ''),
        ('ONEUS', 'LIT', 'LIVED'),
        ('BVNDIT', 'Jungle', 'Carnival'),
        ('TREASURE', 'MMM', 'THE FIRST STEP : CHAPTER THREE'),
        ('TREASURE', 'My Treasure', 'THE FIRST STEP'),
        ('TREASURE', 'Come Back Home', 'THE FIRST STEP : CHAPTER ONE'),
        ('TREASURE', 'I Love You', 'THE FIRST STEP : CHAPTER TWO'),
        ('TREASURE', 'Boy', 'THE FIRST STEP : CHAPTER ONE'),
        ('STAYC', 'ASAP', ''),
        ('Brave Girls', "Rollin'", ''),
        ('ENHYPEN', 'Drunk-Dazed', 'BORDER : CARNIVAL'),
        ('NCT 127', 'Punch', 'NCT #Resonance Pt. 2'),
        ('ATEEZ', 'Inception', 'ZERO : FEVER Part.1'),
        ('TXT', "Can't You See Me?", 'The Dream Chapter: ETERNITY'),
        ('GFRIEND', 'Apple', '回:Song of the Sirens'),
        ('Everglow', 'LA DI DA', ''),
        ('WINNER', 'Remember', ''),
        ('TWICE', "I Can't Stop Me", 'Eyes wide open'),
        ('BOL4', 'Some', ''),
    ],
    2021: [
        ('BTS', 'Butter', ''),
        ('BTS', 'Permission to Dance', ''),
        ('aespa', 'Next Level', ''),
        ('aespa', 'Savage', 'Savage - The 1st Mini Album'),
        ('IU', 'Celebrity', 'Lilac'),
        ('IU', 'Lilac', 'Lilac'),
        ('IU', 'Coin', 'Lilac'),
        ('IU', 'Flu', 'Lilac'),
        ('TWICE', 'Alcohol-Free', 'Taste of Love'),
        ('TWICE', 'Scientist', 'Formula of Love - O+T=<3'),
        ('Heize', 'HAPPEN', 'HAPPEN'),
        ('AKMU', 'Nakka', 'NEXT EPISODE'),
        ('Lim Young Woong', 'My Starry Love', ''),
        ('IU', 'strawberry moon', ''),
        ('STAYC', 'ASAP', ''),
        ('STAYC', 'Stereotype', 'Stereotype'),
        ('ITZY', 'MAFIA In the morning', ''),
        ('ITZY', 'LOCO', ''),
        ('(G)-IDLE', 'HWAA', 'I burn'),
        ('OH MY GIRL', 'Dun Dun Dance', ''),
        ('Brave Girls', "Rollin'", ''),
        ('Brave Girls', 'Chi Mat Ba Ram', 'Summer Queen'),
        ('NCT 127', 'Sticker', 'Sticker'),
        ('NCT DREAM', 'Hot Sauce', 'Hot Sauce'),
        ('Stray Kids', 'Thunderous', 'NOEASY'),
        ('SEVENTEEN', 'Ready to love', 'Your Choice'),
        ('SEVENTEEN', 'Rock with you', 'Attacca'),
        ('ENHYPEN', 'Drunk-Dazed', 'BORDER : CARNIVAL'),
        ('TXT', '0X1=LOVESONG (I Know I Love You)', 'The Chaos Chapter: FIGHT OR ESCAPE'),
        ('TXT', 'LO$ER=LO♡ER', 'The Chaos Chapter: FIGHT OR ESCAPE'),
        ('ATEEZ', 'Deja Vu', 'ZERO : FEVER Part.2'),
        ('THE BOYZ', 'MAVERICK', ''),
        ('IVE', 'ELEVEN', ''),
        ('WOODZ', 'Feel Like', 'OO-LI'),
        ('B.I', 'MIDNIGHT BLUE', ''),
        ('Wonho', 'Open Mind', 'Love Synonym #2 : Open Mind'),
        ('KEY', 'Bad Love', 'Bad Love - The 1st Mini Album'),
        ('Taemin', 'Advice', 'Advice - The 1st Mini Album'),
        ('Rosé', 'On The Ground', ''),
        ('LISA', 'LALISA', 'LALISA'),
        ('Sunmi', "You can't sit with us", ''),
        ('Lee Hi', 'H.S.K.T.', '4 ONLY'),
        ('Lee Hi', 'Only', '4 ONLY'),
        ('Melomance', 'You & I', 'The Cafe'),
        ('Red Velvet', 'Queendom', 'Queendom - The 6th Mini Album'),
        ('TWICE', 'The Feels', ''),
        ('Weeekly', 'After School', 'We play'),
        ('fromis_9', 'WE GO', '9 WAY TICKET'),
        ('LOONA', 'Paint the Town', '[&]'),
        ('Dreamcatcher', 'MAISON', 'Same Thing In Different Way'),
        ('NCT U', "Universe (Let's Play Ball)", 'Universe - The 3rd Album'),
        ('Super Junior', 'Mango', 'The Renaissance'),
        ('EXO', "Don't fight the feeling", ''),
        ('Kai', 'Mmmh', 'KAI - The 1st Mini Album'),
        ('Baekhyun', 'Bambi', 'Bambi - The 3rd Mini Album'),
        ('MONSTA X', 'One Day', ''),
        ('Purple Kiss', 'Zombie', ''),
        ('TRI.BE', 'RUB-A-DUM', ''),
        ('woo!ah!', 'Purple', ''),
        ('LIGHTSUM', 'Vivace', 'Into The Light AD MOMENTUM'),
        ('Coldplay & BTS', 'My Universe', ''),
        ('Jeon Somi', 'DUMB DUMB', 'DUMB DUMB'),
        ('Golden Child', 'Burn It', 'GGUM'),
        ('AB6IX', 'CHERRY', ''),
        ('Epik High', 'Rosario', 'Epik High Is Here 上 (Part 1)'),
        ('GWSN', 'Like It Like This', ''),
        ('Secret Number', 'Like It Like It', ''),
        ('ONF', 'Beautiful Beautiful', 'City of ONF'),
        ('SF9', 'Tear Drop', 'Tear Drop'),
        ('BTOB', 'Outsider', 'Outsider'),
        ("NU'EST", 'INSIDE OUT', 'The 2nd Album'),
        ('ONEWE', 'BEAUTIFUL', 'Planet Nine : VOYAGER'),
        ('A.C.E', 'Higher', ''),
        ('CRAVITY', 'My Turn', 'HIDEOUT: REMEMBER WHO WE ARE - PT.2'),
        ('Mirae', 'VROOM VROOM', ''),
        ('TREASURE', 'Beautiful', 'THE FIRST STEP : TREASURE EFFECT'),
        ('STAYC', "I'll Be There", 'Stereotype'),
        ('STAYC', 'Same Same', 'Stereotype'),
        ('ITZY', 'Swipe', 'Crazy in Love'),
        ('TWICE', 'Moonlight', 'Formula of Love - O+T=<3'),
        ('aespa', 'aenergy', 'Savage - The 1st Mini Album'),
        ('aespa', 'Illusion', 'Savage - The 1st Mini Album'),
        ('NCT 127', 'Favorite (Vampire)', 'Favorite - The 3rd Album Repackage'),
        ('NCT DREAM', 'Hello Future', 'Hello Future - The 1st Single Album'),
        ('Stray Kids', 'Christmas EveL', 'Christmas EveL'),
        ('ATEEZ', 'Eternal Sunshine', 'ZERO : FEVER Part.2'),
        ('ENHYPEN', 'Tamed-Dashed', 'DIMENSION : DILEMMA'),
        ('ENHYPEN', 'Fever', 'BORDER : CARNIVAL'),
        ('THE BOYZ', 'The Stealer', 'THE STEALER'),
        ('Dreamcatcher', 'BEcause', 'Special Edition Album [Summer Holiday]'),
        ('Weeekly', 'Zig Zag', 'We play'),
        ('PENTAGON', 'Do or Not', 'LOVE or HATE'),
        ('OH MY GIRL', 'Real Love', 'Real Love'),
        ('Mamamoo', 'Where Are We Now', 'WAW'),
        ('Mamamoo', 'AYA', 'Travel'),
        ('CHUNG HA', 'PLAY', 'Querencia'),
        ('CHUNG HA', 'Killing Me', 'Querencia'),
        ('Kang Daniel', 'Antidote', 'The Answer'),
        ('TXT', 'Anti-Romantic', 'The Chaos Chapter: FIGHT OR ESCAPE'),
        ('woo!ah!', 'Rollercoaster', 'Rollercoaster'),
        ('TRI.BE', 'WE ARE YOUNG', 'WE ARE YOUNG'),
        ('Cherry Bullet', 'Love in Space', 'Love in Space'),
        ('Rocket Punch', 'Fiore', 'Fiore'),
        ('BVNDIT', 'Venom', 'Re-Original'),
        ('DRIPPIN', 'The One', 'Villain'),
        ('CLASS:y', 'CLASS IS OVER', 'CLASS IS OVER'),
        ('VIVIZ', 'BOP BOP!', 'Beam of Prism'),
        ('H1-KEY', 'Athletic Girl', 'H1-KEY'),
        ('LIGHTSUM', 'ALIVE', 'Into The Light AD MOMENTUM'),
        ('PURPLE KISS', '7HEAVEN', 'Geekyland'),
        ('STAYC', 'Beautiful Monster', 'We Need Love'),
        ('ENHYPEN', 'Future Perfect (Pass the MIC)', 'MANIFESTO : DAY 1'),
        ('THE BOYZ', 'WHISPER', 'BE AWARE'),
        ('SF9', 'Scream', 'THE WAVE OF9'),
        ('PENTAGON', "Feelin' Like", 'IN:VITE U'),
        ('ONEUS', 'Bring it on', 'TRICKSTER'),
        ('TEMPEST', "Can't Stop Shining", 'THE 2nd Mini Album : SHINING UP'),
        ('Xdinary Heroes', 'Knock Down', 'Troubleshooting'),
        ('KARD', 'Ring The Alarm', 'Re: KARD'),
        ('SECRET NUMBER', 'Love, Maybe', 'DOXIT'),
        ('NewJeans', 'Cookie', 'NewJeans'),
        ('NewJeans', 'Hurt', 'NewJeans'),
        ('LE SSERAFIM', 'Blue Flame', 'FEARLESS'),
        ('Kep1er', 'WA DA DA', 'FIRST IMPACT'),
        ('NMIXX', 'O.O', 'AD MOMENTUM'),
        ('NMIXX', 'DICE', 'ENTWURF'),
        ('Jeon Somi', 'Fast Forward', 'Fast Forward'),
        ('WOODZ', 'I Hate You', 'OO-LI'),
        ('Zico', 'Freak', 'Grown Ups'),
        ('Zico', 'New thing', 'Street Man Fighter Original Vol.3'),
        ('Lim Young Woong', 'If We Ever Meet Again', ''),
        ('Melomance', 'Love, Maybe', 'Romance Express'),
        ('10CM', 'Spring Snow', '4.3'),
        ('Davichi', 'First Winter', ''),
        ('Crush', 'Rush Hour', ''),
        ('BIBI', 'BIBI Vengeance', 'Lowlife Princess - Noir'),
        ('Jessi', 'Gum', ''),
        ('PSY', 'That That', 'PSY 9th'),
        ('BIG Naughty', 'Beyond Love (Feat. 10CM)', 'Love Game'),
        ('J-Hope', '= (Equal Sign)', 'Jack In The Box'),
        ('Jimin', 'With you', 'Our Blues Pt. 5'),
        ('fromis_9', 'DM', 'Midnight Guest'),
        ('Dreamcatcher', 'VISION', 'Apocalypse : Save us'),
        ('LOONA', 'Flip That', 'Flip That'),
        ('OH MY GIRL', 'Dolphin', 'Real Love'),
        ('MAMAMOO', 'Illicit love', 'MIC ON'),
        ('MAMAMOO', 'Giddy', 'MIC ON'),
        ('WJSN', 'Last Sequence', 'Sequence'),
        ('Apink', 'Dilemma', 'HORN'),
        ('Brave Girls', 'Pool Party', 'Summer Queen'),
        ('VIVIZ', 'LOVEADE', 'Summer Vibe'),
        ('H1-KEY', 'Rose Blossom', 'Rose Blossom'),
        ('LIGHTSUM', 'Honey or Spice', 'Honey or Spice'),
        ('TREASURE', 'MOVE', 'REBOOT'),
        ('THE BOYZ', 'ROAR', 'THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August'),
        ('ATEEZ', 'BOUNCY (K-HOT CHILI PEPPERS)', 'THE WORLD EP.2 : OUTLAW'),
        ('ONEUS', 'Same Scent', 'MALUS'),
        ('TEMPEST', 'Voyage', 'ON and ON'),
        ('Xdinary Heroes', 'Break the Brake', 'Overload'),
        ('KARD', 'ICKY', 'ICKY'),
        ('Weeekly', 'Vroom Vroom', 'ColoRise'),
        ('SECRET NUMBER', 'Toxic', 'DOXIT'),
        ('TRI.BE', 'Diamond', 'Diamond'),
        ('Cherry Bullet', 'POW!', 'Cherry Dash'),
        ('Rocket Punch', 'BOOM', 'BOOM'),
        ('DRIPPIN', 'One Kind', 'Villain - The Zero'),
        ('CLASS:y', 'Tick Tick Bomb', 'Day&Night'),
        ('YENA', 'Good Morning', 'Good Morning'),
        ('WOODZ', 'Drowning', 'OO-LI'),
        ('RIIZE', 'Get A Guitar', 'Get A Guitar'),
        ('RIIZE', 'Talk Saxy', 'Talk Saxy'),
        ('BOYNEXTDOOR', 'One and Only', 'WHO!'),
        ('BOYNEXTDOOR', 'But Sometimes', 'WHO!'),
        ('ZEROBASEONE', 'In Bloom', 'YOUTH IN THE SHADE'),
        ('ZEROBASEONE', 'Crush', 'YOUTH IN THE SHADE'),
        ('NCT U', 'Baggy Jeans', 'Golden Age - The 4th Album'),
        ('NCT DOJAEJUNG', 'Perfume', 'Perfume - The 1st Mini Album'),
        ('SHINee', 'HARD', 'HARD - The 8th Album'),
        ('EXO', 'Cream Soda', 'EXIST - The 7th Album'),
        ('P1Harmony', "Killin' It", "Killin' It"),
        ('CRAVITY', 'Groovy', 'SUN WAVE : UNDER THE SUNLIGHT'),
        ('BABYMONSTER', 'Batter Up', ''),
        ('BABYMONSTER', 'Stuck In The Middle', ''),
        ('KISS OF LIFE', 'Shhh', 'Shhh'),
        ('STAYC', 'Cheeky Icy Thang', '…l'),
        ('MAMAMOO+', 'Dangdang', 'Two Rabbits'),
        ('MAMAMOO+', 'GGBB', 'Two Rabbits'),
        ('Hwa Sa', 'I Love My Body', 'I Love My Body'),
        ('Sunmi', 'Stranger', 'STRANGER'),
        ('Heize', "Fallin'", "Fallin'"),
        ('10CM', 'To Reach You', '4.3'),
        ('BIBI', 'Lowkey', 'Lowkey'),
        ('ITZY', 'None of My Business', 'KILL MY DOUBT'),
    ],
    2022: [
        ('BTS', 'Yet To Come', 'Proof'),
        ('BLACKPINK', 'Pink Venom', ''),
        ('BLACKPINK', 'Shut Down', 'BORN PINK'),
        ('NewJeans', 'Attention', 'NewJeans'),
        ('NewJeans', 'Hype Boy', 'NewJeans'),
        ('NewJeans', 'Ditto', "NewJeans 'OMG'"),
        ('(G)-IDLE', 'TOMBOY', 'I NEVER DIE'),
        ('(G)-IDLE', 'Nxde', 'I love'),
        ('IVE', 'LOVE DIVE', 'LOVE DIVE'),
        ('IVE', 'After LIKE', 'After LIKE'),
        ('aespa', 'Girls', 'Girls - The 2nd Mini Album'),
        ('aespa', "Life's Too Short", "Life's Too Short"),
        ('BIGBANG', 'Still Life', ''),
        ('Stray Kids', 'MANIAC', 'ODDINARY'),
        ('Stray Kids', 'CASE 143', 'MAXIDENT'),
        ('NCT DREAM', 'Glitch Mode', 'Glitch Mode - The 2nd Album'),
        ('NCT DREAM', 'Beatbox', 'Beatbox - The 2nd Album Repackage'),
        ('SEVENTEEN', 'HOT', 'Face the Sun'),
        ('SEVENTEEN', '_WORLD', 'Sector 17'),
        ('LE SSERAFIM', 'FEARLESS', 'FEARLESS'),
        ('LE SSERAFIM', 'ANTIFRAGILE', 'ANTIFRAGILE'),
        ('J-Hope', 'Arson', 'Jack In The Box'),
        ('J-Hope', 'More', 'Jack In The Box'),
        ('Taeyang', 'VIBE', ''),
        ('STAYC', 'RUN2U', 'RUN2U'),
        ('ITZY', 'SNEAKERS', 'CHECKMATE'),
        ('ITZY', 'Cheshire', 'CHESHIRE'),
        ('TWICE', 'Talk that Talk', 'BETWEEN 1&2'),
        ('Red Velvet', 'Feel My Rhythm', 'The ReVe Festival 2022 - Feel My Rhythm'),
        ('Red Velvet', 'Birthday', 'The ReVe Festival 2022 - Birthday'),
        ('Kep1er', 'WA DA DA', 'FIRST IMPACT'),
        ('Kep1er', 'Up!', 'Girls Planet - Kepler : THE SECOND MINI ALBUM'),
        ('TREASURE', 'DARARI', 'THE SECOND STEP : CHAPTER ONE'),
        ('ENHYPEN', 'Polaroid Love', 'DIMENSION : ANSWER'),
        ('TXT', 'Good Boy Gone Bad', "minisode 2: Thursday's Child"),
        ('TXT', 'Sugar Rush Ride', 'The Name Chapter: TEMPTATION'),
        ('ATEEZ', 'Guerrilla', 'THE WORLD EP.1 : MOVEMENT'),
        ('NMIXX', 'O.O', 'AD MOMENTUM'),
        ('NMIXX', 'DICE', 'ENTWURF'),
        ('CLASS:y', 'SHUT DOWN', 'Day&Night'),
        ('Jeon Somi', 'Fast Forward', 'Fast Forward'),
        ('WOODZ', 'I Hate You', 'OO-LI'),
        ('Zico', 'Freak', 'Grown Ups'),
        ('Zico', 'New thing', 'Street Man Fighter Original Vol.3'),
        ('Lim Young Woong', 'If We Ever Meet Again', ''),
        ('Lim Young Woong', 'Trust in Me', 'IM HERO'),
        ('Melomance', 'Love, Maybe', 'Romance Express'),
        ('10CM', 'Spring Snow', '4.3'),
        ('Davichi', 'First Winter', ''),
        ('Crush', 'Rush Hour', ''),
        ('BIBI', 'BIBI Vengeance', 'Lowlife Princess - Noir'),
        ('BIBI', 'KAZINO', 'Lowlife Princess - Noir'),
        ('Jessi', 'Gum', ''),
        ('PSY', 'That That', 'PSY 9th'),
        ('BIG Naughty', 'Beyond Love (Feat. 10CM)', 'Love Game'),
        ('J-Hope', '= (Equal Sign)', 'Jack In The Box'),
        ('Jimin', 'With you', 'Our Blues Pt. 5'),
        ('fromis_9', 'DM', 'Midnight Guest'),
        ('Dreamcatcher', 'VISION', 'Apocalypse : Save us'),
        ('LOONA', 'Flip That', 'Flip That'),
        ('OH MY GIRL', 'Dolphin', 'Real Love'),
        ('MAMAMOO', 'Illicit love', 'MIC ON'),
        ('MAMAMOO', 'Giddy', 'MIC ON'),
        ('WJSN', 'Last Sequence', 'Sequence'),
        ('Apink', 'Dilemma', 'HORN'),
        ('Brave Girls', 'Pool Party', 'Summer Queen'),
        ('VIVIZ', 'BOP BOP!', 'Beam of Prism'),
        ('VIVIZ', 'LOVEADE', 'Summer Vibe'),
        ('H1-KEY', 'Athletic Girl', 'H1-KEY'),
        ('LIGHTSUM', 'ALIVE', 'Into The Light AD MOMENTUM'),
        ('PURPLE KISS', '7HEAVEN', 'Geekyland'),
        ('STAYC', 'Beautiful Monster', 'We Need Love'),
        ('ENHYPEN', 'Future Perfect (Pass the MIC)', 'MANIFESTO : DAY 1'),
        ('THE BOYZ', 'WHISPER', 'BE AWARE'),
        ('SF9', 'Scream', 'THE WAVE OF9'),
        ('PENTAGON', "Feelin' Like", 'IN:VITE U'),
        ('ONEUS', 'Bring it on', 'TRICKSTER'),
        ('TEMPEST', 'Bad News', 'ON and ON'),
        ('TEMPEST', "Can't Stop Shining", 'THE 2nd Mini Album : SHINING UP'),
        ('Xdinary Heroes', 'Happy Death Day', 'Overload'),
        ('Xdinary Heroes', 'Knock Down', 'Troubleshooting'),
        ('KARD', 'Ring The Alarm', 'Re: KARD'),
        ('NCT 127', '2 Baddies', '2 Baddies - The 4th Album'),
        ('NCT DREAM', 'Candy', 'Candy - Winter Special Mini Album'),
        ('MONSTA X', 'Beautiful Liar', 'THE DREAMING'),
        ('woo!ah!', 'Rollercoaster', 'Rollercoaster'),
        ('SECRET NUMBER', 'Love, Maybe', 'DOXIT'),
        ('TRI.BE', 'WE ARE YOUNG', 'WE ARE YOUNG'),
        ('Cherry Bullet', 'Love in Space', 'Love in Space'),
        ('Rocket Punch', 'Fiore', 'Fiore'),
        ('BVNDIT', 'Venom', 'Re-Original'),
        ('DRIPPIN', 'The One', 'Villain'),
        ('NewJeans', 'Cookie', 'NewJeans'),
        ('NewJeans', 'Hurt', 'NewJeans'),
        ('BLACKPINK', 'Typa Girl', 'BORN PINK'),
        ('BLACKPINK', 'Yeah Yeah Yeah', 'BORN PINK'),
        ('Billlie', 'GingaMingaYo (the strange world)', 'the Billage of perception: chapter two'),
        ('YENA', 'SMARTPHONE', 'SMARTPHONE'),
        ('CLASS:y', 'CLASS IS OVER', 'CLASS IS OVER'),
        ('H1-KEY', 'Rose Blossom', 'Rose Blossom'),
        ('LIGHTSUM', 'Honey or Spice', 'Honey or Spice'),
        ('TREASURE', 'MOVE', 'REBOOT'),
        ('THE BOYZ', 'ROAR', 'THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August'),
        ('ATEEZ', 'BOUNCY (K-HOT CHILI PEPPERS)', 'THE WORLD EP.2 : OUTLAW'),
        ('ONEUS', 'Same Scent', 'MALUS'),
        ('TEMPEST', 'Voyage', 'ON and ON'),
        ('Xdinary Heroes', 'Break the Brake', 'Overload'),
        ('KARD', 'ICKY', 'ICKY'),
        ('Weeekly', 'Vroom Vroom', 'ColoRise'),
        ('SECRET NUMBER', 'Toxic', 'DOXIT'),
        ('TRI.BE', 'Diamond', 'Diamond'),
        ('Cherry Bullet', 'POW!', 'Cherry Dash'),
        ('Rocket Punch', 'BOOM', 'BOOM'),
        ('DRIPPIN', 'One Kind', 'Villain - The Zero'),
        ('CLASS:y', 'Tick Tick Bomb', 'Day&Night'),
        ('YENA', 'Good Morning', 'Good Morning'),
        ('WOODZ', 'Drowning', 'OO-LI'),
        ('RIIZE', 'Get A Guitar', 'Get A Guitar'),
        ('RIIZE', 'Talk Saxy', 'Talk Saxy'),
        ('BOYNEXTDOOR', 'One and Only', 'WHO!'),
        ('BOYNEXTDOOR', 'But Sometimes', 'WHO!'),
        ('ZEROBASEONE', 'In Bloom', 'YOUTH IN THE SHADE'),
        ('ZEROBASEONE', 'Crush', 'YOUTH IN THE SHADE'),
        ('NCT U', 'Baggy Jeans', 'Golden Age - The 4th Album'),
        ('NCT DOJAEJUNG', 'Perfume', 'Perfume - The 1st Mini Album'),
        ('SHINee', 'HARD', 'HARD - The 8th Album'),
        ('EXO', 'Cream Soda', 'EXIST - The 7th Album'),
        ('P1Harmony', "Killin' It", "Killin' It"),
        ('CRAVITY', 'Groovy', 'SUN WAVE : UNDER THE SUNLIGHT'),
        ('BABYMONSTER', 'Batter Up', ''),
        ('BABYMONSTER', 'Stuck In The Middle', ''),
        ('KISS OF LIFE', 'Shhh', 'Shhh'),
        ('STAYC', 'Cheeky Icy Thang', '…l'),
        ('MAMAMOO+', 'Dangdang', 'Two Rabbits'),
        ('MAMAMOO+', 'GGBB', 'Two Rabbits'),
        ('Hwa Sa', 'I Love My Body', 'I Love My Body'),
        ('Sunmi', 'Stranger', 'STRANGER'),
        ('Heize', "Fallin'", "Fallin'"),
        ('10CM', 'To Reach You', '4.3'),
        ('BIBI', 'Lowkey', 'Lowkey'),
        ('ITZY', 'None of My Business', 'KILL MY DOUBT'),
        ('MAMAMOO', 'MIC ON', 'MIC ON'),
        ('LE SSERAFIM', 'Blue Flame', 'FEARLESS'),
        ('NMIXX', 'Love Me Like This', 'expérgo'),
        ('NMIXX', 'Dash', 'Fe3O4: BREAK'),
    ],
    2023: [
        ('TWICE', 'Moonlight Sunrise', 'MOONLIGHT SUNRISE'),
        ('NewJeans', 'Super Shy', 'Get Up'),
        ('NewJeans', 'ETA', 'Get Up'),
        ('NewJeans', 'Cool With You', 'Get Up'),
        ('NewJeans', 'OMG', "NewJeans 'OMG'"),
        ('IVE', 'I AM', "I've IVE"),
        ('IVE', 'Kitsch', "I've IVE"),
        ('IVE', 'Baddie', "I'VE MINE"),
        ('IVE', 'Off The Record', "I'VE MINE"),
        ('(G)-IDLE', 'Queencard', 'I feel'),
        ('(G)-IDLE', 'I DO', 'I feel'),
        ('(G)-IDLE', 'I Want That', 'I feel'),
        ('aespa', 'Spicy', 'MY WORLD - The 3rd Mini Album'),
        ('aespa', 'Drama', 'Drama - The 4th Mini Album'),
        ('aespa', 'Better Things', 'Better Things'),
        ('Jungkook', 'Seven', ''),
        ('Jungkook', '3D', ''),
        ('Jungkook', 'Standing Next to You', 'GOLDEN'),
        ('Fifty Fifty', 'Cupid', 'The Beginning'),
        ('AKMU', 'Love Lee', 'Love Lee'),
        ('LE SSERAFIM', 'UNFORGIVEN', 'UNFORGIVEN'),
        ('LE SSERAFIM', "Eve, Psyche & The Bluebeard's wife", 'UNFORGIVEN'),
        ('LE SSERAFIM', 'Perfect Night', 'Perfect Night'),
        ('Stray Kids', 'S-Class', '★★★★★ (5-STAR)'),
        ('Stray Kids', 'LALALALA', '★★★★★ (5-STAR)'),
        ('SEVENTEEN', 'Super', 'FML'),
        ('SEVENTEEN', 'God of Music', 'SEVENTEENTH HEAVEN'),
        ('NCT 127', 'Fact Check', 'Fact Check - The 5th Album'),
        ('NCT DREAM', 'ISTJ', 'ISTJ - The 3rd Album'),
        ('TXT', 'Chasing That Feeling', 'The Name Chapter: FREEFALL'),
        ('ENHYPEN', 'Bite Me', 'DARK BLOOD'),
        ('ENHYPEN', 'Sweet Venom', 'ORANGE BLOOD'),
        ('STAYC', 'Teddy Bear', 'Teddy Bear'),
        ('STAYC', 'Bubble', 'TEENFRESH'),
        ('ITZY', 'CAKE', 'KILL MY DOUBT'),
        ('ITZY', 'BORN TO BE', 'BORN TO BE'),
        ('TWICE', 'SET ME FREE', 'READY TO BE'),
        ('TWICE', 'I GOT YOU', 'With YOU-th'),
        ('Red Velvet', 'Chill Kill', 'Chill Kill - The 3rd Album'),
        ('BLACKPINK', 'The Girls', ''),
        ('Jisoo', 'Flower', 'ME'),
        ('Jisoo', 'All Eyes On Me', 'ME'),
        ('Jimin', 'Like Crazy', 'FACE'),
        ('Jimin', 'Set Me Free Pt.2', 'FACE'),
        ('V', 'Love Me Again', 'Layover'),
        ('V', 'Slow Dancing', 'Layover'),
        ('J-Hope', 'on the street', ''),
        ('Taeyang', 'Shoong! (feat. LISA of BLACKPINK)', 'Down to Earth'),
        ('Lim Young Woong', 'Do or Die', 'IM HERO'),
        ('NMIXX', 'Love Me Like This', 'expérgo'),
        ('NMIXX', 'Dash', 'Fe3O4: BREAK'),
        ('Kep1er', 'Giddy', 'Girls Planet - Kepler : THE 3rd Mini Album'),
        ('Kep1er', 'Back to the City', 'Girls Planet - Kepler : THE 5th Mini Album'),
        ('Billlie', 'EUNOIA', 'the Billage of perception: chapter three'),
        ('VIVIZ', 'PULL UP', 'VarioUS'),
        ('fromis_9', 'Menow', 'Unlock My World'),
        ('Dreamcatcher', 'BON VOYAGE', 'Apocalypse : Follow us'),
        ('OH MY GIRL', 'Summer Comes', 'Golden Hourglass'),
        ('H1-KEY', 'Rose Blossom', 'Rose Blossom'),
        ('LIGHTSUM', 'Honey or Spice', 'Honey or Spice'),
        ('TREASURE', 'MOVE', 'REBOOT'),
        ('THE BOYZ', 'ROAR', 'THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August'),
        ('ATEEZ', 'BOUNCY (K-HOT CHILI PEPPERS)', 'THE WORLD EP.2 : OUTLAW'),
        ('ONEUS', 'Same Scent', 'MALUS'),
        ('TEMPEST', 'Voyage', 'ON and ON'),
        ('Xdinary Heroes', 'Break the Brake', 'Overload'),
        ('KARD', 'ICKY', 'ICKY'),
        ('Weeekly', 'Vroom Vroom', 'ColoRise'),
        ('SECRET NUMBER', 'Toxic', 'DOXIT'),
        ('TRI.BE', 'Diamond', 'Diamond'),
        ('Cherry Bullet', 'POW!', 'Cherry Dash'),
        ('Rocket Punch', 'BOOM', 'BOOM'),
        ('DRIPPIN', 'One Kind', 'Villain - The Zero'),
        ('CLASS:y', 'Tick Tick Bomb', 'Day&Night'),
        ('YENA', 'Good Morning', 'Good Morning'),
        ('WOODZ', 'Drowning', 'OO-LI'),
        ('RIIZE', 'Get A Guitar', 'Get A Guitar'),
        ('RIIZE', 'Talk Saxy', 'Talk Saxy'),
        ('BOYNEXTDOOR', 'One and Only', 'WHO!'),
        ('BOYNEXTDOOR', 'But Sometimes', 'WHO!'),
        ('ZEROBASEONE', 'In Bloom', 'YOUTH IN THE SHADE'),
        ('ZEROBASEONE', 'Crush', 'YOUTH IN THE SHADE'),
        ('NCT U', 'Baggy Jeans', 'Golden Age - The 4th Album'),
        ('NCT DOJAEJUNG', 'Perfume', 'Perfume - The 1st Mini Album'),
        ('SHINee', 'HARD', 'HARD - The 8th Album'),
        ('EXO', 'Cream Soda', 'EXIST - The 7th Album'),
        ('P1Harmony', "Killin' It", "Killin' It"),
        ('CRAVITY', 'Groovy', 'SUN WAVE : UNDER THE SUNLIGHT'),
        ('BABYMONSTER', 'Batter Up', ''),
        ('BABYMONSTER', 'Stuck In The Middle', ''),
        ('KISS OF LIFE', 'Shhh', 'Shhh'),
        ('KISS OF LIFE', 'Sugarcoat (NATTY Solo)', 'Shhh'),
        ('STAYC', 'Cheeky Icy Thang', '…l'),
        ('MAMAMOO+', 'Dangdang', 'Two Rabbits'),
        ('MAMAMOO+', 'GGBB', 'Two Rabbits'),
        ('Hwa Sa', 'I Love My Body', 'I Love My Body'),
        ('Sunmi', 'Stranger', 'STRANGER'),
        ('Heize', "Fallin'", "Fallin'"),
        ('10CM', 'To Reach You', '4.3'),
        ('BIBI', 'Lowkey', 'Lowkey'),
        ('ITZY', 'None of My Business', 'KILL MY DOUBT'),
        ('Fifty Fifty', 'Cupid (Twin Version)', 'The Beginning'),
        ('Xdinary Heroes', 'PLUTO', 'Troubleshooting'),
        ('KARD', 'CAKE', 'Where To Now? (Part 1 : Yellow Light)'),
        ('SECRET NUMBER', "Don't Touch", 'DOXIT'),
        ('CLASS:y', 'Winter Bloom', 'Day&Night'),
        ('DAY6', 'Welcome to the Show', 'Fourever'),
        ('DAY6', 'HAPPY', 'Fourever'),
        ('QWER', 'Discord', "1st Mini Album 'MANITO'"),
        ('QWER', 'T.B.H', "1st Mini Album 'MANITO'"),
        ('tripleS', "Girls' Capitalism", 'ASSEMBLE24'),
        ('tripleS', 'Cherry Talk', 'AESTHETIC'),
        ('UNIS', 'SUPERWOMAN', 'WE UNIS'),
        ('UNIS', 'Curious', 'WE UNIS'),
        ('ARTMS', 'Virtual Angel', 'Dall'),
        ('ARTMS', 'Air', 'Dall'),
        ('WOOAH', 'BLUSH', 'BLUSH'),
        ('CORTIS', 'GO!', 'COLOR OUTSIDE THE LINES'),
        ('CORTIS', 'What You Want', 'COLOR OUTSIDE THE LINES'),
        ('MONSTA X', 'Do What I Want', 'REASON'),
        ('P1Harmony', "It's Alright", "Killin' It"),
        ('CRAVITY', 'Love or Die', 'SUN WAVE : UNDER THE SUNLIGHT'),
        ('SF9', 'BIBORA', 'BIBORA'),
        ('Golden Child', 'Feel Me', 'Feel Me'),
        ('ONEUS', 'Now', 'NOW'),
        ('TEMPEST', 'LIGHTHOUSE', 'TEMPEST Voyage'),
        ('DRIPPIN', 'FIRST LOVE', 'FIRST LOVE'),
        ('Jimin', 'Who', 'MUSE'),
        ('Lisa', 'Rockstar', 'Alter Ego'),
        ('Taeyang', 'Seed', 'Down to Earth'),
        ('AKMU', 'Hero', 'Love Episode'),
        ('Melomance', 'TOY', 'Romance Express'),
        ('Crush', 'Love You With All My Heart', 'wonderlost'),
        ('BIBI', 'Bam Yang Gang', 'Bam Yang Gang'),
        ('PLAVE', 'WAY 4 LUV', 'ASTERUM : Way-Pt.1'),
        ('xikers', 'HOME BOY', 'HOUSE OF TRICKY : Trial And Error'),
        ('KATSEYE', 'Debut', 'Debut'),
        ('KATSEYE', 'Touch', 'Touch'),
        ('WOOAH', 'BLAH BLAH BLAH', 'BLAH BLAH BLAH'),
        ('MEOVV', 'MEOW', 'MEOW'),
        ('MEOVV', 'BODY', 'MEOW'),
        ('BOYNEXTDOOR', 'But I Like You', 'HOW?'),
        ('ZEROBASEONE', 'Good So Bad', 'You had me at HELLO'),
        ('NMIXX', 'See That?', 'Fe3O4: BREAK'),
        ('ENHYPEN', 'No Doubt', 'ROMANCE : UNTOLD'),
        ('TXT', 'Deja Vu (Anxiety)', 'The Name Chapter: FREEFALL'),
        ('PLAVE', 'Dash', 'Caligo Pt.1'),
        ('xikers', 'Red Sun', 'HOUSE OF TRICKY : Trickster'),
        ('FIFTY FIFTY', 'SOS', 'Love Tune'),
        ('JENNIE', 'Seoul City', 'Ruby'),
        ('Rosé', 'drinks or coffee', 'rosie'),
        ('Lisa', 'New Woman', 'Alter Ego'),
        ('Young Posse', 'XX', 'XX'),
        ('KISS OF LIFE', 'Midas Touch', 'Midas Touch'),
        ('(G)-IDLE', 'Wife', '2'),
        ('Taeyeon', 'To. X', 'To. X - The 5th Mini Album'),
        ('IU', 'Holssi', 'The Winning'),
    ],
    2024: [
        ('IVE', 'HEYA', 'IVE EMPATHY'),
        ('aespa', 'Supernova', 'Armageddon - The 1st Album'),
        ('aespa', 'Armageddon', 'Armageddon - The 1st Album'),
        ('(G)-IDLE', 'Super Lady', '2'),
        ('(G)-IDLE', 'Klaxon', 'I SWAY'),
        ('TWS', 'plot twist', "TWS 1st Mini Album 'Sparkling Blue'"),
        ('TWS', 'hey hey hey', "TWS 2nd Mini Album 'SUMMER BEAT!'"),
        ('ILLIT', 'Magnetic', 'SUPER REAL ME'),
        ('ILLIT', 'Lucky Girl Syndrome', 'SUPER REAL ME'),
        ('Jennie', 'Mantra', 'Ruby'),
        ('Rosé & Bruno Mars', 'APT.', ''),
        ('NewJeans', 'How Sweet', 'How Sweet'),
        ('NewJeans', 'Bubble Gum', 'How Sweet'),
        ('LE SSERAFIM', 'Smart', 'CRAZY'),
        ('LE SSERAFIM', 'CRAZY', 'CRAZY'),
        ('LE SSERAFIM', 'EASY', 'EASY'),
        ('Stray Kids', 'Chk Chk Boom', 'ATE'),
        ('Stray Kids', 'Walkin On Water', 'ATE'),
        ('SEVENTEEN', 'MAESTRO', '17 IS RIGHT HERE'),
        ('NCT 127', 'Walk', 'WALK - The 6th Album'),
        ('NCT WISH', 'Wish', 'NCT WISH - The 1st Mini Album'),
        ('NCT DREAM', 'Smoothie', 'DREAM()SCAPE'),
        ('TXT', 'Deja Vu', 'The Name Chapter: FREEFALL'),
        ('ENHYPEN', 'XO (Only If You Say Yes)', 'ROMANCE : UNTOLD'),
        ('STAYC', '1 Thing', '…l'),
        ('ITZY', 'Untouchable', 'BORN TO BE'),
        ('ITZY', 'GOLD', 'GOLD'),
        ('TWICE', 'ONE SPARK', 'With YOU-th'),
        ('TWICE', 'Strategy', 'STRATEGY'),
        ('Red Velvet', 'Cosmic', 'Cosmic - The 1st Mini Album'),
        ('BABYMONSTER', 'Sheesh', 'DRIP'),
        ('BABYMONSTER', 'Forever', 'DRIP'),
        ('BABYMONSTER', 'DRIP', 'DRIP'),
        ('KISS OF LIFE', 'Sticky', 'Sticky'),
        ('KISS OF LIFE', 'Igloo', 'Sticky'),
        ('RIIZE', 'Love 119', 'Love 119'),
        ('RIIZE', 'Impossible', 'Impossible'),
        ('RIIZE', 'Boom Boom Bass', 'RIIZING'),
        ('BOYNEXTDOOR', 'Earth, Wind & Fire', 'HOW?'),
        ('BOYNEXTDOOR', 'Nice Guy', '19.99'),
        ('ZEROBASEONE', 'Feel the POP', 'You had me at HELLO'),
        ('ZEROBASEONE', 'SWEAT', 'You had me at HELLO'),
        ('NMIXX', 'Soñar (Breaker)', 'Fe3O4: BREAK'),
        ('Kep1er', 'Shooting Star', 'Girls Planet - Kepler : THE 6th Mini Album'),
        ('fromis_9', 'Supersonic', 'From'),
        ('Dreamcatcher', 'OOTD', 'VillainS'),
        ('OH MY GIRL', 'Fall in Love', 'Dreamy Resonance'),
        ('H1-KEY', 'Let It Be', 'H1-KEY 4th Mini Album [Lovestruck]'),
        ('TREASURE', 'LAST NIGHT', 'LAST NIGHT'),
        ('THE BOYZ', 'MAESTRO', 'THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound'),
        ('ATEEZ', 'WORK', 'THE WORLD EP.Fin : WILL'),
        ('Jimin', 'Who', 'MUSE'),
        ('NMIXX', 'See That?', 'Fe3O4: BREAK'),
        ('ENHYPEN', 'No Doubt', 'ROMANCE : UNTOLD'),
        ('TXT', 'Deja Vu (Anxiety)', 'The Name Chapter: FREEFALL'),
        ('ILLIT', 'Cherish (My Love)', "I'll Like You"),
        ('TREASURE', 'KING KONG', 'SPECIAL MINI ALBUM [PLEASURE]'),
        ('THE BOYZ', 'Trigger', 'THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound'),
        ('ATEEZ', 'Ice On My Teeth', 'THE WORLD EP.Fin : WILL'),
        ('PLAVE', 'Dash', 'Caligo Pt.1'),
        ('xikers', 'Red Sun', 'HOUSE OF TRICKY : Trickster'),
        ('FIFTY FIFTY', 'SOS', 'Love Tune'),
        ('JENNIE', 'Seoul City', 'Ruby'),
        ('Rosé', 'drinks or coffee', 'rosie'),
        ('Lisa', 'New Woman', 'Alter Ego'),
        ('VIVIZ', 'MANIAC', "The 3rd Mini Album 'VERSUS'"),
        ('fromis_9', 'From', 'From'),
        ('Dreamcatcher', 'Justice', 'VillainS'),
        ('OH MY GIRL', 'Classified', 'Dreamy Resonance'),
        ('STAYC', 'GPT', '…l'),
        ('ITZY', 'Imaginary Friend', 'GOLD'),
        ('TWICE', 'Killing Me Good', 'STRATEGY'),
        ('Red Velvet', 'Sweet Dreams', 'Cosmic - The 1st Mini Album'),
        ('aespa', 'Whiplash', 'Whiplash - The 5th Mini Album'),
        ('aespa', 'Dirty Work', 'Whiplash - The 5th Mini Album'),
        ('DAY6', 'Melt Down', 'Fourever'),
        ('VERIVERY', 'Crazy Like That', 'Lost and Found'),
        ('STAYC', 'Cheeky Icy Thang', '…l'),
        ('ITZY', 'None of My Business', 'KILL MY DOUBT'),
        ('Jungkook', 'Standing Next to You', 'GOLDEN'),
        ('Young Posse', 'XX', 'XX'),
        ('KISS OF LIFE', 'Midas Touch', 'Midas Touch'),
        ('(G)-IDLE', 'Wife', '2'),
        ('Taeyeon', 'To. X', 'To. X - The 5th Mini Album'),
        ('IU', 'Holssi', 'The Winning'),
        ('Melomance', 'Look In Love', 'Look In Love'),
        ('BOYNEXTDOOR', "So let's go see the stars", 'HOW?'),
        ('SEVENTEEN', 'LOVE, MONEY, FAME', 'SEVENTEENTH HEAVEN'),
        ('SEVENTEEN', 'Power of Love', 'SEVENTEENTH HEAVEN'),
        ('NCT WISH', 'Songbird', 'Steady - The 1st Mini Album'),
        ('NCT DREAM', "When I'm With You", 'DREAM()SCAPE'),
        ('NewJeans', 'Supernatural', 'Supernatural'),
        ('LE SSERAFIM', 'Perfect Night', 'Perfect Night'),
        ('IVE', 'Accendio', 'IVE SWITCH'),
        ('N.Flying', 'Bye Bye Bye', 'FLY HIGH PROJECT #5'),
        ('Stray Kids', 'Hall of Fame', 'ATE'),
        ('TWICE', "I Can't Stop Me", 'Eyes wide open'),
        ('GFRIEND', 'Apple', '回:Song of the Sirens'),
        ('Everglow', 'LA DI DA', ''),
        ('ATEEZ', 'Inception', 'ZERO : FEVER Part.1'),
        ('TXT', "Can't You See Me?", 'The Dream Chapter: ETERNITY'),
        ('NCT 127', 'Punch', 'NCT #Resonance Pt. 2'),
        ('TREASURE', 'Boy', 'THE FIRST STEP : CHAPTER ONE'),
        ('TREASURE', 'I Love You', 'THE FIRST STEP : CHAPTER TWO'),
        ('ONEUS', 'LIT', 'LIVED'),
        ('Apink', 'Remind me', 'Selfish'),
        ('BTOB', 'Dear My Lover', 'Be Together'),
        ('Highlight', 'Always You', 'The Blowing'),
        ('INFINITE', 'The Origin', '13egin'),
        ('VIXX', 'G.R.I.T.', 'CONTACT'),
        ('TNX', 'For What', 'For What?'),
        ('TRENDZ', 'Groove', 'New Daybreak'),
        ('WEi', 'Thriller', '2nd Mini Album [Love Syndrome]'),
        ('ONEWE', 'Gravity', 'Planet Nine : VOYAGER'),
        ('ONF', 'Bye My Minimal', 'Bye My Minimal'),
        ('DKZ', 'Harmony', 'Harmony'),
        ('TEMPEST', 'My World', 'TEMPEST Voyage'),
        ('DRIPPIN', 'Home', 'FIRST LOVE'),
        ('CRAVITY', 'Now or Never', 'SUN WAVE : UNDER THE SUNLIGHT'),
        ('P1Harmony', 'More Than Words', "Killin' It"),
        ('SF9', 'Puzzle', 'Sequence'),
        ('Golden Child', 'Cocktail', 'Feel Me'),
        ('tripleS', 'Invincible', 'ASSEMBLE24'),
        ('IVE', 'REBEL HEART', 'IVE EMPATHY'),
        ('LE SSERAFIM', 'HOT', 'HOT'),
        ('Hearts2Hearts', 'The Chase', 'The Chase'),
        ('Hearts2Hearts', 'Butterflies', 'The Chase'),
        ('BOYNEXTDOOR', 'If I Say, I Love You', '19.99'),
        ('NCT WISH', 'Steady', 'Steady - The 1st Mini Album'),
        ('Jisoo', 'Earthquake', 'AMORTAGE'),
        ('Jisoo', 'Your Love', 'AMORTAGE'),
        ('BABYMONSTER', 'WE GO UP', 'WE GO UP'),
        ('BABYMONSTER', 'CLIK CLAK', 'WE GO UP'),
        ('ALLDAY PROJECT', 'FAMOUS', 'FAMOUS'),
        ('MEOVV', 'TOXIC', 'MY EYES OPEN VVIDE'),
        ('MEOVV', 'Hands Up', 'MY EYES OPEN VVIDE'),
        ('ILLIT', 'IYKYK', "I'll Like You"),
        ('TWS', 'OVERDRIVE', "TWS 3rd Mini Album 'TRY WITH US'"),
        ('TWS', 'Countdown!', "TWS 3rd Mini Album 'TRY WITH US'"),
        ('KATSEYE', 'My Way', 'Touch'),
        ('KATSEYE', 'Gameboy', 'Touch'),
        ('Stray Kids', 'CEREMONY', '合 (HOP)'),
        ('Stray Kids', 'Railway (Bang Chan)', '合 (HOP)'),
        ('TWICE', 'Strategy (feat. Megan Thee Stallion)', 'STRATEGY'),
        ('NMIXX', 'Know About Me', 'Fe3O4: FORWARD'),
        ('NMIXX', 'High Horse', 'Fe3O4: FORWARD'),
        ('RIIZE', 'Fly Up', 'ODYSSEY - The 1st Album'),
        ('RIIZE', 'Show Me Love', 'ODYSSEY - The 1st Album'),
        ('ZEROBASEONE', 'Blue', 'You had me at HELLO'),
        ('ENHYPEN', 'Bad Desire (With or Without You)', 'DESIRE : UNLEASH'),
        ('TXT', 'The Star Chapter: SANCTUARY', 'The Star Chapter: SANCTUARY'),
        ('G-DRAGON', 'HOME SWEET HOME (feat. TAEYANG & DAESUNG)', 'Übermensch'),
        ('G-DRAGON', 'TOO BAD (feat. Anderson .Paak)', 'Übermensch'),
        ('G-DRAGON', 'POWER', 'Übermensch'),
        ('G-DRAGON', 'TAKE ME', 'Übermensch'),
        ('BOYNEXTDOOR', 'Lucky Charm', '19.99'),
        ('ILLIT', 'blink', "I'll Like You"),
        ('ALLDAY PROJECT', 'WICKED', 'FAMOUS'),
        ('QWER', 'My Name is Dolores', "1st Mini Album 'MANITO'"),
        ('DAY6', 'The Power of Love', 'Fourever'),
        ('Young Posse', 'Ate That', 'Ate That'),
    ],
    2025: [
        ('IVE', 'FLIRT', 'IVE EMPATHY'),
        ('IVE', 'ACCESS', 'IVE EMPATHY'),
        ('IVE', 'KICK IT', 'IVE EMPATHY'),
        ('LE SSERAFIM', 'Dirty Little Secret', 'HOT'),
        ('LE SSERAFIM', 'Ash', 'HOT'),
        ('Hearts2Hearts', 'Butterflies', 'The Chase'),
        ('Hearts2Hearts', '250901', 'The Chase'),
        ('BOYNEXTDOOR', 'Lucky Charm', '19.99'),
        ('NCT WISH', 'Steady', 'Steady - The 1st Mini Album'),
        ('NCT DREAM', 'Carat Cake', 'DREAM()SCAPE'),
        ('Jisoo', 'Earthquake', 'AMORTAGE'),
        ('Jisoo', 'Your Love', 'AMORTAGE'),
        ('Jisoo', 'Tears', 'AMORTAGE'),
        ('BABYMONSTER', 'WE GO UP', 'WE GO UP'),
        ('BABYMONSTER', 'CLIK CLAK', 'WE GO UP'),
        ('BABYMONSTER', 'Love In My Heart', 'WE GO UP'),
        ('ALLDAY PROJECT', 'FAMOUS', 'FAMOUS'),
        ('ALLDAY PROJECT', 'WICKED', 'FAMOUS'),
        ('MEOVV', 'TOXIC', 'MY EYES OPEN VVIDE'),
        ('MEOVV', 'Hands Up', 'MY EYES OPEN VVIDE'),
        ('MEOVV', 'Drop Off', 'MY EYES OPEN VVIDE'),
        ('ILLIT', 'IYKYK', "I'll Like You"),
        ('ILLIT', 'blink', "I'll Like You"),
        ('TWS', 'OVERDRIVE', "TWS 3rd Mini Album 'TRY WITH US'"),
        ('TWS', 'Countdown!', "TWS 3rd Mini Album 'TRY WITH US'"),
        ('TWS', 'Unbeatable', "TWS 3rd Mini Album 'TRY WITH US'"),
        ('KATSEYE', 'My Way', 'Touch'),
        ('KATSEYE', 'Gameboy', 'Touch'),
        ('KATSEYE', 'Gnarly', 'Touch'),
        ('Stray Kids', 'CEREMONY', '合 (HOP)'),
        ('Stray Kids', 'Railway (Bang Chan)', '合 (HOP)'),
        ('Stray Kids', 'Truman', '合 (HOP)'),
        ('TWICE', 'Strategy (feat. Megan Thee Stallion)', 'STRATEGY'),
        ('TWICE', 'Killing Me Good', 'STRATEGY'),
        ('TWICE', 'The Reason Why', 'STRATEGY'),
        ('ITZY', 'Imaginary Friend', 'GOLD'),
        ('ITZY', 'Escalator', 'GOLD'),
        ('NMIXX', 'Know About Me', 'Fe3O4: FORWARD'),
        ('NMIXX', 'High Horse', 'Fe3O4: FORWARD'),
        ('NMIXX', 'Poke A Hole', 'Fe3O4: FORWARD'),
        ('RIIZE', 'Fly Up', 'ODYSSEY - The 1st Album'),
        ('RIIZE', 'Show Me Love', 'ODYSSEY - The 1st Album'),
        ('RIIZE', 'Passionfruit', 'ODYSSEY - The 1st Album'),
        ('ZEROBASEONE', 'Blue', 'You had me at HELLO'),
        ('ZEROBASEONE', 'Devil Game', 'You had me at HELLO'),
        ('ENHYPEN', 'Bad Desire (With or Without You)', 'DESIRE : UNLEASH'),
        ('ENHYPEN', 'Brought The Heat Back', 'DESIRE : UNLEASH'),
        ('TXT', 'The Star Chapter: SANCTUARY', 'The Star Chapter: SANCTUARY'),
        ('TXT', 'Over The Moon', 'The Star Chapter: SANCTUARY'),
        ('G-DRAGON', 'HOME SWEET HOME (feat. TAEYANG & DAESUNG)', 'Übermensch'),
        ('G-DRAGON', 'TOO BAD (feat. Anderson .Paak)', 'Übermensch'),
        ('G-DRAGON', 'POWER', 'Übermensch'),
        ('G-DRAGON', 'TAKE ME', 'Übermensch'),
        ('G-DRAGON', 'IBELONGIIU', 'Übermensch'),
        ('Rosé', 'number one girl', 'rosie'),
        ('KickFlip', 'Knock Knock', 'Flip Code'),
        ('KickFlip', 'Umm Great Minds', 'Flip Code'),
        ('XLOV', 'I feat. Megan Thee Stallion', 'I'),
        ('XLOV', 'BiiiP', 'I'),
        ('n.SSign', 'Love Potion', 'Love Potion'),
        ('n.SSign', 'Shinyu', 'Love Potion'),
        ('AHOF', 'Gotcha', 'Gotcha'),
        ('AHOF', 'Double Up', 'Gotcha'),
        ('FIFTY FIFTY', 'Starry Night', 'Love Tune'),
        ('PLAVE', 'BBUU!', 'Caligo Pt.1'),
        ('xikers', 'Superpower', 'HOUSE OF TRICKY : Trickster'),
        ('Super Junior', 'Lux', 'Super Junior25'),
        ('SHINee', 'poi', 'poi - The 8th Album'),
        ('WayV', 'She A Wolf', 'Give Me That'),
        ('Young Posse', 'Ate That', 'Ate That'),
        ('KISS OF LIFE', 'Midas Touch', 'Midas Touch'),
        ('(G)-IDLE', 'Wife', '2'),
        ('BOYNEXTDOOR', "So let's go see the stars", 'HOW?'),
        ('Stray Kids', 'Hall of Fame', 'ATE'),
        ('NewJeans', 'Supernatural', 'Supernatural'),
        ('QWER', 'My Name is Dolores', "1st Mini Album 'MANITO'"),
        ('tripleS', 'Invincible', 'ASSEMBLE24'),
        ('DAY6', 'The Power of Love', 'Fourever'),
        ('STAYC', 'Cheeky Icy Thang', '…l'),
        ('ITZY', 'None of My Business', 'KILL MY DOUBT'),
        ('aespa', 'Whiplash', 'Whiplash - The 5th Mini Album'),
        ('aespa', 'Dirty Work', 'Whiplash - The 5th Mini Album'),
        ('ILLIT', 'Cherish (My Love)', "I'll Like You"),
        ('IVE', 'REBEL HEART', 'IVE EMPATHY'),
        ('LE SSERAFIM', 'HOT', 'HOT'),
        ('BOYNEXTDOOR', 'If I Say, I Love You', '19.99'),
        ('NCT 127', 'Intro : Wall', 'WALK - The 6th Album'),
        ('NCT 127', 'Angel Eyes', 'WALK - The 6th Album'),
        ('WayV', 'Give Me That', 'Give Me That'),
        ('Super Junior', 'Show Time', 'Super Junior25'),
        ('TVXQ!', 'Reboot', 'Reboot'),
        ('SHINee', 'The Feeling', 'poi - The 8th Album'),
        ('EXO', 'Hear Me Out', 'EXIST - The 7th Album'),
        ('Wendy', 'Wish You Hell', 'Wish You Hell - The 2nd Mini Album'),
        ('Seulgi', 'Baby, Not Baby', 'HAPPY - Seulgi - The 1st Mini Album'),
        ('Taeyeon', 'Heaven', 'Heaven - The 5th Mini Album'),
        ('Sunmi', 'Balloon in Love', 'Balloon in Love'),
        ('Hwa Sa', 'Good Goodbye', 'Good Goodbye'),
        ('MAMAMOO', 'MY CON', 'MY CON the movie - original soundtrack'),
        ('VIVIZ', 'Shhh!', "The 3rd Mini Album 'VERSUS'"),
        ('Billlie', 'ring ma Bell', 'the Billage of perception: chapter three'),
        ('Geenius', 'Our Style', 'Our Style'),
        ('RESCENE', 'Glow Up', 'Glow Up'),
        ('WAKER', 'Mission', 'Mission'),
        ('NEXZ', 'Riding a Wind', 'Riding a Wind'),
        ('LUN8', 'Wild Heart', 'Wild Heart'),
        ('TIOT', 'KickinIt', 'KickinIt'),
        ('xikers', 'ICONIC', 'HOUSE OF TRICKY : Trickster'),
        ('POW', 'Boyfriend', 'Boyfriend'),
        ('EVNNE', 'Hot Mess', 'Hot Mess'),
        ('AMPERS&ONE', 'Hearts 2 Hearts', 'ONE QUESTION'),
        ('B.D.U', 'TAKEDOWN', 'TAKEDOWN'),
        ('NOWZ', 'Fly To The Youth', 'Fly To The Youth'),
        ('Hearts2Hearts', 'The Chase', 'The Chase'),
        ('Lim Young Woong', 'Vertigo', 'IM HERO 2'),
        ('Jannabi', 'poems, dreams, love', 'poems, dreams, love'),
        ('H1-KEY', 'SEOUL (Such a warm feeling)', 'H1-KEY 4th Mini Album [Lovestruck]'),
        ('idntt', 'Shine', 'Shine'),
        ('MADEIN', 'LA LUNA', 'LA LUNA'),
        ('Geenius', 'Lucky', 'Lucky'),
        ('RESCENE', 'Deja Vu', 'Deja Vu'),
        ('Close Your Eyes', 'Snowy Summer', 'Snowy Summer'),
        ('idntt', 'Lucky', 'Lucky'),
        ('KiiiKiii', 'I Do Me', 'I Do Me'),
        ('HUNTR/X', 'Golden', 'Golden'),
        ('MADEIN', 'UNoUE', 'UNoUE'),
        ('SAY MY NAME', 'WaveWay', 'WaveWay'),
        ('CIGNATURE', 'Sweetie but not too sweet', 'Sweetie but not too sweet'),
    ],
}
