#!/usr/bin/env python3
"""K-pop Top 100 candidate pools (2017-2019). Melon/Gaon/community ordered."""
from __future__ import annotations

CATALOG_2017_2019: dict[int, list[tuple[str, str, str]]] = {
    2017: [
        ('IU', '밤편지', 'Palette'),
        ('IU', 'Palette (feat. G-DRAGON)', 'Palette'),
        ('BTS', '봄날', 'YOU NEVER WALK ALONE'),
        ('BTS', 'DNA', "LOVE YOURSELF 承 'Her'"),
        ('BTS', 'MIC Drop', "LOVE YOURSELF 承 'Her'"),
        ('BTS', 'Not Today', 'YOU NEVER WALK ALONE'),
        ('TWICE', 'KNOCK KNOCK', 'TWICEcoaster : LANE 2'),
        ('TWICE', 'SIGNAL', 'SIGNAL'),
        ('TWICE', 'LIKEY', 'TWICEcoaster : LANE 2'),
        ('TWICE', 'Heart Shaker', 'Merry & Happy'),
        ('Red Velvet', 'Peek-A-Boo', 'Perfect Velvet - The 2nd Album'),
        ('Red Velvet', 'Rookie', 'Rookie - The 4th Mini Album'),
        ('Wanna One', 'Energetic', '1-1=0 (NOTHING WITHOUT YOU)'),
        ('Wanna One', 'Beautiful', '1-1=0 (NOTHING WITHOUT YOU)'),
        ('Wanna One', 'Burn It Up', '1X1=1 (TO BE ZERO)'),
        ('Heize', '너, 구름, 비', '너, 구름, 비'),
        ('Heize', 'Jenga', '너, 구름, 비'),
        ('AKMU', "How can I love the heartbreak, you're the one I love", 'Summer Episode'),
        ('AKMU', '200%', 'PLAY'),
        ('BOL4', 'You(=I)', 'Red Diary Page.1'),
        ('BOL4', 'Way Home', 'Red Diary Page.1'),
        ('Taeyeon', 'Make Me Love You', 'My Voice - The 1st Album'),
        ('Taeyeon', 'I Got Love (feat. Dok2)', 'My Voice - The 1st Album'),
        ('Sunmi', 'Gashina', ''),
        ('Hyuna', 'Babe', ''),
        ('EXO', 'Ko Ko Bop', 'THE WAR - The 4th Album'),
        ('EXO', 'Power', 'THE WAR - The 4th Album'),
        ('BLACKPINK', "As If It's Your Last", ''),
        ('SEVENTEEN', "Don't Wanna Cry", 'Al1'),
        ('SEVENTEEN', 'Clap', 'TEEN, AGE'),
        ('GOT7', 'Never Ever', '7 for 7'),
        ('GOT7', 'You Are', '7 for 7'),
        ("NU'EST W", 'Where You At', 'W, HERE'),
        ('Mamamoo', 'Yes I Am', 'Purple'),
        ('GFRIEND', 'Summer Rain', 'Parallel'),
        ('GFRIEND', 'Love Whisper', 'Parallel'),
        ('Hyukoh', 'Tomboy', '24 : How to find true love and happiness'),
        ('Zico', 'Artist', 'Television'),
        ('Zico', 'Any Song', ''),
        ('Crush', "Don't Forget (feat. Whee In)", ''),
        ('DEAN', 'instagram', '130 Mood : TRBL'),
        ('Lee Hi', 'Breathe', 'SEOULITE'),
        ('Park Hyo Shin', 'Wild Flower', ''),
        ('Urban Zakapa', "I Don't Love You", '02'),
        ('Davichi', 'As Time Goes By', 'As Time Goes By'),
        ('10CM', 'Phonecert', '4.0'),
        ('Melomance', 'Gift', ''),
        ('Standing Egg', 'Old Song', 'Lip'),
        ('SHINee', 'View', 'Odd - The 5th Album'),
        ('SHINee', 'Tell Me What To Do', "The Story of Light 'Epilogue'"),
        ('WINNER', 'REALLY REALLY', 'FATE NUMBER FOR'),
        ('WINNER', 'FOOL', 'FATE NUMBER FOR'),
        ('iKON', 'LOVE SCENARIO', 'Return'),
        ('iKON', 'RUBBER DUCK', 'Return'),
        ('Block B', 'Yesterday', 'Yesterday'),
        ('MONSTA X', 'Dramarama', 'THE CODE'),
        ('VIXX', 'Shangri-La', 'Shangri-La'),
        ('INFINITE', 'Tell Me', '24/7'),
        ('BTOB', 'Movie', "Feel'eM"),
        ('Apink', 'Five', 'Pink UP'),
        ('SISTAR', 'Lonely', 'Lonely'),
        ('EXID', 'DDD', 'Full Moon'),
        ('AOA', 'Excuse Me', "Angel's Knock"),
        ("Girls' Generation", 'Holiday', 'Holiday Night - The 6th Album'),
        ("Girls' Generation", 'All Night', 'Holiday Night - The 6th Album'),
        ('Taeyang', 'So Good', 'WHITE NIGHT'),
        ('PSY', 'New Face', '4X2=8'),
        ('NCT 127', 'Cherry Bomb', 'NCT #127 CHERRY BOMB - The 1st Mini Album'),
        ('NCT DREAM', 'We Young', 'We Young - The 1st Mini Album'),
        ('ASTRO', 'Baby', 'Winter Dream'),
        ('SF9', 'O Sole Mio', 'Breaking Sensation'),
        ('PENTAGON', 'Runaway', 'Pentagon'),
        ('Cosmic Girls', 'Happy', 'HAPPY MOMENT'),
        ('CLC', 'Hobgoblin', 'CRYSTYLE'),
        ('Lovelyz', 'WoW!', "Fallin' in Love"),
        ('OH MY GIRL', 'Secret Garden', 'Secret Garden'),
        ('DIA', 'Will You Go Out With Me', 'LOVE GENERATION'),
        ('Stellar', 'Archangels', 'Sting'),
        ('UP10TION', 'Going Crazy', 'Top Secret'),
        ('Berry Good', "Don't Make Me Cry", 'Very Berry'),
        ('f(x)', 'All Mine', ''),
        ('N.Flying', 'Real Love', 'Love in the FLY'),
        ('CNBLUE', 'Between Us', '7°CN'),
        ('FTISLAND', 'Wind', 'OVER 10 YEARS'),
        ('Super Junior', 'Black Suit', 'PLAY - The 8th Album'),
        ('Teen Top', 'Missing', 'Red Point'),
        ('B.A.P', 'Honeymoon', 'Blue'),
        ('Rain', 'GANG', ''),
        ('Yoon Mi Rae', 'Gemini', 'Gemini'),
        ('Primary', 'When I Was Young', '2'),
        ('Gary', 'Sunrise', '2002'),
        ('Loco', 'Too Much', ''),
        ('San E', 'Me You', ''),
        ('Mad Clown', 'Fire', ''),
        ('Ben', 'Like a Dream', ''),
        ('Punch', 'Stay With Me', ''),
        ('Roy Kim', 'Only Then', ''),
        ('Jung Seung Hwan', 'The Fan', ''),
        ('Huh Gak', 'Spring Rain', ''),
        ('Ailee', 'If You', 'VIVID'),
        ('Son Seung Yeon', 'A Person Like You', ''),
        ('Im Chang Jung', 'Home', ''),
        ('Epik High', 'Sleeping Beauty', 'Shoebox'),
        ('BewhY', 'Forever', ''),
        ('Jessi', 'Gucci', ''),
        ('Hyolyn', 'Blue Moon', 'Xperience'),
        ('Soyou', 'The Night', ''),
        ('K.Will', 'Talk Love', ''),
        ('Chen', 'Everytime', ''),
        ('Baekhyun', 'Dream', ''),
        ('Wonder Girls', 'Why So Lonely', ''),
        ('I.O.I', 'Downpour', 'miss me?'),
        ('NCT U', 'Without You', ''),
        ('VIXX LR', 'Whisper', 'Beautiful Liar'),
        ('XIA', 'Flower', "XIA 4th Album 'XIGNATURE'"),
        ('Gummy', 'You Are My Everything', 'I Wanna Be With You'),
        ('Lee Juck', "Don't Worry", ''),
        ('NCT U', 'From Home', 'Resonance Pt. 1'),
        ('Golden Child', 'DamDaDi', "Golden Child 1st Mini Album 'Gol-Cha!'"),
        ('ONF', 'Complete', 'ONF:MY NAME'),
        ('Dreamcatcher', 'Good Night', 'Nightmare'),
        ('LOONA', 'Love & Live', 'Love & Live'),
        ('WJSN', 'Happy', 'Happy Moment'),
        ('Momoland', 'Wonderful Love', 'Wonderful Love'),
        ('Gfriend', 'Rainbow', 'Parallel'),
        ('Highlight', "Plz Don't Be Sad", 'Can You Feel It?'),
        ('B1A4', "Rollin'", 'This Is Us'),
        ('VAV', 'Flower (You)', 'Under the Moonlight'),
        ('KNK', 'Rain', 'KNK SINGLES COLLECTION 265'),
        ('SF9', 'Still My Lady', 'Breaking Sensation'),
        ('Victon', "I'm Fine", 'Identity'),
        ('P1Harmony', 'Siren', 'DISHARMONY : Stand Out'),
    ],
    2018: [
        ('iKON', 'LOVE SCENARIO', 'Return'),
        ('BTS', 'Fake Love', "LOVE YOURSELF 轉 'Tear'"),
        ('BTS', 'IDOL', "LOVE YOURSELF 結 'Answer'"),
        ('BTS', 'Singularity', "LOVE YOURSELF 轉 'Tear'"),
        ('BLACKPINK', 'DDU-DU DDU-DU', 'SQUARE UP'),
        ('BLACKPINK', 'Forever Young', 'SQUARE UP'),
        ('TWICE', 'What is Love?', 'What is Love?'),
        ('TWICE', 'Dance The Night Away', 'Summer Nights'),
        ('TWICE', 'Yes or Yes', 'YES or YES'),
        ('IU', 'BBIBBI', ''),
        ('IU', 'eight (Prod.&feat. SUGA of BTS)', 'eight'),
        ('Mamamoo', 'Starry Night', 'Yellow Flower'),
        ('Mamamoo', 'Egotistic', 'Red Moon'),
        ('Mamamoo', 'Wind flower', 'Blue;s'),
        ('BOL4', 'Travel', 'Travel'),
        ('BOL4', 'Starlight', 'Travel'),
        ('Red Velvet', 'Bad Boy', 'The Perfect Red Velvet'),
        ('Red Velvet', 'Power Up', 'Summer Magic - Special Mini Album'),
        ('Red Velvet', 'RBB (Really Bad Boy)', 'RBB - The 5th Mini Album'),
        ('Sunmi', 'Heroine', 'Heroine'),
        ('Sunmi', 'Siren', 'WARNING'),
        ('Hyuna', "I'm Not Cool", "I'm Not Cool"),
        ('(G)-IDLE', 'LATATA', 'I am'),
        ('(G)-IDLE', 'HANN (Alone)', 'I am'),
        ('Taeyeon', 'Fine', 'Fine - The 1st Single Album'),
        ('Taeyeon', 'Four Seasons', 'Purpose - The 2nd Studio Album'),
        ('Wanna One', 'Boomerang', '1-1=0 (NOTHING WITHOUT YOU)'),
        ('Wanna One', 'Light', '1-1=0 (NOTHING WITHOUT YOU)'),
        ('SEVENTEEN', 'Oh My!', 'YOU MAKE MY DAY'),
        ('SEVENTEEN', 'Getting Closer', 'YOU MAKE MY DAY'),
        ('GOT7', 'Look', 'Eyes On You'),
        ('GOT7', 'Lullaby', 'Present : YOU'),
        ('Stray Kids', 'District 9', 'I am NOT'),
        ('Stray Kids', 'Hellevator', 'I am NOT'),
        ('NCT 127', 'Regular', 'NCT #127 Regular-Irregular - The 1st Album'),
        ('NCT DREAM', 'We Go Up', 'We Go Up - The 2nd Mini Album'),
        ('EXO', 'Tempo', "Don't Mess Up My Tempo - The 2nd Album"),
        ('EXO', 'Love Shot', 'LOVE SHOT - The Repackage Album'),
        ('SHINee', 'Good Evening', "The Story of Light 'Epilogue'"),
        ('SHINee', 'I Want You', "The Story of Light 'Epilogue'"),
        ('WINNER', 'Everyday', 'EVERYD4Y'),
        ('WINNER', 'Millions', 'EVERYD4Y'),
        ('Lee Hi', 'No One', '24°C'),
        ('Urban Zakapa', 'When We Were Two', '02'),
        ('Davichi', 'Only You', 'Only You'),
        ('Ben', 'From Ben', 'Reality'),
        ('Punch', 'Losing Sleep', ''),
        ('Apink', "I'm So Sick", 'ONE&Six'),
        ('SISTAR', 'Shining Star', 'Lonely'),
        ('GFRIEND', 'Time for the moon night', 'Time for the moon night'),
        ('GFRIEND', 'Sunrise', 'Time for the moon night'),
        ('OH MY GIRL', 'Banana Cha Cha', 'Secret Garden'),
        ('Lovelyz', 'That Day', 'That Day'),
        ('MOMOLAND', 'Bboom Bboom', 'GREAT!'),
        ('MOMOLAND', 'Baam', 'Fun to the World'),
        ('CLC', 'No', 'Amigo'),
        ('Cosmic Girls', 'Dreams Come True', 'Dreams Come True'),
        ('PENTAGON', 'Shine', 'Positive'),
        ('MONSTA X', 'Jealousy', 'THE CONNECT : DEJAVU'),
        ('VIXX', 'Scentist', 'Conception Ker'),
        ('BTOB', 'Only one for me', 'This Is Us'),
        ('Block B', "Don't Leave", 'RECONSTRUCTION'),
        ('ASTRO', 'Crazy Sexy Cool', 'Dream Part.02'),
        ('SF9', 'Mamma Mia!', 'Mamma Mia!'),
        ('Golden Child', 'Lady', 'Miracle'),
        ('Dreamcatcher', 'What', 'Escape the Era'),
        ('LOONA', 'Butterfly', '[X X]'),
        ('WJSN', 'La La Love', 'WJ PLEASE?'),
        ('fromis_9', 'To Heart', 'To. Heart'),
        ('IZ*ONE', 'La Vie en Rose', 'COLOR*IZ'),
        ('IZ*ONE', 'Violeta', 'HEART*IZ'),
        ('Cherry Bullet', 'Q&A', "Let's Play Cherry Bullet"),
        ('Rocket Punch', 'BIM BAM BUM', 'Pink Punch'),
        ('AB6IX', 'Breathe', 'B:COMPLETE'),
        ('CIX', 'Movie Star', 'HELLO Chapter 1. Hello, Stranger'),
        ('EVERGLOW', 'Bon Bon Chocolat', 'Arrival of EVERGLOW'),
        ('TXT', 'Crown', 'The Dream Chapter: STAR'),
        ('ATEEZ', 'Hala Hala', 'TREASURE EP.2 : Zero To One'),
        ('The Boyz', 'Giddy Up', 'The Start'),
        ('KARD', 'Bomb Bomb', 'Bomb Bomb'),
        ('Super Junior', 'Lo Siento', 'REPLAY'),
        ('WayV', 'Regular', 'Take Off'),
        ('NCT U', 'Boss', 'NCT 2018 EMPATHY'),
        ('NCT U', 'Yestoday', 'NCT 2018 EMPATHY'),
        ('Taemin', 'Move', 'Move - The 2nd Mini Album'),
        ('Key', 'One of Those Nights', 'Poet | Artist'),
        ('Hwa Sa', 'Maria', 'Maria'),
        ('TREASURE', 'Going Crazy', 'THE FIRST STEP : CHAPTER ONE'),
        ('CHUNG HA', 'Love U', 'Flourishing'),
        ('Paul Kim', 'Me After You', ''),
        ('Sam Kim', 'Make Up', ''),
        ('Younha', 'Event Horizon', 'UNSTABLE MINDSET'),
        ('Hyukoh', 'Tomboy', '24 : How to find true love and happiness'),
        ('Epik High', 'Born Hater', 'Shoebox'),
        ('Soran', 'The Star', ''),
        ('Colde', 'Your Dog Loves You', ''),
        ('George', "Where's Wool", ''),
        ('Jannabi', 'for lovers who hesitate', 'LEGEND'),
        ('DAY6', 'Shoot Me', 'Shoot Me : Youth Part 1'),
        ('DAY6', 'Sweet Chaos', 'The Book of Us : Entropy'),
        ('N.Flying', 'Oh really?', 'So, 通'),
        ('ONEWE', 'Tag Me (@Me)', 'ONE'),
        ('VERIVERY', 'Thunder', 'Truth or Dare'),
        ('D1CE', 'HATE YOU', 'Wake Up'),
        ('OnlyOneOf', 'libidO', 'Instinct, Part. 1'),
        ('DPR LIVE', 'Martini Blue', 'Coming To You Live'),
        ('Sik-K', 'NEVER END', 'HEADLINER'),
        ('Haon', 'Skrt', 'Travel : Nostalgia'),
        ('Nafla', "You Gon' Need It", 'Natural High'),
        ('K/DA', 'POP/STARS', ''),
        ('BoA', 'Woman', 'ONE SHOT, TWO SHOT'),
        ('Taeyeon', 'Wine', 'Something New - The 3rd Mini Album'),
        ('Hyolyn', 'Say My Name', 'Xperience'),
        ('Sunny Hill', 'Monday to Sunday', 'The Beginning of New Endings'),
        ('Brown Eyed Girls', 'Wonder Woman', 'RE_vive'),
        ('2NE1', 'Goodbye', ''),
        ('Gfriend', 'Time for the moon night', 'Time for the moon night'),
        ('WJSN', 'Dreams Come True', 'Dreams Come True'),
        ('Cosmic Girls', 'La La Love', 'WJ PLEASE?'),
        ('Dreamcatcher', 'Piri', 'The End of Nightmare'),
        ('Rocket Punch', 'Bouncy', 'Blue Punch'),
        ('Cherry Bullet', 'Hands Up', ''),
        ('AB6IX', 'Blind For Love', '6IX SENSE'),
        ('CIX', 'My My', ''),
        ('ATEEZ', 'Answer', 'TREASURE EP.Fin : All To Action'),
        ('TREASURE', 'I Love You', 'THE FIRST STEP : CHAPTER TWO'),
        ('TREASURE', 'MMM', 'THE FIRST STEP : CHAPTER THREE'),
        ('NCT U', 'Make A Wish (Birthday Song)', 'Resonance Pt. 1'),
        ('SuperM', 'Jopping', 'Super One'),
        ('Victon', 'Nostalgia', 'Nostalgia'),
        ('ONF', 'Summer Poem', 'ONF:MY NAME'),
        ('MCND', 'nanana', 'EARTH AGE'),
        ('A.C.E', 'Favorite Boys', 'HIGHER'),
        ('WEi', "Dondododo (Don't Hold Back)", ''),
        ('Im Chang-jung', 'Nothing Like You', ''),
    ],
    2019: [
        ('BTS', 'Boy With Luv', 'MAP OF THE SOUL : PERSONA'),
        ('BTS', 'Make It Right', 'MAP OF THE SOUL : PERSONA'),
        ('IU', 'Blueming', 'Love poem'),
        ('IU', 'Love poem', 'Love poem'),
        ('IU', 'Unlucky', 'Love poem'),
        ('BLACKPINK', 'Kill This Love', ''),
        ('BLACKPINK', "Don't Know What To Do", 'Kill This Love'),
        ('TWICE', 'Fancy', 'Fancy You'),
        ('TWICE', 'Feel Special', 'Feel Special'),
        ('TWICE', 'Breakthrough', 'Breakthrough'),
        ('Mamamoo', 'HIP', ''),
        ('Taeyeon', 'Spark', 'Purpose - The 2nd Studio Album'),
        ('Sunmi', 'LALALAY', 'WARNING'),
        ('Heize', "We don't talk together", "We don't talk together"),
        ('BOL4', 'Work', 'Two Five'),
        ('BOL4', 'Warm', 'Two Five'),
        ('Red Velvet', 'Zimzalabim', 'The ReVe Festival Day 1'),
        ('Red Velvet', 'Umpah Umpah', 'The ReVe Festival Day 2'),
        ('Red Velvet', 'Psycho', "'The ReVe Festival' Finale"),
        ('ITZY', 'WANNABE', ''),
        ('(G)-IDLE', 'Senorita', 'I made'),
        ('(G)-IDLE', 'Uh-Oh', 'I made'),
        ('SEVENTEEN', 'Home', 'An Ode'),
        ('SEVENTEEN', 'Hit', 'An Ode'),
        ('Stray Kids', 'MIROH', 'Clé 1 : MIROH'),
        ('Stray Kids', 'Side Effects', 'Clé 2 : Yellow Wood'),
        ('GOT7', 'Eclipse', 'Spinning Top : Between Security & Insecurity'),
        ('NCT 127', 'Kick It', 'NCT #127 Neo Zone - The 2nd Album'),
        ('NCT DREAM', 'BOOM', 'We Boom - The 3rd Mini Album'),
        ('EXO', 'Obsession', 'OBSESSION - The 6th Album'),
        ('WINNER', 'Ah Yeah', 'WE'),
        ('Davichi', 'Just the Two of Us', 'Just the Two of Us'),
        ('CHUNG HA', 'Snapping', 'Flourishing'),
        ('CHUNG HA', 'Gotta Go', 'Flourishing'),
        ('Kang Daniel', '2U', ''),
        ('Apink', '%%', 'Percent'),
        ('OH MY GIRL', 'The Fifth Season (SSoL)', 'The Fifth Season'),
        ('MOMOLAND', "I'm So Hot", 'Show Me'),
        ('CLC', 'ME', 'No.1'),
        ('MONSTA X', 'Follow', 'FOLLOW : FIND YOU'),
        ('VIXX', 'Parallel', 'Conception Ker'),
        ('INFINITE', 'Why Why', 'Why Why'),
        ('BTOB', 'Blue Moon', "Feel'eM"),
        ('ASTRO', 'All Night', 'All Light'),
        ('SF9', 'RPM', 'RPM'),
        ('fromis_9', 'Fun!', 'FUN FACTORY'),
        ('IZ*ONE', 'FIESTA', 'BLOOM*IZ'),
        ('Super Junior', 'SUPER Clap', 'Timeless'),
        ('Baekhyun', 'Candy', 'Delight - The 4th Mini Album'),
        ("NU'EST", 'Bet Bet', 'The 2nd Album'),
        ('BoA', 'Woman', 'ONE SHOT, TWO SHOT'),
        ('Taeyeon', 'Wine', 'Something New - The 3rd Mini Album'),
        ('Sunny Hill', 'Monday to Sunday', 'The Beginning of New Endings'),
        ('Brown Eyed Girls', 'Wonder Woman', 'RE_vive'),
        ('2NE1', 'Goodbye', ''),
        ('Everglow', 'Adios', 'HUSH'),
        ('K/DA', 'POP/STARS', ''),
        ('Sunmi', 'Gotta Go', 'WARNING'),
        ('iKON', 'Dive', 'NEW KIDS : THE FINAL'),
        ('AKMU', 'Happening', 'HAPPENING'),
        ('Zion.T', 'No Love', ''),
        ('Kim Feel', 'All I Do', ''),
        ('Vibe', 'Vibe', ''),
        ('Davichi', "Changmin's Not Here", ''),
        ('Im Chang-jung', 'Nothing Like You', ''),
        ('NCT 127', 'Superhuman', 'NCT #127 Neo Zone - The 2nd Album'),
        ('Stray Kids', 'Double Knot', 'Clé : LEVANTER'),
        ('Stray Kids', 'Astronaut', 'Clé : LEVANTER'),
        ('GFRIEND', 'Crossroads', '回:Song of the Sirens'),
        ('GFRIEND', 'Tonight', '回:Song of the Sirens'),
        ('Lovelyz', 'Once Upon a Time', 'Once Upon a Time'),
        ('MOMOLAND', 'Thumbs Up', 'Show Me'),
        ('(G)-IDLE', 'LION', 'I made'),
        ('OH MY GIRL', 'Bungee (Fall in Love)', 'The Fifth Season'),
        ('Taemin', 'Want', 'WANT'),
        ('Hyolyn', 'Say My Name', 'Xperience'),
        ('Heize', "We don't talk together (Feat. Giriboy)", "We don't talk together"),
        ('Dreamcatcher', 'Piri', 'The End of Nightmare'),
        ('ATEEZ', 'Answer', 'TREASURE EP.Fin : All To Action'),
        ('PENTAGON', 'Shower of Stars', 'Sum(me:r)'),
        ('Song Haye', 'I Like You', ''),
        ('The Boyz', 'D.D.D', 'Dreamlike'),
        ('ATEEZ', 'Wonderland', 'TREASURE EP.Fin : All To Action'),
        ('WayV', 'Take Off', 'Take Off'),
        ('NCT U', 'Make A Wish (Birthday Song)', 'Resonance Pt. 1'),
        ('SuperM', 'Jopping', 'Super One'),
        ('AB6IX', 'Blind For Love', '6IX SENSE'),
        ('CIX', 'My My', ''),
        ('Rocket Punch', 'Bouncy', 'Blue Punch'),
        ('Cherry Bullet', 'Hands Up', ''),
        ('Hwa Sa', 'Twit', 'Guilty Pleasure'),
        ('Soyou', 'Gotta Go', 'The Night'),
        ('fromis_9', 'Love Bomb', 'Love Bomb'),
    ],
}
