# 2019 풀 보강 — global 유일·발매연도 2019 확정
EXTRA_2019 = [
    ("TXT", "Run Away", "The Dream Chapter: ETERNITY"),
    ("KARD", "Dumb Litty", "KARD 4th Mini Album"),
    ("Cosmic Girls", "La La Love", "WJ PLEASE?"),
    ("Nature", "Some", "Some"),
    ("ONEUS", "Valkyrie", "FLY WITH US"),
    ("Park Ji Hoon", "L.O.V.E", "360°"),
    ("SuperM", "100", "Super One"),
    ("LOONA", "Butterfly", "[#]"),
    ("Lovelyz", "That Day", "Once Upon a Time"),
    ("Golden Child", "Lady", "Re-boot"),
    ("WJSN", "La La Love", "WJ PLEASE?"),
    ("IZ*ONE", "Violeta", "Violeta"),
    ("Cherry Bullet", "Q&A", "Let's Play Cherry Bullet"),
    ("DPR LIVE", "Martini Blue", "Coming To You Live"),
    ("Sik-K", "NEVER END", "HEADLINER"),
    ("Loona", "Butterfly", "[#]"),
    ("Gfriend", "Time for the moon night", "Time for the moon night"),
    ("MOMOLAND", "Thumbs Up", "Show Me"),
    ("OH MY GIRL", "Bungee (Fall in Love)", "The Fifth Season"),
    ("GFRIEND", "Crossroads", "回:Song of the Sirens"),
    ("KNK", "Rain", "KNK SINGLES COLLECTION 265"),
    ("WJSN", "Dream the Dream", "Dream the Dream"),
    ("ONEUS", "Tag", "FLY WITH US"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Born Hater", "Shoebox"),
    ("Hyukoh", "Tomboy", "24 : How to find true love and happiness"),
    ("Haon", "Skrt", "Travel : Nostalgia"),
    ("Nafla", "You Gon' Need It", "Natural High"),
    ("Sik-K", "NEVER END", "HEADLINER"),
    ("Lee Hi", "No One", "No One"),
    ("BOL4", "Travel", "Travel"),
    ("Woody", "Fire up", "Fire up"),
    ("Nature", "Groove", "Some"),
]
