#!/usr/bin/env python3
"""Fix under-filled year pools by filtering against global selections and adding spares."""
from __future__ import annotations

import importlib.util
import re
import unicodedata
from collections import Counter
from pathlib import Path

GEN = Path(__file__).parent
MAX_PER = 2
TARGET = 100


def track_key(artist: str, title: str) -> str:
    def norm(s: str) -> str:
        s = unicodedata.normalize("NFKC", s or "").lower().replace("&", " and ")
        s = re.sub(r"\bfeat\.?\b|\bft\.?\b|\bfeaturing\b", " ", s)
        s = re.sub(r"[^\w\s가-힣]+", " ", s, flags=re.UNICODE)
        return re.sub(r"\s+", " ", s).strip()

    return f"{norm(artist)}|{norm(title)}"


def load(path: Path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def finalize(raw: dict[int, list], upto: int) -> tuple[dict[int, list], set[str]]:
    seen: set[str] = set()
    out: dict[int, list] = {}
    for year in range(2015, upto + 1):
        pool = raw.get(year, [])
        result: list[tuple[str, str, str]] = []
        ac: Counter[str] = Counter()
        for artist, title, album in pool:
            if len(result) >= TARGET:
                break
            if ac[artist] >= MAX_PER:
                continue
            k = track_key(artist, title)
            if k in seen:
                continue
            result.append((artist, title, album))
            ac[artist] += 1
            seen.add(k)
        out[year] = result
    return out, seen


def dedupe_pool(pool: list[tuple[str, str, str]]) -> list[tuple[str, str, str]]:
    seen: set[tuple[str, str]] = set()
    out: list[tuple[str, str, str]] = []
    for t in pool:
        k = (t[0], t[1])
        if k in seen:
            continue
        seen.add(k)
        out.append(t)
    return out


def append_unique(pool: list, extras: list, global_seen: set[str]) -> None:
    have = {(a, b) for a, b, _ in pool}
    for artist, title, album in extras:
        k = track_key(artist, title)
        if (artist, title) in have or k in global_seen:
            continue
        pool.append((artist, title, album))
        have.add((artist, title))


# ── spare candidates (release year = pool year) ──────────────────────────────
SPARE_2019 = [
    ("NCT 127", "Superhuman", "NCT #127 Neo Zone - The 2nd Album"),
    ("Stray Kids", "Double Knot", "Clé : LEVANTER"),
    ("Stray Kids", "Astronaut", "Clé : LEVANTER"),
    ("GFRIEND", "Crossroads", "回:Song of the Sirens"),
    ("GFRIEND", "Tonight", "回:Song of the Sirens"),
    ("Lovelyz", "Once Upon a Time", "Once Upon a Time"),
    ("MOMOLAND", "Thumbs Up", "Show Me"),
    ("(G)-IDLE", "LION", "I made"),
    ("Sunmi", "LALALAY", "WARNING"),
    ("OH MY GIRL", "Bungee (Fall in Love)", "The Fifth Season"),
    ("TREASURE", "Going Crazy", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "Come Back Home", "THE FIRST STEP : CHAPTER ONE"),
    ("NCT U", "Make A Wish (Birthday Song)", "Resonance Pt. 1"),
    ("SuperM", "Jopping", "Super One"),
    ("SuperM", "100", "Super One"),
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("aespa", "Black Mamba", ""),
    ("DAY6", "Zombie", "The Book of Us : The Demon"),
    ("DAY6", "Love me or Leave me", "The Book of Us : The Demon"),
    ("BoA", "Better", "Better - The 10th Album"),
    ("NU'EST", "Bet Bet", "The 2nd Album"),
    ("TWICE", "Breakthrough", "Breakthrough"),
    ("TWICE", "Feel Special", "Feel Special"),
    ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
    ("Taeyeon", "Spark", "Purpose - The 2nd Studio Album"),
    ("IU", "Unlucky", "Love poem"),
    ("BTS", "Make It Right", "MAP OF THE SOUL : PERSONA"),
    ("Stray Kids", "Side Effects", "Clé 2 : Yellow Wood"),
    ("SEVENTEEN", "Hit", "An Ode"),
    ("NCT DREAM", "BOOM", "We Boom - The 3rd Mini Album"),
    ("EXO", "Obsession", "OBSESSION - The 6th Album"),
    ("iKON", "Dive", "NEW KIDS : THE FINAL"),
    ("WINNER", "Ah Yeah", "WE"),
    ("GOT7", "Eclipse", "Spinning Top : Between Security & Insecurity"),
    ("Apink", "%%", "Percent"),
    ("BTOB", "Blue Moon", "Feel'eM"),
    ("VIXX", "Parallel", "Conception Ker"),
    ("INFINITE", "Why Why", "Why Why"),
    ("ASTRO", "All Night", "All Light"),
    ("SF9", "RPM", "RPM"),
    ("Block B", "Don't Leave", "RECONSTRUCTION"),
    ("CLC", "ME", "No.1"),
    ("MOMOLAND", "I'm So Hot", "Show Me"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Born Hater", "Shoebox"),
    ("K/DA", "POP/STARS", ""),
    ("Sunny Hill", "Monday to Sunday", "The Beginning of New Endings"),
    ("Brown Eyed Girls", "Wonder Woman", "RE_vive"),
    ("2NE1", "Goodbye", ""),
    ("Taeyeon", "Wine", "Something New - The 3rd Mini Album"),
    ("Hwa Sa", "Maria", "Maria"),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Crush", "None", ""),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("BewhY", "Day Day", ""),
    ("Mad Clown", "Fire", ""),
    ("Huh Gak", "Spring Rain", ""),
    ("Ailee", "If You", "VIVID"),
    ("Son Seung Yeon", "A Person Like You", ""),
    ("Jung Seung Hwan", "The Fan", ""),
    ("Rain", "GANG", ""),
    ("PSY", "New Face", "4X2=8"),
    ("Teen Top", "Missing", "Red Point"),
    ("B.A.P", "Honeymoon", "Blue"),
    ("CNBLUE", "Between Us", "7°CN"),
    ("FTISLAND", "Wind", "OVER 10 YEARS"),
    ("N.Flying", "Real Love", "Love in the FLY"),
    ("KNK", "Rain", "KNK SINGLES COLLECTION 265"),
    ("Standing Egg", "Confession", "With Her"),
    ("Roy Kim", "Only Then", ""),
    ("Primary", "When I Was Young", "2"),
    ("Gary", "Sunrise", "2002"),
    ("Im Chang Jung", "Home", ""),
    ("Davichi", "Just the Two of Us", "Just the Two of Us"),
    ("Urban Zakapa", "When We Were Two", "02"),
    ("Melomance", "Gift", ""),
    ("DEAN", "instagram", "130 Mood : TRBL"),
    ("Zico", "Any Song", ""),
    ("AKMU", "Nakka", "NEXT EPISODE"),
    ("Heize", "HAPPEN", "HAPPEN"),
    ("Mamamoo", "Where Are We Now", "WAW"),
    ("Sunmi", "Pporappippam", ""),
    ("Zion.T", "No Love", ""),
    ("Kim Feel", "All I Do", ""),
    ("Vibe", "Vibe", ""),
    ("Punch", "Through the Night", ""),
    ("Lee Hi", "Hola", ""),
    ("Park Hyo Shin", "Good Goodbye", ""),
    ("Jessi", "NUNU NANA", ""),
    ("Kang Daniel", "Who U Are", ""),
    ("10CM", "Your Mountain", "4.3"),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("Davichi", "Changmin's Not Here", ""),
    ("Baekhyun", "Candy", "Delight - The 4th Mini Album"),
    ("AKMU", "Happening", "HAPPENING"),
    ("IU", "Blueming", "Love poem"),
    ("Mamamoo", "HIP", ""),
    ("ITZY", "WANNABE", ""),
    ("Kang Daniel", "2U", ""),
    ("Heize", "We don't talk together", "We don't talk together"),
    ("BTS", "ON", "Map of the Soul : 7"),
    ("BTS", "Black Swan", "Map of the Soul : 7"),
]

SPARE_2020 = [
    ("BTS", "Dynamite", ""),
    ("BTS", "Life Goes On", "BE"),
    ("BTS", "Blue & Grey", "BE"),
    ("BTS", "Telepathy", "BE"),
    ("BTS", "ON", "Map of the Soul : 7"),
    ("BTS", "Black Swan", "Map of the Soul : 7"),
    ("BLACKPINK", "How You Like That", ""),
    ("BLACKPINK", "Lovesick Girls", "THE ALBUM"),
    ("TWICE", "More & More", ""),
    ("TWICE", "Cry For Me", ""),
    ("TWICE", "Fanfare", "Fanfare"),
    ("ITZY", "Not Shy", ""),
    ("(G)-IDLE", "Oh my god", ""),
    ("(G)-IDLE", "Dumdi Dumdi", "Dumdi Dumdi"),
    ("Jessi", "What Type of X", "What Type of X"),
    ("Sunmi", "Pporappippam", ""),
    ("Seventeen", "Left & Right", "Heng:garæ"),
    ("Seventeen", "Home;run", "Heng:garæ"),
    ("Seventeen", "Fear", "Heng:garæ"),
    ("Stray Kids", "God's Menu", "GO LIVE"),
    ("Stray Kids", "Back Door", "IN LIFE"),
    ("NCT DREAM", "Ridin'", "Reload"),
    ("NCT 127", "Kick Back", "NCT RESONANCE Pt. 2"),
    ("NCT U", "90's Love", "Resonance Pt. 1"),
    ("NCT U", "Work It", "Resonance Pt. 1"),
    ("ATEEZ", "THANXX", "ZERO : FEVER Part.1"),
    ("TXT", "Blue Hour", "minisode1 : Blue Hour"),
    ("TXT", "Eternally", "The Dream Chapter: ETERNITY"),
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("Everglow", "Dun Dun Dance", ""),
    ("IZ*ONE", "Secret Story of the Swan", "Oneiric Diary"),
    ("IZ*ONE", "Panorama", ""),
    ("Taeyeon", "Dear Me", ""),
    ("Woo", "Guilty", "Guilty"),
    ("GOT7", "Last Piece", "Breath of Love : Last Piece"),
    ("GOT7", "Breath", "Breath of Love : Last Piece"),
    ("GFRIEND", "MAGO", "回:Walpurgis Night"),
    ("CLC", "HELICOPTER", "HELICOPTER"),
    ("MOMOLAND", "Ready or Not", "Ready or Not"),
    ("Highlight", "Not The End", "The Blowing"),
    ("ASTRO", "One", "ONEWE"),
    ("Golden Child", "ONE (Lucid Dream)", "Golden Age"),
    ("LOONA", "Star", "[#]"),
    ("DAY6", "Zombie", "The Book of Us : The Demon"),
    ("DAY6", "Love me or Leave me", "The Book of Us : The Demon"),
    ("BoA", "Better", "Better - The 10th Album"),
    ("aespa", "Black Mamba", ""),
    ("NU'EST", "I Don't Care", "The 2nd Album"),
    ("BTOB", "Missing You", "Feel'eM"),
    ("WINNER", "Hold", "Remember"),
    ("SHINee", "Don't Call Me", "Don't Call Me"),
    ("Super Junior", "2YA2YAO!", "TIMELESS"),
    ("WayV", "Turn Back Time", ""),
    ("The Boyz", "Reveal", "Reveal"),
    ("KARD", "GUNSHOT", ""),
    ("SF9", "Summer Breeze", "Summer Breeze"),
    ("AB6IX", "The Answer", "VIVID"),
    ("Bvndit", "Jungle", "Carnival"),
    ("TREASURE", "Orange", "THE FIRST STEP : CHAPTER TWO"),
    ("TREASURE", "Beautiful", "THE FIRST STEP : TREASURE EFFECT"),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("woo!ah!", "Purple", ""),
    ("TRI.BE", "RUB-A-DUM", ""),
    ("PURPLE KISS", "Zombie", ""),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
    ("ENHYPEN", "Let Me In (Crown)", "BORDER : CARNIVAL"),
    ("VIXX", "Revolution", "CONTACT"),
    ("INFINITE", "Why Why", "Why Why"),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("Weki Meki", "Dazzle Dazzle", ""),
    ("Apink", "Dumhdurum", "Look"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Why Not?", "[12:00]"),
    ("LOONA", "So What", "[#]"),
    ("CHUNG HA", "Stay Tonight", "Querencia"),
    ("CHUNG HA", "Bicycle", "Querencia"),
    ("STAYC", "So Bad", "Star To A Young Culture"),
    ("CIX", "My My", ""),
    ("Secret Number", "Who Dis?", ""),
    ("Cherry Bullet", "Hands Up", ""),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("Victon", "Nostalgia", "Nostalgia"),
    ("SuperM", "Tiger Inside", "Super One"),
    ("SuperM", "Jopping", "Super One"),
    ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
    ("Mamamoo", "Dingga", ""),
    ("Kang Daniel", "Who U Are", ""),
    ("Punch", "Through the Night", ""),
    ("Kim Feel", "All I Do", ""),
    ("Lee Hi", "Hola", ""),
    ("Park Hyo Shin", "Good Goodbye", ""),
    ("Vibe", "Vibe", ""),
    ("Paul Kim", "Me After You", ""),
    ("Sam Kim", "Make Up", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("N.Flying", "Oh really?", "So, 通"),
    ("ONEWE", "Tag Me (@Me)", "ONE"),
    ("VERIVERY", "Thunder", "Truth or Dare"),
    ("D1CE", "HATE YOU", "Wake Up"),
    ("OnlyOneOf", "libidO", "Instinct, Part. 1"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Crush", "None", ""),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Hwa Sa", "Maria", "Maria"),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Standing Egg", "Old Song", "Lip"),
    ("10CM", "Your Mountain", "4.3"),
    ("Ben", "From Ben", "Reality"),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("Weeekly", "Tag Me (@Me)", "We are"),
    ("SECRET NUMBER", "Who Dis?", ""),
    ("ONEUS", "LIT", "LIVED"),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("BVNDIT", "Jungle", "Carnival"),
    ("TREASURE", "MMM", "THE FIRST STEP : CHAPTER THREE"),
    ("TREASURE", "My Treasure", "THE FIRST STEP"),
    ("TREASURE", "Going Crazy", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "Come Back Home", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
    ("TREASURE", "Boy", "THE FIRST STEP : CHAPTER ONE"),
    ("STAYC", "ASAP", ""),
    ("Brave Girls", "Rollin'", ""),
    ("ENHYPEN", "Drunk-Dazed", "BORDER : CARNIVAL"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Everglow", "LA DI DA", ""),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("Victon", "Nostalgia", "Nostalgia"),
    ("Cherry Bullet", "Hands Up", ""),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("woo!ah!", "Purple", ""),
    ("TRI.BE", "RUB-A-DUM", ""),
    ("PURPLE KISS", "Zombie", ""),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
    ("AKMU", "Happening", "HAPPENING"),
    ("Baekhyun", "Candy", "Delight - The 4th Mini Album"),
    ("Zion.T", "No Love", ""),
    ("Heize", "We don't talk together", "We don't talk together"),
    ("Davichi", "Changmin's Not Here", ""),
    ("Zico", "Any Song", ""),
    ("IU", "Blueming", "Love poem"),
    ("Mamamoo", "HIP", ""),
    ("ITZY", "WANNABE", ""),
    ("Kang Daniel", "2U", ""),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Everglow", "LA DI DA", ""),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("Apink", "Dumhdurum", "Look"),
    ("Weki Meki", "Dazzle Dazzle", ""),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("CIX", "My My", ""),
    ("SuperM", "Tiger Inside", "Super One"),
    ("WINNER", "Remember", ""),
    ("SHINee", "Don't Call Me", "Don't Call Me"),
    ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
]

SPARE_2021 = [
    ("STAYC", "I'll Be There", "Stereotype"),
    ("STAYC", "Same Same", "Stereotype"),
    ("ITZY", "Swipe", "Crazy in Love"),
    ("TWICE", "Moonlight", "Formula of Love - O+T=<3"),
    ("aespa", "aenergy", "Savage - The 1st Mini Album"),
    ("aespa", "Illusion", "Savage - The 1st Mini Album"),
    ("NCT 127", "Favorite (Vampire)", "Favorite - The 3rd Album Repackage"),
    ("NCT DREAM", "Hello Future", "Hello Future - The 1st Single Album"),
    ("Stray Kids", "Christmas EveL", "Christmas EveL"),
    ("ATEEZ", "Eternal Sunshine", "ZERO : FEVER Part.2"),
    ("ENHYPEN", "Tamed-Dashed", "DIMENSION : DILEMMA"),
    ("ENHYPEN", "Fever", "BORDER : CARNIVAL"),
    ("THE BOYZ", "The Stealer", "THE STEALER"),
    ("Dreamcatcher", "BEcause", "Special Edition Album [Summer Holiday]"),
    ("Weeekly", "Zig Zag", "We play"),
    ("PENTAGON", "Do or Not", "LOVE or HATE"),
    ("OH MY GIRL", "Real Love", "Real Love"),
    ("CHUNG HA", "PLAY", "Querencia"),
    ("CHUNG HA", "Killing Me", "Querencia"),
    ("Kang Daniel", "Antidote", "The Answer"),
    ("TXT", "Anti-Romantic", "The Chaos Chapter: FIGHT OR ESCAPE"),
    ("TREASURE", "Beautiful", "THE FIRST STEP : TREASURE EFFECT"),
    ("Mirae", "VROOM VROOM", ""),
    ("GWSN", "Like It Like This", ""),
    ("Secret Number", "Like It Like It", ""),
    ("ONF", "Beautiful Beautiful", "City of ONF"),
    ("SF9", "Tear Drop", "Tear Drop"),
    ("BTOB", "Outsider", "Outsider"),
    ("NU'EST", "INSIDE OUT", "The 2nd Album"),
    ("ONEWE", "BEAUTIFUL", "Planet Nine : VOYAGER"),
    ("A.C.E", "Higher", ""),
    ("CRAVITY", "My Turn", "HIDEOUT: REMEMBER WHO WE ARE - PT.2"),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("AB6IX", "CHERRY", ""),
    ("Golden Child", "Burn It", "GGUM"),
    ("Coldplay & BTS", "My Universe", ""),
    ("Jeon Somi", "DUMB DUMB", "DUMB DUMB"),
    ("woo!ah!", "Purple", ""),
    ("TRI.BE", "RUB-A-DUM", ""),
    ("Purple Kiss", "Zombie", ""),
    ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("SECRET NUMBER", "Who Dis?", ""),
    ("BVNDIT", "Jungle", "Carnival"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("TRI.BE", "WE ARE YOUNG", "WE ARE YOUNG"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "Fiore", "Fiore"),
    ("BVNDIT", "Venom", "Re-Original"),
    ("DRIPPIN", "The One", "Villain"),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("CLASS:y", "CLASS IS OVER", "CLASS IS OVER"),
    ("VIVIZ", "BOP BOP!", "Beam of Prism"),
    ("H1-KEY", "Athletic Girl", "H1-KEY"),
    ("LIGHTSUM", "ALIVE", "Into The Light AD MOMENTUM"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("STAYC", "Beautiful Monster", "We Need Love"),
    ("ENHYPEN", "Future Perfect (Pass the MIC)", "MANIFESTO : DAY 1"),
    ("THE BOYZ", "WHISPER", "BE AWARE"),
    ("SF9", "Scream", "THE WAVE OF9"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("ONEUS", "Bring it on", "TRICKSTER"),
    ("TEMPEST", "Can't Stop Shining", "THE 2nd Mini Album : SHINING UP"),
    ("Xdinary Heroes", "Knock Down", "Troubleshooting"),
    ("KARD", "Ring The Alarm", "Re: KARD"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("SECRET NUMBER", "Love, Maybe", "DOXIT"),
    ("TRI.BE", "WE ARE YOUNG", "WE ARE YOUNG"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "Fiore", "Fiore"),
    ("BVNDIT", "Venom", "Re-Original"),
    ("DRIPPIN", "The One", "Villain"),
    ("NewJeans", "Cookie", "NewJeans"),
    ("NewJeans", "Hurt", "NewJeans"),
    ("LE SSERAFIM", "Blue Flame", "FEARLESS"),
    ("Kep1er", "WA DA DA", "FIRST IMPACT"),
    ("NMIXX", "O.O", "AD MOMENTUM"),
    ("NMIXX", "DICE", "ENTWURF"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("Jeon Somi", "Fast Forward", "Fast Forward"),
    ("WOODZ", "I Hate You", "OO-LI"),
    ("Zico", "Freak", "Grown Ups"),
    ("Zico", "New thing", "Street Man Fighter Original Vol.3"),
    ("Lim Young Woong", "If We Ever Meet Again", ""),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("10CM", "Spring Snow", "4.3"),
    ("Davichi", "First Winter", ""),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "BIBI Vengeance", "Lowlife Princess - Noir"),
    ("Jessi", "Gum", ""),
    ("PSY", "That That", "PSY 9th"),
    ("BIG Naughty", "Beyond Love (Feat. 10CM)", "Love Game"),
    ("J-Hope", "= (Equal Sign)", "Jack In The Box"),
    ("Jimin", "With you", "Our Blues Pt. 5"),
    ("fromis_9", "DM", "Midnight Guest"),
    ("Dreamcatcher", "VISION", "Apocalypse : Save us"),
    ("LOONA", "Flip That", "Flip That"),
    ("OH MY GIRL", "Dolphin", "Real Love"),
    ("MAMAMOO", "Illicit love", "MIC ON"),
    ("MAMAMOO", "Giddy", "MIC ON"),
    ("WJSN", "Last Sequence", "Sequence"),
    ("Apink", "Dilemma", "HORN"),
    ("Brave Girls", "Pool Party", "Summer Queen"),
    ("VIVIZ", "LOVEADE", "Summer Vibe"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("SHINee", "HARD", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
]

SPARE_2022 = [
    ("NewJeans", "Cookie", "NewJeans"),
    ("NewJeans", "Hurt", "NewJeans"),
    ("J-Hope", "= (Equal Sign)", "Jack In The Box"),
    ("NCT DREAM", "Candy", "Candy - Winter Special Mini Album"),
    ("BLACKPINK", "Typa Girl", "BORN PINK"),
    ("BLACKPINK", "Yeah Yeah Yeah", "BORN PINK"),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("CLASS:y", "CLASS IS OVER", "CLASS IS OVER"),
    ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
    ("J-Hope", "More", "Jack In The Box"),
    ("J-Hope", "Arson", "Jack In The Box"),
    ("Jimin", "With you", "Our Blues Pt. 5"),
    ("fromis_9", "DM", "Midnight Guest"),
    ("Dreamcatcher", "VISION", "Apocalypse : Save us"),
    ("LOONA", "Flip That", "Flip That"),
    ("OH MY GIRL", "Dolphin", "Real Love"),
    ("MAMAMOO", "Illicit love", "MIC ON"),
    ("MAMAMOO", "Giddy", "MIC ON"),
    ("WJSN", "Last Sequence", "Sequence"),
    ("Apink", "Dilemma", "HORN"),
    ("Brave Girls", "Pool Party", "Summer Queen"),
    ("VIVIZ", "LOVEADE", "Summer Vibe"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("SHINee", "HARD", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("Xdinary Heroes", "Knock Down", "Troubleshooting"),
    ("TEMPEST", "Can't Stop Shining", "THE 2nd Mini Album : SHINING UP"),
    ("ENHYPEN", "Future Perfect (Pass the MIC)", "MANIFESTO : DAY 1"),
    ("THE BOYZ", "WHISPER", "BE AWARE"),
    ("SF9", "Scream", "THE WAVE OF9"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("ONEUS", "Bring it on", "TRICKSTER"),
    ("KARD", "Ring The Alarm", "Re: KARD"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("SECRET NUMBER", "Love, Maybe", "DOXIT"),
    ("TRI.BE", "WE ARE YOUNG", "WE ARE YOUNG"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "Fiore", "Fiore"),
    ("BVNDIT", "Venom", "Re-Original"),
    ("DRIPPIN", "The One", "Villain"),
    ("VIVIZ", "BOP BOP!", "Beam of Prism"),
    ("H1-KEY", "Athletic Girl", "H1-KEY"),
    ("LIGHTSUM", "ALIVE", "Into The Light AD MOMENTUM"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("STAYC", "Beautiful Monster", "We Need Love"),
    ("CLASS:y", "CLASS IS OVER", "CLASS IS OVER"),
    ("Jeon Somi", "Fast Forward", "Fast Forward"),
    ("WOODZ", "I Hate You", "OO-LI"),
    ("Zico", "Freak", "Grown Ups"),
    ("Zico", "New thing", "Street Man Fighter Original Vol.3"),
    ("Lim Young Woong", "If We Ever Meet Again", ""),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("10CM", "Spring Snow", "4.3"),
    ("Davichi", "First Winter", ""),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "BIBI Vengeance", "Lowlife Princess - Noir"),
    ("Jessi", "Gum", ""),
    ("PSY", "That That", "PSY 9th"),
    ("BIG Naughty", "Beyond Love (Feat. 10CM)", "Love Game"),
    ("MAMAMOO", "MIC ON", "MIC ON"),
    ("STAYC", "RUN2U", "RUN2U"),
    ("ITZY", "SNEAKERS", "CHECKMATE"),
    ("ITZY", "Cheshire", "CHESHIRE"),
    ("TWICE", "Talk that Talk", "BETWEEN 1&2"),
    ("Red Velvet", "Feel My Rhythm", "The ReVe Festival 2022 - Feel My Rhythm"),
    ("Red Velvet", "Birthday", "The ReVe Festival 2022 - Birthday"),
    ("Kep1er", "Up!", "Girls Planet - Kepler : THE SECOND MINI ALBUM"),
    ("TREASURE", "DARARI", "THE SECOND STEP : CHAPTER ONE"),
    ("ENHYPEN", "Polaroid Love", "DIMENSION : ANSWER"),
    ("TXT", "Good Boy Gone Bad", "minisode 2: Thursday's Child"),
    ("TXT", "Sugar Rush Ride", "The Name Chapter: TEMPTATION"),
    ("ATEEZ", "Guerrilla", "THE WORLD EP.1 : MOVEMENT"),
    ("NMIXX", "O.O", "AD MOMENTUM"),
    ("NMIXX", "DICE", "ENTWURF"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("Jeon Somi", "Fast Forward", "Fast Forward"),
    ("WOODZ", "I Hate You", "OO-LI"),
    ("Zico", "Freak", "Grown Ups"),
    ("Zico", "New thing", "Street Man Fighter Original Vol.3"),
    ("Lim Young Woong", "Trust in Me", "IM HERO"),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("10CM", "Spring Snow", "4.3"),
    ("Davichi", "First Winter", ""),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "BIBI Vengeance", "Lowlife Princess - Noir"),
    ("BIBI", "KAZINO", "Lowlife Princess - Noir"),
    ("Jessi", "Gum", ""),
    ("PSY", "That That", "PSY 9th"),
    ("BIG Naughty", "Beyond Love (Feat. 10CM)", "Love Game"),
    ("J-Hope", "Arson", "Jack In The Box"),
    ("Jimin", "With you", "Our Blues Pt. 5"),
    ("fromis_9", "DM", "Midnight Guest"),
    ("Dreamcatcher", "VISION", "Apocalypse : Save us"),
    ("LOONA", "Flip That", "Flip That"),
    ("OH MY GIRL", "Dolphin", "Real Love"),
    ("WJSN", "Last Sequence", "Sequence"),
    ("Apink", "Dilemma", "HORN"),
    ("Brave Girls", "Pool Party", "Summer Queen"),
    ("VIVIZ", "BOP BOP!", "Beam of Prism"),
    ("VIVIZ", "LOVEADE", "Summer Vibe"),
    ("H1-KEY", "Athletic Girl", "H1-KEY"),
    ("LIGHTSUM", "ALIVE", "Into The Light AD MOMENTUM"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("STAYC", "Beautiful Monster", "We Need Love"),
    ("ENHYPEN", "Future Perfect (Pass the MIC)", "MANIFESTO : DAY 1"),
    ("THE BOYZ", "WHISPER", "BE AWARE"),
    ("SF9", "Scream", "THE WAVE OF9"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("ONEUS", "Bring it on", "TRICKSTER"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("TEMPEST", "Can't Stop Shining", "THE 2nd Mini Album : SHINING UP"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("Xdinary Heroes", "Knock Down", "Troubleshooting"),
    ("KARD", "Ring The Alarm", "Re: KARD"),
    ("NCT 127", "2 Baddies", "2 Baddies - The 4th Album"),
    ("MONSTA X", "Beautiful Liar", "THE DREAMING"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("SECRET NUMBER", "Love, Maybe", "DOXIT"),
    ("TRI.BE", "WE ARE YOUNG", "WE ARE YOUNG"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "Fiore", "Fiore"),
    ("BVNDIT", "Venom", "Re-Original"),
    ("DRIPPIN", "The One", "Villain"),
    ("NewJeans", "Cookie", "NewJeans"),
    ("NewJeans", "Hurt", "NewJeans"),
    ("LE SSERAFIM", "Blue Flame", "FEARLESS"),
    ("Kep1er", "WA DA DA", "FIRST IMPACT"),
    ("NMIXX", "Love Me Like This", "expérgo"),
    ("NMIXX", "Dash", "Fe3O4: BREAK"),
    ("CLASS:y", "CLASS IS OVER", "CLASS IS OVER"),
    ("Jeon Somi", "Fast Forward", "Fast Forward"),
    ("WOODZ", "I Hate You", "OO-LI"),
    ("Zico", "Freak", "Grown Ups"),
    ("Zico", "New thing", "Street Man Fighter Original Vol.3"),
    ("Lim Young Woong", "If We Ever Meet Again", ""),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("10CM", "Spring Snow", "4.3"),
    ("Davichi", "First Winter", ""),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "BIBI Vengeance", "Lowlife Princess - Noir"),
    ("Jessi", "Gum", ""),
    ("PSY", "That That", "PSY 9th"),
    ("BIG Naughty", "Beyond Love (Feat. 10CM)", "Love Game"),
]

SPARE_2023 = [
    ("NewJeans", "Cool With You", "Get Up"),
    ("NewJeans", "OMG", "NewJeans 'OMG'"),
    ("IVE", "Baddie", "I'VE MINE"),
    ("IVE", "Off The Record", "I'VE MINE"),
    ("(G)-IDLE", "I Want That", "I feel"),
    ("aespa", "Better Things", "Better Things"),
    ("Jungkook", "3D", ""),
    ("Fifty Fifty", "Cupid", "The Beginning"),
    ("LE SSERAFIM", "Perfect Night", "Perfect Night"),
    ("Stray Kids", "LALALALA", "★★★★★ (5-STAR)"),
    ("SEVENTEEN", "God of Music", "SEVENTEENTH HEAVEN"),
    ("ENHYPEN", "Sweet Venom", "ORANGE BLOOD"),
    ("STAYC", "Bubble", "TEENFRESH"),
    ("ITZY", "BORN TO BE", "BORN TO BE"),
    ("TWICE", "I GOT YOU", "With YOU-th"),
    ("BLACKPINK", "The Girls", ""),
    ("Jisoo", "All Eyes On Me", "ME"),
    ("Jimin", "Set Me Free Pt.2", "FACE"),
    ("V", "Slow Dancing", "Layover"),
    ("J-Hope", "on the street", ""),
    ("Taeyang", "Shoong! (feat. LISA of BLACKPINK)", "Down to Earth"),
    ("NMIXX", "Dash", "Fe3O4: BREAK"),
    ("Kep1er", "Back to the City", "Girls Planet - Kepler : THE 5th Mini Album"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("VIVIZ", "PULL UP", "VarioUS"),
    ("fromis_9", "Menow", "Unlock My World"),
    ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
    ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("SHINee", "HARD", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Sugarcoat (NATTY Solo)", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("AKMU", "Love Lee", "Love Lee"),
    ("Fifty Fifty", "Cupid (Twin Version)", "The Beginning"),
    ("Jungkook", "Standing Next to You", "GOLDEN"),
    ("V", "Love Me Again", "Layover"),
    ("Jimin", "Like Crazy", "FACE"),
    ("Jisoo", "Flower", "ME"),
    ("STAYC", "Teddy Bear", "Teddy Bear"),
    ("ITZY", "CAKE", "KILL MY DOUBT"),
    ("TWICE", "SET ME FREE", "READY TO BE"),
    ("Red Velvet", "Chill Kill", "Chill Kill - The 3rd Album"),
    ("NMIXX", "Love Me Like This", "expérgo"),
    ("Kep1er", "Giddy", "Girls Planet - Kepler : THE 3rd Mini Album"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("VIVIZ", "PULL UP", "VarioUS"),
    ("fromis_9", "Menow", "Unlock My World"),
    ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
    ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("SHINee", "HARD", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("UNIS", "Curious", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("ARTMS", "Air", "Dall"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("Jimin", "Who", "MUSE"),
    ("Lisa", "Rockstar", "Alter Ego"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("MEOVV", "MEOW", "MEOW"),
    ("MEOVV", "BODY", "MEOW"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
]

SPARE_2024 = [
    ("LE SSERAFIM", "EASY", "EASY"),
    ("BABYMONSTER", "DRIP", "DRIP"),
    ("RIIZE", "Boom Boom Bass", "RIIZING"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("G-DRAGON", "HOME SWEET HOME (feat. TAEYANG & DAESUNG)", "Übermensch"),
    ("G-DRAGON", "TOO BAD (feat. Anderson .Paak)", "Übermensch"),
    ("G-DRAGON", "POWER", "Übermensch"),
    ("G-DRAGON", "TAKE ME", "Übermensch"),
    ("ILLIT", "Cherish (My Love)", "I'll Like You"),
    ("Jimin", "Who", "MUSE"),
    ("Lisa", "Rockstar", "Alter Ego"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("MEOVV", "MEOW", "MEOW"),
    ("MEOVV", "BODY", "MEOW"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("UNIS", "Curious", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("ARTMS", "Air", "Dall"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("STAYC", "1 Thing", "…l"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("KISS OF LIFE", "Sticky", "Sticky"),
    ("NewJeans", "Bubble Gum", "How Sweet"),
    ("LE SSERAFIM", "Smart", "CRAZY"),
    ("Stray Kids", "Walkin On Water", "ATE"),
    ("SEVENTEEN", "MAESTRO", "17 IS RIGHT HERE"),
    ("NCT WISH", "Wish", "NCT WISH - The 1st Mini Album"),
    ("NCT DREAM", "Smoothie", "DREAM()SCAPE"),
    ("ENHYPEN", "XO (Only If You Say Yes)", "ROMANCE : UNTOLD"),
    ("ITZY", "Untouchable", "BORN TO BE"),
    ("ITZY", "GOLD", "GOLD"),
    ("TWICE", "ONE SPARK", "With YOU-th"),
    ("TWICE", "Strategy", "STRATEGY"),
    ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
    ("BABYMONSTER", "Sheesh", "DRIP"),
    ("BABYMONSTER", "Forever", "DRIP"),
    ("KISS OF LIFE", "Igloo", "Sticky"),
    ("RIIZE", "Love 119", "Love 119"),
    ("RIIZE", "Impossible", "Impossible"),
    ("BOYNEXTDOOR", "Earth, Wind & Fire", "HOW?"),
    ("BOYNEXTDOOR", "Nice Guy", "19.99"),
    ("ZEROBASEONE", "Feel the POP", "You had me at HELLO"),
    ("ZEROBASEONE", "SWEAT", "You had me at HELLO"),
    ("NMIXX", "Soñar (Breaker)", "Fe3O4: BREAK"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("fromis_9", "Supersonic", "From"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("TREASURE", "LAST NIGHT", "LAST NIGHT"),
    ("THE BOYZ", "MAESTRO", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "WORK", "THE WORLD EP.Fin : WILL"),
]

SPARE_BY_YEAR = {
    2019: SPARE_2019,
    2020: SPARE_2020,
    2021: SPARE_2021,
    2022: SPARE_2022,
    2023: SPARE_2023,
    2024: SPARE_2024,
}


def rebuild_pool(raw: dict, year: int, primary: list, spare: list) -> list:
    _, seen = finalize(raw, year - 1)
    pool = dedupe_pool(list(primary))
    append_unique(pool, spare, seen)
    # filter pool order: keep only globally unique vs prior years
    filtered: list[tuple[str, str, str]] = []
    for artist, title, album in pool:
        if track_key(artist, title) not in seen:
            filtered.append((artist, title, album))
    return filtered


def main() -> None:
    c1519 = load(GEN / "catalog_2015_2019.py")
    c1729 = load(GEN / "catalog_2017_2019.py")
    c2025 = load(GEN / "catalog_2020_2025.py")

    raw: dict[int, list] = {}
    raw.update(c1519.CATALOG_2015_2019)
    raw.update(c1729.CATALOG_2017_2019)
    raw.update(c2025.CATALOG_2020_2025)

    # 2019: extend pool
    append_unique(raw[2019], SPARE_2019, finalize(raw, 2018)[1])
    raw[2019] = dedupe_pool(raw[2019])

    # 2020: replace with filtered spare-only build
    _, seen19 = finalize(raw, 2019)
    pool20: list = []
    append_unique(pool20, SPARE_2020, seen19)
    raw[2020] = dedupe_pool(pool20)

    # 2021-2024: extend
    for year in range(2021, 2025):
        _, seen = finalize(raw, year - 1)
        append_unique(raw[year], SPARE_BY_YEAR[year], seen)
        raw[year] = dedupe_pool(raw[year])

    # Fix known issues in existing pools
    raw[2021] = [(a, t, al) for a, t, al in raw[2021] if not (a == "TREASURE" and t == "JIKJIN")]
    raw[2022] = [(a, t, al) for a, t, al in raw[2022] if not (a == "TWICE" and t == "Moonlight Sunrise")]

    # Move Moonlight Sunrise to 2023 if missing
    if not any(a == "TWICE" and t == "Moonlight Sunrise" for a, t, _ in raw[2023]):
        raw[2023].insert(0, ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"))

    # Clean 2025: remove remixes and wrong-year dupes
    raw[2025] = [
        (a, t, al)
        for a, t, al in raw[2025]
        if "(2025 Ver.)" not in t and "(Remix)" not in t and "(Orchestra Remix)" not in t
    ]
    raw[2025] = [(a, t, al) for a, t, al in raw[2025] if not (a == "ILLIT" and t == "Cherish (My Love)")]
    raw[2025] = [(a, t, al) for a, t, al in raw[2025] if not (a == "aespa" and t in ("Whiplash", "Dirty Work", "Supernova"))]
    raw[2025] = [(a, t, al) for a, t, al in raw[2025] if not (a == "IVE" and t == "HEYA")]
    raw[2025] = [(a, t, al) for a, t, al in raw[2025] if not (a == "NewJeans" and "How Sweet" in t)]
    raw[2025] = [(a, t, al) for a, t, al in raw[2025] if not (a == "Rosé & Bruno Mars" and "APT" in t)]
    raw[2025] = dedupe_pool(raw[2025])

    # Remove ILLIT Cherish from 2024 end duplicate block - keep once in 2024
    # Remove duplicate G-DRAGON from 2024 if in 2025 top - keep 2025 for ubermensch
    raw[2024] = [(a, t, al) for a, t, al in raw[2024] if not (a == "G-DRAGON")]

    # Write back to catalog_2020_2025.py
    lines = [
        "#!/usr/bin/env python3",
        '"""K-pop Top 100 candidate pools (2020-2025). Melon/Gaon/community ordered."""',
        "from __future__ import annotations",
        "",
        "CATALOG_2020_2025: dict[int, list[tuple[str, str, str]]] = {",
    ]
    for year in range(2020, 2026):
        lines.append(f"    {year}: [")
        for artist, title, album in raw[year]:
            lines.append(f"        ({artist!r}, {title!r}, {album!r}),")
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    (GEN / "catalog_2020_2025.py").write_text("\n".join(lines), encoding="utf-8")

    # Write 2017_2019 with updated 2019
    lines19 = [
        "#!/usr/bin/env python3",
        '"""K-pop Top 100 candidate pools (2017-2019). Melon/Gaon/community ordered."""',
        "from __future__ import annotations",
        "",
        "CATALOG_2017_2019: dict[int, list[tuple[str, str, str]]] = {",
    ]
    for year in (2017, 2018, 2019):
        lines19.append(f"    {year}: [")
        for artist, title, album in raw[year]:
            lines19.append(f"        ({artist!r}, {title!r}, {album!r}),")
        lines19.append("    ],")
    lines19.append("}")
    lines19.append("")
    (GEN / "catalog_2017_2019.py").write_text("\n".join(lines19), encoding="utf-8")

    # Report
    for year in range(2015, 2026):
        sel, _ = finalize(raw, year)
        print(f"{year}: pool={len(raw.get(year,[]))} selected={len(sel.get(year,[]))}")


if __name__ == "__main__":
    main()
