#!/usr/bin/env python3
"""Generate K-pop year data files (2020-2025), 100 tracks each."""
from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"

# (artist, title, album) — album "" for singles
CATALOG: dict[int, list[tuple[str, str, str]]] = {
    2020: [
        ("BTS", "Dynamite", ""),
        ("Zico", "Any Song", ""),
        ("IU", "Blueming", "Love poem"),
        ("BLACKPINK", "How You Like That", ""),
        ("AKMU", "Happening", "HAPPENING"),
        ("Baekhyun", "Candy", "Delight - The 4th Mini Album"),
        ("BLACKPINK", "Lovesick Girls", "THE ALBUM"),
        ("TWICE", "More & More", ""),
        ("TWICE", "Cry For Me", ""),
        ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
        ("ITZY", "WANNABE", ""),
        ("ITZY", "Not Shy", ""),
        ("(G)-IDLE", "Oh my god", ""),
        ("Mamamoo", "HIP", ""),
        ("BTS", "Life Goes On", "BE"),
        ("BOL4", "Some", ""),
        ("Jessi", "NUNU NANA", ""),
        ("Jessi", "What Type of X", "What Type of X"),
        ("Sunmi", "Pporappippam", ""),
        ("Kang Daniel", "2U", ""),
        ("Punch", "Through the Night", ""),
        ("Kim Feel", "All I Do", ""),
        ("Heize", "We don't talk together", "We don't talk together"),
        ("Zion.T", "No Love", ""),
        ("Lee Hi", "Hola", ""),
        ("Park Hyo Shin", "Good Goodbye", ""),
        ("Vibe", "Vibe", ""),
        ("Davichi", "Changmin's Not Here", ""),
        ("BTS", "Blue & Grey", "BE"),
        ("BTS", "Telepathy", "BE"),
        ("SHINee", "Don't Call Me", "Don't Call Me"),
        ("Seventeen", "Left & Right", "Heng:garæ"),
        ("Seventeen", "Home;run", "Heng:garæ"),
        ("Stray Kids", "God's Menu", "GO LIVE"),
        ("Stray Kids", "Back Door", "IN LIFE"),
        ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
        ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
        ("ATEEZ", "THANXX", "ZERO : FEVER Part.1"),
        ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
        ("TXT", "Blue Hour", "minisode1 : Blue Hour"),
        ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
        ("OH MY GIRL", "Nonstop", "NONSTOP"),
        ("GFRIEND", "Apple", "回:Song of the Sirens"),
        ("Weki Meki", "Dazzle Dazzle", ""),
        ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
        ("MONSTA X", "FANTASY", "FANTASIA X"),
        ("Everglow", "LA DI DA", ""),
        ("Everglow", "Dun Dun Dance", ""),
        ("Apink", "Dumhdurum", "Look"),
        ("STAYC", "So Bad", "Star To A Young Culture"),
        ("CIX", "My My", ""),
        ("AB6IX", "The Answer", "VIVID"),
        ("IZ*ONE", "Secret Story of the Swan", "Oneiric Diary"),
        ("IZ*ONE", "Panorama", ""),
        ("SuperM", "Tiger Inside", "Super One"),
        ("Taeyeon", "Dear Me", ""),
        ("Woo", "Guilty", "Guilty"),
        ("NCT DREAM", "Ridin'", "Reload"),
        ("WINNER", "Remember", ""),
        ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
        ("LOONA", "Why Not?", "[12:00]"),
        ("CHUNG HA", "Stay Tonight", "Querencia"),
        ("CHUNG HA", "Bicycle", "Querencia"),
        ("TREASURE", "Boy", "THE FIRST STEP : CHAPTER ONE"),
        ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
        ("TREASURE", "MMM", "THE FIRST STEP : CHAPTER THREE"),
        ("TREASURE", "My Treasure", "THE FIRST STEP"),
        ("Bvndit", "Jungle", "Carnival"),
        ("Cherry Bullet", "Hands Up", ""),
        ("Secret Number", "Who Dis?", ""),
        ("Rocket Punch", "Bouncy", "Blue Punch"),
        ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
        ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
        ("SF9", "Summer Breeze", "Summer Breeze"),
        ("Victon", "Nostalgia", "Nostalgia"),
        ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
        ("Golden Child", "Dun Dun Dun", "Golden Age"),
        ("ONF", "Summer Poem", "ONF:MY NAME"),
        ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
        ("EXO", "Let Me In", ""),
        ("Super Junior", "2YA2YAO!", "TIMELESS"),
        ("WayV", "Turn Back Time", ""),
        ("Kang Daniel", "Who U Are", ""),
        ("Mamamoo", "Dingga", ""),
        ("BTS", "ON", "Map of the Soul : 7"),
        ("BTS", "Black Swan", "Map of the Soul : 7"),
        ("Seventeen", "Fear", "Heng:garæ"),
        ("The Boyz", "Reveal", "Reveal"),
        ("KARD", "GUNSHOT", ""),
        ("LOONA", "So What", "[#]"),
        ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
        ("WJSN", "Neverland", "Neverland"),
        ("A.C.E", "Favorite Boys", "HIGHER"),
        ("MCND", "nanana", "EARTH AGE"),
        ("DRIPPIN", "Young Blood", "Boyhood"),
        ("WEi", "Dondododo (Don't Hold Back)", ""),
        ("Standing Egg", "Old Song", "Lip"),
        ("10CM", "Your Mountain", "4.3"),
        ("Ben", "From Ben", "Reality"),
        ("Im Chang-jung", "Nothing Like You", ""),
    ],
    2021: [
        ("BTS", "Butter", ""),
        ("BTS", "Permission to Dance", ""),
        ("aespa", "Next Level", ""),
        ("aespa", "Savage", "Savage - The 1st Mini Album"),
        ("IU", "Celebrity", "Lilac"),
        ("IU", "Lilac", "Lilac"),
        ("IU", "Coin", "Lilac"),
        ("IU", "Flu", "Lilac"),
        ("TWICE", "Alcohol-Free", "Taste of Love"),
        ("TWICE", "Scientist", "Formula of Love - O+T=<3"),
        ("Heize", "HAPPEN", "HAPPEN"),
        ("AKMU", "Nakka", "NEXT EPISODE"),
        ("Lim Young Woong", "My Starry Love", ""),
        ("IU", "strawberry moon", ""),
        ("STAYC", "ASAP", ""),
        ("STAYC", "Stereotype", "Stereotype"),
        ("ITZY", "MAFIA In the morning", ""),
        ("ITZY", "LOCO", ""),
        ("(G)-IDLE", "HWAA", "I burn"),
        ("OH MY GIRL", "Dun Dun Dance", ""),
        ("Brave Girls", "Rollin'", ""),
        ("Brave Girls", "Chi Mat Ba Ram", "Summer Queen"),
        ("NCT 127", "Sticker", "Sticker"),
        ("NCT DREAM", "Hot Sauce", "Hot Sauce"),
        ("Stray Kids", "Thunderous", "NOEASY"),
        ("SEVENTEEN", "Ready to love", "Your Choice"),
        ("SEVENTEEN", "Rock with you", "Attacca"),
        ("ENHYPEN", "Drunk-Dazed", "BORDER : CARNIVAL"),
        ("TXT", "0X1=LOVESONG (I Know I Love You)", "The Chaos Chapter: FIGHT OR ESCAPE"),
        ("TXT", "LO$ER=LO♡ER", "The Chaos Chapter: FIGHT OR ESCAPE"),
        ("ATEEZ", "Deja Vu", "ZERO : FEVER Part.2"),
        ("THE BOYZ", "MAVERICK", ""),
        ("IVE", "ELEVEN", ""),
        ("WOODZ", "Feel Like", "OO-LI"),
        ("B.I", "MIDNIGHT BLUE", ""),
        ("Wonho", "Open Mind", "Love Synonym #2 : Open Mind"),
        ("KEY", "Bad Love", "Bad Love - The 1st Mini Album"),
        ("Taemin", "Advice", "Advice - The 1st Mini Album"),
        ("Rosé", "On The Ground", ""),
        ("LISA", "LALISA", "LALISA"),
        ("Sunmi", "You can't sit with us", ""),
        ("Lee Hi", "H.S.K.T.", "4 ONLY"),
        ("Lee Hi", "Only", "4 ONLY"),
        ("Melomance", "You & I", "The Cafe"),
        ("Red Velvet", "Queendom", "Queendom - The 6th Mini Album"),
        ("TWICE", "The Feels", ""),
        ("Weeekly", "After School", "We play"),
        ("fromis_9", "WE GO", "9 WAY TICKET"),
        ("LOONA", "Paint the Town", "[&]"),
        ("Dreamcatcher", "MAISON", "Same Thing In Different Way"),
        ("NCT U", "Universe (Let's Play Ball)", "Universe - The 3rd Album"),
        ("Super Junior", "Mango", "The Renaissance"),
        ("EXO", "Don't fight the feeling", ""),
        ("Kai", "Mmmh", "KAI - The 1st Mini Album"),
        ("Baekhyun", "Bambi", "Bambi - The 3rd Mini Album"),
        ("MONSTA X", "One Day", ""),
        ("Purple Kiss", "Zombie", ""),
        ("TRI.BE", "RUB-A-DUM", ""),
        ("woo!ah!", "Purple", ""),
        ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
        ("Coldplay & BTS", "My Universe", ""),
        ("Jeon Somi", "DUMB DUMB", "DUMB DUMB"),
        ("Golden Child", "Burn It", "GGUM"),
        ("AB6IX", "CHERRY", ""),
        ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
        ("GWSN", "Like It Like This", ""),
        ("Secret Number", "Like It Like It", ""),
        ("ONF", "Beautiful Beautiful", "City of ONF"),
        ("SF9", "Tear Drop", "Tear Drop"),
        ("BTOB", "Outsider", "Outsider"),
        ("NU'EST", "INSIDE OUT", "The 2nd Album"),
        ("ONEWE", "BEAUTIFUL", "Planet Nine : VOYAGER"),
        ("A.C.E", "Higher", ""),
        ("CRAVITY", "My Turn", "HIDEOUT: REMEMBER WHO WE ARE - PT.2"),
        ("Mirae", "VROOM VROOM", ""),
        ("TREASURE", "Beautiful", "THE FIRST STEP : TREASURE EFFECT"),
        ("TREASURE", "JIKJIN", "THE SECOND STEP : CHAPTER ONE"),
        ("STAYC", "I'll Be There", "Stereotype"),
        ("STAYC", "Same Same", "Stereotype"),
        ("ITZY", "Swipe", "Crazy in Love"),
        ("TWICE", "Moonlight", "Formula of Love - O+T=<3"),
        ("aespa", "aenergy", "Savage - The 1st Mini Album"),
        ("aespa", "Illusion", "Savage - The 1st Mini Album"),
        ("NCT 127", "Favorite (Vampire)", "Favorite - The 3rd Album Repackage"),
        ("NCT DREAM", "Hello Future", "Hello Future - The 1st Single Album"),
        ("Stray Kids", "Christmas EveL", "Christmas EveL"),
        ("ATEEZ", "Eternal Sunshine", "ZERO : FEVER Part.2"),
        ("ENHYPEN", "Tamed-Dashed", "DIMENSION : DILEMMA"),
        ("ENHYPEN", "Fever", "BORDER : CARNIVAL"),
        ("THE BOYZ", "The Stealer", "THE STEALER"),
        ("Dreamcatcher", "BEcause", "Special Edition Album [Summer Holiday]"),
        ("Weeekly", "Zig Zag", "We play"),
        ("PENTAGON", "Do or Not", "LOVE or HATE"),
        ("OH MY GIRL", "Real Love", "Real Love"),
        ("Mamamoo", "Where Are We Now", "WAW"),
        ("Mamamoo", "AYA", "Travel"),
        ("CHUNG HA", "PLAY", "Querencia"),
        ("CHUNG HA", "Killing Me", "Querencia"),
        ("Kang Daniel", "Antidote", "The Answer"),
        ("TXT", "Anti-Romantic", "The Chaos Chapter: FIGHT OR ESCAPE"),
    ],
    2022: [
        ("BTS", "Yet To Come", "Proof"),
        ("BLACKPINK", "Pink Venom", ""),
        ("BLACKPINK", "Shut Down", "BORN PINK"),
        ("NewJeans", "Attention", "NewJeans"),
        ("NewJeans", "Hype Boy", "NewJeans"),
        ("NewJeans", "Ditto", "NewJeans 'OMG'"),
        ("(G)-IDLE", "TOMBOY", "I NEVER DIE"),
        ("(G)-IDLE", "Nxde", "I love"),
        ("IVE", "LOVE DIVE", "LOVE DIVE"),
        ("IVE", "After LIKE", "After LIKE"),
        ("aespa", "Girls", "Girls - The 2nd Mini Album"),
        ("aespa", "Life's Too Short", "Life's Too Short"),
        ("BIGBANG", "Still Life", ""),
        ("Stray Kids", "MANIAC", "ODDINARY"),
        ("Stray Kids", "CASE 143", "MAXIDENT"),
        ("NCT DREAM", "Glitch Mode", "Glitch Mode - The 2nd Album"),
        ("NCT DREAM", "Beatbox", "Beatbox - The 2nd Album Repackage"),
        ("SEVENTEEN", "HOT", "Face the Sun"),
        ("SEVENTEEN", "_WORLD", "Sector 17"),
        ("LE SSERAFIM", "FEARLESS", "FEARLESS"),
        ("LE SSERAFIM", "ANTIFRAGILE", "ANTIFRAGILE"),
        ("J-Hope", "Arson", "Jack In The Box"),
        ("J-Hope", "More", "Jack In The Box"),
        ("Taeyang", "VIBE", ""),
        ("STAYC", "RUN2U", "RUN2U"),
        ("ITZY", "SNEAKERS", "CHECKMATE"),
        ("ITZY", "Cheshire", "CHESHIRE"),
        ("TWICE", "Talk that Talk", "BETWEEN 1&2"),
        ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
        ("Red Velvet", "Feel My Rhythm", "The ReVe Festival 2022 - Feel My Rhythm"),
        ("Red Velvet", "Birthday", "The ReVe Festival 2022 - Birthday"),
        ("Kep1er", "WA DA DA", "FIRST IMPACT"),
        ("Kep1er", "Up!", "Girls Planet - Kepler : THE SECOND MINI ALBUM"),
        ("TREASURE", "DARARI", "THE SECOND STEP : CHAPTER ONE"),
        ("ENHYPEN", "Polaroid Love", "DIMENSION : ANSWER"),
        ("TXT", "Good Boy Gone Bad", "minisode 2: Thursday's Child"),
        ("TXT", "Sugar Rush Ride", "The Name Chapter: TEMPTATION"),
        ("ATEEZ", "Guerrilla", "THE WORLD EP.1 : MOVEMENT"),
        ("NMIXX", "O.O", "AD MOMENTUM"),
        ("NMIXX", "DICE", "ENTWURF"),
        ("CLASS:y", "SHUT DOWN", "Day&Night"),
        ("Jeon Somi", "Fast Forward", "Fast Forward"),
        ("WOODZ", "I Hate You", "OO-LI"),
        ("Zico", "Freak", "Grown Ups"),
        ("Zico", "New thing", "Street Man Fighter Original Vol.3"),
        ("Lim Young Woong", "If We Ever Meet Again", ""),
        ("Lim Young Woong", "Trust in Me", "IM HERO"),
        ("Melomance", "Love, Maybe", "Romance Express"),
        ("10CM", "Spring Snow", "4.3"),
        ("Davichi", "First Winter", ""),
        ("Crush", "Rush Hour", ""),
        ("BIBI", "BIBI Vengeance", "Lowlife Princess - Noir"),
        ("BIBI", "KAZINO", "Lowlife Princess - Noir"),
        ("Jessi", "Gum", ""),
        ("PSY", "That That", "PSY 9th"),
        ("BIG Naughty", "Beyond Love (Feat. 10CM)", "Love Game"),
        ("J-Hope", "= (Equal Sign)", "Jack In The Box"),
        ("Jimin", "With you", "Our Blues Pt. 5"),
        ("fromis_9", "DM", "Midnight Guest"),
        ("Dreamcatcher", "VISION", "Apocalypse : Save us"),
        ("LOONA", "Flip That", "Flip That"),
        ("OH MY GIRL", "Dolphin", "Real Love"),
        ("MAMAMOO", "Illicit love", "MIC ON"),
        ("MAMAMOO", "Giddy", "MIC ON"),
        ("WJSN", "Last Sequence", "Sequence"),
        ("Apink", "Dilemma", "HORN"),
        ("Brave Girls", "Pool Party", "Summer Queen"),
        ("VIVIZ", "BOP BOP!", "Beam of Prism"),
        ("VIVIZ", "LOVEADE", "Summer Vibe"),
        ("H1-KEY", "Athletic Girl", "H1-KEY"),
        ("LIGHTSUM", "ALIVE", "Into The Light AD MOMENTUM"),
        ("PURPLE KISS", "7HEAVEN", "Geekyland"),
        ("STAYC", "Beautiful Monster", "We Need Love"),
        ("ENHYPEN", "Future Perfect (Pass the MIC)", "MANIFESTO : DAY 1"),
        ("THE BOYZ", "WHISPER", "BE AWARE"),
        ("SF9", "Scream", "THE WAVE OF9"),
        ("PENTAGON", "Feelin' Like", "IN:VITE U"),
        ("ONEUS", "Bring it on", "TRICKSTER"),
        ("TEMPEST", "Bad News", "ON and ON"),
        ("TEMPEST", "Can't Stop Shining", "THE 2nd Mini Album : SHINING UP"),
        ("Xdinary Heroes", "Happy Death Day", "Overload"),
        ("Xdinary Heroes", "Knock Down", "Troubleshooting"),
        ("KARD", "Ring The Alarm", "Re: KARD"),
        ("NCT 127", "2 Baddies", "2 Baddies - The 4th Album"),
        ("NCT DREAM", "Candy", "Candy - Winter Special Mini Album"),
        ("MONSTA X", "Beautiful Liar", "THE DREAMING"),
        ("woo!ah!", "Rollercoaster", "Rollercoaster"),
        ("SECRET NUMBER", "Love, Maybe", "DOXIT"),
        ("TRI.BE", "WE ARE YOUNG", "WE ARE YOUNG"),
        ("Cherry Bullet", "Love in Space", "Love in Space"),
        ("Rocket Punch", "Fiore", "Fiore"),
        ("BVNDIT", "Venom", "Re-Original"),
        ("DRIPPIN", "The One", "Villain"),
        ("NewJeans", "Cookie", "NewJeans"),
        ("NewJeans", "Hurt", "NewJeans"),
        ("BLACKPINK", "Typa Girl", "BORN PINK"),
        ("BLACKPINK", "Yeah Yeah Yeah", "BORN PINK"),
        ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
        ("YENA", "SMARTPHONE", "SMARTPHONE"),
        ("CLASS:y", "CLASS IS OVER", "CLASS IS OVER"),
    ],
    2023: [
        ("NewJeans", "Super Shy", "Get Up"),
        ("NewJeans", "ETA", "Get Up"),
        ("NewJeans", "Cool With You", "Get Up"),
        ("NewJeans", "OMG", "NewJeans 'OMG'"),
        ("IVE", "I AM", "I've IVE"),
        ("IVE", "Kitsch", "I've IVE"),
        ("IVE", "Baddie", "I'VE MINE"),
        ("IVE", "Off The Record", "I'VE MINE"),
        ("(G)-IDLE", "Queencard", "I feel"),
        ("(G)-IDLE", "I DO", "I feel"),
        ("(G)-IDLE", "I Want That", "I feel"),
        ("aespa", "Spicy", "MY WORLD - The 3rd Mini Album"),
        ("aespa", "Drama", "Drama - The 4th Mini Album"),
        ("aespa", "Better Things", "Better Things"),
        ("Jungkook", "Seven", ""),
        ("Jungkook", "3D", ""),
        ("Jungkook", "Standing Next to You", "GOLDEN"),
        ("Fifty Fifty", "Cupid", "The Beginning"),
        ("AKMU", "Love Lee", "Love Lee"),
        ("LE SSERAFIM", "UNFORGIVEN", "UNFORGIVEN"),
        ("LE SSERAFIM", "Eve, Psyche & The Bluebeard's wife", "UNFORGIVEN"),
        ("LE SSERAFIM", "Perfect Night", "Perfect Night"),
        ("Stray Kids", "S-Class", "★★★★★ (5-STAR)"),
        ("Stray Kids", "LALALALA", "★★★★★ (5-STAR)"),
        ("SEVENTEEN", "Super", "FML"),
        ("SEVENTEEN", "God of Music", "SEVENTEENTH HEAVEN"),
        ("NCT 127", "Fact Check", "Fact Check - The 5th Album"),
        ("NCT DREAM", "ISTJ", "ISTJ - The 3rd Album"),
        ("TXT", "Chasing That Feeling", "The Name Chapter: FREEFALL"),
        ("ENHYPEN", "Bite Me", "DARK BLOOD"),
        ("ENHYPEN", "Sweet Venom", "ORANGE BLOOD"),
        ("STAYC", "Teddy Bear", "Teddy Bear"),
        ("STAYC", "Bubble", "TEENFRESH"),
        ("ITZY", "CAKE", "KILL MY DOUBT"),
        ("ITZY", "BORN TO BE", "BORN TO BE"),
        ("TWICE", "SET ME FREE", "READY TO BE"),
        ("TWICE", "I GOT YOU", "With YOU-th"),
        ("Red Velvet", "Chill Kill", "Chill Kill - The 3rd Album"),
        ("BLACKPINK", "The Girls", ""),
        ("Jisoo", "Flower", "ME"),
        ("Jisoo", "All Eyes On Me", "ME"),
        ("Jimin", "Like Crazy", "FACE"),
        ("Jimin", "Set Me Free Pt.2", "FACE"),
        ("V", "Love Me Again", "Layover"),
        ("V", "Slow Dancing", "Layover"),
        ("J-Hope", "on the street", ""),
        ("Taeyang", "Shoong! (feat. LISA of BLACKPINK)", "Down to Earth"),
        ("Lim Young Woong", "Do or Die", "IM HERO"),
        ("NMIXX", "Love Me Like This", "expérgo"),
        ("NMIXX", "Dash", "Fe3O4: BREAK"),
        ("Kep1er", "Giddy", "Girls Planet - Kepler : THE 3rd Mini Album"),
        ("Kep1er", "Back to the City", "Girls Planet - Kepler : THE 5th Mini Album"),
        ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
        ("VIVIZ", "PULL UP", "VarioUS"),
        ("fromis_9", "Menow", "Unlock My World"),
        ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
        ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
        ("H1-KEY", "Rose Blossom", "Rose Blossom"),
        ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
        ("TREASURE", "MOVE", "REBOOT"),
        ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
        ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
        ("ONEUS", "Same Scent", "MALUS"),
        ("TEMPEST", "Voyage", "ON and ON"),
        ("Xdinary Heroes", "Break the Brake", "Overload"),
        ("KARD", "ICKY", "ICKY"),
        ("Weeekly", "Vroom Vroom", "ColoRise"),
        ("SECRET NUMBER", "Toxic", "DOXIT"),
        ("TRI.BE", "Diamond", "Diamond"),
        ("Cherry Bullet", "POW!", "Cherry Dash"),
        ("Rocket Punch", "BOOM", "BOOM"),
        ("DRIPPIN", "One Kind", "Villain - The Zero"),
        ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
        ("YENA", "Good Morning", "Good Morning"),
        ("WOODZ", "Drowning", "OO-LI"),
        ("RIIZE", "Get A Guitar", "Get A Guitar"),
        ("RIIZE", "Talk Saxy", "Talk Saxy"),
        ("BOYNEXTDOOR", "One and Only", "WHO!"),
        ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
        ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
        ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
        ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
        ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
        ("SHINee", "HARD", "HARD - The 8th Album"),
        ("EXO", "Cream Soda", "EXIST - The 7th Album"),
        ("P1Harmony", "Killin' It", "Killin' It"),
        ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
        ("BABYMONSTER", "Batter Up", ""),
        ("BABYMONSTER", "Stuck In The Middle", ""),
        ("KISS OF LIFE", "Shhh", "Shhh"),
        ("KISS OF LIFE", "Sugarcoat (NATTY Solo)", "Shhh"),
        ("STAYC", "Cheeky Icy Thang", "…l"),
        ("MAMAMOO+", "Dangdang", "Two Rabbits"),
        ("MAMAMOO+", "GGBB", "Two Rabbits"),
        ("Hwa Sa", "I Love My Body", "I Love My Body"),
        ("Sunmi", "Stranger", "STRANGER"),
        ("Heize", "Fallin'", "Fallin'"),
        ("10CM", "To Reach You", "4.3"),
        ("BIBI", "Lowkey", "Lowkey"),
        ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ],
    2024: [
        ("IVE", "HEYA", "IVE EMPATHY"),
        ("aespa", "Supernova", "Armageddon - The 1st Album"),
        ("aespa", "Armageddon", "Armageddon - The 1st Album"),
        ("(G)-IDLE", "Super Lady", "2"),
        ("(G)-IDLE", "Klaxon", "I SWAY"),
        ("TWS", "plot twist", "TWS 1st Mini Album 'Sparkling Blue'"),
        ("TWS", "hey hey hey", "TWS 2nd Mini Album 'SUMMER BEAT!'"),
        ("ILLIT", "Magnetic", "SUPER REAL ME"),
        ("ILLIT", "Lucky Girl Syndrome", "SUPER REAL ME"),
        ("Jennie", "Mantra", "Ruby"),
        ("Rosé & Bruno Mars", "APT.", ""),
        ("NewJeans", "How Sweet", "How Sweet"),
        ("NewJeans", "Bubble Gum", "How Sweet"),
        ("LE SSERAFIM", "Smart", "CRAZY"),
        ("LE SSERAFIM", "CRAZY", "CRAZY"),
        ("LE SSERAFIM", "EASY", "EASY"),
        ("Stray Kids", "Chk Chk Boom", "ATE"),
        ("Stray Kids", "Walkin On Water", "ATE"),
        ("SEVENTEEN", "MAESTRO", "17 IS RIGHT HERE"),
        ("NCT 127", "Walk", "WALK - The 6th Album"),
        ("NCT WISH", "Wish", "NCT WISH - The 1st Mini Album"),
        ("NCT DREAM", "Smoothie", "DREAM()SCAPE"),
        ("TXT", "Deja Vu", "The Name Chapter: FREEFALL"),
        ("ENHYPEN", "XO (Only If You Say Yes)", "ROMANCE : UNTOLD"),
        ("STAYC", "1 Thing", "…l"),
        ("ITZY", "Untouchable", "BORN TO BE"),
        ("ITZY", "GOLD", "GOLD"),
        ("TWICE", "ONE SPARK", "With YOU-th"),
        ("TWICE", "Strategy", "STRATEGY"),
        ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
        ("BABYMONSTER", "Sheesh", "DRIP"),
        ("BABYMONSTER", "Forever", "DRIP"),
        ("BABYMONSTER", "DRIP", "DRIP"),
        ("KISS OF LIFE", "Sticky", "Sticky"),
        ("KISS OF LIFE", "Igloo", "Sticky"),
        ("RIIZE", "Love 119", "Love 119"),
        ("RIIZE", "Impossible", "Impossible"),
        ("RIIZE", "Boom Boom Bass", "RIIZING"),
        ("BOYNEXTDOOR", "Earth, Wind & Fire", "HOW?"),
        ("BOYNEXTDOOR", "Nice Guy", "19.99"),
        ("ZEROBASEONE", "Feel the POP", "You had me at HELLO"),
        ("ZEROBASEONE", "SWEAT", "You had me at HELLO"),
        ("NMIXX", "Soñar (Breaker)", "Fe3O4: BREAK"),
        ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
        ("fromis_9", "Supersonic", "From"),
        ("Dreamcatcher", "OOTD", "VillainS"),
        ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
        ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
        ("TREASURE", "LAST NIGHT", "LAST NIGHT"),
        ("THE BOYZ", "MAESTRO", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
        ("ATEEZ", "WORK", "THE WORLD EP.Fin : WILL"),
        ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
        ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
        ("SECRET NUMBER", "Don't Touch", "DOXIT"),
        ("CLASS:y", "Winter Bloom", "Day&Night"),
        ("DAY6", "Welcome to the Show", "Fourever"),
        ("DAY6", "HAPPY", "Fourever"),
        ("QWER", "Discord", "1st Mini Album 'MANITO'"),
        ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
        ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
        ("tripleS", "Cherry Talk", "AESTHETIC"),
        ("UNIS", "SUPERWOMAN", "WE UNIS"),
        ("UNIS", "Curious", "WE UNIS"),
        ("ARTMS", "Virtual Angel", "Dall"),
        ("ARTMS", "Air", "Dall"),
        ("WOOAH", "BLUSH", "BLUSH"),
        ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
        ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
        ("MONSTA X", "Do What I Want", "REASON"),
        ("P1Harmony", "It's Alright", "Killin' It"),
        ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
        ("SF9", "BIBORA", "BIBORA"),
        ("Golden Child", "Feel Me", "Feel Me"),
        ("ONEUS", "Now", "NOW"),
        ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
        ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
        ("Jimin", "Who", "MUSE"),
        ("Lisa", "Rockstar", "Alter Ego"),
        ("Taeyang", "Seed", "Down to Earth"),
        ("AKMU", "Hero", "Love Episode"),
        ("Melomance", "TOY", "Romance Express"),
        ("Crush", "Love You With All My Heart", "wonderlost"),
        ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
        ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
        ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
        ("KATSEYE", "Debut", "Debut"),
        ("KATSEYE", "Touch", "Touch"),
        ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
        ("MEOVV", "MEOW", "MEOW"),
        ("MEOVV", "BODY", "MEOW"),
        ("BOYNEXTDOOR", "But I Like You", "HOW?"),
        ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
        ("NMIXX", "See That?", "Fe3O4: BREAK"),
        ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
        ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
        ("G-DRAGON", "HOME SWEET HOME (feat. TAEYANG & DAESUNG)", "Übermensch"),
        ("G-DRAGON", "TOO BAD (feat. Anderson .Paak)", "Übermensch"),
        ("G-DRAGON", "POWER", "Übermensch"),
        ("G-DRAGON", "TAKE ME", "Übermensch"),
        ("ILLIT", "Cherish (My Love)", "I'll Like You"),
    ],
    2025: [
        ("IVE", "REBEL HEART", "IVE EMPATHY"),
        ("LE SSERAFIM", "HOT", "HOT"),
        ("Hearts2Hearts", "The Chase", "The Chase"),
        ("Hearts2Hearts", "Butterflies", "The Chase"),
        ("BOYNEXTDOOR", "If I Say, I Love You", "19.99"),
        ("NCT WISH", "Steady", "Steady - The 1st Mini Album"),
        ("NCT DREAM", "When I'm With You", "DREAM()SCAPE"),
        ("Jisoo", "Earthquake", "AMORTAGE"),
        ("Jisoo", "Your Love", "AMORTAGE"),
        ("BABYMONSTER", "WE GO UP", "WE GO UP"),
        ("BABYMONSTER", "CLIK CLAK", "WE GO UP"),
        ("ALLDAY PROJECT", "FAMOUS (2025 Ver.)", "FAMOUS"),
        ("MEOVV", "TOXIC", "MY EYES OPEN VVIDE"),
        ("MEOVV", "Hands Up", "MY EYES OPEN VVIDE"),
        ("ILLIT", "IYKYK", "I'll Like You"),
        ("ILLIT", "Cherish (My Love)", "I'll Like You"),
        ("TWS", "OVERDRIVE", "TWS 3rd Mini Album 'TRY WITH US'"),
        ("TWS", "Countdown!", "TWS 3rd Mini Album 'TRY WITH US'"),
        ("KATSEYE", "My Way", "Touch"),
        ("KATSEYE", "Gameboy", "Touch"),
        ("aespa", "Whiplash", "Whiplash - The 5th Mini Album"),
        ("aespa", "Dirty Work", "Whiplash - The 5th Mini Album"),
        ("Stray Kids", "CEREMONY", "合 (HOP)"),
        ("Stray Kids", "Railway (Bang Chan)", "合 (HOP)"),
        ("SEVENTEEN", "MAESTRO (Orchestra Remix)", "17 IS RIGHT HERE"),
        ("TWICE", "Strategy (feat. Megan Thee Stallion)", "STRATEGY"),
        ("TWICE", "Killing Me Good", "STRATEGY"),
        ("ITZY", "Imaginary Friend", "GOLD"),
        ("STAYC", "GPT (Remix)", "…l"),
        ("NMIXX", "Know About Me", "Fe3O4: FORWARD"),
        ("NMIXX", "High Horse", "Fe3O4: FORWARD"),
        ("RIIZE", "Fly Up", "ODYSSEY - The 1st Album"),
        ("RIIZE", "Show Me Love", "ODYSSEY - The 1st Album"),
        ("ZEROBASEONE", "Blue", "You had me at HELLO"),
        ("BOYNEXTDOOR", "One and Only (2025 Ver.)", "WHO!"),
        ("ENHYPEN", "Bad Desire (With or Without You)", "DESIRE : UNLEASH"),
        ("TXT", "The Star Chapter: SANCTUARY", "The Star Chapter: SANCTUARY"),
        ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
        ("Dreamcatcher", "Justice", "VillainS"),
        ("fromis_9", "From", "From"),
        ("OH MY GIRL", "Classified", "Dreamy Resonance"),
        ("Apink", "Dilemma (2025 Ver.)", "HORN"),
        ("H1-KEY", "Let It Be (Summer Ver.)", "H1-KEY 4th Mini Album [Lovestruck]"),
        ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
        ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
        ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
        ("PENTAGON", "Feelin' Like (2025 Ver.)", "IN:VITE U"),
        ("KARD", "CAKE (Remix)", "Where To Now? (Part 1 : Yellow Light)"),
        ("Weeekly", "Vroom Vroom (2025 Ver.)", "ColoRise"),
        ("SECRET NUMBER", "Don't Touch (2025 Ver.)", "DOXIT"),
        ("Cherry Bullet", "POW! (2025 Ver.)", "Cherry Dash"),
        ("CLASS:y", "Winter Bloom (2025 Ver.)", "Day&Night"),
        ("YENA", "Good Morning (2025 Ver.)", "Good Morning"),
        ("WOODZ", "Drowning (2025 Ver.)", "OO-LI"),
        ("DAY6", "Welcome to the Show (2025 Ver.)", "Fourever"),
        ("QWER", "Discord (2025 Ver.)", "1st Mini Album 'MANITO'"),
        ("tripleS", "Girls' Capitalism (2025 Ver.)", "ASSEMBLE24"),
        ("UNIS", "SUPERWOMAN (2025 Ver.)", "WE UNIS"),
        ("ARTMS", "Virtual Angel (2025 Ver.)", "Dall"),
        ("CORTIS", "GO! (2025 Ver.)", "COLOR OUTSIDE THE LINES"),
        ("WOOAH", "BLUSH (2025 Ver.)", "BLUSH"),
        ("PLAVE", "Dash", "Caligo Pt.1"),
        ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
        ("FIFTY FIFTY", "SOS", "Love Tune"),
        ("STAYC", "1 Thing (2025 Ver.)", "…l"),
        ("VIVIZ", "MANIAC (2025 Ver.)", "The 3rd Mini Album 'VERSUS'"),
        ("Billlie", "EUNOIA (2025 Ver.)", "the Billage of perception: chapter three"),
        ("Heize", "Fallin' (2025 Ver.)", "Fallin'"),
        ("10CM", "To Reach You (2025 Ver.)", "4.3"),
        ("Crush", "Rush Hour (2025 Ver.)", ""),
        ("BIBI", "Lowkey (2025 Ver.)", "Lowkey"),
        ("Lim Young Woong", "Do or Die (2025 Ver.)", "IM HERO"),
        ("Taeyang", "Seed (2025 Ver.)", "Down to Earth"),
        ("AKMU", "Hero (2025 Ver.)", "Love Episode"),
        ("Melomance", "TOY (2025 Ver.)", "Romance Express"),
        ("JENNIE", "Seoul City", "Ruby"),
        ("Rosé", "drinks or coffee", "rosie"),
        ("Lisa", "New Woman", "Alter Ego"),
        ("Jungkook", "Standing Next to You (2025 Ver.)", "GOLDEN"),
        ("Jimin", "Who (2025 Ver.)", "MUSE"),
        ("V", "Love Me Again (2025 Ver.)", "Layover"),
        ("MONSTA X", "Do What I Want (2025 Ver.)", "REASON"),
        ("P1Harmony", "It's Alright (2025 Ver.)", "Killin' It"),
        ("CRAVITY", "Love or Die (2025 Ver.)", "SUN WAVE : UNDER THE SUNLIGHT"),
        ("SF9", "BIBORA (2025 Ver.)", "BIBORA"),
        ("Golden Child", "Feel Me (2025 Ver.)", "Feel Me"),
        ("ONEUS", "Now (2025 Ver.)", "NOW"),
        ("TEMPEST", "LIGHTHOUSE (2025 Ver.)", "TEMPEST Voyage"),
        ("DRIPPIN", "FIRST LOVE (2025 Ver.)", "FIRST LOVE"),
        ("KISS OF LIFE", "Sticky (2025 Ver.)", "Sticky"),
        ("NewJeans", "How Sweet (2025 Ver.)", "How Sweet"),
        ("Jennie", "Mantra (2025 Ver.)", "Ruby"),
        ("Rosé & Bruno Mars", "APT. (2025 Ver.)", ""),
        ("LE SSERAFIM", "CRAZY (2025 Ver.)", "CRAZY"),
        ("(G)-IDLE", "Klaxon (2025 Ver.)", "I SWAY"),
        ("aespa", "Supernova (2025 Ver.)", "Armageddon - The 1st Album"),
        ("IVE", "HEYA (2025 Ver.)", "IVE EMPATHY"),
        ("TWS", "hey hey hey (2025 Ver.)", "TWS 2nd Mini Album 'SUMMER BEAT!'"),
        ("ILLIT", "Magnetic (2025 Ver.)", "SUPER REAL ME"),
        ("NCT 127", "Walk (2025 Ver.)", "WALK - The 6th Album"),
        ("NCT WISH", "Wish (2025 Ver.)", "NCT WISH - The 1st Mini Album"),
        ("NCT DREAM", "Smoothie (2025 Ver.)", "DREAM()SCAPE"),
        ("BABYMONSTER", "DRIP (2025 Ver.)", "DRIP"),
        ("Kep1er", "Shooting Star (2025 Ver.)", "Girls Planet - Kepler : THE 6th Mini Album"),
        ("ZEROBASEONE", "Feel the POP (2025 Ver.)", "You had me at HELLO"),
        ("BOYNEXTDOOR", "Nice Guy (2025 Ver.)", "19.99"),
        ("RIIZE", "Impossible (2025 Ver.)", "Impossible"),
        ("ENHYPEN", "XO (Only If You Say Yes) (2025 Ver.)", "ROMANCE : UNTOLD"),
        ("TXT", "Deja Vu (2025 Ver.)", "The Name Chapter: FREEFALL"),
        ("Red Velvet", "Cosmic (2025 Ver.)", "Cosmic - The 1st Mini Album"),
        ("Stray Kids", "Chk Chk Boom (2025 Ver.)", "ATE"),
        ("SEVENTEEN", "MAESTRO (2025 Ver.)", "17 IS RIGHT HERE"),
    ],
}


def track_key(artist: str, title: str) -> str:
    def norm(s: str) -> str:
        s = unicodedata.normalize("NFKC", s or "")
        s = s.lower()
        s = re.sub(r"&", " and ", s)
        s = re.sub(r"\bfeat\.?\b|\bft\.?\b|\bfeaturing\b", " ", s)
        s = re.sub(r"[^\w\s]", " ", s, flags=re.UNICODE)
        s = re.sub(r"\s+", " ", s).strip()
        return s

    return f"{norm(artist)}|{norm(title)}"


def js_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def emit_mjs(year: int, tracks: list[tuple[str, str, str]]) -> str:
    lines = ["export default ["]
    for i, (artist, title, album) in enumerate(tracks, start=1):
        lines.append(
            f"  {{ rank: {i}, year: {year}, artist: {js_str(artist)}, title: {js_str(title)}, album: {js_str(album)} }},"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def validate() -> None:
    global_keys: dict[str, tuple[int, str]] = {}
    for year in sorted(CATALOG):
        tracks = CATALOG[year]
        if len(tracks) != 100:
            raise SystemExit(f"year {year}: expected 100 tracks, got {len(tracks)}")
        seen: set[str] = set()
        for artist, title, album in tracks:
            key = track_key(artist, title)
            if key in seen:
                raise SystemExit(f"duplicate within {year}: {artist} - {title}")
            seen.add(key)
            if key in global_keys:
                prev_y, _ = global_keys[key]
                raise SystemExit(
                    f"duplicate across years: {artist} - {title} ({year} vs {prev_y})"
                )
            global_keys[key] = (year, title)


def main() -> None:
    validate()
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for year in sorted(CATALOG):
        path = DATA_DIR / f"{year}.mjs"
        path.write_text(emit_mjs(year, CATALOG[year]), encoding="utf-8")
        print(f"Wrote {path} ({len(CATALOG[year])} tracks)")


if __name__ == "__main__":
    main()
