# Additional 2024 / 2025 release candidates (ordered by estimated rank)

MORE_2024 = [
    ("Young Posse", "XX", "XX"),
    ("KISS OF LIFE", "Midas Touch", "Midas Touch"),
    ("(G)-IDLE", "Wife", "2"),
    ("Taeyeon", "To. X", "To. X - The 5th Mini Album"),
    ("IU", "Holssi", "The Winning"),
    ("Melomance", "Look In Love", "Look In Love"),
    ("BOYNEXTDOOR", "So let's go see the stars", "HOW?"),
    ("SEVENTEEN", "LOVE, MONEY, FAME", "SEVENTEENTH HEAVEN"),
    ("SEVENTEEN", "Power of Love", "SEVENTEENTH HEAVEN"),
    ("NCT 127", "Walk", "WALK - The 6th Album"),
    ("NCT WISH", "Songbird", "Steady - The 1st Mini Album"),
    ("NCT DREAM", "When I'm With You", "DREAM()SCAPE"),
    ("Stray Kids", "Chk Chk Boom", "ATE"),
    ("Stray Kids", "Walkin On Water", "ATE"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("TWS", "plot twist", "TWS 1st Mini Album 'Sparkling Blue'"),
    ("TWS", "hey hey hey", "TWS 2nd Mini Album 'SUMMER BEAT!'"),
    ("ILLIT", "Magnetic", "SUPER REAL ME"),
    ("ILLIT", "Lucky Girl Syndrome", "SUPER REAL ME"),
    ("ILLIT", "Cherish (My Love)", "I'll Like You"),
    ("NewJeans", "How Sweet", "How Sweet"),
    ("NewJeans", "Bubble Gum", "How Sweet"),
    ("NewJeans", "Supernatural", "Supernatural"),
    ("LE SSERAFIM", "Smart", "CRAZY"),
    ("LE SSERAFIM", "CRAZY", "CRAZY"),
    ("LE SSERAFIM", "EASY", "EASY"),
    ("LE SSERAFIM", "Perfect Night", "Perfect Night"),
    ("aespa", "Supernova", "Armageddon - The 1st Album"),
    ("aespa", "Armageddon", "Armageddon - The 1st Album"),
    ("aespa", "Whiplash", "Whiplash - The 5th Mini Album"),
    ("aespa", "Dirty Work", "Whiplash - The 5th Mini Album"),
    ("IVE", "HEYA", "IVE EMPATHY"),
    ("IVE", "Accendio", "IVE SWITCH"),
    ("(G)-IDLE", "Super Lady", "2"),
    ("(G)-IDLE", "Klaxon", "I SWAY"),
    ("Jennie", "Mantra", "Ruby"),
    ("Rosé & Bruno Mars", "APT.", ""),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("Jimin", "Who", "MUSE"),
    ("Lisa", "Rockstar", "Alter Ego"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("MEOVV", "MEOW", "MEOW"),
    ("MEOVV", "BODY", "MEOW"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("UNIS", "Curious", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("ARTMS", "Air", "Dall"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("DAY6", "Melt Down", "Fourever"),
    ("STAYC", "1 Thing", "…l"),
    ("STAYC", "GPT", "…l"),
    ("ITZY", "Untouchable", "BORN TO BE"),
    ("ITZY", "GOLD", "GOLD"),
    ("ITZY", "Imaginary Friend", "GOLD"),
    ("TWICE", "ONE SPARK", "With YOU-th"),
    ("TWICE", "Strategy", "STRATEGY"),
    ("TWICE", "Killing Me Good", "STRATEGY"),
    ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
    ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
    ("BABYMONSTER", "Sheesh", "DRIP"),
    ("BABYMONSTER", "Forever", "DRIP"),
    ("BABYMONSTER", "DRIP", "DRIP"),
    ("KISS OF LIFE", "Sticky", "Sticky"),
    ("KISS OF LIFE", "Igloo", "Sticky"),
    ("RIIZE", "Love 119", "Love 119"),
    ("RIIZE", "Impossible", "Impossible"),
    ("RIIZE", "Boom Boom Bass", "RIIZING"),
    ("BOYNEXTDOOR", "Earth, Wind & Fire", "HOW?"),
    ("BOYNEXTDOOR", "Nice Guy", "19.99"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Feel the POP", "You had me at HELLO"),
    ("ZEROBASEONE", "SWEAT", "You had me at HELLO"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "Soñar (Breaker)", "Fe3O4: BREAK"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("fromis_9", "Supersonic", "From"),
    ("fromis_9", "From", "From"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("Dreamcatcher", "Justice", "VillainS"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("OH MY GIRL", "Classified", "Dreamy Resonance"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("Apink", "Dilemma", "HORN"),
    ("TREASURE", "LAST NIGHT", "LAST NIGHT"),
    ("THE BOYZ", "MAESTRO", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "WORK", "THE WORLD EP.Fin : WILL"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("NCT 127", "Fact Check", "Fact Check - The 5th Album"),
    ("SHINee", "Hard", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("AKMU", "Love Lee", "Love Lee"),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("N.Flying", "Bye Bye Bye", "FLY HIGH PROJECT #5"),
    ("VERIVERY", "Crazy Like That", "Lost and Found"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("ENHYPEN", "XO (Only If You Say Yes)", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu", "The Name Chapter: FREEFALL"),
    ("NCT DREAM", "Smoothie", "DREAM()SCAPE"),
    ("NCT WISH", "Wish", "NCT WISH - The 1st Mini Album"),
    ("SEVENTEEN", "MAESTRO", "17 IS RIGHT HERE"),
    ("Stray Kids", "Hall of Fame", "ATE"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("TWICE", "SET ME FREE", "READY TO BE"),
    ("Red Velvet", "Chill Kill", "Chill Kill - The 3rd Album"),
    ("NMIXX", "Love Me Like This", "expérgo"),
    ("Kep1er", "Giddy", "Girls Planet - Kepler : THE 3rd Mini Album"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Fifty Fifty", "Cupid", "The Beginning"),
    ("Jungkook", "Standing Next to You", "GOLDEN"),
    ("V", "Love Me Again", "Layover"),
    ("Jimin", "Like Crazy", "FACE"),
    ("Jisoo", "Flower", "ME"),
    ("STAYC", "Teddy Bear", "Teddy Bear"),
    ("ITZY", "CAKE", "KILL MY DOUBT"),
    ("Paul Kim", "Me After You", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Crush", "None", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Davichi", "First Winter", ""),
    ("Urban Zakapa", "When We Were Two", "02"),
    ("10CM", "Spring Snow", "4.3"),
    ("Punch", "Losing Sleep", ""),
    ("Roy Kim", "Only Then", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("VIVIZ", "PULL UP", "VarioUS"),
    ("fromis_9", "Menow", "Unlock My World"),
    ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
    ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
]

MORE_2025 = [
    ("IVE", "REBEL HEART", "IVE EMPATHY"),
    ("LE SSERAFIM", "HOT", "HOT"),
    ("Hearts2Hearts", "The Chase", "The Chase"),
    ("Hearts2Hearts", "Butterflies", "The Chase"),
    ("BOYNEXTDOOR", "If I Say, I Love You", "19.99"),
    ("NCT WISH", "Steady", "Steady - The 1st Mini Album"),
    ("NCT DREAM", "When I'm With You", "DREAM()SCAPE"),
    ("Jisoo", "Earthquake", "AMORTAGE"),
    ("Jisoo", "Your Love", "AMORTAGE"),
    ("BABYMONSTER", "WE GO UP", "WE GO UP"),
    ("BABYMONSTER", "CLIK CLAK", "WE GO UP"),
    ("ALLDAY PROJECT", "FAMOUS", "FAMOUS"),
    ("MEOVV", "TOXIC", "MY EYES OPEN VVIDE"),
    ("MEOVV", "Hands Up", "MY EYES OPEN VVIDE"),
    ("ILLIT", "IYKYK", "I'll Like You"),
    ("TWS", "OVERDRIVE", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("TWS", "Countdown!", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("KATSEYE", "My Way", "Touch"),
    ("KATSEYE", "Gameboy", "Touch"),
    ("Stray Kids", "CEREMONY", "合 (HOP)"),
    ("Stray Kids", "Railway (Bang Chan)", "合 (HOP)"),
    ("TWICE", "Strategy (feat. Megan Thee Stallion)", "STRATEGY"),
    ("TWICE", "Killing Me Good", "STRATEGY"),
    ("ITZY", "Imaginary Friend", "GOLD"),
    ("NMIXX", "Know About Me", "Fe3O4: FORWARD"),
    ("NMIXX", "High Horse", "Fe3O4: FORWARD"),
    ("RIIZE", "Fly Up", "ODYSSEY - The 1st Album"),
    ("RIIZE", "Show Me Love", "ODYSSEY - The 1st Album"),
    ("ZEROBASEONE", "Blue", "You had me at HELLO"),
    ("ENHYPEN", "Bad Desire (With or Without You)", "DESIRE : UNLEASH"),
    ("TXT", "The Star Chapter: SANCTUARY", "The Star Chapter: SANCTUARY"),
    ("G-DRAGON", "HOME SWEET HOME (feat. TAEYANG & DAESUNG)", "Übermensch"),
    ("G-DRAGON", "TOO BAD (feat. Anderson .Paak)", "Übermensch"),
    ("G-DRAGON", "POWER", "Übermensch"),
    ("G-DRAGON", "TAKE ME", "Übermensch"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
    ("Dreamcatcher", "Justice", "VillainS"),
    ("fromis_9", "From", "From"),
    ("OH MY GIRL", "Classified", "Dreamy Resonance"),
    ("Apink", "Dilemma", "HORN"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("UNIS", "Curious", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("ARTMS", "Air", "Dall"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("MEOVV", "MEOW", "MEOW"),
    ("MEOVV", "BODY", "MEOW"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("STAYC", "GPT", "…l"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("KISS OF LIFE", "Sticky", "Sticky"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("fromis_9", "Supersonic", "From"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("Young Posse", "XX", "XX"),
    ("KISS OF LIFE", "Midas Touch", "Midas Touch"),
    ("(G)-IDLE", "Wife", "2"),
    ("Taeyeon", "To. X", "To. X - The 5th Mini Album"),
    ("IU", "Holssi", "The Winning"),
    ("Melomance", "Look In Love", "Look In Love"),
    ("BOYNEXTDOOR", "So let's go see the stars", "HOW?"),
    ("NCT WISH", "Songbird", "Steady - The 1st Mini Album"),
    ("Stray Kids", "Hall of Fame", "ATE"),
    ("SEVENTEEN", "LOVE, MONEY, FAME", "SEVENTEENTH HEAVEN"),
    ("N.Flying", "Bye Bye Bye", "FLY HIGH PROJECT #5"),
    ("VERIVERY", "Crazy Like That", "Lost and Found"),
    ("Paul Kim", "Me After You", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Crush", "None", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Davichi", "First Winter", ""),
    ("Urban Zakapa", "When We Were Two", "02"),
    ("10CM", "Spring Snow", "4.3"),
    ("Punch", "Losing Sleep", ""),
    ("Roy Kim", "Only Then", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("VIVIZ", "PULL UP", "VarioUS"),
    ("fromis_9", "Menow", "Unlock My World"),
    ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
    ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("AKMU", "Love Lee", "Love Lee"),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
    ("Fifty Fifty", "Cupid", "The Beginning"),
    ("Jungkook", "Standing Next to You", "GOLDEN"),
    ("V", "Love Me Again", "Layover"),
    ("Jimin", "Like Crazy", "FACE"),
    ("Jisoo", "Flower", "ME"),
    ("STAYC", "Teddy Bear", "Teddy Bear"),
    ("ITZY", "CAKE", "KILL MY DOUBT"),
    ("TWICE", "SET ME FREE", "READY TO BE"),
    ("Red Velvet", "Chill Kill", "Chill Kill - The 3rd Album"),
    ("NMIXX", "Love Me Like This", "expérgo"),
    ("Kep1er", "Giddy", "Girls Planet - Kepler : THE 3rd Mini Album"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("SHINee", "Hard", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Apink", "Dilemma", "HORN"),
    ("fromis_9", "From", "From"),
    ("Dreamcatcher", "Justice", "VillainS"),
    ("OH MY GIRL", "Classified", "Dreamy Resonance"),
    ("STAYC", "GPT", "…l"),
    ("ITZY", "Imaginary Friend", "GOLD"),
    ("TWICE", "Killing Me Good", "STRATEGY"),
    ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
    ("aespa", "Whiplash", "Whiplash - The 5th Mini Album"),
    ("aespa", "Dirty Work", "Whiplash - The 5th Mini Album"),
    ("NCT 127", "Fact Check", "Fact Check - The 5th Album"),
    ("SHINee", "Hard", "HARD - The 8th Album"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("AKMU", "Love Lee", "Love Lee"),
    ("Melomance", "Love, Maybe", "Romance Express"),
]
