#!/usr/bin/env python3
"""Append unique candidate tracks to under-filled year pools."""
from __future__ import annotations

import importlib.util
import re
import unicodedata
from collections import Counter
from pathlib import Path

GEN = Path(__file__).parent


def track_key(artist: str, title: str) -> str:
    def norm(s: str) -> str:
        s = unicodedata.normalize("NFKC", s or "").lower().replace("&", " and ")
        s = re.sub(r"\bfeat\.?\b|\bft\.?\b|\bfeaturing\b", " ", s)
        s = re.sub(r"[^\w\s가-힣]+", " ", s, flags=re.UNICODE)
        return re.sub(r"\s+", " ", s).strip()

    return f"{norm(artist)}|{norm(title)}"


def load(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def simulate_global(raw: dict[int, list], upto: int) -> set[str]:
    seen: set[str] = set()
    for year in range(2015, upto + 1):
        ac: Counter[str] = Counter()
        for artist, title, _ in raw.get(year, []):
            if len([1 for y in range(2015, year + 1) if y == year]) and sum(
                1 for a, t, _ in raw.get(year, []) if track_key(a, t) in seen
            ):
                pass
            if ac[artist] >= 2:
                continue
            k = track_key(artist, title)
            if k in seen:
                continue
            if len([t for t in raw.get(year, []) if track_key(t[0], t[1]) == k]) == 0:
                continue
            # count selected
        pool = raw.get(year, [])
        result: list = []
        ac = Counter()
        for artist, title, album in pool:
            if len(result) >= 100:
                break
            if ac[artist] >= 2:
                continue
            k = track_key(artist, title)
            if k in seen:
                continue
            result.append((artist, title, album))
            ac[artist] += 1
            seen.add(k)
    return seen


# Extra tracks — 2019-only releases not yet in prior-year finals
EXTRA_2019 = [
    ("NCT 127", "Superhuman", "NCT #127 Neo Zone - The 2nd Album"),
    ("Stray Kids", "Double Knot", "Clé : LEVANTER"),
    ("Stray Kids", "Astronaut", "Clé : LEVANTER"),
    ("GFRIEND", "Crossroads", "回:Song of the Sirens"),
    ("GFRIEND", "Tonight", "回:Song of the Sirens"),
    ("Lovelyz", "Once Upon a Time", "Once Upon a Time"),
    ("MOMOLAND", "Thumbs Up", "Show Me"),
    ("(G)-IDLE", "LION", "I made"),
    ("Sunmi", "LALALAY", "WARNING"),
    ("Taeyeon", "Spark", "Purpose - The 2nd Studio Album"),
    ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
    ("OH MY GIRL", "Bungee (Fall in Love)", "The Fifth Season"),
    ("Apink", "%%", "Percent"),
    ("BTOB", "Blue Moon", "Feel'eM"),
    ("VIXX", "Parallel", "Conception Ker"),
    ("INFINITE", "Why Why", "Why Why"),
    ("ASTRO", "All Night", "All Light"),
    ("SF9", "RPM", "RPM"),
    ("Block B", "Don't Leave", "RECONSTRUCTION"),
    ("iKON", "Dive", "NEW KIDS : THE FINAL"),
    ("WINNER", "Ah Yeah", "WE"),
    ("GOT7", "Eclipse", "Spinning Top : Between Security & Insecurity"),
    ("Stray Kids", "Side Effects", "Clé 2 : Yellow Wood"),
    ("SEVENTEEN", "Hit", "An Ode"),
    ("NCT DREAM", "BOOM", "We Boom - The 3rd Mini Album"),
    ("EXO", "Obsession", "OBSESSION - The 6th Album"),
    ("BLACKPINK", "Kill This Love", ""),
    ("TWICE", "Fancy", "Fancy You"),
    ("TWICE", "Feel Special", "Feel Special"),
    ("ITZY", "WANNABE", ""),
    ("(G)-IDLE", "Senorita", "I made"),
    ("IU", "Love poem", "Love poem"),
    ("BTS", "Make It Right", "MAP OF THE SOUL : PERSONA"),
    ("Mamamoo", "HIP", ""),
    ("Heize", "We don't talk together", "We don't talk together"),
    ("BOL4", "Work", "Two Five"),
    ("CHUNG HA", "Snapping", "Flourishing"),
    ("CHUNG HA", "Gotta Go", "Flourishing"),
    ("Kang Daniel", "2U", ""),
    ("Jessi", "NUNU NANA", ""),
    ("Sunmi", "Pporappippam", ""),
    ("Zion.T", "No Love", ""),
    ("Kim Feel", "All I Do", ""),
    ("Vibe", "Vibe", ""),
    ("Punch", "Through the Night", ""),
    ("Lee Hi", "Hola", ""),
    ("Park Hyo Shin", "Good Goodbye", ""),
    ("Crush", "None", ""),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("DAY6", "Sweet Chaos", "The Book of Us : Entropy"),
    ("N.Flying", "Oh really?", "So, 通"),
    ("ONEWE", "Tag Me (@Me)", "ONE"),
    ("VERIVERY", "Thunder", "Truth or Dare"),
    ("D1CE", "HATE YOU", "Wake Up"),
    ("OnlyOneOf", "libidO", "Instinct, Part. 1"),
    ("BoA", "Woman", "ONE SHOT, TWO SHOT"),
    ("Taeyeon", "Wine", "Something New - The 3rd Mini Album"),
    ("Sunny Hill", "Monday to Sunday", "The Beginning of New Endings"),
    ("Brown Eyed Girls", "Wonder Woman", "RE_vive"),
    ("2NE1", "Goodbye", ""),
    ("Epik High", "Born Hater", "Shoebox"),
    ("K/DA", "POP/STARS", ""),
    ("Paul Kim", "Me After You", ""),
    ("Sam Kim", "Make Up", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("TREASURE", "Going Crazy", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "Come Back Home", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
    ("TREASURE", "MMM", "THE FIRST STEP : CHAPTER THREE"),
    ("TREASURE", "My Treasure", "THE FIRST STEP"),
    ("NCT U", "Make A Wish (Birthday Song)", "Resonance Pt. 1"),
    ("SuperM", "Jopping", "Super One"),
    ("SuperM", "100", "Super One"),
    ("Victon", "Nostalgia", "Nostalgia"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("aespa", "Black Mamba", ""),
    ("STAYC", "ASAP", ""),
    ("Brave Girls", "Rollin'", ""),
    ("Everglow", "Adios", "HUSH"),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("Cherry Bullet", "Hands Up", ""),
    ("AB6IX", "Blind For Love", "6IX SENSE"),
    ("CIX", "My My", ""),
    ("The Boyz", "D.D.D", "Dreamlike"),
    ("ATEEZ", "Wonderland", "TREASURE EP.Fin : All To Action"),
    ("WayV", "Take Off", "Take Off"),
    ("TXT", "Run Away", "The Dream Chapter: ETERNITY"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Why Not?", "[12:00]"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Weki Meki", "Dazzle Dazzle", ""),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("Everglow", "LA DI DA", ""),
    ("Apink", "Dumhdurum", "Look"),
    ("SuperM", "Tiger Inside", "Super One"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("TXT", "Blue Hour", "minisode1 : Blue Hour"),
    ("Mamamoo", "Dingga", ""),
    ("AKMU", "Happening", "HAPPENING"),
    ("Baekhyun", "Candy", "Delight - The 4th Mini Album"),
    ("IU", "Blueming", "Love poem"),
    ("Zico", "Any Song", ""),
    ("Davichi", "Changmin's Not Here", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("10CM", "Your Mountain", "4.3"),
    ("CLC", "ME", "No.1"),
    ("MOMOLAND", "I'm So Hot", "Show Me"),
    ("NU'EST", "Bet Bet", "The 2nd Album"),
    ("TREASURE", "Boy", "THE FIRST STEP : CHAPTER ONE"),
    ("STAYC", "So Bad", "Star To A Young Culture"),
    ("Weeekly", "Tag Me (@Me)", "We are"),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("SECRET NUMBER", "Who Dis?", ""),
    ("ONEUS", "LIT", "LIVED"),
    ("woo!ah!", "Purple", ""),
    ("TRI.BE", "RUB-A-DUM", ""),
    ("PURPLE KISS", "Zombie", ""),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("BVNDIT", "Jungle", "Carnival"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
]

# 2020-only (replace pool entirely)
POOL_2020 = [
    ("BTS", "Dynamite", ""),
    ("BTS", "Life Goes On", "BE"),
    ("BTS", "Blue & Grey", "BE"),
    ("BTS", "Telepathy", "BE"),
    ("BTS", "ON", "Map of the Soul : 7"),
    ("BTS", "Black Swan", "Map of the Soul : 7"),
    ("BLACKPINK", "How You Like That", ""),
    ("BLACKPINK", "Lovesick Girls", "THE ALBUM"),
    ("TWICE", "More & More", ""),
    ("TWICE", "Cry For Me", ""),
    ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
    ("ITZY", "Not Shy", ""),
    ("(G)-IDLE", "Oh my god", ""),
    ("Jessi", "What Type of X", "What Type of X"),
    ("Sunmi", "Pporappippam", ""),
    ("Kang Daniel", "Who U Are", ""),
    ("Punch", "Through the Night", ""),
    ("Kim Feel", "All I Do", ""),
    ("Lee Hi", "Hola", ""),
    ("Park Hyo Shin", "Good Goodbye", ""),
    ("Vibe", "Vibe", ""),
    ("SHINee", "Don't Call Me", "Don't Call Me"),
    ("Seventeen", "Left & Right", "Heng:garæ"),
    ("Seventeen", "Home;run", "Heng:garæ"),
    ("Seventeen", "Fear", "Heng:garæ"),
    ("Stray Kids", "God's Menu", "GO LIVE"),
    ("Stray Kids", "Back Door", "IN LIFE"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("NCT DREAM", "Ridin'", "Reload"),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("ATEEZ", "THANXX", "ZERO : FEVER Part.1"),
    ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
    ("TXT", "Blue Hour", "minisode1 : Blue Hour"),
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Weki Meki", "Dazzle Dazzle", ""),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("Everglow", "LA DI DA", ""),
    ("Everglow", "Dun Dun Dance", ""),
    ("Apink", "Dumhdurum", "Look"),
    ("STAYC", "So Bad", "Star To A Young Culture"),
    ("CIX", "My My", ""),
    ("AB6IX", "The Answer", "VIVID"),
    ("IZ*ONE", "Secret Story of the Swan", "Oneiric Diary"),
    ("IZ*ONE", "Panorama", ""),
    ("SuperM", "Tiger Inside", "Super One"),
    ("Taeyeon", "Dear Me", ""),
    ("Woo", "Guilty", "Guilty"),
    ("WINNER", "Remember", ""),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Why Not?", "[12:00]"),
    ("LOONA", "So What", "[#]"),
    ("CHUNG HA", "Stay Tonight", "Querencia"),
    ("CHUNG HA", "Bicycle", "Querencia"),
    ("TREASURE", "MMM", "THE FIRST STEP : CHAPTER THREE"),
    ("TREASURE", "My Treasure", "THE FIRST STEP"),
    ("Bvndit", "Jungle", "Carnival"),
    ("Cherry Bullet", "Hands Up", ""),
    ("Secret Number", "Who Dis?", ""),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
    ("SF9", "Summer Breeze", "Summer Breeze"),
    ("Victon", "Nostalgia", "Nostalgia"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("Super Junior", "2YA2YAO!", "TIMELESS"),
    ("WayV", "Turn Back Time", ""),
    ("Mamamoo", "Dingga", ""),
    ("The Boyz", "Reveal", "Reveal"),
    ("KARD", "GUNSHOT", ""),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("MCND", "nanana", "EARTH AGE"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("10CM", "Your Mountain", "4.3"),
    ("Ben", "From Ben", "Reality"),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("AKMU", "Happening", "HAPPENING"),
    ("Baekhyun", "Candy", "Delight - The 4th Mini Album"),
    ("Zion.T", "No Love", ""),
    ("Heize", "We don't talk together", "We don't talk together"),
    ("Davichi", "Changmin's Not Here", ""),
    ("Zico", "Any Song", ""),
    ("IU", "Blueming", "Love poem"),
    ("Mamamoo", "HIP", ""),
    ("ITZY", "WANNABE", ""),
    ("Kang Daniel", "2U", ""),
    ("TREASURE", "Boy", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
    ("aespa", "Black Mamba", ""),
    ("STAYC", "ASAP", ""),
    ("Brave Girls", "Rollin'", ""),
    ("ENHYPEN", "Drunk-Dazed", "BORDER : CARNIVAL"),
    ("NCT 127", "Kick Back", "NCT RESONANCE Pt. 2"),
    ("NCT U", "90's Love", "Resonance Pt. 1"),
    ("NCT U", "Work It", "Resonance Pt. 1"),
    ("GOT7", "Last Piece", "Breath of Love : Last Piece"),
    ("GOT7", "Breath", "Breath of Love : Last Piece"),
    ("SEVENTEEN", "HOME;RUN", "Heng:garæ"),
    ("BTOB", "Blue Moon", "Feel'eM"),
    ("Highlight", "Not The End", "The Blowing"),
    ("Apink", "Dumhdurum", "Look"),
    ("GFRIEND", "MAGO", "回:Walpurgis Night"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("MOMOLAND", "Ready or Not", "Ready or Not"),
    ("CLC", "HELICOPTER", "HELICOPTER"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("VIXX", "Revolution", "CONTACT"),
    ("INFINITE", "Why Why", "Why Why"),
    ("ASTRO", "One", "ONEWE"),
    ("SF9", "Summer Breeze", "Summer Breeze"),
    ("Golden Child", "ONE (Lucid Dream)", "Golden Age"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Star", "[#]"),
    ("WJSN", "My Type", "Neverland"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("Cherry Bullet", "Hands Up", ""),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("AB6IX", "The Answer", "VIVID"),
    ("CIX", "My My", ""),
    ("EVERGLOW", "LA DI DA", ""),
    ("ITZY", "Not Shy", ""),
    ("Sunmi", "Gotta Go", "WARNING"),
    ("Paul Kim", "Me After You", ""),
    ("Sam Kim", "Make Up", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("DAY6", "Zombie", "The Book of Us : The Demon"),
    ("DAY6", "Love me or Leave me", "The Book of Us : The Demon"),
    ("N.Flying", "Oh really?", "So, 通"),
    ("ONEWE", "Tag Me (@Me)", "ONE"),
    ("VERIVERY", "Thunder", "Truth or Dare"),
    ("D1CE", "HATE YOU", "Wake Up"),
    ("OnlyOneOf", "libidO", "Instinct, Part. 1"),
    ("BoA", "Better", "Better - The 10th Album"),
    ("Taeyeon", "Spark", "Purpose - The 2nd Studio Album"),
    ("Hwa Sa", "Maria", "Maria"),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Crush", "None", ""),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Primary", "When I Was Young", "2"),
    ("Gary", "Sunrise", "2002"),
    ("BewhY", "Day Day", ""),
    ("Mad Clown", "Fire", ""),
    ("Huh Gak", "Spring Rain", ""),
    ("Ailee", "If You", "VIVID"),
    ("Son Seung Yeon", "A Person Like You", ""),
    ("Jung Seung Hwan", "The Fan", ""),
    ("Rain", "GANG", ""),
    ("PSY", "New Face", "4X2=8"),
    ("Teen Top", "Missing", "Red Point"),
    ("B.A.P", "Honeymoon", "Blue"),
    ("CNBLUE", "Between Us", "7°CN"),
    ("FTISLAND", "Wind", "OVER 10 YEARS"),
    ("N.Flying", "Real Love", "Love in the FLY"),
    ("KNK", "Rain", "KNK SINGLES COLLECTION 265"),
    ("TREASURE", "Going Crazy", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "Come Back Home", "THE FIRST STEP : CHAPTER ONE"),
    ("TREASURE", "Orange", "THE FIRST STEP : CHAPTER TWO"),
    ("TREASURE", "Beautiful", "THE FIRST STEP : TREASURE EFFECT"),
    ("STAYC", "So Bad", "Star To A Young Culture"),
    ("Weeekly", "Tag Me (@Me)", "We are"),
    ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
    ("SECRET NUMBER", "Who Dis?", ""),
    ("ONEUS", "LIT", "LIVED"),
    ("woo!ah!", "Purple", ""),
    ("TRI.BE", "RUB-A-DUM", ""),
    ("PURPLE KISS", "Zombie", ""),
    ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
    ("DRIPPIN", "Young Blood", "Boyhood"),
    ("CLASS:y", "SHUT DOWN", "Day&Night"),
    ("YENA", "SMARTPHONE", "SMARTPHONE"),
    ("BVNDIT", "Jungle", "Carnival"),
    ("TEMPEST", "Bad News", "ON and ON"),
    ("Xdinary Heroes", "Happy Death Day", "Overload"),
    ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
    ("ENHYPEN", "Let Me In (Crown)", "BORDER : CARNIVAL"),
    ("TXT", "Eternally", "The Dream Chapter: ETERNITY"),
    ("ATEEZ", "Answer", "TREASURE EP.Fin : All To Action"),
    ("Stray Kids", "Levanter", "Clé : LEVANTER"),
    ("Stray Kids", "Double Knot", "Clé : LEVANTER"),
    ("NCT 127", "Kick It", "NCT #127 Neo Zone - The 2nd Album"),
    ("NCT DREAM", "Ridin'", "Reload"),
    ("SuperM", "Jopping", "Super One"),
    ("SuperM", "100", "Super One"),
    ("WayV", "Take Off", "Take Off"),
    ("The Boyz", "The Stealer", "THE STEALER"),
    ("KARD", "Dumb Litty", "KARD 4th Mini Album"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("10CM", "Your Mountain", "4.3"),
    ("IU", "eight (Prod.&feat. SUGA of BTS)", "eight"),
    ("BOL4", "Some", ""),
    ("AKMU", "Nakka", "NEXT EPISODE"),
    ("Heize", "HAPPEN", "HAPPEN"),
    ("Mamamoo", "Where Are We Now", "WAW"),
    ("Sunmi", "Gotta Go", "WARNING"),
    ("Taeyeon", "Four Seasons", "Purpose - The 2nd Studio Album"),
    ("Red Velvet", "Zimzalabim", "The ReVe Festival Day 1"),
    ("Red Velvet", "Umpah Umpah", "The ReVe Festival Day 2"),
    ("TWICE", "Fancy", "Fancy You"),
    ("TWICE", "Feel Special", "Feel Special"),
    ("BLACKPINK", "Kill This Love", ""),
    ("BTS", "Boy With Luv", "MAP OF THE SOUL : PERSONA"),
    ("EXO", "Obsession", "OBSESSION - The 6th Album"),
    ("SHINee", "Don't Call Me", "Don't Call Me"),
    ("WINNER", "Ah Yeah", "WE"),
    ("iKON", "Dive", "NEW KIDS : THE FINAL"),
    ("GOT7", "Eclipse", "Spinning Top : Between Security & Insecurity"),
    ("SEVENTEEN", "Home", "An Ode"),
    ("Stray Kids", "MIROH", "Clé 1 : MIROH"),
    ("NCT 127", "Superhuman", "NCT #127 Neo Zone - The 2nd Album"),
    ("NCT DREAM", "BOOM", "We Boom - The 3rd Mini Album"),
    ("GFRIEND", "Crossroads", "回:Song of the Sirens"),
    ("GFRIEND", "Tonight", "回:Song of the Sirens"),
    ("Lovelyz", "Once Upon a Time", "Once Upon a Time"),
    ("MOMOLAND", "Thumbs Up", "Show Me"),
    ("(G)-IDLE", "LION", "I made"),
    ("Sunmi", "LALALAY", "WARNING"),
    ("Taeyeon", "Wine", "Something New - The 3rd Mini Album"),
    ("Sunny Hill", "Monday to Sunday", "The Beginning of New Endings"),
    ("Brown Eyed Girls", "Wonder Woman", "RE_vive"),
    ("2NE1", "Goodbye", ""),
    ("Epik High", "Born Hater", "Shoebox"),
    ("K/DA", "POP/STARS", ""),
    ("Paul Kim", "Me After You", ""),
    ("Sam Kim", "Make Up", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("DAY6", "Sweet Chaos", "The Book of Us : Entropy"),
    ("N.Flying", "Oh really?", "So, 通"),
    ("ONEWE", "Tag Me (@Me)", "ONE"),
    ("VERIVERY", "Thunder", "Truth or Dare"),
    ("D1CE", "HATE YOU", "Wake Up"),
    ("OnlyOneOf", "libidO", "Instinct, Part. 1"),
    ("BoA", "Woman", "ONE SHOT, TWO SHOT"),
    ("Taeyeon", "Spark", "Purpose - The 2nd Studio Album"),
    ("Hwa Sa", "Maria", "Maria"),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Crush", "None", ""),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Primary", "When I Was Young", "2"),
    ("Gary", "Sunrise", "2002"),
    ("BewhY", "Day Day", ""),
    ("Mad Clown", "Fire", ""),
    ("Huh Gak", "Spring Rain", ""),
    ("Ailee", "If You", "VIVID"),
    ("Son Seung Yeon", "A Person Like You", ""),
    ("Jung Seung Hwan", "The Fan", ""),
    ("Rain", "GANG", ""),
    ("PSY", "New Face", "4X2=8"),
]
