# 2025 전용 — global 유일 + 신규 아티스트 1곡 (연도당 100곡 보강)
SPREAD_2025 = [
    ("H1-KEY", "SEOUL (Such a warm feeling)", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("idntt", "Shine", "Shine"),
    ("MADEIN", "LA LUNA", "LA LUNA"),
    ("Geenius", "Lucky", "Lucky"),
    ("RESCENE", "Deja Vu", "Deja Vu"),
    ("Close Your Eyes", "Snowy Summer", "Snowy Summer"),
    ("idntt", "Lucky", "Lucky"),
    ("KiiiKiii", "I Do Me", "I Do Me"),
    ("HUNTR/X", "Golden", "Golden"),
    ("MADEIN", "UNoUE", "UNoUE"),
    ("SAY MY NAME", "WaveWay", "WaveWay"),
    ("CIGNATURE", "Sweetie but not too sweet", "Sweetie but not too sweet"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("ARTMS", "Air", "Dall"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("STAYC", "GPT", "…l"),
    ("Melomance", "TOY", "Romance Express"),
    ("AKMU", "Hero", "Love Episode"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("BIBI", "Lowkey", "Lowkey"),
    ("YENA", "Good Morning", "Good Morning"),
]
