# 2025 발매 트랙 추가 후보 (B-side·신곡·deep cut) — global 유일 확보용

UNIQUE_2025 = [
    ("IVE", "FLIRT", "IVE EMPATHY"),
    ("IVE", "ACCESS", "IVE EMPATHY"),
    ("IVE", "KICK IT", "IVE EMPATHY"),
    ("LE SSERAFIM", "Dirty Little Secret", "HOT"),
    ("LE SSERAFIM", "Ash", "HOT"),
    ("Hearts2Hearts", "Butterflies", "The Chase"),
    ("Hearts2Hearts", "250901", "The Chase"),
    ("BOYNEXTDOOR", "Lucky Charm", "19.99"),
    ("BOYNEXTDOOR", "One and Only", "19.99"),
    ("NCT WISH", "Steady", "Steady - The 1st Mini Album"),
    ("NCT WISH", "Songbird", "Steady - The 1st Mini Album"),
    ("NCT DREAM", "When I'm With You", "DREAM()SCAPE"),
    ("NCT DREAM", "Carat Cake", "DREAM()SCAPE"),
    ("Jisoo", "Earthquake", "AMORTAGE"),
    ("Jisoo", "Your Love", "AMORTAGE"),
    ("Jisoo", "Tears", "AMORTAGE"),
    ("BABYMONSTER", "WE GO UP", "WE GO UP"),
    ("BABYMONSTER", "CLIK CLAK", "WE GO UP"),
    ("BABYMONSTER", "Love In My Heart", "WE GO UP"),
    ("ALLDAY PROJECT", "FAMOUS", "FAMOUS"),
    ("ALLDAY PROJECT", "WICKED", "FAMOUS"),
    ("MEOVV", "TOXIC", "MY EYES OPEN VVIDE"),
    ("MEOVV", "Hands Up", "MY EYES OPEN VVIDE"),
    ("MEOVV", "Drop Off", "MY EYES OPEN VVIDE"),
    ("ILLIT", "IYKYK", "I'll Like You"),
    ("ILLIT", "blink", "I'll Like You"),
    ("TWS", "OVERDRIVE", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("TWS", "Countdown!", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("TWS", "Unbeatable", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("KATSEYE", "My Way", "Touch"),
    ("KATSEYE", "Gameboy", "Touch"),
    ("KATSEYE", "Gnarly", "Touch"),
    ("Stray Kids", "CEREMONY", "合 (HOP)"),
    ("Stray Kids", "Railway (Bang Chan)", "合 (HOP)"),
    ("Stray Kids", "Truman", "合 (HOP)"),
    ("TWICE", "Strategy (feat. Megan Thee Stallion)", "STRATEGY"),
    ("TWICE", "Killing Me Good", "STRATEGY"),
    ("TWICE", "The Reason Why", "STRATEGY"),
    ("ITZY", "Imaginary Friend", "GOLD"),
    ("ITZY", "Escalator", "GOLD"),
    ("NMIXX", "Know About Me", "Fe3O4: FORWARD"),
    ("NMIXX", "High Horse", "Fe3O4: FORWARD"),
    ("NMIXX", "Poke A Hole", "Fe3O4: FORWARD"),
    ("RIIZE", "Fly Up", "ODYSSEY - The 1st Album"),
    ("RIIZE", "Show Me Love", "ODYSSEY - The 1st Album"),
    ("RIIZE", "Passionfruit", "ODYSSEY - The 1st Album"),
    ("ZEROBASEONE", "Blue", "You had me at HELLO"),
    ("ZEROBASEONE", "Devil Game", "You had me at HELLO"),
    ("ENHYPEN", "Bad Desire (With or Without You)", "DESIRE : UNLEASH"),
    ("ENHYPEN", "Brought The Heat Back", "DESIRE : UNLEASH"),
    ("TXT", "The Star Chapter: SANCTUARY", "The Star Chapter: SANCTUARY"),
    ("TXT", "Over The Moon", "The Star Chapter: SANCTUARY"),
    ("G-DRAGON", "HOME SWEET HOME (feat. TAEYANG & DAESUNG)", "Übermensch"),
    ("G-DRAGON", "TOO BAD (feat. Anderson .Paak)", "Übermensch"),
    ("G-DRAGON", "POWER", "Übermensch"),
    ("G-DRAGON", "TAKE ME", "Übermensch"),
    ("G-DRAGON", "IBELONGIIU", "Übermensch"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("JENNIE", "Mantra", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Rosé", "number one girl", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("Lisa", "Rockstar", "Alter Ego"),
    ("KickFlip", "Knock Knock", "Flip Code"),
    ("KickFlip", "Umm Great Minds", "Flip Code"),
    ("XLOV", "I feat. Megan Thee Stallion", "I"),
    ("XLOV", "BiiiP", "I"),
    ("n.SSign", "Love Potion", "Love Potion"),
    ("n.SSign", "Shinyu", "Love Potion"),
    ("AHOF", "Gotcha", "Gotcha"),
    ("AHOF", "Double Up", "Gotcha"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("FIFTY FIFTY", "Starry Night", "Love Tune"),
    ("PLAVE", "Dash", "Caligo Pt.1"),
    ("PLAVE", "BBUU!", "Caligo Pt.1"),
    ("xikers", "Red Sun", "HOUSE OF TRICKY : Trickster"),
    ("xikers", "Superpower", "HOUSE OF TRICKY : Trickster"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("TREASURE", "LAST NIGHT", "LAST NIGHT"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("ATEEZ", "WORK", "THE WORLD EP.Fin : WILL"),
    ("SEVENTEEN", "LOVE, MONEY, FAME", "SEVENTEENTH HEAVEN"),
    ("NCT 127", "Walk", "WALK - The 6th Album"),
    ("NCT 127", "Fact Check", "Fact Check - The 5th Album"),
    ("Super Junior", "Lux", "Super Junior25"),
    ("SHINee", "poi", "poi - The 8th Album"),
    ("WayV", "She A Wolf", "Give Me That"),
    ("EXO", "Cream Soda", "EXIST - The 7th Album"),
    ("Red Velvet", "Sweet Dreams", "Cosmic - The 1st Mini Album"),
    ("Dreamcatcher", "Justice", "VillainS"),
    ("fromis_9", "From", "From"),
    ("OH MY GIRL", "Classified", "Dreamy Resonance"),
    ("Apink", "Dilemma", "HORN"),
    ("STAYC", "GPT", "…l"),
    ("VIVIZ", "MANIAC", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "EUNOIA", "the Billage of perception: chapter three"),
    ("Heize", "Fallin'", "Fallin'"),
    ("10CM", "To Reach You", "4.3"),
    ("Crush", "Rush Hour", ""),
    ("BIBI", "Lowkey", "Lowkey"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("AKMU", "Hero", "Love Episode"),
    ("Melomance", "TOY", "Romance Express"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("KATSEYE", "Debut", "Debut"),
    ("KATSEYE", "Touch", "Touch"),
    ("WOOAH", "BLAH BLAH BLAH", "BLAH BLAH BLAH"),
    ("MEOVV", "MEOW", "MEOW"),
    ("MEOVV", "BODY", "MEOW"),
    ("BOYNEXTDOOR", "But I Like You", "HOW?"),
    ("ZEROBASEONE", "Good So Bad", "You had me at HELLO"),
    ("NMIXX", "See That?", "Fe3O4: BREAK"),
    ("ENHYPEN", "No Doubt", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu (Anxiety)", "The Name Chapter: FREEFALL"),
    ("KISS OF LIFE", "Sticky", "Sticky"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("fromis_9", "Supersonic", "From"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("Young Posse", "XX", "XX"),
    ("Young Posse", "Ate That", "Ate That"),
    ("KISS OF LIFE", "Midas Touch", "Midas Touch"),
    ("(G)-IDLE", "Wife", "2"),
    ("Taeyeon", "To. X", "To. X - The 5th Mini Album"),
    ("IU", "Holssi", "The Winning"),
    ("Melomance", "Look In Love", "Look In Love"),
    ("BOYNEXTDOOR", "So let's go see the stars", "HOW?"),
    ("NCT WISH", "Songbird", "Steady - The 1st Mini Album"),
    ("Stray Kids", "Hall of Fame", "ATE"),
    ("NewJeans", "Supernatural", "Supernatural"),
    ("IVE", "Accendio", "IVE SWITCH"),
    ("N.Flying", "Bye Bye Bye", "FLY HIGH PROJECT #5"),
    ("VERIVERY", "Crazy Like That", "Lost and Found"),
    ("Apink", "Remind me", "Selfish"),
    ("BTOB", "Dear My Lover", "Be Together"),
    ("Highlight", "Always You", "The Blowing"),
    ("INFINITE", "The Origin", "13egin"),
    ("VIXX", "G.R.I.T.", "CONTACT"),
    ("TNX", "For What", "For What?"),
    ("TRENDZ", "Groove", "New Daybreak"),
    ("WEi", "Thriller", "2nd Mini Album [Love Syndrome]"),
    ("ONEWE", "Gravity", "Planet Nine : VOYAGER"),
    ("ONF", "Bye My Minimal", "Bye My Minimal"),
    ("DKZ", "Harmony", "Harmony"),
    ("TEMPEST", "My World", "TEMPEST Voyage"),
    ("DRIPPIN", "Home", "FIRST LOVE"),
    ("CRAVITY", "Now or Never", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("P1Harmony", "More Than Words", "Killin' It"),
    ("SF9", "Puzzle", "Sequence"),
    ("Golden Child", "Cocktail", "Feel Me"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("QWER", "Discord", "1st Mini Album 'MANITO'"),
    ("QWER", "T.B.H", "1st Mini Album 'MANITO'"),
    ("QWER", "My Name is Dolores", "1st Mini Album 'MANITO'"),
    ("tripleS", "Girls' Capitalism", "ASSEMBLE24"),
    ("tripleS", "Cherry Talk", "AESTHETIC"),
    ("tripleS", "Invincible", "ASSEMBLE24"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("UNIS", "Curious", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("ARTMS", "Air", "Dall"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("DAY6", "Welcome to the Show", "Fourever"),
    ("DAY6", "HAPPY", "Fourever"),
    ("DAY6", "The Power of Love", "Fourever"),
    ("Paul Kim", "Me After You", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Crush", "None", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Davichi", "First Winter", ""),
    ("Urban Zakapa", "When We Were Two", "02"),
    ("10CM", "Spring Snow", "4.3"),
    ("Punch", "Losing Sleep", ""),
    ("Roy Kim", "Only Then", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("SECRET NUMBER", "Toxic", "DOXIT"),
    ("TRI.BE", "Diamond", "Diamond"),
    ("Cherry Bullet", "Love in Space", "Love in Space"),
    ("Rocket Punch", "BOOM", "BOOM"),
    ("DRIPPIN", "One Kind", "Villain - The Zero"),
    ("CLASS:y", "Tick Tick Bomb", "Day&Night"),
    ("woo!ah!", "Rollercoaster", "Rollercoaster"),
    ("PURPLE KISS", "7HEAVEN", "Geekyland"),
    ("LIGHTSUM", "Honey or Spice", "Honey or Spice"),
    ("H1-KEY", "Rose Blossom", "Rose Blossom"),
    ("VIVIZ", "PULL UP", "VarioUS"),
    ("fromis_9", "Menow", "Unlock My World"),
    ("Dreamcatcher", "BON VOYAGE", "Apocalypse : Follow us"),
    ("OH MY GIRL", "Summer Comes", "Golden Hourglass"),
    ("TREASURE", "MOVE", "REBOOT"),
    ("THE BOYZ", "ROAR", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.1 Christmas In August"),
    ("ATEEZ", "BOUNCY (K-HOT CHILI PEPPERS)", "THE WORLD EP.2 : OUTLAW"),
    ("ONEUS", "Same Scent", "MALUS"),
    ("TEMPEST", "Voyage", "ON and ON"),
    ("Xdinary Heroes", "Break the Brake", "Overload"),
    ("KARD", "ICKY", "ICKY"),
    ("RIIZE", "Get A Guitar", "Get A Guitar"),
    ("RIIZE", "Talk Saxy", "Talk Saxy"),
    ("BOYNEXTDOOR", "One and Only", "WHO!"),
    ("BOYNEXTDOOR", "But Sometimes", "WHO!"),
    ("ZEROBASEONE", "In Bloom", "YOUTH IN THE SHADE"),
    ("ZEROBASEONE", "Crush", "YOUTH IN THE SHADE"),
    ("NCT DOJAEJUNG", "Perfume", "Perfume - The 1st Mini Album"),
    ("P1Harmony", "Killin' It", "Killin' It"),
    ("CRAVITY", "Groovy", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("BABYMONSTER", "Batter Up", ""),
    ("BABYMONSTER", "Stuck In The Middle", ""),
    ("KISS OF LIFE", "Shhh", "Shhh"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("MAMAMOO+", "Dangdang", "Two Rabbits"),
    ("Hwa Sa", "I Love My Body", "I Love My Body"),
    ("Sunmi", "Stranger", "STRANGER"),
    ("AKMU", "Love Lee", "Love Lee"),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("TWICE", "Moonlight Sunrise", "MOONLIGHT SUNRISE"),
    ("Fifty Fifty", "Cupid", "The Beginning"),
    ("Jungkook", "Standing Next to You", "GOLDEN"),
    ("V", "Love Me Again", "Layover"),
    ("Jimin", "Like Crazy", "FACE"),
    ("Jisoo", "Flower", "ME"),
    ("STAYC", "Teddy Bear", "Teddy Bear"),
    ("ITZY", "CAKE", "KILL MY DOUBT"),
    ("TWICE", "SET ME FREE", "READY TO BE"),
    ("Red Velvet", "Chill Kill", "Chill Kill - The 3rd Album"),
    ("NMIXX", "Love Me Like This", "expérgo"),
    ("Kep1er", "Giddy", "Girls Planet - Kepler : THE 3rd Mini Album"),
    ("NCT U", "Baggy Jeans", "Golden Age - The 4th Album"),
    ("SHINee", "Hard", "HARD - The 8th Album"),
    ("MAMAMOO+", "GGBB", "Two Rabbits"),
    ("ENHYPEN", "XO (Only If You Say Yes)", "ROMANCE : UNTOLD"),
    ("TXT", "Deja Vu", "The Name Chapter: FREEFALL"),
    ("NCT DREAM", "Smoothie", "DREAM()SCAPE"),
    ("NCT WISH", "Wish", "NCT WISH - The 1st Mini Album"),
    ("SEVENTEEN", "MAESTRO", "17 IS RIGHT HERE"),
    ("Stray Kids", "Chk Chk Boom", "ATE"),
    ("STAYC", "1 Thing", "…l"),
    ("ITZY", "Untouchable", "BORN TO BE"),
    ("ITZY", "GOLD", "GOLD"),
    ("TWICE", "ONE SPARK", "With YOU-th"),
    ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
    ("BABYMONSTER", "Sheesh", "DRIP"),
    ("BABYMONSTER", "Forever", "DRIP"),
    ("RIIZE", "Love 119", "Love 119"),
    ("RIIZE", "Impossible", "Impossible"),
    ("BOYNEXTDOOR", "Earth, Wind & Fire", "HOW?"),
    ("BOYNEXTDOOR", "Nice Guy", "19.99"),
    ("ZEROBASEONE", "Feel the POP", "You had me at HELLO"),
    ("ZEROBASEONE", "SWEAT", "You had me at HELLO"),
    ("NMIXX", "Soñar (Breaker)", "Fe3O4: BREAK"),
    ("LE SSERAFIM", "Smart", "CRAZY"),
    ("LE SSERAFIM", "CRAZY", "CRAZY"),
    ("Jennie", "Mantra", "Ruby"),
    ("Rosé & Bruno Mars", "APT.", ""),
    ("NewJeans", "How Sweet", "How Sweet"),
    ("NewJeans", "Bubble Gum", "How Sweet"),
    ("aespa", "Supernova", "Armageddon - The 1st Album"),
    ("aespa", "Armageddon", "Armageddon - The 1st Album"),
    ("aespa", "Whiplash", "Whiplash - The 5th Mini Album"),
    ("aespa", "Dirty Work", "Whiplash - The 5th Mini Album"),
    ("IVE", "HEYA", "IVE EMPATHY"),
    ("(G)-IDLE", "Super Lady", "2"),
    ("(G)-IDLE", "Klaxon", "I SWAY"),
    ("TWS", "plot twist", "TWS 1st Mini Album 'Sparkling Blue'"),
    ("TWS", "hey hey hey", "TWS 2nd Mini Album 'SUMMER BEAT!'"),
    ("ILLIT", "Magnetic", "SUPER REAL ME"),
    ("ILLIT", "Lucky Girl Syndrome", "SUPER REAL ME"),
    ("ILLIT", "Cherish (My Love)", "I'll Like You"),
    ("THE BOYZ", "MAESTRO", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("Jimin", "Who", "MUSE"),
    # 추가 2025 B-side / deep cut (global 유일 확보)
    ("Hearts2Hearts", "Butterflies", "The Chase"),
    ("Hearts2Hearts", "250901", "The Chase"),
    ("IVE", "REBEL HEART", "IVE EMPATHY"),
    ("LE SSERAFIM", "HOT", "HOT"),
    ("BOYNEXTDOOR", "If I Say, I Love You", "19.99"),
    ("ALLDAY PROJECT", "FAMOUS", "FAMOUS"),
    ("CORTIS", "GO!", "COLOR OUTSIDE THE LINES"),
    ("UNIS", "SUPERWOMAN", "WE UNIS"),
    ("ARTMS", "Virtual Angel", "Dall"),
    ("tripleS", "Invincible", "ASSEMBLE24"),
    ("QWER", "My Name is Dolores", "1st Mini Album 'MANITO'"),
    ("DAY6", "Melt Down", "Fourever"),
    ("NCT 127", "Intro : Wall", "WALK - The 6th Album"),
    ("NCT 127", "Angel Eyes", "WALK - The 6th Album"),
    ("NCT DREAM", "Carat Cake", "DREAM()SCAPE"),
    ("NCT WISH", "Steady", "Steady - The 1st Mini Album"),
    ("WayV", "Give Me That", "Give Me That"),
    ("WayV", "She A Wolf", "Give Me That"),
    ("Super Junior", "Lux", "Super Junior25"),
    ("Super Junior", "Show Time", "Super Junior25"),
    ("TVXQ!", "Reboot", "Reboot"),
    ("SHINee", "poi", "poi - The 8th Album"),
    ("SHINee", "The Feeling", "poi - The 8th Album"),
    ("EXO", "Hear Me Out", "EXIST - The 7th Album"),
    ("Red Velvet", "Cosmic", "Cosmic - The 1st Mini Album"),
    ("Wendy", "Wish You Hell", "Wish You Hell - The 2nd Mini Album"),
    ("Seulgi", "Baby, Not Baby", "HAPPY - Seulgi - The 1st Mini Album"),
    ("Taeyeon", "Heaven", "Heaven - The 5th Mini Album"),
    ("Sunmi", "Balloon in Love", "Balloon in Love"),
    ("Hwa Sa", "Good Goodbye", "Good Goodbye"),
    ("MAMAMOO", "MY CON", "MY CON the movie - original soundtrack"),
    ("STAYC", "1 Thing", "…l"),
    ("VIVIZ", "Shhh!", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "ring ma Bell", "the Billage of perception: chapter three"),
    ("fromis_9", "Supersonic", "From"),
    ("Dreamcatcher", "OOTD", "VillainS"),
    ("OH MY GIRL", "Fall in Love", "Dreamy Resonance"),
    ("Apink", "Remind me", "Selfish"),
    ("H1-KEY", "Let It Be", "H1-KEY 4th Mini Album [Lovestruck]"),
    ("Kep1er", "Shooting Star", "Girls Planet - Kepler : THE 6th Mini Album"),
    ("CLASS:y", "Winter Bloom", "Day&Night"),
    ("YENA", "Good Morning", "Good Morning"),
    ("WOODZ", "Drowning", "OO-LI"),
    ("PENTAGON", "Feelin' Like", "IN:VITE U"),
    ("Weeekly", "Vroom Vroom", "ColoRise"),
    ("Cherry Bullet", "POW!", "Cherry Dash"),
    ("SECRET NUMBER", "Don't Touch", "DOXIT"),
    ("KARD", "CAKE", "Where To Now? (Part 1 : Yellow Light)"),
    ("Xdinary Heroes", "PLUTO", "Troubleshooting"),
    ("TREASURE", "KING KONG", "SPECIAL MINI ALBUM [PLEASURE]"),
    ("THE BOYZ", "Trigger", "THE BOYZ 2nd ALBUM [PHANTASY] Pt.2 Spellbound"),
    ("ATEEZ", "Ice On My Teeth", "THE WORLD EP.Fin : WILL"),
    ("MONSTA X", "Do What I Want", "REASON"),
    ("P1Harmony", "It's Alright", "Killin' It"),
    ("CRAVITY", "Love or Die", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("SF9", "BIBORA", "BIBORA"),
    ("Golden Child", "Feel Me", "Feel Me"),
    ("ONEUS", "Now", "NOW"),
    ("TEMPEST", "LIGHTHOUSE", "TEMPEST Voyage"),
    ("DRIPPIN", "FIRST LOVE", "FIRST LOVE"),
    ("PLAVE", "WAY 4 LUV", "ASTERUM : Way-Pt.1"),
    ("xikers", "HOME BOY", "HOUSE OF TRICKY : Trial And Error"),
    ("FIFTY FIFTY", "SOS", "Love Tune"),
    ("Melomance", "TOY", "Romance Express"),
    ("AKMU", "Hero", "Love Episode"),
    ("Crush", "Love You With All My Heart", "wonderlost"),
    ("BIBI", "Bam Yang Gang", "Bam Yang Gang"),
    ("Lim Young Woong", "Do or Die", "IM HERO"),
    ("Taeyang", "Seed", "Down to Earth"),
    ("JENNIE", "Seoul City", "Ruby"),
    ("Rosé", "drinks or coffee", "rosie"),
    ("Lisa", "New Woman", "Alter Ego"),
    ("Paul Kim", "Me After You", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
    ("Loco", "Weak", ""),
    ("Gray", "Real Love", ""),
    ("Crush", "None", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Ben", "From Ben", "Reality"),
    ("Davichi", "First Winter", ""),
    ("Urban Zakapa", "When We Were Two", "02"),
    ("10CM", "Spring Snow", "4.3"),
    ("Punch", "Losing Sleep", ""),
    ("Roy Kim", "Only Then", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("N.Flying", "Bye Bye Bye", "FLY HIGH PROJECT #5"),
    ("VERIVERY", "Crazy Like That", "Lost and Found"),
    ("BTOB", "Dear My Lover", "Be Together"),
    ("Highlight", "Always You", "The Blowing"),
    ("INFINITE", "The Origin", "13egin"),
    ("VIXX", "G.R.I.T.", "CONTACT"),
    ("TNX", "For What", "For What?"),
    ("TRENDZ", "Groove", "New Daybreak"),
    ("WEi", "Thriller", "2nd Mini Album [Love Syndrome]"),
    ("ONEWE", "Gravity", "Planet Nine : VOYAGER"),
    ("ONF", "Bye My Minimal", "Bye My Minimal"),
    ("DKZ", "Harmony", "Harmony"),
    ("TEMPEST", "My World", "TEMPEST Voyage"),
    ("DRIPPIN", "Home", "FIRST LOVE"),
    ("CRAVITY", "Now or Never", "SUN WAVE : UNDER THE SUNLIGHT"),
    ("P1Harmony", "More Than Words", "Killin' It"),
    ("SF9", "Puzzle", "Sequence"),
    ("Golden Child", "Cocktail", "Feel Me"),
    ("Young Posse", "Ate That", "Ate That"),
    ("STAYC", "Cheeky Icy Thang", "…l"),
    ("ITZY", "None of My Business", "KILL MY DOUBT"),
    ("KickFlip", "Knock Knock", "Flip Code"),
    ("XLOV", "I feat. Megan Thee Stallion", "I"),
    ("n.SSign", "Love Potion", "Love Potion"),
    ("AHOF", "Gotcha", "Gotcha"),
    ("FIFTY FIFTY", "Starry Night", "Love Tune"),
    ("PLAVE", "BBUU!", "Caligo Pt.1"),
    ("xikers", "Superpower", "HOUSE OF TRICKY : Trickster"),
    ("G-DRAGON", "IBELONGIIU", "Übermensch"),
    ("ENHYPEN", "Brought The Heat Back", "DESIRE : UNLEASH"),
    ("TXT", "Over The Moon", "The Star Chapter: SANCTUARY"),
    ("ZEROBASEONE", "Devil Game", "You had me at HELLO"),
    ("RIIZE", "Passionfruit", "ODYSSEY - The 1st Album"),
    ("NMIXX", "Poke A Hole", "Fe3O4: FORWARD"),
    ("ITZY", "Escalator", "GOLD"),
    ("TWICE", "The Reason Why", "STRATEGY"),
    ("Stray Kids", "Truman", "合 (HOP)"),
    ("KATSEYE", "Gnarly", "Touch"),
    ("TWS", "Unbeatable", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("MEOVV", "Drop Off", "MY EYES OPEN VVIDE"),
    ("ILLIT", "blink", "I'll Like You"),
    ("BABYMONSTER", "Love In My Heart", "WE GO UP"),
    ("Jisoo", "Tears", "AMORTAGE"),
    ("ALLDAY PROJECT", "WICKED", "FAMOUS"),
    ("LE SSERAFIM", "Ash", "HOT"),
    ("IVE", "KICK IT", "IVE EMPATHY"),
    # 2025 신인·B-side (global 유일 보강)
    ("Geenius", "Our Style", "Our Style"),
    ("RESCENE", "Glow Up", "Glow Up"),
    ("WAKER", "Mission", "Mission"),
    ("NEXZ", "Riding a Wind", "Riding a Wind"),
    ("LUN8", "Wild Heart", "Wild Heart"),
    ("TIOT", "KickinIt", "KickinIt"),
    ("xikers", "ICONIC", "HOUSE OF TRICKY : Trickster"),
    ("POW", "Boyfriend", "Boyfriend"),
    ("EVNNE", "Hot Mess", "Hot Mess"),
    ("AMPERS&ONE", "Hearts 2 Hearts", "ONE QUESTION"),
    ("B.D.U", "TAKEDOWN", "TAKEDOWN"),
    ("NOWZ", "Fly To The Youth", "Fly To The Youth"),
    ("TWS", "Unbeatable", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("BOYNEXTDOOR", "Lucky Charm", "19.99"),
    ("BOYNEXTDOOR", "If I Say, I Love You", "19.99"),
    ("Hearts2Hearts", "The Chase", "The Chase"),
    ("Hearts2Hearts", "Butterflies", "The Chase"),
    ("Hearts2Hearts", "250901", "The Chase"),
    ("KickFlip", "Knock Knock", "Flip Code"),
    ("KickFlip", "Umm Great Minds", "Flip Code"),
    ("XLOV", "I feat. Megan Thee Stallion", "I"),
    ("XLOV", "BiiiP", "I"),
    ("n.SSign", "Love Potion", "Love Potion"),
    ("n.SSign", "Shinyu", "Love Potion"),
    ("AHOF", "Gotcha", "Gotcha"),
    ("AHOF", "Double Up", "Gotcha"),
    ("G-DRAGON", "IBELONGIIU", "Übermensch"),
    ("ENHYPEN", "Brought The Heat Back", "DESIRE : UNLEASH"),
    ("TXT", "Over The Moon", "The Star Chapter: SANCTUARY"),
    ("ZEROBASEONE", "Devil Game", "You had me at HELLO"),
    ("RIIZE", "Passionfruit", "ODYSSEY - The 1st Album"),
    ("NMIXX", "Poke A Hole", "Fe3O4: FORWARD"),
    ("ITZY", "Escalator", "GOLD"),
    ("TWICE", "The Reason Why", "STRATEGY"),
    ("Stray Kids", "Truman", "合 (HOP)"),
    ("KATSEYE", "Gnarly", "Touch"),
    ("MEOVV", "Drop Off", "MY EYES OPEN VVIDE"),
    ("ILLIT", "blink", "I'll Like You"),
    ("BABYMONSTER", "Love In My Heart", "WE GO UP"),
    ("Jisoo", "Tears", "AMORTAGE"),
    ("ALLDAY PROJECT", "WICKED", "FAMOUS"),
    ("LE SSERAFIM", "Ash", "HOT"),
    ("IVE", "FLIRT", "IVE EMPATHY"),
    ("IVE", "ACCESS", "IVE EMPATHY"),
    ("LE SSERAFIM", "Dirty Little Secret", "HOT"),
    ("FIFTY FIFTY", "Starry Night", "Love Tune"),
    ("PLAVE", "BBUU!", "Caligo Pt.1"),
    ("xikers", "Superpower", "HOUSE OF TRICKY : Trickster"),
    ("NCT 127", "Intro : Wall", "WALK - The 6th Album"),
    ("NCT 127", "Angel Eyes", "WALK - The 6th Album"),
    ("WayV", "Give Me That", "Give Me That"),
    ("Super Junior", "Lux", "Super Junior25"),
    ("Super Junior", "Show Time", "Super Junior25"),
    ("TVXQ!", "Reboot", "Reboot"),
    ("SHINee", "The Feeling", "poi - The 8th Album"),
    ("EXO", "Hear Me Out", "EXIST - The 7th Album"),
    ("Wendy", "Wish You Hell", "Wish You Hell - The 2nd Mini Album"),
    ("Seulgi", "Baby, Not Baby", "HAPPY - Seulgi - The 1st Mini Album"),
    ("Taeyeon", "Heaven", "Heaven - The 5th Mini Album"),
    ("Sunmi", "Balloon in Love", "Balloon in Love"),
    ("Hwa Sa", "Good Goodbye", "Good Goodbye"),
    ("VIVIZ", "Shhh!", "The 3rd Mini Album 'VERSUS'"),
    ("Billlie", "ring ma Bell", "the Billage of perception: chapter three"),
    ("Lim Young Woong", "Vertigo", "IM HERO 2"),
    ("Melomance", "Love, Maybe", "Romance Express"),
    ("Jannabi", "poems, dreams, love", "poems, dreams, love"),
    ("DAY6", "The Power of Love", "Fourever"),
    ("NCT WISH", "Songbird", "Steady - The 1st Mini Album"),
    ("BOYNEXTDOOR", "So let's go see the stars", "HOW?"),
    ("Stray Kids", "Hall of Fame", "ATE"),
    ("NewJeans", "Supernatural", "Supernatural"),
    ("IVE", "Accendio", "IVE SWITCH"),
    ("Young Posse", "Ate That", "Ate That"),
    ("KISS OF LIFE", "Midas Touch", "Midas Touch"),
    ("(G)-IDLE", "Wife", "2"),
    ("Taeyeon", "To. X", "To. X - The 5th Mini Album"),
    ("IU", "Holssi", "The Winning"),
    ("Melomance", "Look In Love", "Look In Love"),
    ("QWER", "My Name is Dolores", "1st Mini Album 'MANITO'"),
    ("tripleS", "Invincible", "ASSEMBLE24"),
    ("CORTIS", "What You Want", "COLOR OUTSIDE THE LINES"),
    ("ARTMS", "Air", "Dall"),
    ("UNIS", "Curious", "WE UNIS"),
    ("WOOAH", "BLUSH", "BLUSH"),
    ("MEOVV", "TOXIC", "MY EYES OPEN VVIDE"),
    ("MEOVV", "Hands Up", "MY EYES OPEN VVIDE"),
    ("ILLIT", "IYKYK", "I'll Like You"),
    ("TWS", "OVERDRIVE", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("TWS", "Countdown!", "TWS 3rd Mini Album 'TRY WITH US'"),
    ("KATSEYE", "My Way", "Touch"),
    ("KATSEYE", "Gameboy", "Touch"),
    ("Stray Kids", "CEREMONY", "合 (HOP)"),
    ("Stray Kids", "Railway (Bang Chan)", "合 (HOP)"),
    ("NMIXX", "Know About Me", "Fe3O4: FORWARD"),
    ("NMIXX", "High Horse", "Fe3O4: FORWARD"),
    ("RIIZE", "Fly Up", "ODYSSEY - The 1st Album"),
    ("RIIZE", "Show Me Love", "ODYSSEY - The 1st Album"),
    ("ZEROBASEONE", "Blue", "You had me at HELLO"),
    ("ENHYPEN", "Bad Desire (With or Without You)", "DESIRE : UNLEASH"),
    ("TXT", "The Star Chapter: SANCTUARY", "The Star Chapter: SANCTUARY"),
    ("G-DRAGON", "HOME SWEET HOME (feat. TAEYANG & DAESUNG)", "Übermensch"),
    ("G-DRAGON", "TOO BAD (feat. Anderson .Paak)", "Übermensch"),
    ("G-DRAGON", "POWER", "Übermensch"),
    ("G-DRAGON", "TAKE ME", "Übermensch"),
    ("JENNIE", "Mantra", "Ruby"),
    ("Rosé", "number one girl", "rosie"),
    ("Lisa", "Rockstar", "Alter Ego"),
    ("Jisoo", "Earthquake", "AMORTAGE"),
    ("Jisoo", "Your Love", "AMORTAGE"),
    ("BABYMONSTER", "WE GO UP", "WE GO UP"),
    ("BABYMONSTER", "CLIK CLAK", "WE GO UP"),
    ("ALLDAY PROJECT", "FAMOUS", "FAMOUS"),
    ("LE SSERAFIM", "HOT", "HOT"),
    ("IVE", "REBEL HEART", "IVE EMPATHY"),
    ("Hearts2Hearts", "The Chase", "The Chase"),
]

EXTRA_2020 = [
    ("Brave Girls", "Rollin'", ""),
    ("TWICE", "I Can't Stop Me", "Eyes wide open"),
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("aespa", "Black Mamba", ""),
    ("DAY6", "Zombie", "The Book of Us : The Demon"),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Why Not?", "[12:00]"),
    ("Apink", "Dumhdurum", "Look"),
    ("CIX", "My My", ""),
    ("SuperM", "Tiger Inside", "Super One"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("Cherry Bullet", "Hands Up", ""),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Everglow", "LA DI DA", ""),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("Mamamoo", "Dingga", ""),
    ("IU", "eight (Prod.&feat. SUGA of BTS)", "eight"),
    ("BOL4", "Some", ""),
]
