#!/usr/bin/env python3
"""Generate catalog_2017_2019.py with ordered candidate pools (~125+ per year)."""
from pathlib import Path

OUT = Path(__file__).parent / "catalog_2017_2019.py"

CATALOG_2017_2019 = {
    2017: [
        ("IU", "밤편지", "Palette"),
        ("IU", "Palette (feat. G-DRAGON)", "Palette"),
        ("BTS", "봄날", "YOU NEVER WALK ALONE"),
        ("BTS", "DNA", "LOVE YOURSELF 承 'Her'"),
        ("BTS", "MIC Drop", "LOVE YOURSELF 承 'Her'"),
        ("BTS", "Not Today", "YOU NEVER WALK ALONE"),
        ("TWICE", "KNOCK KNOCK", "TWICEcoaster : LANE 2"),
        ("TWICE", "SIGNAL", "SIGNAL"),
        ("TWICE", "LIKEY", "TWICEcoaster : LANE 2"),
        ("TWICE", "Heart Shaker", "Merry & Happy"),
        ("Red Velvet", "Peek-A-Boo", "Perfect Velvet - The 2nd Album"),
        ("Red Velvet", "Rookie", "Rookie - The 4th Mini Album"),
        ("Wanna One", "Energetic", "1-1=0 (NOTHING WITHOUT YOU)"),
        ("Wanna One", "Beautiful", "1-1=0 (NOTHING WITHOUT YOU)"),
        ("Wanna One", "Burn It Up", "1X1=1 (TO BE ZERO)"),
        ("Heize", "너, 구름, 비", "너, 구름, 비"),
        ("Heize", "Jenga", "너, 구름, 비"),
        ("AKMU", "How can I love the heartbreak, you're the one I love", "Summer Episode"),
        ("AKMU", "200%", "PLAY"),
        ("BOL4", "You(=I)", "Red Diary Page.1"),
        ("BOL4", "Way Home", "Red Diary Page.1"),
        ("Taeyeon", "Make Me Love You", "My Voice - The 1st Album"),
        ("Taeyeon", "I Got Love (feat. Dok2)", "My Voice - The 1st Album"),
        ("Sunmi", "Gashina", ""),
        ("Hyuna", "Babe", ""),
        ("EXO", "Ko Ko Bop", "THE WAR - The 4th Album"),
        ("EXO", "Power", "THE WAR - The 4th Album"),
        ("BLACKPINK", "As If It's Your Last", ""),
        ("SEVENTEEN", "Don't Wanna Cry", "Al1"),
        ("SEVENTEEN", "Clap", "TEEN, AGE"),
        ("GOT7", "Never Ever", "7 for 7"),
        ("GOT7", "You Are", "7 for 7"),
        ("NU'EST W", "Where You At", "W, HERE"),
        ("Mamamoo", "Yes I Am", "Purple"),
        ("GFRIEND", "Summer Rain", "Parallel"),
        ("GFRIEND", "Love Whisper", "Parallel"),
        ("Hyukoh", "Tomboy", "24 : How to find true love and happiness"),
        ("Zico", "Artist", "Television"),
        ("Zico", "Any Song", ""),
        ("Crush", "Don't Forget (feat. Whee In)", ""),
        ("DEAN", "instagram", "130 Mood : TRBL"),
        ("Lee Hi", "Breathe", "SEOULITE"),
        ("Park Hyo Shin", "Wild Flower", ""),
        ("Urban Zakapa", "I Don't Love You", "02"),
        ("Davichi", "As Time Goes By", "As Time Goes By"),
        ("10CM", "Phonecert", "4.0"),
        ("Melomance", "Gift", ""),
        ("Standing Egg", "Old Song", "Lip"),
        ("SHINee", "View", "Odd - The 5th Album"),
        ("SHINee", "Tell Me What To Do", "The Story of Light 'Epilogue'"),
        ("WINNER", "REALLY REALLY", "FATE NUMBER FOR"),
        ("WINNER", "FOOL", "FATE NUMBER FOR"),
        ("iKON", "LOVE SCENARIO", "Return"),
        ("iKON", "RUBBER DUCK", "Return"),
        ("Block B", "Yesterday", "Yesterday"),
        ("MONSTA X", "Dramarama", "THE CODE"),
        ("VIXX", "Shangri-La", "Shangri-La"),
        ("INFINITE", "Tell Me", "24/7"),
        ("BTOB", "Movie", "Feel'eM"),
        ("Apink", "Five", "Pink UP"),
        ("SISTAR", "Lonely", "Lonely"),
        ("EXID", "DDD", "Full Moon"),
        ("AOA", "Excuse Me", "Angel's Knock"),
        ("Girls' Generation", "Holiday", "Holiday Night - The 6th Album"),
        ("Girls' Generation", "All Night", "Holiday Night - The 6th Album"),
        ("Taeyang", "So Good", "WHITE NIGHT"),
        ("PSY", "New Face", "4X2=8"),
        ("NCT 127", "Cherry Bomb", "NCT #127 CHERRY BOMB - The 1st Mini Album"),
        ("NCT DREAM", "We Young", "We Young - The 1st Mini Album"),
        ("ASTRO", "Baby", "Winter Dream"),
        ("SF9", "O Sole Mio", "Breaking Sensation"),
        ("PENTAGON", "Runaway", "Pentagon"),
        ("Cosmic Girls", "Happy", "HAPPY MOMENT"),
        ("CLC", "Hobgoblin", "CRYSTYLE"),
        ("Lovelyz", "WoW!", "Fallin' in Love"),
        ("OH MY GIRL", "Secret Garden", "Secret Garden"),
        ("DIA", "Will You Go Out With Me", "LOVE GENERATION"),
        ("Stellar", "Archangels", "Sting"),
        ("UP10TION", "Going Crazy", "Top Secret"),
        ("Berry Good", "Don't Make Me Cry", "Very Berry"),
        ("f(x)", "All Mine", ""),
        ("N.Flying", "Real Love", "Love in the FLY"),
        ("CNBLUE", "Between Us", "7°CN"),
        ("FTISLAND", "Wind", "OVER 10 YEARS"),
        ("Super Junior", "Black Suit", "PLAY - The 8th Album"),
        ("Teen Top", "Missing", "Red Point"),
        ("B.A.P", "Honeymoon", "Blue"),
        ("Rain", "GANG", ""),
        ("Yoon Mi Rae", "Gemini", "Gemini"),
        ("Primary", "When I Was Young", "2"),
        ("Gary", "Sunrise", "2002"),
        ("Loco", "Too Much", ""),
        ("San E", "Me You", ""),
        ("Mad Clown", "Fire", ""),
        ("Ben", "Like a Dream", ""),
        ("Punch", "Stay With Me", ""),
        ("Roy Kim", "Only Then", ""),
        ("Jung Seung Hwan", "The Fan", ""),
        ("Huh Gak", "Spring Rain", ""),
        ("Ailee", "If You", "VIVID"),
        ("Son Seung Yeon", "A Person Like You", ""),
        ("Im Chang Jung", "Home", ""),
        ("Epik High", "Sleeping Beauty", "Shoebox"),
        ("BewhY", "Forever", ""),
        ("Jessi", "Gucci", ""),
        ("Hyolyn", "Blue Moon", "Xperience"),
        ("Soyou", "The Night", ""),
        ("K.Will", "Talk Love", ""),
        ("Chen", "Everytime", ""),
        ("Baekhyun", "Dream", ""),
        ("Wonder Girls", "Why So Lonely", ""),
        ("I.O.I", "Downpour", "miss me?"),
        ("NCT U", "Without You", ""),
        ("VIXX LR", "Whisper", "Beautiful Liar"),
        ("XIA", "Flower", "XIA 4th Album 'XIGNATURE'"),
        ("Gummy", "You Are My Everything", "I Wanna Be With You"),
        ("Lee Juck", "Don't Worry", ""),
        ("NCT U", "From Home", "Resonance Pt. 1"),
        ("Golden Child", "DamDaDi", "Golden Child 1st Mini Album 'Gol-Cha!'"),
        ("ONF", "Complete", "ONF:MY NAME"),
        ("Dreamcatcher", "Good Night", "Nightmare"),
        ("LOONA", "Love & Live", "Love & Live"),
        ("WJSN", "Happy", "Happy Moment"),
        ("Momoland", "Wonderful Love", "Wonderful Love"),
        ("Gfriend", "Rainbow", "Parallel"),
        ("Highlight", "Plz Don't Be Sad", "Can You Feel It?"),
        ("B1A4", "Rollin'", "This Is Us"),
        ("VAV", "Flower (You)", "Under the Moonlight"),
        ("KNK", "Rain", "KNK SINGLES COLLECTION 265"),
        ("SF9", "Still My Lady", "Breaking Sensation"),
        ("Victon", "I'm Fine", "Identity"),
        ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
    ],
    2018: [
        ("iKON", "LOVE SCENARIO", "Return"),
        ("BTS", "Fake Love", "LOVE YOURSELF 轉 'Tear'"),
        ("BTS", "IDOL", "LOVE YOURSELF 結 'Answer'"),
        ("BTS", "Singularity", "LOVE YOURSELF 轉 'Tear'"),
        ("BLACKPINK", "DDU-DU DDU-DU", "SQUARE UP"),
        ("BLACKPINK", "Forever Young", "SQUARE UP"),
        ("TWICE", "What is Love?", "What is Love?"),
        ("TWICE", "Dance The Night Away", "Summer Nights"),
        ("TWICE", "Yes or Yes", "YES or YES"),
        ("TWICE", "TT (Japanese ver.)", "TWICEcoaster : LANE 1"),
        ("IU", "BBIBBI", ""),
        ("IU", "eight (Prod.&feat. SUGA of BTS)", "eight"),
        ("Mamamoo", "Starry Night", "Yellow Flower"),
        ("Mamamoo", "Egotistic", "Red Moon"),
        ("Mamamoo", "Wind flower", "Blue;s"),
        ("BOL4", "Travel", "Travel"),
        ("BOL4", "Starlight", "Travel"),
        ("Red Velvet", "Bad Boy", "The Perfect Red Velvet"),
        ("Red Velvet", "Power Up", "Summer Magic - Special Mini Album"),
        ("Red Velvet", "RBB (Really Bad Boy)", "RBB - The 5th Mini Album"),
        ("Sunmi", "Heroine", "Heroine"),
        ("Sunmi", "Siren", "WARNING"),
        ("Hyuna", "Babe", ""),
        ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
        ("(G)-IDLE", "LATATA", "I am"),
        ("(G)-IDLE", "HANN (Alone)", "I am"),
        ("Taeyeon", "Fine", "Fine - The 1st Single Album"),
        ("Taeyeon", "Four Seasons", "Purpose - The 2nd Studio Album"),
        ("Wanna One", "Boomerang", "1-1=0 (NOTHING WITHOUT YOU)"),
        ("Wanna One", "Light", "1-1=0 (NOTHING WITHOUT YOU)"),
        ("SEVENTEEN", "Oh My!", "YOU MAKE MY DAY"),
        ("SEVENTEEN", "Getting Closer", "YOU MAKE MY DAY"),
        ("GOT7", "Look", "Eyes On You"),
        ("GOT7", "Lullaby", "Present : YOU"),
        ("Stray Kids", "District 9", "I am NOT"),
        ("Stray Kids", "Hellevator", "I am NOT"),
        ("NCT 127", "Regular", "NCT #127 Regular-Irregular - The 1st Album"),
        ("NCT DREAM", "We Go Up", "We Go Up - The 2nd Mini Album"),
        ("EXO", "Tempo", "Don't Mess Up My Tempo - The 2nd Album"),
        ("EXO", "Love Shot", "LOVE SHOT - The Repackage Album"),
        ("SHINee", "Good Evening", "The Story of Light 'Epilogue'"),
        ("SHINee", "I Want You", "The Story of Light 'Epilogue'"),
        ("WINNER", "Everyday", "EVERYD4Y"),
        ("WINNER", "Millions", "EVERYD4Y"),
        ("AKMU", "How can I love the heartbreak, you're the one I love", "Summer Episode"),
        ("Heize", "Jenga", "너, 구름, 비"),
        ("Zico", "Any Song", ""),
        ("DEAN", "D (Half Moon)", "130 Mood : TRBL"),
        ("Crush", "Beautiful", ""),
        ("Lee Hi", "No One", "24°C"),
        ("Park Hyo Shin", "Beautiful Tomorrow", ""),
        ("10CM", "Spring Snow", "4.3"),
        ("Melomance", "You&Me", ""),
        ("Urban Zakapa", "When We Were Two", "02"),
        ("Davichi", "Only You", "Only You"),
        ("Ben", "From Ben", "Reality"),
        ("Punch", "Losing Sleep", ""),
        ("Standing Egg", "Old Song", "Lip"),
        ("Apink", "I'm So Sick", "ONE&Six"),
        ("SISTAR", "Shining Star", "Lonely"),
        ("GFRIEND", "Time for the moon night", "Time for the moon night"),
        ("GFRIEND", "Sunrise", "Time for the moon night"),
        ("OH MY GIRL", "Banana Cha Cha", "Secret Garden"),
        ("Lovelyz", "That Day", "That Day"),
        ("MOMOLAND", "Bboom Bboom", "GREAT!"),
        ("MOMOLAND", "Baam", "Fun to the World"),
        ("CLC", "No", "Amigo"),
        ("Cosmic Girls", "Dreams Come True", "Dreams Come True"),
        ("PENTAGON", "Shine", "Positive"),
        ("MONSTA X", "Jealousy", "THE CONNECT : DEJAVU"),
        ("VIXX", "Scentist", "Conception Ker"),
        ("INFINITE", "Tell Me", "24/7"),
        ("BTOB", "Only one for me", "This Is Us"),
        ("Block B", "Don't Leave", "RECONSTRUCTION"),
        ("ASTRO", "Crazy Sexy Cool", "Dream Part.02"),
        ("SF9", "Mamma Mia!", "Mamma Mia!"),
        ("Golden Child", "Lady", "Miracle"),
        ("ONF", "Complete", "ONF:MY NAME"),
        ("Dreamcatcher", "What", "Escape the Era"),
        ("LOONA", "Butterfly", "[X X]"),
        ("WJSN", "La La Love", "WJ PLEASE?"),
        ("fromis_9", "To Heart", "To. Heart"),
        ("IZ*ONE", "La Vie en Rose", "COLOR*IZ"),
        ("IZ*ONE", "Violeta", "HEART*IZ"),
        ("Cherry Bullet", "Q&A", "Let's Play Cherry Bullet"),
        ("Rocket Punch", "BIM BAM BUM", "Pink Punch"),
        ("AB6IX", "Breathe", "B:COMPLETE"),
        ("CIX", "Movie Star", "HELLO Chapter 1. Hello, Stranger"),
        ("EVERGLOW", "Bon Bon Chocolat", "Arrival of EVERGLOW"),
        ("ITZY", "DALLA DALLA", ""),
        ("ITZY", "ICY", ""),
        ("TXT", "Crown", "The Dream Chapter: STAR"),
        ("ATEEZ", "Hala Hala", "TREASURE EP.2 : Zero To One"),
        ("The Boyz", "Giddy Up", "The Start"),
        ("KARD", "Bomb Bomb", "Bomb Bomb"),
        ("Super Junior", "Lo Siento", "REPLAY"),
        ("WayV", "Regular", "Take Off"),
        ("NCT U", "Boss", "NCT 2018 EMPATHY"),
        ("NCT U", "Yestoday", "NCT 2018 EMPATHY"),
        ("Taemin", "Move", "Move - The 2nd Mini Album"),
        ("Key", "One of Those Nights", "Poet | Artist"),
        ("Kai", "Tempo", "Don't Mess Up My Tempo - The 2nd Album"),
        ("Jennie", "SOLO", "SOLO"),
        ("Rosé", "On The Ground", ""),
        ("PSY", "New Face", "4X2=8"),
        ("Epik High", "Love Love Love", "sleepless in __________"),
        ("BewhY", "Day Day", ""),
        ("Loco", "Weak", ""),
        ("Gray", "Real Love", ""),
        ("Primary", "When I Was Young", "2"),
        ("Yoon Mi Rae", "Gemini", "Gemini"),
        ("Hwa Sa", "Maria", "Maria"),
        ("Jessi", "Down", "Nununu"),
        ("Hyolyn", "Dally", "Xperience"),
        ("Soyou", "The Night", ""),
        ("Chen", "Everytime", ""),
        ("Baekhyun", "Bambi", "Bambi - The 3rd Mini Album"),
        ("Highlight", "Plz Don't Be Sad", "Can You Feel It?"),
        ("NU'EST W", "Dejavu", "W, HERE"),
        ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
        ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
        ("DRIPPIN", "Young Blood", "Boyhood"),
        ("TREASURE", "Going Crazy", "THE FIRST STEP : CHAPTER ONE"),
        ("STAYC", "So Bad", "Star To A Young Culture"),
        ("Weeekly", "Tag Me (@Me)", "We are"),
        ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
        ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
        ("CLASS:y", "SHUT DOWN", "Day&Night"),
        ("YENA", "SMARTPHONE", "SMARTPHONE"),
        ("SECRET NUMBER", "Who Dis?", ""),
        ("BVNDIT", "Jungle", "Carnival"),
        ("ONEUS", "LIT", "LIVED"),
        ("TEMPEST", "Bad News", "ON and ON"),
        ("Xdinary Heroes", "Happy Death Day", "Overload"),
        ("woo!ah!", "Purple", ""),
        ("TRI.BE", "RUB-A-DUM", ""),
        ("PURPLE KISS", "Zombie", ""),
    ],
    2019: [
        ("BTS", "Boy With Luv", "MAP OF THE SOUL : PERSONA"),
        ("BTS", "Make It Right", "MAP OF THE SOUL : PERSONA"),
        ("BTS", "ON", "Map of the Soul : 7"),
        ("BTS", "Black Swan", "Map of the Soul : 7"),
        ("IU", "Blueming", "Love poem"),
        ("IU", "Love poem", "Love poem"),
        ("IU", "Unlucky", "Love poem"),
        ("BLACKPINK", "Kill This Love", ""),
        ("BLACKPINK", "Don't Know What To Do", "Kill This Love"),
        ("TWICE", "Fancy", "Fancy You"),
        ("TWICE", "Feel Special", "Feel Special"),
        ("TWICE", "Breakthrough", "Breakthrough"),
        ("Mamamoo", "HIP", ""),
        ("Mamamoo", "Dingga", ""),
        ("Mamamoo", "Where Are We Now", "WAW"),
        ("Taeyeon", "Four Seasons", "Purpose - The 2nd Studio Album"),
        ("Taeyeon", "Spark", "Purpose - The 2nd Studio Album"),
        ("Sunmi", "Siren", "WARNING"),
        ("Sunmi", "LALALAY", "WARNING"),
        ("Heize", "We don't talk together", "We don't talk together"),
        ("Heize", "HAPPEN", "HAPPEN"),
        ("AKMU", "How can I love the heartbreak, you're the one I love", "Summer Episode"),
        ("AKMU", "Nakka", "NEXT EPISODE"),
        ("BOL4", "Work", "Two Five"),
        ("BOL4", "Warm", "Two Five"),
        ("Red Velvet", "Zimzalabim", "The ReVe Festival Day 1"),
        ("Red Velvet", "Umpah Umpah", "The ReVe Festival Day 2"),
        ("Red Velvet", "Psycho", "'The ReVe Festival' Finale"),
        ("ITZY", "DALLA DALLA", ""),
        ("ITZY", "ICY", ""),
        ("ITZY", "WANNABE", ""),
        ("(G)-IDLE", "Senorita", "I made"),
        ("(G)-IDLE", "Uh-Oh", "I made"),
        ("SEVENTEEN", "Home", "An Ode"),
        ("SEVENTEEN", "Hit", "An Ode"),
        ("Stray Kids", "MIROH", "Clé 1 : MIROH"),
        ("Stray Kids", "Side Effects", "Clé 2 : Yellow Wood"),
        ("GOT7", "Eclipse", "Spinning Top : Between Security & Insecurity"),
        ("NCT 127", "Kick It", "NCT #127 Neo Zone - The 2nd Album"),
        ("NCT DREAM", "BOOM", "We Boom - The 3rd Mini Album"),
        ("EXO", "Obsession", "OBSESSION - The 6th Album"),
        ("EXO", "Monster", "EX'ACT - The 3rd Album"),
        ("SHINee", "Don't Call Me", "Don't Call Me"),
        ("WINNER", "Ah Yeah", "WE"),
        ("WINNER", "Remember", ""),
        ("Zico", "Any Song", ""),
        ("DEAN", "instagram", "130 Mood : TRBL"),
        ("Crush", "None", ""),
        ("Lee Hi", "Hola", ""),
        ("Park Hyo Shin", "Good Goodbye", ""),
        ("10CM", "Your Mountain", "4.3"),
        ("Melomance", "Gift", ""),
        ("Urban Zakapa", "When We Were Two", "02"),
        ("Davichi", "Just the Two of Us", "Just the Two of Us"),
        ("Ben", "From Ben", "Reality"),
        ("Punch", "Through the Night", ""),
        ("Standing Egg", "Old Song", "Lip"),
        ("CHUNG HA", "Snapping", "Flourishing"),
        ("CHUNG HA", "Gotta Go", "Flourishing"),
        ("Kang Daniel", "2U", ""),
        ("Kang Daniel", "Who U Are", ""),
        ("Jessi", "NUNU NANA", ""),
        ("Sunmi", "Pporappippam", ""),
        ("Zion.T", "No Love", ""),
        ("Kim Feel", "All I Do", ""),
        ("Vibe", "Vibe", ""),
        ("Apink", "%%", "Percent"),
        ("GFRIEND", "Sunrise", "Time for the moon night"),
        ("OH MY GIRL", "The Fifth Season (SSoL)", "The Fifth Season"),
        ("Lovelyz", "That Day", "That Day"),
        ("MOMOLAND", "I'm So Hot", "Show Me"),
        ("CLC", "ME", "No.1"),
        ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
        ("MONSTA X", "Follow", "FOLLOW : FIND YOU"),
        ("VIXX", "Parallel", "Conception Ker"),
        ("INFINITE", "Why Why", "Why Why"),
        ("BTOB", "Blue Moon", "Feel'eM"),
        ("ASTRO", "All Night", "All Light"),
        ("SF9", "RPM", "RPM"),
        ("Golden Child", "Lady", "Miracle"),
        ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
        ("LOONA", "Butterfly", "[X X]"),
        ("WJSN", "La La Love", "WJ PLEASE?"),
        ("fromis_9", "Fun!", "FUN FACTORY"),
        ("IZ*ONE", "Violeta", "HEART*IZ"),
        ("IZ*ONE", "FIESTA", "BLOOM*IZ"),
        ("Cherry Bullet", "Hands Up", ""),
        ("Rocket Punch", "Bouncy", "Blue Punch"),
        ("AB6IX", "Blind For Love", "6IX SENSE"),
        ("CIX", "My My", ""),
        ("EVERGLOW", "Adios", "HUSH"),
        ("TXT", "Can't You See Me?", "The Dream Chapter: ETERNITY"),
        ("TXT", "Run Away", "The Dream Chapter: ETERNITY"),
        ("ATEEZ", "Wonderland", "TREASURE EP.Fin : All To Action"),
        ("The Boyz", "D.D.D", "Dreamlike"),
        ("KARD", "Dumb Litty", "KARD 4th Mini Album 'KARD 4th Mini Album 'KARD 4th Mini Album ''"),
        ("Super Junior", "SUPER Clap", "Timeless"),
        ("WayV", "Take Off", "Take Off"),
        ("Taemin", "Move", "Move - The 2nd Mini Album"),
        ("Jennie", "SOLO", "SOLO"),
        ("Epik High", "Rosario", "Epik High Is Here 上 (Part 1)"),
        ("Hwa Sa", "Maria", "Maria"),
        ("Hyolyn", "Dally", "Xperience"),
        ("Soyou", "The Night", ""),
        ("Baekhyun", "Candy", "Delight - The 4th Mini Album"),
        ("Highlight", "Plz Don't Be Sad", "Can You Feel It?"),
        ("NU'EST", "Bet Bet", "The 2nd Album"),
        ("TREASURE", "Boy", "THE FIRST STEP : CHAPTER ONE"),
        ("STAYC", "So Bad", "Star To A Young Culture"),
        ("Weeekly", "Tag Me (@Me)", "We are"),
        ("Billlie", "GingaMingaYo (the strange world)", "the Billage of perception: chapter two"),
        ("SECRET NUMBER", "Who Dis?", ""),
        ("ONEUS", "LIT", "LIVED"),
        ("woo!ah!", "Purple", ""),
        ("TRI.BE", "RUB-A-DUM", ""),
        ("PURPLE KISS", "Zombie", ""),
        ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
        ("aespa", "Black Mamba", ""),
        ("STAYC", "ASAP", ""),
        ("Brave Girls", "Rollin'", ""),
        ("P1Harmony", "Siren", "DISHARMONY : Stand Out"),
        ("CRAVITY", "Break all the Rules", "HIDEOUT: REMEMBER WHO WE ARE - PT.1"),
        ("DRIPPIN", "Young Blood", "Boyhood"),
        ("CLASS:y", "SHUT DOWN", "Day&Night"),
        ("YENA", "SMARTPHONE", "SMARTPHONE"),
        ("BVNDIT", "Jungle", "Carnival"),
        ("TEMPEST", "Bad News", "ON and ON"),
        ("Xdinary Heroes", "Happy Death Day", "Overload"),
        ("LIGHTSUM", "Vivace", "Into The Light AD MOMENTUM"),
        ("NCT U", "Make A Wish (Birthday Song)", "Resonance Pt. 1"),
        ("SuperM", "Jopping", "Super One"),
        ("SuperM", "Tiger Inside", "Super One"),
        ("Victon", "Nostalgia", "Nostalgia"),
        ("ONF", "Summer Poem", "ONF:MY NAME"),
        ("MCND", "nanana", "EARTH AGE"),
        ("A.C.E", "Favorite Boys", "HIGHER"),
        ("WEi", "Dondododo (Don't Hold Back)", ""),
        ("Im Chang-jung", "Nothing Like You", ""),
        ("Standing Egg", "Confession", "With Her"),
        ("Roy Kim", "Only Then", ""),
        ("Primary", "When I Was Young", "2"),
        ("Gary", "Sunrise", "2002"),
        ("Loco", "Weak", ""),
        ("Gray", "Real Love", ""),
        ("BewhY", "Day Day", ""),
        ("Mad Clown", "Fire", ""),
        ("Huh Gak", "Spring Rain", ""),
        ("Ailee", "If You", "VIVID"),
        ("Son Seung Yeon", "A Person Like You", ""),
        ("Jung Seung Hwan", "The Fan", ""),
        ("Rain", "GANG", ""),
        ("PSY", "New Face", "4X2=8"),
        ("Teen Top", "Missing", "Red Point"),
        ("B.A.P", "Honeymoon", "Blue"),
        ("CNBLUE", "Between Us", "7°CN"),
        ("FTISLAND", "Wind", "OVER 10 YEARS"),
        ("N.Flying", "Real Love", "Love in the FLY"),
        ("KNK", "Rain", "KNK SINGLES COLLECTION 265"),
    ],
}

# Fix bad album string
for t in CATALOG_2017_2019[2019]:
    if t[0] == "KARD" and "KARD 4th" in t[2]:
        idx = CATALOG_2017_2019[2019].index(t)
        CATALOG_2017_2019[2019][idx] = ("KARD", "Dumb Litty", "KARD 4th Mini Album 'KARD 4th Mini Album 'KARD 4th Mini Album ''")
        break
# proper fix
for i, t in enumerate(CATALOG_2017_2019[2019]):
    if t[0] == "KARD" and t[1] == "Dumb Litty":
        CATALOG_2017_2019[2019][i] = ("KARD", "Dumb Litty", "KARD 4th Mini Album 'KARD 4th Mini Album 'KARD 4th Mini Album ''")
        CATALOG_2017_2019[2019][i] = ("KARD", "Dumb Litty", "KARD 4th Mini Album")
        break

# Remove cross-year dupes within 2018 pool that duplicate 2017 global (iKON LOVE SCENARIO is 2018 album Return re-hit - actually released Jan 2018, belongs 2018)
# Remove 2018 iKON LOVE SCENARIO duplicate of itself - only once
# Remove 2018 dupes: Hyuna Babe is 2017, AKMU heartbreak is 2017, Heize Jenga 2017, Zico Any Song 2017, etc from 2018 pool
REMOVE_2018 = {
    ("Hyuna", "Babe"), ("AKMU", "How can I love the heartbreak, you're the one I love"),
    ("Heize", "Jenga"), ("Zico", "Any Song"), ("DEAN", "D (Half Moon)"), ("Crush", "Beautiful"),
    ("Park Hyo Shin", "Beautiful Tomorrow"), ("10CM", "Spring Snow"), ("Melomance", "You&Me"),
    ("Standing Egg", "Old Song"), ("INFINITE", "Tell Me"), ("ONF", "Complete"),
    ("Highlight", "Plz Don't Be Sad"), ("P1Harmony", "Siren"), ("PSY", "New Face"),
    ("Primary", "When I Was Young"), ("Yoon Mi Rae", "Gemini"), ("Chen", "Everytime"),
    ("Soyou", "The Night"), ("BewhY", "Day Day"), ("Loco", "Weak"), ("Gray", "Real Love"),
    ("Epik High", "Love Love Love"), ("Hyolyn", "Dally"), ("Jessi", "Down"),
    ("NU'EST W", "Dejavu"), ("Billlie", "GingaMingaYo (the strange world)"),
    ("CLASS:y", "SHUT DOWN"), ("YENA", "SMARTPHONE"), ("SECRET NUMBER", "Who Dis?"),
    ("BVNDIT", "Jungle"), ("TEMPEST", "Bad News"), ("Xdinary Heroes", "Happy Death Day"),
    ("woo!ah!", "Purple"), ("TRI.BE", "RUB-A-DUM"), ("PURPLE KISS", "Zombie"),
    ("STAYC", "So Bad"), ("Weeekly", "Tag Me (@Me)"), ("LIGHTSUM", "Vivace"),
    ("CRAVITY", "Break all the Rules"), ("DRIPPIN", "Young Blood"), ("ONEUS", "LIT"),
    ("Rosé", "On The Ground"),  # 2021
    ("Baekhyun", "Bambi"),  # 2021
    ("Kai", "Tempo"),  # 2018 EXO album track - EXO Tempo covers
    ("Jennie", "SOLO"),  # 2018
    ("ITZY", "DALLA DALLA"),  # 2019
    ("ITZY", "ICY"),  # 2019
    ("TWICE", "TT (Japanese ver.)",),  # wrong
}
CATALOG_2017_2019[2018] = [t for t in CATALOG_2017_2019[2018] if (t[0], t[1]) not in {(a,b) for a,b in REMOVE_2018}]

# Add more 2018-only tracks to replenish
EXTRA_2018 = [
    ("CHUNG HA", "Love U", "Flourishing"),
    ("CHUNG HA", "Snapping", "Flourishing"),
    ("Kang Daniel", "2U", ""),
    ("Paul Kim", "Me After You", ""),
    ("Sam Kim", "Make Up", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Bolbbalgan4", "Some", ""),
    ("Hyukoh", "Tomboy", "24 : How to find true love and happiness"),
    ("Epik High", "Born Hater", "Shoebox"),
    ("Soran", "The Star", ""),
    ("Colde", "Your Dog Loves You", ""),
    ("George", "Where's Wool", ""),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("DAY6", "Shoot Me", "Shoot Me : Youth Part 1"),
    ("DAY6", "Sweet Chaos", "The Book of Us : Entropy"),
    ("N.Flying", "Oh really?", "So, 通"),
    ("ONEWE", "Tag Me (@Me)", "ONE"),
    ("VERIVERY", "Thunder", "Truth or Dare"),
    ("D1CE", "HATE YOU", "Wake Up"),
    ("OnlyOneOf", "libidO", "Instinct, Part. 1"),
    ("DPR LIVE", "Martini Blue", "Coming To You Live"),
    ("Sik-K", "NEVER END", "HEADLINER"),
    ("Haon", "Skrt", "Travel : Nostalgia"),
    ("Nafla", "You Gon' Need It", "Natural High"),
    ("Woodz", "Drowning", "OO-LI"),
    ("K/DA", "POP/STARS", ""),
    ("BoA", "Woman", "ONE SHOT, TWO SHOT"),
    ("Taeyeon", "Wine", "Something New - The 3rd Mini Album"),
    ("Hyolyn", "Say My Name", "Xperience"),
    ("Sunny Hill", "Monday to Sunday", "The Beginning of New Endings"),
    ("Brown Eyed Girls", "Wonder Woman", "RE_vive"),
    ("2NE1", "Goodbye", ""),
    ("Gfriend", "Time for the moon night", "Time for the moon night"),
    ("WJSN", "Dreams Come True", "Dreams Come True"),
    ("Cosmic Girls", "La La Love", "WJ PLEASE?"),
    ("Loona", "So What", "[#]"),
    ("Dreamcatcher", "Piri", "The End of Nightmare"),
    ("Everglow", "Adios", "HUSH"),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("Cherry Bullet", "Hands Up", ""),
    ("AB6IX", "Blind For Love", "6IX SENSE"),
    ("CIX", "My My", ""),
    ("The Boyz", "The Stealer", "THE STEALER"),
    ("ATEEZ", "Answer", "TREASURE EP.Fin : All To Action"),
    ("ENHYPEN", "Given-Taken", "BORDER : DAY ONE"),
    ("aespa", "Black Mamba", ""),
    ("STAYC", "ASAP", ""),
    ("Brave Girls", "Rollin'", ""),
    ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
    ("TREASURE", "MMM", "THE FIRST STEP : CHAPTER THREE"),
    ("NCT U", "Make A Wish (Birthday Song)", "Resonance Pt. 1"),
    ("SuperM", "Jopping", "Super One"),
    ("Victon", "Nostalgia", "Nostalgia"),
    ("ONF", "Summer Poem", "ONF:MY NAME"),
    ("MCND", "nanana", "EARTH AGE"),
    ("A.C.E", "Favorite Boys", "HIGHER"),
    ("WEi", "Dondododo (Don't Hold Back)", ""),
    ("Im Chang-jung", "Nothing Like You", ""),
]
# Filter extras that are wrong year
WRONG_YEAR_2018 = {("Woodz", "Drowning"), ("STAYC", "ASAP"), ("Brave Girls", "Rollin'"), ("ENHYPEN", "Given-Taken"),
                   ("aespa", "Black Mamba"), ("Everglow", "Adios"), ("Loona", "So What"), ("Bolbbalgan4", "Some"),
                   ("The Boyz", "The Stealer"), ("Kang Daniel", "2U"), ("CHUNG HA", "Snapping")}
EXTRA_2018 = [t for t in EXTRA_2018 if (t[0], t[1]) not in WRONG_YEAR_2018]
CATALOG_2017_2019[2018].extend(EXTRA_2018)

# Clean 2019 pool - remove wrong year / dupes with 2017-2018
REMOVE_2019 = {
    ("EXO", "Monster"), ("SHINee", "Don't Call Me"), ("ITZY", "DALLA DALLA"), ("ITZY", "ICY"),
    ("AKMU", "How can I love the heartbreak, you're the one I love"), ("DEAN", "instagram"),
    ("Crush", "None"), ("Melomance", "Gift"), ("Standing Egg", "Old Song"), ("Ben", "From Ben"),
    ("Urban Zakapa", "When We Were Two"), ("GFRIEND", "Sunrise"), ("Lovelyz", "That Day"),
    ("Golden Child", "Lady"), ("LOONA", "Butterfly"), ("WJSN", "La La Love"),
    ("IZ*ONE", "Violeta"), ("PENTAGON", "Dr. Bebe"), ("Dreamcatcher", "Scream"),
    ("Billlie", "GingaMingaYo (the strange world)"), ("SECRET NUMBER", "Who Dis?"),
    ("ONEUS", "LIT"), ("woo!ah!", "Purple"), ("TRI.BE", "RUB-A-DUM"), ("PURPLE KISS", "Zombie"),
    ("P1Harmony", "Siren"), ("CRAVITY", "Break all the Rules"), ("DRIPPIN", "Young Blood"),
    ("CLASS:y", "SHUT DOWN"), ("YENA", "SMARTPHONE"), ("BVNDIT", "Jungle"), ("TEMPEST", "Bad News"),
    ("Xdinary Heroes", "Happy Death Day"), ("LIGHTSUM", "Vivace"), ("STAYC", "So Bad"),
    ("Weeekly", "Tag Me (@Me)"), ("Jennie", "SOLO"), ("Taemin", "Move"), ("Highlight", "Plz Don't Be Sad"),
    ("Hwa Sa", "Maria"), ("Hyolyn", "Dally"), ("Soyou", "The Night"), ("Epik High", "Rosario"),
    ("Sunmi", "Siren"), ("Heize", "HAPPEN"), ("AKMU", "Nakka"), ("Mamamoo", "Where Are We Now"),
    ("PSY", "New Face"), ("Rain", "GANG"), ("Primary", "When I Was Young"), ("Gary", "Sunrise"),
    ("Loco", "Weak"), ("Gray", "Real Love"), ("BewhY", "Day Day"), ("Mad Clown", "Fire"),
    ("Huh Gak", "Spring Rain"), ("Ailee", "If You"), ("Son Seung Yeon", "A Person Like You"),
    ("Jung Seung Hwan", "The Fan"), ("Im Chang-jung", "Nothing Like You"), ("Standing Egg", "Confession"),
    ("Roy Kim", "Only Then"), ("Teen Top", "Missing"), ("B.A.P", "Honeymoon"), ("CNBLUE", "Between Us"),
    ("FTISLAND", "Wind"), ("N.Flying", "Real Love"), ("KNK", "Rain"), ("ENHYPEN", "Given-Taken"),
    ("aespa", "Black Mamba"), ("STAYC", "ASAP"), ("Brave Girls", "Rollin'"), ("SuperM", "Jopping"),
    ("SuperM", "Tiger Inside"), ("Victon", "Nostalgia"), ("ONF", "Summer Poem"), ("MCND", "nanana"),
    ("A.C.E", "Favorite Boys"), ("WEi", "Dondododo (Don't Hold Back)"), ("Sunmi", "Pporappippam"),
    ("Zion.T", "No Love"), ("Kim Feel", "All I Do"), ("Vibe", "Vibe"), ("Punch", "Through the Night"),
    ("Jessi", "NUNU NANA"), ("Kang Daniel", "Who U Are"), ("10CM", "Your Mountain"),
    ("Park Hyo Shin", "Good Goodbye"), ("Lee Hi", "Hola"), ("Zico", "Any Song"),
    ("WINNER", "Remember"), ("BTS", "ON"), ("BTS", "Black Swan"),  # 2020
    ("Red Velvet", "Psycho"),  # late 2019 Dec - actually 2019 OK keep
}
# Keep ON/Black Swan out (2020), keep Psycho
REMOVE_2019.discard(("Red Velvet", "Psycho"))
REMOVE_2019.add(("BTS", "ON"))
REMOVE_2019.add(("BTS", "Black Swan"))
CATALOG_2017_2019[2019] = [t for t in CATALOG_2017_2019[2019] if (t[0], t[1]) not in REMOVE_2019]

EXTRA_2019 = [
    ("Paul Kim", "Me After You", ""),
    ("Sam Kim", "Make Up", ""),
    ("Younha", "Event Horizon", "UNSTABLE MINDSET"),
    ("Jannabi", "for lovers who hesitate", "LEGEND"),
    ("DAY6", "Sweet Chaos", "The Book of Us : Entropy"),
    ("N.Flying", "Oh really?", "So, 通"),
    ("ONEWE", "Tag Me (@Me)", "ONE"),
    ("VERIVERY", "Thunder", "Truth or Dare"),
    ("D1CE", "HATE YOU", "Wake Up"),
    ("OnlyOneOf", "libidO", "Instinct, Part. 1"),
    ("BoA", "Woman", "ONE SHOT, TWO SHOT"),
    ("Taeyeon", "Wine", "Something New - The 3rd Mini Album"),
    ("Sunny Hill", "Monday to Sunday", "The Beginning of New Endings"),
    ("Brown Eyed Girls", "Wonder Woman", "RE_vive"),
    ("2NE1", "Goodbye", ""),
    ("Everglow", "Adios", "HUSH"),
    ("Rocket Punch", "Bouncy", "Blue Punch"),
    ("Cherry Bullet", "Hands Up", ""),
    ("AB6IX", "Blind For Love", "6IX SENSE"),
    ("CIX", "My My", ""),
    ("The Boyz", "D.D.D", "Dreamlike"),
    ("ATEEZ", "Wonderland", "TREASURE EP.Fin : All To Action"),
    ("WayV", "Take Off", "Take Off"),
    ("NCT U", "Make A Wish (Birthday Song)", "Resonance Pt. 1"),
    ("TREASURE", "I Love You", "THE FIRST STEP : CHAPTER TWO"),
    ("TREASURE", "MMM", "THE FIRST STEP : CHAPTER THREE"),
    ("TREASURE", "My Treasure", "THE FIRST STEP"),
    ("OH MY GIRL", "Nonstop", "NONSTOP"),
    ("GFRIEND", "Apple", "回:Song of the Sirens"),
    ("Weki Meki", "Dazzle Dazzle", ""),
    ("Hyuna", "I'm Not Cool", "I'm Not Cool"),
    ("MONSTA X", "FANTASY", "FANTASIA X"),
    ("Everglow", "LA DI DA", ""),
    ("Apink", "Dumhdurum", "Look"),
    ("SuperM", "Tiger Inside", "Super One"),
    ("NCT 127", "Punch", "NCT #Resonance Pt. 2"),
    ("ATEEZ", "Inception", "ZERO : FEVER Part.1"),
    ("TXT", "Blue Hour", "minisode1 : Blue Hour"),
    ("Dreamcatcher", "Scream", "Dystopia: The Tree of Language"),
    ("LOONA", "Why Not?", "[12:00]"),
    ("fromis_9", "Feel Good (SECRET CODE)", "My Little Society"),
    ("WJSN", "Neverland", "Neverland"),
    ("PENTAGON", "Dr. Bebe", "UNIVERSE : THE PROLOGUE"),
    ("Golden Child", "Dun Dun Dun", "Golden Age"),
    ("ONEUS", "TO BE OR NOT TO BE", "LIVED"),
    ("EXO", "Let Me In", ""),
    ("Mamamoo", "Dingga", ""),
    ("IU", "eight (Prod.&feat. SUGA of BTS)", "eight"),
    ("BOL4", "Some", ""),
    ("Colde", "Your Dog Loves You", ""),
    ("Soran", "The Star", ""),
    ("George", "Where's Wool", ""),
    ("Epik High", "Born Hater", "Shoebox"),
    ("K/DA", "POP/STARS", ""),
    ("Hyukoh", "Tomboy", "24 : How to find true love and happiness"),
    ("CHUNG HA", "Stay Tonight", "Querencia"),
    ("CHUNG HA", "Bicycle", "Querencia"),
    ("Sunmi", "Gotta Go", "WARNING"),
    ("Taeyeon", "Spark", "Purpose - The 2nd Studio Album"),
    ("Red Velvet", "Zimzalabim", "The ReVe Festival Day 1"),
    ("Red Velvet", "Umpah Umpah", "The ReVe Festival Day 2"),
    ("CLC", "ME", "No.1"),
    ("MOMOLAND", "I'm So Hot", "Show Me"),
    ("VIXX", "Parallel", "Conception Ker"),
    ("INFINITE", "Why Why", "Why Why"),
    ("BTOB", "Blue Moon", "Feel'eM"),
    ("ASTRO", "All Night", "All Light"),
    ("SF9", "RPM", "RPM"),
    ("Block B", "Don't Leave", "RECONSTRUCTION"),
    ("iKON", "Dive", "NEW KIDS : THE FINAL"),
    ("WINNER", "Ah Yeah", "WE"),
    ("GOT7", "Eclipse", "Spinning Top : Between Security & Insecurity"),
    ("Stray Kids", "MIROH", "Clé 1 : MIROH"),
    ("SEVENTEEN", "Home", "An Ode"),
    ("NCT 127", "Kick It", "NCT #127 Neo Zone - The 2nd Album"),
    ("NCT DREAM", "BOOM", "We Boom - The 3rd Mini Album"),
    ("EXO", "Obsession", "OBSESSION - The 6th Album"),
    ("BLACKPINK", "Kill This Love", ""),
    ("TWICE", "Fancy", "Fancy You"),
    ("ITZY", "WANNABE", ""),
    ("(G)-IDLE", "Senorita", "I made"),
    ("IU", "Blueming", "Love poem"),
    ("BTS", "Boy With Luv", "MAP OF THE SOUL : PERSONA"),
    ("Mamamoo", "HIP", ""),
    ("Heize", "We don't talk together", "We don't talk together"),
    ("AKMU", "Happening", "HAPPENING"),
    ("Zion.T", "No Love", ""),
    ("Kim Feel", "All I Do", ""),
    ("Vibe", "Vibe", ""),
    ("Davichi", "Changmin's Not Here", ""),
    ("Standing Egg", "Old Song", "Lip"),
    ("Im Chang-jung", "Nothing Like You", ""),
    ("Ben", "From Ben", "Reality"),
]
# Dedupe EXTRA_2019 against current 2019 list
existing = {(a, b) for a, b, _ in CATALOG_2017_2019[2019]}
EXTRA_2019 = [t for t in EXTRA_2019 if (t[0], t[1]) not in existing]
CATALOG_2017_2019[2019].extend(EXTRA_2019)

# Remove 2017 dupes within pool
seen17 = set()
clean17 = []
for t in CATALOG_2017_2019[2017]:
    k = (t[0], t[1])
    if k in seen17:
        continue
    seen17.add(k)
    clean17.append(t)
CATALOG_2017_2019[2017] = clean17

for y in (2018, 2019):
    seen = set()
    clean = []
    for t in CATALOG_2017_2019[y]:
        k = (t[0], t[1])
        if k in seen:
            continue
        seen.add(k)
        clean.append(t)
    CATALOG_2017_2019[y] = clean

lines = [
    '#!/usr/bin/env python3',
    '"""K-pop Top 100 candidate pools (2017-2019). Melon/Gaon/community ordered."""',
    'from __future__ import annotations',
    '',
    'CATALOG_2017_2019: dict[int, list[tuple[str, str, str]]] = {',
]
for year in sorted(CATALOG_2017_2019):
    lines.append(f"    {year}: [")
    for artist, title, album in CATALOG_2017_2019[year]:
        lines.append(f"        ({artist!r}, {title!r}, {album!r}),")
    lines.append("    ],")
lines.append("}")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
for y in sorted(CATALOG_2017_2019):
    print(f"{y}: {len(CATALOG_2017_2019[y])} tracks")
