export default [
  "Faith Hill|Breathe|",
  "Santana feat. Rob Thomas|Smooth|",
  "Santana feat. The Product GandB|Maria Maria|",
  "Joe|I Wanna Know|",
  "Vertical Horizon|Everything You Want|",
  "Destiny's Child|Say My Name|",
  "Savage Garden|I Knew I Loved You|",
  "Lonestar|Amazed|",
  "matchbox twenty|Bent|",
  "Toni Braxton|He Wasn't Man Enough|",
  "Creed|Higher|",
  "Aaliyah|Try Again|",
  "Destiny's Child|Jumpin Jumpin'|",
  "Sisqo|Thong Song|",
  "3 Doors Down|Kryptonite|",
  "Pink|There You Go|",
  "Madonna|Music|",
  "Janet|Doesn't Really Matter|",
  "Christina Aguilera|What A Girl Wants|",
  "Brian McKnight|Back At One|",
  "'N Sync|Bye Bye Bye|",
  "Marc Anthony|You Sang To Me|",
  "Marc Anthony|I Need To Know|",
  "Montell Jordan|Get It On Tonite|",
  "Sisqo|Incomplete|",
  "Macy Gray|I Try|",
  "'N Sync|It's Gonna Be Me|",
  "Celine Dion|That's The Way It Is|",
  "Nelly|(Hot S**T) Country Grammar|",
  "Blaque|Bring It All To Me|",
  "Backstreet Boys|Show Me The Meaning Of Being Lonely|",
  "Missy Elliott feat. Nas, EVE and Q-Tip|Hot Boyz|",
  "BBMak|Back Here|",
  "Sonique|It Feels So Good|",
  "Nine Days|Absolutely (Story Of A Girl)|",
  "Creed|With Arms Wide Open|",
  "Enrique Iglesias|Be With You|",
  "Christina Aguilera|Come On Over Baby (All I Want Is You)|",
  "Ruff Endz|No More|",
  "Blink 182|All The Small Things|",
  "Faith Hill|The Way You Love Me|",
  "Christina Aguilera|I Turn To You|",
  "Third Eye Blind|Never Let You Go|",
  "LeAnn Rimes|I Need You|",
  "Mariah Carey feat. Joe and 98 Degrees|Thank God I Found You|",
  "Jagged Edge|Let's Get Married|",
  "Whitney Houston|My Love Is Your Love|",
  "Smash Mouth|Then The Morning Comes|",
  "iffel 65|Blue (Da Ba Dee)|",
  "Sting feat. Cheb Mami|Desert Rose|",
  "Pink|Most Girls|",
  "Next|Wifey|",
  "Everclear|Wonderful|",
  "Britney Spears|Oops!&#8230; I Did It Again|",
  "Jessica Simpson|I Wanna Love You Forever|",
  "98 Degrees|Give Me Just One Night (Una Noche )|",
  "Filter|Take A Picture|",
  "Red Hot Chili Peppers|Otherside|",
  "Son By Four|Purest Of Pain (A Puro Dolor)|",
  "Jagged Edge|He Can't Love U|",
  "Avant|Separated|",
  "Carl Thomas|I Wish|",
  "Donell Jones|U Know What's Up|",
  "SoulDecision feat. Thrust|Faded|",
  "Kid Rock|Only God Knows Why|",
  "Erykah Badu|Bag Lady|",
  "Train|Meet Virginia|",
  "DMX|Party Up (Up In Here)|",
  "Mya|Case Of The Ex (Whatcha Gonna Do)|",
  "Dr. Dre feat. Eminem|Forget About Dre|",
  "Jo Dee Messina|That's The Way|",
  "Westlife|Swear It Again|",
  "Britney Spears|From The Bottom Of My Broken Heart|",
  "Savage Garden|Crash And Burn|",
  "Chad Brock|Yes!|",
  "George Strait|The Best Day|",
  "Donell Jones|Where I Wanna Be|",
  "Toby Keith|How Do You Like Me Now?!|",
  "Tim McGraw|My Best Friend|",
  "Goo Goo Dolls|Broadway|",
  "Da Brat feat. Tyrese|What'chu Like|",
  "Kandi|Don't Think I'm Not|",
  "Lee Ann Womack and Sons Of The Desert|I Hope You Dance|",
  "Alice Deejay|Better Off Alone|",
  "Debelah Morgan|Dance With Me|",
  "Lonestar|What About Now|",
  "Sammie|I Like It|",
  "Kevon Edmonds|24/7|",
  "LFO|Girl On TV|",
  "Lil Bow Wow feat. Xscape|Bounce With Me|",
  "Dixie Chicks|Cowboy Take Me Away|",
  "Aaliyah|I Don't Wanna|",
  "Destiny's Child|Independent Women Part I|",
  "Samantha Mumba|Gotta Tell You|",
  "Jennifer Lopez|Waiting For Tonight|",
  "Mary Mary|Shackles (Praise You)|",
  "Bon Jovi|It's My Life|Crush",
  "Radiohead|Everything in Its Right Place|Kid A",
  "Radiohead|Optimistic|Kid A",
  "Coldplay|Yellow|Parachutes",
];
