export default [
  "Lifehouse|Hanging By A Moment|",
  "Alicia Keys|Fallin'|",
  "Janet|All For You|",
  "Train|Drops Of Jupiter (Tell Me)|",
  "Jennifer Lopez feat. Ja Rule|I'm Real|",
  "matchbox twenty|If You're Gone|",
  "Dido|Thank You|",
  "Lenny Kravitz|Again|",
  "Blu Cantrell|Hit 'Em Up Style (Oops!)|",
  "Shaggy feat. Ricardo &#8220;RikRok&#8221; Ducent|It Wasn't Me|",
  "Joe feat. Mystikal|Stutter|",
  "Staind|It's Been Awhile|",
  "Usher|U Remind Me|",
  "Jagged Edge With Nelly|Where The Party At|",
  "Shaggy feat. Rayvon|Angel|",
  "Uncle Kracker|Follow Me|",
  "112|Peaches & Cream|",
  "Incubus|Drive|",
  "City High|What Would You Do?|",
  "Destiny's Child|Survivor|",
  "Christina Aguilera, Lil' Kim, Mya and Pink|Lady Marmalade|",
  "Jennifer Lopez|Love Don't Cost A Thing|",
  "Dream|He Loves U Not|",
  "Crazy Town|Butterfly|",
  "Ja Rule feat. Lil' Mo and Vita|Put It On Me|",
  "Mary J. Blige|Family Affair|",
  "Moby feat. Gwen Stefani|South Side|",
  "Madonna|Don't Tell Me|",
  "Missy &#8220;Misdemeanor&#8221; Elliott|Get Ur Freak On|",
  "K-Ci and JoJo|Crazy|",
  "Craig David|Fill Me In|",
  "Janet|Someone To Call My Lover|",
  "O-Town|All Or Nothing|",
  "Destiny's Child|Bootylicious|",
  "Nelly Furtado|I'm Like A Bird|",
  "R. Kelly feat. Jay-Z|Fiesta|",
  "Sugar Ray|When It's Over|",
  "Aerosmith|Jaded|",
  "Jagged Edge|Promise|",
  "Case|Missing You|",
  "Ginuwine|Differences|",
  "'N Sync|This I Promise You|",
  "Lil' Mo feat. Fabolous|Superwoman Pt. II|",
  "Evan And Jaron|Crazy For This Girl|",
  "Ricky Martin and Christina Aguilera|Nobody Wants To Be Lonely|",
  "Jay-Z|I Just Wanna Love U (Give It 2 Me)|",
  "Missy &#8220;Misdemeanor&#8221; Elliott|One Minute Man|",
  "Mystikal feat. Nivea|Danger (Been So Long)|",
  "Enya|Only Time|",
  "Toya|I Do!!|",
  "S Club 7|Never Had A Dream Come True|",
  "Tamia|Stranger In My House|",
  "Jessica Simpson|Irresistible|",
  "Sunshine Anderson|Heard It All Before|",
  "Dave Matthews Band|The Space Between|",
  "Faith Hill|There You'll Be|",
  "Musiq Soulchild|Love|",
  "112|It's Over Now|",
  "3LW|No More (Baby I'ma Do Right)|",
  "Nelly Furtado|Turn Off The Light|",
  "Brooks and Dunn|Ain't Nothing `Bout You|",
  "Jennifer Lopez|Play|",
  "Lonestar|I'm Already There|",
  "Lil' Romeo|My Baby|",
  "U2|Beautiful Day|",
  "Blake Shelton|Austin|",
  "Ludacris|Southern Hospitality|",
  "Tim McGraw|Grown Men Don't Cry|",
  "Ja Rule feat. Case|Livin' It Up|",
  "Mariah Carey feat. Cameo|Loverboy|",
  "Isley Brothers feat. Ronald Isley AKA Mr. Biggs|Contagious|",
  "Jessica Andrews|Who I Am|",
  "Erick Sermon feat. Marvin Gaye|Music|",
  "Willa Ford|I Wanna Be Bad|",
  "Kenny Chesney|Don't Happen Twice|",
  "Diamond Rio|One More Day|",
  "R. Kelly|I Wish|",
  "Travis Tritt|It's A Great Day To Be Alive|",
  "Trick Daddy|I'm A Thug|",
  "Eve 6|Here's To The Night|",
  "Toby Keith|You Shouldn't Kiss Me Like This|",
  "Eden's Crush|Get Over Yourself|",
  "Nelly|E.I.|",
  "3 Doors Down|Be Like That|",
  "QB's Finest feat. Nas and Braveheart's|Oochie Wally|",
  "Enrique Iglesias|Hero|",
  "Fuel|Hemorrhage (In My Hands)|",
  "Green Day|Minority|Warning",
  "Blink-182|Adam's Song|Enema of the State",
  "Moby|Natural Blues|Play",
  "All Saints|Pure Shores|Saints & Sinners",
  "Modjo|Lady (Hear Me Tonight)|Modjo",
  "Sonique|Synchro Love|Club Zip",
  "Eiffel 65|Move Your Body|Europop",
  "Wheatus|Teenage Dirtbag|Wheatus",
  "D'Angelo|Untitled (How Does It Feel)|Voodoo",
  "Erykah Badu|Didn't Cha Know?|Mama's Gun",
  "Radiohead|Pyramid Song|Amnesiac",
  "Radiohead|Knives Out|Amnesiac",
  "Coldplay|In My Place|Parachutes",
];
