export default [
  "Nickelback|How Your Remind Me|",
  "Ashanti|Foolish|",
  "Nelly|Hot in Herre|",
  "The Calling|Wherever you Will Go|",
  "Vanessa Carlton|A Thousand Miles|",
  "Linkin Park|In the End|",
  "Fat Joe feat. Ashanti|What's Luv?|",
  "Usher|U Got it Bad|",
  "Puddle Of Mudd|Blurry|",
  "Avril Lavigne|Complicated|",
  "Jennifer Lopez feat. Ja Rule|Ain't it Funny|",
  "Jimmy Eat World|The Middle|",
  "P. Diddy feat. Usher and Loon|I Need a Girl (Part One)|",
  "Usher|U Don't have to Call|",
  "P. Diddy and Ginuwine feat. Loon, Mario Winans and Tammy Ruggeri|I Need a Girl (Part Two)|",
  "Eve feat. Alicia Keys|Gangsta Lovin'|",
  "Creed|My Sacrifice|",
  "Eminem|Without Me|",
  "Michelle Branch|All You Wanted|",
  "Pink|Get the Party Started|",
  "Chad Kroeger feat. Josey Scott|Hero|",
  "Default|Wasting My Time|",
  "Creed|One Last Breath|",
  "Shakira|Whenever, Wherever|",
  "Jennifer Lopez feat. Nas|I'm Gonna Be Alright|",
  "Cam'ron feat. Juelz Santana|Oh Boy|",
  "DJ Sammy and Yanou feat. Do|Heaven|",
  "No Doubt feat. Bounty Killer|Hey Baby|",
  "'N Sync feat. Nelly|Girlfriend|",
  "Mario|Just a Friend 2002|",
  "Sheryl Crow|Soak up the Sun|",
  "Pink|Don't Let Me Get Me|",
  "N.O.R.E.|Nothin'|",
  "Tweet|Oops (Oh My)|",
  "Kelly Clarkson|A Moment Like This|",
  "Truth Hurts feat. Rakim|Addictive|",
  "Ashanti|Happy|",
  "John Mayer|No Such Thing|",
  "Pink|Just Like a Pill|",
  "Irv Gotti Presents The Inc. feat. Ja Rule, Ashanti, Charli Baltimore and Vita|Down 4 U|",
  "Kylie Minogue|Can't Get You Out Of My Head|",
  "Five For Fighting|Superman (It's not Easy)|",
  "Musiq|Halfcrazy|",
  "Mr. Cheeks|Lights, Camera, Action!|",
  "Big Tymers|Still Fly|",
  "Alicia Keys|A Woman's Worth|",
  "Craig David|7 Days|",
  "Cam'ron feat. Juelz Santana, Freekey Zekey and Toya|Hey Ma|",
  "Missy &#8220;Misdemeanor&#8221; Elliott|Work It|",
  "Ludacris feat. Mystikal and Infamous 2.0|Move Bitch|",
  "LeAnn Rimes|Can't Fight the Moonlight|",
  "Enrique Iglesias|Escape|",
  "Aaliyah|More than a Woman|",
  "No Doubt|Hello Good|",
  "Faith Evans|I Love You|",
  "Daniel Bedingfield|Gotta Get Thru This|",
  "Busta Rhymes feat. P. Diddy and Pharrell|Pass the Courvoisier Part II|",
  "Michael Jackson|Butterflies|",
  "Brandy|What About Us?|",
  "Shakira|Underneath your Clothes|",
  "Mary J. Blige feat. Ja Rule|Rainy Dayz|",
  "Angie Martinez feat. Lil' Mo and Sacario|If I could Go!|",
  "OutKast feat. Killer Mike|The Whole World|",
  "No Doubt feat. Lady Saw|Underneath it All|",
  "City High feat. Eve|Caramel|",
  "LL Cool J|Luv U Better|",
  "Sean Paul|Gimme the Light|",
  "'N Sync|Gone|",
  "Ludacris|Roll Out (My Business)|",
  "Goo Goo Dolls|Here is Gone|",
  "Mary J. Blige|No More Drama|",
  "Dirty Vegas|Days go By|",
  "Ashanti|Baby|",
  "Kenny Chesney|The Good Stuff|",
  "Fat Joe feat. R. Kelly|We Thuggin'|",
  "Steve Holy|Good Morning Beautiful|",
  "Aaliyah|Rock the Boat|",
  "Alan Jackson|Drive (For Daddy Gene)|",
  "Jewel|Standing Still|",
  "Jaheim feat. Next|Anything|",
  "Brandy|Full Moon|",
  "B2K|Uh Huh|",
  "Celine Dion|A New Day has Come|",
  "George Strait|Living and Living Well|",
  "Toby Keith|My List|",
  "Alanis Morissette|Hands Clean|",
  "Avril Lavigne|Sk8er Boi|",
  "Dixie Chicks|Long Time Gone|",
  "Alan Jackson|Where Were You (When the World Stopped Turning)|",
  "Justin Timberlake|Like I Love You|",
  "Coldplay|Don't Panic|Parachutes",
  "The Strokes|Last Nite|Is This It",
  "The Strokes|Someday|Is This It",
  "System of a Down|Chop Suey!|Toxicity",
  "System of a Down|Aerials|Toxicity",
  "Linkin Park|Crawling|Hybrid Theory",
  "Linkin Park|One Step Closer|Hybrid Theory",
  "Gorillaz|Clint Eastwood|Gorillaz",
  "Gorillaz|19-2000|Gorillaz",
  "Daft Punk|One More Time|Discovery",
];
