export default [
  "Usher feat. Lil Jon and Ludacris|Yeah!|",
  "Usher|Burn|",
  "Alicia Keys|If I Ain't Got You|",
  "Maroon5|This Love|",
  "OutKast feat. Sleepy Brown|The Way You Move|",
  "Hoobastank|The Reason|",
  "Mario Winans feat. Enya and P. Diddy|I Don't Wanna Know|",
  "Ciara feat. Petey Pablo|Goodies|",
  "Terror Squad|Lean Back|",
  "J-Kwon|Tipsy|",
  "Usher|Confessions Part II|",
  "Juvenile feat. Soulja Slim|Slow Motion|",
  "Petey Pablo|Freek-a-Leek|",
  "Twista feat. Kanye West and Jamie Foxx|Slow Jamz|",
  "Nickelback|Someday|",
  "Beyonce|Naughty Girl|",
  "Evanescence|My Immortal|",
  "Lil' Flip feat. Lea|Sunshine|",
  "Nina Sky feat. Jabba|Move Ya Body|",
  "Christina Milian|Dip It Low|",
  "Usher And Alicia Keys|My Boo|",
  "Chingy feat. J. Weav|One Call Away|",
  "Beyonce|Me, Myself, and I|",
  "Kevin Lyttle feat. Spragga Benz|Turn Me On|",
  "Sheryl Crow|The First Cut Is The Deepest|",
  "Alicia Keys|You Don't Know My Name|",
  "Nelly feat. Jaheim|My Place|",
  "Twista|Overnight Celebrity|",
  "Cassidy feat. R. Kelly|Hotel|",
  "Linkin Park|Numb|",
  "Alicia Keys feat. Tony! Toni! Tone!|Diary|",
  "Maroon 5|She Will be Loved|",
  "Dido|White Flag|",
  "Los Lonely Boys|Heaven|",
  "No Doubt|It's My Life|",
  "Ashlee Simpson|Pieces of Me|",
  "JoJo|Leave (Get Out)|",
  "Kelis|Milkshake|",
  "Ludacris|Splash Waterfalls|",
  "Akon feat. Styles P.|Locked Up|",
  "Kanye West feat. Syleena Johnson|All Falls Down|",
  "Britney Spears|Toxic|",
  "Ying Yang Twins feat. Lil Jon and The East Side Boyz|Salt Shaker|",
  "Jessica Simpson|With You|",
  "Switchfoot|Meant to Live|",
  "Houston feat. Chingy, Nate Dogg and I-20|I Like That|",
  "Ruben Studdard|Sorry 2004|",
  "Avril Lavigne|My Happy Ending|",
  "Lloyd Banks|On Fire|",
  "OutKast|Roses|",
  "Jagged Edge|Walker outta Heaven|",
  "Destiny's Child|Lose My Breath|",
  "D12|My Band|",
  "Sean Paul feat. Sasha|I'm Still in Love with You|",
  "Jadakiss feat. Anthony Hamilton|Why?|",
  "Eamon|F**k It (I Don't Want you Back)|",
  "Avant|Read your Mind|",
  "Lil' Flip|Game Over (Flip)|",
  "Finger Eleven|One Thing|",
  "LL Cool J|Headsprung|",
  "Monica|U Should've Known Better|",
  "Ryan Cabrera|On the Way Down|",
  "Kelly Clarkson|Breakaway|",
  "Jet|Are You Gonna Be My Girl|",
  "Five For Fighting|100 Years|",
  "Linkin Park|Breaking the Habit|",
  "Nick Cannon feat. R. Kelly|Gigolo|",
  "Tim McGraw|Live Like You Were Dying|",
  "Alan Jackson|Remember When|",
  "Britney Spears|Everytime|",
  "Lloyd feat. Ashanti|Southside|",
  "Beenie Man feat. Ms. Thing|Dude|",
  "G-Unit feat. Joe|Wanna Get To Know You|",
  "Black Eyed Peas|Let's Get It Started|",
  "Kenny Chesney and Uncle Kracker|When the Sun Goes Down|",
  "Toby Keith|American Soldier|",
  "Jay-Z|Change Clothes|",
  "Avril Lavigne|Don't Tell Me|",
  "Keith Urban|You'll Think of Me|",
  "R. Kelly|Happy People|",
  "Black Eyed Peas|Hey Mama|",
  "Nelly feat. Tim McGraw|Over and Over|",
  "Gretchen Wilson|Redneck Woman|",
  "Eminem|Just Lose It|",
  "John Michael Montgomery|Letters from Home|",
  "Kenny Chesney|I Go Back|",
  "P!nk|Get the Party Started|M!ssundaztood",
  "P!nk|Just Like a Pill|M!ssundaztood",
  "Michelle Branch|Everywhere|The Spirit Room",
  "Tool|Schism|Lateralus",
  "Sade|By Your Side|Lovers Rock",
  "Travis|Sing|The Invisible Band",
  "Nickelback|How You Remind Me|Silver Side Up",
  "Coldplay|The Scientist|A Rush of Blood to the Head",
  "Red Hot Chili Peppers|By the Way|By the Way",
  "No Doubt|Hella Good|Rock Steady",
  "Jennifer Lopez|Jenny from the Block|This Is Me... Then",
  "Sum 41|Still Waiting|Does This Look Infected?",
  "No Doubt|Underneath It All|Rock Steady",
  "P.O.D.|Youth of the Nation|Satellite",
];
