export default [
  "Flo Rida feat. T-Pain|Low|",
  "Leona Lewis|Bleeding Love|",
  "Lil Wayne feat. Static Major|Lollipop|",
  "Jordin Sparks Duet With Chris Brown|No Air|",
  "Sara Bareilles|Love Song|",
  "Usher feat. Young Jeezy|Love In This Club|",
  "Chris Brown|With You|",
  "Chris Brown|Forever|",
  "Ray J and Yung Berg|Sexy Can I|",
  "Rihanna|Take A Bow|",
  "Coldplay|Viva La Vida|",
  "Katy Perry|I Kissed A Girl|",
  "T.I.|Whatever You Like|",
  "Rihanna|Disturbia|",
  "Rihanna|Don't Stop the Music|",
  "Natasha Bedingfield|Pocketful of Sunshine|",
  "Ne-Yo|Closer|",
  "Mariah Carey|Touch My Body|",
  "Madonna feat. Justin Timberlake|4 Minutes|",
  "Pink|So What|",
  "Fergie|Clumsy|",
  "Jason Mraz|I'm Yours|",
  "Jesse McCartney|Leavin'|",
  "Kardinal Offishall feat. Akon|Dangerous|",
  "Jordin Sparks|Tattoo|",
  "Miley Cyrus|See You Again|",
  "Metro Station|Shake It|",
  "OneRepublic|Stop And Stare|",
  "Sean Kingston|Take You There|",
  "Katy Perry|Hot N Cold|",
  "T.I. feat. Rihanna|Live Your Life|",
  "Plies feat. Ne-Yo|Bust It Baby Part 2|",
  "Estelle feat. Kanye West|American Boy|",
  "Lil Wayne feat. T-Pain|Got Money|",
  "Taylor Swift|Our Song|",
  "Danity Kane|Damaged|",
  "Buckcherry|Sorry|",
  "Webbie feat. Lil' Phat & Lil' Boosie|Independent|",
  "T-Pain feat. Lil Wayne|Can't Believe It|",
  "Alicia Keys|Like You'll Never See Me Again|",
  "The Pussycat Dolls|When I Grow Up|",
  "Snoop Dogg|Sensual Seduction|",
  "Colby O'Donis feat. Akon|What You Got|",
  "3 Doors Down|It'S Not My Time|",
  "Leona Lewis|Better In Time|",
  "Linkin Park|Shadow Of The Day|",
  "Wyclef Jean feat. Akon, Lil Wayne & Niia|Sweetest Girl (Dollar Bill)|",
  "Ne-Yo|Miss Independent|",
  "Secondhand Serenade|Fall For You|",
  "Flo Rida feat. will.i.am|In The Ayer|",
  "John Mayer|Say|",
  "Jordin Sparks|One Step at A Time|",
  "Rihanna feat. Ne-Yo|Hate That I Love You|",
  "Lupe Fiasco feat. Matthew Santos|Superstar|",
  "J. Holiday|Suffocate|",
  "Kevin Rudolf feat. Lil Wayne|Let It Rock|",
  "David Banner feat. Chris Brown|Get Like Me|",
  "Colbie Caillat|Realize|",
  "David Cook|The Time Of My Life|",
  "Three 6 Mafia feat. Project Pat, Young D and Superpower|Lolli Lolli (Pop That Body)|",
  "Natasha Bedingfield feat. Sean Kingston|Love Like This|",
  "Jonas Brothers|Burnin' Up|",
  "The-Dream|I Luv Your Girl|",
  "David Archuleta|Crush|",
  "Plies feat. Akon|Hypnotized|",
  "Kanye West feat. T-Pain|Good Life|",
  "Britney Spears|Womanizer|",
  "Taylor Swift|Love Story|",
  "Mary J. Blige|Just Fine|",
  "Britney Spears|Piece Of Me|",
  "Rick Ross feat. T-Pain|The Boss|",
  "Kid Rock|All Summer Long|",
  "Trey Songz|Can't Help But Wait|",
  "Gavin DeGraw|In Love With A Girl|",
  "The Game feat. Lil Wayne|My Life|",
  "Keyshia Cole|I Remember|",
  "Kanye West feat. Dwele|Flashing Lights|",
  "Lil Wayne feat. Bobby Valentino & Kidd Kidd|Mrs. Officer|",
  "Miley Cyrus|7 Things|",
  "Trace Adkins|You're Gonna Miss This|",
  "Gavin Rossdale|Love Remains The Same|",
  "Daughtry|Feels Like Tonight|",
  "Saving Abel|Addicted|",
  "Santana feat. Chad Kroeger|Into The Night|",
  "Keyshia Cole|Heaven Sent|",
  "2 Pistols feat. T-Pain and Tay Dizm|She Got It|",
  "Coldplay|Violet Hill|Viva la Vida or Death and All His Friends",
  "Kings of Leon|Sex on Fire|Only by the Night",
  "Kings of Leon|Use Somebody|Only by the Night",
  "Lady Gaga|Just Dance|The Fame",
  "Lady Gaga|Poker Face|The Fame",
  "Taylor Swift|You Belong with Me|Fearless",
  "Britney Spears|Circus|Circus",
  "Pink|Sober|Funhouse",
  "OneRepublic|Apologize|Dreaming Out Loud",
  "Estelle|American Boy|Shine",
  "Beyoncé|Single Ladies (Put a Ring on It)|I Am... Sasha Fierce",
  "Beyoncé|If I Were a Boy|I Am... Sasha Fierce",
  "Duffy|Mercy|Rockferry",
  "Kelly Clarkson|My Life Would Suck Without You|All I Ever Wanted",
];
