export default [
  "The Black Eyed Peas|Boom Boom Pow|",
  "Lady Gaga feat. Colby O'Donis|Just Dance|",
  "The Black Eyed Peas|I Gotta Feeling|",
  "Flo Rida|Right Round|",
  "The All-American Rejects|Gives You Hell|",
  "T.I. feat. Justin Timberlake|Dead And Gone|",
  "The Fray|You Found Me|",
  "Keri Hilson feat. Kanye West and Ne-Yo|Knock You Down|",
  "Jamie Foxx feat. T-Pain|Blame It|",
  "Pitbull|I Know You Want Me (Calle Ocho)|",
  "Soulja Boy Tell 'em feat. Sammie|Kiss Me Thru The Phone|",
  "Jay Sean feat. Lil Wayne|Down|",
  "Miley Cyrus|The Climb|",
  "Beyonce|Halo|",
  "Shinedown|Second Chance|",
  "Miley Cyrus|Party in the U.S.A.|",
  "3OH!3|Don't Trust Me|",
  "Jay-Z, Rihanna and Kanye West|Run This Town|",
  "Sean Kingston|Fire Burning|",
  "Jason DeRulo|Whatcha Say|",
  "Lady Gaga|Lovegame|",
  "Katy Perry|Waking Up In Vegas|",
  "Jeremih|Birthday Sex|",
  "Mariah Carey|Obsessed|",
  "Ne-Yo|Mad|",
  "Cobra Starship feat. Leighton Meester|Good Girls Go Bad|",
  "Pitbull|Hotel Room Service|",
  "Eminem, Dr. Dre and 50 Cent|Crack A Bottle|",
  "Keri Hilson feat. Lil Wayne|Turning Me On|",
  "The Pussycat Dolls|I Hate This Part|",
  "Nickelback|Gotta Be Somebody|",
  "Pink|Please Don't Leave Me|",
  "Lady Gaga|Paparazzi|",
  "Akon feat. Colby O'Donis and Kardinal Offishall|Beautiful|",
  "Akon|Right Now (Na Na Na)|",
  "Jordin Sparks|Battlefield|",
  "Flo Rida feat. Wynter|Sugar|",
  "Owl City|Fireflies|",
  "Linkin Park|New Divide|",
  "Jay-Z + Alicia Keys|Empire State Of Mind|",
  "Daughtry|No Surprise|",
  "Shakira|She Wolf|",
  "Mario feat. Gucci Mane and Sean Garrett|Break Up|",
  "Beyonce|Sweet Dreams|",
  "Young Money|Every Girl|",
  "Colbie Caillat|Fallin' For You|",
  "The Veronicas|Untouched|",
  "Nickelback|If Today Was Your Last Day|",
  "Fabolous feat. The-Dream|Throw It In The Bag|",
  "Boys Like Girls|Love Drunk|",
  "Asher Roth|I Love College|",
  "Britney Spears|If U Seek Amy|",
  "Jason Aldean|Big Green Tractor|",
  "Taylor Swift|White Horse|",
  "Green Day|21 Guns|",
  "Soulja Boy Tell'em|Turn My Swag On|",
  "The-Dream|Rockin' That Thang|",
  "Zac Brown Band|Chicken Fried|",
  "Beyonce|Diva|",
  "Iyaz|Replay|",
  "Brad Paisley|Then|",
  "Rob Thomas|Her Diamonds|",
  "Jesse McCartney feat. Ludacris|How Do You Sleep?|",
  "Britney Spears|3|",
  "Drake feat. Kanye West, Lil Wayne and Eminem|Forever|",
  "Justin Bieber|One Time|",
  "Lady Antebellum|I Run To You|",
  "Kelly Clarkson|I Do Not Hook Up|",
  "John Legend feat. Andre 3000|Green Light|",
  "Billy Currington|People Are Crazy|",
  "Zac Brown Band|Whatever It Is|",
  "Kelly Clarkson|Already Gone|",
  "Kristinia DeBarge|Goodbye|",
  "Michael Franti and Spearhead feat. Cherine Anderson|Say Hey (I Love You)|",
  "Jim Jones and Ron Browz feat. Juelz Santana|Pop Champagne|",
  "Maxwell|Pretty Wings|",
  "The Fray|Never Say Never|",
  "Lady Gaga|Bad Romance|The Fame Monster",
  "Black Eyed Peas|I Gotta Feeling|The E.N.D.",
  "Black Eyed Peas|Boom Boom Pow|The E.N.D.",
  "Black Eyed Peas|Meet Me Halfway|The E.N.D.",
  "Florence + The Machine|Dog Days Are Over|Lungs",
  "La Roux|Bulletproof|La Roux",
  "Jay Sean|Down|All or Nothing",
  "Rihanna|Russian Roulette|Rated R",
  "Kesha|Tik Tok|Animal",
  "Whitney Houston|I Look to You|I Look to You",
  "Paramore|Ignorance|Brand New Eyes",
  "Pearl Jam|The Fixer|Backspacer",
  "Shakira|Did It Again|She Wolf",
  "Lady Gaga|Telephone|The Fame Monster",
  "Rihanna|Only Girl (In the World)|Loud",
  "Bruno Mars|Just the Way You Are|Doo-Wops & Hooligans",
  "Arcade Fire|The Suburbs|The Suburbs",
  "Katy Perry|Firework|Teenage Dream",
  "Adele|Rolling in the Deep|21",
  "Adele|Someone Like You|21",
  "Gotye|Somebody That I Used to Know|Making Mirrors",
  "LMFAO|Party Rock Anthem|Sorry for Party Rocking",
  "Maroon 5|Moves Like Jagger|Hands All Over",
];
