export default [
  "Ke$ha|TiK ToK|",
  "Lady Antebellum|Need You Now|",
  "Train|Hey, Soul Sister|",
  "Katy Perry feat. Snoop Dogg|California Gurls|",
  "Usher feat. will.i.am|OMG|",
  "B.o.B feat. Hayley Williams|Airplanes|",
  "Taio Cruz|Dynamite|",
  "Taio Cruz feat. Ludacris|Break Your Heart|",
  "B.o.B feat. Bruno Mars|Nothin' On You|",
  "Enrique Iglesias feat. Pitbull|I Like It|",
  "Young Money feat. Lloyd|Bedrock|",
  "Jason Derulo|In My Head|",
  "Rihanna|Rude Boy|",
  "Lady Gaga feat. Beyonce|Telephone|",
  "Katy Perry|Teenage Dream|",
  "Mike Posner|Cooler Than Me|",
  "Black Eyed Peas|Imma Be|",
  "Jay-Z and Alicia Keys|Empire State of Mind|",
  "Usher feat. Pitbull|DJ Got Us Fallin' in Love|",
  "Travie McCoy feat. Bruno Mars|Billionaire|",
  "Eminem|Not Afraid|",
  "David Guetta feat. Akon|Sexy Chick|",
  "The Script|Breakeven|",
  "Ke$ha|Your Love Is My Drug|",
  "Trey Songz feat. Fabolous|Say Aah|",
  "Lady Gaga|Alejandro|",
  "Jason Derulo|Ridin' Solo|",
  "Nelly|Just A Dream|",
  "Ludacris|How Low|",
  "Far East Movement feat. The Cataracs and Dev|Like A G6|",
  "Timbaland feat. Justin Timberlake|Carry Out|",
  "Michael Buble|Haven't Met You Yet|",
  "Flo Rida feat. David Guetta|Club Can't Handle Me|",
  "Justin Bieber feat. Ludacris|Baby|",
  "Adam Lambert|Whataya Want From Me|",
  "Taylor Swift|Mine|",
  "Kris Allen|Live Like We're Dying|",
  "Rihanna feat. Jeezy|Hard|",
  "Jay-Z and Mr. Hudson|Young Forever|",
  "Ke$ha feat. 3OH!3|Blah Blah Blah|",
  "Trey Songz feat. Nicki Minaj|Bottoms Up|",
  "Jay Sean feat. Sean Paul & Lil Jon|Do You Remember|",
  "OneRepublic|All The Right Moves|",
  "Orianthi|According To You|",
  "Ludacris feat. Nicki Minaj|My Chick Bad|",
  "Ke$ha|Take It Off|",
  "Neon Trees|Animal|",
  "Maroon 5|Misery|",
  "B.o.B feat. Rivers Cuomo|Magic|",
  "New Boyz feat. Ray J|Tie Me Down|",
  "Nicki Minaj|Your Love|",
  "Chris Brown feat. Tyga and Kevin McCall|Deuces|",
  "Shontelle|Impossible|",
  "Boys Like Girls feat. Taylor Swift|Two Is Better Than One|",
  "3OH!3 feat. Ke$ha|My First Kiss|",
  "Black Eyed Peas|Rock That Body|",
  "OneRepublic|Secrets|",
  "Selena Gomez and The Scene|Naturally|",
  "Alicia Keyes|Un-Thinkable (I'm Ready)|",
  "DJ Khaled feat. T-Pain, Ludacris, Snoop Dogg and Rick Ross|All I Do Is Win|",
  "Kevin Rudolf feat. Birdman, Jay Sean, & Lil Wayne|I Made It (Cash Money Heroes)|",
  "Sugarland|Stuck Like Glue|",
  "Usher feat. Plies|Hey Daddy (Daddy's Home)|",
  "Usher|There Goes My Baby|",
  "Taylor Swift|Today Was A Fairytale|",
  "Timbaland feat. Drake|Say Something|",
  "Carrie Underwood|Undo It|",
  "Sean Kingston and Justin Bieber|Eenie Meenie|",
  "Lil Wayne feat. Drake|Right Above It|",
  "Miranda Lambert|The House That Built Me|",
  "The Band Perry|If I Die Young|",
  "Paramore|The Only Exception|",
  "Lady Antebellum|American Honey|",
  "Sara Bareilles|King Of Anything|",
  "Daughtry|Life After You|",
  "Uncle Kraker|Smile|",
  "Cali Swag District|Teach Me How To Dougie|",
  "Alicia Keyes|Try Sleeping With A Broken Heart|",
  "Jerrod Niemann|Lover, Lover|",
  "Fun.|We Are Young|Some Nights",
  "Carly Rae Jepsen|Call Me Maybe|Kiss",
  "PSY|Gangnam Style|",
  "Rihanna|We Found Love|Talk That Talk",
  "Maroon 5|Payphone|Overexposed",
  "Daft Punk|Get Lucky|Random Access Memories",
  "Lorde|Royals|Pure Heroine",
  "Avicii|Wake Me Up|True",
  "Miley Cyrus|Wrecking Ball|Bangerz",
  "OneRepublic|Counting Stars|Native",
  "Capital Cities|Safe and Sound|In a Tidal Wave of Mystery",
  "Imagine Dragons|Demons|Night Visions",
  "Bruno Mars|When I Was Your Man|Unorthodox Jukebox",
  "Bruno Mars|Locked Out of Heaven|Unorthodox Jukebox",
  "Pink|Just Give Me a Reason|The Truth About Love",
  "Justin Timberlake|Mirrors|The 20/20 Experience",
  "Justin Timberlake|Suit & Tie|The 20/20 Experience",
  "Robin Thicke|Blurred Lines|Blurred Lines",
  "Imagine Dragons|Radioactive|Night Visions",
  "Pharrell Williams|Happy|G I R L",
  "Sam Smith|Stay with Me|In the Lonely Hour",
];
