export default [
  "LMFAO feat. Lauren Bennett & GoonRock|Party Rock Anthem|",
  "Katy Perry feat. Kanye West|E.T.|",
  "Pitbull feat. Ne-Yo, Afrojack & Nayer|Give Me Everything|",
  "Bruno Mars|Grenade|",
  "Cee Lo Green|F**K You (Forget You)|",
  "Nicki Minaj|Super Bass|",
  "Maroon 5 feat. Christina Aguilera|Moves Like Jagger|",
  "The Black Eyed Peas|Just Can't Get Enough|",
  "Jennifer Lopez feat. Pitbull|On The Floor|",
  "Rihanna|S&M|",
  "Foster The People|Pumped Up Kicks|",
  "Katy Perry|Last Friday Night (T.G.I.F.)|",
  "Enrique Iglesias feat. Ludacris & DJ Frank E|Tonight (I'm Lovin' You)|",
  "P!Nk|Raise Your Glass|",
  "Lady Gaga|Born This Way|",
  "P!Nk|F**Kin' Perfect|",
  "Rihanna feat. Drake|What's My Name?|",
  "Chris Brown feat. Lil Wayne & Busta Rhymes|Look At Me Now|",
  "Jeremih feat. 50 Cent|Down On Me|",
  "Lil Wayne|How To Love|",
  "OneRepublic|Good Life|",
  "Bruno Mars|The Lazy Song|",
  "Britney Spears|Till The World Ends|",
  "Lupe Fiasco|The Show Goes On|",
  "Lady Gaga|The Edge Of Glory|",
  "Ke$Ha|We R Who We R|",
  "Wiz Khalifa|Black And Yellow|",
  "Hot Chelle Rae|Tonight Tonight|",
  "Ke$Ha|Blow|",
  "Bad Meets Evil feat. Bruno Mars|Lighters|",
  "Gym Class Heroes feat. Adam Levine|Stereo Hearts|",
  "The Black Eyed Peas|The Time (Dirty Bit)|",
  "Diddy &#8211; Dirty Money feat. Skylar Grey|Coming Home|",
  "Pitbull feat. T-Pain|Hey Baby (Drop It To The Floor)|",
  "Lil Wayne feat. Cory Gunz|6 Foot 7 Foot|",
  "Lady Antebellum|Just A Kiss|",
  "Jason Aldean|Dirt Road Anthem|",
  "Waka Flocka Flame feat. Roscoe Dash & Wale|No Hands|",
  "Britney Spears|I Wanna Go|",
  "DJ Khaled feat. Drake, Rick Ross & Lil Wayne|I'm On One|",
  "Cobra Starship feat. Sabi|You Make Me Feel&#8230;|",
  "Chris Brown|Yeah 3x|",
  "Nicki Minaj feat. Drake|Moment 4 Life|",
  "Dr. Dre feat. Eminem & Skylar Grey|I Need A Doctor|",
  "Kelly Rowland feat. Lil Wayne|Motivation|",
  "Edward Maya & Vika Jigulina|Stereo Love|",
  "Christina Perri|Jar Of Hearts|",
  "Wiz Khalifa|Roll Up|",
  "LMFAO|Sexy And I Know It|",
  "Far*East Movement feat. Ryan Tedder|Rocketeer|",
  "Britney Spears|Hold It Against Me|",
  "Usher|More|",
  "Avril Lavigne|What The Hell|",
  "Tinie Tempah feat. Eric Turner|Written In The Stars|",
  "The Script|For The First Time|",
  "Blake Shelton|Honey Bee|",
  "Jason Aldean With Kelly Clarkson|Don't You Wanna Stay|",
  "Rihanna feat. Calvin Harris|We Found Love|",
  "Keri Hilson|Pretty Girl Rock|",
  "Lady Gaga|You And I|",
  "Far*East Movement feat. Cataracs & Dev|Like A G6|",
  "David Guetta feat. Usher|Without You|",
  "Taylor Swift|Back To December|",
  "Eli Young Band|Crazy Girl|",
  "Rihanna|Cheers (Drink To That)|",
  "Selena Gomez & The Scene|Who Says|",
  "Jake Owen|Barefoot Blue Jean Night|",
  "Zac Brown Band feat. Jimmy Buffett|Knee Deep|",
  "Luke Bryan|Country Girl (Shake It For Me)|",
  "Brad Paisley With Carrie Underwood|Remind Me|",
  "Dev|In The Dark|",
  "New Boyz feat. The Cataracs & Dev|Backseat|",
  "Beyonce|Best Thing I Never Had|",
  "Jason Derulo|Don't Wanna Go Home|",
  "David Guetta feat. Flo Rida & Nicki Minaj|Where Them Girls At|",
  "Chris Brown|She Ain't You|",
  "Rodney Atkins|Take A Back Road|",
  "Mike Posner|Please Don't Go|",
  "Miguel|Sure Thing|",
  "Jessie J feat. B.O.B|Price Tag|",
  "Blake Shelton|God Gave Me You|",
  "Lil Wayne feat. Drake|She Will|",
  "Thompson Square|Are You Gonna Kiss Me Or Not|",
  "Kenny Chesney feat. Grace Potter|You And Tequila|",
  "Zac Brown Band|Colder Weather|",
  "Big Sean feat. Chris Brown|My Last|",
  "Sia|Chandelier|1000 Forms of Fear",
  "Mark Ronson|Uptown Funk|Uptown Special",
  "Hozier|Take Me to Church|Hozier",
  "John Legend|All of Me|Love in the Future",
  "Katy Perry|Dark Horse|Prism",
  "Clean Bandit|Rather Be|New Eyes",
  "Ariana Grande|Problem|My Everything",
  "Ed Sheeran|Thinking Out Loud|x",
  "Ed Sheeran|Photograph|x",
  "The Weeknd|Can't Feel My Face|Beauty Behind the Madness",
  "Taylor Swift|Blank Space|1989",
  "Taylor Swift|Shake It Off|1989",
  "Maroon 5|Sugar|V",
  "Walk the Moon|Shut Up and Dance|Talking Is Hard",
];
