export default [
  "Macklemore & Ryan Lewis featuring Wanz|Thrift Shop|",
  "Robin Thicke featuring T.I. and Pharrell Williams|Blurred Lines|",
  "Baauer|Harlem Shake|",
  "Macklemore & Ryan Lewis featuring Ray Dalton|Can't Hold Us|",
  "Pink featuring Nate Ruess|Just Give Me a Reason|",
  "Florida Georgia Line featuring Nelly|Cruise|",
  "Katy Perry|Roar|",
  "Rihanna featuring Mikky Ekko|Stay|",
  "Daft Punk featuring Pharrell Williams|Get Lucky|",
  "Taylor Swift|I Knew You Were Trouble|",
  "\"Wrecking Ball\"|We Can't Stop\"\nMiley Cyrus\n\n\n18|",
  "Justin Timberlake featuring Jay-Z|Suit & Tie|",
  "Anna Kendrick|Cups (Pitch Perfect's When I'm Gone)|",
  "Jay-Z featuring Justin Timberlake|Holy Grail|",
  "Will.i.am featuring Britney Spears|Scream & Shout|",
  "Zedd featuring Foxes|Clarity|",
  "Awolnation|Sail|",
  "Swedish House Mafia featuring John Martin|Don't You Worry Child|",
  "Icona Pop featuring Charli XCX|I Love It|",
  "Bruno Mars|Treasure|",
  "Ariana Grande featuring Mac Miller|The Way|",
  "Selena Gomez|Come & Get It|",
  "Drake featuring Majid Jordan|Hold On, We're Going Home|",
  "Maroon 5|Daylight|",
  "Pitbull featuring Christina Aguilera|Feel This Moment|",
  "Lady Gaga|Applause|",
  "Lil Wayne featuring Drake and Future|Love Me|",
  "Fall Out Boy|My Songs Know What You Did in the Dark (Light Em Up)|",
  "ASAP Rocky featuring Drake, 2 Chainz and Kendrick Lamar|Fuckin' Problems|",
  "Justin Bieber featuring Nicki Minaj|Beauty and a Beat|",
  "Macklemore & Ryan Lewis featuring Mary Lambert|Same Love|",
  "Calvin Harris featuring Florence Welch|Sweet Nothing|",
  "Lana Del Rey and Cédric Gervais|Summertime Sadness|",
  "J. Cole featuring Miguel|Power Trip|",
  "Alicia Keys featuring Nicki Minaj|Girl on Fire|",
  "Demi Lovato|Heart Attack|",
  "Maroon 5|Love Somebody|",
  "Mumford & Sons|I Will Wait|",
  "Pink|Try|",
  "Darius Rucker|Wagon Wheel|",
  "Calvin Harris featuring Ellie Goulding|I Need Your Love|",
  "Kesha|Die Young|",
  "Wale featuring Tiara Thomas or Rihanna|Bad|",
  "Blake Shelton featuring Pistol Annies and Friends|Boys 'Round Here|",
  "Phillip Phillips|Gone, Gone, Gone|",
  "Flo Rida|I Cry|",
  "Of Monsters and Men|Little Talks|",
  "Jason Derulo|The Other Side|",
  "Eminem|Berzerk|",
  "Kelly Clarkson|Catch My Breath|",
  "Luke Bryan|Crash My Party|",
  "Rihanna|Pour It Up|",
  "Taylor Swift|22|",
  "Hunter Hayes|I Want Crazy|",
  "Ylvis|The Fox (What Does the Fox Say?)|",
  "One Direction|Best Song Ever|",
  "Ed Sheeran|The A Team|",
  "Fun|Carry On|",
  "Tim McGraw featuring Taylor Swift and Keith Urban|Highway Don't Care|",
  "Luke Bryan|That's My Kind of Night|",
  "Blake Shelton|Sure Be Cool If You Did|",
  "Mariah Carey featuring Miguel|#Beautiful|",
  "Olly Murs featuring Flo Rida|Troublemaker|",
  "Ciara|Body Party|",
  "The Script featuring will.i.am|Hall of Fame|",
  "Rocko featuring Future and Rick Ross|U.O.E.N.O.|",
  "Emeli Sandé|Next to Me|",
  "Miranda Lambert|Mama's Broken Heart|",
  "Thomas Rhett|It Goes Like This|",
  "Ace Hood featuring Future and Rick Ross|Bugatti|",
  "Lady Antebellum|Downtown|",
  "Florida Georgia Line|Get Your Shine On|",
  "will.i.am featuring Justin Bieber|#thatPower|",
  "Sara Bareilles|Brave|",
  "Passenger|Let Her Go|",
  "Randy Houser|Runnin' Outta Moonlight|",
  "2 Chainz|I'm Different|",
  "Paramore|Still Into You|",
  "Rihanna|Work|Anti",
  "Flume|Never Be like You|Skin",
  "Ed Sheeran|Shape of You|÷",
  "Ed Sheeran|Castle on the Hill|÷",
  "Ed Sheeran|Galway Girl|÷",
  "Bruno Mars|That's What I Like|24K Magic",
  "Bruno Mars|24K Magic|24K Magic",
  "The Chainsmokers|Something Just like This|Memories...Do Not Open",
  "Dua Lipa|New Rules|Dua Lipa",
  "Harry Styles|Sign of the Times|Harry Styles",
  "Portugal. The Man|Feel It Still|Woodstock",
  "Imagine Dragons|Believer|Evolve",
  "Imagine Dragons|Thunder|Evolve",
  "Luis Fonsi|Despacito|Vida",
  "Taylor Swift|Look What You Made Me Do|Reputation",
  "Sam Smith|Too Good at Goodbyes|The Thrill of It All",
  "Zedd|The Middle|",
  "Camila Cabello|Havana|Camila",
  "Charlie Puth|Attention|Voicenotes",
  "Shawn Mendes|There's Nothing Holdin' Me Back|Illuminate",
  "Maroon 5|What Lovers Do|Red Pill Blues",
  "Kelly Clarkson|Love So Soft|Meaning of Life",
];
