export default [
  "Katy Perry featuring Juicy J|Dark Horse|",
  "Iggy Azalea featuring Charli XCX|Fancy|",
  "Jason Derulo featuring 2 Chainz|Talk Dirty|",
  "Magic!|Rude|",
  "Meghan Trainor|All About That Bass|",
  "Ariana Grande featuring Iggy Azalea|Problem|",
  "Pitbull featuring Kesha|Timber|",
  "Bastille|Pompeii|",
  "Nico & Vinz|Am I Wrong|",
  "DJ Snake and Lil Jon|Turn Down for What|",
  "Eminem featuring Rihanna|The Monster|",
  "A Great Big World and Christina Aguilera|Say Something|",
  "Lorde|Team|",
  "Idina Menzel|Let It Go|",
  "One Direction|Story of My Life|",
  "Iggy Azalea featuring Rita Ora|Black Widow|",
  "Jessie J, Ariana Grande and Nicki Minaj|Bang Bang|",
  "Disclosure featuring Sam Smith|Latch|",
  "Maroon 5|Maps|",
  "Chris Brown featuring Lil Wayne and French Montana or Too Short or Tyga|Loyal|",
  "American Authors|Best Day of My Life|",
  "Tove Lo|Habits (Stay High)|",
  "Calvin Harris|Summer|",
  "Charli XCX|Boom Clap|",
  "Beyoncé featuring Jay-Z|Drunk in Love|",
  "Ariana Grande featuring Zedd|Break Free|",
  "Enrique Iglesias featuring Descemer Bueno and Gente de Zona|Bailando|",
  "Ellie Goulding|Burn|",
  "Jason Derulo featuring Snoop Dogg|Wiggle|",
  "Clean Bandit featuring Jess Glynne|Rather Be|",
  "Jeremih featuring YG|Don't Tell 'Em|",
  "Kid Ink featuring Chris Brown|Show Me|",
  "Justin Timberlake|Not a Bad Thing|",
  "Paramore|Ain't It Fun|",
  "Aloe Blacc|The Man|",
  "Florida Georgia Line featuring Luke Bryan|This Is How We Roll|",
  "MKTO|Classic|",
  "Coldplay|A Sky Full of Stars|",
  "Ed Sheeran|Don't|",
  "Trey Songz|Na Na|",
  "Bobby Shmurda|Hot Boy|",
  "Ed Sheeran|Sing|",
  "YG featuring Jeezy and Rich Homie Quan|My Hitta|",
  "Echosmith|Cool Kids|",
  "Avicii|Hey Brother|",
  "Jason Derulo|Trumpets|",
  "Maroon 5|Animals|",
  "Jason Aldean|Burnin' It Down|",
  "Luke Bryan|Play It Again|",
  "Tinashe featuring ScHoolboy Q|2 On|",
  "Florida Georgia Line|Dirt|",
  "OneRepublic|Love Runs Out|",
  "Brantley Gilbert|Bottoms Up|",
  "Becky G|Shower|",
  "Rixton|Me and My Broken Heart|",
  "Martin Garrix|Animals|",
  "Rich Gang featuring Young Thug and Rich Homie Quan|Lifestyle|",
  "Kenny Chesney|American Kids|",
  "The Neighbourhood|Sweater Weather|",
  "Sam Hunt|Leave the Night On|",
  "Chris Brown featuring Usher and Rick Ross|New Flame|",
  "Michael Jackson and Justin Timberlake|Love Never Felt So Good|",
  "Dierks Bentley|Drunk on a Plane|",
  "Katy Perry|Birthday|",
  "Lady Antebellum|Bartender|",
  "Naughty Boy featuring Sam Smith|La La La|",
  "Lady Gaga featuring R. Kelly|Do What U Want|",
  "Shakira featuring Rihanna|Can't Remember to Forget You|",
  "5 Seconds of Summer|Amnesia|",
  "T.I. featuring Iggy Azalea|No Mediocre|",
  "KONGOS|Come with Me Now|",
  "Lil Wayne featuring Drake|Believe Me|",
  "Mike WiLL Made-It featuring Miley Cyrus, Wiz Khalifa, and Juicy J|23|",
  "Jake Owen|Beachin'|",
  "Macklemore & Ryan Lewis featuring ScHoolboy Q and Hollis|White Walls|",
  "5 Seconds of Summer|She Looks So Perfect|",
  "Zedd featuring Hayley Williams|Stay the Night|",
  "Beyoncé|Partition|",
  "ScHoolboy Q featuring BJ the Chicago Kid|Studio|",
  "Drake|0 to 100 / The Catch Up|",
  "Lee Brice|I Don't Dance|",
  "Miranda Lambert and Carrie Underwood|Somethin' Bad|",
  "Miley Cyrus|Adore You|",
  "Kesha|Praying|Rainbow",
  "Clean Bandit|Symphony|What Is Love?",
  "Selena Gomez|It Ain't Me|",
  "Maroon 5|Girls Like You|Red Pill Blues",
  "Dua Lipa|IDGAF|Dua Lipa",
  "Dua Lipa|One Kiss|Dua Lipa",
  "Camila Cabello|Never Be the Same|Camila",
  "Ariana Grande|thank u, next|thank u, next",
  "Ariana Grande|no tears left to cry|Sweetener",
  "Ariana Grande|God is a woman|Sweetener",
  "Lady Gaga|Shallow|A Star Is Born",
  "Marshmello|Happier|",
  "Billie Eilish|when the party's over|WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
  "Billie Eilish|lovely|",
  "Ed Sheeran|Perfect|÷",
  "Bebe Rexha|Meant to Be|Expectations",
  "Imagine Dragons|Natural|Origins",
];
