export default [
  "Mark Ronson featuring Bruno Mars|Uptown Funk|",
  "Wiz Khalifa featuring Charlie Puth|See You Again|",
  "Fetty Wap|Trap Queen|",
  "Silentó|Watch Me|",
  "\"The Hills\"|Earned It\"\nThe Weeknd\n\n\n10|",
  "OMI|Cheerleader (Felix Jaehn Remix)|",
  "Taylor Swift featuring Kendrick Lamar|Bad Blood|",
  "Major Lazer and DJ Snake featuring MØ|Lean On|",
  "Jason Derulo|Want to Want Me|",
  "Jack Ü featuring Justin Bieber|Where Are Ü Now|",
  "Rachel Platten|Fight Song|",
  "Fetty Wap featuring Remy Boyz|679|",
  "Meghan Trainor|Lips Are Movin|",
  "Fifth Harmony featuring Kid Ink|Worth It|",
  "Omarion featuring Chris Brown and Jhené Aiko|Post to Be|",
  "Andy Grammer|Honey, I'm Good.|",
  "Sam Smith|I'm Not the Only One|",
  "Selena Gomez featuring ASAP Rocky|Good for You|",
  "Taylor Swift|Style|",
  "David Guetta featuring Nicki Minaj, Bebe Rexha and Afrojack|Hey Mama|",
  "Flo Rida featuring Sage the Gemini and Lookas|G.D.F.R.|",
  "Justin Bieber|What Do You Mean?|",
  "Shawn Mendes|Stitches|",
  "Tove Lo|Talking Body|",
  "Nick Jonas|Jealous|",
  "Pitbull and Ne-Yo|Time of Our Lives|",
  "R. City featuring Adam Levine|Locked Away|",
  "Natalie La Rose featuring Jeremih|Somebody|",
  "Rihanna, Kanye West and Paul McCartney|FourFiveSeconds|",
  "Fall Out Boy|Centuries|",
  "Fetty Wap featuring Monty|My Way|",
  "Sam Hunt|Take Your Time|",
  "Big Sean featuring E-40|I Don't Fuck with You|",
  "Rihanna|Bitch Better Have My Money|",
  "Rich Homie Quan|Flex (Ooh, Ooh, Ooh)|",
  "T-Wayne|Nasty Freestyle|",
  "Nicki Minaj featuring Drake, Lil Wayne and Chris Brown|Only|",
  "Sia|Elastic Heart|",
  "Demi Lovato|Cool for the Summer|",
  "X Ambassadors|Renegades|",
  "Usher featuring Juicy J|I Don't Mind|",
  "Ariana Grande and The Weeknd|Love Me Harder|",
  "Taylor Swift|Wildest Dreams|",
  "DJ Snake and AlunaGeorge|You Know You Like It|",
  "Fall Out Boy|Uma Thurman|",
  "Beyoncé|7/11|",
  "Selena Gomez|The Heart Wants What It Wants|",
  "Little Big Town|Girl Crush|",
  "Trey Songz|Slow Motion|",
  "One Direction|Drag Me Down|",
  "Nicki Minaj featuring Drake and Lil Wayne|Truffle Butter|",
  "Ariana Grande|One Last Time|",
  "Nick Jonas|Chains|",
  "Meek Mill featuring Chris Brown and Nicki Minaj|All Eyes on You|",
  "Rae Sremmurd|No Type|",
  "Vance Joy|Riptide|",
  "Jidenna featuring Roman GianArthur|Classic Man|",
  "Elle King|Ex's & Oh's|",
  "Meghan Trainor|Dear Future Husband|",
  "Charlie Puth featuring Meghan Trainor|Marvin Gaye|",
  "Meghan Trainor featuring John Legend|Like I'm Gonna Lose You|",
  "James Newton Howard featuring Jennifer Lawrence|The Hanging Tree|",
  "O.T. Genasis|CoCo|",
  "Sam Smith|Lay Me Down|",
  "ILoveMakonnen featuring Drake|Tuesday|",
  "iLoveMemphis|Hit the Quan|",
  "Macklemore & Ryan Lewis featuring Eric Nally, Melle Mel, Kool Moe Dee and Grandmaster Caz|Downtown|",
  "Sam Hunt|House Party|",
  "Chris Brown and Tyga|Ayo|",
  "Luke Bryan|Kick the Dust Up|",
  "Big Sean featuring Drake and Kanye West|Blessings|",
  "George Ezra|Budapest|",
  "Kelly Clarkson|Heartbeat Song|",
  "Ella Henderson|Ghost|",
  "Alessia Cara|Here|",
  "Mr Probz|Waves (Robin Schulz Remix)|",
  "Nicky Jam and Enrique Iglesias|El Perdón|",
  "Ne-Yo featuring Juicy J|She Knows|",
  "One Direction|Night Changes|",
  "Drake|Back to Back|",
  "Calvin Harris and Disciples|How Deep Is Your Love|",
  "Imagine Dragons|Whatever It Takes|Evolve",
  "Shawn Mendes|In My Blood|Shawn Mendes",
  "Shawn Mendes|Lost in Japan|Shawn Mendes",
  "Halsey|Without Me|Manic",
  "Khalid|Love Lies|",
  "Khalid|Better|Suncity",
  "Clean Bandit|Solo|What Is Love?",
  "Anne-Marie|2002|Speak Your Mind",
  "Lauv|I Like Me Better|I met you when I was 18.",
  "Bazzi|Mine|Cosmic",
  "Zedd|Stay|",
  "Little Mix|Woman Like Me|LM5",
  "Panic! at the Disco|High Hopes|Pray for the Wicked",
  "5 Seconds of Summer|Youngblood|Youngblood",
  "Dan + Shay|Tequila|Dan + Shay",
  "Florida Georgia Line|Meant to Be|",
  "Benny Blanco|Eastside|",
  "Ariana Grande|breathin|Sweetener",
  "H.E.R.|Focus|I Used to Know Her",
];
