export default [
  "\"Sorry\"|Love Yourself\"\nJustin Bieber\n\n\n2|",
  "Drake featuring Wizkid and Kyla|One Dance|",
  "Rihanna featuring Drake|Work|",
  "Desiigner|Panda|",
  "The Chainsmokers featuring Daya|Don't Let Me Down|",
  "Justin Timberlake|Can't Stop the Feeling!|",
  "The Chainsmokers featuring Halsey|Closer|",
  "Sia featuring Sean Paul|Cheap Thrills|",
  "Lukas Graham|7 Years|",
  "Rihanna|Needed Me|",
  "Flo Rida|My House|",
  "Mike Posner|I Took a Pill in Ibiza|",
  "Fifth Harmony featuring Ty Dolla Sign|Work from Home|",
  "Calvin Harris featuring Rihanna|This Is What You Came For|",
  "DNCE|Cake by the Ocean|",
  "G-Eazy and Bebe Rexha|Me, Myself & I|",
  "\"Heathens\"|Ride\"\nTwenty One Pilots\n\n\n21|",
  "Zayn|Pillowtalk|",
  "Major Lazer featuring Justin Bieber and MØ|Cold Water|",
  "Adele|Send My Love (To Your New Lover)|",
  "The Chainsmokers featuring Rozes|Roses|",
  "Drake featuring Rihanna|Too Good|",
  "Future featuring The Weeknd|Low Life|",
  "The Weeknd|The Hills|",
  "P!nk|Just Like Fire|",
  "DRAM featuring Lil Yachty|Broccoli|",
  "Bryson Tiller|Don't|",
  "Ariana Grande|Dangerous Woman|",
  "Drake and Future|Jumpman|",
  "Gnash featuring Olivia O'Brien|I Hate U, I Love U|",
  "Selena Gomez|Same Old Love|",
  "Drake|Controlla|",
  "Charlie Puth|One Call Away|",
  "James Bay|Let It Go|",
  "Meghan Trainor|No|",
  "Zara Larsson and MNEK|Never Forget You|",
  "DJ Snake featuring Justin Bieber|Let Me Love You|",
  "Kent Jones|Don't Mind|",
  "Florida Georgia Line|H.O.L.Y.|",
  "Charlie Puth featuring Selena Gomez|We Don't Talk Anymore|",
  "Ariana Grande|Into You|",
  "Kiiara|Gold|",
  "Bryson Tiller|Exchange|",
  "Jeremih|Oui|",
  "Selena Gomez|Hands to Myself|",
  "Kevin Gates|2 Phones|",
  "The Weeknd featuring Daft Punk|Starboy|",
  "DJ Khaled featuring Drake|For Free|",
  "Flume featuring Kai|Never Be Like You|",
  "The Weeknd|In the Night|",
  "Meghan Trainor|Me Too|",
  "Thomas Rhett|Die a Happy Man|",
  "Post Malone|White Iverson|",
  "Nick Jonas featuring Tove Lo|Close|",
  "X Ambassadors|Unsteady|",
  "Lil Wayne, Wiz Khalifa and Imagine Dragons with Logic and Ty Dolla Sign featuring X Ambassadors|Sucker for Pain|",
  "Yo Gotti featuring Nicki Minaj|Down in the DM|",
  "Tory Lanez|Luv|",
  "Beyoncé|Sorry|",
  "Coldplay|Hymn for the Weekend|",
  "Tory Lanez|Say It|",
  "Travis Scott|Antidote|",
  "Ruth B|Lost Boy|",
  "Ariana Grande featuring Nicki Minaj|Side to Side|",
  "Daya|Sit Still, Look Pretty|",
  "DJ Snake featuring Bipolar Sunshine|Middle|",
  "Ellie Goulding|On My Mind|",
  "Drake featuring Jay-Z and Kanye West&#91;a&#93;|Pop Style|",
  "Adele|When We Were Young|",
  "Daya|Hide Away|",
  "Shawn Mendes and Camila Cabello|I Know What You Did Last Summer|",
  "Fat Joe and Remy Ma featuring French Montana and Infared|All the Way Up|",
  "Chris Brown|Back to Sleep|",
  "Usher featuring Young Thug|No Limit|",
  "O.T. Genasis featuring Young Dolph|Cut It|",
  "Kevin Gates|Really Really|",
  "Fifth Harmony featuring Fetty Wap|All In My Head (Flex)|",
  "Hailee Steinfeld and Grey featuring Zedd|Starving|",
  "Coldplay|Adventure of a Lifetime|",
  "Tim McGraw|Humble and Kind|",
  "Future|Wicked|",
  "Desiigner|Tiimmy Turner|",
  "One Direction|Perfect|",
  "Lauren Daigle|You Say|Look Up Child",
  "Luke Combs|Beautiful Crazy|This One's for You",
  "Selena Gomez|Back to You|13 Reasons Why",
  "Charlie Puth|How Long|Voicenotes",
  "Troye Sivan|My My My!|Bloom",
  "Bebe Rexha|I'm a Mess|Expectations",
  "Billie Eilish|bad guy|WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
  "Billie Eilish|bury a friend|WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
  "Ariana Grande|7 rings|thank u, next",
  "Ariana Grande|break up with your girlfriend, i'm bored|thank u, next",
  "Lizzo|Truth Hurts|Cuz I Love You",
  "Lizzo|Good as Hell|Cuz I Love You",
  "Lewis Capaldi|Someone You Loved|Divinely Uninspired to a Hellish Extent",
  "Tones and I|Dance Monkey|The Kids Are Coming",
  "Shawn Mendes|Señorita|",
  "Jonas Brothers|Sucker|Happiness Begins",
  "Jonas Brothers|Only Human|Happiness Begins",
];
