export default [
  "Luis Fonsi and Daddy Yankee featuring Justin Bieber|Despacito (Remix)|",
  "The Chainsmokers and Coldplay|Something Just Like This|",
  "Migos featuring Lil Uzi Vert|Bad and Boujee|",
  "Sam Hunt|Body Like a Back Road|",
  "Post Malone featuring Quavo|Congratulations|",
  "James Arthur|Say You Won't Let Go|",
  "DJ Khaled featuring Justin Bieber, Quavo, Chance the Rapper and Lil Wayne|I'm the One|",
  "Lil Uzi Vert|XO Tour Llif3|",
  "French Montana featuring Swae Lee|Unforgettable|",
  "Zedd and Alessia Cara|Stay|",
  "DJ Khaled featuring Rihanna and Bryson Tiller|Wild Thoughts|",
  "Rae Sremmurd featuring Gucci Mane|Black Beatles|",
  "Khalid|Location|",
  "Cardi B|Bodak Yellow|",
  "Childish Gambino|Redbone|",
  "Zayn and Taylor Swift|I Don't Wanna Live Forever|",
  "Kygo and Selena Gomez|It Ain't Me|",
  "Kyle featuring Lil Yachty|iSpy|",
  "Julia Michaels|Issues|",
  "Alessia Cara|Scars to Your Beautiful|",
  "Logic featuring Alessia Cara and Khalid|1-800-273-8255|",
  "Niall Horan|Slow Hands|",
  "Rihanna|Love on the Brain|",
  "The Weeknd featuring Daft Punk|I Feel It Coming|",
  "Big Sean|Bounce Back|",
  "Liam Payne featuring Quavo|Strip That Down|",
  "Drake|Fake Love|",
  "Maroon 5 featuring Kendrick Lamar|Don't Wanna Know|",
  "Machine Gun Kelly and Camila Cabello|Bad Things|",
  "The Chainsmokers|Paris|",
  "Clean Bandit featuring Sean Paul and Anne-Marie|Rockabye|",
  "Demi Lovato|Sorry Not Sorry|",
  "21 Savage|Bank Account|",
  "J Balvin and Willy William featuring Beyoncé|Mi Gente|",
  "Migos|T-shirt|",
  "Yo Gotti featuring Nicki Minaj|Rake It Up|",
  "Shawn Mendes|Mercy|",
  "Kodak Black|Tunnel Vision|",
  "Post Malone featuring 21 Savage|Rockstar|",
  "Brett Young|In Case You Didn't Know|",
  "Twenty One Pilots|Heathens|",
  "Halsey|Now or Never|",
  "Aminé|Caroline|",
  "Ayo & Teo|Rolex|",
  "Zay Hilfigerrr & Zayion McCall|Juju on That Beat (TZ Anthem)|",
  "Rae Sremmurd|Swang|",
  "Drake|Passionfruit|",
  "Kendrick Lamar featuring Rihanna|Loyalty|",
  "Travis Scott|Goosebumps|",
  "Maroon 5 featuring Future|Cold|",
  "Calvin Harris featuring Frank Ocean and Migos|Slide|",
  "Kane Brown featuring Lauren Alaina|What Ifs|",
  "Katy Perry featuring Skip Marley|Chained to the Rhythm|",
  "Calvin Harris featuring Pharrell Williams, Katy Perry and Big Sean|Feels|",
  "Jon Bellion|All Time Low|",
  "Luke Combs|Hurricane|",
  "Khalid|Young Dumb & Broke|",
  "Playboi Carti|Magnolia|",
  "SZA featuring Travis Scott|Love Galore|",
  "A Boogie wit da Hoodie featuring Kodak Black|Drowning|",
  "Gucci Mane featuring Drake|Both|",
  "P!nk|What About Us|",
  "Jason Derulo featuring Nicki Minaj and Ty Dolla Sign|Swalla|",
  "Migos featuring Gucci Mane|Slippery|",
  "Adele|Water Under the Bridge|",
  "Miley Cyrus|Malibu|",
  "Marian Hill|Down|",
  "Cheat Codes featuring Demi Lovato|No Promises|",
  "Gucci Mane featuring Migos|I Get the Bag|",
  "Dustin Lynch|Small Town Boy|",
  "YFN Lucci featuring PnB Rock|Everyday We Lit|",
  "Camila Cabello featuring Young Thug|Havana|",
  "Maroon 5 featuring SZA|What Lovers Do|",
  "Blackbear|Do Re Mi|",
  "XXXTentacion|Look at Me!|",
  "Keith Urban featuring Carrie Underwood|The Fighter|",
  "Khalid|Talk|Free Spirit",
  "Ed Sheeran|I Don't Care|No.6 Collaborations Project",
  "Ed Sheeran|Beautiful People|No.6 Collaborations Project",
  "Lady Gaga|Always Remember Us This Way|A Star Is Born",
  "Taylor Swift|You Need to Calm Down|Lover",
  "Taylor Swift|Lover|Lover",
  "Miley Cyrus|Mother's Daughter|SHE IS COMING",
  "Ava Max|Sweet but Psycho|Heaven & Hell",
  "Lizzo|Juice|Cuz I Love You",
  "Billie Eilish|all the good girls go to hell|WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
  "Taylor Swift|The Man|Lover",
  "Selena Gomez|Lose You to Love Me|Rare",
  "Dua Lipa|Don't Start Now|Future Nostalgia",
  "Sam Smith|How Do You Sleep?|Love Goes",
  "Dan + Shay|Speechless|Dan + Shay",
  "Maren Morris|The Bones|GIRL",
  "Maggie Rogers|Light On|Heard It in a Past Life",
  "Panic! at the Disco|Hey Look Ma, I Made It|Pray for the Wicked",
  "Luke Combs|Even Though I'm Leaving|What You See Is What You Get",
  "Katy Perry|Never Really Over|Smile",
  "Shawn Mendes|If I Can't Have You|",
  "Harry Styles|Adore You|Fine Line",
  "Normani|Motivation|",
  "Taylor Swift|ME!|Lover",
];
