export default [
  "Bebe Rexha featuring Florida Georgia Line|Meant to Be|",
  "Post Malone featuring Ty Dolla Sign|Psycho|",
  "Cardi B, Bad Bunny and J Balvin|I Like It|",
  "Zedd, Maren Morris and Grey|The Middle|",
  "Drake|In My Feelings|",
  "Maroon 5 featuring Cardi B|Girls Like You|",
  "Drake|Nice for What|",
  "Juice Wrld|Lucid Dreams|",
  "Post Malone|Better Now|",
  "Bruno Mars featuring Cardi B|Finesse|",
  "Ella Mai|Boo'd Up|",
  "XXXTentacion|Sad!|",
  "Khalid and Normani|Love Lies|",
  "BlocBoy JB featuring Drake|Look Alive|",
  "Taylor Swift|Delicate|",
  "Lil Baby and Drake|Yes Indeed|",
  "Marshmello and Anne-Marie|Friends|",
  "Halsey|Bad at Love|",
  "Tyga featuring Offset|Taste|",
  "NF|Let You Down|",
  "G-Eazy featuring ASAP Rocky and Cardi B|No Limit|",
  "6ix9ine featuring Nicki Minaj and Murda Beatz|Fefe|",
  "Migos, Nicki Minaj and Cardi B|MotorSport|",
  "Offset and Metro Boomin|Ric Flair Drip|",
  "Post Malone|I Fall Apart|",
  "The Weeknd and Kendrick Lamar|Pray for Me|",
  "Migos featuring Drake|Walk It Talk It|",
  "Lil Pump|Gucci Gang|",
  "G-Eazy and Halsey|Him & I|",
  "Kendrick Lamar and SZA|All the Stars|",
  "Migos|Stir Fry|",
  "Kendrick Lamar featuring Zacari|Love|",
  "Childish Gambino|This Is America|",
  "Drake|Nonstop|",
  "Kane Brown|Heaven|",
  "Lil Dicky featuring Chris Brown|Freaky Friday|",
  "6ix9ine|Gummo|",
  "Rich the Kid|Plug Walk|",
  "Maroon 5|Wait|",
  "Cardi B|Be Careful|",
  "Selena Gomez and Marshmello|Wolves|",
  "Cardi B featuring 21 Savage|Bartier Cardi|",
  "YG featuring 2 Chainz, Nicki Minaj and Big Sean|Big Bank|",
  "Max featuring Gnash|Lights Down Low|",
  "Calvin Harris and Dua Lipa|One Kiss|",
  "Jason Aldean|You Make It Easy|",
  "DJ Khaled featuring Justin Bieber, Chance the Rapper and Quavo|No Brainer|",
  "ASAP Ferg featuring Nicki Minaj|Plain Jane|",
  "Miguel featuring Travis Scott|Sky Walker|",
  "Thomas Rhett|Marry Me|",
  "Benny Blanco, Halsey and Khalid|Eastside|",
  "The Weeknd|Call Out My Name|",
  "Jay Rock, Kendrick Lamar, Future and James Blake|King's Dead|",
  "Marshmello and Bastille|Happier|",
  "Nio García, Darell and Casper Mágico featuring Bad Bunny, Nicky Jam and Ozuna|Te Boté|",
  "Florida Georgia Line|Simple|",
  "N.E.R.D and Rihanna|Lemon|",
  "Justin Timberlake featuring Chris Stapleton|Say Something|",
  "Drake|I'm Upset|",
  "Kenny Chesney|Get Along|",
  "XXXTentacion|Moonlight|",
  "Nicky Jam and J Balvin|X|",
  "YoungBoy Never Broke Again|Outside Today|",
  "Ella Mai|Trip|",
  "Daddy Yankee|Dura|",
  "XXXTentacion|Changes|",
  "Brett Young|Mercy|",
  "Luke Combs|One Number Away|",
  "Rae Sremmurd featuring Juicy J|Powerglide|",
  "Maroon 5|Memories|Jordi",
  "Kygo|Higher Love|",
  "Justin Bieber|10,000 Hours|",
  "Thomas Rhett|Look What God Gave Her|Center Point Road",
  "Luke Combs|Beer Never Broke My Heart|What You See Is What You Get",
  "P!nk|Walk Me Home|Hurts 2B Human",
  "Chris Brown|No Guidance|Indigo",
  "Miley Cyrus|Slide Away|",
  "Carrie Underwood|Southbound|Cry Pretty",
  "Miranda Lambert|It All Comes Out in the Wash|Wildcard",
  "Halsey|Nightmare|",
  "The Weeknd|Blinding Lights|After Hours",
  "The Weeknd|Save Your Tears|After Hours",
  "The Weeknd|Heartless|After Hours",
  "Harry Styles|Watermelon Sugar|Fine Line",
  "Harry Styles|Falling|Fine Line",
  "Dua Lipa|Break My Heart|Future Nostalgia",
  "Dua Lipa|Levitating|Future Nostalgia",
  "Dua Lipa|Physical|Future Nostalgia",
  "Lady Gaga|Rain on Me|Chromatica",
  "Lady Gaga|Stupid Love|Chromatica",
  "Taylor Swift|cardigan|folklore",
  "Taylor Swift|willow|evermore",
  "Taylor Swift|exile|folklore",
  "Miley Cyrus|Midnight Sky|Plastic Hearts",
  "Justin Bieber|Intentions|Changes",
  "Justin Bieber|Yummy|Changes",
  "Sam Smith|Diamonds|Love Goes",
  "Billie Eilish|Therefore I Am|",
  "Billie Eilish|my future|",
  "Ariana Grande|positions|Positions",
];
