export default [
  "Lil Nas X featuring Billy Ray Cyrus|Old Town Road|",
  "Post Malone and Swae Lee|Sunflower|",
  "Post Malone|Wow|",
  "Sam Smith and Normani|Dancing with a Stranger|",
  "Shawn Mendes and Camila Cabello|Señorita|",
  "Ed Sheeran and Justin Bieber|I Don't Care|",
  "Meek Mill featuring Drake|Going Bad|",
  "Lady Gaga and Bradley Cooper|Shallow|",
  "Chris Brown featuring Drake|No Guidance|",
  "DaBaby|Suge|",
  "J. Cole|Middle Child|",
  "Lil Baby and Gunna|Drip Too Hard|",
  "Lil Tecca|Ransom|",
  "Post Malone featuring Young Thug|Goodbyes|",
  "Kodak Black featuring Travis Scott and Offset|Zeze|",
  "Drake featuring Rick Ross|Money in the Grave|",
  "Cardi B and Bruno Mars|Please Me|",
  "Cardi B|Money|",
  "Lil Nas X|Panini|",
  "A Boogie wit da Hoodie|Look Back at It|",
  "21 Savage|A Lot|",
  "Taylor Swift featuring Brendon Urie|Me!|",
  "Bad Bunny featuring Drake|Mia|",
  "Polo G featuring Lil Tjay|Pop Out|",
  "Blueface|Thotiana|",
  "Sheck Wes|Mo Bamba|",
  "Ed Sheeran featuring Khalid|Beautiful People|",
  "Gucci Mane, Bruno Mars and Kodak Black|Wake Up in the Sky|",
  "Morgan Wallen|Whiskey Glasses|",
  "Blake Shelton|God's Country|",
  "Dean Lewis|Be Alright|",
  "Mustard and Migos|Pure Water|",
  "Blanco Brown|The Git Up|",
  "DJ Snake featuring Selena Gomez, Ozuna and Cardi B|Taki Taki|",
  "Ellie Goulding and Diplo featuring Swae Lee|Close to Me|",
  "Calboy|Envy Me|",
  "Post Malone|Circles|",
  "Young Thug, J. Cole and Travis Scott|The London|",
  "Daddy Yankee and Katy Perry featuring Snow|Con Calma|",
  "YNW Melly|Murder on My Mind|",
  "City Girls|Act Up|",
  "Shaed|Trampoline|",
  "Flipp Dinero|Leave Me Alone|",
  "Lil Baby|Close Friends|",
  "Pinkfong|Baby Shark|",
  "Saweetie|My Type|",
  "YK Osiris|Worth It|",
  "Luke Bryan|Knockin' Boots|",
  "Lee Brice|Rumor|",
  "A Boogie wit da Hoodie featuring 6ix9ine|Swervin|",
  "Lil Baby and DaBaby|Baby|",
  "Kane Brown|Good as You|",
  "Offset featuring Cardi B|Clout|",
  "Marshmello and Kane Brown|One Thing Right|",
  "Megan Thee Stallion featuring DaBaby|Cash Shit|",
  "NLE Choppa|Shotta Flow|",
  "Megan Thee Stallion featuring Nicki Minaj and Ty Dolla Sign|Hot Girl Summer|",
  "Florida Georgia Line|Talk You Out of It|",
  "Bazzi featuring Camila Cabello|Beautiful|",
  "Chase Rice|Eyes on You|",
  "Dan + Shay|All to Myself|",
  "Ariana Grande and Social House|Boyfriend|",
  "Pink|Walk Me Home|",
  "Juice Wrld|Robbery|",
  "Ariana Grande|34+35|Positions",
  "Doja Cat|Say So|Hot Pink",
  "Jawsh 685|Savage Love (Laxed - Siren Beat)|",
  "BENEE|Supalonely|Fire on Marzz",
  "Powfu|death bed|poems of the past",
  "Surfaces|Sunday Best|Where the Light Is",
  "Lewis Capaldi|Before You Go|Divinely Uninspired to a Hellish Extent",
  "Luke Combs|Forever After All|What You See Ain't Always What You Get",
  "Morgan Wallen|More Than My Hometown|Dangerous: The Double Album",
  "Chris Stapleton|Starting Over|Starting Over",
  "Fleetwood Mac|Dreams|Rumours",
  "BTS|Dynamite|BE",
  "JP Saxe|If the World Was Ending|It's the Worst Possible Time to Be Alive",
  "Gabby Barrett|I Hope|Goldmine",
  "Luke Combs|Lovin' on You|What You See Is What You Get",
  "AJR|Bang!|OK ORCHESTRA",
  "Miranda Lambert|Bluebird|Wildcard",
  "Zayn|Better|",
  "Maluma|Hawái|PAPI JUANCHO",
  "Carly Pearce & Lee Brice|I Hope You're Happy Now|Carly Pearce",
  "Ingrid Andress|More Hearts Than Mine|Lady Like",
  "Olivia Rodrigo|drivers license|SOUR",
  "Olivia Rodrigo|good 4 u|SOUR",
  "Olivia Rodrigo|deja vu|SOUR",
  "Olivia Rodrigo|traitor|SOUR",
  "Ed Sheeran|Bad Habits|=",
  "Ed Sheeran|Shivers|=",
  "Silk Sonic|Leave the Door Open|An Evening with Silk Sonic",
  "Glass Animals|Heat Waves|Dreamland",
  "Billie Eilish|Happier Than Ever|Happier Than Ever",
  "Adele|Easy on Me|30",
  "Coldplay|My Universe|Music of the Spheres",
  "Doja Cat|Kiss Me More|Planet Her",
  "Doja Cat|Need to Know|Planet Her",
  "Justin Bieber|Peaches|Justice",
  "Justin Bieber|Ghost|Justice",
];
