export default [
  "DaBaby featuring Roddy Ricch|Rockstar|",
  "Future featuring Drake|Life Is Good|",
  "Gabby Barrett featuring Charlie Puth|I Hope|",
  "Jack Harlow featuring DaBaby, Tory Lanez and Lil Wayne|Whats Poppin|",
  "Megan Thee Stallion featuring Beyoncé|Savage|",
  "Arizona Zervas|Roxanne|",
  "Justin Bieber featuring Quavo|Intentions|",
  "Billie Eilish|Everything I Wanted|",
  "Saint Jhn|Roses (Imanbek remix)|",
  "Trevor Daniel|Falling|",
  "Dan + Shay and Justin Bieber|10,000 Hours|",
  "Cardi B featuring Megan Thee Stallion|WAP|",
  "Mustard and Roddy Ricch|Ballin'|",
  "Blackbear|Hot Girl Bummer|",
  "Lil Mosey|Blueberry Faygo|",
  "DaBaby|Bop|",
  "Drake|Toosie Slide|",
  "Morgan Wallen|Chasin' You|",
  "Jawsh 685 and Jason Derulo|Savage Love (Laxed – Siren Beat)|",
  "Camila Cabello featuring DaBaby|My Oh My|",
  "Chris Brown and Young Thug|Go Crazy|",
  "Roddy Ricch featuring Mustard|High Fashion|",
  "Drake featuring Lil Durk|Laugh Now Cry Later|",
  "Lil Baby|Woah|",
  "Powfu featuring Beabadoobee|Death Bed|",
  "Travis Scott|Highest in the Room|",
  "24kGoldn featuring Iann Dior|Mood|",
  "Lady Gaga and Ariana Grande|Rain on Me|",
  "Pop Smoke featuring Lil Baby and DaBaby|For the Night|",
  "Black Eyed Peas and J Balvin|Ritmo (Bad Boys for Life)|",
  "Rod Wave|Heart on Ice|",
  "Blake Shelton and Gwen Stefani|Nobody but You|",
  "Juice Wrld and Marshmello|Come & Go|",
  "JP Saxe featuring Julia Michaels|If the World Was Ending|",
  "Lil Baby and 42 Dugg|We Paid|",
  "Old Dominion|One Man Band|",
  "Jason Aldean|Got What I Got|",
  "Eminem featuring Juice Wrld|Godzilla|",
  "Juice Wrld and YoungBoy Never Broke Again|Bandit|",
  "StaySolidRocky|Party Girl|",
  "Maddie & Tae|Die from a Broken Heart|",
  "DJ Khaled featuring Drake|Popstar|",
  "Mariah Carey|All I Want for Christmas Is You|",
  "Lee Brice|One of Them Girls|",
  "Sam Hunt|Hard to Forget|",
  "Luke Bryan|One Margarita|",
  "Young Thug featuring Gunna|Hot|",
  "Carly Pearce and Lee Brice|I Hope You're Happy Now|",
  "Lil Baby|Emotionally Scarred|",
  "YNW Melly featuring Juice Wrld|Suicidal|",
  "Lil Baby|The Bigger Picture|",
  "Pop Smoke featuring 50 Cent and Roddy Ricch|The Woo|",
  "Lil Baby|Sum 2 Prove|",
  "Ariana Grande and Justin Bieber|Stuck with U|",
  "Pop Smoke featuring Lil Tjay|Mood Swings|",
  "Halsey|You Should Be Sad|",
  "Benee featuring Gus Dapperton|Supalonely|",
  "The Scotts (Travis Scott and Kid Cudi)|The Scotts|",
  "Doja Cat and Tyga|Juicy|",
  "Kane Brown, Swae Lee and Khalid|Be Like That|",
  "Kane Brown|Homesick|",
  "Rod Wave featuring ATR Son Son|Rags2Riches|",
  "Juice Wrld|Wishing Well|",
  "Luke Combs featuring Eric Church|Does to Me|",
  "Jhené Aiko|Pussy Fairy (OTW)|",
  "Surf Mesa featuring Emilee|ILY (I Love You Baby)|",
  "Moneybagg Yo|Said Sum|",
  "H.E.R. featuring YG|Slide|",
  "NLE Choppa featuring Roddy Ricch|Walk Em Down|",
  "BTS|Butter|",
  "BTS|Permission to Dance|",
  "Taylor Swift|All Too Well (Taylor's Version)|Red (Taylor's Version)",
  "Masked Wolf|Astronaut in the Ocean|Astronaut in the Ocean",
  "Walker Hayes|Fancy Like|Country Stuff",
  "Chris Stapleton|You Should Probably Leave|Starting Over",
  "Carrie Underwood|If I Didn't Love You|Denim & Rhinestones",
  "Morgan Wallen|Wasted on You|Dangerous: The Double Album",
  "Giveon|Heartbreak Anniversary|Take Time",
  "Måneskin|Beggin'|Chosen",
  "PinkPantheress|Just for Me|",
  "Dermot Kennedy|Better Days|Without Fear",
  "Surf Mesa|ILY (I Love You Baby)|",
  "AJR|World's Smallest Violin|OK ORCHESTRA",
  "Tai Verdes|A-O-K|HDTV",
  "Riton|Friday (Dopamine Re-Edit)|",
  "SZA|Good Days|SOS",
  "Kane Brown|One Mississippi|Different Man",
  "Carly Pearce|Next Girl|29",
  "Elle King|Drunk (And I Don't Wanna Go Home)|Love Stuff",
  "Zac Brown Band|Same Boat|Comeback",
  "Eric Church|Stick That in Your Country Song|Heart & Soul",
  "Luke Bryan|Waves|Born Here Live Here Die Here",
  "Miranda Lambert|Settling Down|Wildcard",
  "Harry Styles|As It Was|Harry's House",
  "Harry Styles|Late Night Talking|Harry's House",
  "Kate Bush|Running Up That Hill (A Deal with God)|Hounds of Love",
  "Lizzo|About Damn Time|Special",
  "Beyoncé|Break My Soul|Renaissance",
  "Beyoncé|CUFF IT|Renaissance",
  "Taylor Swift|Anti-Hero|Midnights",
];
