export default [
  "The Weeknd and Ariana Grande|Save Your Tears|",
  "Doja Cat featuring SZA|Kiss Me More|",
  "Silk Sonic (Bruno Mars and Anderson .Paak)|Leave the Door Open|",
  "Lil Nas X|Montero (Call Me by Your Name)|",
  "Justin Bieber featuring Daniel Caesar and Giveon|Peaches|",
  "The Kid Laroi and Justin Bieber|Stay|",
  "The Kid Laroi|Without You|",
  "Ariana Grande featuring Doja Cat and Megan Thee Stallion|34+35|",
  "Pop Smoke|What You Know Bout Love|",
  "Machine Gun Kelly featuring Blackbear|My Ex's Best Friend|",
  "Lil Nas X and Jack Harlow|Industry Baby|",
  "Cardi B|Up|",
  "Bad Bunny and Jhay Cortez|Dakiti|",
  "Saweetie featuring Doja Cat|Best Friend|",
  "Polo G|Rapstar|",
  "Lil Tjay and 6lack|Calling My Phone|",
  "Maroon 5 featuring Megan Thee Stallion|Beautiful Mistakes|",
  "Justin Bieber featuring Chance the Rapper|Holy|",
  "Lil Baby|On Me|",
  "Tate McRae|You Broke Me First|",
  "Pooh Shiesty featuring Lil Durk|Back in Blood|",
  "Moneybagg Yo|Wockesha|",
  "Doja Cat and the Weeknd|You Right|",
  "SpotemGottem featuring Pooh Shiesty / SpotemGottem featuring DaBaby|Beat Box 2\" / \"Beat Box 3|",
  "Drake featuring Lil Baby|Wants and Needs|",
  "Drake featuring Future and Young Thug|Way 2 Sexy|",
  "Kali Uchis|Telepatía|",
  "CJ|Whoopty|",
  "Internet Money and Gunna featuring Don Toliver and Nav|Lemonade|",
  "Megan Thee Stallion|Body|",
  "Luke Combs|Better Together|",
  "Yung Bleu featuring Drake|You're Mines Still|",
  "DJ Khaled featuring Lil Baby and Lil Durk|Every Chance I Get|",
  "Wizkid featuring Justin Bieber and Tems|Essence|",
  "Ryan Hurd and Maren Morris|Chasing After You|",
  "Gabby Barrett|The Good Ones|",
  "Marshmello and Jonas Brothers|Leave Before You Love Me|",
  "Dan + Shay|Glad You Exist|",
  "Justin Bieber and Benny Blanco|Lonely|",
  "Doja Cat|Streets|",
  "Drake|What's Next|",
  "Chris Young and Kane Brown|Famous Friends|",
  "Nelly and Florida Georgia Line|Lil Bit|",
  "Megan Thee Stallion|Thot Shit|",
  "Roddy Ricch|Late at Night|",
  "Ava Max|Kings & Queens|",
  "Justin Bieber|Anyone|",
  "Mooski|Track Star|",
  "Moneybagg Yo|Time Today|",
  "Megan Thee Stallion featuring DaBaby|Cry Baby|",
  "Coi Leray featuring Lil Durk|No More Parties|",
  "Thomas Rhett|What's Your Country Song|",
  "Keith Urban and Pink|One Too Many|",
  "Duncan Laurence|Arcade|",
  "Bad Bunny|Yonaguni|",
  "Niko Moon|Good Time|",
  "Jason Aldean and Carrie Underwood|If I Didn't Love You|",
  "Drake featuring 21 Savage and Project Pat|Knife Talk|",
  "Ariana Grande|POV|",
  "Parmalee and Blanco Brown|Just the Way|",
  "The Weeknd|Take My Breath|",
  "Dua Lipa|We're Good|",
  "Eric Church|Hell of a View|",
  "Brenda Lee|Rockin' Around the Christmas Tree|",
  "Ritt Momney|Put Your Records On|",
  "Cole Swindell|Single Saturday Night|",
  "Lainey Wilson|Things a Man Oughta Know|",
  "BRS Kash|Throat Baby (Go Baby)|",
  "Rod Wave|Tombstone|",
  "Chase Rice featuring Florida Georgia Line|Drinkin' Beer. Talkin' God. Amen.|",
  "Rauw Alejandro|Todo de Ti|",
  "Taylor Swift|Lavender Haze|Midnights",
  "Steve Lacy|Bad Habit|Gemini Rights",
  "OneRepublic|I Ain't Worried|Top Gun: Maverick",
  "Joji|Glimpse of Us|Smithereens",
  "Elton John|Hold Me Closer|",
  "Gayle|abcdefu|a study of the human experience volume one",
  "Imagine Dragons|Bones|Mercury – Acts 1 & 2",
  "Sam Smith|Unholy|Gloria",
  "Kim Petras|Unholy|Gloria",
  "Luke Combs|The Kind of Love We Make|Growin' Up",
  "Morgan Wallen|You Proof|One Thing at a Time",
  "Walker Hayes|AA|Country Stuff the Album",
  "Carrie Underwood|Ghost Story|Denim & Rhinestones",
  "Parmalee|Take My Name|For You",
  "Cole Swindell|She Had Me at Heads Carolina|Stereotype",
  "Bailey Zimmerman|Fall in Love|",
  "Wet Leg|Chaise Longue|Wet Leg",
  "Rosalía|Despechá|Motomami",
  "Burna Boy|Last Last|Love, Damini",
  "Anitta|Envolver|Versions of Me",
  "Zach Bryan|Something in the Orange|",
  "Zach Bryan|From Austin|American Heartbreak",
  "Red Hot Chili Peppers|Black Summer|Unlimited Love",
  "Red Hot Chili Peppers|These Are the Ways|Unlimited Love",
  "Arctic Monkeys|There'd Better Be a Mirrorball|The Car",
  "Harry Styles|Daydreaming|Harry's House",
  "Harry Styles|Satellite|Harry's House",
  "Harry Styles|Music for a Sushi Restaurant|Harry's House",
  "Beyoncé|ALIEN SUPERSTAR|Renaissance",
];
