export default [
  "Jack Harlow|First Class|",
  "Kodak Black|Super Gremlin|",
  "Elton John and Dua Lipa|Cold Heart (Pnau Remix)|",
  "Future featuring Drake and Tems|Wait for U|",
  "Lil Nas X|Thats What I Want|",
  "Imagine Dragons and JID|Enemy|",
  "Bad Bunny and Chencho Corleone|Me Porto Bonito|",
  "Doja Cat|Woman|",
  "Bad Bunny|Tití Me Preguntó|",
  "Carolina Gaitán, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz and the Encanto cast|We Don't Talk About Bruno|",
  "Post Malone featuring Doja Cat|I Like You (A Happier Song)|",
  "Nicky Youre and Dazy|Sunroof|",
  "Post Malone and the Weeknd|One Right Now|",
  "Em Beihold|Numb Little Bug|",
  "Drake featuring 21 Savage|Jimmy Cooks|",
  "Cody Johnson|'Til You Can't|",
  "Silk Sonic (Bruno Mars and Anderson .Paak)|Smokin out the Window|",
  "Bad Bunny|Moscow Mule|",
  "Doja Cat|Vegas|",
  "Gunna and Future featuring Young Thug|Pushin P|",
  "Jordan Davis and Luke Bryan|Buy Dirt|",
  "SZA|I Hate U|",
  "Dove Cameron|Boyfriend|",
  "Jessica Darrow|Surface Pressure|",
  "CKay|Love Nwantiti (Ah Ah Ah)|",
  "Muni Long|Hrs and Hrs|",
  "Morgan Wallen|Sand in My Boots|",
  "Becky G and Karol G|Mamiii|",
  "Megan Thee Stallion and Dua Lipa|Sweetest Pie|",
  "Karol G|Provenza|",
  "Camila Cabello featuring Ed Sheeran|Bam Bam|",
  "Tyler Hubbard|5 Foot 9|",
  "Doja Cat|Get Into It (Yuh)|",
  "Bad Bunny|Efecto|",
  "Bailey Zimmerman|Rock and a Hard Place|",
  "Luke Combs|Doin' This|",
  "Adele|Oh My God|",
  "Neiked, Mae Muller and Polo G|Better Days|",
  "The Anxiety: Willow and Tyler Cole|Meet Me at Our Spot|",
  "Lauren Spencer-Smith|Fingers Crossed|",
  "Bad Bunny and Rauw Alejandro|Party|",
  "Bad Bunny|Después de la Playa|",
  "Lil Durk featuring Morgan Wallen|Broadway Girls|",
  "Lil Durk featuring Gunna|What Happened to Virgil|",
  "Future|Puffin on Zootiez|",
  "Kane Brown|Like I Love Country Music|",
  "Bobby Helms|Jingle Bell Rock|",
  "Bad Bunny and Bomba Estéreo|Ojitos Lindos|",
  "Jason Aldean|Trouble with a Heartbreak|",
  "Burl Ives|A Holly Jolly Christmas|",
  "Russell Dickerson featuring Jake Scott|She Likes It|",
  "Cole Swindell and Lainey Wilson|Never Say Never|",
  "Scotty McCreery|Damn Strait|",
  "Tate McRae|She's All I Wanna Be|",
  "Jon Pardi|Last Night Lonely|",
  "Ernest featuring Morgan Wallen|Flower Shops|",
  "Jnr Choi and Sam Tompkins|To the Moon|",
  "Sam Smith and Kim Petras|Unholy|",
  "Maren Morris|Circles Around This Town|",
  "Beyoncé|CHURCH GIRL|Renaissance",
  "Taylor Swift|Maroon|Midnights",
  "Taylor Swift|Karma|Midnights",
  "Steve Lacy|Static|Gemini Rights",
  "Joji|YEAH RIGHT|Nectar",
  "MUNA|What I Want|MUNA",
  "Florence + The Machine|Free|Dance Fever",
  "Maggie Rogers|Honey|Surrender",
  "JVKE|golden hour|this is what ____ feels like (Vol. 1-4)",
  "Stephen Sanchez|Until I Found You|Angel Face",
  "Farruko|Pepas|La 167",
  "SZA|Shirt|SOS",
  "Nicky Youre & dazy|Sunroof|",
  "LF System|Afraid to Feel|",
  "Beyoncé|SUMMER RENAISSANCE|Renaissance",
  "Beyoncé|VIRGO'S GROOVE|Renaissance",
  "Beyoncé|PLASTIC OFF THE SOFA|Renaissance",
  "Harry Styles|Love of My Life|Harry's House",
  "Harry Styles|Keep Driving|Harry's House",
  "Meghan Trainor|Made You Look|Takin It Back",
  "Meghan Trainor|Don't I Make It Look Easy|Takin It Back",
  "The Weeknd|Sacrifice|Dawn FM",
  "The Weeknd|Out of Time|Dawn FM",
  "Camila Cabello|Bam Bam|Familia",
  "Halsey|So Good|If I Can't Have Love, I Want Power",
  "Demi Lovato|SUBSTANCE|HOLY FVCK",
  "Måneskin|SUPERMODEL|",
  "Måneskin|The Loneliest|RUSH!",
  "Turnstile|NEW HEARTS|GLOW ON",
  "Paramore|This Is Why|This Is Why",
  "The 1975|Part of the Band|Being Funny in a Foreign Language",
  "Wet Leg|Wet Dream|Wet Leg",
  "Wet Leg|Angelica|Wet Leg",
  "Rosalía|BIZCOCHITO|Motomami",
  "SZA|Snooze|SOS",
  "Lana Del Rey|Snow On The Beach|Did you know that there's a tunnel under Ocean Blvd",
  "Lana Del Rey|Watercolor Eyes|Euphoria Season 2",
  "Imagine Dragons|Sharks|Mercury – Acts 1 & 2",
  "Panic! At The Disco|Viva Las Vengeance|Viva Las Vengeance",
  "Elton John & Britney Spears|Hold Me Closer|",
  "BLACKPINK|Pink Venom|Born Pink",
];
