export default [
  "Morgan Wallen|Last Night|",
  "Miley Cyrus|Flowers|",
  "SZA|Kill Bill|",
  "Metro Boomin, the Weeknd and 21 Savage|Creepin&#39;|",
  "Rema and Selena Gomez|Calm Down|",
  "The Weeknd and Ariana Grande|Die for You|",
  "Luke Combs|Fast Car|",
  "David Guetta and Bebe Rexha|I'm Good (Blue)|",
  "Drake and 21 Savage|Rich Flex|",
  "Chris Brown|Under the Influence|",
  "Taylor Swift|Cruel Summer|",
  "Morgan Wallen|Thinkin' Bout Me|",
  "PinkPantheress and Ice Spice|Boy's a Liar Pt. 2|",
  "Toosii|Favorite Song|",
  "Morgan Wallen|Thought You Should Know|",
  "Kane Brown and Katelyn Brown|Thank God|",
  "Lil Durk featuring J. Cole|All My Life|",
  "Eslabon Armado and Peso Pluma|Ella Baila Sola|",
  "Taylor Swift featuring Ice Spice|Karma|",
  "Lil Uzi Vert|Just Wanna Rock|",
  "Olivia Rodrigo|Vampire|",
  "Gunna|FukUMean|",
  "Coi Leray|Players|",
  "Jelly Roll|Need a Favor|",
  "Dua Lipa|Dance the Night|",
  "Luke Combs|Love You Anyway|",
  "Morgan Wallen|One Thing at a Time|",
  "Metro Boomin, Future and Chris Brown|Superhero (Heroes & Villains)|",
  "Yng Lvcas and Peso Pluma|La Bebé|",
  "Bailey Zimmerman|Religiously|",
  "Drake and 21 Savage|Spin Bout U|",
  "Fifty Fifty|Cupid|",
  "Drake|Search & Rescue|",
  "Nicki Minaj and Ice Spice with Aqua|Barbie World|",
  "Jordan Davis|Next Thing You Know|",
  "Raye featuring 070 Shake|Escapism|",
  "Grupo Frontera and Bad Bunny|Un x100to|",
  "Doja Cat|Paint the Town Red|",
  "Hardy featuring Lainey Wilson|Wait in the Truck|",
  "Morgan Wallen|Everything I Love|",
  "Post Malone|Chemical|",
  "Lainey Wilson|Heart Like a Truck|",
  "Luke Combs|Going, Going, Gone|",
  "Tyler Hubbard|Dancin' in the Country|",
  "David Kushner|Daylight|",
  "Rihanna|Lift Me Up|",
  "Ed Sheeran|Eyes Closed|",
  "Karol G and Shakira|TQG|",
  "Jason Aldean|Try That in a Small Town|",
  "Megan Moroney|Tennessee Orange|",
  "Ice Spice and Nicki Minaj|Princess Diana|",
  "GloRilla and Cardi B|Tomorrow 2|",
  "Bad Bunny|Where She Goes|",
  "Fuerza Regida and Grupo Frontera|Bebe Dame|",
  "Zach Bryan featuring Kacey Musgraves|I Remember Everything|",
  "Doechii featuring Kodak Black|What It Is (Block Boy)|",
  "SZA|Nobody Gets Me|",
  "Oliver Anthony Music|Rich Men North of Richmond|",
  "Noah Kahan and Post Malone|Dial Drunk|",
  "Billie Eilish|What Was I Made For?|",
  "Jung Kook featuring Latto|Seven|",
  "Wham!|Last Christmas|",
  "Parker McCollum|Handle on You|",
  "Peso Pluma|Por Las Noches|",
  "Old Dominion|Memory Lane|",
  "Kaliii|Area Codes|",
  "Kane Brown|Bury Me in Georgia|",
  "Peso Pluma and Natanael Cano|PRC|",
  "Jordan Davis|What My World Spins Around|",
  "Morgan Wallen|Ain't That Some|",
  "Corey Kent|Wild as Her|",
  "Young Nudy featuring 21 Savage|Peaches & Eggplants|",
  "Morgan Wallen|I Wrote the Book|",
  "Bizarrap and Shakira|Bzrp Music Sessions, Vol. 53|",
  "Travis Scott featuring Drake|Meltdown|",
  "Latto featuring Cardi B|Put It on da Floor Again|",
  "Lady Gaga|Bloody Mary|",
  "Lainey Wilson|Watermelon Moonshine|",
  "Rema|Calm Down|Rave & Roses",
  "Jung Kook|Seven|Golden",
  "NewJeans|Super Shy|Get Up",
  "NewJeans|ETA|Get Up",
  "Tate McRae|greedy|Think Later",
  "Djo|End of Beginning|DECIDE",
  "Fred again..|Marea (We've Lost Dancing)|Actual Life 3",
  "PinkPantheress|Boy's a liar Pt. 2|",
  "(G)I-DLE|Nxde|I Love",
  "BTS|Yet to Come|Proof",
  "Stray Kids|Maniac|Oddinary",
  "ITZY|Sneakers|Checkmate",
  "NCT Dream|Beatbox|Beatbox",
  "Tove Lo|2 Be Loved (Am I Ready)|Dirt Femme",
  "Lizzo|2 Be Loved (Am I Ready)|Special",
  "The Killers|Boy|Imploding the Mirage",
  "Fontaines D.C.|Jackie Down the Line|Skinty Fia",
  "Rauw Alejandro|Desesperados|Vice Versa",
  "Calvin Harris|New To You|Funk Wav Bounces Vol. 2",
  "Selena Gomez|My Mind & Me|",
  "Teddy Swims|Lose Control|I've Tried Everything but Therapy (Part 1)",
  "Shaboozey|A Bar Song (Tipsy)|Where I've Been, Isn't Where I'm Going",
];
