export default [
  "Benson Boone|Beautiful Things|",
  "Post Malone featuring Morgan Wallen|I Had Some Help|",
  "Jack Harlow|Lovin on Me|",
  "Sabrina Carpenter|Espresso|",
  "Tommy Richman|Million Dollar Baby|",
  "Hozier|Too Sweet|",
  "Noah Kahan|Stick Season|",
  "Future, Metro Boomin and Kendrick Lamar|Like That|",
  "Billie Eilish|Birds of a Feather|",
  "Sabrina Carpenter|Please Please Please|",
  "Doja Cat|Agora Hills|",
  "Chappell Roan|Good Luck, Babe!|",
  "\"Snooze\"|Saturn\"\nSZA\n\n\n20|",
  "Taylor Swift featuring Post Malone|Fortnight|",
  "Tyla|Water|",
  "Sabrina Carpenter|Feather|",
  "Ariana Grande|We Can't Be Friends (Wait for Your Love)|",
  "Dasha|Austin|",
  "Morgan Wallen featuring Ernest|Cowgirls|",
  "Zach Bryan|Pink Skies|",
  "Beyoncé|Texas Hold 'Em|",
  "Taylor Swift|Is It Over Now?|",
  "Marshmello and Kane Brown|Miles on It|",
  "Taylor Swift|I Can Do It with a Broken Heart|",
  "Jessie Murph and Jelly Roll|Wild Ones|",
  "Luke Combs|Ain't No Love in Oklahoma|",
  "¥$ (Kanye West and Ty Dolla Sign) featuring Rich the Kid and Playboi Carti|Carnival|",
  "Eminem|Houdini|",
  "GloRilla and Megan Thee Stallion|Wanna Be|",
  "Benson Boone|Slow It Down|",
  "21 Savage|Redrum|",
  "Dua Lipa|Houdini|",
  "GloRilla|Yeah Glo!|",
  "Drake featuring Sexyy Red and SZA|Rich Baby Daddy|",
  "Billie Eilish|Lunch|",
  "Flo Milli|Never Lose Me|",
  "Morgan Wallen|Lies Lies Lies|",
  "Future, Metro Boomin, Travis Scott, and Playboi Carti|Type Shit|",
  "FloyyMenor and Cris MJ|Gata Only|",
  "Chappell Roan|Hot to Go!|",
  "Sexyy Red|Get It Sexyy|",
  "Muni Long|Made for Me|",
  "Bryson Tiller|Whatever She Wants|",
  "Warren Zeiders|Pretty Little Poison|",
  "Drake featuring J. Cole|First Person Shooter|",
  "Lady Gaga and Bruno Mars|Die with a Smile|",
  "Artemas|I Like the Way You Kiss Me|",
  "Jelly Roll featuring Lainey Wilson|Save Me|",
  "Hardy|Truck Bed|",
  "Luke Combs|Where the Wild Things Are|",
  "Nicki Minaj featuring Lil Uzi Vert|Everybody|",
  "Xavi|La Diabla|",
  "Myles Smith|Stargazing|",
  "Jelly Roll|I Am Not Okay|",
  "Post Malone featuring Blake Shelton|Pour Me a Drink|",
  "Chris Stapleton|White Horse|",
  "Paul Russell|Lil Boo Thang|",
  "Usher, Summer Walker and 21 Savage|Good Good|",
  "4Batz and Drake|Act II: Date @ 8|",
  "Koe Wetzel featuring Jessie Murph|High Road|",
  "Bad Bunny|Monaco|",
  "Drake featuring Yeat|IDGAF|",
  "Parker McCollum|Burn It Down|",
  "Sabrina Carpenter|Taste|",
  "Bailey Zimmerman|Where It Ends|",
  "Nicki Minaj|FTCU|",
  "Billie Eilish|Wildflower|",
  "Nate Smith|World on Fire|",
  "Victoria Monét|On My Mama|",
  "Ariana Grande|Yes, And?|",
  "Tate McRae|Exes|",
  "Tucker Wetmore|Wind Up Missin' You|",
  "Nate Smith|Bulletproof|",
  "Travis Scott featuring Playboi Carti|Fe!n|",
  "Cody Johnson|The Painter|",
  "Taylor Swift|Down Bad|",
  "Taylor Swift|Fortnight|THE TORTURED POETS DEPARTMENT",
  "Sabrina Carpenter|Bed Chem|Short n' Sweet",
  "Sabrina Carpenter|Juno|Short n' Sweet",
  "Billie Eilish|Chihiro|Hit Me Hard and Soft",
  "Dua Lipa|Training Season|Radical Optimism",
  "Dua Lipa|Illusion|Radical Optimism",
  "Beyoncé|JOLENE|Cowboy Carter",
  "Beyoncé|Bodyguard|Cowboy Carter",
  "SZA|Saturn|",
  "Tyla|Truth or Dare|TYLA",
  "Teddy Swims|The Door|I've Tried Everything but Therapy (Part 2)",
  "Stray Kids|Chk Chk Boom|ATE",
  "NewJeans|How Sweet|How Sweet",
  "ILLIT|Magnetic|SUPER REAL ME",
  "LE SSERAFIM|Easy|EASY",
  "ROSÉ & Bruno Mars|APT.|rosie",
  "Lady Gaga|Disease|",
  "Coldplay|feelslikeimfallinginlove|Moon Music",
  "Imagine Dragons|Eyes Closed|LOOM",
  "Twenty One Pilots|Overcompensate|Clancy",
  "Morgan Wallen|Love Somebody|Dangerous: The Double Album",
  "Jelly Roll|Liar|Beautifully Broken",
  "Kali Uchis|MUÑECA|ORQUÍDEAS",
  "Karol G|Si Antes Te Hubiera Conocido|Mañana Será Bonito (Bichota Season)",
];
