export default [
  "Kendrick Lamar and SZA|Luther|",
  "Alex Warren|Ordinary|",
  "Rosé and Bruno Mars|APT.|",
  "Chappell Roan|Pink Pony Club|",
  "Morgan Wallen|I'm the Problem|",
  "Gracie Abrams|That's So True|",
  "Kendrick Lamar featuring Lefty Gunplay|TV Off|",
  "The Weeknd and Playboi Carti|Timeless|",
  "Morgan Wallen|Just in Case|",
  "SZA and Kendrick Lamar|30 for 30|",
  "Leon Thomas|Mutt|",
  "Shaboozey|Good News|",
  "Drake|Nokia|",
  "Huntrix: Ejae, Audrey Nuna and Rei Ami|Golden|",
  "Morgan Wallen featuring Tate McRae|What I Want|",
  "Lola Young|Messy|",
  "Ravyn Lenae|Love Me Not|",
  "The Marías|No One Noticed|",
  "BigXthaPlug featuring Bailey Zimmerman|All the Way|",
  "Riley Green|Worst Way|",
  "Gigi Perez|Sailor Song|",
  "Benson Boone|Sorry I'm Here for Someone Else|",
  "Sabrina Carpenter|Manchild|",
  "Morgan Wallen|I Got Better|",
  "Tyler, the Creator featuring GloRilla, Sexyy Red and Lil Wayne|Sticky|",
  "Sombr|Undressed|",
  "Zach Top|I Never Lie|",
  "Sombr|Back to Friends|",
  "Tate McRae|Sports Car|",
  "Benson Boone|Mystical Magical|",
  "GloRilla and Sexyy Red|Whatchu Kno About Me|",
  "Sam Barber featuring Avery Anna|Indigo|",
  "Bad Bunny|DTMF|",
  "Jessie Murph|Blue Strips|",
  "Kendrick Lamar featuring AzChike|Peekaboo|",
  "Saja Boys: Andrew Choi, Neckwav, Danny Chung, Kevin Woo and Samuil Lee|Your Idol|",
  "Lady Gaga|Abracadabra|",
  "Jimin|Who|",
  "Mariah the Scientist|Burning Blue|",
  "Justin Bieber|Daisies|",
  "Saja Boys: Andrew Choi, Neckwav, Danny Chung, Kevin Woo and Samuil Lee|Soda Pop|",
  "Tyler, the Creator featuring Lola Young|Like Him|",
  "Chris Brown|Residuals|",
  "Morgan Wallen|Smile|",
  "Megan Moroney|Am I Okay?|",
  "Huntrix: Ejae, Audrey Nuna and Rei Ami|How It's Done|",
  "Russell Dickerson|Happen to Me|",
  "Bad Bunny|Baile Inolvidable|",
  "Ella Langley|Weren't for the Wind|",
  "Morgan Wallen featuring Post Malone|I Ain't Comin' Back|",
  "The Weeknd|Cry for Me|",
  "Teddy Swims|Bad Dreams|",
  "SZA|BMF|",
  "Bad Bunny|Eoo|",
  "Cody Johnson and Carrie Underwood|I'm Gonna Love You|",
  "Bailey Zimmerman and Luke Combs|Backup Plan|",
  "Tate McRae|Revolving Door|",
  "Huntrix: Ejae, Audrey Nuna and Rei Ami|What It Sounds Like|",
  "Brandon Lake and Jelly Roll|Hard Fought Hallelujah|",
  "PartyNextDoor and Drake|Somebody Loves Me|",
  "Óscar Maydon and Fuerza Regida|Tu Boda|",
  "Thomas Rhett|After All the Bars Are Closed|",
  "Bad Bunny|Nuevayol|",
  "Morgan Wallen|20 Cigarettes|",
  "Playboi Carti and the Weeknd|Rather Lie|",
  "Ejae and Andrew Choi|Free|",
  "Huntrix: Ejae, Audrey Nuna and Rei Ami|Takedown|",
  "Summer Walker|Heart of a Woman|",
  "Hudson Westbrook|House Again|",
  "Lil Tecca|Dark Thoughts|",
  "Don Toliver|No Pole|",
  "Kehlani|Folded|",
  "Morgan Wallen|Superman|",
  "Netón Vega|Loco|",
  "Sabrina Carpenter|Busy Woman|Man's Best Friend",
  "Lady Gaga|Die with a Smile|Harlequin",
  "Lady Gaga|Garden of Eden|Mayhem",
  "Alex Warren|Burning Down|You'll Be Alright, Kid",
  "Jelly Roll|Losers|Beautifully Broken",
  "Addison Rae|Aquamarine|Addison",
  "Addison Rae|Diet Pepsi|Addison",
  "Stray Kids|CEREMONY|合 (HOP)",
  "LE SSERAFIM|HOT|HOT",
  "The Weeknd|Timeless|Hurry Up Tomorrow",
  "Katy Perry|LIFETIMES|143",
  "Ed Sheeran|Azizam|Play",
  "Ed Sheeran|Sapphire|Play",
  "Conan Gray|Lonely Dancers|Wishbone",
  "Conan Gray|This Song|Wishbone",
  "Olivia Dean|A Couple Minutes|Messy",
  "Olivia Dean|So Easy (To Fall In Love)|Messy",
  "Fontaines D.C.|In The Modern World|Romance",
  "PinkPantheress|Nice to meet you|Heaven knows",
  "ROLE MODEL|Sally When The Wine Runs Out|Kansas Anymore",
  "David Guetta & OneRepublic|I Don't Wanna Wait|",
  "Kygo & Ava Max|Whatever|Kygo",
  "Calvin Harris & Ellie Goulding|Free|Funk Wav Bounces Vol. 2",
  "P!nk|TRUSTFALL|TRUSTFALL",
  "Vampire Weekend|Capricorn|Only God Was Above Us",
  "Bleachers|Tiny Moves|Bleachers",
];
