/** 150 curated global classics (1960–1999), year|artist|title|album */
export default [
  '1968|The Beatles|Hey Jude|Hey Jude',
  '1970|The Beatles|Let It Be|Let It Be',
  '1965|The Beatles|Yesterday|Help!',
  '1975|Queen|Bohemian Rhapsody|A Night at the Opera',
  '1977|Queen|We Will Rock You|News of the World',
  '1977|Queen|We Are the Champions|News of the World',
  "1978|Queen|Don't Stop Me Now|Jazz",
  '1982|Michael Jackson|Billie Jean|Thriller',
  '1982|Michael Jackson|Beat It|Thriller',
  '1982|Michael Jackson|Thriller|Thriller',
  '1987|Michael Jackson|Smooth Criminal|Bad',
  '1984|Prince|Purple Rain|Purple Rain',
  '1984|Prince|When Doves Cry|Purple Rain',
  '1986|Prince|Kiss|Parade',
  '1984|Madonna|Like a Virgin|Like a Virgin',
  '1989|Madonna|Like a Prayer|Like a Prayer',
  "1990|Madonna|Vogue|I'm Breathless",
  '1998|Madonna|Ray of Light|Ray of Light',
  '1992|Whitney Houston|I Will Always Love You|The Bodyguard',
  '1987|Whitney Houston|I Wanna Dance with Somebody (Who Loves Me)|Whitney',
  '1985|Whitney Houston|Greatest Love of All|Whitney Houston',
  '1985|Whitney Houston|How Will I Know|Whitney Houston',
  '1987|Whitney Houston|So Emotional|Whitney',
  '1998|Monica|The Boy Is Mine|The Boy Is Mine',
  '1970|Elton John|Your Song|Elton John',
  '1997|Elton John|Candle in the Wind 1997|The Big Picture',
  '1971|Elton John|Tiny Dancer|Madman Across the Water',
  "1972|Elton John|Rocket Man (I Think It's Going to Be a Long, Long Time)|Honky Château",
  '1976|ABBA|Dancing Queen|Arrival',
  '1975|ABBA|Mamma Mia|ABBA',
  "1977|Bee Gees|Stayin' Alive|Saturday Night Fever",
  '1977|Bee Gees|Night Fever|Saturday Night Fever',
  '1976|Eagles|Hotel California|Hotel California',
  '1972|Eagles|Take It Easy|Eagles',
  '1979|Supertramp|The Logical Song|Breakfast in America',
  '1977|Fleetwood Mac|Go Your Own Way|Rumours',
  '1977|Fleetwood Mac|The Chain|Rumours',
  '1991|Nirvana|Smells Like Teen Spirit|Nevermind',
  '1991|Nirvana|Come as You Are|Nevermind',
  '1991|Nirvana|Lithium|Nevermind',
  "1987|Guns N' Roses|Sweet Child o' Mine|Appetite for Destruction",
  "1991|Guns N' Roses|November Rain|Use Your Illusion I",
  '1980|AC/DC|Back in Black|Back in Black',
  '1990|AC/DC|Thunderstruck|The Razors Edge',
  '1971|Led Zeppelin|Stairway to Heaven|Led Zeppelin IV',
  '1969|Led Zeppelin|Whole Lotta Love|Led Zeppelin II',
  '1979|Pink Floyd|Another Brick in the Wall, Pt. 2|The Wall',
  '1975|Pink Floyd|Wish You Were Here|Wish You Were Here',
  '1979|Pink Floyd|Comfortably Numb|The Wall',
  '1987|U2|With or Without You|The Joshua Tree',
  '1991|U2|One|Achtung Baby',
  '1987|U2|Where the Streets Have No Name|The Joshua Tree',
  "1987|U2|I Still Haven't Found What I'm Looking For|The Joshua Tree",
  "1965|The Rolling Stones|(I Can't Get No) Satisfaction|Out of Our Heads",
  '1966|The Rolling Stones|Paint It Black|Aftermath',
  '1973|The Rolling Stones|Angie|Goats Head Soup',
  '1977|David Bowie|Heroes|"Heroes"',
  '1969|David Bowie|Space Oddity|David Bowie',
  "1983|David Bowie|Let's Dance|Let's Dance",
  '1975|Bruce Springsteen|Born to Run|Born to Run',
  '1984|Bruce Springsteen|Dancing in the Dark|Born in the U.S.A.',
  '1984|Bruce Springsteen|Born in the U.S.A.|Born in the U.S.A.',
  '1965|Bob Dylan|Like a Rolling Stone|Highway 61 Revisited',
  "1963|Bob Dylan|Blowin' in the Wind|The Freewheelin' Bob Dylan",
  '1974|Bob Marley & The Wailers|No Woman, No Cry|Natty Dread',
  '1980|Bob Marley & The Wailers|Redemption Song|Uprising',
  '1964|Simon & Garfunkel|The Sound of Silence|Sounds of Silence',
  '1970|Simon & Garfunkel|Bridge over Troubled Water|Bridge over Troubled Water',
  '1966|The Beach Boys|Good Vibrations|Smiley Smile',
  '1966|The Beach Boys|God Only Knows|Pet Sounds',
  '1972|Stevie Wonder|Superstition|Talking Book',
  "1976|Stevie Wonder|Isn't She Lovely|Songs in the Key of Life",
  '1984|Stevie Wonder|I Just Called to Say I Love You|The Woman in Red',
  "1971|Marvin Gaye|What's Going On|What's Going On",
  '1982|Marvin Gaye|Sexual Healing|Midnight Love',
  '1967|Aretha Franklin|Respect|I Never Loved a Man the Way I Love You',
  '1967|Aretha Franklin|(You Make Me Feel Like) A Natural Woman|Lady Soul',
  "1968|Otis Redding|(Sittin' On) The Dock of the Bay|The Dock of the Bay",
  "1964|Sam Cooke|A Change Is Gonna Come|Ain't That Good News",
  '1964|The Temptations|My Girl|The Temptations Sing Smokey',
  '1965|Smokey Robinson & The Miracles|The Tracks of My Tears|Going to a Go-Go',
  "1970|Diana Ross|Ain't No Mountain High Enough|Diana Ross",
  '1964|The Supremes|Baby Love|Where Did Our Love Go',
  '1978|Earth, Wind & Fire|September|The Best of Earth, Wind & Fire, Vol. 1',
  '1979|Earth, Wind & Fire|Boogie Wonderland|I Am',
  '1980|Kool & The Gang|Celebration|Celebrate!',
  "1978|Chic|Le Freak|C'est Chic",
  '1979|Donna Summer|Hot Stuff|Bad Girls',
  '1977|Donna Summer|I Feel Love|I Remember Yesterday',
  '1977|Bee Gees|How Deep Is Your Love|Saturday Night Fever',
  '1973|Billy Joel|Piano Man|Piano Man',
  '1983|Billy Joel|Uptown Girl|An Innocent Man',
  "1989|Billy Joel|We Didn't Start the Fire|Storm Front",
  '1981|Phil Collins|In the Air Tonight|Face Value',
  '1984|Phil Collins|Against All Odds (Take a Look at Me Now)|Against All Odds',
  '1986|Genesis|Invisible Touch|Invisible Touch',
  '1985|Tears for Fears|Everybody Wants to Rule the World|Songs from the Big Chair',
  '1984|Tears for Fears|Shout|Songs from the Big Chair',
  '1983|Eurythmics|Sweet Dreams (Are Made of This)|Sweet Dreams (Are Made of This)',
  '1985|a-ha|Take On Me|Hunting High and Low',
  '1982|Duran Duran|Hungry Like the Wolf|Rio',
  '1982|Duran Duran|Rio|Rio',
  '1989|Depeche Mode|Personal Jesus|Violator',
  '1990|Depeche Mode|Enjoy the Silence|Violator',
  '1983|New Order|Blue Monday|Substance',
  '1984|Pet Shop Boys|West End Girls|Please',
  "1983|Cyndi Lauper|Girls Just Want to Have Fun|She's So Unusual",
  '1984|Wham!|Wake Me Up Before You Go-Go|Make It Big',
  '1983|Culture Club|Karma Chameleon|Colour by Numbers',
  '1987|George Michael|Faith|Faith',
  '1984|George Michael|Careless Whisper|Make It Big',
  '1982|Dexys Midnight Runners|Come On Eileen|Too-Rye-Ay',
  '1981|Soft Cell|Tainted Love|Non-Stop Erotic Cabaret',
  '1983|The Police|Every Breath You Take|Synchronicity',
  "1978|The Police|Roxanne|Outlandos d'Amour",
  '1993|Sting|Fields of Gold|Ten Summoner\'s Tales',
  '1985|Dire Straits|Money for Nothing|Brothers in Arms',
  '1978|Dire Straits|Sultans of Swing|Dire Straits',
  '1991|Metallica|Nothing Else Matters|Metallica',
  '1991|Metallica|Enter Sandman|Metallica',
  '1991|R.E.M.|Losing My Religion|Out of Time',
  '1992|R.E.M.|Everybody Hurts|Automatic for the People',
  '1992|Radiohead|Creep|Pablo Honey',
  "1995|Oasis|Wonderwall|(What's the Story) Morning Glory?",
  "1995|Oasis|Champagne Supernova|(What's the Story) Morning Glory?",
  "1995|Oasis|Don't Look Back in Anger|(What's the Story) Morning Glory?",
  '1997|Blur|Song 2|Blur',
  '1997|The Verve|Bitter Sweet Symphony|Urban Hymns',
  '1996|Spice Girls|Wannabe|Spice',
  '1997|Spice Girls|Spice Up Your Life|Spiceworld',
  "1999|Backstreet Boys|I Want It That Way|Millennium",
  "1997|Backstreet Boys|Everybody (Backstreet's Back)|Backstreet's Back",
  '1998|Britney Spears|...Baby One More Time|...Baby One More Time',
  '1999|Britney Spears|(You Drive Me) Crazy|...Baby One More Time',
  '1999|Christina Aguilera|Genie in a Bottle|Christina Aguilera',
  "1999|Ricky Martin|Livin' la Vida Loca|Ricky Martin",
  '1995|Ricky Martin|María|A Medio Vivir',
  '1999|Jennifer Lopez|If You Had My Love|On the 6',
  '1999|TLC|No Scrubs|FanMail',
  '1994|TLC|Waterfalls|CrazySexyCool',
  "1999|Destiny's Child|Bug a Boo|The Writing's on the Wall",
  "1993|Janet Jackson|That's the Way Love Goes|Janet.",
  "1989|Janet Jackson|Rhythm Nation|Janet Jackson's Rhythm Nation 1814",
  '1990|Mariah Carey|Vision of Love|Mariah Carey',
  '1995|Mariah Carey|Fantasy|Daydream',
  '1993|Mariah Carey|Hero|Music Box',
  '1995|Mariah Carey|Always Be My Baby|Daydream',
  '1995|Mariah Carey|One Sweet Day|Daydream',
  "1997|Celine Dion|My Heart Will Go On|Let's Talk About Love",
  '1993|Celine Dion|The Power of Love|The Colour of My Love',
  '1997|Shania Twain|Man! I Feel Like a Woman!|Come On Over',
  "1997|Shania Twain|You're Still the One|Come On Over",
  '1990|Garth Brooks|Friends in Low Places|No Fences',
  '1991|Garth Brooks|The Dance|Garth Brooks',
  '1963|Johnny Cash|Ring of Fire|Ring of Fire: The Best of Johnny Cash',
  '2002|Johnny Cash|Hurt|American IV: The Man Comes Around',
  '1974|Dolly Parton|Jolene|Jolene',
  '1980|Dolly Parton|9 to 5|9 to 5 and Odd Jobs',
  '1969|The Beatles|Here Comes the Sun|Abbey Road',
  '1969|The Beatles|Come Together|Abbey Road',
  '1968|The Beatles|Blackbird|The Beatles',
  '1970|Led Zeppelin|Immigrant Song|Led Zeppelin III',
  "1971|The Who|Baba O'Riley|Who's Next",
  '1965|The Who|My Generation|My Generation',
  '1968|Jimi Hendrix|All Along the Watchtower|Electric Ladyland',
  '1967|Jimi Hendrix|Purple Haze|Are You Experienced',
  '1967|The Doors|Light My Fire|The Doors',
  '1971|The Doors|Riders on the Storm|L.A. Woman',
  '1967|Cream|Sunshine of Your Love|Disraeli Gears',
  '1964|The Kinks|You Really Got Me|Kinks-Size',
  '1964|The Animals|House of the Rising Sun|The Animals',
  '1965|The Byrds|Mr. Tambourine Man|Mr. Tambourine Man',
  '1971|Creedence Clearwater Revival|Have You Ever Seen the Rain|Pendulum',
  '1969|Creedence Clearwater Revival|Bad Moon Rising|Green River',
  '1972|Neil Young|Heart of Gold|Harvest',
  "1989|Neil Young|Rockin' in the Free World|Freedom",
  "1971|Carole King|It's Too Late|Tapestry",
  '1971|Carole King|I Feel the Earth Move|Tapestry',
  '1970|James Taylor|Fire and Rain|Sweet Baby James',
  '1970|Joni Mitchell|Big Yellow Taxi|Ladies of the Canyon',
  '1970|Cat Stevens|Wild World|Tea for the Tillerman',
  '1970|Cat Stevens|Father and Son|Tea for the Tillerman',
];
