/** Backfill acclaimed global (non hip-hop/rap) tracks by release year when Billboard pool is short. */
export const SUPPLEMENT = {
  2000: [
    { artist: 'Bon Jovi', title: "It's My Life", album: 'Crush' },
    { artist: 'Radiohead', title: 'Everything in Its Right Place', album: 'Kid A' },
    { artist: 'Radiohead', title: 'Optimistic', album: 'Kid A' },
    { artist: 'Coldplay', title: 'Yellow', album: 'Parachutes' },
    { artist: 'Green Day', title: 'Minority', album: 'Warning' },
    { artist: 'Blink-182', title: "Adam's Song", album: 'Enema of the State' },
    { artist: 'Moby', title: 'Natural Blues', album: 'Play' },
    { artist: 'All Saints', title: 'Pure Shores', album: 'Saints & Sinners' },
    { artist: 'Modjo', title: 'Lady (Hear Me Tonight)', album: 'Modjo' },
    { artist: 'Sonique', title: 'Synchro Love', album: 'Club Zip' },
    { artist: 'Eiffel 65', title: 'Move Your Body', album: 'Europop' },
    { artist: 'Nine Days', title: 'Absolutely (Story of a Girl)', album: 'The Madding Crowd' },
    { artist: 'Wheatus', title: 'Teenage Dirtbag', album: 'Wheatus' },
    { artist: 'D\'Angelo', title: 'Untitled (How Does It Feel)', album: 'Voodoo' },
    { artist: 'Erykah Badu', title: 'Bag Lady', album: "Mama's Gun" },
    { artist: 'Erykah Badu', title: "Didn't Cha Know?", album: "Mama's Gun" },
  ],
  2001: [
    { artist: 'U2', title: 'Beautiful Day', album: 'All That You Can\'t Leave Behind' },
    { artist: 'Radiohead', title: 'Pyramid Song', album: 'Amnesiac' },
    { artist: 'Radiohead', title: 'Knives Out', album: 'Amnesiac' },
    { artist: 'Coldplay', title: 'In My Place', album: 'Parachutes' },
    { artist: 'Coldplay', title: 'Don\'t Panic', album: 'Parachutes' },
    { artist: 'The Strokes', title: 'Last Nite', album: 'Is This It' },
    { artist: 'The Strokes', title: 'Someday', album: 'Is This It' },
    { artist: 'System of a Down', title: 'Chop Suey!', album: 'Toxicity' },
    { artist: 'System of a Down', title: 'Aerials', album: 'Toxicity' },
    { artist: 'Linkin Park', title: 'In the End', album: 'Hybrid Theory' },
    { artist: 'Linkin Park', title: 'Crawling', album: 'Hybrid Theory' },
    { artist: 'Linkin Park', title: 'One Step Closer', album: 'Hybrid Theory' },
    { artist: 'Gorillaz', title: 'Clint Eastwood', album: 'Gorillaz' },
    { artist: 'Gorillaz', title: '19-2000', album: 'Gorillaz' },
    { artist: 'Daft Punk', title: 'One More Time', album: 'Discovery' },
    { artist: 'Daft Punk', title: 'Digital Love', album: 'Discovery' },
    { artist: 'Daft Punk', title: 'Harder, Better, Faster, Stronger', album: 'Discovery' },
    { artist: 'Michael Jackson', title: 'You Rock My World', album: 'Invincible' },
    { artist: 'Madonna', title: 'Don\'t Tell Me', album: 'Music' },
    { artist: 'Madonna', title: 'Music', album: 'Music' },
    { artist: 'Britney Spears', title: 'I\'m a Slave 4 U', album: 'Britney' },
    { artist: 'Britney Spears', title: 'Overprotected', album: 'Britney' },
    { artist: 'P!nk', title: 'Get the Party Started', album: 'M!ssundaztood' },
    { artist: 'P!nk', title: 'Just Like a Pill', album: 'M!ssundaztood' },
    { artist: 'Enrique Iglesias', title: 'Escape', album: 'Escape' },
    { artist: 'Michelle Branch', title: 'Everywhere', album: 'The Spirit Room' },
    { artist: 'Tool', title: 'Schism', album: 'Lateralus' },
    { artist: 'Sade', title: 'By Your Side', album: 'Lovers Rock' },
    { artist: 'Travis', title: 'Sing', album: 'The Invisible Band' },
    { artist: 'Nickelback', title: 'How You Remind Me', album: 'Silver Side Up' },
  ],
  2002: [
    { artist: 'Avril Lavigne', title: 'Complicated', album: 'Let Go' },
    { artist: 'Avril Lavigne', title: 'Sk8er Boi', album: 'Let Go' },
    { artist: 'Norah Jones', title: "Don't Know Why", album: 'Come Away with Me' },
    { artist: 'Coldplay', title: 'Clocks', album: 'A Rush of Blood to the Head' },
    { artist: 'Coldplay', title: 'The Scientist', album: 'A Rush of Blood to the Head' },
    { artist: 'Shakira', title: 'Whenever, Wherever', album: 'Laundry Service' },
    { artist: 'Christina Aguilera', title: 'Beautiful', album: 'Stripped' },
    { artist: 'Red Hot Chili Peppers', title: 'By the Way', album: 'By the Way' },
    { artist: 'Ashanti', title: 'Foolish', album: 'Ashanti' },
    { artist: 'No Doubt', title: 'Hella Good', album: 'Rock Steady' },
    { artist: 'Pink', title: 'Get the Party Started', album: 'M!ssundaztood' },
    { artist: 'Pink', title: 'Just Like a Pill', album: 'M!ssundaztood' },
    { artist: 'Jennifer Lopez', title: 'Jenny from the Block', album: 'This Is Me... Then' },
    { artist: 'Sum 41', title: 'Still Waiting', album: 'Does This Look Infected?' },
    { artist: 'Nickelback', title: 'How You Remind Me', album: 'Silver Side Up' },
    { artist: 'Default', title: 'Wasting My Time', album: 'The Fallout' },
    { artist: 'Creed', title: 'One Last Breath', album: 'Weathered' },
    { artist: 'No Doubt', title: 'Underneath It All', album: 'Rock Steady' },
    { artist: 'Michelle Branch', title: 'All You Wanted', album: 'The Spirit Room' },
    { artist: 'Evanescence', title: 'My Immortal', album: 'Fallen' },
    { artist: 'Vanessa Carlton', title: 'A Thousand Miles', album: 'Be Not Nobody' },
    { artist: 'Jimmy Eat World', title: 'The Middle', album: 'Bleed American' },
    { artist: 'Audioslave', title: 'Like a Stone', album: 'Audioslave' },
    { artist: 'P.O.D.', title: 'Youth of the Nation', album: 'Satellite' },
    { artist: 'John Mayer', title: 'No Such Thing', album: 'Room for Squares' },
    { artist: 'Alicia Keys', title: "A Woman's Worth", album: 'Songs in A Minor' },
    { artist: 'Nelly Furtado', title: 'Turn Off the Light', album: 'Whoa, Nelly!' },
    { artist: 'N Sync', title: 'Girlfriend', album: 'Celebrity' },
    { artist: 'Bon Jovi', title: 'Everyday', album: 'Bounce' },
    { artist: 'Disturbed', title: 'Prayer', album: 'Believe' },
    { artist: 'Hoobastank', title: 'Running Away', album: 'The Reason' },
  ],
  2003: [
    { artist: 'Beyoncé', title: 'Crazy in Love', album: 'Dangerously in Love' },
    { artist: 'Beyoncé', title: 'Baby Boy', album: 'Dangerously in Love' },
    { artist: 'The White Stripes', title: 'Seven Nation Army', album: 'Elephant' },
    { artist: 'Justin Timberlake', title: 'Cry Me a River', album: 'Justified' },
    { artist: 'Linkin Park', title: 'Numb', album: 'Meteora' },
    { artist: 'Evanescence', title: 'Bring Me to Life', album: 'Fallen' },
    { artist: 'Christina Aguilera', title: 'Beautiful', album: 'Stripped' },
    { artist: 'Christina Aguilera', title: 'Fighter', album: 'Stripped' },
    { artist: 'Sean Paul', title: 'Get Busy', album: 'Dutty Rock' },
    { artist: 'Sean Paul', title: 'Like Glue', album: 'Dutty Rock' },
    { artist: 'Jet', title: 'Are You Gonna Be My Girl', album: 'Get Born' },
    { artist: 'Travis', title: 'Flowers in the Window', album: 'The Invisible Band' },
    { artist: 'Radiohead', title: 'There There', album: 'Hail to the Thief' },
    { artist: 'Matchbox Twenty', title: 'Unwell', album: 'More Than You Think You Are' },
    { artist: 'John Mayer', title: 'Your Body Is a Wonderland', album: 'Room for Squares' },
    { artist: 'Kelis', title: 'Milkshake', album: 'Tasty' },
    { artist: 'Kelly Clarkson', title: 'Miss Independent', album: 'Thankful' },
    { artist: 'Daniel Bedingfield', title: "If You're Not the One", album: 'Gotta Get Thru This' },
    { artist: 'Michelle Branch', title: 'Breathe', album: 'Hotel Paper' },
  ],
  2004: [
    { artist: 'Usher', title: 'Yeah!', album: 'Confessions' },
    { artist: 'Usher', title: 'Burn', album: 'Confessions' },
    { artist: 'Usher', title: 'Confessions Part II', album: 'Confessions' },
    { artist: 'Maroon 5', title: 'This Love', album: 'Songs About Jane' },
    { artist: 'Maroon 5', title: 'She Will Be Loved', album: 'Songs About Jane' },
    { artist: 'Green Day', title: 'American Idiot', album: 'American Idiot' },
    { artist: 'Green Day', title: 'Boulevard of Broken Dreams', album: 'American Idiot' },
    { artist: 'Green Day', title: 'Wake Me Up When September Ends', album: 'American Idiot' },
    { artist: 'Keane', title: 'Somewhere Only We Know', album: 'Hopes and Fears' },
    { artist: 'Keane', title: "Everybody's Changing", album: 'Hopes and Fears' },
    { artist: 'Franz Ferdinand', title: 'Take Me Out', album: 'Franz Ferdinand' },
    { artist: 'Alicia Keys', title: "If I Ain't Got You", album: 'The Diary of Alicia Keys' },
    { artist: 'Alicia Keys', title: "You Don't Know My Name", album: 'The Diary of Alicia Keys' },
    { artist: 'JoJo', title: 'Leave (Get Out)', album: 'JoJo' },
    { artist: 'Prince', title: 'Musicology', album: 'Musicology' },
    { artist: 'Hoobastank', title: 'The Reason', album: 'The Reason' },
    { artist: "Destiny's Child", title: 'Lose My Breath', album: 'Destiny Fulfilled' },
    { artist: 'Gwen Stefani', title: 'Rich Girl', album: 'Love. Angel. Music. Baby.' },
    { artist: 'Beyoncé', title: 'Naughty Girl', album: 'Dangerously in Love' },
    { artist: 'Jet', title: 'Cold Hard Bitch', album: 'Get Born' },
    { artist: 'Nickelback', title: 'Someday', album: 'The Long Road' },
    { artist: 'Evanescence', title: 'My Immortal', album: 'Fallen' },
    { artist: 'Britney Spears', title: 'Toxic', album: 'In the Zone' },
    { artist: 'Britney Spears', title: 'Everytime', album: 'In the Zone' },
    { artist: 'Usher', title: 'My Boo', album: 'Confessions' },
    { artist: 'Alicia Keys', title: 'Karma', album: 'The Diary of Alicia Keys' },
    { artist: 'Mario', title: 'Let Me Love You', album: 'Turning Point' },
    { artist: 'U2', title: 'Vertigo', album: 'How to Dismantle an Atomic Bomb' },
    { artist: 'Linkin Park', title: 'Breaking the Habit', album: 'Meteora' },
    { artist: 'Ciara', title: 'Goodies', album: 'Goodies' },
    { artist: 'Los Lonely Boys', title: 'Heaven', album: 'Los Lonely Boys' },
    { artist: 'The Killers', title: 'Somebody Told Me', album: 'Hot Fuss' },
    { artist: 'Beastie Boys', title: 'Ch-Check It Out', album: 'To the 5 Boroughs' },
  ],
  2005: [
    { artist: 'Gorillaz', title: 'Feel Good Inc.', album: 'Demon Days' },
    { artist: 'Coldplay', title: 'Speed of Sound', album: 'X&Y' },
    { artist: 'James Blunt', title: "You're Beautiful", album: 'Back to Bedlam' },
    { artist: 'The Killers', title: 'Mr. Brightside', album: 'Hot Fuss' },
    { artist: 'Gwen Stefani', title: 'Hollaback Girl', album: 'Love. Angel. Music. Baby.' },
  ],
  2006: [
    { artist: 'Gnarls Barkley', title: 'Crazy', album: 'St. Elsewhere' },
    { artist: 'Nelly Furtado', title: 'Promiscuous', album: 'Loose' },
    { artist: 'Red Hot Chili Peppers', title: 'Dani California', album: 'Stadium Arcadium' },
    { artist: 'Snow Patrol', title: 'Chasing Cars', album: 'Eyes Open' },
    { artist: 'Arctic Monkeys', title: 'I Bet You Look Good on the Dancefloor', album: '' },
  ],
  2007: [
    { artist: 'Amy Winehouse', title: 'Rehab', album: 'Back to Black' },
    { artist: 'Amy Winehouse', title: "You Know I'm No Good", album: 'Back to Black' },
    { artist: 'Mika', title: 'Grace Kelly', album: 'Life in Cartoon Motion' },
    { artist: 'Foo Fighters', title: 'The Pretender', album: 'Echoes, Silence, Patience & Grace' },
    { artist: 'Kaiser Chiefs', title: 'Ruby', album: 'Yours Truly, Angry Mob' },
    { artist: 'Arcade Fire', title: 'Keep the Car Running', album: 'Neon Bible' },
    { artist: 'Fergie', title: "Big Girls Don't Cry", album: 'The Dutchess' },
    { artist: 'Plain White T\'s', title: 'Hey There Delilah', album: 'Every Second Counts' },
  ],
  2008: [
    { artist: 'Katy Perry', title: 'I Kissed a Girl', album: 'One of the Boys' },
    { artist: 'Katy Perry', title: 'Hot n Cold', album: 'One of the Boys' },
    { artist: 'Coldplay', title: 'Viva la Vida', album: 'Viva la Vida or Death and All His Friends' },
    { artist: 'Coldplay', title: 'Violet Hill', album: 'Viva la Vida or Death and All His Friends' },
    { artist: 'Kings of Leon', title: 'Sex on Fire', album: 'Only by the Night' },
    { artist: 'Kings of Leon', title: 'Use Somebody', album: 'Only by the Night' },
    { artist: 'Lady Gaga', title: 'Just Dance', album: 'The Fame' },
    { artist: 'Lady Gaga', title: 'Poker Face', album: 'The Fame' },
    { artist: 'Taylor Swift', title: 'Love Story', album: 'Fearless' },
    { artist: 'Taylor Swift', title: 'You Belong with Me', album: 'Fearless' },
    { artist: 'Britney Spears', title: 'Womanizer', album: 'Circus' },
    { artist: 'Britney Spears', title: 'Circus', album: 'Circus' },
    { artist: 'Rihanna', title: 'Disturbia', album: 'Good Girl Gone Bad' },
    { artist: 'Rihanna', title: 'Take a Bow', album: 'Good Girl Gone Bad' },
    { artist: 'Pink', title: 'So What', album: 'Funhouse' },
    { artist: 'Pink', title: 'Sober', album: 'Funhouse' },
    { artist: 'Leona Lewis', title: 'Bleeding Love', album: 'Spirit' },
    { artist: 'Jason Mraz', title: "I'm Yours", album: 'We Sing. We Dance. We Steal Things.' },
    { artist: 'OneRepublic', title: 'Apologize', album: 'Dreaming Out Loud' },
    { artist: 'Estelle', title: 'American Boy', album: 'Shine' },
    { artist: 'Sara Bareilles', title: 'Love Song', album: 'Little Voice' },
    { artist: 'Secondhand Serenade', title: 'Fall for You', album: 'A Twist in My Story' },
    { artist: 'Beyoncé', title: 'Single Ladies (Put a Ring on It)', album: 'I Am... Sasha Fierce' },
    { artist: 'Beyoncé', title: 'If I Were a Boy', album: 'I Am... Sasha Fierce' },
    { artist: 'Colbie Caillat', title: 'Bubbly', album: 'Coco' },
    { artist: 'Duffy', title: 'Mercy', album: 'Rockferry' },
    { artist: 'Ne-Yo', title: 'Closer', album: 'Year of the Gentleman' },
    { artist: 'Natasha Bedingfield', title: 'Pocketful of Sunshine', album: 'Strip Me' },
    { artist: 'Kelly Clarkson', title: 'My Life Would Suck Without You', album: 'All I Ever Wanted' },
  ],
  2009: [
    { artist: 'Lady Gaga', title: 'Poker Face', album: 'The Fame' },
    { artist: 'Lady Gaga', title: 'Bad Romance', album: 'The Fame Monster' },
    { artist: 'Lady Gaga', title: 'LoveGame', album: 'The Fame' },
    { artist: 'Lady Gaga', title: 'Paparazzi', album: 'The Fame' },
    { artist: 'Black Eyed Peas', title: 'I Gotta Feeling', album: 'The E.N.D.' },
    { artist: 'Black Eyed Peas', title: 'Boom Boom Pow', album: 'The E.N.D.' },
    { artist: 'Black Eyed Peas', title: 'Meet Me Halfway', album: 'The E.N.D.' },
    { artist: 'Florence + The Machine', title: 'Dog Days Are Over', album: 'Lungs' },
    { artist: 'La Roux', title: 'Bulletproof', album: 'La Roux' },
    { artist: 'Beyoncé', title: 'Halo', album: 'I Am... Sasha Fierce' },
    { artist: 'Beyoncé', title: 'Sweet Dreams', album: 'I Am... Sasha Fierce' },
    { artist: 'Shakira', title: 'She Wolf', album: 'She Wolf' },
    { artist: 'Kelly Clarkson', title: 'Already Gone', album: 'All I Ever Wanted' },
    { artist: 'Owl City', title: 'Fireflies', album: 'Ocean Eyes' },
    { artist: 'Jay Sean', title: 'Down', album: 'All or Nothing' },
    { artist: 'Miley Cyrus', title: 'Party in the U.S.A.', album: 'The Time of Our Lives' },
    { artist: 'Britney Spears', title: '3', album: 'The Singles Collection' },
    { artist: 'Rihanna', title: 'Russian Roulette', album: 'Rated R' },
    { artist: 'Jason Derulo', title: 'Whatcha Say', album: 'Jason Derulo' },
    { artist: 'Kesha', title: 'Tik Tok', album: 'Animal' },
    { artist: 'Whitney Houston', title: 'I Look to You', album: 'I Look to You' },
    { artist: 'Maxwell', title: 'Pretty Wings', album: 'BLACKsummers\'night' },
    { artist: 'Paramore', title: 'Ignorance', album: 'Brand New Eyes' },
    { artist: 'Colbie Caillat', title: 'Fallin\' for You', album: 'Breakthrough' },
    { artist: 'Shinedown', title: 'Second Chance', album: 'The Sound of Madness' },
    { artist: 'Pearl Jam', title: 'The Fixer', album: 'Backspacer' },
    { artist: 'Shakira', title: 'Did It Again', album: 'She Wolf' },
  ],
  2010: [
    { artist: 'Lady Gaga', title: 'Telephone', album: 'The Fame Monster' },
    { artist: 'Rihanna', title: 'Only Girl (In the World)', album: 'Loud' },
    { artist: 'Bruno Mars', title: 'Just the Way You Are', album: 'Doo-Wops & Hooligans' },
    { artist: 'Arcade Fire', title: 'The Suburbs', album: 'The Suburbs' },
    { artist: 'Katy Perry', title: 'Firework', album: 'Teenage Dream' },
  ],
  2011: [
    { artist: 'Adele', title: 'Rolling in the Deep', album: '21' },
    { artist: 'Adele', title: 'Someone Like You', album: '21' },
    { artist: 'Gotye', title: 'Somebody That I Used to Know', album: 'Making Mirrors' },
    { artist: 'LMFAO', title: 'Party Rock Anthem', album: 'Sorry for Party Rocking' },
    { artist: 'Maroon 5', title: 'Moves Like Jagger', album: 'Hands All Over' },
  ],
  2012: [
    { artist: 'Fun.', title: 'We Are Young', album: 'Some Nights' },
    { artist: 'Carly Rae Jepsen', title: 'Call Me Maybe', album: 'Kiss' },
    { artist: 'PSY', title: 'Gangnam Style', album: '' },
    { artist: 'Rihanna', title: 'We Found Love', album: 'Talk That Talk' },
    { artist: 'Maroon 5', title: 'Payphone', album: 'Overexposed' },
  ],
  2013: [
    { artist: 'Daft Punk', title: 'Get Lucky', album: 'Random Access Memories' },
    { artist: 'Lorde', title: 'Royals', album: 'Pure Heroine' },
    { artist: 'Avicii', title: 'Wake Me Up', album: 'True' },
    { artist: 'Miley Cyrus', title: 'Wrecking Ball', album: 'Bangerz' },
    { artist: 'OneRepublic', title: 'Counting Stars', album: 'Native' },
    { artist: 'Capital Cities', title: 'Safe and Sound', album: 'In a Tidal Wave of Mystery' },
    { artist: 'Imagine Dragons', title: 'Demons', album: 'Night Visions' },
    { artist: 'Bruno Mars', title: 'When I Was Your Man', album: 'Unorthodox Jukebox' },
    { artist: 'Bruno Mars', title: 'Locked Out of Heaven', album: 'Unorthodox Jukebox' },
    { artist: 'Pink', title: 'Just Give Me a Reason', album: 'The Truth About Love' },
    { artist: 'Justin Timberlake', title: 'Mirrors', album: 'The 20/20 Experience' },
    { artist: 'Justin Timberlake', title: 'Suit & Tie', album: 'The 20/20 Experience' },
    { artist: 'Robin Thicke', title: 'Blurred Lines', album: 'Blurred Lines' },
    { artist: 'Imagine Dragons', title: 'Radioactive', album: 'Night Visions' },
  ],
  2014: [
    { artist: 'Pharrell Williams', title: 'Happy', album: 'G I R L' },
    { artist: 'Sam Smith', title: 'Stay with Me', album: 'In the Lonely Hour' },
    { artist: 'Sia', title: 'Chandelier', album: '1000 Forms of Fear' },
    { artist: 'Mark Ronson', title: 'Uptown Funk', album: 'Uptown Special' },
    { artist: 'Hozier', title: 'Take Me to Church', album: 'Hozier' },
    { artist: 'John Legend', title: 'All of Me', album: 'Love in the Future' },
    { artist: 'Katy Perry', title: 'Dark Horse', album: 'Prism' },
    { artist: 'Clean Bandit', title: 'Rather Be', album: 'New Eyes' },
    { artist: 'Ariana Grande', title: 'Problem', album: 'My Everything' },
    { artist: 'Ed Sheeran', title: 'Thinking Out Loud', album: 'x' },
  ],
  2015: [
    { artist: 'Ed Sheeran', title: 'Photograph', album: 'x' },
    { artist: 'The Weeknd', title: "Can't Feel My Face", album: 'Beauty Behind the Madness' },
    { artist: 'Taylor Swift', title: 'Blank Space', album: '1989' },
    { artist: 'Taylor Swift', title: 'Shake It Off', album: '1989' },
    { artist: 'Maroon 5', title: 'Sugar', album: 'V' },
    { artist: 'Walk the Moon', title: 'Shut Up and Dance', album: 'Talking Is Hard' },
    { artist: 'Major Lazer', title: 'Lean On', album: 'Peace Is the Mission' },
    { artist: 'Ellie Goulding', title: 'Love Me like You Do', album: 'Delirium' },
    { artist: 'Omi', title: 'Cheerleader', album: 'Me 4 U' },
    { artist: 'Adele', title: 'Hello', album: '25' },
  ],
  2016: [
    { artist: 'Justin Bieber', title: 'Love Yourself', album: 'Purpose' },
    { artist: 'Justin Bieber', title: 'Sorry', album: 'Purpose' },
    { artist: 'The Chainsmokers', title: 'Closer', album: 'Collage' },
    { artist: 'Twenty One Pilots', title: 'Stressed Out', album: 'Blurryface' },
    { artist: 'Sia', title: 'Cheap Thrills', album: 'This Is Acting' },
    { artist: 'Adele', title: 'Hello', album: '25' },
    { artist: 'Shawn Mendes', title: 'Treat You Better', album: 'Illuminate' },
    { artist: 'Calvin Harris', title: 'This Is What You Came For', album: '' },
    { artist: 'Rihanna', title: 'Work', album: 'Anti' },
    { artist: 'Flume', title: 'Never Be like You', album: 'Skin' },
  ],
  2017: [
    { artist: 'Ed Sheeran', title: 'Shape of You', album: '÷' },
    { artist: 'Ed Sheeran', title: 'Castle on the Hill', album: '÷' },
    { artist: 'Ed Sheeran', title: 'Galway Girl', album: '÷' },
    { artist: 'Bruno Mars', title: "That's What I Like", album: '24K Magic' },
    { artist: 'Bruno Mars', title: '24K Magic', album: '24K Magic' },
    { artist: 'The Chainsmokers', title: 'Something Just like This', album: 'Memories...Do Not Open' },
    { artist: 'The Chainsmokers', title: 'Closer', album: 'Collage' },
    { artist: 'Dua Lipa', title: 'New Rules', album: 'Dua Lipa' },
    { artist: 'Harry Styles', title: 'Sign of the Times', album: 'Harry Styles' },
    { artist: 'Portugal. The Man', title: 'Feel It Still', album: 'Woodstock' },
    { artist: 'Imagine Dragons', title: 'Believer', album: 'Evolve' },
    { artist: 'Imagine Dragons', title: 'Thunder', album: 'Evolve' },
    { artist: 'Luis Fonsi', title: 'Despacito', album: 'Vida' },
    { artist: 'Taylor Swift', title: 'Look What You Made Me Do', album: 'Reputation' },
    { artist: 'Sam Smith', title: 'Too Good at Goodbyes', album: 'The Thrill of It All' },
    { artist: 'Zedd', title: 'The Middle', album: '' },
    { artist: 'Camila Cabello', title: 'Havana', album: 'Camila' },
    { artist: 'Charlie Puth', title: 'Attention', album: 'Voicenotes' },
    { artist: 'Shawn Mendes', title: "There's Nothing Holdin' Me Back", album: 'Illuminate' },
    { artist: 'Maroon 5', title: 'What Lovers Do', album: 'Red Pill Blues' },
    { artist: 'Kelly Clarkson', title: 'Love So Soft', album: 'Meaning of Life' },
    { artist: 'Kesha', title: 'Praying', album: 'Rainbow' },
    { artist: 'Clean Bandit', title: 'Symphony', album: 'What Is Love?' },
    { artist: 'Selena Gomez', title: "It Ain't Me", album: '' },
  ],
  2018: [
    { artist: 'Maroon 5', title: 'Girls Like You', album: 'Red Pill Blues' },
    { artist: 'Dua Lipa', title: 'IDGAF', album: 'Dua Lipa' },
    { artist: 'Dua Lipa', title: 'One Kiss', album: 'Dua Lipa' },
    { artist: 'Dua Lipa', title: 'New Rules', album: 'Dua Lipa' },
    { artist: 'Camila Cabello', title: 'Havana', album: 'Camila' },
    { artist: 'Camila Cabello', title: 'Never Be the Same', album: 'Camila' },
    { artist: 'Ariana Grande', title: 'thank u, next', album: 'thank u, next' },
    { artist: 'Ariana Grande', title: 'no tears left to cry', album: 'Sweetener' },
    { artist: 'Ariana Grande', title: 'God is a woman', album: 'Sweetener' },
    { artist: 'Lady Gaga', title: 'Shallow', album: 'A Star Is Born' },
    { artist: 'Zedd', title: 'The Middle', album: '' },
    { artist: 'Marshmello', title: 'Happier', album: '' },
    { artist: 'Billie Eilish', title: "when the party's over", album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?' },
    { artist: 'Billie Eilish', title: 'lovely', album: '' },
    { artist: 'Ed Sheeran', title: 'Perfect', album: '÷' },
    { artist: 'Bebe Rexha', title: 'Meant to Be', album: 'Expectations' },
    { artist: 'Imagine Dragons', title: 'Natural', album: 'Origins' },
    { artist: 'Imagine Dragons', title: 'Whatever It Takes', album: 'Evolve' },
    { artist: 'Shawn Mendes', title: 'In My Blood', album: 'Shawn Mendes' },
    { artist: 'Shawn Mendes', title: 'Lost in Japan', album: 'Shawn Mendes' },
    { artist: 'Halsey', title: 'Without Me', album: 'Manic' },
    { artist: 'Khalid', title: 'Love Lies', album: '' },
    { artist: 'Khalid', title: 'Better', album: 'Suncity' },
    { artist: 'Clean Bandit', title: 'Solo', album: 'What Is Love?' },
    { artist: 'Anne-Marie', title: '2002', album: 'Speak Your Mind' },
    { artist: 'Lauv', title: 'I Like Me Better', album: 'I met you when I was 18.' },
    { artist: 'Bazzi', title: 'Mine', album: 'Cosmic' },
    { artist: 'Zedd', title: 'Stay', album: '' },
    { artist: 'Little Mix', title: 'Woman Like Me', album: 'LM5' },
    { artist: 'Panic! at the Disco', title: 'High Hopes', album: 'Pray for the Wicked' },
    { artist: '5 Seconds of Summer', title: 'Youngblood', album: 'Youngblood' },
    { artist: 'Dan + Shay', title: 'Tequila', album: 'Dan + Shay' },
    { artist: 'Florida Georgia Line', title: 'Meant to Be', album: '' },
    { artist: 'Benny Blanco', title: 'Eastside', album: '' },
    { artist: 'Ariana Grande', title: 'breathin', album: 'Sweetener' },
    { artist: 'H.E.R.', title: 'Focus', album: 'I Used to Know Her' },
    { artist: 'Lauren Daigle', title: 'You Say', album: 'Look Up Child' },
    { artist: 'Luke Combs', title: 'Beautiful Crazy', album: 'This One\'s for You' },
    { artist: 'Selena Gomez', title: 'Back to You', album: '13 Reasons Why' },
    { artist: 'Charlie Puth', title: 'How Long', album: 'Voicenotes' },
    { artist: 'Troye Sivan', title: 'My My My!', album: 'Bloom' },
    { artist: 'Bebe Rexha', title: "I'm a Mess", album: 'Expectations' },
  ],
  2019: [
    { artist: 'Billie Eilish', title: 'bad guy', album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?' },
    { artist: 'Billie Eilish', title: 'bury a friend', album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?' },
    { artist: 'Billie Eilish', title: 'when the party\'s over', album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?' },
    { artist: 'Ariana Grande', title: '7 rings', album: 'thank u, next' },
    { artist: 'Ariana Grande', title: 'break up with your girlfriend, i\'m bored', album: 'thank u, next' },
    { artist: 'Ariana Grande', title: 'thank u, next', album: 'thank u, next' },
    { artist: 'Lizzo', title: 'Truth Hurts', album: 'Cuz I Love You' },
    { artist: 'Lizzo', title: 'Good as Hell', album: 'Cuz I Love You' },
    { artist: 'Lewis Capaldi', title: 'Someone You Loved', album: 'Divinely Uninspired to a Hellish Extent' },
    { artist: 'Tones and I', title: 'Dance Monkey', album: 'The Kids Are Coming' },
    { artist: 'Shawn Mendes', title: 'Señorita', album: '' },
    { artist: 'Jonas Brothers', title: 'Sucker', album: 'Happiness Begins' },
    { artist: 'Jonas Brothers', title: 'Only Human', album: 'Happiness Begins' },
    { artist: 'Khalid', title: 'Talk', album: 'Free Spirit' },
    { artist: 'Khalid', title: 'Better', album: 'Suncity' },
    { artist: 'Halsey', title: 'Without Me', album: 'Manic' },
    { artist: 'Ed Sheeran', title: "I Don't Care", album: 'No.6 Collaborations Project' },
    { artist: 'Ed Sheeran', title: 'Beautiful People', album: 'No.6 Collaborations Project' },
    { artist: 'Lady Gaga', title: 'Shallow', album: 'A Star Is Born' },
    { artist: 'Lady Gaga', title: 'Always Remember Us This Way', album: 'A Star Is Born' },
    { artist: 'Taylor Swift', title: 'You Need to Calm Down', album: 'Lover' },
    { artist: 'Taylor Swift', title: 'Lover', album: 'Lover' },
    { artist: 'Miley Cyrus', title: "Mother's Daughter", album: 'SHE IS COMING' },
    { artist: 'Ava Max', title: 'Sweet but Psycho', album: 'Heaven & Hell' },
    { artist: 'Lizzo', title: 'Juice', album: 'Cuz I Love You' },
    { artist: 'Billie Eilish', title: 'all the good girls go to hell', album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?' },
    { artist: 'Taylor Swift', title: 'The Man', album: 'Lover' },
    { artist: 'Selena Gomez', title: 'Lose You to Love Me', album: 'Rare' },
    { artist: 'Dua Lipa', title: "Don't Start Now", album: 'Future Nostalgia' },
    { artist: 'Sam Smith', title: 'How Do You Sleep?', album: 'Love Goes' },
    { artist: 'Dan + Shay', title: 'Speechless', album: 'Dan + Shay' },
    { artist: 'Maren Morris', title: 'The Bones', album: 'GIRL' },
    { artist: 'Maggie Rogers', title: 'Light On', album: 'Heard It in a Past Life' },
    { artist: 'Panic! at the Disco', title: 'Hey Look Ma, I Made It', album: 'Pray for the Wicked' },
    { artist: 'Luke Combs', title: 'Even Though I\'m Leaving', album: 'What You See Is What You Get' },
    { artist: 'Katy Perry', title: 'Never Really Over', album: 'Smile' },
    { artist: 'Shawn Mendes', title: "If I Can't Have You", album: '' },
    { artist: 'Harry Styles', title: 'Adore You', album: 'Fine Line' },
    { artist: 'Normani', title: 'Motivation', album: '' },
    { artist: 'Taylor Swift', title: 'ME!', album: 'Lover' },
    { artist: 'Maroon 5', title: 'Memories', album: 'Jordi' },
    { artist: 'Kygo', title: 'Higher Love', album: '' },
    { artist: 'Justin Bieber', title: '10,000 Hours', album: '' },
    { artist: 'Thomas Rhett', title: 'Look What God Gave Her', album: 'Center Point Road' },
    { artist: 'Luke Combs', title: 'Beer Never Broke My Heart', album: 'What You See Is What You Get' },
    { artist: 'P!nk', title: 'Walk Me Home', album: 'Hurts 2B Human' },
    { artist: 'Chris Brown', title: 'No Guidance', album: 'Indigo' },
    { artist: 'Miley Cyrus', title: 'Slide Away', album: '' },
    { artist: 'Carrie Underwood', title: 'Southbound', album: 'Cry Pretty' },
    { artist: 'Miranda Lambert', title: 'It All Comes Out in the Wash', album: 'Wildcard' },
    { artist: 'Halsey', title: 'Nightmare', album: '' },
  ],
  2020: [
    { artist: 'The Weeknd', title: 'Blinding Lights', album: 'After Hours' },
    { artist: 'The Weeknd', title: 'Save Your Tears', album: 'After Hours' },
    { artist: 'The Weeknd', title: 'Heartless', album: 'After Hours' },
    { artist: 'Harry Styles', title: 'Watermelon Sugar', album: 'Fine Line' },
    { artist: 'Harry Styles', title: 'Adore You', album: 'Fine Line' },
    { artist: 'Harry Styles', title: 'Falling', album: 'Fine Line' },
    { artist: 'Dua Lipa', title: "Don't Start Now", album: 'Future Nostalgia' },
    { artist: 'Dua Lipa', title: 'Break My Heart', album: 'Future Nostalgia' },
    { artist: 'Dua Lipa', title: 'Levitating', album: 'Future Nostalgia' },
    { artist: 'Dua Lipa', title: 'Physical', album: 'Future Nostalgia' },
    { artist: 'Lady Gaga', title: 'Rain on Me', album: 'Chromatica' },
    { artist: 'Lady Gaga', title: 'Stupid Love', album: 'Chromatica' },
    { artist: 'Taylor Swift', title: 'cardigan', album: 'folklore' },
    { artist: 'Taylor Swift', title: 'willow', album: 'evermore' },
    { artist: 'Taylor Swift', title: 'exile', album: 'folklore' },
    { artist: 'Miley Cyrus', title: 'Midnight Sky', album: 'Plastic Hearts' },
    { artist: 'Justin Bieber', title: 'Intentions', album: 'Changes' },
    { artist: 'Justin Bieber', title: 'Yummy', album: 'Changes' },
    { artist: 'Sam Smith', title: 'Diamonds', album: 'Love Goes' },
    { artist: 'Billie Eilish', title: 'Therefore I Am', album: '' },
    { artist: 'Billie Eilish', title: 'my future', album: '' },
    { artist: 'Ariana Grande', title: 'positions', album: 'Positions' },
    { artist: 'Ariana Grande', title: '34+35', album: 'Positions' },
    { artist: 'Maroon 5', title: 'Memories', album: 'Jordi' },
    { artist: 'Doja Cat', title: 'Say So', album: 'Hot Pink' },
    { artist: 'Jawsh 685', title: 'Savage Love (Laxed - Siren Beat)', album: '' },
    { artist: 'BENEE', title: 'Supalonely', album: 'Fire on Marzz' },
    { artist: 'Powfu', title: 'death bed', album: 'poems of the past' },
    { artist: 'Surfaces', title: 'Sunday Best', album: 'Where the Light Is' },
    { artist: 'Lewis Capaldi', title: 'Before You Go', album: 'Divinely Uninspired to a Hellish Extent' },
    { artist: 'Luke Combs', title: 'Forever After All', album: "What You See Ain't Always What You Get" },
    { artist: 'Morgan Wallen', title: 'More Than My Hometown', album: 'Dangerous: The Double Album' },
    { artist: 'Chris Stapleton', title: 'Starting Over', album: 'Starting Over' },
    { artist: 'Fleetwood Mac', title: 'Dreams', album: 'Rumours' },
    { artist: 'BTS', title: 'Dynamite', album: 'BE' },
    { artist: 'JP Saxe', title: 'If the World Was Ending', album: 'It\'s the Worst Possible Time to Be Alive' },
    { artist: 'Gabby Barrett', title: 'I Hope', album: 'Goldmine' },
    { artist: 'Luke Combs', title: "Lovin' on You", album: 'What You See Is What You Get' },
    { artist: 'AJR', title: 'Bang!', album: 'OK ORCHESTRA' },
    { artist: 'Miranda Lambert', title: 'Bluebird', album: 'Wildcard' },
    { artist: 'Zayn', title: 'Better', album: '' },
    { artist: 'Maluma', title: 'Hawái', album: 'PAPI JUANCHO' },
    { artist: 'Carly Pearce & Lee Brice', title: "I Hope You're Happy Now", album: 'Carly Pearce' },
    { artist: 'Ingrid Andress', title: 'More Hearts Than Mine', album: 'Lady Like' },
  ],
  2021: [
    { artist: 'Olivia Rodrigo', title: 'drivers license', album: 'SOUR' },
    { artist: 'Olivia Rodrigo', title: 'good 4 u', album: 'SOUR' },
    { artist: 'Olivia Rodrigo', title: 'deja vu', album: 'SOUR' },
    { artist: 'Olivia Rodrigo', title: 'traitor', album: 'SOUR' },
    { artist: 'Ed Sheeran', title: 'Bad Habits', album: '=' },
    { artist: 'Ed Sheeran', title: 'Shivers', album: '=' },
    { artist: 'Silk Sonic', title: 'Leave the Door Open', album: 'An Evening with Silk Sonic' },
    { artist: 'Glass Animals', title: 'Heat Waves', album: 'Dreamland' },
    { artist: 'Billie Eilish', title: 'Happier Than Ever', album: 'Happier Than Ever' },
    { artist: 'Billie Eilish', title: 'Therefore I Am', album: '' },
    { artist: 'Adele', title: 'Easy on Me', album: '30' },
    { artist: 'Coldplay', title: 'My Universe', album: 'Music of the Spheres' },
    { artist: 'Doja Cat', title: 'Kiss Me More', album: 'Planet Her' },
    { artist: 'Doja Cat', title: 'Need to Know', album: 'Planet Her' },
    { artist: 'The Weeknd', title: 'Save Your Tears', album: 'After Hours' },
    { artist: 'The Weeknd', title: 'Blinding Lights', album: 'After Hours' },
    { artist: 'Dua Lipa', title: 'Levitating', album: 'Future Nostalgia' },
    { artist: 'Justin Bieber', title: 'Peaches', album: 'Justice' },
    { artist: 'Justin Bieber', title: 'Ghost', album: 'Justice' },
    { artist: 'BTS', title: 'Butter', album: '' },
    { artist: 'BTS', title: 'Permission to Dance', album: '' },
    { artist: 'Taylor Swift', title: 'All Too Well (Taylor\'s Version)', album: 'Red (Taylor\'s Version)' },
    { artist: 'Taylor Swift', title: 'Willow', album: 'evermore' },
    { artist: 'Ariana Grande', title: 'positions', album: 'Positions' },
    { artist: 'Ariana Grande', title: '34+35', album: 'Positions' },
    { artist: 'Masked Wolf', title: 'Astronaut in the Ocean', album: 'Astronaut in the Ocean' },
    { artist: 'Walker Hayes', title: 'Fancy Like', album: 'Country Stuff' },
    { artist: 'Luke Combs', title: 'Forever After All', album: "What You See Ain't Always What You Get" },
    { artist: 'Chris Stapleton', title: 'You Should Probably Leave', album: 'Starting Over' },
    { artist: 'Carrie Underwood', title: "If I Didn't Love You", album: 'Denim & Rhinestones' },
    { artist: 'Morgan Wallen', title: 'Wasted on You', album: 'Dangerous: The Double Album' },
    { artist: 'Giveon', title: 'Heartbreak Anniversary', album: 'Take Time' },
    { artist: 'Måneskin', title: "Beggin'", album: 'Chosen' },
    { artist: 'PinkPantheress', title: 'Just for Me', album: '' },
    { artist: 'Dermot Kennedy', title: 'Better Days', album: 'Without Fear' },
    { artist: 'Surf Mesa', title: 'ILY (I Love You Baby)', album: '' },
    { artist: 'AJR', title: "World's Smallest Violin", album: 'OK ORCHESTRA' },
    { artist: 'Tai Verdes', title: 'A-O-K', album: 'HDTV' },
    { artist: 'Riton', title: 'Friday (Dopamine Re-Edit)', album: '' },
    { artist: 'SZA', title: 'Good Days', album: 'SOS' },
    { artist: 'Kane Brown', title: 'One Mississippi', album: 'Different Man' },
    { artist: 'Carly Pearce', title: 'Next Girl', album: '29' },
    { artist: 'Elle King', title: "Drunk (And I Don't Wanna Go Home)", album: 'Love Stuff' },
    { artist: 'Zac Brown Band', title: 'Same Boat', album: 'Comeback' },
    { artist: 'Eric Church', title: 'Stick That in Your Country Song', album: 'Heart & Soul' },
    { artist: 'Luke Bryan', title: 'Waves', album: 'Born Here Live Here Die Here' },
    { artist: 'Miranda Lambert', title: 'Settling Down', album: 'Wildcard' },
  ],
  2022: [
    { artist: 'Harry Styles', title: 'As It Was', album: "Harry's House" },
    { artist: 'Harry Styles', title: 'Late Night Talking', album: "Harry's House" },
    { artist: 'Kate Bush', title: 'Running Up That Hill (A Deal with God)', album: 'Hounds of Love' },
    { artist: 'Lizzo', title: 'About Damn Time', album: 'Special' },
    { artist: 'Beyoncé', title: 'Break My Soul', album: 'Renaissance' },
    { artist: 'Beyoncé', title: 'CUFF IT', album: 'Renaissance' },
    { artist: 'Taylor Swift', title: 'Anti-Hero', album: 'Midnights' },
    { artist: 'Taylor Swift', title: 'Lavender Haze', album: 'Midnights' },
    { artist: 'Steve Lacy', title: 'Bad Habit', album: 'Gemini Rights' },
    { artist: 'OneRepublic', title: "I Ain't Worried", album: 'Top Gun: Maverick' },
    { artist: 'Joji', title: 'Glimpse of Us', album: 'Smithereens' },
    { artist: 'Elton John', title: 'Hold Me Closer', album: '' },
    { artist: 'Måneskin', title: "Beggin'", album: 'Chosen' },
    { artist: 'Gayle', title: 'abcdefu', album: 'a study of the human experience volume one' },
    { artist: 'Ed Sheeran', title: 'Shivers', album: '=' },
    { artist: 'Adele', title: 'Easy on Me', album: '30' },
    { artist: 'Glass Animals', title: 'Heat Waves', album: 'Dreamland' },
    { artist: 'Imagine Dragons', title: 'Bones', album: 'Mercury – Acts 1 & 2' },
    { artist: 'Sam Smith', title: 'Unholy', album: 'Gloria' },
    { artist: 'Kim Petras', title: 'Unholy', album: 'Gloria' },
    { artist: 'Luke Combs', title: 'The Kind of Love We Make', album: "Growin' Up" },
    { artist: 'Morgan Wallen', title: 'You Proof', album: 'One Thing at a Time' },
    { artist: 'Walker Hayes', title: 'AA', album: 'Country Stuff the Album' },
    { artist: 'Carrie Underwood', title: 'Ghost Story', album: 'Denim & Rhinestones' },
    { artist: 'Parmalee', title: 'Take My Name', album: 'For You' },
    { artist: 'Cole Swindell', title: 'She Had Me at Heads Carolina', album: 'Stereotype' },
    { artist: 'Bailey Zimmerman', title: 'Fall in Love', album: '' },
    { artist: 'Dermot Kennedy', title: 'Better Days', album: 'Without Fear' },
    { artist: 'Surf Mesa', title: 'ILY (I Love You Baby)', album: '' },
    { artist: 'AJR', title: "World's Smallest Violin", album: 'OK ORCHESTRA' },
    { artist: 'Tai Verdes', title: 'A-O-K', album: 'HDTV' },
    { artist: 'Riton', title: 'Friday (Dopamine Re-Edit)', album: '' },
    { artist: 'SZA', title: 'Good Days', album: 'SOS' },
    { artist: 'Kane Brown', title: 'One Mississippi', album: 'Different Man' },
    { artist: 'Carly Pearce', title: 'Next Girl', album: '29' },
    { artist: 'Elle King', title: "Drunk (And I Don't Wanna Go Home)", album: 'Love Stuff' },
    { artist: 'Zac Brown Band', title: 'Same Boat', album: 'Comeback' },
    { artist: 'Eric Church', title: 'Stick That in Your Country Song', album: 'Heart & Soul' },
    { artist: 'Luke Bryan', title: 'Waves', album: 'Born Here Live Here Die Here' },
    { artist: 'Miranda Lambert', title: 'Settling Down', album: 'Wildcard' },
    { artist: 'Wet Leg', title: 'Chaise Longue', album: 'Wet Leg' },
    { artist: 'Rosalía', title: 'Despechá', album: 'Motomami' },
    { artist: 'Burna Boy', title: 'Last Last', album: 'Love, Damini' },
    { artist: 'Anitta', title: 'Envolver', album: 'Versions of Me' },
    { artist: 'Zach Bryan', title: 'Something in the Orange', album: '' },
    { artist: 'Zach Bryan', title: 'From Austin', album: 'American Heartbreak' },
    { artist: 'Red Hot Chili Peppers', title: 'Black Summer', album: 'Unlimited Love' },
    { artist: 'Red Hot Chili Peppers', title: 'These Are the Ways', album: 'Unlimited Love' },
    { artist: 'Arctic Monkeys', title: "There'd Better Be a Mirrorball", album: 'The Car' },
    { artist: 'Harry Styles', title: 'Daydreaming', album: "Harry's House" },
    { artist: 'Harry Styles', title: 'Satellite', album: "Harry's House" },
    { artist: 'Harry Styles', title: 'Music for a Sushi Restaurant', album: "Harry's House" },
    { artist: 'Beyoncé', title: 'ALIEN SUPERSTAR', album: 'Renaissance' },
    { artist: 'Beyoncé', title: 'CHURCH GIRL', album: 'Renaissance' },
    { artist: 'Taylor Swift', title: 'Maroon', album: 'Midnights' },
    { artist: 'Taylor Swift', title: 'Karma', album: 'Midnights' },
    { artist: 'Steve Lacy', title: 'Static', album: 'Gemini Rights' },
    { artist: 'Joji', title: 'YEAH RIGHT', album: 'Nectar' },
    { artist: 'MUNA', title: 'What I Want', album: 'MUNA' },
    { artist: 'Florence + The Machine', title: 'Free', album: 'Dance Fever' },
    { artist: 'Maggie Rogers', title: 'Honey', album: 'Surrender' },
    { artist: 'Em Beihold', title: 'Numb Little Bug', album: 'Egg in the Backseat' },
    { artist: 'JVKE', title: 'golden hour', album: 'this is what ____ feels like (Vol. 1-4)' },
    { artist: 'Stephen Sanchez', title: 'Until I Found You', album: 'Angel Face' },
    { artist: 'Farruko', title: 'Pepas', album: 'La 167' },
    { artist: 'SZA', title: 'Shirt', album: 'SOS' },
    { artist: 'Dove Cameron', title: 'Boyfriend', album: '' },
    { artist: 'Lauren Spencer-Smith', title: 'Fingers Crossed', album: 'Mirror' },
    { artist: 'Nicky Youre & dazy', title: 'Sunroof', album: '' },
    { artist: 'LF System', title: 'Afraid to Feel', album: '' },
    { artist: 'Beyoncé', title: 'SUMMER RENAISSANCE', album: 'Renaissance' },
    { artist: 'Beyoncé', title: "VIRGO'S GROOVE", album: 'Renaissance' },
    { artist: 'Beyoncé', title: 'PLASTIC OFF THE SOFA', album: 'Renaissance' },
    { artist: 'Harry Styles', title: 'Love of My Life', album: "Harry's House" },
    { artist: 'Harry Styles', title: 'Keep Driving', album: "Harry's House" },
    { artist: 'Meghan Trainor', title: 'Made You Look', album: 'Takin It Back' },
    { artist: 'Meghan Trainor', title: "Don't I Make It Look Easy", album: 'Takin It Back' },
    { artist: 'The Weeknd', title: 'Sacrifice', album: 'Dawn FM' },
    { artist: 'The Weeknd', title: 'Out of Time', album: 'Dawn FM' },
    { artist: 'The Weeknd', title: 'Take My Breath', album: 'Dawn FM' },
    { artist: 'Camila Cabello', title: 'Bam Bam', album: 'Familia' },
    { artist: 'Halsey', title: 'So Good', album: 'If I Can\'t Have Love, I Want Power' },
    { artist: 'Demi Lovato', title: 'SUBSTANCE', album: 'HOLY FVCK' },
    { artist: 'Måneskin', title: 'SUPERMODEL', album: '' },
    { artist: 'Måneskin', title: 'The Loneliest', album: 'RUSH!' },
    { artist: 'Turnstile', title: 'NEW HEARTS', album: 'GLOW ON' },
    { artist: 'Paramore', title: 'This Is Why', album: 'This Is Why' },
    { artist: 'The 1975', title: 'Part of the Band', album: 'Being Funny in a Foreign Language' },
    { artist: 'Wet Leg', title: 'Wet Dream', album: 'Wet Leg' },
    { artist: 'Wet Leg', title: 'Angelica', album: 'Wet Leg' },
    { artist: 'Rosalía', title: 'BIZCOCHITO', album: 'Motomami' },
    { artist: 'SZA', title: 'I Hate U', album: 'SOS' },
    { artist: 'SZA', title: 'Snooze', album: 'SOS' },
    { artist: 'Lana Del Rey', title: 'Snow On The Beach', album: 'Did you know that there\'s a tunnel under Ocean Blvd' },
    { artist: 'Lana Del Rey', title: 'Watercolor Eyes', album: 'Euphoria Season 2' },
    { artist: 'Imagine Dragons', title: 'Sharks', album: 'Mercury – Acts 1 & 2' },
    { artist: 'Panic! At The Disco', title: 'Viva Las Vengeance', album: 'Viva Las Vengeance' },
    { artist: 'Elton John & Britney Spears', title: 'Hold Me Closer', album: '' },
    { artist: 'BLACKPINK', title: 'Pink Venom', album: 'Born Pink' },
    { artist: '(G)I-DLE', title: 'Nxde', album: 'I Love' },
    { artist: 'BTS', title: 'Yet to Come', album: 'Proof' },
    { artist: 'Stray Kids', title: 'Maniac', album: 'Oddinary' },
    { artist: 'ITZY', title: 'Sneakers', album: 'Checkmate' },
    { artist: 'NCT Dream', title: 'Beatbox', album: 'Beatbox' },
    { artist: 'Tove Lo', title: '2 Be Loved (Am I Ready)', album: 'Dirt Femme' },
    { artist: 'Lizzo', title: '2 Be Loved (Am I Ready)', album: 'Special' },
    { artist: 'The Killers', title: 'Boy', album: 'Imploding the Mirage' },
    { artist: 'Fontaines D.C.', title: 'Jackie Down the Line', album: 'Skinty Fia' },
    { artist: 'KAROL G', title: 'Provenza', album: 'Mañana Será Bonito' },
    { artist: 'Rauw Alejandro', title: 'Desesperados', album: 'Vice Versa' },
    { artist: 'Calvin Harris', title: 'New To You', album: 'Funk Wav Bounces Vol. 2' },
    { artist: 'Selena Gomez', title: 'My Mind & Me', album: '' },
  ],
  2023: [
    { artist: 'Morgan Wallen', title: 'Last Night', album: 'One Thing at a Time' },
    { artist: 'Taylor Swift', title: 'Cruel Summer', album: 'Lover' },
    { artist: 'SZA', title: 'Kill Bill', album: 'SOS' },
    { artist: 'Miley Cyrus', title: 'Flowers', album: 'Endless Summer Vacation' },
    { artist: 'Rema', title: 'Calm Down', album: 'Rave & Roses' },
    { artist: 'Jung Kook', title: 'Seven', album: 'Golden' },
    { artist: 'NewJeans', title: 'Super Shy', album: 'Get Up' },
    { artist: 'NewJeans', title: 'ETA', album: 'Get Up' },
    { artist: 'Dua Lipa', title: 'Dance the Night', album: 'Barbie the Album' },
    { artist: 'Billie Eilish', title: 'What Was I Made For?', album: 'Barbie the Album' },
    { artist: 'Olivia Rodrigo', title: 'vampire', album: 'GUTS' },
    { artist: 'Tate McRae', title: 'greedy', album: 'Think Later' },
    { artist: 'Luke Combs', title: 'Fast Car', album: 'Gettin Old' },
    { artist: 'Jelly Roll', title: 'Need a Favor', album: 'Whitsitt Chapel' },
    { artist: 'Jason Aldean', title: 'Try That in a Small Town', album: 'Highway Desperado' },
    { artist: 'Djo', title: 'End of Beginning', album: 'DECIDE' },
    { artist: 'Fred again..', title: 'Marea (We\'ve Lost Dancing)', album: 'Actual Life 3' },
    { artist: 'PinkPantheress', title: 'Boy\'s a liar Pt. 2', album: '' },
  ],
  2024: [
    { artist: 'Teddy Swims', title: 'Lose Control', album: "I've Tried Everything but Therapy (Part 1)" },
    { artist: 'Shaboozey', title: 'A Bar Song (Tipsy)', album: "Where I've Been, Isn't Where I'm Going" },
    { artist: 'Benson Boone', title: 'Beautiful Things', album: 'Fireworks & Rollerblades' },
    { artist: 'Sabrina Carpenter', title: 'Espresso', album: "Short n' Sweet" },
    { artist: 'Billie Eilish', title: 'Birds of a Feather', album: 'Hit Me Hard and Soft' },
    { artist: 'Chappell Roan', title: 'Good Luck, Babe!', album: 'The Rise and Fall of a Midwest Princess' },
    { artist: 'Hozier', title: 'Too Sweet', album: 'Unreal Unearth: Unheard' },
    { artist: 'Taylor Swift', title: 'Fortnight', album: 'THE TORTURED POETS DEPARTMENT' },
    { artist: 'Ariana Grande', title: "we can't be friends (wait for your love)", album: 'eternal sunshine' },
    { artist: 'Sabrina Carpenter', title: 'Please Please Please', album: "Short n' Sweet" },
    { artist: 'Sabrina Carpenter', title: 'Taste', album: "Short n' Sweet" },
    { artist: 'Sabrina Carpenter', title: 'Bed Chem', album: "Short n' Sweet" },
    { artist: 'Sabrina Carpenter', title: 'Juno', album: "Short n' Sweet" },
    { artist: 'Taylor Swift', title: 'I Can Do It With a Broken Heart', album: 'THE TORTURED POETS DEPARTMENT' },
    { artist: 'Ariana Grande', title: 'yes, and?', album: 'eternal sunshine' },
    { artist: 'Billie Eilish', title: 'Lunch', album: 'Hit Me Hard and Soft' },
    { artist: 'Billie Eilish', title: 'Chihiro', album: 'Hit Me Hard and Soft' },
    { artist: 'Dua Lipa', title: 'Training Season', album: 'Radical Optimism' },
    { artist: 'Dua Lipa', title: 'Illusion', album: 'Radical Optimism' },
    { artist: 'Beyoncé', title: "TEXAS HOLD 'EM", album: 'Cowboy Carter' },
    { artist: 'Beyoncé', title: 'JOLENE', album: 'Cowboy Carter' },
    { artist: 'Beyoncé', title: 'Bodyguard', album: 'Cowboy Carter' },
    { artist: 'SZA', title: 'Saturn', album: '' },
    { artist: 'Muni Long', title: 'Made for Me', album: 'Revenge' },
    { artist: 'Tyla', title: 'Truth or Dare', album: 'TYLA' },
    { artist: 'Benson Boone', title: 'Slow It Down', album: 'Fireworks & Rollerblades' },
    { artist: 'Teddy Swims', title: 'The Door', album: "I've Tried Everything but Therapy (Part 2)" },
    { artist: 'Artemas', title: 'i like the way you kiss me', album: 'yustyna' },
    { artist: 'Stray Kids', title: 'Chk Chk Boom', album: 'ATE' },
    { artist: 'NewJeans', title: 'How Sweet', album: 'How Sweet' },
    { artist: 'ILLIT', title: 'Magnetic', album: 'SUPER REAL ME' },
    { artist: 'LE SSERAFIM', title: 'Easy', album: 'EASY' },
    { artist: 'ROSÉ & Bruno Mars', title: 'APT.', album: 'rosie' },
    { artist: 'Lady Gaga', title: 'Disease', album: '' },
    { artist: 'Coldplay', title: 'feelslikeimfallinginlove', album: 'Moon Music' },
    { artist: 'Imagine Dragons', title: 'Eyes Closed', album: 'LOOM' },
    { artist: 'Twenty One Pilots', title: 'Overcompensate', album: 'Clancy' },
    { artist: 'Morgan Wallen', title: 'Love Somebody', album: 'Dangerous: The Double Album' },
    { artist: 'Luke Combs', title: "Ain't No Love in Oklahoma", album: 'Twisters: The Album' },
    { artist: 'Jelly Roll', title: 'Liar', album: 'Beautifully Broken' },
    { artist: 'Jelly Roll', title: 'I Am Not Okay', album: 'Beautifully Broken' },
    { artist: 'Kali Uchis', title: 'MUÑECA', album: 'ORQUÍDEAS' },
    { artist: 'Karol G', title: 'Si Antes Te Hubiera Conocido', album: 'Mañana Será Bonito (Bichota Season)' },
    { artist: 'Vampire Weekend', title: 'Capricorn', album: 'Only God Was Above Us' },
    { artist: 'Bleachers', title: 'Tiny Moves', album: 'Bleachers' },
    { artist: 'Fontaines D.C.', title: 'Starburster', album: 'Romance' },
    { artist: 'The Killers', title: 'Bright Lights', album: 'Bright Lights' },
    { artist: 'Katy Perry', title: "WOMAN'S WORLD", album: '143' },
    { artist: 'Noah Kahan', title: 'Stick Season', album: 'Stick Season' },
  ],
  2025: [
    { artist: 'Sabrina Carpenter', title: 'Manchild', album: "Man's Best Friend" },
    { artist: 'Sabrina Carpenter', title: 'Busy Woman', album: "Man's Best Friend" },
    { artist: 'Lady Gaga', title: 'Die with a Smile', album: 'Harlequin' },
    { artist: 'Lady Gaga', title: 'Abracadabra', album: 'Mayhem' },
    { artist: 'Lady Gaga', title: 'Garden of Eden', album: 'Mayhem' },
    { artist: 'Billie Eilish', title: 'Wildflower', album: 'Hit Me Hard and Soft' },
    { artist: 'Chappell Roan', title: 'Pink Pony Club', album: 'The Rise and Fall of a Midwest Princess' },
    { artist: 'Shaboozey', title: 'Good News', album: "Where I've Been, Isn't Where I'm Going" },
    { artist: 'Alex Warren', title: 'Ordinary', album: "You'll Be Alright, Kid" },
    { artist: 'Alex Warren', title: 'Burning Down', album: "You'll Be Alright, Kid" },
    { artist: 'Tate McRae', title: 'Sports car', album: 'So Close to What' },
    { artist: 'Tate McRae', title: 'Revolving door', album: 'So Close to What' },
    { artist: 'Benson Boone', title: 'Mystical Magical', album: 'American Heart' },
    { artist: 'Morgan Wallen', title: "I'm the Problem", album: "I'm the Problem" },
    { artist: 'Morgan Wallen', title: 'Just in Case', album: "I'm the Problem" },
    { artist: 'Jelly Roll', title: 'Losers', album: 'Beautifully Broken' },
    { artist: 'Addison Rae', title: 'Aquamarine', album: 'Addison' },
    { artist: 'Addison Rae', title: 'Diet Pepsi', album: 'Addison' },
    { artist: 'Sombr', title: 'back to friends', album: '' },
    { artist: 'Gracie Abrams', title: "That's So True", album: 'The Secret of Us' },
    { artist: 'ROSÉ & Bruno Mars', title: 'APT.', album: 'rosie' },
    { artist: 'Stray Kids', title: 'CEREMONY', album: '合 (HOP)' },
    { artist: 'LE SSERAFIM', title: 'HOT', album: 'HOT' },
    { artist: 'Dua Lipa', title: 'Training Season', album: 'Radical Optimism' },
    { artist: 'Dua Lipa', title: 'Illusion', album: 'Radical Optimism' },
    { artist: 'Hozier', title: 'Too Sweet', album: 'Unreal Unearth: Unheard' },
    { artist: 'Sabrina Carpenter', title: 'Espresso', album: "Short n' Sweet" },
    { artist: 'Sabrina Carpenter', title: 'Please Please Please', album: "Short n' Sweet" },
    { artist: 'Sabrina Carpenter', title: 'Taste', album: "Short n' Sweet" },
    { artist: 'Taylor Swift', title: 'Fortnight', album: 'THE TORTURED POETS DEPARTMENT' },
    { artist: 'Ariana Grande', title: "we can't be friends (wait for your love)", album: 'eternal sunshine' },
    { artist: 'Billie Eilish', title: 'Birds of a Feather', album: 'Hit Me Hard and Soft' },
    { artist: 'Chappell Roan', title: 'Good Luck, Babe!', album: 'The Rise and Fall of a Midwest Princess' },
    { artist: 'Teddy Swims', title: 'Lose Control', album: "I've Tried Everything but Therapy (Part 1)" },
    { artist: 'Shaboozey', title: 'A Bar Song (Tipsy)', album: "Where I've Been, Isn't Where I'm Going" },
    { artist: 'Benson Boone', title: 'Beautiful Things', album: 'Fireworks & Rollerblades' },
    { artist: 'Hozier', title: 'Too Sweet', album: 'Unreal Unearth: Unheard' },
    { artist: 'Beyoncé', title: "TEXAS HOLD 'EM", album: 'Cowboy Carter' },
    { artist: 'The Weeknd', title: 'Cry For Me', album: 'Hurry Up Tomorrow' },
    { artist: 'The Weeknd', title: 'Timeless', album: 'Hurry Up Tomorrow' },
    { artist: 'Katy Perry', title: 'LIFETIMES', album: '143' },
    { artist: 'Coldplay', title: 'feelslikeimfallinginlove', album: 'Moon Music' },
    { artist: 'Karol G', title: 'Si Antes Te Hubiera Conocido', album: 'Mañana Será Bonito (Bichota Season)' },
    { artist: 'Artemas', title: 'i like the way you kiss me', album: 'yustyna' },
    { artist: 'Muni Long', title: 'Made for Me', album: 'Revenge' },
    { artist: 'Tyla', title: 'Truth or Dare', album: 'TYLA' },
    { artist: 'Noah Kahan', title: 'Stick Season', album: 'Stick Season' },
    { artist: 'Luke Combs', title: "Ain't No Love in Oklahoma", album: 'Twisters: The Album' },
    { artist: 'Jelly Roll', title: 'Liar', album: 'Beautifully Broken' },
    { artist: 'Ed Sheeran', title: 'Azizam', album: 'Play' },
    { artist: 'Ed Sheeran', title: 'Sapphire', album: 'Play' },
    { artist: 'Conan Gray', title: 'Lonely Dancers', album: 'Wishbone' },
    { artist: 'Conan Gray', title: 'This Song', album: 'Wishbone' },
    { artist: 'Olivia Dean', title: 'A Couple Minutes', album: 'Messy' },
    { artist: 'Olivia Dean', title: 'So Easy (To Fall In Love)', album: 'Messy' },
    { artist: 'Fontaines D.C.', title: 'In The Modern World', album: 'Romance' },
    { artist: 'PinkPantheress', title: 'Nice to meet you', album: 'Heaven knows' },
    { artist: 'ROLE MODEL', title: 'Sally When The Wine Runs Out', album: 'Kansas Anymore' },
    { artist: 'Lola Young', title: 'Messy', album: 'My Mind Wanders and Sometimes Comes Back' },
    { artist: 'David Guetta & OneRepublic', title: "I Don't Wanna Wait", album: '' },
    { artist: 'Kygo & Ava Max', title: 'Whatever', album: 'Kygo' },
    { artist: 'Calvin Harris & Ellie Goulding', title: 'Free', album: 'Funk Wav Bounces Vol. 2' },
    { artist: 'P!nk', title: 'TRUSTFALL', album: 'TRUSTFALL' },
  ],
};
