-- Chat 세션·메시지
-- 원격에 이미 수동 생성된 경우 이 파일은 스킵한다.
-- 컬럼 의미 SSOT: docs/supabase-tables/chat.md

CREATE TABLE IF NOT EXISTS public."ChatSession"
(
    "SessionID"     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SerialNo"      bigint NOT NULL,
    "ProviderID"    bigint NOT NULL,
    "Title"         varchar NOT NULL,
    "IsDeleted"     boolean NOT NULL DEFAULT false,
    "RegDate"       timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."ChatSession"
IS '사용자별 LLM 대화 세션';

COMMENT ON COLUMN public."ChatSession"."SessionID"
IS '대화 세션 고유번호';

COMMENT ON COLUMN public."ChatSession"."SerialNo"
IS '사용자 일련번호';

COMMENT ON COLUMN public."ChatSession"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."ChatSession"."Title"
IS '대화 제목';

COMMENT ON COLUMN public."ChatSession"."IsDeleted"
IS '삭제 여부';

COMMENT ON COLUMN public."ChatSession"."RegDate"
IS '생성 일시';

COMMENT ON COLUMN public."ChatSession"."UpdateDate"
IS '마지막 대화 일시';

CREATE INDEX IF NOT EXISTS "IX_ChatSession_SerialNo"
ON public."ChatSession" ("SerialNo");

CREATE INDEX IF NOT EXISTS "IX_ChatSession_UpdateDate"
ON public."ChatSession" ("UpdateDate" DESC);

CREATE TABLE IF NOT EXISTS public."ChatMessage"
(
    "MessageID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SessionID"      bigint NOT NULL,
    "Role"           varchar NOT NULL,
    "Content"        text NOT NULL,

    "InputToken"     integer NOT NULL DEFAULT 0,
    "OutputToken"    integer NOT NULL DEFAULT 0,
    "TotalToken"     integer NOT NULL DEFAULT 0,

    "RegDate"        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."ChatMessage"
IS 'LLM 대화 메시지';

COMMENT ON COLUMN public."ChatMessage"."MessageID"
IS '메시지 고유번호';

COMMENT ON COLUMN public."ChatMessage"."SessionID"
IS '대화 세션 고유번호';

COMMENT ON COLUMN public."ChatMessage"."Role"
IS '메시지 작성자 (user, assistant, system)';

COMMENT ON COLUMN public."ChatMessage"."Content"
IS '메시지 내용';

COMMENT ON COLUMN public."ChatMessage"."InputToken"
IS '이번 요청의 입력 토큰';

COMMENT ON COLUMN public."ChatMessage"."OutputToken"
IS '이번 응답의 출력 토큰';

COMMENT ON COLUMN public."ChatMessage"."TotalToken"
IS '이번 요청의 총 토큰';

COMMENT ON COLUMN public."ChatMessage"."RegDate"
IS '메시지 생성 일시';

CREATE INDEX IF NOT EXISTS "IX_ChatMessage_SessionID"
ON public."ChatMessage" ("SessionID");

CREATE INDEX IF NOT EXISTS "IX_ChatMessage_RegDate"
ON public."ChatMessage" ("RegDate");
