-- 사용자별 LLM 사용 권한·할당 토큰
-- 원격에 이미 수동 생성된 경우 이 파일은 스킵한다.
-- 컬럼 의미 SSOT: docs/supabase-tables/llm.md

CREATE TABLE IF NOT EXISTS public."LLMUserPermission"
(
    "PermissionID"      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SerialNo"          bigint NOT NULL,
    "ProviderID"        bigint NOT NULL,

    "IsApproved"        boolean NOT NULL DEFAULT false,

    "AllocatedToken"    bigint NOT NULL DEFAULT 0,

    "ApprovedDate"      timestamptz,

    "RegDate"           timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"        timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMUserPermission"
IS '사용자별 LLM 사용 권한 및 토큰 할당';

COMMENT ON COLUMN public."LLMUserPermission"."PermissionID"
IS '권한 고유번호';

COMMENT ON COLUMN public."LLMUserPermission"."SerialNo"
IS '사용자 일련번호';

COMMENT ON COLUMN public."LLMUserPermission"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."LLMUserPermission"."IsApproved"
IS 'LLM 사용 승인 여부';

COMMENT ON COLUMN public."LLMUserPermission"."AllocatedToken"
IS '관리자가 할당한 총 사용 가능 토큰';

COMMENT ON COLUMN public."LLMUserPermission"."ApprovedDate"
IS '승인 일시';

COMMENT ON COLUMN public."LLMUserPermission"."RegDate"
IS '등록 일시';

COMMENT ON COLUMN public."LLMUserPermission"."UpdateDate"
IS '최종 수정 일시';

CREATE UNIQUE INDEX IF NOT EXISTS "UX_LLMUserPermission"
ON public."LLMUserPermission"
(
    "SerialNo",
    "ProviderID"
);
