-- NullReferMusic: GitHub JSON 5종 → Supabase Postgres
-- alarm, user_ban_list, inquiry, user_list, apk_version + inquiry Storage

-- ── 공통 ─────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nrm_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ── nrm_apk_version (data/apkVersion.json) ───────────────────────────────────
CREATE TABLE public.nrm_apk_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version TEXT NOT NULL,
  created_date TIMESTAMPTZ NOT NULL,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT nrm_apk_version_version_unique UNIQUE (version)
);

CREATE INDEX nrm_apk_version_created_date_idx
  ON public.nrm_apk_version (created_date DESC);

CREATE TRIGGER nrm_apk_version_updated_at
  BEFORE UPDATE ON public.nrm_apk_version
  FOR EACH ROW EXECUTE FUNCTION public.nrm_set_updated_at();

COMMENT ON TABLE public.nrm_apk_version IS 'GitHub Releases 공개 APK 최신 버전 (구 data/apkVersion.json). 최신 1건: ORDER BY created_date DESC, id DESC LIMIT 1';

-- ── nrm_alarm (data/alarm.json) ──────────────────────────────────────────────
CREATE TABLE public.nrm_alarm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_noti BOOLEAN NOT NULL DEFAULT false,
  title TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  serial_no TEXT NOT NULL DEFAULT '',
  alarm_date DATE NOT NULL,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX nrm_alarm_alarm_date_idx ON public.nrm_alarm (alarm_date DESC);
CREATE INDEX nrm_alarm_serial_no_idx ON public.nrm_alarm (serial_no);

CREATE TRIGGER nrm_alarm_updated_at
  BEFORE UPDATE ON public.nrm_alarm
  FOR EACH ROW EXECUTE FUNCTION public.nrm_set_updated_at();

COMMENT ON TABLE public.nrm_alarm IS '인앱 알림·상단 공지 (구 data/alarm.json)';
COMMENT ON COLUMN public.nrm_alarm.serial_no IS '비어 있으면 모든 SerialNo APK. 값 있으면 해당 SerialNo만';

-- ── nrm_user_ban_list (data/userBanList.json) ────────────────────────────────
CREATE TABLE public.nrm_user_ban_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL DEFAULT '',
  serial_no TEXT NOT NULL,
  content TEXT NOT NULL DEFAULT '',
  is_banned BOOLEAN NOT NULL DEFAULT false,
  ban_date DATE NOT NULL,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX nrm_user_ban_list_serial_id_idx
  ON public.nrm_user_ban_list (serial_no, id DESC);

CREATE TRIGGER nrm_user_ban_list_updated_at
  BEFORE UPDATE ON public.nrm_user_ban_list
  FOR EACH ROW EXECUTE FUNCTION public.nrm_set_updated_at();

COMMENT ON TABLE public.nrm_user_ban_list IS '사용자 차단·해제 이력 (구 data/userBanList.json)';

-- ── nrm_inquiry (data/inquiry.json) ──────────────────────────────────────────
CREATE TABLE public.nrm_inquiry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL DEFAULT '',
  serial_no TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL,
  attached_file TEXT NOT NULL DEFAULT '',
  is_answered BOOLEAN NOT NULL DEFAULT false,
  reply_content TEXT NOT NULL DEFAULT '',
  created_date TIMESTAMPTZ NOT NULL,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX nrm_inquiry_serial_no_idx ON public.nrm_inquiry (serial_no);
CREATE INDEX nrm_inquiry_created_date_idx ON public.nrm_inquiry (created_date DESC);

CREATE TRIGGER nrm_inquiry_updated_at
  BEFORE UPDATE ON public.nrm_inquiry
  FOR EACH ROW EXECUTE FUNCTION public.nrm_set_updated_at();

COMMENT ON TABLE public.nrm_inquiry IS '문의하기 (구 data/inquiry.json)';
COMMENT ON COLUMN public.nrm_inquiry.attached_file IS 'Supabase Storage 경로 (구 data/inquiryAttachFile/...)';

-- ── nrm_user_list (data/custom-apk/userList.json) ────────────────────────────
CREATE TABLE public.nrm_user_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_name TEXT NOT NULL DEFAULT '',
  user_name TEXT NOT NULL,
  serial_no TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '',
  created_date DATE NOT NULL,
  device_id TEXT,
  last_access_date TIMESTAMPTZ,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX nrm_user_list_serial_no_idx ON public.nrm_user_list (serial_no);
CREATE INDEX nrm_user_list_serial_id_idx
  ON public.nrm_user_list (serial_no, id DESC);

CREATE TRIGGER nrm_user_list_updated_at
  BEFORE UPDATE ON public.nrm_user_list
  FOR EACH ROW EXECUTE FUNCTION public.nrm_set_updated_at();

COMMENT ON TABLE public.nrm_user_list IS '커스텀 APK 등록·디바이스 바인딩 (구 data/custom-apk/userList.json)';

-- ── Storage: 문의 첨부 (구 data/inquiryAttachFile/) ─────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'inquiry-attachments',
  'inquiry-attachments',
  true,
  20971520,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit;

-- ── RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.nrm_apk_version ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nrm_alarm ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nrm_user_ban_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nrm_inquiry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nrm_user_list ENABLE ROW LEVEL SECURITY;

-- 읽기: 앱(anon/publishable) — GitHub raw와 동일하게 공개 조회
CREATE POLICY nrm_apk_version_select_anon
  ON public.nrm_apk_version FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY nrm_alarm_select_anon
  ON public.nrm_alarm FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY nrm_user_ban_list_select_anon
  ON public.nrm_user_ban_list FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY nrm_inquiry_select_anon
  ON public.nrm_inquiry FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY nrm_user_list_select_anon
  ON public.nrm_user_list FOR SELECT TO anon, authenticated
  USING (true);

-- 쓰기: 앱(anon) — GitHub PAT 내장과 동일 보안 수준 (APK에서 publishable key 사용)
-- 추후 Edge Function / service_role로 강화 예정

CREATE POLICY nrm_apk_version_insert_anon
  ON public.nrm_apk_version FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY nrm_apk_version_update_anon
  ON public.nrm_apk_version FOR UPDATE TO anon, authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY nrm_alarm_insert_anon
  ON public.nrm_alarm FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY nrm_alarm_update_anon
  ON public.nrm_alarm FOR UPDATE TO anon, authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY nrm_alarm_delete_anon
  ON public.nrm_alarm FOR DELETE TO anon, authenticated
  USING (true);

CREATE POLICY nrm_user_ban_list_insert_anon
  ON public.nrm_user_ban_list FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY nrm_user_ban_list_update_anon
  ON public.nrm_user_ban_list FOR UPDATE TO anon, authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY nrm_inquiry_insert_anon
  ON public.nrm_inquiry FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY nrm_inquiry_update_anon
  ON public.nrm_inquiry FOR UPDATE TO anon, authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY nrm_user_list_insert_anon
  ON public.nrm_user_list FOR INSERT TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY nrm_user_list_update_anon
  ON public.nrm_user_list FOR UPDATE TO anon, authenticated
  USING (true) WITH CHECK (true);

-- Storage: 공개 읽기 + anon 업로드
CREATE POLICY nrm_inquiry_attachments_select
  ON storage.objects FOR SELECT TO anon, authenticated
  USING (bucket_id = 'inquiry-attachments');

CREATE POLICY nrm_inquiry_attachments_insert
  ON storage.objects FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'inquiry-attachments');

CREATE POLICY nrm_inquiry_attachments_update
  ON storage.objects FOR UPDATE TO anon, authenticated
  USING (bucket_id = 'inquiry-attachments')
  WITH CHECK (bucket_id = 'inquiry-attachments');

CREATE POLICY nrm_inquiry_attachments_delete
  ON storage.objects FOR DELETE TO anon, authenticated
  USING (bucket_id = 'inquiry-attachments');

-- PostgREST: nrm_apk_version 최신 1건은 뷰 없이 테이블 직접 조회
--   ?order=created_date.desc,id.desc&limit=1
