-- LLM 스키마 정규화: LLMProvider(모델 목록, ApiKey 중복 보유) → LLMModel(모델) + LLMProvider(제공자, ApiKey 단독 보유)
--
-- 배경: 기존 "LLMProvider" 테이블은 사실 "모델" 목록이었고(Gemini 모델마다 행 하나),
-- 모든 행이 동일한 ApiKey를 그대로 복제해서 들고 있었다 — provider(ApiKey 소유자)와
-- model(그 provider가 제공하는 개별 모델)이 뒤섞여 있던 것. 이 마이그레이션은:
--
--   1) "LLMProvider"(기존, 모델 목록) → "LLMModel"로 이름 변경. PK "ProviderID" → "ModelID".
--      ApiKey/DailyLimit/MonthlyLimit/ProviderName 컬럼은 새 "LLMProvider"로 옮기거나
--      제거(정규화 — provider 단위 정보는 이제 join으로 가져온다). "ProviderID"(신규,
--      LLMProvider FK) 컬럼을 추가해 각 모델이 어느 provider 소속인지 표시.
--   2) 새 "LLMProvider" 테이블 생성: ProviderID(PK)/ProviderName/ApiKey/RegDate 만.
--      현재 유일한 provider(ProviderID=1, ProviderName='Google')를 기존 LLMModel.ApiKey
--      값으로 시드.
--   3) LLMUserPermission/LLMUserMonthlyAllocation/LLMUserQuota — 지금까지는 "모델별"
--      권한/할당/사용량이었는데, 요구사항상 이제 "provider별"이어야 한다. 기존
--      모델별 행들을 provider(현재는 전부 ProviderID=1)로 합친다(권한은 OR, 할당은
--      "무제한 있으면 무제한 우선, 아니면 최댓값", 사용량은 SUM).
--   4) LLMTokenHistory/ChatSession — ProviderID(제공자)뿐 아니라 ModelID(실제 사용
--      모델)도 함께 기록/저장하도록 컬럼 추가 + 기존 값 백필.
--   5) 위 구조 변경에 맞춰 관련 RPC를 다시 만든다:
--      - nrm_rpc_admin_replace_llm_providers(모델 시드) → nrm_rpc_admin_replace_llm_models
--      - nrm_rpc_chat_prepare_turn: p_provider_id(모델) → p_model_id, provider는 LLMModel
--        을 통해 join으로 얻는다. 제공자(모델) 단위 DailyLimit/MonthlyLimit 체크 로직은
--        완전히 제거(새 LLMProvider 스키마에 그 컬럼 자체가 없음 — 요구사항).
--      - nrm_rpc_chat_finalize_turn: p_model_id 파라미터 추가(LLMTokenHistory에 ModelID
--        같이 기록).
--
-- 상세 설계 근거는 docs/supabase-tables/llm.md 참고.

-- ── 1) LLMProvider(모델 목록) → LLMModel 이름 변경 + PK 컬럼 이름 변경 ──────────────

ALTER TABLE public."LLMProvider" RENAME TO "LLMModel";
ALTER TABLE public."LLMModel" RENAME COLUMN "ProviderID" TO "ModelID";

-- ── 2) 새 LLMProvider(제공자) 테이블 생성 + 시드 ────────────────────────────────────

CREATE TABLE public."LLMProvider"
(
    "ProviderID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProviderName"  varchar NOT NULL,
    "ApiKey"        text NOT NULL,
    "RegDate"       timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMProvider"
IS 'LLM 제공자(ApiKey 소유자) — 정규화 후: 제공자 1개가 여러 LLMModel을 가질 수 있음';

COMMENT ON COLUMN public."LLMProvider"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."LLMProvider"."ProviderName"
IS '제공자명 (예: Google — Gemini API 소유자)';

COMMENT ON COLUMN public."LLMProvider"."ApiKey"
IS 'LLM API Key (이 제공자의 전체 모델이 공유)';

COMMENT ON COLUMN public."LLMProvider"."RegDate"
IS '등록일시';

-- 현재 유일한 provider: 기존 LLMModel(구 LLMProvider) 행들이 전부 같은 ApiKey를
-- 썼다는 전제(사용자 확인 사항) → 그중 하나를 그대로 가져와 시드.
INSERT INTO public."LLMProvider" ("ProviderID", "ProviderName", "ApiKey")
OVERRIDING SYSTEM VALUE
VALUES (
  1,
  'Google',
  (SELECT "ApiKey" FROM public."LLMModel" WHERE "ApiKey" IS NOT NULL AND "ApiKey" <> '' LIMIT 1)
);

SELECT setval(pg_get_serial_sequence('public."LLMProvider"', 'ProviderID'), 1, true);

-- RLS: SELECT만 anon/authenticated 허용, ApiKey는 컬럼 단위로 차단(기존 LLMProvider와 동일 패턴).
ALTER TABLE public."LLMProvider" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS llm_provider_v2_select_anon ON public."LLMProvider";
CREATE POLICY llm_provider_v2_select_anon
  ON public."LLMProvider" FOR SELECT TO anon, authenticated
  USING (true);

REVOKE SELECT ON public."LLMProvider" FROM anon, authenticated;
GRANT SELECT ("ProviderID", "ProviderName", "RegDate") ON public."LLMProvider" TO anon, authenticated;

-- ── 3) LLMModel: 신규 ProviderID(FK) 컬럼 추가 + 백필, 구 컬럼 제거 ──────────────────

ALTER TABLE public."LLMModel" ADD COLUMN "ProviderID" bigint;
UPDATE public."LLMModel" SET "ProviderID" = 1;
ALTER TABLE public."LLMModel" ALTER COLUMN "ProviderID" SET NOT NULL;

ALTER TABLE public."LLMModel" DROP COLUMN IF EXISTS "ApiKey";
ALTER TABLE public."LLMModel" DROP COLUMN IF EXISTS "DailyLimit";
ALTER TABLE public."LLMModel" DROP COLUMN IF EXISTS "MonthlyLimit";
-- ProviderName은 이제 LLMProvider와 중복(정규화) — join으로 얻는다.
ALTER TABLE public."LLMModel" DROP COLUMN IF EXISTS "ProviderName";

CREATE INDEX IF NOT EXISTS "IX_LLMModel_ProviderID" ON public."LLMModel" ("ProviderID");

COMMENT ON TABLE public."LLMModel"
IS 'LLM 모델 정보 (제공자별 개별 모델) — ApiKey/DailyLimit/MonthlyLimit은 LLMProvider로 이동(정규화)';

COMMENT ON COLUMN public."LLMModel"."ModelID"
IS 'LLM 모델 고유번호';

COMMENT ON COLUMN public."LLMModel"."ProviderID"
IS '이 모델을 제공하는 LLM 제공자 고유번호 (LLMProvider.ProviderID)';

-- LLMModel도 anon/authenticated에 이미 SELECT 정책이 있다(20260721120000, rename으로
-- 그대로 유지됨). ApiKey/DailyLimit/MonthlyLimit 컬럼이 없어졌으니 컬럼 단위 REVOKE/GRANT
-- 를 남길 컬럼 목록만 갱신한다(존재하지 않는 컬럼을 GRANT하면 에러이므로 재정의).
REVOKE SELECT ON public."LLMModel" FROM anon, authenticated;
GRANT SELECT (
  "ModelID",
  "ProviderID",
  "Type",
  "ModelName",
  "ModelDisplayName",
  "Version",
  "Description",
  "IsActive",
  "RegDate"
) ON public."LLMModel" TO anon, authenticated;

-- ── 4) LLMTokenHistory: ModelID 추가 + 백필, ProviderID를 provider 단위로 갱신 ────────

ALTER TABLE public."LLMTokenHistory" ADD COLUMN "ModelID" bigint;
UPDATE public."LLMTokenHistory" SET "ModelID" = "ProviderID";
UPDATE public."LLMTokenHistory" th
SET "ProviderID" = lm."ProviderID"
FROM public."LLMModel" lm
WHERE lm."ModelID" = th."ModelID";
ALTER TABLE public."LLMTokenHistory" ALTER COLUMN "ModelID" SET NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_LLMTokenHistory_ModelID" ON public."LLMTokenHistory" ("ModelID");

COMMENT ON COLUMN public."LLMTokenHistory"."ProviderID"
IS 'LLM 제공자 고유번호 (LLMProvider.ProviderID)';

COMMENT ON COLUMN public."LLMTokenHistory"."ModelID"
IS '실제 호출에 사용한 LLM 모델 고유번호 (LLMModel.ModelID)';

-- ── 5) ChatSession: ModelID 추가 + 백필, ProviderID를 provider 단위로 갱신 ───────────

ALTER TABLE public."ChatSession" ADD COLUMN "ModelID" bigint;
UPDATE public."ChatSession" SET "ModelID" = "ProviderID";
UPDATE public."ChatSession" cs
SET "ProviderID" = lm."ProviderID"
FROM public."LLMModel" lm
WHERE lm."ModelID" = cs."ModelID";
ALTER TABLE public."ChatSession" ALTER COLUMN "ModelID" SET NOT NULL;

COMMENT ON COLUMN public."ChatSession"."ProviderID"
IS 'LLM 제공자 고유번호 (LLMProvider.ProviderID)';

COMMENT ON COLUMN public."ChatSession"."ModelID"
IS '이 세션이 사용하는 LLM 모델 고유번호 (LLMModel.ModelID) — 세션 생성 시 고정, 이후 요청도 이 모델을 계속 사용';

-- ── 6) LLMUserPermission: 모델 단위 → provider 단위로 합치기 ─────────────────────────
-- 기존 "ProviderID"는 사실 모델 ID였다(구 LLMModel.ModelID와 동일 값) — LLMModel을
-- join해 실제 provider ID로 사상하고, 동일 (SerialNo, provider) 조합으로 GROUP BY해
-- 하나로 합친다. 승인 여부는 OR(하나라도 승인돼 있었으면 승인), 할당 토큰은
-- "무제한(0)이 하나라도 있으면 무제한, 아니면 그중 최댓값"으로 합친다.

CREATE TEMP TABLE tmp_llm_user_permission_v2 AS
SELECT
  p."SerialNo",
  lm."ProviderID",
  bool_or(p."IsApproved") AS "IsApproved",
  CASE WHEN bool_or(p."AllocatedToken" = 0) THEN 0 ELSE max(p."AllocatedToken") END AS "AllocatedToken",
  max(p."ApprovedDate") AS "ApprovedDate",
  min(p."RegDate") AS "RegDate"
FROM public."LLMUserPermission" p
JOIN public."LLMModel" lm ON lm."ModelID" = p."ProviderID"
GROUP BY p."SerialNo", lm."ProviderID";

TRUNCATE public."LLMUserPermission" RESTART IDENTITY;

INSERT INTO public."LLMUserPermission"
  ("SerialNo", "ProviderID", "IsApproved", "AllocatedToken", "ApprovedDate", "RegDate", "UpdateDate")
SELECT
  "SerialNo", "ProviderID", "IsApproved", "AllocatedToken", "ApprovedDate", coalesce("RegDate", now()), now()
FROM tmp_llm_user_permission_v2;

DROP TABLE tmp_llm_user_permission_v2;

COMMENT ON COLUMN public."LLMUserPermission"."ProviderID"
IS 'LLM 제공자 고유번호 (LLMProvider.ProviderID) — 모델 단위가 아니라 제공자 단위 승인/할당';

-- ── 7) LLMUserMonthlyAllocation: 모델 단위 → provider 단위로 합치기 ──────────────────

CREATE TEMP TABLE tmp_llm_alloc_v2 AS
SELECT
  a."SerialNo",
  lm."ProviderID",
  a."TargetMonth",
  CASE WHEN bool_or(a."AllocatedToken" = 0) THEN 0 ELSE max(a."AllocatedToken") END AS "AllocatedToken",
  max(a."UpdatedBySerialNo") AS "UpdatedBySerialNo",
  min(a."RegDate") AS "RegDate",
  max(a."UpdateDate") AS "UpdateDate"
FROM public."LLMUserMonthlyAllocation" a
JOIN public."LLMModel" lm ON lm."ModelID" = a."ProviderID"
GROUP BY a."SerialNo", lm."ProviderID", a."TargetMonth";

TRUNCATE public."LLMUserMonthlyAllocation" RESTART IDENTITY;

INSERT INTO public."LLMUserMonthlyAllocation"
  ("SerialNo", "ProviderID", "TargetMonth", "AllocatedToken", "UpdatedBySerialNo", "RegDate", "UpdateDate")
SELECT
  "SerialNo", "ProviderID", "TargetMonth", "AllocatedToken", "UpdatedBySerialNo",
  coalesce("RegDate", now()), coalesce("UpdateDate", now())
FROM tmp_llm_alloc_v2;

DROP TABLE tmp_llm_alloc_v2;

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."ProviderID"
IS 'LLM 제공자 고유번호 (LLMProvider.ProviderID) — 모델 단위가 아니라 제공자 단위 할당';

-- ── 8) LLMUserQuota: 모델 단위 → provider 단위로 합치기(토큰은 SUM) ──────────────────
-- 요구사항: 이 테이블은 (SerialNo, TargetMonth) 조합이 구조적으로 유일해야 한다
-- (제공자가 하나뿐인 지금은 결과적으로 동일). 기존에 모델별로 나뉘어 있던 행들을
-- provider 단위로 합치면서 토큰 사용량은 SUM한다.

CREATE TEMP TABLE tmp_llm_quota_v2 AS
SELECT
  q."SerialNo",
  lm."ProviderID",
  q."TargetMonth",
  sum(q."InputToken") AS "InputToken",
  sum(q."OutputToken") AS "OutputToken",
  sum(q."TotalToken") AS "TotalToken",
  min(q."RegDate") AS "RegDate",
  max(q."UpdateDate") AS "UpdateDate"
FROM public."LLMUserQuota" q
JOIN public."LLMModel" lm ON lm."ModelID" = q."ProviderID"
GROUP BY q."SerialNo", lm."ProviderID", q."TargetMonth";

TRUNCATE public."LLMUserQuota" RESTART IDENTITY;

INSERT INTO public."LLMUserQuota"
  ("SerialNo", "ProviderID", "TargetMonth", "InputToken", "OutputToken", "TotalToken", "RegDate", "UpdateDate")
SELECT
  "SerialNo", "ProviderID", "TargetMonth", "InputToken", "OutputToken", "TotalToken",
  coalesce("RegDate", now()), coalesce("UpdateDate", now())
FROM tmp_llm_quota_v2;

DROP TABLE tmp_llm_quota_v2;

COMMENT ON COLUMN public."LLMUserQuota"."ProviderID"
IS 'LLM 제공자 고유번호 (LLMProvider.ProviderID) — 모델 단위가 아니라 제공자 단위 누적. (SerialNo, TargetMonth) 조합은 항상 유일';

-- ── 9) 관리자 RPC: 모델 시드는 이제 LLMModel 대상 + ProviderID 필요 ──────────────────

DROP FUNCTION IF EXISTS public.nrm_rpc_admin_replace_llm_providers(text, jsonb);

CREATE OR REPLACE FUNCTION public.nrm_rpc_admin_replace_llm_models(
  p_caller_serial text,
  p_rows jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row jsonb;
  v_count integer := 0;
BEGIN
  IF NOT public.nrm_is_admin_caller(p_caller_serial) THEN
    RAISE EXCEPTION 'admin required';
  END IF;

  DELETE FROM public."LLMModel";

  FOR v_row IN SELECT * FROM jsonb_array_elements(p_rows)
  LOOP
    INSERT INTO public."LLMModel" (
      "ProviderID",
      "Type",
      "ModelName",
      "ModelDisplayName",
      "Version",
      "Description",
      "IsActive"
    )
    VALUES (
      (v_row->>'ProviderID')::bigint,
      v_row->>'Type',
      v_row->>'ModelName',
      v_row->>'ModelDisplayName',
      v_row->>'Version',
      NULLIF(v_row->>'Description', ''),
      COALESCE((v_row->>'IsActive')::boolean, false)
    );
    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$$;

COMMENT ON FUNCTION public.nrm_rpc_admin_replace_llm_models(text, jsonb)
IS 'admin: LLMModel 전체 교체 시드 (Gemini 모델 목록 등, 각 row는 ProviderID를 포함해야 함)';

GRANT EXECUTE ON FUNCTION public.nrm_rpc_admin_replace_llm_models(text, jsonb)
TO anon, authenticated;

-- ── 10) nrm_rpc_chat_prepare_turn: 모델 단위 파라미터/조회로 재작성 ──────────────────
-- 변경점:
--   - p_provider_id → p_model_id (앱이 실제로 고르는 건 "모델").
--   - LLMModel + LLMProvider를 join해 apiKey/providerName 등을 얻는다.
--   - 기존 세션을 이어받는 경우(p_session_id) 그 세션에 저장된 ModelID/ProviderID를
--     "그대로" 사용한다(클라이언트가 p_model_id를 잘못 보내도 세션의 원래 모델로
--     계속 요청되도록 서버가 최종 보정 — 요구사항: "해당 채팅세션에서는 해당 모델로
--     계속 요청할 수 있게").
--   - LLMProvider에 DailyLimit/MonthlyLimit 컬럼이 더 이상 없으므로, 제공자 단위
--     일일/월간 전체 사용자 합산 한도 체크(20260721140000에서 추가됐던 로직)는
--     완전히 제거한다.

-- Postgres는 CREATE OR REPLACE로 파라미터 "이름"만 바꾸는 것을 허용하지 않는다
-- (타입/개수가 같아도 "cannot change name of input parameter" 에러) — 명시적으로
-- 기존 시그니처를 먼저 지운다.
DROP FUNCTION IF EXISTS public.nrm_rpc_chat_prepare_turn(text, bigint, bigint, text, varchar, integer);

CREATE OR REPLACE FUNCTION public.nrm_rpc_chat_prepare_turn(
  p_serial_no text,
  p_model_id bigint,
  p_session_id bigint,
  p_content text,
  p_target_month varchar,
  p_history_limit integer DEFAULT 40
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session_id bigint;
  v_is_new boolean := false;
  v_clean text;
  v_title varchar;
  v_user_msg public."ChatMessage"%ROWTYPE;
  v_session_provider_id bigint;
  v_session_model_id bigint;
  v_effective_model_id bigint;
  v_model_id bigint;
  v_provider_id bigint;
  v_provider_name varchar;
  v_model_name varchar;
  v_model_display_name text;
  v_api_key text;
  v_is_active boolean;
  v_is_approved boolean;
  v_allocated_token bigint;
  v_quota_used bigint;
  v_history jsonb;
BEGIN
  IF p_session_id IS NOT NULL THEN
    SELECT "SessionID", "Title", "ProviderID", "ModelID"
    INTO v_session_id, v_title, v_session_provider_id, v_session_model_id
    FROM public."ChatSession"
    WHERE "SessionID" = p_session_id AND "SerialNo" = p_serial_no AND "IsDeleted" = false;
  END IF;

  -- 기존 세션이면 그 세션의 모델을 최종 사용(클라이언트 값보다 우선). 새 세션이면
  -- 클라이언트가 고른 모델을 그대로 쓴다.
  v_effective_model_id := COALESCE(v_session_model_id, p_model_id);

  IF v_session_id IS NULL THEN
    v_clean := trim(regexp_replace(coalesce(p_content, ''), '\s+', ' ', 'g'));
    IF v_clean = '' THEN
      v_title := '새 대화';
    ELSIF length(v_clean) > 28 THEN
      v_title := left(v_clean, 28) || '…';
    ELSE
      v_title := v_clean;
    END IF;

    SELECT "ProviderID" INTO v_provider_id FROM public."LLMModel" WHERE "ModelID" = v_effective_model_id;

    INSERT INTO public."ChatSession" ("SerialNo", "ProviderID", "ModelID", "Title")
    VALUES (p_serial_no, v_provider_id, v_effective_model_id, v_title)
    RETURNING "SessionID" INTO v_session_id;
    v_is_new := true;
  END IF;

  INSERT INTO public."ChatMessage" ("SessionID", "Role", "Content")
  VALUES (v_session_id, p_serial_no, p_content)
  RETURNING * INTO v_user_msg;

  UPDATE public."ChatSession" SET "UpdateDate" = now() WHERE "SessionID" = v_session_id;

  SELECT lm."ModelID", lm."ProviderID", lm."ModelName", lm."ModelDisplayName", lm."IsActive",
         lp."ProviderName", lp."ApiKey"
  INTO v_model_id, v_provider_id, v_model_name, v_model_display_name, v_is_active,
       v_provider_name, v_api_key
  FROM public."LLMModel" lm
  JOIN public."LLMProvider" lp ON lp."ProviderID" = lm."ProviderID"
  WHERE lm."ModelID" = v_effective_model_id;

  SELECT "IsApproved", "AllocatedToken"
  INTO v_is_approved, v_allocated_token
  FROM public."LLMUserPermission"
  WHERE "SerialNo" = p_serial_no AND "ProviderID" = v_provider_id;

  SELECT coalesce("TotalToken", 0) INTO v_quota_used
  FROM public."LLMUserQuota"
  WHERE "SerialNo" = p_serial_no AND "ProviderID" = v_provider_id AND "TargetMonth" = p_target_month;

  SELECT coalesce(jsonb_agg(jsonb_build_object('role', h."Role", 'content', h."Content") ORDER BY h."MessageID"), '[]'::jsonb)
  INTO v_history
  FROM (
    SELECT "MessageID", "Role", "Content"
    FROM public."ChatMessage"
    WHERE "SessionID" = v_session_id
      AND "Role" <> 'system'
      AND "MessageID" <> v_user_msg."MessageID"
    ORDER BY "MessageID" DESC
    LIMIT p_history_limit
  ) h;

  RETURN jsonb_build_object(
    'sessionId', v_session_id,
    'isNewSession', v_is_new,
    'title', v_title,
    'userMessage', to_jsonb(v_user_msg),
    'model', CASE WHEN v_model_id IS NULL THEN NULL ELSE jsonb_build_object(
      'modelId', v_model_id,
      'providerId', v_provider_id,
      'providerName', v_provider_name,
      'modelName', v_model_name,
      'modelDisplayName', v_model_display_name,
      'apiKey', v_api_key,
      'isActive', v_is_active
    ) END,
    'permission', CASE WHEN v_is_approved IS NULL THEN NULL ELSE jsonb_build_object(
      'isApproved', v_is_approved,
      'allocatedToken', v_allocated_token
    ) END,
    'quotaUsed', coalesce(v_quota_used, 0),
    'history', v_history
  );
END;
$$;

COMMENT ON FUNCTION public.nrm_rpc_chat_prepare_turn(text, bigint, bigint, text, varchar, integer)
IS 'AI Lab 채팅 1턴 준비: 세션 확보/생성 + 사용자 메시지 저장 + model(LLMModel+LLMProvider join)/permission(provider 단위)/quota(provider 단위)/history 일괄 조회 (service_role 전용, ApiKey 포함 반환). 기존 세션이면 세션에 저장된 모델을 최우선 사용';

GRANT EXECUTE ON FUNCTION public.nrm_rpc_chat_prepare_turn(text, bigint, bigint, text, varchar, integer)
TO service_role;

-- ── 11) nrm_rpc_chat_finalize_turn: p_model_id 파라미터 추가 ─────────────────────────

DROP FUNCTION IF EXISTS public.nrm_rpc_chat_finalize_turn(bigint, varchar, text, integer, integer, integer, text, bigint, boolean, boolean);

CREATE OR REPLACE FUNCTION public.nrm_rpc_chat_finalize_turn(
  p_session_id bigint,
  p_role varchar,
  p_content text,
  p_input_token integer,
  p_output_token integer,
  p_total_token integer,
  p_serial_no text,
  p_provider_id bigint,
  p_model_id bigint,
  p_record_history boolean,
  p_is_success boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_msg public."ChatMessage"%ROWTYPE;
BEGIN
  INSERT INTO public."ChatMessage" ("SessionID", "Role", "Content", "InputToken", "OutputToken", "TotalToken")
  VALUES (
    p_session_id,
    p_role,
    p_content,
    coalesce(p_input_token, 0),
    coalesce(p_output_token, 0),
    coalesce(p_total_token, 0)
  )
  RETURNING * INTO v_msg;

  UPDATE public."ChatSession" SET "UpdateDate" = now() WHERE "SessionID" = p_session_id;

  IF p_record_history THEN
    INSERT INTO public."LLMTokenHistory" ("SerialNo", "ProviderID", "ModelID", "InputToken", "OutputToken", "TotalToken", "isSuccess")
    VALUES (
      p_serial_no,
      p_provider_id,
      p_model_id,
      coalesce(p_input_token, 0),
      coalesce(p_output_token, 0),
      coalesce(p_total_token, 0),
      p_is_success
    );
  END IF;

  RETURN to_jsonb(v_msg);
END;
$$;

COMMENT ON FUNCTION public.nrm_rpc_chat_finalize_turn(bigint, varchar, text, integer, integer, integer, text, bigint, bigint, boolean, boolean)
IS 'AI Lab 채팅 1턴 종료: 응답(assistant/system) 메시지 저장 + 세션 갱신 + (요청 시도한 경우만) LLMTokenHistory(ProviderID+ModelID) 기록 (service_role 전용)';

GRANT EXECUTE ON FUNCTION public.nrm_rpc_chat_finalize_turn(bigint, varchar, text, integer, integer, integer, text, bigint, bigint, boolean, boolean)
TO service_role;
