-- LLM 제공자·사용자 월간 쿼터·호출 이력
-- 원격에 이미 수동 생성된 경우 이 파일은 스킵한다.
-- 컬럼 의미 SSOT: docs/supabase-tables/llm.md

CREATE TABLE IF NOT EXISTS public."LLMProvider"
(
    "ProviderID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProviderName"  varchar NOT NULL,
    "ModelName"     varchar NOT NULL,
    "ApiKey"        text NOT NULL,
    "IsActive"      boolean NOT NULL DEFAULT true,
    "DailyLimit"    bigint NOT NULL DEFAULT 0,
    "MonthlyLimit"  bigint NOT NULL DEFAULT 0,
    "RegDate"       timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMProvider"
IS 'LLM 제공자 및 모델 정보';

COMMENT ON COLUMN public."LLMProvider"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."LLMProvider"."ProviderName"
IS 'LLM 제공자명 (Gemini, OpenAI, Claude 등)';

COMMENT ON COLUMN public."LLMProvider"."ModelName"
IS '사용할 모델명 (gemini-2.5-flash 등)';

COMMENT ON COLUMN public."LLMProvider"."ApiKey"
IS 'LLM API Key';

COMMENT ON COLUMN public."LLMProvider"."IsActive"
IS '사용 여부';

COMMENT ON COLUMN public."LLMProvider"."DailyLimit"
IS '일일 토큰 제한 (0은 제한 없음)';

COMMENT ON COLUMN public."LLMProvider"."MonthlyLimit"
IS '월간 토큰 제한 (0은 제한 없음)';

COMMENT ON COLUMN public."LLMProvider"."RegDate"
IS '등록일시';

CREATE TABLE IF NOT EXISTS public."LLMUserQuota"
(
    "QuotaID"       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SerialNo"      bigint NOT NULL,
    "ProviderID"    bigint NOT NULL,
    "TargetMonth"   varchar(6) NOT NULL,
    "InputToken"    bigint NOT NULL DEFAULT 0,
    "OutputToken"   bigint NOT NULL DEFAULT 0,
    "TotalToken"    bigint NOT NULL DEFAULT 0,
    "RegDate"       timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMUserQuota"
IS '사용자 월별 LLM 토큰 사용량';

COMMENT ON COLUMN public."LLMUserQuota"."QuotaID"
IS '사용량 고유번호';

COMMENT ON COLUMN public."LLMUserQuota"."SerialNo"
IS '사용자 일련번호';

COMMENT ON COLUMN public."LLMUserQuota"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."LLMUserQuota"."TargetMonth"
IS '사용월 (YYYYMM)';

COMMENT ON COLUMN public."LLMUserQuota"."InputToken"
IS '누적 입력 토큰(LLM에게 보낸 토큰 수)';

COMMENT ON COLUMN public."LLMUserQuota"."OutputToken"
IS '누적 출력 토큰(LLM이 생성한 토큰 수)';

COMMENT ON COLUMN public."LLMUserQuota"."TotalToken"
IS '누적 전체 토큰(InputToken + OutputToken)';

COMMENT ON COLUMN public."LLMUserQuota"."RegDate"
IS '생성일시';

COMMENT ON COLUMN public."LLMUserQuota"."UpdateDate"
IS '최종 수정일시';

CREATE UNIQUE INDEX IF NOT EXISTS "UX_LLMUserQuota"
ON public."LLMUserQuota"
(
    "SerialNo",
    "ProviderID",
    "TargetMonth"
);

CREATE TABLE IF NOT EXISTS public."LLMTokenHistory"
(
    "HistoryID"     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SerialNo"      bigint NOT NULL,
    "ProviderID"    bigint NOT NULL,
    "InputToken"    integer NOT NULL DEFAULT 0,
    "OutputToken"   integer NOT NULL DEFAULT 0,
    "TotalToken"    integer NOT NULL DEFAULT 0,
    "RegDate"       timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMTokenHistory"
IS 'LLM 호출 이력';

COMMENT ON COLUMN public."LLMTokenHistory"."HistoryID"
IS 'LLM 호출 이력 고유번호';

COMMENT ON COLUMN public."LLMTokenHistory"."SerialNo"
IS '사용자 일련번호';

COMMENT ON COLUMN public."LLMTokenHistory"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."LLMTokenHistory"."InputToken"
IS '입력 토큰(LLM에게 보낸 토큰 수)';

COMMENT ON COLUMN public."LLMTokenHistory"."OutputToken"
IS '출력 토큰(LLM이 생성한 토큰 수)';

COMMENT ON COLUMN public."LLMTokenHistory"."TotalToken"
IS '전체 토큰(InputToken + OutputToken)';

COMMENT ON COLUMN public."LLMTokenHistory"."RegDate"
IS '호출 일시';

CREATE INDEX IF NOT EXISTS "IX_LLMTokenHistory_SerialNo"
ON public."LLMTokenHistory" ("SerialNo");

CREATE INDEX IF NOT EXISTS "IX_LLMTokenHistory_RegDate"
ON public."LLMTokenHistory" ("RegDate");
