-- 관리자페이지 「AI토큰 할당」 — 월별 사용자×제공자 토큰 할당 이력.
-- LLMUserPermission.AllocatedToken은 "현재 적용 중인 값"(채팅 요청 시 실시간 체크 기준)이고,
-- 이 테이블은 그 값이 "어느 달에 얼마로 설정됐는지" 조회용 이력이다(월별 조회 UI 전용, 실시간 로직에는 관여하지 않음).
-- 컬럼 의미 SSOT: docs/supabase-tables/llm.md

CREATE TABLE IF NOT EXISTS public."LLMUserMonthlyAllocation"
(
    "AllocationID"      bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SerialNo"          varchar NOT NULL,
    "ProviderID"        bigint NOT NULL,
    "TargetMonth"       varchar(6) NOT NULL,
    "AllocatedToken"    bigint NOT NULL DEFAULT 0,
    "UpdatedBySerialNo" varchar,
    "RegDate"           timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_LLMUserMonthlyAllocation" PRIMARY KEY ("AllocationID", "SerialNo")
);

COMMENT ON TABLE public."LLMUserMonthlyAllocation"
IS '관리자페이지 AI토큰 할당 — 월별(YYYYMM) 사용자×제공자 토큰 할당량 설정 이력(조회용, 실시간 한도 체크는 LLMUserPermission.AllocatedToken 기준)';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."AllocationID"
IS '할당 이력 고유번호';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."SerialNo"
IS '사용자 일련번호 (앱 SerialNo 원문)';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."ProviderID"
IS 'LLM 제공자 고유번호';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."TargetMonth"
IS '할당 대상월 (YYYYMM)';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."AllocatedToken"
IS '해당 월에 설정된 할당 토큰 (0 = 무제한)';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."UpdatedBySerialNo"
IS '설정을 실행한 관리자 SerialNo (항상 admin, 감사용)';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."RegDate"
IS '최초 생성일시';

COMMENT ON COLUMN public."LLMUserMonthlyAllocation"."UpdateDate"
IS '최종 수정일시';

CREATE UNIQUE INDEX IF NOT EXISTS "UX_LLMUserMonthlyAllocation"
ON public."LLMUserMonthlyAllocation"
(
    "SerialNo",
    "ProviderID",
    "TargetMonth"
);

ALTER TABLE public."LLMUserMonthlyAllocation" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS llm_user_monthly_allocation_select_anon ON public."LLMUserMonthlyAllocation";
CREATE POLICY llm_user_monthly_allocation_select_anon
  ON public."LLMUserMonthlyAllocation" FOR SELECT TO anon, authenticated
  USING (true);

-- 관리자: 특정 사용자×제공자×월의 할당량/승인여부를 설정한다.
-- LLMUserPermission(실시간 적용값)과 LLMUserMonthlyAllocation(그 달 조회 이력)을 한 트랜잭션에서 함께 갱신한다.
CREATE OR REPLACE FUNCTION public.nrm_rpc_admin_set_llm_user_token_allocation(
  p_caller_serial varchar,
  p_serial_no varchar,
  p_provider_id bigint,
  p_target_month varchar,
  p_allocated_token bigint,
  p_is_approved boolean
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_serial_no varchar := trim(coalesce(p_serial_no, ''));
  v_target_month varchar := trim(coalesce(p_target_month, ''));
  v_allocated_token bigint := coalesce(p_allocated_token, 0);
  v_is_approved boolean := coalesce(p_is_approved, false);
BEGIN
  IF NOT public.nrm_is_admin_caller(p_caller_serial) THEN
    RAISE EXCEPTION 'admin required';
  END IF;
  IF v_serial_no = '' THEN
    RAISE EXCEPTION 'SerialNo required';
  END IF;
  IF p_provider_id IS NULL THEN
    RAISE EXCEPTION 'ProviderID required';
  END IF;
  IF length(v_target_month) <> 6 THEN
    RAISE EXCEPTION 'TargetMonth(YYYYMM) required';
  END IF;
  IF v_allocated_token < 0 THEN
    RAISE EXCEPTION 'AllocatedToken must be >= 0';
  END IF;

  INSERT INTO public."LLMUserPermission" (
    "SerialNo", "ProviderID", "IsApproved", "AllocatedToken", "ApprovedDate", "RegDate", "UpdateDate"
  )
  VALUES (
    v_serial_no, p_provider_id, v_is_approved, v_allocated_token,
    CASE WHEN v_is_approved THEN now() ELSE NULL END,
    now(), now()
  )
  ON CONFLICT ("SerialNo", "ProviderID") DO UPDATE SET
    "IsApproved" = EXCLUDED."IsApproved",
    "AllocatedToken" = EXCLUDED."AllocatedToken",
    "ApprovedDate" = CASE WHEN EXCLUDED."IsApproved" THEN now() ELSE NULL END,
    "UpdateDate" = now();

  INSERT INTO public."LLMUserMonthlyAllocation" (
    "SerialNo", "ProviderID", "TargetMonth", "AllocatedToken", "UpdatedBySerialNo", "RegDate", "UpdateDate"
  )
  VALUES (
    v_serial_no, p_provider_id, v_target_month, v_allocated_token, trim(p_caller_serial), now(), now()
  )
  ON CONFLICT ("SerialNo", "ProviderID", "TargetMonth") DO UPDATE SET
    "AllocatedToken" = EXCLUDED."AllocatedToken",
    "UpdatedBySerialNo" = EXCLUDED."UpdatedBySerialNo",
    "UpdateDate" = now();
END;
$$;

COMMENT ON FUNCTION public.nrm_rpc_admin_set_llm_user_token_allocation(varchar, varchar, bigint, varchar, bigint, boolean)
IS 'admin: LLMUserPermission(실시간) + LLMUserMonthlyAllocation(월별 이력) 동시 upsert — AI토큰 할당 화면 저장';

GRANT EXECUTE ON FUNCTION public.nrm_rpc_admin_set_llm_user_token_allocation(varchar, varchar, bigint, varchar, bigint, boolean)
TO anon, authenticated;
