-- AI Lab LLM 호출 시도별 진단 로그 (Gemini HTTP/빈응답/타임아웃 원인 추적).
-- Edge Function(llm-chat-send)이 service_role로 INSERT. 앱/anon은 SELECT만.

CREATE TABLE IF NOT EXISTS public."LLMCallAttemptLog"
(
    "LogID"              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RequestID"          uuid NOT NULL,
    "SerialNo"           varchar NOT NULL,
    "SessionID"          bigint NULL,
    "ModelID"            bigint NOT NULL,
    "ModelName"          varchar NOT NULL,
    "AttemptIndex"       integer NOT NULL,
    "AttemptLabel"       varchar NOT NULL,
    "WithSearch"         boolean NOT NULL DEFAULT false,
    "HttpStatus"         integer NULL,
    "Ok"                 boolean NOT NULL DEFAULT false,
    "ErrorKind"          varchar NULL,
    "ErrorMessage"       text NULL,
    "FinishReason"       varchar NULL,
    "BlockReason"        varchar NULL,
    "GroundedQueryCount" integer NOT NULL DEFAULT 0,
    "ElapsedMs"          integer NOT NULL DEFAULT 0,
    "MaxOutputTokens"    integer NULL,
    "UserMessagePreview" varchar NULL,
    "NeedsWebSearch"     boolean NOT NULL DEFAULT false,
    "RegDate"            timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMCallAttemptLog"
IS 'llm-chat-send Gemini 시도별 진단 로그 — Dashboard Edge Logs 없이도 DB에서 실패 원인 확인';

COMMENT ON COLUMN public."LLMCallAttemptLog"."RequestID"
IS 'Edge 요청 UUID (앱 ailab.llmSend requestId와 동일)';

COMMENT ON COLUMN public."LLMCallAttemptLog"."AttemptLabel"
IS 'search / plain / plain_retry 등 시도 라벨';

COMMENT ON COLUMN public."LLMCallAttemptLog"."WithSearch"
IS 'google_search tool 포함 여부';

COMMENT ON COLUMN public."LLMCallAttemptLog"."HttpStatus"
IS 'Gemini HTTP status (네트워크 예외면 NULL)';

COMMENT ON COLUMN public."LLMCallAttemptLog"."ErrorMessage"
IS '실패 메시지(최대 약 500자). ApiKey·전문 대화 미포함';

COMMENT ON COLUMN public."LLMCallAttemptLog"."NeedsWebSearch"
IS '서버 휴리스틱 messageLikelyNeedsWebSearch 결과';

CREATE INDEX IF NOT EXISTS "IX_LLMCallAttemptLog_RequestID"
ON public."LLMCallAttemptLog" ("RequestID");

CREATE INDEX IF NOT EXISTS "IX_LLMCallAttemptLog_RegDate"
ON public."LLMCallAttemptLog" ("RegDate" DESC);

ALTER TABLE public."LLMCallAttemptLog" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS llm_call_attempt_log_select_anon ON public."LLMCallAttemptLog";
CREATE POLICY llm_call_attempt_log_select_anon
  ON public."LLMCallAttemptLog" FOR SELECT TO anon, authenticated
  USING (true);

-- INSERT는 service_role만 (Edge). anon/authenticated에 INSERT 정책 없음.
