-- AI Lab 빈 화면 추천 질문 (카테고리 + 프롬프트)
-- SSOT: docs/supabase-tables/llm.md

CREATE TABLE IF NOT EXISTS public."LLMAiLabSuggestionCategory"
(
    "CategoryID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryCode" varchar NOT NULL,
    "Title"        varchar NOT NULL,
    -- plain | web_search | vector_plain | vector_web
    "AnswerMode"   varchar NOT NULL,
    "SortOrder"    integer NOT NULL DEFAULT 0,
    "IsActive"     boolean NOT NULL DEFAULT true,
    "RegDate"      timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "UQ_LLMAiLabSuggestionCategory_Code" UNIQUE ("CategoryCode"),
    CONSTRAINT "CK_LLMAiLabSuggestionCategory_AnswerMode"
      CHECK ("AnswerMode" IN ('plain', 'web_search', 'vector_plain', 'vector_web'))
);

COMMENT ON TABLE public."LLMAiLabSuggestionCategory"
IS 'AI Lab 빈 화면 추천 질문 카테고리';

COMMENT ON COLUMN public."LLMAiLabSuggestionCategory"."CategoryCode"
IS '코드: music_recommend | upcoming_release | ai_personal_web | user_personal | app_intro';

COMMENT ON COLUMN public."LLMAiLabSuggestionCategory"."AnswerMode"
IS 'plain=일반 / web_search=인터넷검색 / vector_plain=벡터만 / vector_web=벡터+인터넷';

COMMENT ON COLUMN public."LLMAiLabSuggestionCategory"."SortOrder"
IS '카테고리 표시·선정 우선순위(오름차순)';

CREATE TABLE IF NOT EXISTS public."LLMAiLabSuggestionPrompt"
(
    "PromptID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryID"  bigint NOT NULL REFERENCES public."LLMAiLabSuggestionCategory" ("CategoryID") ON DELETE CASCADE,
    "PromptText"  text NOT NULL,
    "SortOrder"   integer NOT NULL DEFAULT 0,
    "IsActive"    boolean NOT NULL DEFAULT true,
    "RegDate"     timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMAiLabSuggestionPrompt"
IS 'AI Lab 추천 질문 문구(카테고리별 여러 개)';

COMMENT ON COLUMN public."LLMAiLabSuggestionPrompt"."PromptText"
IS '칩에 보이는 질문 전문(이모지 포함 가능). 탭 시 그대로 전송';

CREATE INDEX IF NOT EXISTS "IX_LLMAiLabSuggestionPrompt_Category_Active"
ON public."LLMAiLabSuggestionPrompt" ("CategoryID", "IsActive", "SortOrder", "PromptID");

ALTER TABLE public."LLMAiLabSuggestionCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LLMAiLabSuggestionPrompt" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS llm_ailab_suggestion_category_select ON public."LLMAiLabSuggestionCategory";
CREATE POLICY llm_ailab_suggestion_category_select
  ON public."LLMAiLabSuggestionCategory" FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS llm_ailab_suggestion_prompt_select ON public."LLMAiLabSuggestionPrompt";
CREATE POLICY llm_ailab_suggestion_prompt_select
  ON public."LLMAiLabSuggestionPrompt" FOR SELECT TO anon, authenticated
  USING (true);

-- ── 시드: 카테고리 ──────────────────────────────────────────────────────────
INSERT INTO public."LLMAiLabSuggestionCategory"
  ("CategoryCode", "Title", "AnswerMode", "SortOrder", "IsActive")
VALUES
  ('music_recommend', '음악 추천', 'plain', 10, true),
  ('upcoming_release', '발매 예정곡', 'web_search', 20, true),
  ('ai_personal_web', 'AI 활용', 'vector_web', 30, true),
  ('user_personal', '사용자 맞춤', 'vector_plain', 40, true),
  ('app_intro', '앱 소개', 'plain', 50, true)
ON CONFLICT ("CategoryCode") DO UPDATE SET
  "Title" = EXCLUDED."Title",
  "AnswerMode" = EXCLUDED."AnswerMode",
  "SortOrder" = EXCLUDED."SortOrder",
  "IsActive" = EXCLUDED."IsActive",
  "UpdateDate" = now();

-- ── 시드: 프롬프트 (재실행 시 카테고리별 기존 행 교체) ─────────────────────
DELETE FROM public."LLMAiLabSuggestionPrompt" p
USING public."LLMAiLabSuggestionCategory" c
WHERE p."CategoryID" = c."CategoryID"
  AND c."CategoryCode" IN (
    'music_recommend', 'upcoming_release', 'ai_personal_web', 'user_personal', 'app_intro'
  );

INSERT INTO public."LLMAiLabSuggestionPrompt" ("CategoryID", "PromptText", "SortOrder")
SELECT c."CategoryID", v."PromptText", v."SortOrder"
FROM public."LLMAiLabSuggestionCategory" c
JOIN (
  VALUES
    -- 음악 추천 (plain)
    ('music_recommend', E'🔥 언제들어도 안 질리는 노래 추천', 10),
    ('music_recommend', E'🎵 숨겨진 명곡을 추천해줘', 20),
    ('music_recommend', E'🎵 숨겨진 K-Pop을 추천해줘', 30),
    ('music_recommend', E'🎵 숨겨진 팝송을 추천해줘', 40),
    ('music_recommend', E'🎙️ 운동할때 들을 노래 추천해줘', 50),
    ('music_recommend', E'😎 드라이브할 때 들을 노래 추천해줘', 60),
    ('music_recommend', E'☕ 공부할 때 집중되는 노래 추천해줘', 70),
    -- 발매 예정곡 (web_search)
    ('upcoming_release', E'🤖 AI로 최신 노래 찾아줘', 10),
    ('upcoming_release', E'⏰ 이번 달 기대되는 신곡 추천해줘', 20),
    ('upcoming_release', E'🎵 미리 담아둘 신곡 추천해줘', 30),
    ('upcoming_release', E'🎶 최근 발매곡 중 내 취향 추천해줘', 40),
    ('upcoming_release', E'💡 최근 발매된 K-Pop을 추천해줘', 50),
    ('upcoming_release', E'💡 최근 발매된 팝송을 추천해줘', 60),
    ('upcoming_release', E'📊 요즘 하입된 노래가 뭐가있어?', 70),
    ('upcoming_release', E'🎙️ 운동할때 들을 최신 노래 추천해줘', 80),
    ('upcoming_release', E'😎 드라이브할 때 들을 최신 노래 추천', 90),
    ('upcoming_release', E'☕ 공부할 때 집중되는 최신 노래 추천', 100),
    ('upcoming_release', E'📱 최근 바이럴된 노래를 추천해줘', 110),
    -- AI 활용 (vector_web) — 앱 플래그 켜기 전까지 UI 미노출
    ('ai_personal_web', E'📅 곧 나올 내 취향 신곡 알려줘', 10),
    ('ai_personal_web', E'🎤 내가 좋아하는 가수 발매 예정곡 있어?', 20),
    ('ai_personal_web', E'✨ 요즘 내 스타일 노래 뭐 있어?', 30),
    ('ai_personal_web', E'💿 내가 좋아할 만한 최근 K-Pop을 찾아줘', 40),
    ('ai_personal_web', E'💿 내가 좋아할 만한 최근 팝송을 찾아줘', 50),
    ('ai_personal_web', E'🔄 내가 몰랐던 새로운 취향의 최신 노래를 추천해줘', 60),
    -- 사용자 맞춤 (vector_plain)
    ('user_personal', E'❤️ 내가 자주 듣는 스타일 분석해줘', 10),
    ('user_personal', E'📈 내 음악 취향 한 줄로 알려줘', 20),
    ('user_personal', E'🎯 다운로드 기록을 분석해줘', 30),
    ('user_personal', E'🎧 내 취향으로 노래 추천해줘', 40),
    ('user_personal', E'💿 내가 좋아할 만한 K-Pop을 찾아줘', 50),
    ('user_personal', E'💿 내가 좋아할 만한 팝송을 찾아줘', 60),
    ('user_personal', E'🔄 내가 몰랐던 새로운 취향의 노래를 추천해줘', 70),
    -- 앱 소개 (plain)
    ('app_intro', E'❓ 이 앱은 뭐가 특별해?', 10),
    ('app_intro', E'🚀 이 앱의 기능들이 뭐가 있어?', 20),
    ('app_intro', E'🎵 이 앱 활용 꿀팁 알려줘', 30),
    ('app_intro', E'💎 이 앱의 숨겨진 기능 알려줘', 40)
) AS v("CategoryCode", "PromptText", "SortOrder")
  ON c."CategoryCode" = v."CategoryCode";
