-- Discover: 큐레이션 음악 목록 (엑셀 musicList → nrm_music_list)

CREATE TABLE public.nrm_music_list (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rank INT NOT NULL,
  year INT NOT NULL,
  artist TEXT NOT NULL,
  title TEXT NOT NULL,
  album TEXT NOT NULL DEFAULT '',
  genre TEXT NOT NULL,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX nrm_music_list_year_rank_idx
  ON public.nrm_music_list (year DESC, rank ASC, id ASC);

CREATE INDEX nrm_music_list_genre_year_rank_idx
  ON public.nrm_music_list (genre, year DESC, rank ASC, id ASC);

COMMENT ON TABLE public.nrm_music_list IS 'Discover 큐레이션 음악 (엑셀 musicList 포맷)';
COMMENT ON COLUMN public.nrm_music_list.rank IS '엑셀 순위 (연도·장르 내)';
COMMENT ON COLUMN public.nrm_music_list.year IS '엑셀 연도';
COMMENT ON COLUMN public.nrm_music_list.title IS '엑셀 노래';

ALTER TABLE public.nrm_music_list ENABLE ROW LEVEL SECURITY;

CREATE POLICY nrm_music_list_select_anon
  ON public.nrm_music_list FOR SELECT TO anon, authenticated
  USING (true);

-- 장르 목록 (Discover 필터)
CREATE OR REPLACE FUNCTION public.nrm_rpc_music_list_genres()
RETURNS TABLE (genre text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT DISTINCT m.genre FROM public.nrm_music_list m ORDER BY m.genre;
$$;

GRANT EXECUTE ON FUNCTION public.nrm_rpc_music_list_genres() TO anon, authenticated;
