-- AI Lab 전역 시스템 프롬프트 (모든 LLM 모델에 동일 적용).
-- 관리자페이지 「AI 시스템 프롬프트 설정」에서 CRUD.
-- 컬럼 의미 SSOT: docs/supabase-tables/llm.md

CREATE TABLE IF NOT EXISTS public."LLMSystemPrompt"
(
    "PromptID"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title"               varchar NOT NULL,
    "Content"             text NOT NULL,
    "SortOrder"           integer NOT NULL DEFAULT 0,
    "IsActive"            boolean NOT NULL DEFAULT true,
    "UpdatedBySerialNo"   varchar,
    "RegDate"             timestamptz NOT NULL DEFAULT now(),
    "UpdateDate"          timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."LLMSystemPrompt"
IS 'AI Lab 전역 시스템 프롬프트 — 활성 항목이 모든 모델 채팅에 동일 적용';

COMMENT ON COLUMN public."LLMSystemPrompt"."PromptID"
IS '시스템 프롬프트 고유번호';

COMMENT ON COLUMN public."LLMSystemPrompt"."Title"
IS '관리자 UI 표시용 제목';

COMMENT ON COLUMN public."LLMSystemPrompt"."Content"
IS '실제 시스템 프롬프트 본문 (모델에 전달)';

COMMENT ON COLUMN public."LLMSystemPrompt"."SortOrder"
IS '적용 순서 (오름차순, 같으면 PromptID 오름차순)';

COMMENT ON COLUMN public."LLMSystemPrompt"."IsActive"
IS '활성 여부 — false면 채팅에 미적용';

COMMENT ON COLUMN public."LLMSystemPrompt"."UpdatedBySerialNo"
IS '마지막 저장 관리자 SerialNo (감사용)';

COMMENT ON COLUMN public."LLMSystemPrompt"."RegDate"
IS '등록일시';

COMMENT ON COLUMN public."LLMSystemPrompt"."UpdateDate"
IS '최종 수정일시';

CREATE INDEX IF NOT EXISTS "IX_LLMSystemPrompt_Active_Sort"
ON public."LLMSystemPrompt" ("IsActive", "SortOrder", "PromptID");

ALTER TABLE public."LLMSystemPrompt" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS llm_system_prompt_select_anon ON public."LLMSystemPrompt";
CREATE POLICY llm_system_prompt_select_anon
  ON public."LLMSystemPrompt" FOR SELECT TO anon, authenticated
  USING (true);

-- 관리자: 시스템 프롬프트 upsert (p_prompt_id NULL이면 INSERT)
CREATE OR REPLACE FUNCTION public.nrm_rpc_admin_upsert_llm_system_prompt(
  p_caller_serial varchar,
  p_prompt_id bigint,
  p_title varchar,
  p_content text,
  p_sort_order integer,
  p_is_active boolean
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_title varchar := trim(coalesce(p_title, ''));
  v_content text := trim(coalesce(p_content, ''));
  v_sort integer := coalesce(p_sort_order, 0);
  v_active boolean := coalesce(p_is_active, true);
  v_id bigint;
BEGIN
  IF NOT public.nrm_is_admin_caller(p_caller_serial) THEN
    RAISE EXCEPTION 'admin required';
  END IF;
  IF v_title = '' THEN
    RAISE EXCEPTION 'Title required';
  END IF;
  IF v_content = '' THEN
    RAISE EXCEPTION 'Content required';
  END IF;

  IF p_prompt_id IS NULL THEN
    INSERT INTO public."LLMSystemPrompt" (
      "Title", "Content", "SortOrder", "IsActive", "UpdatedBySerialNo", "RegDate", "UpdateDate"
    )
    VALUES (
      v_title, v_content, v_sort, v_active, trim(p_caller_serial), now(), now()
    )
    RETURNING "PromptID" INTO v_id;
  ELSE
    UPDATE public."LLMSystemPrompt"
    SET
      "Title" = v_title,
      "Content" = v_content,
      "SortOrder" = v_sort,
      "IsActive" = v_active,
      "UpdatedBySerialNo" = trim(p_caller_serial),
      "UpdateDate" = now()
    WHERE "PromptID" = p_prompt_id
    RETURNING "PromptID" INTO v_id;

    IF v_id IS NULL THEN
      RAISE EXCEPTION 'PromptID not found';
    END IF;
  END IF;

  RETURN v_id;
END;
$$;

COMMENT ON FUNCTION public.nrm_rpc_admin_upsert_llm_system_prompt(varchar, bigint, varchar, text, integer, boolean)
IS 'admin: LLMSystemPrompt INSERT/UPDATE — AI 시스템 프롬프트 설정';

GRANT EXECUTE ON FUNCTION public.nrm_rpc_admin_upsert_llm_system_prompt(varchar, bigint, varchar, text, integer, boolean)
TO anon, authenticated;

-- 관리자: 시스템 프롬프트 삭제
CREATE OR REPLACE FUNCTION public.nrm_rpc_admin_delete_llm_system_prompt(
  p_caller_serial varchar,
  p_prompt_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.nrm_is_admin_caller(p_caller_serial) THEN
    RAISE EXCEPTION 'admin required';
  END IF;
  IF p_prompt_id IS NULL THEN
    RAISE EXCEPTION 'PromptID required';
  END IF;

  DELETE FROM public."LLMSystemPrompt" WHERE "PromptID" = p_prompt_id;
END;
$$;

COMMENT ON FUNCTION public.nrm_rpc_admin_delete_llm_system_prompt(varchar, bigint)
IS 'admin: LLMSystemPrompt DELETE — AI 시스템 프롬프트 설정';

GRANT EXECUTE ON FUNCTION public.nrm_rpc_admin_delete_llm_system_prompt(varchar, bigint)
TO anon, authenticated;
