-- TrackHistory: 다운로드/가사생성(번역지원)/가사삭제/노래삭제/메타데이터수정 이력.
-- History 탭이 이 테이블을 조회해 리스트를 그린다 (로컬 AsyncStorage 활동기록과는 별개로 병행 기록).
-- PK는 (ID, SerialNo) 복합 — LLMTokenHistory 등 기존 *History 테이블과 동일한 관례.
-- Metadata* 컬럼(Title/Artist/.../AlbumCoverPath/Lyrics)은 이벤트 시점에 알 수 있는 만큼만 채우고,
-- 모르면 NULL을 허용한다(예: 다운로드 실패 행은 대부분 NULL).
-- 향후 Lyrics 임베딩용 벡터 컬럼을 추가할 계획이 있으나 이번 마이그레이션에는 포함하지 않는다.

CREATE TABLE IF NOT EXISTS public."TrackHistory"
(
    "ID"              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SerialNo"        varchar NOT NULL,
    "Kind"            varchar NOT NULL,
    "Platform"        varchar,
    "FileName"        text,
    "AudioUri"        text,
    "Title"           text,
    "Artist"          text,
    "Album"           text,
    "AlbumArtist"     text,
    "Genre"           text,
    "ReleaseDate"     varchar,
    "TrackNumber"     varchar,
    "DiscNumber"      varchar,
    "Composer"        text,
    "Bpm"             varchar,
    "Copyright"       text,
    "Website"         text,
    "Producer"        text,
    "Remixer"         text,
    "Lyrics"          text,
    "LyricsMode"      varchar,
    "AlbumCoverPath"  text,
    "FailReason"      text,
    "IsSuccess"       boolean NOT NULL DEFAULT true,
    "DownloadDate"    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_TrackHistory" PRIMARY KEY ("ID", "SerialNo"),
    CONSTRAINT "CK_TrackHistory_Kind" CHECK ("Kind" IN (
        'down',              -- 노래 다운로드 성공
        'downFail',          -- 노래 다운로드 실패
        'del',                -- 노래(트랙) 삭제
        'lyrics',             -- 가사 생성 성공(번역 없음)
        'lyricsFail',        -- 가사 생성 실패
        'delLyrics',         -- 가사 제거
        'transdLyrics',      -- 가사 생성/추가 성공(번역지원 포함)
        'transdLyricsFail',  -- 번역지원 가사 생성 실패
        'delTransdLyrics',   -- 번역지원만 제거(원문 가사는 유지)
        'metadataEdit'        -- 가사 외 메타데이터만 수정
    ))
);

COMMENT ON TABLE public."TrackHistory"
IS '다운로드·가사생성(번역지원)·가사삭제·노래삭제·메타데이터수정 이력 (History 탭 표시용)';

COMMENT ON COLUMN public."TrackHistory"."ID"
IS '이력 고유번호';

COMMENT ON COLUMN public."TrackHistory"."SerialNo"
IS '사용자 일련번호 (앱 getNrmAppSerialNo() 원문, 예: admin, 1092452918)';

COMMENT ON COLUMN public."TrackHistory"."Kind"
IS '이벤트 종류: down/downFail/del/lyrics/lyricsFail/delLyrics/transdLyrics/transdLyricsFail/delTransdLyrics/metadataEdit';

COMMENT ON COLUMN public."TrackHistory"."Platform"
IS '다운로드 시 경유 플랫폼(YouTube/Melon/Spotify/AppleMusic/LastFm) 또는 가사생성 모델(whisper:base 등, align:wav2vec2-ko 등)';

COMMENT ON COLUMN public."TrackHistory"."FileName"
IS '이벤트 시점 로컬 파일명 (표시용, 리네임 이후 추적 불가할 수 있음)';

COMMENT ON COLUMN public."TrackHistory"."AudioUri"
IS '이벤트 시점 로컬 오디오 파일 URI (기기 로컬 경로 — 다른 기기/재설치 후에는 무효)';

COMMENT ON COLUMN public."TrackHistory"."Title"
IS '노래 제목 (다운로드 시에만 확정적으로 채워짐, 그 외 이벤트는 조회 시점 값)';

COMMENT ON COLUMN public."TrackHistory"."Artist"
IS '아티스트';

COMMENT ON COLUMN public."TrackHistory"."Album"
IS '앨범명';

COMMENT ON COLUMN public."TrackHistory"."AlbumArtist"
IS '앨범 아티스트 (ffmpeg album_artist)';

COMMENT ON COLUMN public."TrackHistory"."Genre"
IS '장르';

COMMENT ON COLUMN public."TrackHistory"."ReleaseDate"
IS '발매일 원문 (플랫폼 API 포맷 그대로)';

COMMENT ON COLUMN public."TrackHistory"."TrackNumber"
IS '트랙 번호 (ffmpeg track)';

COMMENT ON COLUMN public."TrackHistory"."DiscNumber"
IS '디스크 번호 (ffmpeg disc)';

COMMENT ON COLUMN public."TrackHistory"."Composer"
IS '작곡가 (ffmpeg composer)';

COMMENT ON COLUMN public."TrackHistory"."Bpm"
IS 'BPM (ffmpeg bpm)';

COMMENT ON COLUMN public."TrackHistory"."Copyright"
IS '저작권 (ffmpeg copyright)';

COMMENT ON COLUMN public."TrackHistory"."Website"
IS '원본 URL (ffmpeg website — 멜론 상품 URL 등)';

COMMENT ON COLUMN public."TrackHistory"."Producer"
IS '프로듀서 (ffmpeg producer)';

COMMENT ON COLUMN public."TrackHistory"."Remixer"
IS '리믹서 (ffmpeg remixer)';

COMMENT ON COLUMN public."TrackHistory"."Lyrics"
IS '가사 원문(타임스탬프 제거한 plain 텍스트). 향후 벡터화 대상 컬럼.';

COMMENT ON COLUMN public."TrackHistory"."LyricsMode"
IS '가사 UI 모드: configured/translation/melon/melon_translation';

COMMENT ON COLUMN public."TrackHistory"."AlbumCoverPath"
IS 'Supabase Storage album-covers 버킷 내 오브젝트 경로 (공개 URL 아님 — getNrmSupabaseAlbumCoverPublicUrl로 변환)';

COMMENT ON COLUMN public."TrackHistory"."FailReason"
IS '실패 이벤트(다운로드/가사생성 실패)의 짧은 원인 문구';

COMMENT ON COLUMN public."TrackHistory"."IsSuccess"
IS '이벤트 성공 여부';

COMMENT ON COLUMN public."TrackHistory"."DownloadDate"
IS '이벤트 발생 일시 (다운로드가 아닌 이벤트도 이 컬럼에 발생 시각을 기록)';

CREATE INDEX IF NOT EXISTS "IX_TrackHistory_SerialNo"
ON public."TrackHistory" ("SerialNo");

CREATE INDEX IF NOT EXISTS "IX_TrackHistory_DownloadDate"
ON public."TrackHistory" ("DownloadDate" DESC);

CREATE INDEX IF NOT EXISTS "IX_TrackHistory_Kind"
ON public."TrackHistory" ("Kind");

-- RLS: 읽기는 anon/authenticated 전체 허용, 쓰기는 RPC로만 (이 저장소 관례 — 20260629140000 참고)
ALTER TABLE public."TrackHistory" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS track_history_select_anon ON public."TrackHistory";
CREATE POLICY track_history_select_anon
  ON public."TrackHistory" FOR SELECT TO anon, authenticated
  USING (true);

-- 쓰기 RPC: 컬럼이 늘어나도(향후 벡터 컬럼 등) 시그니처를 안 바꾸도록 JSONB 단일 파라미터로 받는다.
CREATE OR REPLACE FUNCTION public.nrm_rpc_track_history_insert(
  p_serial_no varchar,
  p_row jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
BEGIN
  IF coalesce(trim(p_serial_no), '') = '' THEN
    RAISE EXCEPTION 'SerialNo required';
  END IF;
  IF coalesce(trim(p_row->>'kind'), '') = '' THEN
    RAISE EXCEPTION 'kind required';
  END IF;

  INSERT INTO public."TrackHistory" (
    "SerialNo", "Kind", "Platform", "FileName", "AudioUri",
    "Title", "Artist", "Album", "AlbumArtist", "Genre",
    "ReleaseDate", "TrackNumber", "DiscNumber", "Composer", "Bpm",
    "Copyright", "Website", "Producer", "Remixer",
    "Lyrics", "LyricsMode", "AlbumCoverPath", "FailReason",
    "IsSuccess", "DownloadDate"
  )
  VALUES (
    trim(p_serial_no),
    p_row->>'kind',
    p_row->>'platform',
    p_row->>'fileName',
    p_row->>'audioUri',
    p_row->>'title',
    p_row->>'artist',
    p_row->>'album',
    p_row->>'albumArtist',
    p_row->>'genre',
    p_row->>'releaseDate',
    p_row->>'trackNumber',
    p_row->>'discNumber',
    p_row->>'composer',
    p_row->>'bpm',
    p_row->>'copyright',
    p_row->>'website',
    p_row->>'producer',
    p_row->>'remixer',
    p_row->>'lyrics',
    p_row->>'lyricsMode',
    p_row->>'albumCoverPath',
    p_row->>'failReason',
    coalesce((p_row->>'isSuccess')::boolean, true),
    coalesce((p_row->>'downloadDate')::timestamptz, now())
  )
  RETURNING "ID" INTO v_id;

  RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.nrm_rpc_track_history_insert(varchar, jsonb) TO anon, authenticated;

-- Storage: 앨범 커버 이미지 (다운로드 시 원본 coverUrl을 여기로 업로드해 경로를 TrackHistory.AlbumCoverPath에 저장)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'album-covers',
  'album-covers',
  true,
  8388608,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS nrm_album_covers_select ON storage.objects;
CREATE POLICY nrm_album_covers_select
  ON storage.objects FOR SELECT TO anon, authenticated
  USING (bucket_id = 'album-covers');

DROP POLICY IF EXISTS nrm_album_covers_insert ON storage.objects;
CREATE POLICY nrm_album_covers_insert
  ON storage.objects FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'album-covers');

DROP POLICY IF EXISTS nrm_album_covers_update ON storage.objects;
CREATE POLICY nrm_album_covers_update
  ON storage.objects FOR UPDATE TO anon, authenticated
  USING (bucket_id = 'album-covers')
  WITH CHECK (bucket_id = 'album-covers');
