from build_master import norm_key
from gen_spare import build_through

gs = build_through(2024)
EXTRA = [
    ("G-Dragon", "Drama", "Übermensch"),
    ("G-Dragon", "IBELONGIIU", "Übermensch"),
    ("G-Dragon", "RODMAN", "Übermensch"),
    ("G-Dragon", "Gyro-Drop", "Übermensch"),
    ("G-Dragon", "TOURRRGEN!", "Übermensch"),
    ("G-Dragon", "I FEEL LIKE GOD", "Übermensch"),
    ("Changmo", "BOOM", "Op.1"),
    ("Changmo", "METEOR", "Op.1"),
    ("Changmo", "NEO", "Op.1"),
    ("Changmo", "SOSO", "Op.1"),
    ("Lil Moshpit", "K-FLIP", "K-FLIP+"),
    ("Lil Moshpit", "DOPE", "K-FLIP+"),
    ("Lil Moshpit", "KOREA", "K-FLIP+"),
    ("Kid Milli", "RAD MILLI", "RAD MILLI"),
    ("Kid Milli", "RAD", "RAD MILLI"),
    ("Kid Milli", "MVP", "RAD MILLI"),
    ("Dean", "3:33", "3:33"),
    ("Dean", "Die 4 You", "3:33"),
    ("Dean", "Rest", "3:33"),
    ("Dean", "Normal People", "3:33"),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Sokodomo", "Merry Go Round (Feat. Zion.T)", "Merry Go Round"),
    ("Qwala", "yorter", "yorter"),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("Beenzino", "Train", ""),
    ("Beenzino", "Monet", "Monet"),
    ("Epik High", "Stop the Rain", ""),
    ("Epik High", "Frost", "Strawberry"),
    ("82MAJOR", "X-82", "X-82"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("82MAJOR", "Stuck", "Beat Road"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE", "THURSDAYCLUB MIXTAPE"),
    ("Blase", "SELF MADE", "SELF MADE"),
    ("Blase", "INDUSTRY", "SELF MADE"),
    ("Blase", "12345678", "SELF MADE"),
    ("Blase", "KKUCKDARI", "SELF MADE"),
    ("Giriboy", "heat", "heat"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Ash Island", "Malibu", "Ash Island"),
    ("Ash Island", "ISLAND", "ISLAND"),
    ("Coogie", "UPSET", "UPSET"),
    ("Coogie", "ON FIRE", ""),
    ("Coogie", "Flame", "UPSET"),
    ("Coogie", "Shut Up", "UPSET"),
    ("Coogie", "BABYFACE", "UPSET"),
    ("Leellamarz", "L&B", "L&B"),
    ("Leellamarz", "Let me go to heaven", ""),
    ("Leellamarz", "GONE", ""),
    ("Leellamarz", "Hell yea", "L&B"),
    ("Leellamarz", "Two Pills", "STILL YOUNG BOY L"),
    ("The Quiett", "Luxury Flow", "Luxury Flow"),
    ("The Quiett", "LF Intro", "Luxury Flow"),
    ("The Quiett", "Look Inside", "Luxury Flow"),
    ("The Quiett", "Crystal Crates", "Luxury Flow"),
    ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
    ("PH-1", "FLAT COKE", ""),
    ("PH-1", "GOSHA", "WHAT HAVE WE DONE"),
    ("Gray", "SLIDIN'", ""),
    ("Gray", "Real Love", "Remedy"),
    ("Crush", "Yes or No", ""),
    ("Crush", "Fallin'", ""),
    ("Loco", "random summer night", ""),
    ("Loco", "Smeraldo Garden Marching Band", ""),
    ("Jay Park", "Taxi Blurr", ""),
    ("Jay Park", "Stand Out", ""),
    ("Heize", "Even if (이븐 이프)", ""),
    ("Zico", "ZOOM", ""),
    ("Jessi", "Zoom", ""),
    ("Zion.T", "Snooze", "Zion.T Special: OO"),
    ("Mino", "Trigger", "XX"),
    ("Bobby", "Sir.Robert", "Sir.Robert"),
    ("Bobby", "Sae", "Sir.Robert"),
    ("Bobby", "Harmless", "Sir.Robert"),
    ("Mirani", "Drama", "Drama"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Owen Ovadoz", "Diamond", "119"),
    ("BE'O", "Momentum", "Show Me the Money 10"),
    ("Lee Young Ji", "Not Sure", "16"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Sik-K", "MAKE OUT", "MAKE OUT"),
    ("Sik-K", "Wet", "MAKE OUT"),
    ("Nafla", "MVP", "[ Album ]"),
    ("Loopy", "SEOUL pt.A", "SEOUL pt.A"),
    ("Loopy", "DOPE", "SEOUL pt.A"),
    ("Loopy", "DEAD MAN WALKING", "SEOUL pt.A"),
    ("Loopy", "CROWN", "SEOUL pt.A"),
    ("Loopy", "PINK SPILL", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Penomeco", "COCO BOTTLE", ""),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Gaeko", "Gajah", "Gajah"),
    ("Swings", "Per se", "Per se"),
    ("Swings", "Remedy", "Remedy"),
    ("Punchnello", "before you", ""),
    ("Dynamic Duo", "Highfive", ""),
    ("TOIL", "염염상망", ""),
    ("BRADYSTREET", "Brady Street", ""),
    ("Gist", "Gist", ""),
    ("CAMO", "Melody", "Melody"),
    ("Rad Museum", "Life", "Life"),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Rohann", "Problem", "Problem"),
    ("TOIL", "MAZE (메이즈)", "MAZE"),
    ("Code Kunst", "Buckle Up (버클 업)", "Code Kunst Archive Pack 02"),
    ("Knoxx", "Knoxx", ""),
    ("Polodared", "Multiverse", ""),
    ("Hej!", "Drive", ""),
    ("Futuristic Swaver", "Villain", ""),
    ("Hodaky", "Yellow", ""),
    ("Chillin Homie", "Good Day", ""),
    ("Bluso", "Fade Away", ""),
    ("LeyonC", "Fall", ""),
    ("Hyunsang", "Take Care", ""),
    ("Woo", "Rain Drop", "Rain Drop"),
    ("Rohann", "Sunday", ""),
    ("Mudd the student", "Sleepy Beauty", ""),
    ("Olltii", "Turtle Ship Remix", ""),
    ("Jessi", "Cold Blooded", "Cold Blooded"),
    ("Lee Young Ji", "O.K?", "O.K?"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Hero", "Hero"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("C Jamm", "RED", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Blued", "Blue", "Blue"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "BILLING", "BILLING"),
    ("Lil Boi", "ONFleek", "Show Me the Money 9"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Cool", "Cool"),
    ("PLT", "Summer", "Summer"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("BE'O", "Healing", "Show Me the Money 10"),
    ("Mirani", "Ticket", "Ticket"),
    ("Woodie Gochild", "GOchild", "#GOchild"),
    ("Owen Ovadoz", "Freeze", "119"),
    ("Blase", "Blue", ""),
    ("Swings", "Brand New Day", "Upgrade III"),
    ("Giriboy", "PlanetariuM", "Engineering"),
    ("Punchnello", "Everyday", "Everyday"),
    ("Loco", "BROKEN IPHONE", "WEAK"),
    ("Zion.T", "Whale", "Zip"),
    ("Heize", "Forgotten Love", "Last Winter"),
    ("Flowsik", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
    ("Reddy", "THINK (띵)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "VVS", "Show Me the Money 8"),
    ("Giriboy", "on my way", "Show Me the Money 8"),
    ("BIG Naughty", "Vogue", "Vogue"),
    ("Thama", "In My Room", "In My Room"),
    ("Mirani", "VANS", "Show Me the Money 8"),
    ("Zion.T", "No Make Up (feat. Wonstein)", "No Make Up"),
    ("Zion.T", "Spring Dream (봄꿀)", "Zionic"),
    ("Kid Milli", "Cliché (클리셰)", "Cliché"),
    ("Hash Swan", "Retro Love", ""),
    ("Jvcki Wai", "Doughnet", "Exposure"),
    ("Simon Dominic", "make her dance (메이크 허 댄스)", "GOTT"),
    ("Blase", "City Life", ""),
    ("Blase", "Holiday (Feat. Lil Boi, 기리보이)", "Show Me the Money 11"),
    ("Ahn Se-min", "물", "Show Me the Money 11"),
    ("Uneducated Kid", "UNEDUCATED KID", ""),
    ("Superbee", "Superbee", ""),
    ("Mad Clown", "Maximum", "Potato"),
    ("Deepflow", "Flow the Life 6", "Flow the Life 6"),
    ("Huckleberry P", "Mantra 6", "Mantra 6"),
    ("D.Ark", "Genius", "Genius"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("GroovyRoom", "Brought the Heat Back", "Brought the Heat Back"),
    ("Ash Island", "Me n Mine", "Show Me the Money 10"),
    ("Jay Park", "Candy", ""),
    ("Jay Park", "Sunday Night Drive", ""),
    ("PLT", "Way Back Home", "Way Back Home"),
    ("Lil Boi", "Empty Head", ""),
    ("Sokodomo", "IF I", "Show Me the Money 8"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Girls", "Life"),
    ("meenoi", "Malfunction", ""),
    ("CAMO", "Wifey", ""),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Coq", "Tweaker", ""),
    ("B.I", "Lover", ""),
    ("Basick", "Nice Day (나이스 데이)", "The Classic"),
    ("Verbal Jint", "Mainstream", "Mainstream"),
    ("JJK", "Go Back", "Go-Back"),
    ("Baechigi", "Shark's Tale", "Shark's Tale"),
    ("Futuristic Swaver", "Blue Hawaii", ""),
    ("Knoxx", "Knoxx Tape", ""),
    ("Polodared", "Polodared", ""),
    ("Hej!", "Hej!", ""),
    ("Hodaky", "Hodaky", ""),
    ("Chillin Homie", "Chillin Homie", ""),
    ("Bluso", "Bluso", ""),
    ("LeyonC", "LeyonC", ""),
    ("Hyunsang", "Hyunsang", ""),
    ("Woo", "Woo", ""),
    ("NSW yoon", "NSW yoon", "Show Me the Money 11"),
    ("Kan", "Kan", "Show Me the Money 11"),
    ("QM", "QM", "Show Me the Money 11"),
    ("노윤하", "노윤하", "Show Me the Money 11"),
    ("잠비노", "잠비노", "Show Me the Money 11"),
    ("허성현", "펄펄 (Feat. Dynamic Duo)", "Show Me the Money 11"),
    ("Don Malik", "Don Malik", "Show Me the Money 11"),
    ("이영지", "이영지", "Show Me the Money 11"),
    ("JUSTHIS", "JUSTHIS", "Show Me the Money 11"),
    ("Blase", "Quote That", ""),
    ("NO:EL", "Rain Drop", "Rain Drop"),
    ("Deepflow", "Flow the Life 3", "Flow the Life 3"),
    ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
    ("Huckleberry P", "Mantra 3", "Mantra 3"),
    ("Primary", "Morning Glory", ""),
    ("Dok2", "Rich Forever", "Rich Forever"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("Geologic", "Blaze", "Blaze"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca", "Orca-Tape"),
    ("C Jamm", "Monster", ""),
    ("Flowsik", "We On (위 온)", "Show Me the Money 777"),
    ("Reddy", "Think", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Illinit", "Ill Street Live 2 (일 스트릿)", ""),
    ("B-Free", "Hot Summer (핫 썸머)", "Best Seller"),
    ("Vasco", "더 바스코", "The Vasco"),
    ("Outsider", "볼륨2 마에스트로 4", "Vol.2-Maestro 4"),
    ("G2", "Business (비즈니스)", "Business"),
    ("Cheetah", "Keep It Movin (킵 잇 무빙)", ""),
    ("J'Kyun", "Ready to Fly (레디 투 플라이)", "Ready to Fly"),
    ("Myun Do One", "불도저", "Bulldozer"),
    ("Jerry.K", "Ready", "V"),
    ("Bumkey", "Attraction", "Single Life"),
    ("Junggigo", "Because", "Rookie"),
    ("Rhymer", "브랜드 뉴 데이", "Rhymer Trax Vol.1"),
    ("Double K", "플라이 하이", "Fly High"),
    ("MC Meta", "혼자서", "On My Own"),
    ("Mudd the student", "Open", "Show Me the Money 8"),
    ("BewhY", "Movie Star", "The Movie Star"),
    ("Penomeco", "Famous", ""),
    ("Simon Dominic", "NO OPEN FLAME", "NO OPEN FLAME"),
    ("Gaeko", "Geon Gangs", "Geon Gangs"),
    ("Nafla", "C.R.E.A.M", "C.R.E.A.M"),
    ("Loopy", "Portrait Mode", "[ Album ]"),
    ("YUMDDA", "I'm Good", "I'm Good"),
    ("Sik-K", "FL1X", "FL1X"),
    ("Tablo", "Hood", "Drill Presents: Tablo x Fantasy"),
    ("The Quiett", "King Is Back", "Luxury Flow"),
    ("Paloalto", "GONE", ""),
    ("TOIL", "1989", "1989"),
    ("Mirani", "Baby Steps", "Show Me the Money 10"),
    ("Blase", "ONOFF", "Show Me the Money 10"),
    ("Dynamic Duo", "Smoke (Prod. Dynamicduo, Padi)", "Street Woman Fighter 2 Original Vol.1"),
    ("Colde", "Wave", ""),
    ("Punchnello", "Motive", ""),
    ("Gray", "Summer Surf", "Summer Surf"),
    ("PH-1", "Rosario", "But For Now Leave Me Alone 2"),
    ("PH-1", "Final Bout", "But For Now Leave Me Alone 2"),
    ("Changmo", "VOOM", ""),
    ("Changmo", "FWB", ""),
    ("Bobby", "Drowning", "S.i.R"),
    ("Mino", "Smoke", "BODY"),
    ("Zion.T", "UNLOVE", "Zip"),
    ("Zion.T", "Happy Ending", "Zip"),
    ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)", "Last Winter"),
    ("Dean", "NO FUN", "howlin' 404"),
    ("Loco", "VOLVO", ""),
    ("Loco", "INEEDYOURLOVE", ""),
    ("Coogie", "Buck", "DIFF"),
    ("Crush", "wonderego", "wonderego"),
    ("Kid Milli", "Benzo", ""),
    ("Leellamarz", "DAYDATE", "DAYDATE"),
    ("meenoi", "3MAN", ""),
    ("82MAJOR", "ON", "ON"),
    ("Lil Moshpit", "Money Only Shows Hustle", ""),
    ("Zico", "Earthquake", ""),
    ("Beenzino", "NOWITZKI", "NOWITZKI"),
    ("Don Malik", "Malik", "MADE IN SEOUL"),
    ("Epik High", "Fade Away", "Strawberry"),
    ("BIG Naughty", "Você", "Você"),
    ("Giriboy", "Girlfriend", ""),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("Zico", "SPOT!", ""),
    ("Epik High", "Strawberry", "Strawberry"),
    ("82MAJOR", "FIRST CLASS", "ON"),
    ("Don Malik", "SEOUL", "MADE IN SEOUL"),
    ("Beenzino", "Trippy", "NOWITZKI"),
    ("Lil Moshpit", "TO GO", ""),
]
if __name__ == "__main__":
    gs = build_through(2024)
    ok = [x for x in EXTRA if norm_key(x[0], x[1]) not in gs]
    from collections import Counter

    c = Counter(a for a, _, _ in ok)
    cap = sum(min(2, n) for n in c.values())
    print("ok", len(ok), "artists", len(c), "capacity", cap)
    for x in ok[:30]:
        print(x[0], "|", x[1][:40])
