from build_master import norm_key
from gen_spare import build_through

gs = build_through(2022)
cands = [
    ("Blase", "Quote That", ""),
    ("Sokodomo", "SIGNATURE (시그니처)", "Show Me the Money 10"),
    ("BE'O", "Countdown (카운트다운)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Mudd the student", "Nectar (넥타)", "Show Me the Money 10"),
    ("Lil Boi", "Good Day", "Show Me the Money 10"),
    ("BewhY", "Day Day", "The Movie Star"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Bobby", "감동 (Secret)", "SECRET"),
    ("Mad Clown", "Maximum", "Potato"),
    ("Crush", "Oasis", ""),
    ("Dean", "4:44", ""),
    ("Sik-K", "Brought the Heat Back (더운데)", "Brought the Heat Back"),
    ("Swings", "우리를 기억해", "Growing Pains"),
    ("TOIL", "Rollin", "1989"),
    ("The Quiett", "Luxury Flow", "Luxury Flow"),
    ("Changmo", "ANTHEM", "Op.1"),
    ("Lil Moshpit", "ACHOO", "ACHOO"),
    ("BRADYSTREET", "Heavy", ""),
    ("Gist", "Engagement", ""),
    ("Blued", "Melody", "Melody"),
    ("Blase", "Blue", ""),
    ("Sokodomo", "Winner", "Show Me the Money 10"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("D.Ark", "Genius", "Genius"),
    ("Kid Ash", "Orca", "Orca-Tape"),
    ("C Jamm", "Monster", ""),
    ("Flowsik", "We On (위 온)", "Show Me the Money 777"),
    ("Reddy", "THINK (띵)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Basick", "Nice Day (나이스 데이)", "The Classic"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "2", "2"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("JJK", "Go Back", "Go-Back"),
    ("Baechigi", "Shark's Tale", "Shark's Tale"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Blaze", "Blaze"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Ash Island", "Howling", "Ash Island"),
    ("Leellamarz", "Profile (프로필)", "To Be Continued"),
    ("Punchnello", "Loving You Girl", "Loving You Girl"),
    ("Colde", "Your Dog Loves You", "Your Dog Loves You"),
    ("Giriboy", "Engineering (엔지니어링)", "Engineering"),
    ("Mirani", "Villain (빌런)", "Show Me the Money 10"),
    ("Woodie Gochild", "Mud (머드)", "Show Me the Money 10"),
    ("Owen Ovadoz", "Diana (디ana)", "Show Me the Money 10"),
    ("Blase", "ONOFF", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Jessi", "Who Dat B", "Who Dat B"),
    ("Tablo", "Fantasy", "Drill Presents: Tablo x Fantasy"),
    ("Nafla", "Swervin", "C.R.E.A.M"),
    ("Loopy", "Save", "[ Album ]"),
    ("YUMDDA", "Shake", "I'm Good"),
    ("Hash Swan", "Retro Love", ""),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("Mudd the student", "Sleepy Beauty", ""),
    ("BewhY", "Forever", "The Fiery"),
    ("Penomeco", "OFM", ""),
    ("Simon Dominic", "DAx4", "DAx4"),
    ("Gaeko", "West Coast", "Redingray"),
    ("Deepflow", "그날", "Flow the Life 3"),
    ("Huckleberry P", "우퍼", "Mantra 3"),
    ("D.Ark", "Undercover", "Genius"),
    ("Koonta", "Grandma", "Show Me the Money 8"),
    ("Kid Milli", "Simple Poem", "BEIGE"),
]
ok = [x for x in cands if norm_key(x[0], x[1]) not in gs]
print("ok", len(ok))
for x in ok:
    print(x)
