#!/usr/bin/env python3
"""2024–2025 POOLS/HEAD 재작성."""
from __future__ import annotations

import os

from build_master import HERE, build_from_pool, load_global_exclude, load_module, norm_key, GEN
from gen_spare import build_through
from rebalance_pools import rewrite_section

HEAD_2024 = [
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER", "Übermensch"),
    ("Beenzino", "Train", ""),
    ("Changmo", "Wonderful Days", ""),
    ("Lil Moshpit", "K-FLIP", "K-FLIP+"),
    ("Kid Milli", "5AM", "RAD MILLI"),
    ("Dean", "NASA", "3:33"),
    ("Jay Park", "Taxi Blurr", ""),
    ("Crush", "Yes or No", ""),
    ("Heize", "Even if (이븐 이프)", ""),
]

CANDIDATES_2024 = [
    ("G-Dragon", "TAKE ME", "Übermensch"),
    ("G-Dragon", "Bonamana", "Übermensch"),
    ("Zico", "ZOOM", ""),
    ("Changmo", "HOLDUP", "Op.1"),
    ("Changmo", "ANTHEM", "Op.1"),
    ("Lil Moshpit", "KC2", "K-FLIP+"),
    ("Lil Moshpit", "LALALA", "K-FLIP+"),
    ("Lil Moshpit", "MADE IN KCOREA", "K-FLIP+"),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Kid Milli", "술", "RAD MILLI"),
    ("Kid Milli", "Summer Time", "RAD MILLI"),
    ("Kid Milli", "Feel Good", "RAD MILLI"),
    ("Dean", "Ctrl", "3:33"),
    ("Jay Park", "Stand Out", ""),
    ("Loco", "random summer night", ""),
    ("Loco", "Smeraldo Garden Marching Band", ""),
    ("Crush", "Fallin'", ""),
    ("Leellamarz", "Let me go to heaven", ""),
    ("Leellamarz", "GONE", ""),
    ("The Quiett", "LF Intro", "Luxury Flow"),
    ("The Quiett", "Look Inside", "Luxury Flow"),
    ("Bobby", "Sae", "Sir.Robert"),
    ("Bobby", "Harmless", "Sir.Robert"),
    ("Coogie", "ON FIRE", ""),
    ("Coogie", "Flame", "UPSET"),
    ("Coogie", "Shut Up", "UPSET"),
    ("Coogie", "BABYFACE", "UPSET"),
    ("PH-1", "FLAT COKE", ""),
    ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
    ("Punchnello", "before you", ""),
    ("Gray", "SLIDIN'", ""),
    ("Gray", "Real Love", "Remedy"),
    ("Giriboy", "heat", "heat"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Dynamic Duo", "Highfive", ""),
    ("Epik High", "Stop the Rain", ""),
    ("Epik High", "Frost", "Strawberry"),
    ("Ash Island", "Malibu", "Ash Island"),
    ("Ash Island", "ISLAND", "ISLAND"),
    ("TOIL", "염염상망", ""),
    ("Blase", "INDUSTRY", "SELF MADE"),
    ("Blase", "12345678", "SELF MADE"),
    ("Blase", "KKUCKDARI", "SELF MADE"),
    ("Mirani", "Drama", "Drama"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Owen Ovadoz", "Diamond", "119"),
    ("BE'O", "Momentum", "Show Me the Money 10"),
    ("BE'O", "Healing", "Show Me the Money 10"),
    ("Lee Young Ji", "Not Sure", "16"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Jessi", "Zoom", ""),
    ("Sik-K", "MAKE OUT", "MAKE OUT"),
    ("Sik-K", "Wet", "MAKE OUT"),
    ("Nafla", "MVP", "[ Album ]"),
    ("Nafla", "Jazz Freestyle", "[ Album ]"),
    ("Loopy", "DOPE", "SEOUL pt.A"),
    ("Loopy", "DEAD MAN WALKING", "SEOUL pt.A"),
    ("Loopy", "CROWN", "SEOUL pt.A"),
    ("Loopy", "PINK SPILL", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Penomeco", "COCO BOTTLE", ""),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Antihuman", "Antihuman", "Antihuman"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Swings", "Per se", "Per se"),
    ("Swings", "Remedy", "Remedy"),
    ("Mino", "Trigger", "XX"),
    ("Zion.T", "Snooze", "Zion.T Special: OO"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE", "THURSDAYCLUB MIXTAPE"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("82MAJOR", "Stuck", "Beat Road"),
    ("Leellamarz", "Hell yea", "L&B"),
    ("Leellamarz", "Two Pills", "STILL YOUNG BOY L"),
    ("The Quiett", "Crystal Crates", "Luxury Flow"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Cool", "Cool"),
    ("PLT", "Summer", "Summer"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Hero", "Hero"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("C Jamm", "RED", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Blued", "Blue", "Blue"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "BILLING", "BILLING"),
    ("Leellamarz", "B", ""),
    ("Knoxx", "Knoxx", ""),
    ("Polodared", "Multiverse", ""),
    ("Hej!", "Drive", ""),
    ("Futuristic Swaver", "Villain", ""),
    ("Hodaky", "Yellow", ""),
    ("Chillin Homie", "Good Day", ""),
    ("Uneducated Kid", "UNEDUCATED KID", ""),
    ("Superbee", "Superbee", ""),
    ("Mad Clown", "Maximum", "Potato"),
    ("Bluso", "Fade Away", ""),
    ("LeyonC", "Fall", ""),
    ("Hyunsang", "Take Care", ""),
    ("Woo", "Rain Drop", "Rain Drop"),
    ("Rohann", "Sunday", ""),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Life", "Life"),
    ("meenoi", "Malfunction", ""),
    ("CAMO", "Wifey", ""),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Coq", "Tweaker", ""),
    ("B.I", "Lover", ""),
    ("Rad Museum", "Girls", "Life"),
    ("Lil Boi", "ONFleek", "Show Me the Money 9"),
    ("Lil Boi", "Empty Head", ""),
    ("Sokodomo", "Winner", "Show Me the Money 10"),
    ("Flowsik", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
    ("Reddy", "THINK (띵)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "VVS", "Show Me the Money 8"),
    ("Giriboy", "on my way", "Show Me the Money 8"),
    ("Mirani", "Ticket", "Ticket"),
    ("Woodie Gochild", "GOchild", "#GOchild"),
    ("Owen Ovadoz", "Freeze", "119"),
    ("Blase", "Blue", ""),
    ("Swings", "Brand New Day", "Upgrade III"),
    ("Giriboy", "PlanetariuM", "Engineering"),
    ("Punchnello", "Everyday", "Everyday"),
    ("Dean", "Die 4 You", ""),
    ("Loco", "BROKEN IPHONE", "WEAK"),
    ("Zion.T", "Whale", "Zip"),
    ("Heize", "Forgotten Love", "Last Winter"),
    ("Mino", "Smoke", "BODY"),
    ("Bobby", "Drowning", "S.i.R"),
    ("Zion.T", "UNLOVE", "Zip"),
    ("Dean", "NO FUN", "howlin' 404"),
    ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)", "Last Winter"),
    ("Loco", "VOLVO", ""),
    ("Coogie", "Buck", "DIFF"),
    ("Crush", "wonderego", "wonderego"),
    ("Kid Milli", "Benzo", ""),
    ("Leellamarz", "DAYDATE", "DAYDATE"),
    ("meenoi", "3MAN", ""),
    ("82MAJOR", "ON", "ON"),
    ("Lil Moshpit", "Money Only Shows Hustle", ""),
    ("Zico", "Earthquake", ""),
    ("Beenzino", "NOWITZKI", "NOWITZKI"),
    ("Don Malik", "Malik", "MADE IN SEOUL"),
    ("Epik High", "Fade Away", "Strawberry"),
    ("BIG Naughty", "Você", "Você"),
    ("Giriboy", "Girlfriend", ""),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("Zico", "SPOT!", ""),
    ("Epik High", "Strawberry", "Strawberry"),
    ("82MAJOR", "FIRST CLASS", "ON"),
    ("Don Malik", "SEOUL", "MADE IN SEOUL"),
    ("Beenzino", "Trippy", "NOWITZKI"),
    ("Lil Moshpit", "TO GO", ""),
]

HEAD_2025 = [
    ("G-Dragon", "Too Bad", "Übermensch"),
    ("Crush", "UP ALL NITE", "FANG"),
    ("Loco", "work++", "SCRAPS"),
    ("Changmo", "HOLDUP", "Op.1"),
    ("PH-1", "GOSHA", "WHAT HAVE WE DONE"),
    ("Lil Moshpit", "K-FLIP", "K-FLIP+"),
    ("Heize", "Love Virus (러브 바이러스)", "LOVE VIRUS Pt.1"),
    ("Kid Milli", "5AM", "RAD MILLI"),
    ("Dean", "NASA", "3:33"),
    ("Jay Park", "Taxi Blurr", ""),
]

CANDIDATES_2025 = [
    ("Heize", "Last Taxi (라스트 택시)", "LOVE VIRUS Pt.1"),
    ("Crush", "FANG", "FANG"),
    ("Loco", "SCRAPS", "SCRAPS"),
    ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER", "Übermensch"),
    ("G-Dragon", "TAKE ME", "Übermensch"),
    ("Beenzino", "Train", ""),
    ("Changmo", "Wonderful Days", ""),
    ("Lil Moshpit", "KC2", "K-FLIP+"),
    ("Lil Moshpit", "LALALA", "K-FLIP+"),
    ("Zico", "ZOOM", ""),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Kid Milli", "술", "RAD MILLI"),
    ("Kid Milli", "Feel Good", "RAD MILLI"),
    ("Dean", "Ctrl", "3:33"),
    ("Jay Park", "Stand Out", ""),
    ("Crush", "Yes or No", ""),
    ("Crush", "Fallin'", ""),
    ("Heize", "Even if (이븐 이프)", ""),
    ("Leellamarz", "Let me go to heaven", ""),
    ("Leellamarz", "GONE", ""),
    ("The Quiett", "LF Intro", "Luxury Flow"),
    ("Bobby", "Sae", "Sir.Robert"),
    ("Coogie", "ON FIRE", ""),
    ("Gray", "SLIDIN'", ""),
    ("Giriboy", "heat", "heat"),
    ("Dynamic Duo", "Highfive", ""),
    ("Ash Island", "Malibu", "Ash Island"),
    ("TOIL", "염염상망", ""),
    ("Blase", "INDUSTRY", "SELF MADE"),
    ("Mirani", "Drama", "Drama"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Owen Ovadoz", "Diamond", "119"),
    ("BE'O", "Momentum", "Show Me the Money 10"),
    ("Lee Young Ji", "Not Sure", "16"),
    ("Jessi", "Zoom", ""),
    ("Sik-K", "MAKE OUT", "MAKE OUT"),
    ("Nafla", "MVP", "[ Album ]"),
    ("Loopy", "DOPE", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Penomeco", "COCO BOTTLE", ""),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Antihuman", "Antihuman", "Antihuman"),
    ("Swings", "Per se", "Per se"),
    ("Mino", "Trigger", "XX"),
    ("Zion.T", "Snooze", "Zion.T Special: OO"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE", "THURSDAYCLUB MIXTAPE"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("Epik High", "Frost", "Strawberry"),
    ("Coogie", "Shut Up", "UPSET"),
    ("Leellamarz", "Hell yea", "L&B"),
    ("The Quiett", "Crystal Crates", "Luxury Flow"),
    ("Gray", "Real Love", "Remedy"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Ash Island", "ISLAND", "ISLAND"),
    ("Mirani", "Ticket", "Ticket"),
    ("Blase", "KKUCKDARI", "SELF MADE"),
    ("BE'O", "Healing", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Sik-K", "Wet", "MAKE OUT"),
    ("Loopy", "CROWN", "SEOUL pt.A"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Swings", "Remedy", "Remedy"),
    ("Lil Boi", "ONFleek", "Show Me the Money 9"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Cool", "Cool"),
    ("PLT", "Summer", "Summer"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Hero", "Hero"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("C Jamm", "RED", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Blued", "Blue", "Blue"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "BILLING", "BILLING"),
    ("Leellamarz", "B", ""),
    ("Knoxx", "Knoxx", ""),
    ("Polodared", "Multiverse", ""),
    ("Hej!", "Drive", ""),
    ("Futuristic Swaver", "Villain", ""),
    ("Hodaky", "Yellow", ""),
    ("Chillin Homie", "Good Day", ""),
    ("Uneducated Kid", "UNEDUCATED KID", ""),
    ("Superbee", "Superbee", ""),
    ("Mad Clown", "Maximum", "Potato"),
    ("Bluso", "Fade Away", ""),
    ("LeyonC", "Fall", ""),
    ("Hyunsang", "Take Care", ""),
    ("Woo", "Rain Drop", "Rain Drop"),
    ("Rohann", "Sunday", ""),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Life", "Life"),
    ("CAMO", "Melody", "Melody"),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Coq", "Tweaker", ""),
    ("B.I", "Lover", ""),
    ("Rad Museum", "Girls", "Life"),
    ("meenoi", "Malfunction", ""),
    ("Mudd the student", "Sleepy Beauty", ""),
    ("Olltii", "Turtle Ship Remix", ""),
    ("Jessi", "Cold Blooded", "Cold Blooded"),
    ("Lee Young Ji", "O.K?", "O.K?"),
    ("Epik High", "Stop the Rain", ""),
    ("Paloalto", "GONE", ""),
    ("Sik-K", "FL1X", "FL1X"),
    ("Tablo", "Hood", "Drill Presents: Tablo x Fantasy"),
    ("Nafla", "C.R.E.A.M", "C.R.E.A.M"),
    ("Loopy", "Portrait Mode", "[ Album ]"),
    ("YUMDDA", "I'm Good", "I'm Good"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Exposure", "Exposure"),
    ("BewhY", "Movie Star", "The Movie Star"),
    ("Penomeco", "Famous", ""),
    ("Simon Dominic", "NO OPEN FLAME", "NO OPEN FLAME"),
    ("Gaeko", "Geon Gangs", "Geon Gangs"),
    ("Deepflow", "Flow the Life 6", "Flow the Life 6"),
    ("Huckleberry P", "Mantra 6", "Mantra 6"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Blase", "City Life", ""),
    ("GroovyRoom", "Brought the Heat Back", "Brought the Heat Back"),
    ("Ash Island", "Me n Mine", "Show Me the Money 10"),
    ("Jay Park", "Candy", ""),
    ("Jay Park", "Sunday Night Drive", ""),
    ("PLT", "Way Back Home", "Way Back Home"),
    ("Lil Boi", "Empty Head", ""),
    ("Sokodomo", "IF I", "Show Me the Money 8"),
    ("Flowsik", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
    ("Reddy", "THINK (띵)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "VVS", "Show Me the Money 8"),
    ("Giriboy", "on my way", "Show Me the Money 8"),
    ("BIG Naughty", "Vogue", "Vogue"),
    ("Rohann", "Problem", "Problem"),
    ("Thama", "In My Room", "In My Room"),
    ("TOIL", "MAZE (메이즈)", "MAZE"),
    ("Mirani", "VANS", "Show Me the Money 8"),
    ("Zion.T", "No Make Up (feat. Wonstein)", "No Make Up"),
    ("Code Kunst", "Buckle Up (버클 업)", "Code Kunst Archive Pack 02"),
    ("Zion.T", "Spring Dream (봄꿈)", "Zionic"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Kid Milli", "Cliché (클리셰)", "Cliché"),
    ("Hash Swan", "Retro Love", ""),
    ("Jvcki Wai", "Doughnet", "Exposure"),
    ("Simon Dominic", "make her dance (메이크 허 댄스)", "GOTT"),
    ("Swings", "Brand New Day", "Upgrade III"),
    ("Woodie Gochild", "GOchild", "#GOchild"),
    ("Owen Ovadoz", "Freeze", "119"),
    ("Blase", "Blue", ""),
    ("Giriboy", "PlanetariuM", "Engineering"),
    ("Punchnello", "Everyday", "Everyday"),
    ("Dean", "Die 4 You", ""),
    ("Loco", "BROKEN IPHONE", "WEAK"),
    ("Zion.T", "Whale", "Zip"),
    ("Heize", "Forgotten Love", "Last Winter"),
    ("Mino", "Smoke", "BODY"),
    ("Bobby", "Drowning", "S.i.R"),
    ("Zion.T", "UNLOVE", "Zip"),
    ("Dean", "NO FUN", "howlin' 404"),
    ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)", "Last Winter"),
    ("Loco", "VOLVO", ""),
    ("Coogie", "Buck", "DIFF"),
    ("Crush", "wonderego", "wonderego"),
    ("Kid Milli", "Benzo", ""),
    ("Leellamarz", "DAYDATE", "DAYDATE"),
    ("meenoi", "3MAN", ""),
    ("82MAJOR", "ON", "ON"),
    ("Lil Moshpit", "Money Only Shows Hustle", ""),
    ("Zico", "Earthquake", ""),
    ("Beenzino", "NOWITZKI", "NOWITZKI"),
    ("Don Malik", "Malik", "MADE IN SEOUL"),
    ("Epik High", "Fade Away", "Strawberry"),
    ("BIG Naughty", "Você", "Você"),
    ("Giriboy", "Girlfriend", ""),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("Zico", "SPOT!", ""),
    ("Epik High", "Strawberry", "Strawberry"),
    ("82MAJOR", "FIRST CLASS", "ON"),
    ("Don Malik", "SEOUL", "MADE IN SEOUL"),
    ("Beenzino", "Trippy", "NOWITZKI"),
    ("Lil Moshpit", "TO GO", ""),
    ("Changmo", "ANTHEM", "Op.1"),
    ("Lil Moshpit", "MADE IN KCOREA", "K-FLIP+"),
    ("G-Dragon", "Bonamana", "Übermensch"),
    ("PH-1", "FLAT COKE", ""),
    ("Loco", "random summer night", ""),
    ("Loco", "Smeraldo Garden Marching Band", ""),
    ("The Quiett", "Look Inside", "Luxury Flow"),
    ("Bobby", "Harmless", "Sir.Robert"),
    ("Coogie", "Flame", "UPSET"),
    ("Coogie", "BABYFACE", "UPSET"),
    ("Kid Milli", "Summer Time", "RAD MILLI"),
    ("Leellamarz", "Two Pills", "STILL YOUNG BOY L"),
    ("Blase", "12345678", "SELF MADE"),
    ("Loopy", "DEAD MAN WALKING", "SEOUL pt.A"),
    ("Loopy", "PINK SPILL", "SEOUL pt.A"),
    ("Nafla", "Jazz Freestyle", "[ Album ]"),
    ("82MAJOR", "Stuck", "Beat Road"),
    ("Don Malik", "MADE IN SEOUL", "MADE IN SEOUL"),
    ("Qwala", "If WONA becomes a gangster (Feat. Qwala, New Champ)", ""),
]


def pick_pool(year: int, head: list, candidates: list) -> list[tuple[str, str, str]]:
    gs = build_through(year)
    ex = load_global_exclude()
    ac: dict[str, int] = {a: 1 for a, _, _ in head}
    pool: list[tuple[str, str, str]] = []
    seen = {norm_key(a, t) for a, t, _ in head}
    for a, t, al in candidates:
        k = norm_key(a, t)
        if k in seen or k in gs or k in ex:
            continue
        if ac.get(a, 0) >= 2:
            continue
        seen.add(k)
        pool.append((a, t, al))
        ac[a] = ac.get(a, 0) + 1
    return pool


def load_extra_2024() -> list[tuple[str, str, str]]:
    from _extra2024 import EXTRA
    from underground_2024 import UNDERGROUND_2024

    gs = build_through(2024)
    seen: set[str] = set()
    out: list[tuple[str, str, str]] = []
    for a, t, al in EXTRA + UNDERGROUND_2024:
        k = norm_key(a, t)
        if k in gs or k in seen:
            continue
        seen.add(k)
        out.append((a, t, al))
    return out


def try_build(year: int, head: list, pool: list) -> tuple[int, str | None]:
    gs = set(build_through(year))
    ex = load_global_exclude()
    spare = load_module("spare", os.path.join(GEN, "spare_tracks.py"))
    try:
        r = build_from_pool(
            year,
            pool + spare.SPARE.get(year, []),
            gs,
            ex,
            head=head,
            round_robin=True,
        )
        return len(r), None
    except Exception as e:
        return len(r) if "r" in dir() else 0, str(e)


def main() -> None:
    path = os.path.join(HERE, "pools_2022_2025.py")
    with open(path, encoding="utf-8") as f:
        text = f.read()

    configs = [
        (2024, HEAD_2024, None),
        (2025, HEAD_2025, None),
    ]
    for year, head, cands in configs:
        if cands is None:
            if year == 2024:
                cands = CANDIDATES_2024 + load_extra_2024()
            else:
                from underground_2025 import UNDERGROUND_2025
                gs = build_through(2025)
                seen: set[str] = set()
                cands = []
                for a, t, al in CANDIDATES_2025 + UNDERGROUND_2025:
                    k = norm_key(a, t)
                    if k in gs or k in seen:
                        continue
                    seen.add(k)
                    cands.append((a, t, al))
        if year == 2025 and cands is not None:
            pass
        pool = pick_pool(year, head, cands)
        gs = set(build_through(year))
        ex = load_global_exclude()
        spare = load_module("spare", os.path.join(GEN, "spare_tracks.py"))
        try:
            build_from_pool(
                year,
                pool + spare.SPARE.get(year, []),
                gs,
                ex,
                head=head,
                round_robin=True,
            )
            print(f"{year}: pool={len(pool)} OK 100")
        except Exception as e:
            print(f"{year}: pool={len(pool)} FAIL {e}")

        text = rewrite_section(text, "HEAD", year, head)
        text = rewrite_section(text, "POOLS", year, pool)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"wrote HEAD/POOLS[{year}]")


if __name__ == "__main__":
    main()
