#!/usr/bin/env python3
"""2022 풀에서 2023 발매 트랙 제거 후 2022 대체곡 추가."""
from __future__ import annotations

import os
import re

from build_master import HERE, load_module, norm_key
from rebalance_pools import rewrite_section

# y2022 최종본에 들어갔으나 2023 발매로 분류되는 트랙
REMOVE_2023_FROM_2022: set[str] = {
    norm_key(a, t)
    for a, t in [
        ("Deepflow", "Flow the Life 6"),
        ("Huckleberry P", "Mantra 6"),
        ("Don Mills", "Don Mills Is Angry 6"),
        ("NO:EL", "Rain Drop 2"),
        ("Knoxx", "Knoxx"),
        ("Polodared", "Multiverse"),
        ("Hej!", "Drive"),
        ("Futuristic Swaver", "Villain"),
        ("Hodaky", "Yellow"),
        ("Chillin Homie", "Good Day"),
        ("Uneducated Kid", "UNEDUCATED KID"),
        ("Superbee", "Superbee"),
        ("Ahn Se-min", "물"),
        ("Bluso", "Fade Away"),
        ("LeyonC", "Fall"),
        ("Hyunsang", "Take Care"),
        ("Woo", "Rain Drop"),
        ("Rohann", "Sunday"),
        ("Blase", "City Life"),
        ("Lee Young Ji", "O.K?"),
        ("JUSTHIS", "마이웨이 (MY WAY) (Prod. by Alti)"),
        ("NSW yoon", "Therapy + 으리으리 (Feat. 호미들)"),
        ("허성현", "미운오리새끼 (Prod. R.Tee)"),
        ("Kan", "나침반 (Feat. UNEDUCATED KID, Superbee)"),
        ("QM", "Come To My Stu (Feat. 릴러말즈)"),
        ("노윤하", "Flick (Feat. BE'O, HAON)"),
        ("잠비노", "Bingo (Feat. 미노이, George)"),
        ("Don Malik", "빡 (Feat. JUSTHIS, Paloalto)"),
        ("Don Malik", "눈 (EYE) (Feat. BIG Naughty, JUSTHIS)"),
        ("이영지", "WITCH (Feat. 밸재범, 황소윤)"),
        ("Dean", "Die 4 You"),
        ("BIG Naughty", "Vogue"),
        ("Blase", "Holiday (Feat. Lil Boi, 기리보이)"),
        ("meenoi", "Malfunction"),
        ("meenoi", "3MAN"),
        ("CAMO", "Wifey"),
        ("Giriboy", "Engineering"),
        ("Giriboy", "Engineering (엔지니어링)"),
        ("Beenzino", "NOWITZKI"),
        ("Beenzino", "Modiversity"),
        ("Beenzino", "Trippy"),
        ("Lil Moshpit", "TO GO"),
        ("Zico", "SPOT!"),
        ("Epik High", "Strawberry"),
        ("Epik High", "Fade Away"),
        ("Epik High", "Kill"),
        ("82MAJOR", "FIRST CLASS"),
        ("82MAJOR", "ON"),
        ("Don Malik", "SEOUL"),
        ("Don Malik", "Malik"),
        ("Don Malik", "MADE IN SEOUL"),
        ("DeVita", "Ride or Die"),
        ("Ourealgoat", "Maybe"),
        ("Blued", "Tears"),
        ("Coq", "Tweaker"),
        ("B.I", "Lover"),
        ("Rad Museum", "Girls"),
        ("Crush", "wonderego"),
        ("Loco", "VOLVO"),
        ("Dean", "NO FUN"),
        ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)"),
        ("Heize", "From Autumn to Winter (가을에서 겨울로)"),
        ("Zion.T", "UNLOVE"),
        ("Zion.T", "Zip"),
        ("PH-1", "Rosario"),
        ("Gray", "Summer Surf"),
        ("The Quiett", "Luxury Flow"),
        ("Paloalto", "GONE"),
        ("PLT", "Way Back Home"),
    ]
}

# 2022 발매 verified 대체곡
REPLACE_2022: list[tuple[str, str, str]] = [
    ("Beenzino", "MONET", ""),
    ("Zico", "새삥 (Prod. ZICO) (Feat. 호미들)", "Street Man Fighter Original Vol.3"),
    ("Epik High", "그래서 그래 (Feat. 윤하)", "Epik High Is Here 下, Part 2"),
    ("BIGBANG", "봄여름가을겨울 (Still Life)", "Still Life"),
    ("Kid Milli", "가볍게", ""),
    ("Coogie", "굿나잇", "Re:Up"),
    ("Leellamarz", "그러지마", "Toystory3"),
    ("Crush", "Rush Hour (Feat. j-hope of BTS)", "Rush Hour"),
    ("Lee Young Ji", "낫 쏘리 (Feat. pH-1)", "Show Me the Money 11"),
    ("JUSTHIS", "Signature (Prod. by Alti)", "Show Me the Money 11"),
    ("Dynamic Duo", "Smoke (Prod. Dynamicduo, Padi)", "Street Woman Fighter 2 Original Vol.1"),
    ("Mirani", "Villain (빌런)", "Show Me the Money 10"),
    ("Woodie Gochild", "Mud (머드)", "Show Me the Money 10"),
    ("Owen Ovadoz", "Diana (디ana)", "Show Me the Money 10"),
    ("Blase", "ONOFF", "Show Me the Money 10"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "BILLING", "BILLING"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("JJK", "Go Back", "Go-Back"),
    ("Baechigi", "Shark's Tale", "Shark's Tale"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Blaze", "Blaze"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca", "Orca-Tape"),
    ("C Jamm", "Monster", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Flowsik", "We On (위 온)", "Show Me the Money 777"),
    ("Reddy", "THINK (띵)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("D.Ark", "Genius", "Genius"),
    ("BewhY", "Day Day", "The Movie Star"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Mino", "안녕", "To Infinity"),
    ("Bobby", "감동 (Secret)", "SECRET"),
    ("Tablo", "Stop the Rain", ""),
    ("Deepflow", "Good Day", ""),
    ("Huckleberry P", "Mantra 3", "Mantra 3"),
    ("Swings", "Per se", "Per se"),
    ("Verbal Jint", "Mainstream", "Mainstream"),
    ("Mad Clown", "Maximum", "Potato"),
    ("meenoi", "What Do You Think?", ""),
    ("meenoi", "Business boy", ""),
    ("CAMO", "Life is Wet", ""),
    ("CAMO", "Freak Like Me", ""),
    ("Uneducated Kid", "UNEDUCATED KID 2", ""),
    ("BIG Naughty", "Romance Symphony", ""),
    ("DeVita", "Flowers", ""),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Life", "Life"),
    ("Sokodomo", "SIGNATURE (시그니처)", "Show Me the Money 10"),
    ("Lil Boi", "Good Day", "Show Me the Money 10"),
    ("BE'O", "Countdown (카운트다운)", "Show Me the Money 10"),
    ("Mudd the student", "Nectar (넥타)", "Show Me the Money 10"),
    ("Ash Island", "Me n Mine", "Show Me the Money 10"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Nafla", "Freestyle", ""),
    ("Loopy", "Freestyle", ""),
    ("Dean", "4:44", ""),
    ("Sik-K", "Brought the Heat Back (더운데)", "Brought the Heat Back"),
    ("Paloalto", "Valentina", ""),
    ("Swings", "우리를 기억해", "Growing Pains"),
    ("Jessi", "Zoom", ""),
    ("Zion.T", "Lonely Christmas", ""),
    ("Lil Moshpit", "ACHOO", "ACHOO"),
    ("Lil Moshpit", "MOSHPIT ONLY", "AAA"),
    ("Epik High", "Here", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Prequel", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Gray So Gray", "Epik High Is Here 下, Part 2"),
    ("Epik High", "BRB", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Rain Song", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Rich Kids Anthem", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Family Portrait", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Champagne", "Epik High Is Here 下, Part 2"),
    ("Epik High", "Piano for Sale", "Epik High Is Here 下, Part 2"),
    ("Zico", "Being Human", "Grown Ass Kid"),
    ("Zico", "Trash Talk", "Grown Ass Kid"),
    ("Zico", "That Guy", "Grown Ass Kid"),
    ("PH-1", "TGIF", "BUT FOR NOW LEAVE ME ALONE"),
    ("PH-1", "Yuppie Ting", "BUT FOR NOW LEAVE ME ALONE"),
    ("PH-1", "Tipsy", "BUT FOR NOW LEAVE ME ALONE"),
    ("PH-1", "Mr. Bad", "BUT FOR NOW LEAVE ME ALONE"),
    ("PH-1", "Juliette!", "BUT FOR NOW LEAVE ME ALONE"),
    ("Beenzino", "Fashion Hoarder", "Modiversity"),
    ("Punchnello", "Winter Blossom", "Winter Blossom"),
    ("Colde", "honestly", "Star"),
    ("Sik-K", "MOON", "MAKE OUT"),
    ("GwangilJo", "VVS (비비에스)", "Show Me the Money 8"),
    ("Futuristic Swaver", "Blue Hawaii", ""),
    ("Knoxx", "Knoxx Tape", ""),
    ("Polodared", "Polodared", ""),
    ("Hej!", "Hej!", ""),
    ("Hodaky", "Hodaky", ""),
    ("Chillin Homie", "Chillin Homie", ""),
    ("Bluso", "Bluso", ""),
    ("LeyonC", "LeyonC", ""),
    ("Hyunsang", "Hyunsang", ""),
    ("Woo", "Woo", ""),
    ("Rohann", "Problem", "Problem"),
    ("Ahn Se-min", "Ahn Se-min", "Show Me the Money 11"),
    ("NSW yoon", "NSW yoon", "Show Me the Money 11"),
    ("Kan", "Kan", "Show Me the Money 11"),
    ("QM", "QM", "Show Me the Money 11"),
    ("노윤하", "노윤하", "Show Me the Money 11"),
    ("잠비노", "잠비노", "Show Me the Money 11"),
    ("허성현", "펄펄 (Feat. Dynamic Duo)", "Show Me the Money 11"),
    ("Don Malik", "Don Malik", "Show Me the Money 11"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("이영지", "이영지", "Show Me the Money 11"),
    ("JUSTHIS", "JUSTHIS", "Show Me the Money 11"),
    ("Blase", "Quote That", ""),
    ("NO:EL", "Rain Drop", "Rain Drop"),
    ("Deepflow", "Flow the Life 3", "Flow the Life 3"),
    ("Don Mills", "Don Mills Is Angry 3", "Don Mills Is Angry 3"),
]


def main() -> None:
    path = os.path.join(HERE, "pools_2022_2025.py")
    b = load_module("b", path)
    pool = list(b.POOLS[2022])
    before = len(pool)
    filtered = [t for t in pool if norm_key(t[0], t[1]) not in REMOVE_2023_FROM_2022]
    seen = {norm_key(a, t) for a, t, _ in filtered}
    for t in REPLACE_2022:
        k = norm_key(t[0], t[1])
        if k not in seen:
            filtered.append(t)
            seen.add(k)
    print(f"2022 pool: {before} -> {len(filtered)} (removed {before - len([x for x in pool if norm_key(x[0],x[1]) in REMOVE_2023_FROM_2022])})")

    with open(path, encoding="utf-8") as f:
        text = f.read()
    text = rewrite_section(text, "POOLS", 2022, filtered)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("Updated POOLS[2022]")


if __name__ == "__main__":
    main()
