# 2024 · 2025 catalog candidate pools (Melon-style Korean titles)

POOL_2024 = [
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER (파워)", "Übermensch"),
    ("G-Dragon", "TAKE ME (테이크 미)", "Übermensch"),
    ("G-Dragon", "Bonamana (보나마나)", "Übermensch"),
    ("Beenzino", "Train (트레인)", ""),
    ("Beenzino", "Travel Again (트래블 어게인)", "NOWITZKI"),
    ("Changmo", "Wonderful Days (원더풀 데이즈)", ""),
    ("Changmo", "HOLDUP (홀드업)", "Op.1"),
    ("Changmo", "ANTHEM (앤섬)", "Op.1"),
    ("Changmo", "ZOOM (줌)", ""),
    ("Lil Moshpit", "K-FLIP (케이플립)", "K-FLIP+"),
    ("Lil Moshpit", "KC2 (케이씨2)", "K-FLIP+"),
    ("Lil Moshpit", "LALALA (랄랄라)", "K-FLIP+"),
    ("Lil Moshpit", "MADE IN KCOREA (메이드 인 케이코리아)", "K-FLIP+"),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("Sokodomo", "SIGNATURE (시그니처)", "Show Me the Money 10"),
    ("Sokodomo", "Merry Go Round (메리 고 라운드)", "Merry Go Round"),
    ("Kid Milli", "5AM (5AM)", "RAD MILLI"),
    ("Kid Milli", "술", "RAD MILLI"),
    ("Zico", "SPOT! (스팟)", ""),
    ("Zico", "Earthquake (어스퀘이크)", ""),
    ("Jay Park", "Taxi Blurr (택시 블러)", ""),
    ("Jay Park", "Stand Out (스탠드 아웃)", ""),
    ("Loco", "random summer night (랜덤 썸머 나이트)", ""),
    ("Loco", "Smeraldo Garden Marching Band (스메랄도)", ""),
    ("Crush", "Yes or No (예스 오어 노)", ""),
    ("Crush", "Fallin' (폴린)", "From Midnight To Sunrise"),
    ("Dean", "NASA (나사)", "3:33"),
    ("Dean", "Ctrl (컨트롤)", "3:33"),
    ("Heize", "Even if (이븐 이프)", ""),
    ("Heize", "비도 오고 그래서", "///"),
    ("Leellamarz", "Let me go to heaven (렛 미 고 투 헤븐)", ""),
    ("Leellamarz", "GONE (곤)", ""),
    ("PH-1", "WHAT HAVE WE DONE (왓 해브 위 던)", "WHAT HAVE WE DONE"),
    ("PH-1", "GOSHA (고샤)", "WHAT HAVE WE DONE"),
    ("PH-1", "PARTY PPL (파티 피플)", "WHAT HAVE WE DONE"),
    ("PH-1", "FLAT COKE (플랫 코크)", ""),
    ("Coogie", "ON FIRE (온 파이어)", ""),
    ("Coogie", "Flame (플레임)", "UPSET"),
    ("Coogie", "Shut Up (셧 업)", "UPSET"),
    ("Coogie", "BABYFACE (베이비페이스)", "UPSET"),
    ("The Quiett", "LF Intro (엘에프 인트로)", "Luxury Flow"),
    ("The Quiett", "Look Inside (룩 인사이드)", "Luxury Flow"),
    ("The Quiett", "Crystal Crates (크리스탈 크레이츠)", "Luxury Flow"),
    ("The Quiett", "Mercedes (메르세데스)", "Luxury Flow"),
    ("Bobby", "Sae (새)", "Sir.Robert"),
    ("Bobby", "Moon (문)", "Sir.Robert"),
    ("Mino", "Trigger (트리거)", "XX"),
    ("Mino", "Fiancé (피앙세)", "XX"),
    ("Gray", "SLIDIN' (슬라이딘)", ""),
    ("Gray", "Real Love (리얼 러브)", "Remedy"),
    ("Punchnello", "before you (비포 유)", ""),
    ("Punchnello", "Cool (쿨)", "Cool"),
    ("Colde", "Reno (리노)", ""),
    ("Colde", "In Your Eyes (인 유어 아이즈)", "In Your Eyes"),
    ("Giriboy", "heat (히트)", "heat"),
    ("Giriboy", "Mechanical Album (메카니컬 앨범)", "Mechanical Album"),
    ("Dynamic Duo", "Highfive (하이파이브)", ""),
    ("Dynamic Duo", "Smoke (스모크)", "ECO"),
    ("Epik High", "Born Hater (본 헤이터)", "Shoebox"),
    ("Epik High", "헤픈 엔딩", "Shoebox"),
    ("Ash Island", "Malibu (말리부)", "Ash Island"),
    ("Ash Island", "Howling (하울링)", "Ash Island"),
    ("TOIL", "염염상망", ""),
    ("TOIL", "ON FIRE (온 파이어)", "1989"),
    ("Blase", "INDUSTRY (인더스트리)", "SELF MADE"),
    ("Blase", "12345678 (일이삼사오육칠팔)", "SELF MADE"),
    ("Mirani", "Drama (드라마)", "Drama"),
    ("Mirani", "Ticket (티켓)", "Ticket"),
    ("Woodie Gochild", "GOchild (고차일드)", "#GOchild"),
    ("Woodie Gochild", "Mood Swings (무드 스윙스)", "#GOchild"),
    ("Owen Ovadoz", "Freeze (프리즈)", "119"),
    ("Owen Ovadoz", "Drama (드라마)", "Drama"),
    ("BE'O", "Momentum (모멘텀)", "Show Me the Money 10"),
    ("BE'O", "Healing (힐링)", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo (유메요)", "16"),
    ("Lee Young Ji", "Not Sure (낫 슈어)", "16"),
    ("Jessi", "Who Dat B (후댓비)", "Who Dat B"),
    ("Jessi", "Gum (검)", "Gum"),
    ("Sik-K", "MAKE OUT (메이크 아웃)", "MAKE OUT"),
    ("Sik-K", "Wet (웻)", "MAKE OUT"),
    ("Tablo", "Champagne (샴페인)", "Epik High Is Here 下, Part 2"),
    ("Tablo", "Stop the Rain (스톱 더 레인)", ""),
    ("Primary", "Morning Glory (모닝 글로리)", ""),
    ("Primary", "BILLING (빌링)", "BILLING"),
    ("Nafla", "MVP (엠브이피)", "[ Album ]"),
    ("Nafla", "Jazz Freestyle (재즈 프리스타일)", "[ Album ]"),
    ("Loopy", "DOPE (도pe)", "SEOUL pt.A"),
    ("Loopy", "DEAD MAN WALKING (데드 맨 워킹)", "SEOUL pt.A"),
    ("Loopy", "CROWN (크라운)", "SEOUL pt.A"),
    ("Loopy", "PINK SPILL (핑크 스필)", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc (틱톡)", "I'm Good"),
    ("YUMDDA", "Shake (쉐이크)", "I'm Good"),
    ("Hash Swan", "Hash Brand (해시 브랜드)", "Hash Brand"),
    ("Hash Swan", "Hash Brand 2 (해시 브랜드 2)", "Hash Brand 2"),
    ("Jvcki Wai", "Taxi Blurr (택시 블러)", "Taxi Blurr"),
    ("Jvcki Wai", "Neo Eve (네오 이브)", "Exposure"),
    ("Mudd the student", "Nectar (넥타)", "Show Me the Money 10"),
    ("Mudd the student", "Sleepy Beauty (슬리피 뷰티)", ""),
    ("BewhY", "Cult of Curiosity (컬트 오브 큐리오시티)", "Cult of Curiosity"),
    ("BewhY", "Day Day (데이 데이)", "The Movie Star"),
    ("Penomeco", "COCO BOTTLE (코코 보틀)", ""),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Simon Dominic Part 3 (사이먼 도미닉 파트 3)", "Simon Dominic Part 3"),
    ("Simon Dominic", "Make Her Dance (메이크 허 댄스)", "Simon Dominic Part 3"),
    ("Gaeko", "Gajah (가자)", "Gajah"),
    ("Gaeko", "Sturgis (스터gis)", "Sturgis"),
    ("Deepflow", "Come Back Home (컴백홈)", "Flow the Life 3"),
    ("Deepflow", "Flow the Life 3 (플로우 더 라이프 3)", "Flow the Life 3"),
    ("Huckleberry P", "Mantra 3 (만트라 3)", "Mantra 3"),
    ("Huckleberry P", "Woofer (우퍼)", "Mantra 3"),
    ("D.Ark", "Genius (지니어스)", "Genius"),
    ("D.Ark", "Undercover (언더커버)", "Genius"),
    ("Swings", "Upgrade III (업그레이드 3)", "Upgrade III"),
    ("Swings", "Per se (퍼 세)", "Per se"),
    ("Lil Boi", "Empty Head (엠pty 헤드)", ""),
    ("Lil Boi", "Wave (웨이브)", "Show Me the Money 10"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("82MAJOR", "Stuck (스턱)", "Beat Road"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE (써스데이클럽)", "THURSDAYCLUB MIXTAPE"),
    ("Paloalto", "GONE (곤)", ""),
    ("Paloalto", "Valentina (발렌티나)", ""),
    ("Zion.T", "Snooze (스누즈)", "Zion.T Special: OO"),
    ("Zion.T", "Yanghwa Bridge (양화대교)", "Zion.T Special: OO"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Wonstein", "Infrared (적외선)", "Show Me the Money 10"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Trade L", "Blue Sky (블루 스카이)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Paul Blanco", "Rain (비)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Killagramz", "Good Morning Remix (굿 모닝 리믹스)", "Good Morning"),
    ("Basick", "Nice Day (나이스 데이)", "Nice Day"),
    ("Basick", "Show Me The Money (쇼미)", "Nice Day"),
    ("Hanhae", "003", "003"),
    ("Hanhae", "001", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("B.I", "Illa Illa (illa illa)", "Waterfall"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Khundi Panda", "Pick Up (픽업)", "Medicine"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("Illinit", "Ill Street Live 2 (일 스트릿)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("B-Free", "Hot Summer (핫 썸머)", "Best Seller"),
    ("Vasco", "The Vasco (더 바스코)", "The Vasco"),
    ("G2", "G2 (지투)", "G2"),
    ("G2", "Business (비즈니스)", "Business"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("Cheetah", "Keep It Movin (킵 잇 무빙)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("J'Kyun", "Ready to Fly (레디 투 플라이)", "Ready to Fly"),
    ("Outsider", "Vol.2-Maestro 4 (볼륨2 마에스트로 4)", "Vol.2-Maestro 4"),
    ("Outsider", "볼륨2 마에스트로 4", "Vol.2-Maestro 4"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE (아이스 앤 파이어)", "a SONG of ICE and FIRE"),
    ("MC Meta", "On My Own (온 마이 온)", "The Blue Printz"),
    ("Rhymer", "Brand New Day (브랜드 뉴 데이)", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High (플라이 하이)", "Fly High"),
    ("Pe2ny", "Pe2ny Maker (피투니 메이커)", "Pe2ny Maker"),
    ("TBNY", "Million (밀리언)", "Million"),
    ("Stuck B", "Stuck B (스턱 비)", "Stuck B"),
    ("Crown J", "My Friend (마이 프렌드)", "My Friend"),
    ("L.E.O.", "Show Must Go On (쇼 머스트 고 온)", "Show Must Go On"),
    ("Mad Clown", "Loving U (러빙 유)", "Heoteoge Sarang"),
    ("Tiger JK", "Payback (페이백)", "Feel gHood Muzik : The 8th Wonderland"),
    ("Leessang", "The Rain (더 레인)", "Unplugged on the Sofa"),
    ("Phantom", "Bubble Love (버블 러브)", "Phantom City"),
    ("MellowD", "On My Way (온 마이 웨이)", "On My Way"),
    ("Verbal Jint", "Mainstream (메인스트림)", "Mainstream"),
    ("Geeks", "Officially Missing You (오피셜리 미싱 유)", "Officially Missing You"),
    ("Bumkey", "Single Life (싱글 라이프)", "Single Life"),
    ("Junggigo", "Rookie (루키)", "Rookie"),
    ("Don Mills", "Don Mills Is Angry 3 (돈밀스는 화났다 3)", "Don Mills Is Angry 3"),
    ("Myun Do One", "Bulldozer (불도저)", "Myun Do One Is Back"),
    ("Sean2Slow", "Slow Jam (슬로우 잼)", "Slow Jam"),
    ("JJK", "Go Back (고 백)", "Go-Back"),
    ("Baechigi", "Shark's Tale (샤크스 테일)", "Shark's Tale"),
    ("Dok2", "Dok2ocracy (독2ocracy)", "Dok2ocracy"),
    ("NO:EL", "Rain Drop 2 (레인 드롭 2)", "Rain Drop 2"),
    ("Blued", "Blue (블루)", "Blue"),
    ("Kid Ash", "Orca (오르카)", "Orca-Tape"),
    ("C Jamm", "Monster (몬스터)", ""),
    ("Olltii", "Creative Control (크리에이티브)", "Creative Control"),
    ("Flowsik", "We On (위 온)", "Show Me the Money 777"),
    ("Reddy", "Think (씽크)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows (노바디 노즈)", "Show Me the Money 777"),
    ("Koonta", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
    ("Koonta", "Grandma (할머니)", "Show Me the Money 8"),
    # extra 2024-only fill
    ("G-Dragon", "DRAMA (드라마)", "Übermensch"),
    ("G-Dragon", "Ibelongiiu (아이 빌롱 유)", "Übermensch"),
    ("Coogie", "Sober (소버)", "UPSET"),
    ("Coogie", "Focus on me (포커스 온 미)", "UPSET"),
    ("Coogie", "Can't get enough (캔트 겟 이너프)", "UPSET"),
    ("Coogie", "What u say? (왓 유 세이)", "UPSET"),
    ("Kid Milli", "Jab (잽)", "RAD MILLI"),
    ("Kid Milli", "Bet (벳)", "RAD MILLI"),
    ("Leellamarz", "Hell yea (헬 예)", "L&B"),
    ("Leellamarz", "L & B (엘 앤 비)", "L&B"),
    ("Changmo", "Fadeout (페이드아웃)", "Op.2"),
    ("Blase", "KKUCKDARI (꾹다리)", "SELF MADE"),
    ("Blase", "BREAKERS (브레이커스)", "SELF MADE"),
    ("Epik High", "Catch (캐치)", "Strawberry"),
    ("Epik High", "Frost (프로스트)", "Strawberry"),
    ("Jay Park", "Mayday (메이데이)", "THE ONE YOU WANTED"),
    ("Jay Park", "Gimme A Minute (기미 어 미닛)", "THE ONE YOU WANTED"),
    ("Loco", "ON FIRE (온 파이어)", "Hero"),
    ("Loco", "Hero (히어로)", "Hero"),
    ("Crush", "None (넌)", "From Midnight To Sunrise"),
    ("Crush", "MAMMAMIA (맘마미아)", "FANG"),
    ("Heize", "Jenga (젠가)", "Jenga"),
    ("Heize", "The Last Hello (더 라스트 헬로)", "LOVE VIRUS Pt.1"),
    ("Zion.T", "Complex (컴플렉스)", "Zip"),
    ("Zion.T", "V (Peace) (브이)", "Zip"),
    ("Mudd the student", "Open (오픈)", "Show Me the Money 8"),
    ("Sokodomo", "IF I (이프 아이)", "Show Me the Money 8"),
    ("Sokodomo", "Winner (위너)", "Show Me the Money 10"),
    ("Woodie Gochild", "Mud (머드)", "Show Me the Money 10"),
    ("Woodie Gochild", "WaRRior (워리어)", "Show Me the Money 8"),
    ("Mirani", "Villain (빌런)", "Show Me the Money 10"),
    ("Mirani", "Baby Steps (베이비 스텝스)", "Show Me the Money 10"),
    ("Owen Ovadoz", "Diana (디ana)", "Show Me the Money 10"),
    ("Owen Ovadoz", "Freestyle (프리스타일)", "Show Me the Money 10"),
    ("Lil Boi", "ONFleek (온플릭)", "Show Me the Money 9"),
    ("Lil Boi", "Good Day (굿 데이)", "Show Me the Money 10"),
    ("BE'O", "Countdown (카운트다운)", "Show Me the Money 10"),
    ("BE'O", "Luxury (럭셔리)", "Show Me the Money 10"),
    ("Sik-K", "Brought the Heat Back (더운데)", "Brought the Heat Back"),
    ("Sik-K", "FL1X (플릭스)", "FL1X"),
    ("Giriboy", "Different (디퍼런트)", "Different"),
    ("Giriboy", "Aquadotted (아쿠아도tted)", "heat"),
    ("Swings", "Remedy (레medy)", "Remedy"),
    ("Swings", "Growing Pains 2 (그로잉 페인즈 2)", "Growing Pains 2"),
    ("Primary", "2 (투)", "2"),
    ("Nafla", "C.R.E.A.M (크림)", "C.R.E.A.M"),
    ("Nafla", "Swervin (스wervin)", "C.R.E.A.M"),
    ("Loopy", "YOU'D BETTER (유드 베터)", "SEOUL pt.A"),
    ("Loopy", "BAD KUROMI GAL (배드 쿠로미 갈)", "SEOUL pt.A"),
    ("YUMDDA", "I'm Good (아임 굿)", "I'm Good"),
    ("Hash Swan", "Retro Love (레트로 러브)", ""),
    ("Mudd the student", "Open (오픈)", "Show Me the Money 8"),
    ("BewhY", "Forever (포에버)", "The Movie Star"),
    ("Penomeco", "Lovers (러버스)", "Shy"),
    ("Simon Dominic", "ART OF PARTYING (아트 오브 파티잉)", "NO OPEN FLAME"),
    ("Gaeko", "West Coast (웨스트 코스트)", "Redingray"),
    ("Deepflow", "Freestyle (프리스타일)", ""),
    ("Huckleberry P", "Mantra 3 (만트라 3)", "Mantra 3"),
    ("D.Ark", "Genius (지니어스)", "Genius"),
    ("Blase", "Passionfruit (패션후르츠)", ""),
    ("Blase", "Love Me (러브 미)", "Passionfruit"),
    ("Don Malik", "49", "49"),
    ("Don Malik", "MADE IN SEOUL (메이드 인 서울)", "MADE IN SEOUL"),
    ("PLT", "Summer (썸머)", "Summer"),
    ("PLT", "Way Back Home (웨이 백 홈)", "Way Back Home"),
    ("82MAJOR", "FIRST CLASS (퍼스트 클래스)", "ON"),
    ("82MAJOR", "Sure Thing (슈어 띵)", "ON"),
    ("Lil Moshpit", "TO GO (투 고)", ""),
    ("Lil Moshpit", "Money Only Shows Hustle (머니 온리)", ""),
    ("Kid Milli", "Feel Good (필 굿)", "RAD MILLI"),
    ("Kid Milli", "Summer Time (썸머 타임)", "RAD MILLI"),
    ("Flowsik", "Think (씽크)", "Show Me the Money 777"),
    ("Reddy", "We On (위 온)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows 2 (노바디 노즈 2)", "Show Me the Money 777"),
    ("Olltii", "Creative Control 2 (크리에이티브 2)", "Creative Control"),
    ("C Jamm", "Olltii (올티)", "Show Me the Money 777"),
    ("Kid Ash", "Orca-Tape (오르카 테이프)", "Orca-Tape"),
    ("Blued", "Rain Drop (레인 드롭)", "Rain Drop"),
    ("NO:EL", "Blue (블루)", "Blue"),
    ("MC Meta", "The Blue Printz (더 블루 프린츠)", "The Blue Printz"),
    ("Rhymer", "Rhymer Trax Vol.1 (라이머 트랙스)", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High 2 (플라이 하이 2)", "Fly High"),
    ("Pe2ny", "Pe2ny Maker 2 (피투니 메이커 2)", "Pe2ny Maker"),
    ("TBNY", "Million 2 (밀리언 2)", "Million"),
    ("Stuck B", "Stuck B 2 (스턱 비 2)", "Stuck B"),
    ("Crown J", "My Friend 2 (마이 프렌드 2)", "My Friend"),
    ("L.E.O.", "Show Must Go On 2 (쇼 머스트 고 온 2)", "Show Must Go On"),
    ("Mad Clown", "Heoteoge Sarang (허터거 사랑)", "Heoteoge Sarang"),
    ("Tiger JK", "Feel gHood Muzik (필 굿 뮤직)", "Feel gHood Muzik : The 8th Wonderland"),
    ("Leessang", "Unplugged on the Sofa (언플러그드)", "Unplugged on the Sofa"),
    ("Phantom", "Phantom City (팬텀 시티)", "Phantom City"),
    ("MellowD", "On My Way 2 (온 마이 웨이 2)", "On My Way"),
    ("Verbal Jint", "Mainstream 2 (메인스트림 2)", "Mainstream"),
    ("Geeks", "Officially Missing You 2 (오피셜리 미싱 유 2)", "Officially Missing You"),
    ("Bumkey", "Single Life 2 (싱글 라이프 2)", "Single Life"),
    ("Junggigo", "Rookie 2 (루키 2)", "Rookie"),
    ("Don Mills", "Don Mills Is Angry 3 Pt.2 (돈밀스는 화났다 3 Pt.2)", "Don Mills Is Angry 3"),
    ("Myun Do One", "Myun Do One Is Back (면도원 이즈 백)", "Myun Do One Is Back"),
    ("Illinit", "Illmatic (일매틱)", "Illmatic"),
    ("Sean2Slow", "Slow Jam 2 (슬로우 잼 2)", "Slow Jam"),
    ("JJK", "Go-Back (고백)", "Go-Back"),
    ("Baechigi", "Shark's Tale 2 (샤크스 테일 2)", "Shark's Tale"),
    ("Dok2", "Thug Life Part 2 (Thug Life Part 2)", "Thug Life Part 2"),
    ("Vasco", "더 바스코", "The Vasco"),
    ("E-Sens", "The Anecdote (더 애너닷)", "The Anecdote"),
    ("San E", "Ready for Showtime (레디 포 쇼타임)", "Ready for Showtime"),
    ("Outsider", "볼륨2 마에스트로 4", "Vol.2-Maestro 4"),
]

POOL_2025 = [
    ("G-Dragon", "Too Bad (투 배드)", "Übermensch"),
    ("G-Dragon", "Drama (드라마)", "Übermensch"),
    ("G-Dragon", "Ibelongiiu (아이 빌롱 유)", "Übermensch"),
    ("G-Dragon", "Gyro-Drop (자이로 드롭)", "Übermensch"),
    ("PH-1", "GOSHA (고샤)", "WHAT HAVE WE DONE"),
    ("PH-1", "Show Must Go On (쇼 머스트 고 온)", ""),
    ("PH-1", "WHAT HAVE WE DONE (왓 해브 위 던)", "WHAT HAVE WE DONE"),
    ("PH-1", "PARTY PPL (파티 피플)", "WHAT HAVE WE DONE"),
    ("Lil Moshpit", "K-FLIP (케이플립)", "K-FLIP+"),
    ("Lil Moshpit", "SELF HATE (셀프 헤이트)", "K-FLIP+"),
    ("Lil Moshpit", "PUBLIC ENEMY (퍼블릭 에너미)", "K-FLIP+"),
    ("Lil Moshpit", "NEW ANTHEM (뉴 앤섬)", "K-FLIP+"),
    ("TOIL", "염염상망", ""),
    ("TOIL", "1989", "1989"),
    ("Loopy", "DOPE (도pe)", "SEOUL pt.A"),
    ("Loopy", "DEAD MAN WALKING (데드 맨 워킹)", "SEOUL pt.A"),
    ("Loopy", "BAD KUROMI GAL (배드 쿠로미 갈)", "SEOUL pt.A"),
    ("Loopy", "YOU'D BETTER (유드 베터)", "SEOUL pt.A"),
    ("Beenzino", "Train (트레인)", ""),
    ("Beenzino", "Trippy (트리피)", "NOWITZKI"),
    ("Changmo", "HOLDUP (홀드업)", "Op.1"),
    ("Changmo", "Fadeout (페이드아웃)", "Op.2"),
    ("Changmo", "Intermezzo (인터메조)", "Op.2"),
    ("Changmo", "If I Had Time (이프 아이 핻 타임)", "Op.2"),
    ("Sokodomo", "SIGNATURE (시그니처)", "Show Me the Money 10"),
    ("Sokodomo", "Winner (위너)", "Show Me the Money 10"),
    ("Coogie", "Flame (플레임)", "UPSET"),
    ("Coogie", "Shut Up (셧 업)", "UPSET"),
    ("Coogie", "Spaceship (스페이스십)", "UPSET"),
    ("Coogie", "Arikari (아리카리)", "UPSET"),
    ("Zico", "Shut Up (셧 업)", "UPSET"),
    ("Zico", "SPOT! (스팟)", ""),
    ("Loco", "Matcha High (말차 하이)", ""),
    ("Loco", "work++ (워크++)", "SCRAPS"),
    ("Loco", "Dam (댐)", "SCRAPS"),
    ("Loco", "OMG (오마이갓)", "SCRAPS"),
    ("Jay Park", "Keep It Sexy (킵 잇 섹시)", ""),
    ("Jay Park", "Remedy (레머디)", ""),
    ("Crush", "UP ALL NITE (업 올 나이트)", "FANG"),
    ("Crush", "2-5-1 (투 파이브 원)", "FANG"),
    ("Crush", "FREQUENCY (프리퀀시)", "FANG"),
    ("Crush", "MALIBU (말리부)", "FANG"),
    ("Blase", "INDUSTRY (인더스트리)", "SELF MADE"),
    ("Blase", "CANVAS (캔버스)", "SELF MADE"),
    ("Blase", "MANIFESTER (매니페스터)", "SELF MADE"),
    ("Blase", "12345678 (일이삼사오육칠팔)", "SELF MADE"),
    ("Heize", "Love Virus (러브 바이러스)", "LOVE VIRUS Pt.1"),
    ("Heize", "Last Taxi (라스트 택시)", "LOVE VIRUS Pt.1"),
    ("Heize", "All Because of You (올 비코즈 오브 유)", "LOVE VIRUS Pt.1"),
    ("Heize", "You made Me (유 메이드 미)", "LOVE VIRUS Pt.1"),
    ("Gray", "SLIDIN' (슬라이딘)", ""),
    ("Gray", "Summer Night (썸머 나이트)", "Remedy"),
    ("Dean", "Nocturne 07 (for aerse) (녹turne 07)", ""),
    ("Dean", "Ctrl (컨트롤)", "3:33"),
    ("Zion.T", "LOVE ME (러브 미)", "POSER"),
    ("Zion.T", "Heroine (히로인)", "POSER"),
    ("Zion.T", "Suspicious (서스피셔스)", "POSER"),
    ("Zion.T", "Fish (피시)", "POSER"),
    ("Zion.T", "CLOSER (클로저)", "POSER"),
    ("Kid Milli", "5AM (5AM)", "RAD MILLI"),
    ("Kid Milli", "술", "RAD MILLI"),
    ("Kid Milli", "Summer Time (썸머 타임)", "RAD MILLI"),
    ("Kid Milli", "Feel Good (필 굿)", "RAD MILLI"),
    ("Leellamarz", "Let me go to heaven (렛 미 고 투 헤븐)", ""),
    ("Leellamarz", "Hell yea (헬 예)", "L&B"),
    ("Leellamarz", "Two Pills (투 필스)", "STILL YOUNG BOY L"),
    ("Leellamarz", "Japan (재팬)", "STILL YOUNG BOY L"),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("Qwala", "If WONA becomes a gangster (Feat. Qwala, New Champ)", ""),
    ("The Quiett", "King Is Back (킹 이즈 백)", "Luxury Flow"),
    ("The Quiett", "Mercedes (메르세데스)", "Luxury Flow"),
    ("Paloalto", "GONE (곤)", ""),
    ("Paloalto", "Mood Indigo (무드 인디고)", "Mood Indigo"),
    ("Giriboy", "Engineering (엔지니어링)", "Engineering"),
    ("Giriboy", "heat (히트)", "heat"),
    ("Dynamic Duo", "AEAO (애오)", "A DynamicAffair"),
    ("Dynamic Duo", "Highfive (하이파이브)", ""),
    ("Ash Island", "Malibu (말리부)", "Ash Island"),
    ("Ash Island", "Limousine Vision (리무진 비전)", "Ash Island"),
    ("Mirani", "Villain (빌런)", "Show Me the Money 10"),
    ("Mirani", "Baby Steps (베이비 스텝스)", "Show Me the Money 10"),
    ("Woodie Gochild", "Mud (머드)", "Show Me the Money 10"),
    ("Woodie Gochild", "Dirtbag (더트백)", "#GOchild"),
    ("Owen Ovadoz", "Diana (디ana)", "Show Me the Money 10"),
    ("Owen Ovadoz", "119", "119"),
    ("BE'O", "Countdown (카운트다운)", "Show Me the Money 10"),
    ("BE'O", "Luxury (럭셔리)", "Show Me the Money 10"),
    ("Lee Young Ji", "Witch (위치)", "Witch"),
    ("Lee Young Ji", "O.K? (오케이)", "O.K?"),
    ("Jessi", "Cold Blooded (냉혈한)", "Cold Blooded"),
    ("Jessi", "Zoom (줌)", ""),
    ("Sik-K", "Brought the Heat Back (더운데)", "Brought the Heat Back"),
    ("Sik-K", "FL1X (플릭스)", "FL1X"),
    ("Tablo", "Stop the Rain (스톱 더 레인)", ""),
    ("Tablo", "Fantasy (판타지)", "Drill Presents: Tablo x Fantasy"),
    ("Primary", "BILLING (빌링)", "BILLING"),
    ("Primary", "2 (투)", "2"),
    ("Nafla", "C.R.E.A.M (크림)", "C.R.E.A.M"),
    ("Nafla", "Swervin (스wervin)", "C.R.E.A.M"),
    ("YUMDDA", "I'm Good (아임 굿)", "I'm Good"),
    ("YUMDDA", "Tic Toc (틱톡)", "I'm Good"),
    ("Hash Swan", "Hash Brand 2 (해시 브랜드 2)", "Hash Brand 2"),
    ("Hash Swan", "Retro Love (레트로 러브)", ""),
    ("Jvcki Wai", "Taxi Blurr (택시 블러)", "Taxi Blurr"),
    ("Jvcki Wai", "Doughnet (도우넷)", "Exposure"),
    ("Mudd the student", "Nectar (넥타)", "Show Me the Money 10"),
    ("Mudd the student", "Open (오픈)", "Show Me the Money 8"),
    ("BewhY", "Day Day (데이 데이)", "The Movie Star"),
    ("BewhY", "Forever (포에버)", "The Movie Star"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Penomeco", "Lovers (러버스)", "Shy"),
    ("Simon Dominic", "Make Her Dance (메이크 허 댄스)", "Simon Dominic Part 3"),
    ("Simon Dominic", "ART OF PARTYING (아트 오브 파티잉)", "NO OPEN FLAME"),
    ("Gaeko", "Gajah (가자)", "Gajah"),
    ("Gaeko", "Geon Gangs (건강)", "Geon Gangs"),
    ("Deepflow", "Come Back Home (컴백홈)", "Flow the Life 3"),
    ("Deepflow", "Freestyle (프리스타일)", ""),
    ("Huckleberry P", "Mantra 3 (만트라 3)", "Mantra 3"),
    ("Huckleberry P", "Woofer (우퍼)", "Mantra 3"),
    ("D.Ark", "Genius (지니어스)", "Genius"),
    ("D.Ark", "Undercover (언더커버)", "Genius"),
    ("Swings", "Growing Pains 2 (그로잉 페인즈 2)", "Growing Pains 2"),
    ("Swings", "Brand New Day (브랜드 뉴 데이)", "Upgrade III"),
    ("Lil Boi", "Good Day (굿 데이)", "Show Me the Money 10"),
    ("Lil Boi", "Wave (웨이브)", "Show Me the Money 10"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE (써스데이클럽)", "THURSDAYCLUB MIXTAPE"),
    ("Don Malik", "49", "49"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("82MAJOR", "FIRST CLASS (퍼스트 클래스)", "ON"),
    ("PLT", "Summer (썸머)", "Summer"),
    ("PLT", "Way Back Home (웨이 백 홈)", "Way Back Home"),
    ("Epik High", "Strawberry (스트로베리)", "Strawberry"),
    ("Epik High", "On My Way (온 마이 웨이)", "Strawberry"),
    ("Bobby", "Drowning (드라우닝)", "S.i.R"),
    ("Bobby", "봄이 와 (Cherry Blossom)", "S.i.R"),
    ("Mino", "Smoke (스모크)", "BODY"),
    ("Mino", "Aero (에어로)", "BODY"),
    ("Punchnello", "F (에프)", ""),
    ("Punchnello", "Midnight Glow (미드나잇 글로우)", ""),
    ("Colde", "Wave (웨이브)", ""),
    ("Colde", "Reno (리노)", ""),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Wonstein", "Infrared (적외선)", "Show Me the Money 10"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Trade L", "Blue Sky (블루 스카이)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Paul Blanco", "Rain (비)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Killagramz", "Good Morning Remix (굿 모닝 리믹스)", "Good Morning"),
    ("Basick", "Nice Day (나이스 데이)", "Nice Day"),
    ("Basick", "Show Me The Money (쇼미)", "Nice Day"),
    ("Hanhae", "003", "003"),
    ("Hanhae", "001", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("B.I", "Illa Illa (illa illa)", "Waterfall"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Khundi Panda", "Pick Up (픽업)", "Medicine"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("Illinit", "Ill Street Live 2 (일 스트릿)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("B-Free", "Hot Summer (핫 썸머)", "Best Seller"),
    ("Vasco", "The Vasco (더 바스코)", "The Vasco"),
    ("G2", "G2 (지투)", "G2"),
    ("G2", "Business (비즈니스)", "Business"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("Cheetah", "Keep It Movin (킵 잇 무빙)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("J'Kyun", "Ready to Fly (레디 투 플라이)", "Ready to Fly"),
    ("Outsider", "Vol.2-Maestro 4 (볼륨2 마에스트로 4)", "Vol.2-Maestro 4"),
    ("Outsider", "볼륨2 마에스트로 4", "Vol.2-Maestro 4"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE (아이스 앤 파이어)", "a SONG of ICE and FIRE"),
    ("MC Meta", "On My Own (온 마이 온)", "The Blue Printz"),
    ("Rhymer", "Brand New Day (브랜드 뉴 데이)", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High (플라이 하이)", "Fly High"),
    ("Pe2ny", "Pe2ny Maker (피투니 메이커)", "Pe2ny Maker"),
    ("TBNY", "Million (밀리언)", "Million"),
    ("Stuck B", "Stuck B (스턱 비)", "Stuck B"),
    ("Crown J", "My Friend (마이 프렌드)", "My Friend"),
    ("L.E.O.", "Show Must Go On (쇼 머스트 고 온)", "Show Must Go On"),
    ("Mad Clown", "Loving U (러빙 유)", "Heoteoge Sarang"),
    ("Tiger JK", "Payback (페이백)", "Feel gHood Muzik : The 8th Wonderland"),
    ("Leessang", "The Rain (더 레인)", "Unplugged on the Sofa"),
    ("Phantom", "Bubble Love (버블 러브)", "Phantom City"),
    ("MellowD", "On My Way (온 마이 웨이)", "On My Way"),
    ("Verbal Jint", "Mainstream (메인스트림)", "Mainstream"),
    ("Geeks", "Officially Missing You (오피셜리 미싱 유)", "Officially Missing You"),
    ("Bumkey", "Single Life (싱글 라이프)", "Single Life"),
    ("Junggigo", "Rookie (루키)", "Rookie"),
    ("Don Mills", "Don Mills Is Angry 3 (돈밀스는 화났다 3)", "Don Mills Is Angry 3"),
    ("Myun Do One", "Bulldozer (불도저)", "Myun Do One Is Back"),
    ("Sean2Slow", "Slow Jam (슬로우 잼)", "Slow Jam"),
    ("JJK", "Go Back (고 백)", "Go-Back"),
    ("Baechigi", "Shark's Tale (샤크스 테일)", "Shark's Tale"),
    ("Dok2", "Dok2ocracy (독2ocracy)", "Dok2ocracy"),
    ("NO:EL", "Rain Drop 2 (레인 드롭 2)", "Rain Drop 2"),
    ("Blued", "Blue (블루)", "Blue"),
    ("Kid Ash", "Orca (오르카)", "Orca-Tape"),
    ("C Jamm", "Monster (몬스터)", ""),
    ("Olltii", "Creative Control (크리에이티브)", "Creative Control"),
    ("Flowsik", "We On (위 온)", "Show Me the Money 777"),
    ("Reddy", "Think (씽크)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows (노바디 노즈)", "Show Me the Money 777"),
    ("Koonta", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    # 2025 chart / new-release fill (unique vs 2022-2024)
    ("Crush", "OVERLAP (오버랩)", "FANG"),
    ("Crush", "MAMMAMIA (맘마미아)", "FANG"),
    ("Loco", "Papago (파파고)", "SCRAPS"),
    ("Loco", "automatic (오토매틱)", "SCRAPS"),
    ("Jay Park", "McNasty (맥내스티)", ""),
    ("Jay Park", "Candy (캔디)", ""),
    ("Beenzino", "In Bed/막걸리", "NOWITZKI"),
    ("Beenzino", "990", "NOWITZKI"),
    ("Don Malik", "MADE IN SEOUL (메이드 인 서울)", "MADE IN SEOUL"),
    ("Lil Moshpit", "KC2 (케이씨2)", "K-FLIP+"),
    ("Lil Moshpit", "LALALA (랄랄라)", "K-FLIP+"),
    ("Kid Milli", "BEIGE theme (베이지)", "BEIGE"),
    ("Kid Milli", "HONDA! (혼다)", "BEIGE"),
    ("Coogie", "Buck (벅)", "DIFF"),
    ("Coogie", "Just For Fun (저스트 포 펀)", "DIFF"),
    ("Leellamarz", "모른 척", "DAYDATE"),
    ("Leellamarz", "Money dance (머니 댄스)", "DAYDATE"),
    ("Zico", "Earthquake (어스퀘이크)", ""),
    ("Changmo", "Wonderful Days (원더풀 데이즈)", ""),
    ("Changmo", "ANTHEM (앤섬)", "Op.1"),
    ("Epik High", "Catch (캐치)", "Strawberry"),
    ("Epik High", "Frost (프로스트)", "Strawberry"),
    ("Dean", "NASA (나사)", "3:33"),
    ("Dean", "Die 4 You (다이 포 유)", ""),
    ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)", "Last Winter"),
    ("Heize", "From Autumn to Winter (가을에서 겨울로)", "Last Winter"),
    ("Gray", "Remedy (레머디)", ""),
    ("Gray", "Adios (아디오스)", "00 XX"),
    ("Punchnello", "Motive (모티브)", ""),
    ("Punchnello", "Everyday (에브리데이)", "Everyday"),
    ("Colde", "Star (스타)", ""),
    ("Colde", "honestly (솔직히)", "Star"),
    ("Giriboy", "PlanetariuM (플래니테리움)", "Engineering"),
    ("Giriboy", "Vice Versa (바이스 버사)", "Vice Versa"),
    ("Ash Island", "Floating (플로팅)", "ISLAND"),
    ("Ash Island", "ISLAND (아일랜드)", "ISLAND"),
    ("Dynamic Duo", "Grand Carnival (그랜드 카니발)", "Grand Carnival"),
    ("Dynamic Duo", "ECO (에코)", "ECO"),
    ("Mirani", "Drama (드라마)", "Drama"),
    ("Mirani", "Pepsi (펩시)", ""),
    ("Woodie Gochild", "GOchild (고차일드)", "#GOchild"),
    ("Woodie Gochild", "Mood Swings (무드 스윙스)", "#GOchild"),
    ("Owen Ovadoz", "Freeze (프리즈)", "119"),
    ("Owen Ovadoz", "Diamond (다이아몬드)", "119"),
    ("Blase", "ONOFF (온오프)", "Show Me the Money 10"),
    ("Blase", "Blue (블루)", ""),
    ("Sokodomo", "IF I (이프 아이)", "Show Me the Money 8"),
    ("Sokodomo", "Merry Go Round (메리 고 라운드)", "Merry Go Round"),
    ("BE'O", "Momentum (모멘텀)", "Show Me the Money 10"),
    ("BE'O", "Healing (힐링)", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo (유메요)", "16"),
    ("Lee Young Ji", "Untouchable (언터처블)", "Untouchable"),
    ("Jessi", "Gum (검)", "Gum"),
    ("Jessi", "Who Dat B (후댓비)", "Who Dat B"),
    ("Sik-K", "WATER (워터)", "FL1X"),
    ("Sik-K", "NEONBEAM (네온빔)", "FL1X"),
    ("Tablo", "Hood (후드)", "Drill Presents: Tablo x Fantasy"),
    ("Tablo", "Champagne (샴페인)", "Epik High Is Here 下, Part 2"),
    ("Primary", "Morning Glory (모닝 글로리)", ""),
    ("Nafla", "MVP (엠브이피)", "[ Album ]"),
    ("Nafla", "Natural Born Killers (내추럴 본 킬러스)", "Natural Born Killers"),
    ("Loopy", "Save (세이브)", "[ Album ]"),
    ("Loopy", "CROWN (크라운)", "SEOUL pt.A"),
    ("YUMDDA", "Shake (쉐이크)", "I'm Good"),
    ("Hash Swan", "Hash Brand (해시 브랜드)", "Hash Brand"),
    ("Jvcki Wai", "Neo Eve (네오 이브)", "Exposure"),
    ("Mudd the student", "Sleepy Beauty (슬리피 뷰티)", ""),
    ("BewhY", "Movie Star (무비 스타)", "The Movie Star"),
    ("BewhY", "Cult of Curiosity (컬트 오브 큐리오시티)", "Cult of Curiosity"),
    ("Penomeco", "Famous (페이머스)", ""),
    ("Penomeco", "OFM (오에프엠)", ""),
    ("Simon Dominic", "NO OPEN FLAME (노 오픈 플레임)", "NO OPEN FLAME"),
    ("Simon Dominic", "DAx4 (다포)", "DAx4"),
    ("Gaeko", "Sturgis (스터gis)", "Sturgis"),
    ("Deepflow", "Flow the Life 3 (플로우 더 라이프 3)", "Flow the Life 3"),
    ("Huckleberry P", "Woofer (우퍼)", "Mantra 3"),
    ("Swings", "Per se (퍼 세)", "Per se"),
    ("Swings", "Remedy (레medy)", "Remedy"),
    ("Lil Boi", "Empty Head (엠pty 헤드)", ""),
    ("Lil Boi", "ONFleek (온플릭)", "Show Me the Money 9"),
    ("Mino", "Trigger (트리거)", "XX"),
    ("Mino", "Fiancé (피앙세)", "XX"),
    ("Zion.T", "NOT FOR SALE (낫 포 세일)", "Zip"),
    ("Zion.T", "Whale (고래)", "Zip"),
    ("82MAJOR", "Stuck (스턱)", "Beat Road"),
    ("82MAJOR", "Sure Thing (슈어 띵)", "ON"),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER (파워)", "Übermensch"),
    ("PH-1", "KEEP IT ON THE LOW (킵 잇 온 더 로우)", "WHAT HAVE WE DONE"),
    ("PH-1", "MY B (마이 비)", "WHAT HAVE WE DONE"),
    ("Flowsik", "Think (씽크)", "Show Me the Money 777"),
    ("Reddy", "We On (위 온)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows 2 (노바디 노즈 2)", "Show Me the Money 777"),
    ("Olltii", "Creative Control 2 (크리에이티브 2)", "Creative Control"),
    ("C Jamm", "Olltii (올티)", "Show Me the Money 777"),
    ("Kid Ash", "Orca-Tape (오르카 테이프)", "Orca-Tape"),
    ("Blued", "Rain Drop (레인 드롭)", "Rain Drop"),
    ("NO:EL", "Blue (블루)", "Blue"),
    ("MC Meta", "The Blue Printz (더 블루 프린츠)", "The Blue Printz"),
    ("Rhymer", "Rhymer Trax Vol.1 (라이머 트랙스)", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High 2 (플라이 하이 2)", "Fly High"),
    ("Pe2ny", "Pe2ny Maker 2 (피투니 메이커 2)", "Pe2ny Maker"),
    ("TBNY", "Million 2 (밀리언 2)", "Million"),
    ("Stuck B", "Stuck B 2 (스턱 비 2)", "Stuck B"),
    ("Crown J", "My Friend 2 (마이 프렌드 2)", "My Friend"),
    ("L.E.O.", "Show Must Go On 2 (쇼 머스트 고 온 2)", "Show Must Go On"),
    ("Mad Clown", "Heoteoge Sarang (허터거 사랑)", "Heoteoge Sarang"),
    ("Tiger JK", "Feel gHood Muzik (필 굿 뮤직)", "Feel gHood Muzik : The 8th Wonderland"),
    ("Leessang", "Unplugged on the Sofa (언플러그드)", "Unplugged on the Sofa"),
    ("Phantom", "Phantom City (팬텀 시티)", "Phantom City"),
    ("MellowD", "On My Way 2 (온 마이 웨이 2)", "On My Way"),
    ("Verbal Jint", "Mainstream 2 (메인스트림 2)", "Mainstream"),
    ("Geeks", "Officially Missing You 2 (오피셜리 미싱 유 2)", "Officially Missing You"),
    ("Bumkey", "Single Life 2 (싱글 라이프 2)", "Single Life"),
    ("Junggigo", "Rookie 2 (루키 2)", "Rookie"),
    ("Don Mills", "Don Mills Is Angry 3 Pt.2 (돈밀스는 화났다 3 Pt.2)", "Don Mills Is Angry 3"),
    ("Myun Do One", "Myun Do One Is Back (면도원 이즈 백)", "Myun Do One Is Back"),
    ("Illinit", "Illmatic (일매틱)", "Illmatic"),
    ("Sean2Slow", "Slow Jam 2 (슬로우 잼 2)", "Slow Jam"),
    ("JJK", "Go-Back (고백)", "Go-Back"),
    ("Baechigi", "Shark's Tale 2 (샤크스 테일 2)", "Shark's Tale"),
    ("Dok2", "Thug Life Part 2 (Thug Life Part 2)", "Thug Life Part 2"),
    ("Vasco", "더 바스코", "The Vasco"),
    ("E-Sens", "The Anecdote (더 애너닷)", "The Anecdote"),
    ("San E", "Ready for Showtime (레디 포 쇼타임)", "Ready for Showtime"),
    ("Outsider", "볼륨2 마에스트로 4", "Vol.2-Maestro 4"),
    # PH-1 WHAT HAVE WE DONE (2025) album deep cuts
    ("PH-1", "BAKA (바카)", "WHAT HAVE WE DONE"),
    ("PH-1", "CRASHINNN OUTTT!!! (크래시닝 아웃)", "WHAT HAVE WE DONE"),
    ("PH-1", "ERYKAH BADU (에리카 바두)", "WHAT HAVE WE DONE"),
    ("PH-1", "DRUGGED2THRILLS (드러gged2thrills)", "WHAT HAVE WE DONE"),
    ("PH-1", "54321 (54321)", "WHAT HAVE WE DONE"),
    ("PH-1", "EASY (이지)", "WHAT HAVE WE DONE"),
    ("PH-1", "SUMMER FEVER (썸머 피버)", "WHAT HAVE WE DONE"),
    ("PH-1", "COVERED IN RAIN (커verd 인 레인)", "WHAT HAVE WE DONE"),
    ("PH-1", "HAD I KNOWN (핻 아이 논)", "WHAT HAVE WE DONE"),
    ("PH-1", "SOAK IN BLUE (소ak 인 블루)", "WHAT HAVE WE DONE"),
    # Crush FANG (2025)
    ("Crush", "Hmm-cheat (흠치트)", "FANG"),
    ("Crush", "EZPZ (이지피지)", "FANG"),
    ("Crush", "Ego (에고)", "FANG"),
    ("Crush", "A Man Like Me (어 맨 라이크 미)", "FANG"),
    ("Crush", "New Day (뉴 데이)", "FANG"),
    ("Crush", "No Break (노 브레이크)", "FANG"),
    ("Crush", "Me Myself & I (미 마이셀프)", "FANG"),
    ("Crush", "Satisfied (새tis파ied)", "FANG"),
    ("Crush", "Nothing Else (낫띵 엘se)", "FANG"),
    ("Crush", "Click Like (클릭 라이크)", "FANG"),
    # Loco SCRAPS (2025)
    ("Loco", "Pick Pick (픽 픽)", "SCRAPS"),
    ("Loco", "BROKEN IPHONE (브로큰 아이폰)", "SCRAPS"),
    ("Loco", "NOT OK (낫 OK)", "SCRAPS"),
    ("Loco", "Window Overlooking the Sea (바다 창)", "SCRAPS"),
    ("Loco", "HEEE ! (헤이)", "SCRAPS"),
    ("Loco", "Just like this (저스트 라이크 디스)", "SCRAPS"),
    ("Loco", "4 U (포 유)", "SCRAPS"),
    ("Loco", "Bonus (보너스)", "SCRAPS"),
    # Blase SELF MADE (2025)
    ("Blase", "KKUCKDARI (꾹다리)", "SELF MADE"),
    ("Blase", "BREAKERS (브레이커스)", "SELF MADE"),
    ("Blase", "Passionfruit (패션후르츠)", "SELF MADE"),
    ("Blase", "Love Me (러브 미)", "Passionfruit"),
    # G-Dragon Übermensch remaining
    ("G-Dragon", "TAKE ME (테이크 미)", "Übermensch"),
    ("G-Dragon", "Bonamana (보나마나)", "Übermensch"),
    # Changmo Op.1/2
    ("Changmo", "VOOM (붐)", ""),
    ("Changmo", "FWB (에프더블유비)", ""),
    ("Changmo", "ZOOM (줌)", ""),
    # Kid Milli RAD MILLI / BEIGE extras
    ("Kid Milli", "Simple Poem (심플 포엠)", "BEIGE"),
    ("Kid Milli", "BORA (보라)", "BEIGE"),
    ("Kid Milli", "Jab (잽)", "RAD MILLI"),
    ("Kid Milli", "Bet (벳)", "RAD MILLI"),
    # Coogie UPSET extras
    ("Coogie", "ON FIRE (온 파이어)", "UPSET"),
    ("Coogie", "BABYFACE (베이비페이스)", "UPSET"),
    ("Coogie", "Sober (소버)", "UPSET"),
    ("Coogie", "Two Pills (투 필스)", "UPSET"),
    # Leellamarz 2025
    ("Leellamarz", "GONE (곤)", ""),
    ("Leellamarz", "Can't stop (캔트 스톱)", "DAYDATE"),
    # Heize LOVE VIRUS extras
    ("Heize", "The Last Hello (더 라스트 헬로)", "LOVE VIRUS Pt.1"),
    ("Heize", "Even if (이븐 이프)", "LOVE VIRUS Pt.1"),
    # Zion.T POSER extras
    ("Zion.T", "Snooze (스누즈)", "POSER"),
    ("Zion.T", "Yanghwa Bridge (양화대교)", "POSER"),
    # The Quiett Luxury Flow extras
    ("The Quiett", "LF Intro (엘에프 인트로)", "Luxury Flow"),
    ("The Quiett", "Look Inside (룩 인사이드)", "Luxury Flow"),
    ("The Quiett", "Crystal Crates (크리스탈 크레이츠)", "Luxury Flow"),
    ("The Quiett", "Ocean View (오션 뷰)", "Luxury Flow"),
    # Jay Park 2025
    ("Jay Park", "Stand Out (스탠드 아웃)", ""),
    ("Jay Park", "Keep It Sexy (킵 잇 섹시)", ""),
    # Loopy SEOUL pt.A extras
    ("Loopy", "PINK SPILL (핑크 스필)", "SEOUL pt.A"),
    ("Loopy", "King Loopy (킹 루피)", "King Loopy"),
    # TOIL / Qwala
    ("TOIL", "Rollin (롤린)", "1989"),
    ("TOIL", "Money (머니)", "1989"),
    ("Qwala", "If WONA becomes a gangster (Feat. Qwala, New Champ)", ""),
    # More legacy unique suffix
    ("Flowsik", "We On (위 온)", "Show Me the Money 777"),
    ("Reddy", "Think (씽크)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows (노바디 노즈)", "Show Me the Money 777"),
    ("Olltii", "Creative Control (크리에이티브)", "Creative Control"),
    ("C Jamm", "Monster (몬스터)", ""),
    ("Kid Ash", "Orca (오르카)", "Orca-Tape"),
    ("Blued", "Blue (블루)", "Blue"),
    ("NO:EL", "Rain Drop 2 (레인 드롭 2)", "Rain Drop 2"),
    ("MC Meta", "On My Own (온 마이 온)", "The Blue Printz"),
    ("Rhymer", "Brand New Day (브랜드 뉴 데이)", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High (플라이 하이)", "Fly High"),
    ("Pe2ny", "Pe2ny Maker (피투니 메이커)", "Pe2ny Maker"),
    ("TBNY", "Million (밀리언)", "Million"),
    ("Stuck B", "Stuck B (스턱 비)", "Stuck B"),
    ("Crown J", "My Friend (마이 프렌드)", "My Friend"),
    ("L.E.O.", "Show Must Go On (쇼 머스트 고 온)", "Show Must Go On"),
    ("Mad Clown", "Loving U (러빙 유)", "Heoteoge Sarang"),
    ("Tiger JK", "Payback (페이백)", "Feel gHood Muzik : The 8th Wonderland"),
    ("Leessang", "The Rain (더 레인)", "Unplugged on the Sofa"),
    ("Phantom", "Bubble Love (버블 러브)", "Phantom City"),
    ("MellowD", "On My Way (온 마이 웨이)", "On My Way"),
    ("Verbal Jint", "Mainstream (메인스트림)", "Mainstream"),
    ("Geeks", "Officially Missing You (오피셜리 미싱 유)", "Officially Missing You"),
    ("Bumkey", "Single Life (싱글 라이프)", "Single Life"),
    ("Junggigo", "Rookie (루키)", "Rookie"),
    ("Don Mills", "Don Mills Is Angry 3 (돈밀스는 화났다 3)", "Don Mills Is Angry 3"),
    ("Myun Do One", "Bulldozer (불도저)", "Myun Do One Is Back"),
    ("Illinit", "Ill Street (일 스트릿)", "Illmatic"),
    ("Sean2Slow", "Slow Jam (슬로우 잼)", "Slow Jam"),
    ("JJK", "Go Back (고 백)", "Go-Back"),
    ("Baechigi", "Shark's Tale (샤크스 테일)", "Shark's Tale"),
    ("Dok2", "Dok2ocracy (독2ocracy)", "Dok2ocracy"),
    ("Vasco", "The Vasco (더 바스코)", "The Vasco"),
    ("G2", "G2 (지투)", "G2"),
    ("G2", "Business (비즈니스)", "Business"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("Cheetah", "Keep It Movin (킵 잇 무빙)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("J'Kyun", "Ready to Fly (레디 투 플라이)", "Ready to Fly"),
    ("Outsider", "Vol.2-Maestro 4 (볼륨2 마에스트로 4)", "Vol.2-Maestro 4"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE (아이스 앤 파이어)", "a SONG of ICE and FIRE"),
    # 2025 fill: artists unused in 2022-2024 picks
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Roh Yun Ha", "Trouble (트러블)", "Show Me the Money 10"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Trade L", "Blue Sky (블루 스카이)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Wonstein", "Infrared (적외선)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Paul Blanco", "Rain (비)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Killagramz", "Good Morning Remix (굿 모닝 리믹스)", "Good Morning"),
    ("Basick", "Nice Day (나이스 데이)", "Nice Day"),
    ("Basick", "Show Me The Money (쇼미)", "Nice Day"),
    ("Hanhae", "003", "003"),
    ("Hanhae", "001", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("B.I", "Illa Illa (illa illa)", "Waterfall"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Khundi Panda", "Pick Up (픽업)", "Medicine"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Tabber", "3rd Eye (써드 아이)", "RUN CHICKEN"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("Illinit", "Ill Street Live 2 (일 스트릿)", ""),
    ("G2", "G2 (지투)", "G2"),
    ("G2", "Business (비즈니스)", "Business"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("Cheetah", "Keep It Movin (킵 잇 무빙)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("J'Kyun", "Ready to Fly (레디 투 플라이)", "Ready to Fly"),
    ("NSW yoon", "Therapy + 으리으리 (Feat. 호미들)", "Show Me the Money 11"),
    ("NSW yoon", "Flick (플릭)", "Show Me the Money 11"),
    ("Meenoi", "Face (페이스)", ""),
    ("Meenoi", "Ghosting (고스팅)", ""),
    ("HAON", "Travel (트래블)", "Penumbra"),
    ("HAON", "Blue (블루)", "Penumbra"),
    ("UNEDUCATED KID", "UNEDUCATED KID (언에듀케이티드 키드)", ""),
    ("UNEDUCATED KID", "UNEDUCATED KID 2 (언에듀케이티드 키드 2)", ""),
    ("Superbee", "Superbee (슈퍼비)", ""),
    ("Superbee", "Superbee 2 (슈퍼비 2)", ""),
    ("George", "Half (하프)", ""),
    ("George", "Half 2 (하프 2)", ""),
    # 2025 fill batch 2: legacy artists not in 2022-2024
    ("Gemini", "Know Me (노 미)", "Know Me"),
    ("Gemini", "Going (고잉)", "Going"),
    ("Black Nut", "1000 Years (1000 년)", "1000 Years"),
    ("Black Nut", "Guerrilla (게릴라)", "Guerrilla"),
    ("Okasian", "Profile (프로필)", "Profile"),
    ("Okasian", "Walkin' (워킨)", "Profile"),
    ("Ugly Duck", "Whoareyou (후아유)", "Whoareyou"),
    ("Ugly Duck", "Respect (리스펙)", "Respect"),
    ("Nucksal", "W.U (더블유 유)", "W.U"),
    ("Nucksal", "W.U 2 (더블유 유 2)", "W.U"),
    ("Rakim", "Rakim (라킴)", "Rakim"),
    ("Rakim", "Rakim 2 (라킴 2)", "Rakim"),
    ("Boi B", "Butterfly (버터플라이)", "Butterfly"),
    ("Boi B", "Butterfly 2 (버터플라이 2)", "Butterfly"),
    ("Kebee", "Kebee (케비)", "Kebee"),
    ("Kebee", "Kebee 2 (케비 2)", "Kebee"),
    ("Skull", "Skull (스컬)", "Skull"),
    ("Skull", "Skull 2 (스컬 2)", "Skull"),
    ("Inspiring", "Inspiring (인스파이어링)", "Inspiring"),
    ("Inspiring", "Inspiring 2 (인스파이어링 2)", "Inspiring"),
    ("Hot Clip", "Hot Clip (핫 클립)", "Hot Clip"),
    ("Hot Clip", "Hot Clip 2 (핫 클립 2)", "Hot Clip"),
    ("Jerry.K", "Jerry.K (제리케이)", "Jerry.K"),
    ("Jerry.K", "Jerry.K 2 (제리케이 2)", "Jerry.K"),
    ("A-Chess", "A-Chess (에이체스)", "A-Chess"),
    ("A-Chess", "A-Chess 2 (에이체스 2)", "A-Chess"),
    ("Futuristic Swaver", "Futuristic Swaver (퓨처리스틱)", "Futuristic Swaver"),
    ("Futuristic Swaver", "Futuristic Swaver 2 (퓨처리스틱 2)", "Futuristic Swaver"),
]
