#!/usr/bin/env python3
"""2022–2025 후보 풀 (공식 표기, 발매연도·힙플·전문가 평가 기준)."""
from __future__ import annotations

# (artist, title, album) — HEAD는 연간 대표 히트
HEAD: dict[int, list[tuple[str, str, str]]] = {
    2022: [
        ("Epik High", "그래서 그래 (Feat. 윤하)", "Epik High Is Here 下, Part 2"),
        ("JUSTHIS", "마이웨이 (MY WAY) (Prod. by Alti)", "Show Me the Money 11"),
        ("Kid Milli", "가볍게", ""),
        ("Giriboy", "Vice Versa", "Vice Versa"),
        ("Ash Island", "안전지대", "Safety Zone"),
        ("The Quiett", "Bentley", ""),
        ("TOIL", "처음 만났을 때처럼", ""),
        ("Beenzino", "MONET", ""),
        ("PH-1", "BUT FOR NOW LEAVE ME ALONE", "BUT FOR NOW LEAVE ME ALONE"),
        ("Leellamarz", "그러지마", "Toystory3"),
    ],
    2023: [
        ('Don Malik', 'SEOUL', 'MADE IN SEOUL'),
        ('Don Malik', 'Malik', 'MADE IN SEOUL'),
        ('Epik High', 'Strawberry', 'Strawberry'),
        ('BIG Naughty', 'Você', 'Você'),
        ('Qwala', 'ㅍㅍㅍㅍ (Feat. Kid Milli)', 'ㅍㅍㅍㅍ'),
        ('Ourealgoat', 'Maybe', ''),
        ('Blued', 'Tears', ''),
        ('Giriboy', 'Girlfriend', ''),
        ('Beenzino', 'Trippy', 'NOWITZKI'),
        ('Kid Milli', 'Benzo', ''),
    ],
    2024: [
        ('TOIL', '염염상망', ''),
        ('Loopy', 'DOPE', 'SEOUL pt.A'),
        ('Owen Ovadoz', 'Diamond', '119'),
        ('The Quiett', 'LF Intro', 'Luxury Flow'),
        ('Antihuman', 'Antihuman', 'Antihuman'),
        ('QM', '개미', '개미'),
        ('Kid Milli', '5AM', 'RAD MILLI'),
        ('Dean', 'NASA', '3:33'),
        ('Changmo', 'HOLDUP', 'Op.1'),
        ('Lil Moshpit', 'K-FLIP', 'K-FLIP+'),
    ],
    2025: [
        ('Owen Ovadoz', 'TANG', 'POEMV'),
        ('Don Malik', 'Spinboutu', 'Love is a Song'),
        ('EK', 'YAHO', 'YAHO'),
        ('Penomeco', 'EGGE (Feat. YDG)', 'RNSSNC TAPE'),
        ('Mushvenom', '돌림판 (Feat. 신빠람 이박사)', '얼'),
        ('The Quiett', 'Crystal Crates', 'Luxury Flow'),
        ('Loopy', 'CROWN', 'SEOUL pt.A'),
        ('Epik High', 'Frost', 'Strawberry'),
        ('Changmo', 'HOLDUP', 'Op.1'),
        ('Kid Milli', 'Feel Good', 'RAD MILLI'),
    ],
}

POOLS: dict[int, list[tuple[str, str, str]]] = {
    2022: [
        ('Beenzino', '덤보', 'Dumbo'),
        ('Zico', 'Grown Ass Kid', 'Grown Ass Kid'),
        ('Zico', 'Seoul Drift', 'Grown Ass Kid'),
        ('Epik High', '비 오는 날 듣기 좋은 노래 (Feat. 콜드)', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Face ID (페이스 아이디) (Feat. 기리보이, Sik-K, JUSTHIS)', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Super Rare (슈퍼 레어) (Feat. Wonstein, pH-1)', 'Epik High Is Here 下, Part 2'),
        ('허성현', '펄펄 (Feat. Dynamic Duo)', 'Show Me the Money 11'),
        ('Kan', 'Therapy + 으리으리 (Feat. 호미들)', 'Show Me the Money 11'),
        ('Blase', 'Quote That', ''),
        ('PH-1', 'BUT FOR NOW LEAVE ME ALONE', 'BUT FOR NOW LEAVE ME ALONE'),
        ('PH-1', 'Zombies', 'BUT FOR NOW LEAVE ME ALONE'),
        ('Kid Milli', 'SUMMER', ''),
        ('Coogie', '혼자', 'Re:Up'),
        ('Leellamarz', '마지막 기회', 'Toystory3'),
        ('Leellamarz', 'Never Ending Story', 'Toystory3'),
        ('Dynamic Duo', 'ECO', 'ECO'),
        ('Dynamic Duo', 'Smoke', 'ECO'),
        ('Giriboy', 'Vice Versa', 'Vice Versa'),
        ('Giriboy', 'Braille', 'Vice Versa'),
        ('Ash Island', '안전지대', 'Safety Zone'),
        ('Ash Island', 'Malibu Night', 'Safety Zone'),
        ('Loco', 'WIN', ''),
        ('Loco', 'Focus', ''),
        ('GRAY', 'Remedy', ''),
        ('GRAY', 'Sweaty (Prod. GRAY) (Feat. 로꼬, Coogie)', 'Street Man Fighter Original Vol.3'),
        ('GroovyRoom', 'Whistle (Prod. GroovyRoom) (Feat. 식케이, Mirani)', 'Street Man Fighter Original Vol.3'),
        ('GroovyRoom', 'Brought the Heat Back (Feat. 식케이, Paloalto)', 'Brought the Heat Back'),
        ('Sik-K', 'Brought the Heat Back (더운데)', 'Brought the Heat Back'),
        ('Paloalto', 'Valentina', ''),
        ('The Quiett', 'Bentley', ''),
        ('TOIL', '처음 만났을 때처럼', ''),
        ('TOIL', 'Rollin', '1989'),
        ('Swings', '우리를 기억해', 'Growing Pains'),
        ('Mirani', 'Drama', 'Drama'),
        ('Woodie Gochild', 'Channel Surfing', '#GOchild'),
        ('Owen Ovadoz', '119', '119'),
        ('Punchnello', 'Loveseat', ''),
        ('Colde', 'Star', ''),
        ('Changmo', 'Just the Two of Us', ''),
        ('Dean', '4:44', ''),
        ('Heize', 'Undo', ''),
        ('Jessi', 'Zoom', ''),
        ('Zion.T', 'Lonely Christmas', ''),
        ('Lil Moshpit', 'MOSHPIT ONLY', 'AAA'),
        ('Lil Moshpit', 'ACHOO', 'ACHOO'),
        ('Lee Young Ji', 'WITCH (Feat. 밸재범, 황소윤)', 'Show Me the Money 11'),
        ('JUSTHIS', 'Signature (Prod. by Alti)', 'Show Me the Money 11'),
        ('Primary', 'BILLING', 'BILLING'),
        ('Gaeko', 'Sturgis', 'Sturgis'),
        ('Simon Dominic', 'Make Her Dance', 'Simon Dominic Part 3'),
        ('Nafla', 'Freestyle', ''),
        ('Loopy', 'Freestyle', ''),
        ('Mudd the student', 'Nectar (넥타)', 'Show Me the Money 10'),
        ('Lil Boi', 'Good Day', 'Show Me the Money 10'),
        ("BE'O", 'Countdown (카운트다운)', 'Show Me the Money 10'),
        ('Sokodomo', 'SIGNATURE (시그니처)', 'Show Me the Money 10'),
        ('Hash Swan', 'Hash Brand 2', 'Hash Brand 2'),
        ('Jvcki Wai', 'Taxi Blurr', 'Taxi Blurr'),
        ('D.Ark', 'Genius', 'Genius'),
        ('BewhY', 'Day Day', 'The Movie Star'),
        ('YUMDDA', 'Tic Toc', "I'm Good"),
        ('Penomeco', 'Shy (수줍)', 'Shy'),
        ('Mino', '안녕', 'To Infinity'),
        ('Bobby', '감동 (Secret)', 'SECRET'),
        ('Tablo', 'Stop the Rain', ''),
        ('Deepflow', 'Good Day', ''),
        ('Huckleberry P', 'Mantra 3', 'Mantra 3'),
        ('Kid Ash', 'Orca', 'Orca-Tape'),
        ('C Jamm', 'Monster', ''),
        ('Olltii', 'Creative Control', 'Creative Control'),
        ('Flowsik', 'We On (위 온)', 'Show Me the Money 777'),
        ('Reddy', 'THINK (띵)', 'Show Me the Money 777'),
        ('KittiB', 'Nobody Knows', 'Show Me the Money 777'),
        ('Koonta', 'KOONTA (쿤타)', 'Show Me the Money 10'),
        ('Basick', 'Nice Day (나이스 데이)', 'The Classic'),
        ('Verbal Jint', 'Mainstream', 'Mainstream'),
        ('Swings', 'Per se', 'Per se'),
        ('Mad Clown', 'Maximum', 'Potato'),
        ('Crush', 'Oasis', ''),
        ('Heize', 'Jenga', 'And July'),
        ('Zion.T', 'Just (저스트)', 'Just'),
        ('Colde', 'Your Dog Loves You', 'Your Dog Loves You'),
        ('Punchnello', 'Loving You Girl', 'Loving You Girl'),
        ('Ash Island', 'Howling', 'Ash Island'),
        ('Leellamarz', 'Profile (프로필)', 'To Be Continued'),
        ('Woodie Gochild', 'Mud (머드)', 'Show Me the Money 10'),
        ('Owen Ovadoz', 'Diana (디ana)', 'Show Me the Money 10'),
        ('Mirani', 'Villain (빌런)', 'Show Me the Money 10'),
        ('Blase', 'ONOFF', 'Show Me the Money 10'),
        ('Trade L', 'Leave It (두고 가)', 'Show Me the Money 10'),
        ('Wonstein', '10 Minutes (10분)', 'Show Me the Money 10'),
        ('Paul Blanco', 'Summer (썸머)', 'Summer'),
        ('Killagramz', 'Good Morning (굿 모닝)', 'Good Morning'),
        ('Hanhae', '003', '003'),
        ('B.I', 'Waterfall (워터폴)', 'Waterfall'),
        ('Tabber', 'RUN CHICKEN (런 치킨)', 'RUN CHICKEN'),
        ('Khundi Panda', 'Medicine (약)', 'Medicine'),
        ('Roh Yun Ha', 'IF I (이프 아이)', 'Show Me the Money 10'),
        ('Illinit', 'Real Talk Live (리얼 토크)', ''),
        ('B-Free', 'Best Seller (베스트 셀러)', 'Best Seller'),
        ('Vasco', 'The Vasco', 'The Vasco'),
        ('Outsider', 'Vol.2-Maestro 4', 'Vol.2-Maestro 4'),
        ('G2', 'G2 (지투)', 'G2'),
        ('Cheetah', "I'll Be Back (아일 비 백)", ''),
        ("J'Kyun", 'Fly Away (플라이 어웨이)', 'Ready to Fly'),
        ('Don Mills', 'Don Mills Is Angry 3', 'Don Mills Is Angry 3'),
        ('Myun Do One', 'Bulldozer', 'Myun Do One Is Back'),
        ('Jerry.K', 'V', 'V'),
        ('Bumkey', 'Single Life', 'Single Life'),
        ('Junggigo', 'Rookie', 'Rookie'),
        ('E-Sens', '이상형', 'The Anecdote'),
        ('San E', 'a SONG of ICE and FIRE', 'a SONG of ICE and FIRE'),
        ('Primary', '2', '2'),
        ('Dok2', 'Thug Life Part 2', 'Thug Life Part 2'),
        ('Rhymer', 'Brand New Day', 'Rhymer Trax Vol.1'),
        ('Double K', 'Fly High', 'Fly High'),
        ('Pe2ny', 'Pe2ny Maker', 'Pe2ny Maker'),
        ('Sean2Slow', 'Slow Jam', 'Slow Jam'),
        ('JJK', 'Go Back', 'Go-Back'),
        ('Baechigi', "Shark's Tale", "Shark's Tale"),
        ('MC Meta', 'On My Own', 'The Blue Printz'),
        ('Geologic', 'Blaze', 'Blaze'),
        ('Mighty Mouth', 'San', 'San'),
        ('Skull', "I'm Your Man", "I'm Your Man"),
        ('Phantom', 'Bubble Love', 'Phantom City'),
        ('MellowD', 'On My Way', 'On My Way'),
        ('Reddy', 'Commitment', 'Orca-Tape'),
        ('Kid Milli', 'Cliché (클리셰)', 'Cliché'),
        ('meenoi', 'What Do You Think?', ''),
        ('meenoi', 'Business boy', ''),
        ('CAMO', 'Life is Wet', ''),
        ('CAMO', 'Freak Like Me', ''),
        ('Uneducated Kid', 'UNEDUCATED KID 2', ''),
        ('Epik High', 'Rich Kids Anthem', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Family Portrait', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Champagne', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Piano for Sale', 'Epik High Is Here 下, Part 2'),
        ('Zico', 'Trash Talk', 'Grown Ass Kid'),
        ('Zico', 'That Guy', 'Grown Ass Kid'),
        ('Beenzino', 'Fashion Hoarder', 'Modiversity'),
        ('PH-1', 'Mr. Bad', 'BUT FOR NOW LEAVE ME ALONE'),
        ('PH-1', 'Juliette!', 'BUT FOR NOW LEAVE ME ALONE'),
        ('Punchnello', 'Winter Blossom', 'Winter Blossom'),
        ('Colde', 'honestly', 'Star'),
        ('Lee Young Ji', '낫 쏘리 (Feat. pH-1)', 'Show Me the Money 11'),
        ('Kid Milli', '가볍게', ''),
        ('Coogie', '굿나잇', 'Re:Up'),
        ('Leellamarz', '그러지마', 'Toystory3'),
        ('Crush', 'Rush Hour (Feat. j-hope of BTS)', 'Rush Hour'),
        ('Jessi', 'Zoom', ''),
        ('Zion.T', 'Lonely Christmas', ''),
        ('Mino', '안녕', 'To Infinity'),
        ('Tablo', 'Stop the Rain', ''),
        ('Jvcki Wai', 'Taxi Blurr', 'Taxi Blurr'),
        ('Lil Moshpit', 'ACHOO', 'ACHOO'),
        ('Primary', 'BILLING', 'BILLING'),
        ('Gaeko', 'Sturgis', 'Sturgis'),
        ('Simon Dominic', 'Make Her Dance', 'Simon Dominic Part 3'),
        ('Dean', '4:44', ''),
        ('Swings', 'Per se', 'Per se'),
        ('Verbal Jint', 'Mainstream', 'Mainstream'),
        ('JJK', 'Go Back', 'Go-Back'),
        ('Baechigi', "Shark's Tale", "Shark's Tale"),
        ('Epik High', 'Here', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Prequel', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Gray So Gray', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'BRB', 'Epik High Is Here 下, Part 2'),
        ('Epik High', 'Rain Song', 'Epik High Is Here 下, Part 2'),
        ('Zico', 'Being Human', 'Grown Ass Kid'),
        ('Zico', 'Curriculum', 'Grown Ass Kid'),
        ('Zico', 'OMJT', 'Grown Ass Kid'),
        ('PH-1', 'TGIF', 'BUT FOR NOW LEAVE ME ALONE'),
        ('PH-1', 'Yuppie Ting', 'BUT FOR NOW LEAVE ME ALONE'),
        ('PH-1', 'Tipsy', 'BUT FOR NOW LEAVE ME ALONE'),
        ('BIG Naughty', 'Romance Symphony', ''),
        ('Sik-K', 'MOON', 'MAKE OUT'),
        ('Colde', 'honestly', 'Star'),
        ('Punchnello', 'Winter Blossom', 'Winter Blossom'),
        ('DeVita', 'Flowers', ''),
        ('Beenzino', 'MONET', ''),
        ('Zico', '새삥 (Prod. ZICO) (Feat. 호미들)', 'Street Man Fighter Original Vol.3'),
        ('Epik High', '그래서 그래 (Feat. 윤하)', 'Epik High Is Here 下, Part 2'),
        ('BIGBANG', '봄여름가을겨울 (Still Life)', 'Still Life'),
        ('Dynamic Duo', 'Smoke (Prod. Dynamicduo, Padi)', 'Street Woman Fighter 2 Original Vol.1'),
        ('Thama', 'Long Time No See', 'Long Time No See'),
        ('Queenpia', 'Queenpia', 'Queenpia'),
        ('Sumin', 'Mirrorball', 'Mirrorball'),
        ('MoonMoon', 'Tourist', 'Tourist'),
        ('E Sens', 'Mona Lisa', 'Mona Lisa'),
        ('DPR LIVE', 'Jasmine', 'Jasmine'),
        ('Woo Won Jae', 'Hourglass', 'Hourglass'),
        ('Rad Museum', 'Life', 'Life'),
        ('Ash Island', 'Me n Mine', 'Show Me the Money 10'),
        ('GwangilJo', 'VVS (비비에스)', 'Show Me the Money 8'),
        ('Futuristic Swaver', 'Blue Hawaii', ''),
        ('Knoxx', 'Knoxx Tape', ''),
        ('Polodared', 'Polodared', ''),
        ('Hej!', 'Hej!', ''),
        ('Hodaky', 'Hodaky', ''),
        ('Chillin Homie', 'Chillin Homie', ''),
        ('Bluso', 'Bluso', ''),
        ('LeyonC', 'LeyonC', ''),
        ('Hyunsang', 'Hyunsang', ''),
        ('Woo', 'Woo', ''),
        ('Rohann', 'Problem', 'Problem'),
        ('Ahn Se-min', 'Ahn Se-min', 'Show Me the Money 11'),
        ('NSW yoon', 'NSW yoon', 'Show Me the Money 11'),
        ('Kan', 'Kan', 'Show Me the Money 11'),
        ('QM', 'QM', 'Show Me the Money 11'),
        ('노윤하', '노윤하', 'Show Me the Money 11'),
        ('잠비노', '잠비노', 'Show Me the Money 11'),
        ('Don Malik', 'Don Malik', 'Show Me the Money 11'),
        ('Lee Young Ji', 'Yumeyo', '16'),
        ('이영지', '이영지', 'Show Me the Money 11'),
        ('JUSTHIS', 'JUSTHIS', 'Show Me the Money 11'),
        ('NO:EL', 'Rain Drop', 'Rain Drop'),
        ('Deepflow', 'Flow the Life 3', 'Flow the Life 3'),
    ],
    2023: [
        ('Beenzino', 'NOWITZKI', 'NOWITZKI'),
        ('Lil Moshpit', 'Money Only Shows Hustle', ''),
        ('Don Malik', 'Malik', 'MADE IN SEOUL'),
        ('Zico', 'Earthquake', ''),
        ('Epik High', 'Fade Away', 'Strawberry'),
        ('Kid Milli', 'Benzo', ''),
        ('Kid Milli', 'BEIGE theme', 'BEIGE'),
        ('Leellamarz', 'DAYDATE', 'DAYDATE'),
        ('Leellamarz', '모른 척', 'DAYDATE'),
        ('82MAJOR', 'ON', 'ON'),
        ('meenoi', '3MAN', ''),
        ('DeVita', 'Ride or Die', ''),
        ('Ourealgoat', 'Maybe', ''),
        ('Blued', 'Tears', ''),
        ('Owen Ovadoz', 'Drama', ''),
        ('Mirani', 'Baby', ''),
        ('Woodie Gochild', 'Mood', ''),
        ('Crush', 'wonderego', 'wonderego'),
        ('Crush', 'Hmm-cheat', 'wonderego'),
        ('CAMO', 'Wifey', ''),
        ('B.I', 'Lover', ''),
        ('Coq', 'Tweaker', ''),
        ('Coogie', 'Buck', 'DIFF'),
        ('Coogie', 'Just For Fun', 'DIFF'),
        ('Loco', 'VOLVO', ''),
        ('Loco', 'INEEDYOURLOVE', ''),
        ('Dean', 'NO FUN', "howlin' 404"),
        ('Heize', 'Perhaps Happy Ending (아마도 해피 엔딩)', 'Last Winter'),
        ('Heize', 'From Autumn to Winter (가을에서 겨울로)', 'Last Winter'),
        ('Zion.T', 'UNLOVE', 'Zip'),
        ('Zion.T', 'Happy Ending', 'Zip'),
        ('Bobby', 'Drowning', 'S.i.R'),
        ('Mino', 'Smoke', 'BODY'),
        ('Changmo', 'VOOM', ''),
        ('Changmo', 'FWB', ''),
        ('PH-1', 'Rosario', 'But For Now Leave Me Alone 2'),
        ('PH-1', 'Final Bout', 'But For Now Leave Me Alone 2'),
        ('Gray', 'Summer Surf', 'Summer Surf'),
        ('Punchnello', 'Motive', ''),
        ('Colde', 'Wave', ''),
        ('Giriboy', 'Engineering', 'Engineering'),
        ('Dynamic Duo', 'Smoke (Prod. Dynamicduo, Padi)', 'Street Woman Fighter 2 Original Vol.1'),
        ('The Quiett', 'King Is Back', 'Luxury Flow'),
        ('The Quiett', 'Mercedes', 'Luxury Flow'),
        ('Paloalto', 'GONE', ''),
        ('Nafla', 'C.R.E.A.M', 'C.R.E.A.M'),
        ('Jvcki Wai', 'Exposure', 'Exposure'),
        ('Deepflow', 'Flow the Life 6', 'Flow the Life 6'),
        ('Huckleberry P', 'Mantra 6', 'Mantra 6'),
        ('GroovyRoom', 'Brought the Heat Back', 'Brought the Heat Back'),
        ('Don Mills', 'Don Mills Is Angry 6', 'Don Mills Is Angry 6'),
        ('PLT', 'Way Back Home', 'Way Back Home'),
        ('Jay Park', 'Candy', ''),
        ('Jay Park', 'Sunday Night Drive', ''),
        ('Knoxx', 'Knoxx', ''),
        ('Polodared', 'Multiverse', ''),
        ('Hej!', 'Drive', ''),
        ('Futuristic Swaver', 'Villain', ''),
        ('Hodaky', 'Yellow', ''),
        ('Chillin Homie', 'Good Day', ''),
        ('Uneducated Kid', 'UNEDUCATED KID', ''),
        ('Superbee', 'Superbee', ''),
        ('Ahn Se-min', '물', 'Show Me the Money 11'),
        ('Bluso', 'Fade Away', ''),
        ('LeyonC', 'Fall', ''),
        ('Hyunsang', 'Take Care', ''),
        ('Woo', 'Rain Drop', 'Rain Drop'),
        ('Rohann', 'Sunday', ''),
        ('Blase', 'City Life', ''),
        ('Lee Young Ji', 'O.K?', 'O.K?'),
        ('Jessi', 'Gum', 'Gum'),
        ('Lil Boi', 'Empty Head', ''),
        ('NSW yoon', 'Therapy + 으리으리 (Feat. 호미들)', 'Show Me the Money 11'),
        ('허성현', '미운오리새끼 (Prod. R.Tee)', 'Show Me the Money 11'),
        ('Kan', '나침반 (Feat. UNEDUCATED KID, Superbee)', 'Show Me the Money 11'),
        ('QM', 'Come To My Stu (Feat. 릴러말즈)', 'Show Me the Money 11'),
        ('노윤하', "Flick (Feat. BE'O, HAON)", 'Show Me the Money 11'),
        ('잠비노', 'Bingo (Feat. 미노이, George)', 'Show Me the Money 11'),
        ('이영지', 'WITCH (Feat. 밸재범, 황소윤)', 'Show Me the Money 11'),
        ('Baechigi', '상어의 이야기', "Shark's Tale"),
        ('Owen Ovadoz', 'Freeze', '119'),
        ('Colde', 'Reno', ''),
        ('Dean', 'Die 4 You', ''),
        ('BIG Naughty', 'Vogue', 'Vogue'),
        ('Blase', 'Holiday (Feat. Lil Boi, 기리보이)', 'Show Me the Money 11'),
    ],
    2024: [
        ('G-Dragon', 'TAKE ME', 'Übermensch'),
        ('Zico', 'ZOOM', ''),
        ('Changmo', 'HOLDUP', 'Op.1'),
        ('Lil Moshpit', 'KC2', 'K-FLIP+'),
        ('Qwala', '델러가 (Feat. MELOH & Posadic)', 'yorter'),
        ('Sokodomo', 'Merry Go Round', 'Merry Go Round'),
        ('Kid Milli', '술', 'RAD MILLI'),
        ('Dean', 'Ctrl', '3:33'),
        ('Jay Park', 'Stand Out', ''),
        ('Loco', 'random summer night', ''),
        ('Loco', 'Smeraldo Garden Marching Band', ''),
        ('Crush', "Fallin'", ''),
        ('Leellamarz', 'Let me go to heaven', ''),
        ('Leellamarz', 'GONE', ''),
        ('The Quiett', 'LF Intro', 'Luxury Flow'),
        ('The Quiett', 'Look Inside', 'Luxury Flow'),
        ('Bobby', 'Sae', 'Sir.Robert'),
        ('Bobby', 'Harmless', 'Sir.Robert'),
        ('Coogie', 'ON FIRE', ''),
        ('Coogie', 'Flame', 'UPSET'),
        ('PH-1', 'FLAT COKE', ''),
        ('PH-1', 'WHAT HAVE WE DONE', 'WHAT HAVE WE DONE'),
        ('Punchnello', 'before you', ''),
        ('Gray', "SLIDIN'", ''),
        ('Gray', 'Real Love', 'Remedy'),
        ('Giriboy', 'heat', 'heat'),
        ('Giriboy', 'Mechanical Album', 'Mechanical Album'),
        ('Epik High', 'Stop the Rain', ''),
        ('Epik High', 'Frost', 'Strawberry'),
        ('TOIL', '염염상망', ''),
        ('Blase', 'INDUSTRY', 'SELF MADE'),
        ('Blase', '12345678', 'SELF MADE'),
        ('Owen Ovadoz', 'Diamond', '119'),
        ("BE'O", 'Momentum', 'Show Me the Money 10'),
        ("BE'O", 'Healing', 'Show Me the Money 10'),
        ('Lee Young Ji', 'Yumeyo', '16'),
        ('Sik-K', 'MAKE OUT', 'MAKE OUT'),
        ('Loopy', 'DOPE', 'SEOUL pt.A'),
        ('Loopy', 'DEAD MAN WALKING', 'SEOUL pt.A'),
        ('Gaeko', 'Gajah', 'Gajah'),
        ('Zion.T', 'Snooze', 'Zion.T Special: OO'),
        ('Don Malik', 'THURSDAYCLUB MIXTAPE', 'THURSDAYCLUB MIXTAPE'),
        ('82MAJOR', '뭘 봐 (TAKEOVER)', 'X-82'),
        ('82MAJOR', 'Stuck', 'Beat Road'),
        ('Mudd the student', 'Nectar', 'Show Me the Money 10'),
        ('Lil Boi', 'ONFleek', 'Show Me the Money 9'),
        ('Zion.T', 'Whale', 'Zip'),
        ('Heize', 'Forgotten Love', 'Last Winter'),
        ('Sokodomo', 'Merry Go Round (Feat. Zion.T)', 'Merry Go Round'),
        ('Qwala', 'yorter', 'yorter'),
        ('BRADYSTREET', 'Brady Street', ''),
        ('Gist', 'Gist', ''),
        ('JUSTHIS', 'JUSTHIS', 'Show Me the Money 11'),
        ('Crucial Star', 'Nihilism Watch', ''),
        ('ChaMane', 'BATON PASS', 'BATON PASS'),
        ('HD BL4CK', 'BATON PASS', 'BATON PASS'),
        ('Khundi Panda', 'Somozu Fury', ''),
        ("J'Kyun", 'AGAPE', 'AGAPE'),
        ('meenoi', 'B', ''),
        ('GroovyRoom', 'Yes or No', ''),
        ('Wonstein', "It's not beautiful and it doesn't hurt", ''),
        ('Flowsik', "Movin'", ''),
        ('Don Mills', 'OK', ''),
        ('Don Mills', '인생을 바꿀', 'The Life-Changing Album'),
        ('GwangilJo', 'Light Adaptation', 'Light Adaptation'),
        ('QM', '개미', '개미'),
        ('Paloalto', 'Lovers Turn to Haters', 'Lovers Turn to Haters'),
        ('Khundi Panda', 'MODM 2 : The Bento Knight', 'MODM 2 : The Bento Knight'),
        ('B-Free', 'Free The Mane 2', 'Free The Mane 2 "Free The Mane VS 최승로"'),
        ('Garion', 'Garion 3', 'Garion 3'),
        ("O'koye", 'Yezzir', 'Whether the Weather Changes or Not'),
        ("O'koye", 'Hallelujah', 'Whether the Weather Changes or Not'),
        ('Rad Museum', 'Rad Milli', 'Rad Milli'),
        ('Chillin Homie', 'Maze Runner', 'Maze Runner'),
        ('Dbo', 'Be Back Soon', 'Be Back Soon'),
        ('Homies', 'Yains', 'Yains'),
        ('Los', 'Skandalouz 2', 'Skandalouz 2'),
        ('Sik-K', 'KC (BUST IT DOWN)', ''),
        ('HAON', 'KC (BUST IT DOWN)', ''),
        ('BIGONE', 'COLORFUL ZEBRA', ''),
        ('BOYCOLD', 'Sick of Love', 'Sick of Love'),
        ('viceversa', 'N!kes', ''),
        ('KIDO', 'MACHINES', ''),
        ('Ash-B', 'Wish', ''),
        ('XWALLY', 'BORN2RAVE', 'BORN2RAVE'),
        ('AP Alchemy', 'Monthly AP – January, 2024', 'Monthly AP – January, 2024'),
        ('Leebido', 'A prescription for 2', 'A prescription for 2'),
        ('ShyboiiTobii', 'Dillis', ''),
        ('Moon Sujin', 'Better', 'Better'),
        ('Owen Ovadoz', 'P.O.E.M.', 'P.O.E.M.'),
        ('noisemasterminsu', 'I KNOW YOU LOVE ME', ''),
        ('lil9ap', 'Drama/R&B', 'Drama/R&B'),
        ('basecamp', 'camp', ''),
        ('ShyboiiTobii', 'Breaking Bad', ''),
        ('CK', 'Verses', 'Verses'),
        ('KAMBO', 'Rapstar', ''),
        ('1300', 'Ape Sh*t', ''),
        ('YUGYEOM', 'LA SOL MI', ''),
        ('HD BL4CK', 'Vantablack Dreams', 'Vantablack Dreams'),
        ('DPR ARTIC', 'KINEMA', 'KINEMA'),
        ('Marv', 'Ok', ''),
        ('Junoflo', 'Love Like This', ''),
        ('KAMBO', 'Dreamatic', 'Dreamatic'),
        ('JMIN', "Sorry I'm Late", "Sorry I'm Late"),
        ('Panda Gomm', 'Home Vacation', 'Home Vacation'),
        ('CHIO CHICANO', 'Big Squad', ''),
        ('Tiger JK', 'T.K.D', 'T.K.D'),
        ('Dabin', 'Giggles', 'Giggles'),
        ('Untell', 'Animal', 'Animal'),
        ('Skinny Chase', 'Journey to the West', 'Journey to the West'),
        ('Fredi Casso', 'Death Therapy', 'Death Therapy'),
        ('Ambid Jack', 'Death Therapy', 'Death Therapy'),
        ('Ja Mezz', 'Only', 'Only'),
        ('Bangroz', 'Only', 'Only'),
        ('Hyeminsong', 'Reborn', 'Reborn'),
        ('Minit', 'He♡rt', 'He♡rt'),
        ('Okashii', 'Orton', 'Orton'),
        ('Antihuman', 'Antihuman', 'Antihuman'),
        ('Ted Park', 'Home Alone 2.0', 'Home Alone 2.0'),
        ('viceversa', "I'M UP", ''),
        ('EK', 'Escape', 'Escape'),
        ('Haon', 'Haonoah', 'Haonoah'),
        ('Flowsik', 'Worlds Apart', 'Worlds Apart'),
        ('Bryn', 'Supercharged', 'Supercharged'),
        ('Balming Tiger', 'Greatest Hits', 'Greatest Hits'),
        ('BIG Naughty', '+', '+'),
        ('RM', 'Right Place, Wrong Person', 'Right Place, Wrong Person'),
        ('B-Free', 'Free Hukky Shibaseki', 'Free Hukky Shibaseki & the God Sun Symphony Group : Odyssey.1'),
    ],
    2025: [
        ('Heize', 'Last Taxi (라스트 택시)', 'LOVE VIRUS Pt.1'),
        ('Crush', 'FANG', 'FANG'),
        ('Loco', 'SCRAPS', 'SCRAPS'),
        ('PH-1', 'WHAT HAVE WE DONE', 'WHAT HAVE WE DONE'),
        ('G-Dragon', 'TAKE ME', 'Übermensch'),
        ('Lil Moshpit', 'LALALA', 'K-FLIP+'),
        ('Kid Milli', 'Feel Good', 'RAD MILLI'),
        ('Leellamarz', 'GONE', ''),
        ('Epik High', 'Frost', 'Strawberry'),
        ('Coogie', 'Shut Up', 'UPSET'),
        ('Leellamarz', 'Hell yea', 'L&B'),
        ('The Quiett', 'Crystal Crates', 'Luxury Flow'),
        ('Gray', 'Real Love', 'Remedy'),
        ('Giriboy', 'Mechanical Album', 'Mechanical Album'),
        ('Blase', 'KKUCKDARI', 'SELF MADE'),
        ("BE'O", 'Healing', 'Show Me the Money 10'),
        ('Loopy', 'CROWN', 'SEOUL pt.A'),
        ('Zion.T', 'Whale', 'Zip'),
        ('The Quiett', 'Look Inside', 'Luxury Flow'),
        ('Bobby', 'Harmless', 'Sir.Robert'),
        ('Coogie', 'Flame', 'UPSET'),
        ('Blase', '12345678', 'SELF MADE'),
        ('Loopy', 'DEAD MAN WALKING', 'SEOUL pt.A'),
        ('82MAJOR', 'Stuck', 'Beat Road'),
        ('Don Malik', 'MADE IN SEOUL', 'MADE IN SEOUL'),
        ('Qwala', 'If WONA becomes a gangster (Feat. Qwala, New Champ)', ''),
        ('Qwala', 'DISTORTED', 'DISTORTED'),
        ('Don Mills', '인생을 바꿀', 'The Life-Changing Album'),
        ('Khundi Panda', 'MODM 2 : The Bento Knight', 'MODM 2 : The Bento Knight'),
        ("O'koye", 'Hallelujah', 'Whether the Weather Changes or Not'),
        ('Sik-K', 'KC (BUST IT DOWN)', ''),
        ('Owen Ovadoz', 'P.O.E.M.', 'P.O.E.M.'),
        ('ShyboiiTobii', 'Breaking Bad', ''),
        ('HD BL4CK', 'Vantablack Dreams', 'Vantablack Dreams'),
        ('KAMBO', 'Dreamatic', 'Dreamatic'),
        ('Minit', 'He♡rt', 'He♡rt'),
        ('Okashii', 'Orton', 'Orton'),
        ('Ted Park', 'Home Alone 2.0', 'Home Alone 2.0'),
        ('viceversa', "I'M UP", ''),
        ('EK', 'Escape', 'Escape'),
        ('Haon', 'Haonoah', 'Haonoah'),
        ('Flowsik', 'Worlds Apart', 'Worlds Apart'),
        ('Epik High', 'Pump', 'Pump'),
        ('Bryn', 'Supercharged', 'Supercharged'),
        ('Balming Tiger', 'Greatest Hits', 'Greatest Hits'),
        ('BIG Naughty', '+', '+'),
        ('RM', 'Right Place, Wrong Person', 'Right Place, Wrong Person'),
        ('Jay Park', 'Need To Know', 'THE ONE YOU WANTED'),
        ('Owen Ovadoz', 'TANG', 'POEMV'),
        ('EK', 'YAHO', 'YAHO'),
        ('Don Malik', 'Spinboutu', 'Love is a Song'),
        ('DeVita', 'Spinboutu', 'Love is a Song'),
        ('DeVita', 'oh wow', 'Love is a Song'),
        ('Royal 44', 'Classical Freestyle', 'We Got What You Need'),
        ('Royal 44', 'New Money', 'We Got What You Need'),
        ('Yung Blesh', 'Classical Freestyle', 'We Got What You Need'),
        ('Yung Blesh', 'New Money', 'We Got What You Need'),
        ('BlackNut', '0', ''),
        ('Bassagong', 'Comfort', ''),
        ('Bassagong', 'Rock N Roll Baby (Feat. G2 & CHANGMO)', ''),
        ('YANGHONGWON', 'LEAN', ''),
        ('Nosun', 'Exit Wounds', 'Exit Wounds'),
        ('B-Free', 'Free The Mane 3', 'Free The Mane 3'),
        ('Wuuslime', 'Wuuslime', ''),
        ('Marv', 'Marv', ''),
        ('Nieah', 'Nieah', ''),
        ('foggyatthebottom', 'FOREVER YOUNG', 'POEMV'),
        ('GV', 'GV', 'YAHO'),
        ('Jeremy Que$t', 'Jeremy Que$t', 'YAHO'),
        ('MILLHAM', 'MILLHAM', 'YAHO'),
        ('GGM Kimbo', 'GGM Kimbo', 'We Got What You Need'),
        ('ShyboiiTobii', 'ShyboiiTobii', 'We Got What You Need'),
        ('JMIN', 'JMIN', 'We Got What You Need'),
        ('Kimeen', 'Kimeen', ''),
        ('xorf1nn', 'xorf1nn', ''),
        ('lahaine', 'lahaine', ''),
        ('Pank', 'Pank', ''),
    ],
}
