#!/usr/bin/env python3
"""HEAD/POOLS 재구성: HEAD=대표 10곡, POOLS=아티스트당 최대 2곡·전역 중복 제거."""
from __future__ import annotations

import os
import re

from build_master import HERE, load_global_exclude, load_module, norm_key
from gen_spare import build_through

MAX_PER_ARTIST = 2
TARGET_POOL = 115  # head 10 + pool 90+ 여유


def rewrite_section(text: str, key: str, year: int, tracks: list[tuple[str, str, str]]) -> str:
    marker = f"    {year}: ["
    start = text.find(marker, text.find(key))
    if start < 0:
        raise RuntimeError(f"{key}[{year}] not found")
    end = text.find("\n    ],", start)
    if end < 0:
        raise RuntimeError(f"{key}[{year}] end not found")
    body = "\n".join(f"        ({a!r}, {t!r}, {al!r})," for a, t, al in tracks)
    return text[:start] + f"    {year}: [\n{body}" + text[end:]


def simulate(year: int, head: list, pool: list) -> tuple[int, int, list]:
    gs = build_through(year)
    ex = load_global_exclude()
    ordered: list[tuple[str, str, str]] = []
    sl: set[str] = set()
    for a, t, al in head + pool:
        k = norm_key(a, t)
        if k in sl:
            continue
        sl.add(k)
        ordered.append((a, t, al))
    result: list[tuple[str, str, str]] = []
    ac: dict[str, int] = {}
    for a, t, al in ordered:
        if len(result) >= 100:
            break
        if ac.get(a, 0) >= MAX_PER_ARTIST:
            continue
        k = norm_key(a, t)
        if k in gs or k in ex:
            continue
        result.append((a, t, al))
        ac[a] = ac.get(a, 0) + 1
    return len(result), len(ac), result


def pick_pool(
    year: int,
    head: list[tuple[str, str, str]],
    candidates: list[tuple[str, str, str]],
) -> list[tuple[str, str, str]]:
    gs = build_through(year)
    ex = load_global_exclude()
    head_keys = {norm_key(a, t) for a, t, _ in head}
    head_artists = {a for a, _, _ in head}
    ac: dict[str, int] = {}
    for a, _, _ in head:
        ac[a] = ac.get(a, 0) + 1

    pool: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for a, t, al in candidates:
        k = norm_key(a, t)
        if k in seen or k in head_keys or k in gs or k in ex:
            continue
        if ac.get(a, 0) >= MAX_PER_ARTIST:
            continue
        seen.add(k)
        pool.append((a, t, al))
        ac[a] = ac.get(a, 0) + 1
        if len(pool) >= TARGET_POOL:
            break
    return pool


HEAD_2023 = [
    ("Beenzino", "Trippy", "NOWITZKI"),
    ("Lil Moshpit", "TO GO", ""),
    ("Zico", "SPOT!", ""),
    ("Epik High", "Strawberry", "Strawberry"),
    ("82MAJOR", "FIRST CLASS", "ON"),
    ("Giriboy", "Girlfriend", ""),
    ("BIG Naughty", "Você", "Você"),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("meenoi", "Malfunction", ""),
    ("Don Malik", "SEOUL", "MADE IN SEOUL"),
]

# 2023 발매 verified — 아티스트당 pool에 최대 2곡(head 제외)
CANDIDATES_2023 = [
    ("Beenzino", "NOWITZKI", "NOWITZKI"),
    ("Beenzino", "Modiversity", "Modiversity"),
    ("Lil Moshpit", "Money Only Shows Hustle", ""),
    ("Don Malik", "Malik", "MADE IN SEOUL"),
    ("Don Malik", "49", "49"),
    ("Zico", "Earthquake", ""),
    ("Zico", "Curriculum", "Grown Ass Kid"),
    ("Zico", "OMJT", "Grown Ass Kid"),
    ("Epik High", "Fade Away", "Strawberry"),
    ("Epik High", "Kill", "Strawberry"),
    ("Kid Milli", "Benzo", ""),
    ("Kid Milli", "BEIGE theme", "BEIGE"),
    ("Kid Milli", "HONDA!", "BEIGE"),
    ("Leellamarz", "DAYDATE", "DAYDATE"),
    ("Leellamarz", "모른 척", "DAYDATE"),
    ("82MAJOR", "ON", "ON"),
    ("82MAJOR", "Sure Thing", "ON"),
    ("meenoi", "3MAN", ""),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Owen Ovadoz", "Drama", ""),
    ("Mirani", "Baby", ""),
    ("Woodie Gochild", "Mood", ""),
    ("Crush", "wonderego", "wonderego"),
    ("Crush", "Hmm-cheat", "wonderego"),
    ("CAMO", "Wifey", ""),
    ("Rad Museum", "Girls", "Life"),
    ("B.I", "Lover", ""),
    ("Coq", "Tweaker", ""),
    ("Coogie", "Buck", "DIFF"),
    ("Coogie", "Just For Fun", "DIFF"),
    ("Loco", "VOLVO", ""),
    ("Loco", "INEEDYOURLOVE", ""),
    ("Dean", "NO FUN", "howlin' 404"),
    ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)", "Last Winter"),
    ("Heize", "From Autumn to Winter (가을에서 겨울로)", "Last Winter"),
    ("Zion.T", "UNLOVE", "Zip"),
    ("Zion.T", "Happy Ending", "Zip"),
    ("Bobby", "Drowning", "S.i.R"),
    ("Mino", "Smoke", "BODY"),
    ("Changmo", "VOOM", ""),
    ("Changmo", "FWB", ""),
    ("PH-1", "Rosario", "But For Now Leave Me Alone 2"),
    ("PH-1", "Final Bout", "But For Now Leave Me Alone 2"),
    ("Gray", "Summer Surf", "Summer Surf"),
    ("Punchnello", "Motive", ""),
    ("Colde", "Wave", ""),
    ("Giriboy", "Engineering", "Engineering"),
    ("Dynamic Duo", "Smoke (Prod. Dynamicduo, Padi)", "Street Woman Fighter 2 Original Vol.1"),
    ("The Quiett", "King Is Back", "Luxury Flow"),
    ("The Quiett", "Mercedes", "Luxury Flow"),
    ("Paloalto", "GONE", ""),
    ("TOIL", "1989", "1989"),
    ("Swings", "Growing Pains 2", "Growing Pains 2"),
    ("Mirani", "Baby Steps", "Show Me the Money 10"),
    ("Blase", "ONOFF", "Show Me the Money 10"),
    ("Sik-K", "FL1X", "FL1X"),
    ("Tablo", "Hood", "Drill Presents: Tablo x Fantasy"),
    ("Nafla", "C.R.E.A.M", "C.R.E.A.M"),
    ("Loopy", "Portrait Mode", "[ Album ]"),
    ("YUMDDA", "I'm Good", "I'm Good"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Exposure", "Exposure"),
    ("Mudd the student", "Open", "Show Me the Money 8"),
    ("BewhY", "Movie Star", "The Movie Star"),
    ("Penomeco", "Famous", ""),
    ("Simon Dominic", "NO OPEN FLAME", "NO OPEN FLAME"),
    ("Gaeko", "Geon Gangs", "Geon Gangs"),
    ("Deepflow", "Flow the Life 6", "Flow the Life 6"),
    ("Huckleberry P", "Mantra 6", "Mantra 6"),
    ("D.Ark", "Genius", "Genius"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("C Jamm", "RED", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("GroovyRoom", "Brought the Heat Back", "Brought the Heat Back"),
    ("Ash Island", "Me n Mine", "Show Me the Money 10"),
    ("Trade L", "Blue Sky (블루 스카이)", "Show Me the Money 10"),
    ("Wonstein", "Infrared (적외선)", "Show Me the Money 10"),
    ("Paul Blanco", "Rain (비)", "Summer"),
    ("Killagramz", "Good Morning Remix (굿 모닝 리믹스)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("Basick", "Nice Day (나이스 데이)", "The Classic"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Primary", "Morning Glory", ""),
    ("Dok2", "Rich Forever", "Rich Forever"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Blaze", "Blaze"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("PLT", "Way Back Home", "Way Back Home"),
    ("Jay Park", "Candy", ""),
    ("Jay Park", "Sunday Night Drive", ""),
    ("Blued", "Blue", "Blue"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Knoxx", "Knoxx", ""),
    ("Polodared", "Multiverse", ""),
    ("Hej!", "Drive", ""),
    ("Futuristic Swaver", "Villain", ""),
    ("Hodaky", "Yellow", ""),
    ("Chillin Homie", "Good Day", ""),
    ("Uneducated Kid", "UNEDUCATED KID", ""),
    ("Superbee", "Superbee", ""),
    ("Mad Clown", "Maximum", "Potato"),
    ("Ahn Se-min", "물", "Show Me the Money 11"),
    ("Bluso", "Fade Away", ""),
    ("LeyonC", "Fall", ""),
    ("Hyunsang", "Take Care", ""),
    ("Woo", "Rain Drop", "Rain Drop"),
    ("Rohann", "Sunday", ""),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Blase", "City Life", ""),
    ("Simon Dominic", "GOTT", "GOTT"),
    ("Lee Young Ji", "O.K?", "O.K?"),
    ("Jessi", "Gum", "Gum"),
    ("BE'O", "Luxury (럭셔리)", "Show Me the Money 10"),
    ("Sokodomo", "IF I", "Show Me the Money 8"),
    ("Lil Boi", "Empty Head", ""),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Life", "Life"),
    ("JUSTHIS", "마이웨이 (MY WAY) (Prod. by Alti)", "Show Me the Money 11"),
    ("NSW yoon", "Therapy + 으리으리 (Feat. 호미들)", "Show Me the Money 11"),
    ("허성현", "미운오리새끼 (Prod. R.Tee)", "Show Me the Money 11"),
    ("Kan", "나침반 (Feat. UNEDUCATED KID, Superbee)", "Show Me the Money 11"),
    ("QM", "Come To My Stu (Feat. 릴러말즈)", "Show Me the Money 11"),
    ("노윤하", "Flick (Feat. BE'O, HAON)", "Show Me the Money 11"),
    ("잠비노", "Bingo (Feat. 미노이, George)", "Show Me the Money 11"),
    ("Don Malik", "빡 (Feat. JUSTHIS, Paloalto)", "Show Me the Money 11"),
    ("Don Malik", "눈 (EYE) (Feat. BIG Naughty, JUSTHIS)", "Show Me the Money 11"),
    ("이영지", "WITCH (Feat. 밸재범, 황소윤)", "Show Me the Money 11"),
    ("Baechigi", "상어의 이야기", "Shark's Tale"),
    ("Swings", "Brand New Day", "Upgrade III"),
    ("Mirani", "Ticket", "Ticket"),
    ("Woodie Gochild", "GOchild", "#GOchild"),
    ("Owen Ovadoz", "Freeze", "119"),
    ("Blase", "Blue", ""),
    ("Giriboy", "PlanetariuM", "Engineering"),
    ("Punchnello", "Everyday", "Everyday"),
    ("Colde", "Reno", ""),
    ("Heize", "Forgotten Love", "Last Winter"),
    ("Crush", "EZPZ", "wonderego"),
    ("Loco", "Pick Pick", "WEAK"),
    ("Zion.T", "NOT FOR SALE", "Zip"),
    ("Dean", "Die 4 You", ""),
    ("Flowsik", "Unbreakable (언브레이커블)", "Show Me the Money 8"),
    ("Reddy", "THINK (띵)", "Show Me the Money 777"),
    ("KittiB", "Nobody Knows", "Show Me the Money 777"),
    ("Koonta", "VVS", "Show Me the Money 8"),
    ("Giriboy", "on my way", "Show Me the Money 8"),
    ("BIG Naughty", "Vogue", "Vogue"),
    ("Rohann", "Problem", "Problem"),
    ("Thama", "In My Room", "In My Room"),
    ("TOIL", "MAZE (메이즈)", "MAZE"),
    ("Mirani", "VANS", "Show Me the Money 8"),
    ("Zion.T", "No Make Up (feat. Wonstein)", "No Make Up"),
    ("Code Kunst", "Buckle Up (버클 업)", "Code Kunst Archive Pack 02"),
    ("Zion.T", "Spring Dream (봄꿈)", "Zionic"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("Kid Milli", "Cliché (클리셰)", "Cliché"),
    ("Hash Swan", "Retro Love", ""),
    ("Jvcki Wai", "Doughnet", "Exposure"),
    ("Simon Dominic", "make her dance (메이크 허 댄스)", "GOTT"),
    ("Blase", "Holiday (Feat. Lil Boi, 기리보이)", "Show Me the Money 11"),
    ("Ahn Se-min", "물", "Show Me the Money 11"),
]

HEAD_2024 = [
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER", "Übermensch"),
    ("Beenzino", "Train", ""),
    ("Changmo", "Wonderful Days", ""),
    ("Lil Moshpit", "K-FLIP", "K-FLIP+"),
    ("Kid Milli", "5AM", "RAD MILLI"),
    ("Dean", "NASA", "3:33"),
    ("Jay Park", "Taxi Blurr", ""),
    ("Crush", "Yes or No", ""),
    ("Heize", "Even if (이븐 이프)", ""),
]

CANDIDATES_2024 = [
    ("G-Dragon", "TAKE ME", "Übermensch"),
    ("G-Dragon", "Bonamana", "Übermensch"),
    ("Zico", "ZOOM", ""),
    ("Changmo", "HOLDUP", "Op.1"),
    ("Changmo", "ANTHEM", "Op.1"),
    ("Lil Moshpit", "KC2", "K-FLIP+"),
    ("Lil Moshpit", "LALALA", "K-FLIP+"),
    ("Lil Moshpit", "MADE IN KCOREA", "K-FLIP+"),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Kid Milli", "술", "RAD MILLI"),
    ("Kid Milli", "Summer Time", "RAD MILLI"),
    ("Dean", "Ctrl", "3:33"),
    ("Jay Park", "Stand Out", ""),
    ("Loco", "random summer night", ""),
    ("Loco", "Smeraldo Garden Marching Band", ""),
    ("Crush", "Fallin'", ""),
    ("Leellamarz", "Let me go to heaven", ""),
    ("Leellamarz", "GONE", ""),
    ("The Quiett", "LF Intro", "Luxury Flow"),
    ("The Quiett", "Look Inside", "Luxury Flow"),
    ("Bobby", "Sae", "Sir.Robert"),
    ("Bobby", "Harmless", "Sir.Robert"),
    ("Coogie", "ON FIRE", ""),
    ("Coogie", "Flame", "UPSET"),
    ("PH-1", "FLAT COKE", ""),
    ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
    ("Punchnello", "before you", ""),
    ("Gray", "SLIDIN'", ""),
    ("Giriboy", "heat", "heat"),
    ("Dynamic Duo", "Highfive", ""),
    ("Epik High", "Stop the Rain", ""),
    ("Ash Island", "Malibu", "Ash Island"),
    ("TOIL", "염염상망", ""),
    ("Blase", "INDUSTRY", "SELF MADE"),
    ("Blase", "12345678", "SELF MADE"),
    ("Mirani", "Drama", "Drama"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Owen Ovadoz", "Diamond", "119"),
    ("BE'O", "Momentum", "Show Me the Money 10"),
    ("Lee Young Ji", "Not Sure", "16"),
    ("Jessi", "Zoom", ""),
    ("Sik-K", "MAKE OUT", "MAKE OUT"),
    ("Nafla", "MVP", "[ Album ]"),
    ("Loopy", "DOPE", "SEOUL pt.A"),
    ("Loopy", "DEAD MAN WALKING", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Penomeco", "COCO BOTTLE", ""),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Gaeko", "Gajah", "Gajah"),
    ("Swings", "Per se", "Per se"),
    ("Mino", "Trigger", "XX"),
    ("Zion.T", "Snooze", "Zion.T Special: OO"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE", "THURSDAYCLUB MIXTAPE"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("82MAJOR", "Stuck", "Beat Road"),
    ("Epik High", "Frost", "Strawberry"),
    ("Kid Milli", "Feel Good", "RAD MILLI"),
    ("Coogie", "Shut Up", "UPSET"),
    ("Coogie", "BABYFACE", "UPSET"),
    ("Leellamarz", "Hell yea", "L&B"),
    ("Leellamarz", "Two Pills", "STILL YOUNG BOY L"),
    ("The Quiett", "Crystal Crates", "Luxury Flow"),
    ("Gray", "Real Love", "Remedy"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Ash Island", "ISLAND", "ISLAND"),
    ("Mirani", "Ticket", "Ticket"),
    ("Blase", "KKUCKDARI", "SELF MADE"),
    ("BE'O", "Healing", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Sik-K", "Wet", "MAKE OUT"),
    ("Nafla", "Jazz Freestyle", "[ Album ]"),
    ("Loopy", "CROWN", "SEOUL pt.A"),
    ("Loopy", "PINK SPILL", "SEOUL pt.A"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Swings", "Remedy", "Remedy"),
    ("Lil Boi", "ONFleek", "Show Me the Money 9"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Cool", "Cool"),
    ("PLT", "Summer", "Summer"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Hero", "Hero"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("C Jamm", "RED", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Blued", "Blue", "Blue"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "BILLING", "BILLING"),
    ("Mudd the student", "Nectar", "Show Me the Money 10"),
    ("Qwala", "If WONA becomes a gangster (Feat. Qwala, New Champ)", ""),
    ("meenoi", "Malfunction", ""),
    ("CAMO", "Wifey", ""),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Knoxx", "Knoxx", ""),
    ("Polodared", "Multiverse", ""),
    ("Hej!", "Drive", ""),
    ("Futuristic Swaver", "Villain", ""),
    ("Hodaky", "Yellow", ""),
    ("Chillin Homie", "Good Day", ""),
    ("Uneducated Kid", "UNEDUCATED KID", ""),
    ("Superbee", "Superbee", ""),
    ("Mad Clown", "Maximum", "Potato"),
    ("Bluso", "Fade Away", ""),
    ("LeyonC", "Fall", ""),
    ("Hyunsang", "Take Care", ""),
    ("Woo", "Rain Drop", "Rain Drop"),
    ("Rohann", "Sunday", ""),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Life", "Life"),
    ("BIG Naughty", "Você", "Você"),
    ("Giriboy", "Girlfriend", ""),
    ("Coq", "Tweaker", ""),
    ("B.I", "Lover", ""),
    ("Rad Museum", "Girls", "Life"),
]

HEAD_2025 = [
    ("G-Dragon", "Too Bad", "Übermensch"),
    ("Crush", "UP ALL NITE", "FANG"),
    ("Loco", "work++", "SCRAPS"),
    ("Changmo", "HOLDUP", "Op.1"),
    ("PH-1", "GOSHA", "WHAT HAVE WE DONE"),
    ("Lil Moshpit", "K-FLIP", "K-FLIP+"),
    ("Beenzino", "Train", ""),
    ("Kid Milli", "5AM", "RAD MILLI"),
    ("Dean", "NASA", "3:33"),
    ("Heize", "Love Virus (러브 바이러스)", "LOVE VIRUS Pt.1"),
]

CANDIDATES_2025 = [
    ("Heize", "Last Taxi (라스트 택시)", "LOVE VIRUS Pt.1"),
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER", "Übermensch"),
    ("G-Dragon", "TAKE ME", "Übermensch"),
    ("Crush", "FANG", "FANG"),
    ("Loco", "SCRAPS", "SCRAPS"),
    ("Changmo", "Wonderful Days", ""),
    ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
    ("Lil Moshpit", "KC2", "K-FLIP+"),
    ("Zico", "SPOT!", ""),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("82MAJOR", "FIRST CLASS", "ON"),
    ("Epik High", "Strawberry", "Strawberry"),
    ("Giriboy", "Girlfriend", ""),
    ("BIG Naughty", "Você", "Você"),
    ("meenoi", "Malfunction", ""),
    ("Don Malik", "SEOUL", "MADE IN SEOUL"),
    ("Beenzino", "Trippy", "NOWITZKI"),
    ("Lil Moshpit", "TO GO", ""),
    ("Jay Park", "Taxi Blurr", ""),
    ("Leellamarz", "Let me go to heaven", ""),
    ("The Quiett", "LF Intro", "Luxury Flow"),
    ("Bobby", "Sae", "Sir.Robert"),
    ("Coogie", "ON FIRE", ""),
    ("Gray", "SLIDIN'", ""),
    ("Giriboy", "heat", "heat"),
    ("Dynamic Duo", "Highfive", ""),
    ("Ash Island", "Malibu", "Ash Island"),
    ("TOIL", "염염상망", ""),
    ("Blase", "INDUSTRY", "SELF MADE"),
    ("Mirani", "Drama", "Drama"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Owen Ovadoz", "Diamond", "119"),
    ("BE'O", "Momentum", "Show Me the Money 10"),
    ("Lee Young Ji", "Not Sure", "16"),
    ("Jessi", "Zoom", ""),
    ("Sik-K", "MAKE OUT", "MAKE OUT"),
    ("Nafla", "MVP", "[ Album ]"),
    ("Loopy", "DOPE", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Penomeco", "COCO BOTTLE", ""),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Gaeko", "Gajah", "Gajah"),
    ("Swings", "Per se", "Per se"),
    ("Mino", "Trigger", "XX"),
    ("Zion.T", "Snooze", "Zion.T Special: OO"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE", "THURSDAYCLUB MIXTAPE"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("Epik High", "Frost", "Strawberry"),
    ("Kid Milli", "Feel Good", "RAD MILLI"),
    ("Coogie", "Shut Up", "UPSET"),
    ("Leellamarz", "Hell yea", "L&B"),
    ("The Quiett", "Crystal Crates", "Luxury Flow"),
    ("Gray", "Real Love", "Remedy"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Ash Island", "ISLAND", "ISLAND"),
    ("Mirani", "Ticket", "Ticket"),
    ("Blase", "KKUCKDARI", "SELF MADE"),
    ("BE'O", "Healing", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Sik-K", "Wet", "MAKE OUT"),
    ("Nafla", "Jazz Freestyle", "[ Album ]"),
    ("Loopy", "CROWN", "SEOUL pt.A"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Swings", "Remedy", "Remedy"),
    ("Lil Boi", "ONFleek", "Show Me the Money 9"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Cool", "Cool"),
    ("PLT", "Summer", "Summer"),
    ("Trade L", "Leave It (두고 가)", "Show Me the Money 10"),
    ("Wonstein", "10 Minutes (10분)", "Show Me the Money 10"),
    ("Paul Blanco", "Summer (썸머)", "Summer"),
    ("Killagramz", "Good Morning (굿 모닝)", "Good Morning"),
    ("Hanhae", "003", "003"),
    ("B.I", "Waterfall (워터폴)", "Waterfall"),
    ("Tabber", "RUN CHICKEN (런 치킨)", "RUN CHICKEN"),
    ("Khundi Panda", "Medicine (약)", "Medicine"),
    ("Roh Yun Ha", "IF I (이프 아이)", "Show Me the Money 10"),
    ("Illinit", "Real Talk Live (리얼 토크)", ""),
    ("B-Free", "Best Seller (베스트 셀러)", "Best Seller"),
    ("Vasco", "The Vasco", "The Vasco"),
    ("Outsider", "Vol.2-Maestro 4", "Vol.2-Maestro 4"),
    ("G2", "G2 (지투)", "G2"),
    ("Cheetah", "I'll Be Back (아일 비 백)", ""),
    ("J'Kyun", "Fly Away (플라이 어웨이)", "Ready to Fly"),
    ("Don Mills", "Don Mills Is Angry 6", "Don Mills Is Angry 6"),
    ("Myun Do One", "Bulldozer", "Myun Do One Is Back"),
    ("Jerry.K", "V", "V"),
    ("Bumkey", "Single Life", "Single Life"),
    ("Junggigo", "Rookie", "Rookie"),
    ("Dok2", "Thug Life Part 2", "Thug Life Part 2"),
    ("Rhymer", "Brand New Day", "Rhymer Trax Vol.1"),
    ("Double K", "Fly High", "Fly High"),
    ("Pe2ny", "Pe2ny Maker", "Pe2ny Maker"),
    ("Sean2Slow", "Slow Jam", "Slow Jam"),
    ("MC Meta", "On My Own", "The Blue Printz"),
    ("Geologic", "Hero", "Hero"),
    ("Mighty Mouth", "San", "San"),
    ("Skull", "I'm Your Man", "I'm Your Man"),
    ("Phantom", "Bubble Love", "Phantom City"),
    ("MellowD", "On My Way", "On My Way"),
    ("Reddy", "Commitment", "Commitment"),
    ("Kid Ash", "Orca-Tape", "Orca-Tape"),
    ("C Jamm", "RED", ""),
    ("Olltii", "Creative Control", "Creative Control"),
    ("Koonta", "KOONTA (쿤타)", "Show Me the Money 10"),
    ("NO:EL", "Rain Drop 2", "Rain Drop 2"),
    ("Blued", "Blue", "Blue"),
    ("E-Sens", "이상형", "The Anecdote"),
    ("San E", "a SONG of ICE and FIRE", "a SONG of ICE and FIRE"),
    ("Primary", "BILLING", "BILLING"),
    ("Mudd the student", "Nectar", "Show Me the Money 10"),
    ("Knoxx", "Knoxx", ""),
    ("Polodared", "Multiverse", ""),
    ("Hej!", "Drive", ""),
    ("Futuristic Swaver", "Villain", ""),
    ("Hodaky", "Yellow", ""),
    ("Chillin Homie", "Good Day", ""),
    ("Uneducated Kid", "UNEDUCATED KID", ""),
    ("Superbee", "Superbee", ""),
    ("Mad Clown", "Maximum", "Potato"),
    ("Bluso", "Fade Away", ""),
    ("LeyonC", "Fall", ""),
    ("Hyunsang", "Take Care", ""),
    ("Woo", "Rain Drop", "Rain Drop"),
    ("Rohann", "Sunday", ""),
    ("Thama", "Long Time No See", "Long Time No See"),
    ("Queenpia", "Queenpia", "Queenpia"),
    ("Sumin", "Mirrorball", "Mirrorball"),
    ("MoonMoon", "Tourist", "Tourist"),
    ("E Sens", "Mona Lisa", "Mona Lisa"),
    ("DPR LIVE", "Jasmine", "Jasmine"),
    ("Woo Won Jae", "Hourglass", "Hourglass"),
    ("Rad Museum", "Life", "Life"),
    ("CAMO", "Wifey", ""),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Coq", "Tweaker", ""),
    ("B.I", "Lover", ""),
    ("Rad Museum", "Girls", "Life"),
    ("Dean", "Ctrl", "3:33"),
    ("Crush", "Yes or No", ""),
    ("Crush", "Fallin'", ""),
    ("Heize", "Even if (이븐 이프)", ""),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Epik High", "Stop the Rain", ""),
    ("Paloalto", "GONE", ""),
    ("Mino", "Smoke", "BODY"),
    ("Bobby", "Drowning", "S.i.R"),
    ("Zion.T", "UNLOVE", "Zip"),
    ("Loco", "VOLVO", ""),
    ("Dean", "NO FUN", "howlin' 404"),
    ("Heize", "Perhaps Happy Ending (아마도 해피 엔딩)", "Last Winter"),
]

YEAR_CONFIG = {
    2023: (HEAD_2023, CANDIDATES_2023),
    2024: (HEAD_2024, CANDIDATES_2024),
    2025: (HEAD_2025, CANDIDATES_2025),
}


def main() -> None:
    path = os.path.join(HERE, "pools_2022_2025.py")
    with open(path, encoding="utf-8") as f:
        text = f.read()

    for year, (head, cands) in YEAR_CONFIG.items():
        pool = pick_pool(year, head, cands)
        n, artists, _ = simulate(year, head, pool)
        print(f"{year}: pool={len(pool)} simulate={n}/100 artists={artists}")
        if n < 100:
            print(f"  WARNING short {100 - n}")
        text = rewrite_section(text, "HEAD", year, head)
        text = rewrite_section(text, "POOLS", year, pool)

    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("Done rewrite pools_2022_2025.py")


if __name__ == "__main__":
    main()
