# 2024 underground / indie 발매 (HiphopKR·리드머 기준)
UNDERGROUND_2024 = [
    ("Crucial Star", "Nihilism Watch", ""),
    ("ChaMane", "BATON PASS", "BATON PASS"),
    ("HD BL4CK", "BATON PASS", "BATON PASS"),
    ("Khundi Panda", "Somozu Fury", ""),
    ("J'Kyun", "AGAPE", "AGAPE"),
    ("Leellamarz", "B", ""),
    ("meenoi", "B", ""),
    ("GroovyRoom", "Yes or No", ""),
    ("Wonstein", "It's not beautiful and it doesn't hurt", ""),
    ("Flowsik", "Movin'", ""),
    ("Don Mills", "OK", ""),
    ("Don Mills", "인생을 바꿀", "The Life-Changing Album"),
    ("GwangilJo", "Light Adaptation", "Light Adaptation"),
    ("QM", "개미", "개미"),
    ("Qwala", "DISTORTED", "DISTORTED"),
    ("Paloalto", "Lovers Turn to Haters", "Lovers Turn to Haters"),
    ("Khundi Panda", "MODM 2 : The Bento Knight", "MODM 2 : The Bento Knight"),
    ("B-Free", "Free The Mane 2", 'Free The Mane 2 "Free The Mane VS 최승로"'),
    ("Garion", "Garion 3", "Garion 3"),
    ("O'koye", "Yezzir", "Whether the Weather Changes or Not"),
    ("O'koye", "Hallelujah", "Whether the Weather Changes or Not"),
    ("Rad Museum", "Rad Milli", "Rad Milli"),
    ("Chillin Homie", "Maze Runner", "Maze Runner"),
    ("Dbo", "Be Back Soon", "Be Back Soon"),
    ("Homies", "Yains", "Yains"),
    ("Loopy", "MARNI", "MARNI"),
    ("Los", "Skandalouz 2", "Skandalouz 2"),
    ("Sik-K", "KC (BUST IT DOWN)", ""),
    ("HAON", "KC (BUST IT DOWN)", ""),
    ("Leellamarz", "KC (BUST IT DOWN)", ""),
    ("BIGONE", "COLORFUL ZEBRA", ""),
    ("BOYCOLD", "Sick of Love", "Sick of Love"),
    ("viceversa", "N!kes", ""),
    ("KIDO", "MACHINES", ""),
    ("Ash-B", "Wish", ""),
    ("XWALLY", "BORN2RAVE", "BORN2RAVE"),
    ("AP Alchemy", "Monthly AP – January, 2024", "Monthly AP – January, 2024"),
    ("Leebido", "A prescription for 2", "A prescription for 2"),
    ("ShyboiiTobii", "Dillis", ""),
    ("Moon Sujin", "Better", "Better"),
    ("Owen Ovadoz", "P.O.E.M.", "P.O.E.M."),
    ("noisemasterminsu", "I KNOW YOU LOVE ME", ""),
    ("lil9ap", "Drama/R&B", "Drama/R&B"),
    ("basecamp", "camp", ""),
    ("ShyboiiTobii", "Breaking Bad", ""),
    ("CK", "Verses", "Verses"),
    ("KAMBO", "Rapstar", ""),
    ("1300", "Ape Sh*t", ""),
    ("YUGYEOM", "LA SOL MI", ""),
    ("HD BL4CK", "Vantablack Dreams", "Vantablack Dreams"),
    ("DPR ARTIC", "KINEMA", "KINEMA"),
    ("Marv", "Ok", ""),
    ("Junoflo", "Love Like This", ""),
    ("KAMBO", "Dreamatic", "Dreamatic"),
    ("JMIN", "Sorry I'm Late", "Sorry I'm Late"),
    ("Panda Gomm", "Home Vacation", "Home Vacation"),
    ("CHIO CHICANO", "Big Squad", ""),
    ("Tiger JK", "T.K.D", "T.K.D"),
    ("Dabin", "Giggles", "Giggles"),
    ("Untell", "Animal", "Animal"),
    ("Skinny Chase", "Journey to the West", "Journey to the West"),
    ("Fredi Casso", "Death Therapy", "Death Therapy"),
    ("Ambid Jack", "Death Therapy", "Death Therapy"),
    ("Ja Mezz", "Only", "Only"),
    ("Bangroz", "Only", "Only"),
    ("Hyeminsong", "Reborn", "Reborn"),
    ("Minit", "He♡rt", "He♡rt"),
    ("Okashii", "Orton", "Orton"),
    ("Antihuman", "Antihuman", "Antihuman"),
    ("Yugyeom", "LA SOL MI", "LA SOL MI"),
    ("Ted Park", "Home Alone 2.0", "Home Alone 2.0"),
    ("viceversa", "I'M UP", ""),
    ("KIDO", "MACHINES", ""),
    ("D.Ark", "Undercover", "Genius"),
    ("EK", "Escape", "Escape"),
    ("Haon", "Haonoah", "Haonoah"),
    ("Flowsik", "Worlds Apart", "Worlds Apart"),
    ("Epik High", "Pump", "Pump"),
    ("Bryn", "Supercharged", "Supercharged"),
    ("Balming Tiger", "Greatest Hits", "Greatest Hits"),
    ("BIG Naughty", "+", "+"),
    ("Kid Milli", "+", "+"),
    ("RM", "Right Place, Wrong Person", "Right Place, Wrong Person"),
    ("The Quiett", "Luxury Flow", "Luxury Flow"),
    ("Rad Museum", "Rad Milli", "Rad Milli"),
    ("Changmo", "Wonderful Days", "Wonderful Days"),
    ("Dbo", "Be Back Soon", "Be Back Soon"),
    ("Garion", "Garion 3", "Garion 3"),
    ("B-Free", "Free Hukky Shibaseki", "Free Hukky Shibaseki & the God Sun Symphony Group : Odyssey.1"),
    ("BRADYSTREET", "Brady Street", ""),
    ("BRADYSTREET", "Heavy", ""),
    ("Gist", "Engagement", ""),
    ("Jay Park", "Need To Know", "THE ONE YOU WANTED"),
    ("TOIL", "MAZE (메이즈)", "MAZE"),
    ("Code Kunst", "Rain (비)", "Code Kunst Archive Pack 02"),
]
