# 2025 발매 (HiphopKR·멜론 기준)
UNDERGROUND_2025 = [
    ("G-Dragon", "Too Bad", "Übermensch"),
    ("G-Dragon", "HOME SWEET HOME (Feat. 태양, 대성)", "Übermensch"),
    ("G-Dragon", "POWER", "Übermensch"),
    ("G-Dragon", "TAKE ME", "Übermensch"),
    ("G-Dragon", "Bonamana", "Übermensch"),
    ("G-Dragon", "Drama", "Übermensch"),
    ("Crush", "UP ALL NITE", "FANG"),
    ("Crush", "FANG", "FANG"),
    ("Loco", "work++", "SCRAPS"),
    ("Loco", "SCRAPS", "SCRAPS"),
    ("Heize", "Love Virus (러브 바이러스)", "LOVE VIRUS Pt.1"),
    ("Heize", "Last Taxi (라스트 택시)", "LOVE VIRUS Pt.1"),
    ("PH-1", "GOSHA", "WHAT HAVE WE DONE"),
    ("PH-1", "WHAT HAVE WE DONE", "WHAT HAVE WE DONE"),
    ("Changmo", "HOLDUP", "Op.1"),
    ("Changmo", "ANTHEM", "Op.1"),
    ("Lil Moshpit", "K-FLIP", "K-FLIP+"),
    ("Lil Moshpit", "KC2", "K-FLIP+"),
    ("Beenzino", "Train", ""),
    ("Kid Milli", "5AM", "RAD MILLI"),
    ("Dean", "NASA", "3:33"),
    ("Jay Park", "Taxi Blurr", ""),
    ("Crush", "Yes or No", ""),
    ("Heize", "Even if (이븐 이프)", ""),
    ("Zico", "ZOOM", ""),
    ("Changmo", "Wonderful Days", ""),
    ("Sokodomo", "Merry Go Round", "Merry Go Round"),
    ("Qwala", "델러가 (Feat. MELOH & Posadic)", "yorter"),
    ("Qwala", "DISTORTED", "DISTORTED"),
    ("Leellamarz", "Let me go to heaven", ""),
    ("Leellamarz", "GONE", ""),
    ("The Quiett", "LF Intro", "Luxury Flow"),
    ("Bobby", "Sae", "Sir.Robert"),
    ("Coogie", "ON FIRE", ""),
    ("Gray", "SLIDIN'", ""),
    ("Giriboy", "heat", "heat"),
    ("Dynamic Duo", "Highfive", ""),
    ("Ash Island", "Malibu", "Ash Island"),
    ("TOIL", "염염상망", ""),
    ("Blase", "INDUSTRY", "SELF MADE"),
    ("Mirani", "Drama", "Drama"),
    ("Woodie Gochild", "Mood Swings", "#GOchild"),
    ("Owen Ovadoz", "Diamond", "119"),
    ("BE'O", "Momentum", "Show Me the Money 10"),
    ("Lee Young Ji", "Not Sure", "16"),
    ("Jessi", "Zoom", ""),
    ("Sik-K", "MAKE OUT", "MAKE OUT"),
    ("Nafla", "MVP", "[ Album ]"),
    ("Loopy", "DOPE", "SEOUL pt.A"),
    ("YUMDDA", "Tic Toc", "I'm Good"),
    ("Hash Swan", "Hash Brand", "Hash Brand"),
    ("Jvcki Wai", "Taxi Blurr", "Taxi Blurr"),
    ("BewhY", "Cult of Curiosity", "Cult of Curiosity"),
    ("Penomeco", "COCO BOTTLE", ""),
    ("Simon Dominic", "Simon Dominic Part 3", "Simon Dominic Part 3"),
    ("Gaeko", "Gajah", "Gajah"),
    ("Swings", "Per se", "Per se"),
    ("Mino", "Trigger", "XX"),
    ("Zion.T", "Snooze", "Zion.T Special: OO"),
    ("Don Malik", "THURSDAYCLUB MIXTAPE", "THURSDAYCLUB MIXTAPE"),
    ("82MAJOR", "뭘 봐 (TAKEOVER)", "X-82"),
    ("Epik High", "Frost", "Strawberry"),
    ("Coogie", "Shut Up", "UPSET"),
    ("Leellamarz", "Hell yea", "L&B"),
    ("The Quiett", "Crystal Crates", "Luxury Flow"),
    ("Gray", "Real Love", "Remedy"),
    ("Giriboy", "Mechanical Album", "Mechanical Album"),
    ("Ash Island", "ISLAND", "ISLAND"),
    ("Mirani", "Ticket", "Ticket"),
    ("Blase", "KKUCKDARI", "SELF MADE"),
    ("BE'O", "Healing", "Show Me the Money 10"),
    ("Lee Young Ji", "Yumeyo", "16"),
    ("Sik-K", "Wet", "MAKE OUT"),
    ("Loopy", "CROWN", "SEOUL pt.A"),
    ("Hash Swan", "Hash Brand 2", "Hash Brand 2"),
    ("Jvcki Wai", "Neo Eve", "Exposure"),
    ("Penomeco", "Shy (수줍)", "Shy"),
    ("Simon Dominic", "Make Her Dance", "Simon Dominic Part 3"),
    ("Gaeko", "Sturgis", "Sturgis"),
    ("Swings", "Remedy", "Remedy"),
    ("Lil Boi", "ONFleek", "Show Me the Money 9"),
    ("Colde", "In Your Eyes", "In Your Eyes"),
    ("Punchnello", "Cool", "Cool"),
    ("PLT", "Summer", "Summer"),
    ("Crucial Star", "Nihilism Watch", ""),
    ("ChaMane", "BATON PASS", "BATON PASS"),
    ("HD BL4CK", "BATON PASS", "BATON PASS"),
    ("Khundi Panda", "Somozu Fury", ""),
    ("J'Kyun", "AGAPE", "AGAPE"),
    ("Leellamarz", "B", ""),
    ("meenoi", "B", ""),
    ("GroovyRoom", "Yes or No", ""),
    ("Wonstein", "It's not beautiful and it doesn't hurt", ""),
    ("Flowsik", "Movin'", ""),
    ("Don Mills", "OK", ""),
    ("Don Mills", "인생을 바꿀", "The Life-Changing Album"),
    ("GwangilJo", "Light Adaptation", "Light Adaptation"),
    ("QM", "개미", "개미"),
    ("Paloalto", "Lovers Turn to Haters", "Lovers Turn to Haters"),
    ("Khundi Panda", "MODM 2 : The Bento Knight", "MODM 2 : The Bento Knight"),
    ("B-Free", "Free The Mane 2", 'Free The Mane 2 "Free The Mane VS 최승로"'),
    ("Garion", "Garion 3", "Garion 3"),
    ("O'koye", "Yezzir", "Whether the Weather Changes or Not"),
    ("O'koye", "Hallelujah", "Whether the Weather Changes or Not"),
    ("Rad Museum", "Rad Milli", "Rad Milli"),
    ("Chillin Homie", "Maze Runner", "Maze Runner"),
    ("Dbo", "Be Back Soon", "Be Back Soon"),
    ("Homies", "Yains", "Yains"),
    ("Loopy", "MARNI", "MARNI"),
    ("Los", "Skandalouz 2", "Skandalouz 2"),
    ("Sik-K", "KC (BUST IT DOWN)", ""),
    ("HAON", "KC (BUST IT DOWN)", ""),
    ("BIGONE", "COLORFUL ZEBRA", ""),
    ("BOYCOLD", "Sick of Love", "Sick of Love"),
    ("viceversa", "N!kes", ""),
    ("KIDO", "MACHINES", ""),
    ("Ash-B", "Wish", ""),
    ("XWALLY", "BORN2RAVE", "BORN2RAVE"),
    ("AP Alchemy", "Monthly AP – January, 2024", "Monthly AP – January, 2024"),
    ("Leebido", "A prescription for 2", "A prescription for 2"),
    ("ShyboiiTobii", "Dillis", ""),
    ("Moon Sujin", "Better", "Better"),
    ("Owen Ovadoz", "P.O.E.M.", "P.O.E.M."),
    ("noisemasterminsu", "I KNOW YOU LOVE ME", ""),
    ("lil9ap", "Drama/R&B", "Drama/R&B"),
    ("basecamp", "camp", ""),
    ("ShyboiiTobii", "Breaking Bad", ""),
    ("CK", "Verses", "Verses"),
    ("KAMBO", "Rapstar", ""),
    ("1300", "Ape Sh*t", ""),
    ("YUGYEOM", "LA SOL MI", ""),
    ("HD BL4CK", "Vantablack Dreams", "Vantablack Dreams"),
    ("DPR ARTIC", "KINEMA", "KINEMA"),
    ("Marv", "Ok", ""),
    ("Junoflo", "Love Like This", ""),
    ("KAMBO", "Dreamatic", "Dreamatic"),
    ("JMIN", "Sorry I'm Late", "Sorry I'm Late"),
    ("Panda Gomm", "Home Vacation", "Home Vacation"),
    ("CHIO CHICANO", "Big Squad", ""),
    ("Tiger JK", "T.K.D", "T.K.D"),
    ("Dabin", "Giggles", "Giggles"),
    ("Untell", "Animal", "Animal"),
    ("Skinny Chase", "Journey to the West", "Journey to the West"),
    ("Fredi Casso", "Death Therapy", "Death Therapy"),
    ("Ambid Jack", "Death Therapy", "Death Therapy"),
    ("Ja Mezz", "Only", "Only"),
    ("Bangroz", "Only", "Only"),
    ("Hyeminsong", "Reborn", "Reborn"),
    ("Minit", "He♡rt", "He♡rt"),
    ("Okashii", "Orton", "Orton"),
    ("Ted Park", "Home Alone 2.0", "Home Alone 2.0"),
    ("viceversa", "I'M UP", ""),
    ("D.Ark", "Undercover", "Genius"),
    ("EK", "Escape", "Escape"),
    ("Haon", "Haonoah", "Haonoah"),
    ("Flowsik", "Worlds Apart", "Worlds Apart"),
    ("Epik High", "Pump", "Pump"),
    ("Bryn", "Supercharged", "Supercharged"),
    ("Balming Tiger", "Greatest Hits", "Greatest Hits"),
    ("BIG Naughty", "+", "+"),
    ("Kid Milli", "+", "+"),
    ("RM", "Right Place, Wrong Person", "Right Place, Wrong Person"),
    ("BRADYSTREET", "Brady Street", ""),
    ("BRADYSTREET", "Heavy", ""),
    ("Gist", "Engagement", ""),
    ("Jay Park", "Need To Know", "THE ONE YOU WANTED"),
    ("TOIL", "MAZE (메이즈)", "MAZE"),
    ("Code Kunst", "Rain (비)", "Code Kunst Archive Pack 02"),
    ("CAMO", "Melody", "Melody"),
    ("Mudd the student", "Sleepy Beauty", ""),
    ("Olltii", "Turtle Ship Remix", ""),
    ("Jessi", "Cold Blooded", "Cold Blooded"),
    ("Lee Young Ji", "O.K?", "O.K?"),
    # 2025 HiphopKR 신규
    ("Owen Ovadoz", "TANG", "POEMV"),
    ("Owen Ovadoz", "TREND", "POEMV"),
    ("Owen Ovadoz", "SUCCEEDING", "POEMV"),
    ("Owen Ovadoz", "TRUTH (feat. Marv, Nieah)", "POEMV"),
    ("Owen Ovadoz", "5AM IN SYDNEY", "POEMV"),
    ("Owen Ovadoz", "BE MY LOVE (feat. Seo Ja Yeong)", "POEMV"),
    ("Owen Ovadoz", "TUNED IN", "POEMV"),
    ("Owen Ovadoz", "ALL ALIKE", "POEMV"),
    ("Owen Ovadoz", "TILL I DIE (feat. EK)", "POEMV"),
    ("Owen Ovadoz", "ALL IS FINE", "POEMV"),
    ("Owen Ovadoz", "BONAFIED", "POEMV"),
    ("Owen Ovadoz", "TWELVE (feat. Wuuslime)", "POEMV"),
    ("Owen Ovadoz", "TEARS", "POEMV"),
    ("Owen Ovadoz", "ANGEL", "POEMV"),
    ("Owen Ovadoz", "TANTRUM (feat. The Quiett)", "POEMV"),
    ("Owen Ovadoz", "INTENTIONS", "POEMV"),
    ("Owen Ovadoz", "MUST BE KIDDING (feat. Paloalto)", "POEMV"),
    ("Owen Ovadoz", "FOREVER YOUNG (feat. foggyatthebottom)", "POEMV"),
    ("EK", "YAHO", "YAHO"),
    ("EK", "MollyWorld (feat. GV)", "YAHO"),
    ("EK", "FLY", "YAHO"),
    ("EK", "Supernova", "YAHO"),
    ("EK", "Machine", "YAHO"),
    ("EK", "Back In The Building (feat. Jeremy Que$t)", "YAHO"),
    ("EK", "Same (feat. YUMDDA)", "YAHO"),
    ("EK", "AFTER PARTY", "YAHO"),
    ("EK", "BE GOOD", "YAHO"),
    ("EK", "MR.P", "YAHO"),
    ("EK", "Coming Sunny Days", "YAHO"),
    ("EK", "Religion True (feat. MILLHAM)", "YAHO"),
    ("Don Malik", "Spinboutu", "Love is a Song"),
    ("DeVita", "Spinboutu", "Love is a Song"),
    ("Don Malik", "oh wow", "Love is a Song"),
    ("DeVita", "oh wow", "Love is a Song"),
    ("Don Malik", "White T", "Love is a Song"),
    ("Don Malik", "chuum", "Love is a Song"),
    ("Don Malik", "DAP", "Love is a Song"),
    ("Don Malik", "How To Make Love Song", "Love is a Song"),
    ("Don Malik", "name cost", "Love is a Song"),
    ("Don Malik", "Savio, Draco", "Love is a Song"),
    ("Don Malik", "Pornography", "Love is a Song"),
    ("Don Malik", "Ew", "Love is a Song"),
    ("Don Malik", "Winter is Coming", "Love is a Song"),
    ("Royal 44", "Classical Freestyle", "We Got What You Need"),
    ("Royal 44", "New Money", "We Got What You Need"),
    ("Royal 44", "2025 (U Got It)", "We Got What You Need"),
    ("Yung Blesh", "Classical Freestyle", "We Got What You Need"),
    ("Yung Blesh", "New Money", "We Got What You Need"),
    ("Royal 44", "Dolce & Gabbana", "We Got What You Need"),
    ("Royal 44", "City Girls", "We Got What You Need"),
    ("Royal 44", "Sexy Club", "We Got What You Need"),
    ("Royal 44", "Beautiful Life", "We Got What You Need"),
    ("Royal 44", "Supertrap (feat. Wuuslime)", "We Got What You Need"),
    ("Royal 44", "Racks (feat. ShyboiiTobii, GGM Kimbo)", "We Got What You Need"),
    ("Royal 44", "Party Shit (feat. Wuuslime, JMIN)", "We Got What You Need"),
    ("BlackNut", "0", ""),
    ("Bassagong", "Comfort", ""),
    ("Bassagong", "Rock N Roll Baby (Feat. G2 & CHANGMO)", ""),
    ("YANGHONGWON", "LEAN", ""),
    ("Nosun", "Exit Wounds", "Exit Wounds"),
    ("B-Free", "Free The Mane 3", "Free The Mane 3"),
    ("Wuuslime", "Wuuslime", ""),
    ("Marv", "Marv", ""),
    ("Nieah", "Nieah", ""),
    ("foggyatthebottom", "FOREVER YOUNG", "POEMV"),
    ("GV", "GV", "YAHO"),
    ("Jeremy Que$t", "Jeremy Que$t", "YAHO"),
    ("MILLHAM", "MILLHAM", "YAHO"),
    ("GGM Kimbo", "GGM Kimbo", "We Got What You Need"),
    ("ShyboiiTobii", "ShyboiiTobii", "We Got What You Need"),
    ("JMIN", "JMIN", "We Got What You Need"),
    ("Kimeen", "Kimeen", ""),
    ("xorf1nn", "xorf1nn", ""),
    ("lahaine", "lahaine", ""),
    ("Pank", "Pank", ""),
    ("Royal 44", "EVOL", "EVOL"),
    ("Yung Blesh", "M.D.M.A 2", ""),
    ("Don Malik", "Made in Seoul", "MADE IN SEOUL"),
    ("DeVita", "Ride or Die", ""),
    ("Ourealgoat", "Maybe", ""),
    ("Blued", "Tears", ""),
    ("Coq", "Tweaker", ""),
    ("B.I", "Lover", ""),
    ("Rad Museum", "Girls", "Life"),
    ("meenoi", "Malfunction", ""),
    ("Lil Moshpit", "TO GO", ""),
    ("Zico", "SPOT!", ""),
    ("Epik High", "Strawberry", "Strawberry"),
    ("Giriboy", "Girlfriend", ""),
    ("Qwala", "ㅍㅍㅍㅍ (Feat. Kid Milli)", "ㅍㅍㅍㅍ"),
    ("82MAJOR", "FIRST CLASS", "ON"),
    ("Don Malik", "SEOUL", "MADE IN SEOUL"),
    ("Beenzino", "Trippy", "NOWITZKI"),
    ("BIG Naughty", "Você", "Você"),
]
