# 힙플·힙플레이·전문가 평가 기준 2016년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Dean', 'D (Half Moon)', '130 Mood : TRBL'),
    ('Dean', 'what2do', '130 Mood : TRBL'),
    ('Simon Dominic', 'GOTT', 'Show Me the Money 5'),
    ('BewhY', 'Movie Star', 'The Fiery'),
    ('Beenzino', 'Dali', ''),
    ('C Jamm', 'The Last', 'Show Me the Money 5'),
    ('Punchnello', 'My Piece', 'My Piece'),
    ('Sik-K', 'YESSIR', 'Trap Art'),
    ('Giriboy', 'Because', 'Mechanical Album'),
    ('Dynamic Duo', 'Highfive', ''),
    ('Gray', 'Good', ''),
    ('Loco', 'You Too', ''),
    ('Crush', '잊을만해', 'Interlude'),
    ('Zion.T', '노크', 'Show Me the Money 5'),
    ('Heize', '너, 나, 우리', ''),
    ('Jay Park', 'Me Like Yuh', 'EVERYTHING YOU WANTED'),
    ('BTS', '피 땀 눈물', 'WINGS'),
    ('BTS', '불타오르네', 'The Most Beautiful Moment in Life : Young Forever'),
    ('Loco', 'Still', ''),
    ('Beenzino', 'Vanilla Sky', ''),
    ('Jay Park', 'Drive', 'EVERYTHING YOU WANTED'),
    ('Crush', 'woo ah', 'Interlude'),
    ('BewhY', 'The Fiery', 'The Fiery'),
    ('Giriboy', "You're Pretty", 'Mechanical Album'),
    ('Sik-K', 'Throw That', 'Trap Art'),
    ('Punchnello', '펀치', 'My Piece'),
    ('Deepflow', 'Flow the Life 4', 'Flow the Life 4'),
    ('Huckleberry P', 'Mantra 4', 'Mantra 4'),
    ('Simon Dominic', 'Simon Dominic Part 3', 'Show Me the Money 5'),
    ('Zico', "It Isn't Love", 'Show Me the Money 5'),
    ('Hanhae', 'Drop', 'Show Me the Money 5'),
    ('Killagramz', 'Good Morning', 'Show Me the Money 5'),
    ('Jessi', 'China', 'Show Me the Money 5'),
    ('Hanhae', '드롭', 'Show Me the Money 5'),
    ('Killagramz', '굿모닝', 'Show Me the Money 5'),
    ('Jessi', '차이나', 'Show Me the Money 5'),
    ('Iron', '편견', 'Show Me the Money 5'),
    ('Hash Swan', 'Hash Brand', 'Hash Brand'),
    ('Zico', '지코', 'Show Me the Money 5'),
    ('Hash Swan', '해쉬', 'Hash Brand'),
    ('Basick', '베이식', 'Show Me the Money 5'),
    ('Flowsik', '플로우', 'Show Me the Money 5'),
    ('San E', '산이', 'Show Me the Money 5'),
    ('Nafla', 'Crew Love', 'Natural High'),
    ('Loopy', 'Press It', 'Mmk'),
    ('Owen Ovadoz', 'POEM', 'POEM'),
    ('Don Mills', 'Don Mills Is Angry 4', 'Don Mills Is Angry 4'),
    ('Verbal Jint', 'Dooms Day', 'Rap Genius No. 9'),
    ('Owen Ovadoz', '피', 'POEM'),
    ('Blase', 'Blue', ''),
    ('Nafla', 'Natural Born Killers', 'Natural High'),
    ('Loopy', 'No Loopy', 'Mmk'),
    ('Verbal Jint', '버벌', 'Rap Genius No. 9'),
    ('Paloalto', '팔로', 'Nomad'),
    ('The Quiett', '콰이엇', 'Cut'),
    ('Heize', 'Listen To Me', 'Unpretty Rapstar 2'),
    ('Gray', 'Late Night', ''),
    ('Nucksal', '180°', ''),
    ('Bobby', 'GO', 'MOBB'),
    ('Mino', 'Hit Me', 'MOBB'),
    ('Mino', 'Burning Up', 'MOBB'),
    ('Bobby', 'Wang Hola', 'MOBB'),
    ('Colde', 'Love Lessons', 'Love Lessons'),
    ('Kid Milli', 'Linguistics', 'IndiGO'),
    ('Olltii', 'Creative Control', 'Creative Control'),
    ('G2', 'Business', 'Business'),
    ('Illinit', 'Ill Street Live 2', ''),
    ('Cheetah', 'Keep It Movin', ''),
    ('Reddy', 'THINK', ''),
    ('Junggigo', "No Diggin'", ''),
    ('Gaeko', 'Pass', 'Pass'),
    ('Yoon Mirae', 'Gemini', ''),
    ('Bumkey', 'Single Life 2', 'Single Life 2'),
    ('Tiger JK', 'I Know', 'Feel gHood Muzik : The 8th Wonderland'),
    ('Tablo', 'Hood', "Fever's End Pt. 2"),
    ('Primary', 'Planetarium', ''),
    ('Elo', 'Trouble', 'Hood'),
    ('Swings', 'Growling', 'Growling'),
    ('Jinbo', 'Honey', 'Honey'),
    ('Swings', 'Remember We', 'Growing Pains'),
    ('Woo', 'We Are', ''),
    ('Cheetah', '키퍼', ''),
    ('KittiB', '노바디', ''),
    ('Jinbo', '허니', 'Honey'),
    ('Penomeco', 'OFM', ''),
    ('Mirani', 'Ticket', ''),
    ('YUMDDA', 'Tic Toc', ''),
    ('Leellamarz', 'Profile', 'To Be Continued'),
    ('Woo', 'YACHT', 'YACHT'),
    ('Dok2', 'Thug Life Part 2', 'Thug Life Part 2'),
    ('Coogie', 'Glow', ''),
    ('Dynamic Duo', 'Sign', 'Grand Carnival'),
    ('Kid Milli', '밀리', 'IndiGO'),
    ('PH-1', '피에이치', 'Good Day'),
    ('Reddy', '레디', 'Orca-Tape'),
    ('Leellamarz', '릴러', 'To Be Continued'),
    ('Mad Clown', '매드', 'Fire'),
    ('Tiger JK', '타이거', 'Feel gHood Muzik : The 8th Wonderland'),
    ('Yoon Mirae', '윤미', 'Gemini'),
    ('Junggigo', '정이', 'Want U'),
]
