# 힙플·힙플레이·전문가 평가 기준 2013년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('다이나믹듀오', 'BAAAM', 'Lucky Numbers'),
    ('Penomeco', 'COCO BOTTLE', ''),
    ('San E', 'Show Me the Money', 'Show Me the Money 2'),
    ('Basick', 'Show Me the Money', 'Show Me the Money 3'),
    ('Olltii', 'MVP', 'Show Me the Money 2'),
    ('B-Free', 'Korean Dream Team', ''),
    ('The Quiett', 'Green Light', ''),
    ('The Quiett', '11:11', '11:11'),
    ('Paloalto', 'Good Morning Seoul', ''),
    ('Paloalto', 'Sunday', ''),
    ('E-Sens', 'Black Suit', ''),
    ('E-Sens', 'New York', 'Anonymous Letters'),
    ('Owen Ovadoz', 'P', ''),
    ('Owen Ovadoz', 'We Up', ''),
    ('Deepflow', 'Good Day', ''),
    ('Don Mills', 'Zero', ''),
    ('Don Mills', 'Bang', 'Don Mills Is Angry'),
    ('Verbal Jint', 'Rap Genius No. 8 Intro', 'Rap Genius No. 8'),
    ('다이나믹듀오', '쉽게', 'Lucky Numbers'),
    ('Zion.T', 'SNUPERMAN', ''),
    ('Zion.T', '양화대교', 'Mirrorball'),
    ('빈지노', 'Profile', '11:11'),
    ('빈지노', 'Illionaire Gang', '11:11'),
    ('Mad Clown', 'Fire', ''),
    ('Mad Clown', '오빠 생각', ''),
    ('Bumkey', 'When I Wake Up', ''),
    ('Bumkey', 'Goodbye', ''),
    ('스윙스', 'Growing Pains', 'Growing Pains'),
    ('스윙스', '리챔', ''),
    ('Giriboy', 'Wake Up', ''),
    ('Giriboy', 'Lowlife', ''),
    ('Dean', '130613', ''),
    ('Dean', 'Pour Out', ''),
    ('Gray', 'In My Head', 'Call Me Gray'),
    ('Gray', 'Dream Chaser', 'Call Me Gray'),
    ('Loco', 'Take Care', ''),
    ('Loco', 'Blonote', 'Blonote'),
    ('지코', '97시험', ''),
    ('지코', 'Hurricane Venus', 'Zico on the Block 1.5'),
    ('프라이머리', 'eeee', ''),
    ('프라이머리', 'Amigo', ''),
    ('도끼', 'Good Vibes Only', 'Ruthless, The Album'),
    ('도끼', '1LLIN', 'Ruthless, The Album'),
    ('Jinbo', 'Fantasy', 'Fantasy'),
    ('Jinbo', 'Neon Pink Ocean', 'Fantasy'),
    ('Crush', 'Where Do You Wanna Go', ''),
    ('Crush', 'Beautiful', 'Crush on You'),
    ('Gaeko', '건강', 'Geon Gangs'),
    ('Gaeko', 'Geon Gangs', 'Geon Gangs'),
    ('San E', 'Bad Year', ''),
    ('Okasian', 'Check-in', 'Orca-Tape'),
    ('Okasian', "Don't Front", 'Orca-Tape'),
    ('Jerry.K', 'V', 'V'),
    ('Jerry.K', 'Ready', 'V'),
    ('Vasco', 'Exodus', 'Guerrilla Muzik Vol.3 Exodos'),
    ('Vasco', 'Guerrilla Muzik', 'Guerrilla Muzik Vol.3 Exodos'),
    ('릴리삼', 'Ballerino', ''),
    ('릴리삼', 'Wipe', 'Unplugged on the Sofa'),
    ('타이거 JK', 'Monologue', ''),
    ('Lil Boi', 'Ferris Wheel', ''),
    ('Lil Boi', 'No Feat No Problem', ''),
    ('G2', 'Online', ''),
    ('G2', 'G2', ''),
    ('Kebee', 'Call Me', ''),
    ('Junggigo', 'Going Crazy', ''),
    ('Junggigo', 'Looking Star', 'Rookie'),
    ('Outsider', 'Loner 2', 'Vol.2-Maestro'),
    ('NO:EL', 'Super Saiyan', ''),
    ('NO:EL', 'No Way', ''),
    ('Coogie', 'Coogie', ''),
    ('Hash Swan', 'Swan', ''),
    ('Changmo', 'Bad Boy', ''),
    ('C Jamm', 'Monster', ''),
    ('C Jamm', 'C Jamm', ''),
    ('Olltii', 'Turtle Ship', ''),
    ('Kid Ash', 'Kid Ash', ''),
    ('Penomeco', '코코', ''),
    ('Swings', 'Bulldozer', 'Upgrade II'),
    ('Swings', '불도저', 'Upgrade II'),
    ('Beenzino', 'Dali, Van, Picasso', '11:11'),
    ('Beenzino', '달리', '11:11'),
    ('Jay Park', 'Joah', 'Evolution'),
    ('Jay Park', '좋아', 'Evolution'),
    ('Simon Dominic', 'Cheer Up to You', 'Consolation'),
    ('Simon Dominic', '위로해줄게', 'Consolation'),
    ('Epik High', 'Happen Ending', 'Shoebox'),
    ('Epik High', '헤픈엔딩', 'Shoebox'),
    ('Dynamic Duo', 'Return Of The Kings', 'Lucky Numbers'),
    ('Dynamic Duo', '리턴 오브 더 킹', 'Lucky Numbers'),
    ('Primary', 'eeee (2013 Ver.)', ''),
    ('Primary', '프라이머리', ''),
    ('Flowsik', 'We On', ''),
    ('Flowsik', '플로우식', ''),
    ('Jessi', 'Unpretty Dreams', ''),
    ('Jessi', '제시', ''),
    ('KittiB', 'Nobody Knows', ''),
    ('KittiB', '키티비', ''),
    ('Colde', 'Your Dog Loves You', ''),
    ('Colde', '콜드', ''),
    ('Louie', 'Picture', ''),
]
