# 힙플·힙플레이·전문가 평가 기준 2019년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Epik High', 'Eternal Sunshine', 'Sleepless in __________'),
    ('Penomeco', 'Shy (수줍)', 'Shy'),
    ('Penomeco', 'Lovers (러버스)', 'Shy'),
    ('Mudd the student', 'IndiGO (인디GO)', 'Show Me the Money 8'),
    ('Mirani', 'VANS', 'Show Me the Money 8'),
    ('TOIL', 'Panorama (파노라마)', 'Show Me the Money 8'),
    ('Blase', 'Tic Tac', 'Show Me the Money 8'),
    ('Blase', 'Fill It', 'Show Me the Money 8'),
    ('Owen Ovadoz', '119 REMIX (119 리믹스)', 'Show Me the Money 8'),
    ('Owen Ovadoz', '119 REMIX', 'Show Me the Money 8'),
    ('Lil Boi', 'VVS', 'Show Me the Money 8'),
    ('Lil Boi', 'On My Way (온 마이 웨이)', 'Show Me the Money 8'),
    ('Mudd the student', 'MEMORIES (메모리즈)', 'Show Me the Money 8'),
    ('Mirani', 'VVS', 'Show Me the Money 8'),
    ('Koonta', 'VVS', 'Show Me the Money 8'),
    ('Koonta', 'Unbreakable (언브레이커블)', 'Show Me the Money 8'),
    ('Sokodomo', 'coffee', 'Show Me the Money 8'),
    ('Sokodomo', 'Gamble (겜블)', 'Show Me the Money 8'),
    ('Giriboy', 'on my way', 'Show Me the Money 8'),
    ('PH-1', 'RUBBER (러버)', 'Show Me the Money 8'),
    ('Leellamarz', 'Barcode', 'Show Me the Money 8'),
    ('Woodie Gochild', 'WaRRior (워리어)', 'Show Me the Money 8'),
    ('Woodie Gochild', 'Money Wave (머니 웨이브)', 'Show Me the Money 8'),
    ('Lil Moshpit', 'Lil Moshpit (릴 모스hpit)', 'Show Me the Money 8'),
    ('Lil Moshpit', 'VVS', 'Show Me the Money 8'),
    ('YunB', 'VVS', 'Show Me the Money 8'),
    ('YunB', 'Piano (피아노)', 'Show Me the Money 8'),
    ('Swings', 'IndiGO', 'Show Me the Money 8'),
    ('Flowsik', 'Unbreakable (언브레이커블)', 'Show Me the Money 8'),
    ('Nafla', 'Swervin (스wervin)', 'C.R.E.A.M'),
    ('Nafla', 'cashrules (캐시룰즈)', 'C.R.E.A.M'),
    ('Paloalto', 'Mood Indigo (무드 인디고)', 'Mood Indigo'),
    ('Paloalto', 'Nomad (노마드)', 'Nomad'),
    ('Epik High', '로스트 원 (Lost One)', 'Sleepless in __________'),
    ('Zico', 'Summer Hate (여름 Hate)', 'Human'),
    ('Zico', 'Balloon (풍선)', 'Human'),
    ('Giriboy', 'SEOUL CITY G', 'heat'),
    ('Changmo', 'Thrift Shop (쓰리프트 샵)', 'Ghetto Kids'),
    ('Changmo', 'Sufferer', 'Boyhood'),
    ('Beenzino', '24:26', '24:26'),
    ('Beenzino', 'Mozart (모차르트)', '24:26'),
    ('Dean', "howlin' 404", "howlin' 404"),
    ('Dean', 'DIE 4 YOU (다이 포 유)', "howlin' 404"),
    ('Crush', 'NAPPA (낮잠)', 'NAPPA'),
    ('Crush', 'Lay Your Head on Me', 'NAPPA'),
    ('Heize', "우리 헤어지게 될 마음이 (We Don't Talk Together)", 'She Drive'),
    ('Heize', 'She Drive (쉬 드라이브)', 'She Drive'),
    ('Loco', 'OFFICIAL (오피셜)', 'OFFICIAL'),
    ('Loco', 'Thinking of You', 'OFFICIAL'),
    ('Gray', 'Remedy (레미디)', 'Remedy'),
    ('Gray', 'Comfortable (편해)', 'Remedy'),
    ('Sik-K', 'Wet', 'MAKE OUT'),
    ('Sik-K', 'Out of Ink', 'MAKE OUT'),
    ('Kid Milli', 'BOON (분)', 'BEANie'),
    ('Kid Milli', 'WHY TRIP (와이 트립)', 'BEANie'),
    ('Coogie', 'Save the Day (세이브 더 데이)', 'Save the Day'),
    ('Coogie', 'Alone (얼론)', 'Save the Day'),
    ('PH-1', "Cupid's Arrow (큐피드의 화살)", 'Good Day'),
    ('Ash Island', 'Floating', 'ISLAND'),
    ('Ash Island', 'ISLAND', 'ISLAND'),
    ('HAON', 'HAON', 'ISLAND'),
    ('HAON', 'Swervin', 'ISLAND'),
    ('Leellamarz', '3AM in Seoul (3AM in 서울)', 'To Be Continued'),
    ('Swings', 'The King (더 킹)', 'Growing Pains 2'),
    ('Jessi', 'Who Dat B (후 댓 B)', 'Who Dat B'),
    ('Jessi', 'Diamond (다이아몬드)', 'Who Dat B'),
    ('Jay Park', 'These Days (요즘)', 'The Season: The Blue Bird'),
    ('NO:EL', 'Rain Drop 3 (비 3)', 'Rain Drop 3'),
    ('NO:EL', 'Rain Drop 4 (비 4)', 'Rain Drop 4'),
    ('YUMDDA', 'Shake (쉐이크)', "I'm Good"),
    ('YUMDDA', 'Diamond (다이아몬드)', "I'm Good"),
    ('Dynamic Duo', 'A DynamicAffair', 'A DynamicAffair'),
    ('Dynamic Duo', '에이 다이나믹 어페어', 'A DynamicAffair'),
    ('Mino', 'Do It (두 잇)', 'Do It'),
    ('Bobby', 'One Shot (원샷)', 'One Shot'),
    ('Code Kunst', 'ARCHIVE (아카이브)', 'Code Kunst Archive Pack 02'),
    ('Code Kunst', 'Jungle', 'Code Kunst Archive Pack 02'),
    ('Primary', 'eee (이)', '2'),
    ('Primary', '2', '2'),
    ('Outsider', 'Vol.2-Maestro 3', 'Vol.2-Maestro 3'),
    ('Outsider', '볼륨2 마에스트로 3', 'Vol.2-Maestro 3'),
    ('D.Ark', 'Genius (Remix)', 'Genius'),
    ('D.Ark', '천재 (Remix)', 'Genius'),
    ('Punchnello', 'Winter Blossom (겨울꽃)', 'Winter Blossom'),
    ('Colde', 'In Your Eyes (인 유어 아이즈)', 'In Your Eyes'),
    ('Gaeko', 'Rosetta (로제타)', 'Rosetta'),
    ('Tablo', 'Birthday (생일)', 'Birthday'),
    ('Kid Ash', 'Orca (오르카)', 'Orca-Tape'),
    ('Kid Ash', 'Orca-Tape', 'Orca-Tape'),
    ('Elo', '타투 온 마이 하트', 'Tattoo On My Heart'),
    ('Nucksal', '확실히 (For sure)', ''),
    ('Zion.T', 'No Make Up (feat. Wonstein)', 'No Make Up'),
    ('DPR LIVE', 'Coming To You Live', 'Coming to You Live'),
    ('GroovyRoom', 'Thinkin About You', 'Thinkin About You'),
    ('GroovyRoom', 'Sunny', 'Thinkin About You'),
    ('BIG Naughty', 'Relationship', 'Relationship'),
    ('Rohann', 'Problem', 'Problem'),
    ('Thama', 'Long Time No See', 'Long Time No See'),
    ('Jvcki Wai', 'Mood', 'Exposure'),
    ('Woo Won Jae', 'We Are', 'We Are'),
]
