# 힙플·힙플레이·전문가 평가 기준 2010년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('에픽하이', 'RUN', 'Epilogue'),
    ('다이나믹듀오', '없네', 'Band of Dynamic Brothers'),
    ('릴리삼', '살아가는 중', 'Hexagonal'),
    ('에픽하이', 'Up', 'Epilogue'),
    ('슈프림팀', '땡땡땡', 'Supreme Team Guide To Absolute Respect'),
    ('사이먼 디', '청담동 Madonna', 'Simon Dominic Part 2'),
    ('프라이머리', '2 Weeks', 'Primary And The Messengers LP'),
    ('버벌진트', 'Ready To Die', 'Going Down Under'),
    ('지코', 'Tough Cookie', 'O.M.M'),
    ('The Quiett', 'Can You?', 'Can You?'),
    ('Deepflow', 'Come Back Home', 'Flow the Life'),
    ('빈지노', 'Retro Love', '24:26'),
    ('타블로', 'Bad', 'Tomorrow'),
    ('도끼', 'Thug Life', 'Thug Life'),
    ('San E', 'LoveSick', 'Ready for Showtime'),
    ('허클베리 P', 'Mantra', 'Mantra'),
    ('Paloalto', 'Imagination', 'Imagination'),
    ('Don Mills', 'Don Mills Is Angry', 'Don Mills Is Angry'),
    ('E-Sens', 'Poison', ''),
    ('배치기', '상어의 이야기', "Shark's Tale"),
    ('아웃사이더', '외투', 'Vol.2-Maestro'),
    ('Deepflow', '그날', 'Flow the Life'),
    ('허클베리 P', '만트라', 'Mantra'),
    ('E-Sens', '감기', ''),
    ('The Quiett', 'Money and the Power', 'Can You?'),
    ('Don Mills', '분노', 'Don Mills Is Angry'),
    ('Paloalto', '탑 락 스타', 'The Big Picture'),
    ('B-Free', 'Best Seller', 'Best Seller'),
    ('B-Free', '베스트셀러', 'Best Seller'),
    ('다이나믹듀오', '인터뷰', 'Band of Dynamic Brothers'),
    ('릴리삼', '헤어지지 못하는 여자, 떠나가지 못하는 남자', 'Hexagonal'),
    ('타이거 JK', '몬스터', 'Feel gHood Muzik : The 8th Wonderland'),
    ('스윙스', '내일이면', 'Upgrade'),
    ('프라이머리', '오랜만이야', 'Primary And The Messengers LP'),
    ('사이먼 디', '180도 Turn', 'Simon Dominic Part 2'),
    ('타블로', 'Tomorrow', 'Tomorrow'),
    ('버벌진트', 'Desperado', 'Going Down Under'),
    ('슈프림팀', 'Respect', 'Supreme Team Guide To Absolute Respect'),
    ('빈지노', 'Starlight', '24:26'),
    ('도끼', '88', 'Thug Life'),
    ('스윙스', 'Upgrade', 'Upgrade'),
    ('지코', 'I Love U', 'O.M.M'),
    ('San E', 'Ready for Showtime', 'Ready for Showtime'),
    ('매드클라own', '허특사랑', 'Heoteoge Sarang'),
    ('매드클라own', 'Fire', 'Heoteoge Sarang'),
    ('아웃사이더', 'Maestro', 'Vol.2-Maestro'),
    ('타이거 JK', 'Push It', 'Feel gHood Muzik : The 8th Wonderland'),
    ('윤미래', 'Get It In', ''),
    ('윤미래', 'Black Happiness', ''),
    ('배치기', 'Time to Love', "Shark's Tale"),
    ('개코', 'Hard Rock Techno', 'Hard Rock Techno'),
    ('개코', 'Wherever', 'Hard Rock Techno'),
    ('Kebee', 'On Our Own', 'On Our Own'),
    ('Kebee', 'Rhythm and Poetry', 'On Our Own'),
    ('Vasco', 'The Vasco', 'The Vasco'),
    ('Vasco', 'Revolution', 'The Vasco'),
    ('MC Meta', 'On My Own', 'On Our Own'),
    ('MC Meta', '혼자서', 'On Our Own'),
    ('Geologic', 'Blaze', 'Blaze'),
    ('Geologic', '불꽃놀이', 'Blaze'),
    ('Mighty Mouth', 'San', 'San'),
    ('Mighty Mouth', '사랑해', 'San'),
    ('Skull', "I'm Your Man", "I'm Your Man"),
    ('Skull', '사랑해', "I'm Your Man"),
    ('Sean2Slow', 'Slow Down', 'Slow Down'),
    ('Sean2Slow', '새로운', 'Slow Down'),
    ('Myun Do One', 'Bulldozer', 'Bulldozer'),
    ('Myun Do One', '불도저', 'Bulldozer'),
    ('Phantom', 'Bubble Love', "Phantom's Opera"),
    ('Phantom', '몸매가 좋아', "Phantom's Opera"),
    ('MellowD', 'MellowD', 'MellowD'),
    ('MellowD', '멜로디', 'MellowD'),
    ('Reddy', 'Commitment', 'Commitment'),
    ('Reddy', '약속', 'Commitment'),
    ('Kid Ash', 'Orca', 'Orca'),
    ('Kid Ash', '오르카', 'Orca'),
    ('Olltii', 'TTM', 'TTM'),
    ('Olltii', '티티엠', 'TTM'),
    ('Illinit', 'Real Talk Live', 'Real Talk Live'),
    ('Illinit', '리얼톡', 'Real Talk Live'),
    ('Jerry.K', 'Thorn Crown', 'Thorn Crown'),
    ('Jerry.K', '가시관', 'Thorn Crown'),
    ('Basick', 'Nice Day', 'The Classic'),
    ('Basick', '나이스 데이', 'The Classic'),
    ("J'Kyun", 'Fly Away', 'Fly Away'),
    ("J'Kyun", '사랑해', 'Fly Away'),
    ('Rhymer', 'Brand New Day', 'Rhymer Trax Vol.1'),
    ('Rhymer', '브랜드 뉴 데이', 'Rhymer Trax Vol.1'),
    ('Jinbo', '555', '555'),
    ('Jinbo', '콜 미', '555'),
    ('Double K', 'Fly High', 'Fly High'),
    ('Double K', '플라이 하이', 'Fly High'),
    ('Pe2ny', 'Pe2ny Maker', 'Pe2ny Maker'),
    ('Pe2ny', '페니 메이커', 'Pe2ny Maker'),
    ('TBNY', 'Million', 'Million'),
    ('TBNY', '밀리언', 'Million'),
    ('Stuck B', 'Stuck B', 'Stuck B'),
    ('Stuck B', '스턱비', 'Stuck B'),
    ('Crown J', 'My Friend', 'My Friend'),
    ('Crown J', '마이 프렌드', 'My Friend'),
]
