# 힙플·힙플레이·전문가 평가 기준 2012년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('G-Dragon', 'One Of A Kind', 'One of a Kind'),
    ('버벌진트', 'Mainstream', 'Mainstream'),
    ('Deepflow', 'Flow the Life 3', 'Flow the Life 3'),
    ('허클베리 P', 'Mantra 3', 'Mantra 3'),
    ('E-Sens', 'Anonymous Letters', 'Anonymous Letters'),
    ('E-Sens', 'The Song of the Sword', 'Anonymous Letters'),
    ('The Quiett', 'Q Train', 'Q Train'),
    ('The Quiett', 'Guilty Conscience', 'Q Train'),
    ('Paloalto', 'Shining Diamond', 'Shining Diamond'),
    ('Paloalto', 'Good Morning', 'Shining Diamond'),
    ('Don Mills', 'Don Mills Is Angry 3', 'Don Mills Is Angry 3'),
    ('Loopy', 'Mmk', ''),
    ('Loopy', '루피', ''),
    ('Nafla', 'Mood Indigo', ''),
    ('Nafla', '나플라', ''),
    ('Verbal Jint', '비 오는 날', 'Mainstream'),
    ('G-Dragon', '그 XX', 'One of a Kind'),
    ('에픽하이', '99', '99'),
    ('에픽하이', '춥다', '99'),
    ('다이나믹듀오', '살아있네', 'A Giant Step'),
    ('다이나믹듀오', '은행', 'A Giant Step'),
    ('Jay Park', 'New Breed', 'New Breed'),
    ('Jay Park', 'Girlfriend', 'New Breed'),
    ('빈지노', '247', '247'),
    ('빈지노', 'Perfect Lover', '247'),
    ('버벌진트', 'No Scope', 'Mainstream'),
    ('사이먼 디', '위로', 'Consolation'),
    ('사이먼 디', 'Consolation', 'Consolation'),
    ('Zion.T', 'I Need U', 'Zion.T Special: ZIP'),
    ('Zion.T', '병', 'Zion.T Special: ZIP'),
    ('Crush', '퐁퐁', 'Crush on You'),
    ('Crush', 'Hug Me', 'Crush on You'),
    ('프라이머리', 'JohnLegend', 'Primary and the Messengers LP 2'),
    ('프라이머리', 'Roller Coaster', 'Primary and the Messengers LP 2'),
    ('Gaeko', 'Redingray', 'Redingray'),
    ('Gaeko', 'West Coast', 'Redingray'),
    ('지코', 'Battle Royale', 'Zico on the Block 1.5'),
    ('지코', 'Human', 'Zico on the Block 1.5'),
    ('도끼', 'Rich', 'Dok2ocracy'),
    ('도끼', 'We Online', 'Dok2ocracy'),
    ('Mad Clown', '감자', 'Potato'),
    ('Mad Clown', 'Maximum', 'Potato'),
    ('윤미래', 'Touch Love', ''),
    ('타블로', 'Baddest Female', "Fever's End Pt. 1"),
    ('타블로', 'Tomorrow Is Coming', "Fever's End Pt. 1"),
    ('Jinbo', 'Deeper', '555'),
    ('Jinbo', 'O.S.T.', '555'),
    ('스윙스', '다 줄게', ''),
    ('스윙스', '잘 자', ''),
    ('Junggigo', 'Rookie', 'Rookie'),
    ('Junggigo', 'Because', 'Rookie'),
    ('Beenzino', 'Slow Down', '247'),
    ('Beenzino', 'Hot Spring', '247'),
    ('Simon Dominic', 'Simplize', 'Consolation'),
    ('Simon Dominic', 'I2', 'Consolation'),
    ('Illinit', '릴 스트릿', 'Illmatic'),
    ('Sean2Slow', 'Slow Jam', 'Slow Jam'),
    ('Sean2Slow', '슬로우 잼', 'Slow Jam'),
    ('Skull', 'Love U', 'Skull & Haha 2'),
    ('Skull', '러브 유', 'Skull & Haha 2'),
    ('Mighty Mouth', 'Good Good Feeling', 'Mighty Style'),
    ('Mighty Mouth', '굿굿필링', 'Mighty Style'),
    ("J'Kyun", 'Ready to Fly', 'Ready to Fly'),
    ("J'Kyun", '플라이', 'Ready to Fly'),
    ('면도원', 'Myun Do One Is Back', 'Myun Do One Is Back'),
    ('면도원', '면도원', 'Myun Do One Is Back'),
    ('MC Meta', 'Icarus', 'The Blue Printz'),
    ('MC Meta', '이카루스', 'The Blue Printz'),
    ('Geologic', 'Hero', 'Hero'),
    ('Geologic', '히어로', 'Hero'),
    ('Pe2ny', '페투니', 'Pe2ny Maker'),
    ('L.E.O.', 'Show Must Go On', 'Show Must Go On'),
    ('L.E.O.', '쇼 머스트 고', 'Show Must Go On'),
    ('Kid Milli', 'A Swaggy Song Called Kidd', ''),
    ('Kid Milli', '키드밀리', ''),
    ('PH-1', "PH1's Day Off", ''),
    ('PH-1', '피에이치원', ''),
    ('Coogie', 'PLAY', ''),
    ('Coogie', '쿠기', ''),
    ('Hash Swan', 'Hash X Kash', ''),
    ('Hash Swan', '해시 스완', ''),
    ('Changmo', 'Rebels', ''),
    ('Changmo', '창모', ''),
    ('Olltii', '올티', 'TTM'),
    ('Kid Ash', '키드애쉬', 'Orca'),
    ('Epik High', "It's Cold", '99'),
    ('Epik High', '춥다 (Remix)', '99'),
    ('Dynamic Duo', 'Go Back', 'A Giant Step'),
    ('Dynamic Duo', '돌아가', 'A Giant Step'),
    ('Leessang', 'Ballerino', ''),
    ('Leessang', '발레리노', ''),
    ('Swings', '마녀사냥', 'Upgrade II'),
    ('Swings', 'Heavy Smoker', 'Upgrade II'),
    ('Zico', 'No Limit', 'Zico on the Block 1.5'),
    ('Zico', '노 리미트', 'Zico on the Block 1.5'),
    ('Primary', 'Mission', 'Primary and the Messengers LP 2'),
    ('Primary', '미션', 'Primary and the Messengers LP 2'),
    ('Loco', 'Thinking About You', 'Blonote'),
    ('Loco', 'Thinking', 'Blonote'),
    ('Gray', 'Stay the Night', 'Gray Season 1'),
]
