# 힙플·힙플레이·전문가 평가 기준 2017년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Nafla', 'MVP', '[ Album ]'),
    ('Nafla', 'Jazz Freestyle', '[ Album ]'),
    ('Loopy', 'Portrait Mode', '[ Album ]'),
    ('Loopy', 'Save', '[ Album ]'),
    ('Kid Milli', 'Cappuccino', ''),
    ('Kid Milli', 'Maiden Voyage', 'Maiden Voyage'),
    ('BewhY', 'Cult of Curiosity', 'Cult of Curiosity'),
    ('Hash Swan', 'Hash Brand 2', 'Hash Brand 2'),
    ('PH-1', 'YIN YANG', 'YIN YANG'),
    ('PH-1', 'Platonic', 'YIN YANG'),
    ('Dean', 'instagram', ''),
    ('Giriboy', '914', '914'),
    ('Changmo', 'Meteor', 'Boyhood'),
    ('Changmo', 'Boyhood', 'Boyhood'),
    ('The Quiett', 'Glow', ''),
    ('Epik High', 'Lesson 1', 'Lesson 0'),
    ('Epik High', 'Lesson 2', 'Lesson 0'),
    ('Penomeco', 'Famous', ''),
    ('Punchnello', 'Everyday', 'Everyday'),
    ('Simon Dominic', 'DAx4', 'DAx4'),
    ('G-Dragon', '무제', '권지용'),
    ('Zico', 'Artist', 'Television'),
    ('Gray', "I'm Fine", 'Hyena on the Keyboard'),
    ('Beenzino', 'Damnato', 'Damnato'),
    ('Sik-K', 'YACHT', 'YACHT'),
    ('Woo', '위 아', 'YACHT'),
    ('Jvcki Wai', 'Neo Eve', 'Exposure'),
    ('Ash Island', 'Howling', 'Ash Island'),
    ('TOIL', 'Money', '1989'),
    ('D.Ark', 'Genius', 'Show Me the Money 777'),
    ('Heize', '비도 오고 그래서', '///'),
    ('Crush', 'None', ''),
    ('Loco', 'Too Much', 'Bleached'),
    ('Jay Park', 'V', 'The Season: The Blue Bird'),
    ('Zion.T', 'Snow', ''),
    ('BTS', 'DNA', "LOVE YOURSELF 承 'Her'"),
    ('BTS', 'MIC Drop', "LOVE YOURSELF 承 'Her'"),
    ('BewhY', '호기심', 'Cult of Curiosity'),
    ('Giriboy', 'Traffic Control', '914'),
    ('Jvcki Wai', '도넛', 'Exposure'),
    ('Ash Island', '하울링', 'Ash Island'),
    ('Deepflow', '플로우', 'Flow the Life 4'),
    ('Hash Swan', '브랜드2', 'Hash Brand 2'),
    ('D.Ark', '천재', 'Show Me the Money 777'),
    ('Basick', '베이', 'Show Me the Money 777'),
    ('Flowsik', '플로', 'Show Me the Money 777'),
    ('San E', '몸', 'Show Me the Money 777'),
    ('E-Sens', '이상형', 'The Anecdote'),
    ('Blase', '블루', 'Blue'),
    ('TOIL', '일구팔구', '1989'),
    ('G-Dragon', 'Untitled, 2014', '권지용'),
    ('Loco', 'Summer Go Loco', 'Summer Go Loco'),
    ('Heize', 'Jenga', 'Jenga'),
    ('Crush', 'Skip', ''),
    ('Jay Park', 'All The Way Up', ''),
    ('Zion.T', 'Sorry', 'OO'),
    ('Beenzino', 'Holiday', 'Damnato'),
    ('Sik-K', 'CRRWD', 'YACHT'),
    ('Zico', 'Television', 'Television'),
    ('Gray', 'Upside Down', ''),
    ('Primary', 'Morning Glory', ''),
    ('Elo', 'Tattoo On My Heart', 'Tattoo On My Heart'),
    ('Swings', 'Remedy', 'Remedy'),
    ('Dok2', 'All I Know Is', 'Thug Life Part 2'),
    ('Bobby', 'Y.G.G', 'Y.G.G'),
    ('Coogie', 'PICK UP THE PHONE', ''),
    ('Coogie', 'Money & Fame', ''),
    ('NO:EL', 'Rain Drop', 'Rain Drop'),
    ('Woo', '오늘밤', 'YACHT'),
    ('NO:EL', '레인', 'Rain Drop'),
    ('Mino', 'Fiancé', 'XX'),
    ('Mino', 'Trigger', 'XX'),
    ('Swings', 'Brand New Day', 'Remedy'),
    ('Leessang', '리듬', ''),
    ('Tablo', "Fever's End", "Fever's End Pt. 2"),
    ('Woodie Gochild', 'GOchild', '#GOchild'),
    ('Haon', 'Blue', 'Penumbra'),
    ('Punchnello', '매일', 'Everyday'),
    ('Simon Dominic', '포', 'DAx4'),
    ('Bobby', '와이지지', 'Y.G.G'),
    ('Dynamic Duo', '하이파이브', ''),
    ('Primary', '행복', 'Morning Glory'),
    ('Tablo', '후드', "Fever's End Pt. 2"),
    ('Dok2', '올 아이 노', 'Thug Life Part 2'),
    ('Penomeco', '유명', ''),
    ('Leellamarz', '계속', 'To Be Continued'),
    ('Mirani', '표', 'Ticket'),
    ('YUMDDA', '틱톡', "I'm Good"),
    ('Woodie Gochild', '무드', '#GOchild'),
    ('Haon', '페넘', 'Penumbra'),
    ('Gaeko', '패스', 'Pass'),
    ('Elo', '문신', 'Tattoo On My Heart'),
    ('Tiger JK', '타JK', 'Feel gHood Muzik : The 8th Wonderland'),
    ('Yoon Mirae', '쌍둥', 'Gemini'),
    ('Junggigo', '원해', 'Want U'),
    ('Bumkey', '범', 'Single Life 2'),
    ('Okasian', '셀', 'Celebration'),
    ('Illinit', '일', 'Ill Street Live 2'),
    ('Vasco', '바', 'The Vasco'),
    ('Hwang Kwanghee', 'Yellow Boots', '프로듀스 101 Season 2'),
]
