# 힙플·힙플레이·전문가 평가 기준 2018년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Penomeco', 'Work', 'Work'),
    ('Nafla', '무엇 (What)', 'Show Me the Money 777'),
    ('Loopy', 'No Loopy (노 루피)', 'Show Me the Money 777'),
    ('Deepflow', '집으로 (Come Back Home)', 'Flow the Life 4'),
    ('Jessi', 'Gucci', 'Show Me the Money 777'),
    ('Jessi', '어떤X', 'Show Me the Money 777'),
    ('D.Ark', 'Undercover', 'Show Me the Money 777'),
    ('D.Ark', '천재 (Genius)', 'Show Me the Money 777'),
    ('Punchnello', 'If You (너라면)', 'Show Me the Money 777'),
    ('Flowsik', 'We On (위 온)', 'Show Me the Money 777'),
    ('Flowsik', '반박불가 (Unbreakable)', 'Show Me the Money 777'),
    ('Reddy', 'THINK (띵)', 'Show Me the Money 777'),
    ('Reddy', '잘 (Well)', 'Show Me the Money 777'),
    ('KittiB', '누구 없소 (Nobody)', 'Show Me the Money 777'),
    ('Hash Swan', 'Hash Brand (해시 브랜드)', 'Hash Brand'),
    ('Hash Swan', 'Retro Love (레트로 러브)', 'Hash Brand'),
    ('BewhY', '까불지마', 'Cult of Curiosity'),
    ('BewhY', '1990', 'Cult of Curiosity'),
    ('TOIL', '1989', '1989'),
    ('Loopy', 'King Loopy', 'King Loopy'),
    ('Blase', 'Blue (블루)', ''),
    ('Blase', 'Love Me', 'Passionfruit'),
    ('Don Mills', '돈밀리 4', 'Don Mills Is Angry 4'),
    ('Verbal Jint', '랩 genius no.9', 'Rap Genius No. 9'),
    ('Paloalto', 'Shangri-La (상그릴라)', 'Shangri-La'),
    ('Owen Ovadoz', 'Drama (드라마)', 'Drama'),
    ('TOIL', 'Rollin', '1989'),
    ('iKON', '사랑을 했다', 'NEW KIDS : CONTINUE'),
    ('iKON', '굿바이 로드 (GOODBYE ROAD)', 'NEW KIDS : CONTINUE'),
    ('Zico', '어땠을까', '어땠을까'),
    ('Zico', 'SoulMate (소울메이트)', 'SoulMate'),
    ('Crush', '우아', 'From Midnight to Sunrise'),
    ('Heize', '내 마음을 볼 수 있나요', 'HAPPEN'),
    ('Heize', '내 마을', 'HAPPEN'),
    ('Mino', '아낙 (Fiancé)', 'XX'),
    ('Mino', '송곳니', 'XX'),
    ('Loco', '주저해 (Some)', 'Hero'),
    ('Loco', '시 (Poem)', 'Hero'),
    ('Simon Dominic', 'ART OF PARTYING', 'NO OPEN FLAME'),
    ('Simon Dominic', 'NO OPEN FLAME', 'NO OPEN FLAME'),
    ('Kid Milli', 'Yellow (옐로우)', 'Maiden Voyage'),
    ('Kid Milli', 'SIT', 'BEANie'),
    ('PH-1', 'Homebody (홈바디)', 'YIN YANG'),
    ('HAON', 'Travel (트래블)', 'Penumbra'),
    ('HAON', 'Blue (블루)', 'Penumbra'),
    ('Coogie', 'Wifey (와이피)', 'Emo #1'),
    ('Coogie', 'GPS', 'Emo #1'),
    ('Giriboy', 'Engineering (엔지니어링)', 'Engineering'),
    ('Giriboy', 'PlanetariuM', 'Engineering'),
    ('Swings', 'Upgrade III', 'Upgrade III'),
    ('Swings', 'Growing Pains 2', 'Growing Pains 2'),
    ('Changmo', 'Meteor (메테오)', 'Boyhood'),
    ('Dean', 'DMT', ''),
    ('Sik-K', 'FL1X', 'FL1X'),
    ('Sik-K', 'NEONBEAM', 'FL1X'),
    ('Ash Island', 'Malibu', 'Ash Island'),
    ('Leellamarz', 'Profile (프로필)', 'To Be Continued'),
    ('Leellamarz', 'Don`t Call Me', 'To Be Continued'),
    ('Woodie Gochild', 'Mood Swings', '#GOchild'),
    ('Jvcki Wai', 'Doughnet', 'Exposure'),
    ('Mirani', 'Ticket (티켓)', 'Ticket'),
    ('Mirani', 'Bayer Dynamic', 'Ticket'),
    ('YUMDDA', 'Tic Toc (틱톡)', "I'm Good"),
    ('YUMDDA', "I'm Good (아임 굿)", "I'm Good"),
    ('Tablo', 'Fantasy (환상)', 'Drill Presents: Tablo x Fantasy'),
    ('Tablo', 'Drill Presents', 'Drill Presents: Tablo x Fantasy'),
    ('Jay Park', 'Likes (좋아)', ''),
    ('Jay Park', "Can't Be Saved", ''),
    ('Gray', 'Tik Tak Tok (틱택톡)', ''),
    ('Gray', 'Late Night (레이트 나이트)', 'Gray Season 2.5'),
    ('Gaeko', 'Gajah (가자)', 'Gajah'),
    ('Sokodomo', 'Merry Go Round (메리고라운드)', 'Merry Go Round'),
    ('Sokodomo', 'IF I', 'Merry Go Round'),
    ('Lil Moshpit', 'MOSHPIT (모스hpit)', 'MOSHPIT'),
    ('Lil Moshpit', 'BITE', 'MOSHPIT'),
    ('NO:EL', 'Rain Drop (비)', 'Rain Drop'),
    ('NO:EL', 'Rain Drop 2 (비 2)', 'Rain Drop 2'),
    ('San E', 'a SONG of ICE and FIRE', 'a SONG of ICE and FIRE'),
    ('San E', '얼음과 불의 노래', 'a SONG of ICE and FIRE'),
    ('C Jamm', 'Monster (몬스터)', ''),
    ('C Jamm', 'RED', ''),
    ('Primary', 'Morning Glory (모닝글로리)', ''),
    ('Primary', 'Planetarium (플라네타리움)', ''),
    ('E Sens', 'Mona Lisa', 'Mona Lisa'),
    ('GroovyRoom', 'Champion', 'Champion'),
    ('DPR LIVE', 'Jasmine', 'Jasmine'),
    ('DPR LIVE', 'Martini Blue', 'Martini Blue'),
    ('Zion.T', 'MMM', 'Repetition'),
    ('Beenzino', 'January', ''),
    ('MoonMoon', 'Tourist', 'Tourist'),
    ('BIG Naughty', 'Singapore', 'Singapore'),
    ('Bobby', 'U MAD', 'THE MADMAN'),
    ('Thama', 'In My Room', 'In My Room'),
    ('Dean', 'I Think U', ''),
    ('Hanhae', 'Domesticated Mode', '135'),
    ('Penomeco', 'Shy', 'Work'),
    ('GroovyRoom', 'Wavy', 'Champion'),
    ('Bobby', 'Falling In Love', 'THE MADMAN'),
    ('Ash Island', 'Limousine Vision', 'Ash Island'),
    ('Woodie Gochild', 'Dirtbag', '#GOchild'),
]
