# 힙플·힙플레이·전문가 평가 기준 2011년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Deepflow', 'Flow the Life 2', 'Flow the Life 2'),
    ('도끼', 'Thug Life Part 2', 'Thug Life Part 2'),
    ('배치기', "Shark's Tale Pt.2", "Shark's Tale"),
    ('Deepflow', 'Come Back Home Pt.2', 'Flow the Life 2'),
    ('허클베리 P', 'Woofer', 'Mantra 2'),
    ('E-Sens', 'The New One', ''),
    ('The Quiett', 'Freeze', 'Can You?'),
    ('Don Mills', 'Go Away', 'Don Mills Is Angry 2'),
    ('Paloalto', 'Nomad', 'Nomad'),
    ('Verbal Jint', 'Walking in the Rain', 'Rap Genius No. 7'),
    ('Verbal Jint', 'Rap Genius No. 7 Intro', 'Rap Genius No. 7'),
    ('B-Free', 'Hot Summer', 'Hot Summer'),
    ('B-Free', '핫 썸머', 'Hot Summer'),
    ('릴리삼', '서울시', 'Unplugged on the Sofa'),
    ('다이나믹듀오', '죽일놈', 'Band of Dynamic Brothers'),
    ('빈지노', '나이키 SHOES', 'City Life'),
    ('사이먼 디', 'Give It To Me', 'Simon Dominic Part 2'),
    ('버벌진트', 'Good Morning', 'Rap Genius No. 7'),
    ('스윙스', '마녀사냥', 'Upgrade II'),
    ('지코', 'See my Rap', 'Zico on the Block'),
    ('Jay Park', '몸매', 'Take a Deeper Look'),
    ('도끼', "It's All Good", 'Thug Life Part 2'),
    ('프라이머리', 'Johnny', 'Primary And The Messengers LP'),
    ('San E', '내가 아는 사람의 이야기', 'Ready for Showtime'),
    ('릴리삼', '비', 'Unplugged on the Sofa'),
    ('빈지노', 'City Life', 'City Life'),
    ('버벌진트', 'You Deserve Better', 'Rap Genius No. 7'),
    ('스윙스', 'Heavy Smoker', 'Upgrade II'),
    ('지코', 'Tick Tock', 'Zico on the Block'),
    ('Jay Park', 'Abandoned', 'Take a Deeper Look'),
    ('프라이머리', 'Question Mark', 'Primary And The Messengers LP'),
    ('사이먼 디', 'Latte', 'Simon Dominic Part 2'),
    ('다이나믹듀오', 'Animal', 'Band of Dynamic Brothers'),
    ('팬텀', 'Bubble Love', 'Phantom City'),
    ('타이거 JK', 'Payback', 'Feel gHood Muzik : The 8th Wonderland'),
    ('윤미래', 'Always', ''),
    ('매드클라own', 'The Quiett Smiles', 'Heoteoge Sarang'),
    ('Geologic', 'Geologic', 'Geologic'),
    ('MellowD', 'On My Way', 'On My Way'),
    ('Kebee', 'On Our Own Pt.2', 'On Our Own'),
    ('면도원', 'Bulldozer', 'Myun Do One Is Back'),
    ('Illinit', 'Ill Street', 'Illmatic'),
    ('Sean2Slow', 'Slow Jam Pt.2', 'Slow Jam'),
    ('Jinbo', 'Call Me', '555'),
    ('타블로', "Tomorrow's Today", 'Tomorrow'),
    ('Vasco', 'Vasco', 'The Bill'),
    ('JJK', 'Go Back Pt.2', 'Go-Back'),
    ('아웃사이더', 'Hero', 'Vol.2-Maestro'),
    ('Rhymer', 'Brand New Day Pt.2', 'Rhymer Trax Vol.1'),
    ('Double K', 'Fly High Pt.2', 'Fly High'),
    ('Pe2ny', 'Pe2ny Maker Pt.2', 'Pe2ny Maker'),
    ('TBNY', 'Million Pt.2', 'Million'),
    ('Stuck B', 'Stuck B Pt.2', 'Stuck B'),
    ('Crown J', 'My Friend Pt.2', 'My Friend'),
    ('L.E.O.', 'Show Must Go On Pt.2', 'Show Must Go On'),
    ('에픽하이', 'Clutch', 'Epilogue'),
    ('San E', 'Not Cute', 'Ready for Showtime'),
    ('팬텀', 'Phantom City', 'Phantom City'),
    ('Gaeko', 'Wherever', 'Hard Rock Techno'),
    ('Gaeko', 'Hard Rock Techno', 'Hard Rock Techno'),
    ('Swings', 'Volcanic', 'Upgrade II'),
    ('Swings', '화산', 'Upgrade II'),
    ('Zion.T', 'Click Me', 'Click Me'),
    ('Zion.T', 'Must Go', 'Click Me'),
    ('Crush', 'Memories', 'Memories'),
    ('Crush', 'Sometimes', 'Memories'),
    ('Loco', 'See You', 'Blonote'),
    ('Loco', 'Hold Me', 'Blonote'),
    ('Gray', 'Call Me Yours', 'Gray Season 1'),
    ('Gray', 'Dangerous', 'Gray Season 1'),
    ('Giriboy', 'Different Language', 'Different Language'),
    ('Giriboy', '다른 언어', 'Different Language'),
    ('Bumkey', 'Single Life', 'Single Life'),
    ('Bumkey', 'Attraction', 'Single Life'),
    ('Basick', 'Alright', 'The Classic'),
    ('Eluphant', 'Make Her Feel', 'Eluphant'),
    ('Eluphant', '편지', 'Eluphant'),
    ('Soul Dive', 'Soul Dive', 'Soul Dive'),
    ('Soul Dive', '소울 다이브', 'Soul Dive'),
    ('MC Sniper', 'Better Than Yesterday', 'Just Sniper'),
    ('MC Sniper', '어제보다', 'Just Sniper'),
    ('Nuol', 'Rainbow', 'Rainbow'),
    ('Nuol', '레인보우', 'Rainbow'),
    ('Pharaoh', 'Pharaoh', 'Pharaoh'),
    ('Pharaoh', '파라오', 'Pharaoh'),
    ('Leo Kott', 'Leo Kott', 'Leo Kott'),
    ('Leo Kott', '레오 콧', 'Leo Kott'),
    ('J Black', 'Why', 'Why'),
    ('J Black', '왜', 'Why'),
    ('가은', 'Tears', ''),
    ('가은', '눈물', ''),
    ('Honey Family', 'Honey Family', 'Honey Family'),
    ('Honey Family', '꿀가족', 'Honey Family'),
    ('Crucial Star', '너의 집 앞', ''),
    ('Crucial Star', 'Street Love', ''),
    ('Rohzi', '찌질어', ''),
    ('Rohzi', '로지', ''),
    ('Myk', '그해 여름', ''),
    ('Myk', '마이크', ''),
    ('Primary', 'Happy Ending', 'Primary And The Messengers LP'),
]
