# 힙플·힙플레이·전문가 평가 기준 2014년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Epik High', 'Born Hater (본 헤이터)', 'Shoebox'),
    ('Epik High', '눈, 코, 입', 'Shoebox'),
    ('Crush', '소파', ''),
    ('Mad Clown', '오늘밤', '허튼 소망'),
    ('Loco', '너를 생각해', 'Locomotive'),
    ('Swings', '홍키영', 'Show Me the Money 3'),
    ('Bobby', 'Holup!', 'SECRET'),
    ('Mino', '겁', 'Fear'),
    ('Dynamic Duo', '거대한 발걸음', ''),
    ('Gaeko', '집으로', '집으로'),
    ('Heize', '조금만 더 걸을래', ''),
    ('Verbal Jint', 'Good Morning Pt.3', 'Rap Genius No. 8'),
    ('Huckleberry P', 'Mantra 3', 'Mantra 3'),
    ('Huckleberry P', '만트라 3', 'Mantra 3'),
    ('Deepflow', '컴백홈', 'Flow the Life 3'),
    ('San E', 'Story of Someone I Know', 'Show Me the Money 3'),
    ('Iron', 'Rock Bottom', 'Show Me the Money 3'),
    ('Basick', 'Hold You', 'Show Me the Money 3'),
    ('Black Nut', '100', 'Show Me the Money 3'),
    ('Louie', 'GO', 'Show Me the Money 3'),
    ('Truedy', 'My Light', 'Show Me the Money 3'),
    ('San E', 'Bananas', 'Show Me the Money 3'),
    ('Black Nut', '가', 'Show Me the Money 3'),
    ('Louie', '고', 'Show Me the Money 3'),
    ('Truedy', '마이 라이트', 'Show Me the Money 3'),
    ('Verbal Jint', 'Rap Genius No. 8', 'Rap Genius No. 8'),
    ('Nafla', '무드', ''),
    ('Paloalto', '샤이닝 다이아몬드', 'Shining Diamond'),
    ('Don Mills', '돈밀스', 'Don Mills Is Angry 3'),
    ('The Quiett', '큐 트레인', 'Q Train'),
    ('BTS', 'Danger', 'DARK & WILD'),
    ('Bobby', '감동 (Secret)', 'SECRET'),
    ('Crush', '가끔', 'Crush on You'),
    ('Loco', '장갑', 'Locomotive'),
    ('Jay Park', 'So Good', 'Evolution'),
    ('Swings', '우리를 기억해', 'Growing Pains'),
    ('Beenzino', 'Up All Night', 'Up All Night'),
    ('Zico', 'Tough Cookie', 'Zico on the Block 1.5'),
    ('Dean', 'Put My Hands on You', ''),
    ('Primary', 'JohnLegend', 'Da Capo'),
    ('Giriboy', 'Camp', ''),
    ('Zion.T', 'Zero Gravity', ''),
    ('Beenzino', 'How Do I Look?', 'Up All Night'),
    ('Jay Park', 'Evolution', 'Evolution'),
    ('BTS', '호르몬 전쟁', 'DARK & WILD'),
    ('Mino', 'Body', 'Fear'),
    ('Zion.T', 'Eat', ''),
    ('Giriboy', 'Different', 'Different'),
    ('Punchnello', 'If You', 'If You'),
    ('Colde', 'In Your Eyes', 'In Your Eyes'),
    ('Zico', '성인식', ''),
    ('Dok2', 'Thug Life', 'Thug Life Part 2'),
    ('Tablo', 'Bad', "Fever's End Pt. 2"),
    ('Leessang', 'Coming of Age Story', ''),
    ('Yoon Mirae', 'Angel', ''),
    ('Junggigo', 'Warm', ''),
    ('Okasian', 'Airplane Mode', ''),
    ('Tiger JK', 'Monologue', ''),
    ('Gray', "Let's Fall in Love", 'Gray Season 2'),
    ('Gray', 'Smile', 'Gray Season 2'),
    ('Heize', 'Heize', 'HEIZE'),
    ('Primary', 'Da Capo', 'Da Capo'),
    ('Illinit', 'Ill Street Live', ''),
    ('Outsider', 'Vol.2-Maestro', 'Vol.2-Maestro'),
    ('Simon Dominic', 'No Stress', ''),
    ('Simon Dominic', 'New Year New Me', ''),
    ('Tablo', 'Timeless', "Fever's End Pt. 2"),
    ('Dok2', "It's All Good", 'Thug Life Part 2'),
    ('Mad Clown', 'Potato', 'Potato'),
    ('Elo', 'Hood', 'Hood'),
    ('C Jamm', '떡', ''),
    ('Lil Boi', '관람차', ''),
    ('Reddy', '커밋먼트', 'Orca-Tape'),
    ('G2', '온라인', ''),
    ('Bumkey', '깨어나', ''),
    ('Okasian', '에어플레인', ''),
    ('Tiger JK', '독백', ''),
    ('Sean2Slow', '슬로우', 'Slow Jam'),
    ('Leessang', '청춘', ''),
    ('Yoon Mirae', '천사', ''),
    ('Junggigo', '따뜻', ''),
    ('Phantom', '버블 러브', 'Phantom City'),
    ('Mighty Mouth', '사랑이', 'Mighty Style'),
    ('Skull', '스쿨', 'Skull & Haha'),
    ("J'Kyun", '날아', 'Ready to Fly'),
    ('MC Meta', '혼자', 'The Blue Printz'),
    ('Geologic', '블레이즈', 'Geologic'),
    ('Kebee', '리듬', 'Rhythm and Poetry'),
    ('Vasco', '바스코', 'The Vasco'),
    ('Jerry.K', '브이', 'V'),
    ('Changmo', '리벨', ''),
    ('Punchnello', '니가 있다면', 'If You'),
    ('Outsider', '외톨이', 'Vol.2-Maestro'),
    ('Hanhae', 'Hanhae Business', '135'),
    ('Andup', 'U', 'The Last'),
    ('Shin Zino', 'Good Day', ''),
    ('TBNY', '2 Bad', ''),
    ('Most Badass Asian', 'The Most Badass Asian', ''),
    ('Flowsik', 'Airplane Mode', ''),
    ('Nucksal', 'Skill', ''),
]
