# 힙플·힙플레이·전문가 평가 기준 2015년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('E-Sens', '회의록', 'The Anecdote'),
    ('E-Sens', '새벽 2시', 'The Anecdote'),
    ('Simon Dominic', 'Won & Only', 'Won & Only'),
    ('Simon Dominic', '사이먼 도미닉', 'Won & Only'),
    ('Beenzino', 'So What', ''),
    ('Giriboy', '왜 이렇게 살아', ''),
    ('BewhY', 'Day Day', 'The Movie Star'),
    ('BewhY', 'Forever', 'The Movie Star'),
    ('Nafla', 'Natural High', 'Natural High'),
    ('Loopy', 'No More', 'Mmk'),
    ('Iron', 'Rain Shower', 'Show Me the Money 4'),
    ('Basick', 'Pale Dream', 'Show Me the Money 4'),
    ('Basick', 'Stand Up', 'Show Me the Money 4'),
    ('Kid Milli', 'IndiGO', 'IndiGO'),
    ('Changmo', 'Maestro', 'Maestro'),
    ('The Quiett', 'Cut', ''),
    ('Verbal Jint', 'Rap Genius No. 9', 'Rap Genius No. 9'),
    ('Epik High', 'Born Hater', 'Shoebox'),
    ('Primary', 'Roller Coaster', 'Primary and the Messengers LP 2'),
    ('Tablo', 'Eyes, Nose, Lips', "Fever's End Pt. 1"),
    ('Dean', 'Pour Up', ''),
    ('Zion.T', '노메이크업', ''),
    ('Crush', 'Just', ''),
    ('Heize', 'And July', 'And July'),
    ('Loco', 'Respect', ''),
    ('Gray', 'Just Do It', ''),
    ('Jay Park', 'MOMMAE', 'Worldwide'),
    ('Zico', 'Boys and Girls', 'Breakthrough'),
    ('Sik-K', 'TRAP', 'TRAP'),
    ('Punchnello', 'Loving You Girl', 'Loving You Girl'),
    ('PH-1', 'Good Day', 'Good Day'),
    ('Hash Swan', 'Retro Love', ''),
    ('Dynamic Duo', 'AEAO', 'Grand Carnival'),
    ('iKON', '취향저격', 'WELCOME BACK'),
    ('BTS', 'I NEED U', 'The Most Beautiful Moment in Life Pt.1'),
    ('BTS', '뱁새', 'The Most Beautiful Moment in Life Pt.1'),
    ('Kid Milli', '키드', 'IndiGO'),
    ('Huckleberry P', '만트라 4', 'Mantra 4'),
    ('Lil Boi', 'Good Day', 'Show Me the Money 4'),
    ('San E', 'A BILLIONAIRE', 'Show Me the Money 4'),
    ('Iron', '새벽에', 'Show Me the Money 4'),
    ('Black Nut', '살', 'Show Me the Money 4'),
    ('Black Nut', '사랑', 'Show Me the Money 4'),
    ('Louie', '빛', 'Show Me the Money 4'),
    ('Truedy', '비밀', 'Show Me the Money 4'),
    ('Flowsik', '위 온', 'Show Me the Money 4'),
    ('Hash Swan', '레트로', 'Hash Brand'),
    ('San E', 'Body', 'Show Me the Money 4'),
    ('Lil Boi', 'Credit', 'Show Me the Money 4'),
    ('Truedy', 'Truedy', 'Show Me the Money 4'),
    ('Louie', '루이', 'Show Me the Money 4'),
    ('Blase', 'Passionfruit', ''),
    ('Blase', '블레이즈', ''),
    ('Paloalto', 'Sunday Service', 'Nomad'),
    ('Verbal Jint', 'Numbers', 'Rap Genius No. 9'),
    ('Paloalto', '팔로알토', 'Nomad'),
    ('The Quiett', '더콰이엇', ''),
    ('Dean', 'I Love It', ''),
    ('Crush', 'Oasis', 'Crush on You'),
    ('Zion.T', 'Complex', ''),
    ('Jay Park', 'All I Wanna Do', 'Worldwide'),
    ('iKON', 'MY TYPE', 'WELCOME BACK'),
    ('Loco', 'Awesome', ''),
    ('Heize', 'No Way', 'And July'),
    ('Dynamic Duo', 'Grand Carnival', 'Grand Carnival'),
    ('Beenzino', 'Break', '12'),
    ('Gray', "We Don't Love", 'Gray Season 2'),
    ('Giriboy', 'Back and Forth 30 Min', 'Sexual Perceptions'),
    ('Zico', 'Breakthrough', 'Breakthrough'),
    ('Sik-K', 'Romeo & Juliet', 'TRAP'),
    ('Bobby', 'GO UP', 'WILD AND YOUNG'),
    ('PH-1', 'Nineteen', 'Good Day'),
    ('Junggigo', 'Want U', ''),
    ('Okasian', 'Celebration', ''),
    ('YUMDDA', "I'm Good", ''),
    ('Mirani', 'Pepsi', ''),
    ('Mad Clown', '화 (Fire)', 'Fire'),
    ('Yoon Mirae', 'Touch Love', ''),
    ('Vasco', 'Real Talk', 'The Vasco'),
    ('Swings', "I'll Give You Everything", ''),
    ('Nucksal', '홍보', ''),
    ('Mirani', '미란', ''),
    ('YUMDDA', '염따', ''),
    ('Changmo', 'Ring Ding', 'Maestro'),
    ('Dok2', 'Rich Forever', 'Thug Life Part 2'),
    ('Swings', '비', ''),
    ('Coogie', 'Woops', ''),
    ('Leellamarz', 'To Be Continued', 'To Be Continued'),
    ('Colde', '네 눈', 'Your Dog Loves You'),
    ('Punchnello', 'Cool', 'Loving You Girl'),
    ('Bobby', 'Wedding Dress', 'WILD AND YOUNG'),
    ('Tablo', '타블로', "Fever's End Pt. 1"),
    ('Dok2', '도끼', 'Thug Life Part 2'),
    ('Gaeko', '개코', 'Redingray'),
    ('Elo', '이로', 'Hood'),
    ('Junggigo', '정이고', ''),
    ('Okasian', '오케이션', ''),
    ('Penomeco', '페노', ''),
    ('Leellamarz', '릴러말즈', 'To Be Continued'),
    ('Nucksal', '넉살', ''),
]
