# 힙플·힙플레이·전문가 평가 기준 2023년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Don Malik', 'SEOUL', 'MADE IN SEOUL'),
    ('Don Malik', 'Malik', 'MADE IN SEOUL'),
    ('Epik High', 'Strawberry', 'Strawberry'),
    ('Epik High', 'Fade Away', 'Strawberry'),
    ('BIG Naughty', 'Você', 'Você'),
    ('Qwala', 'ㅍㅍㅍㅍ (Feat. Kid Milli)', 'ㅍㅍㅍㅍ'),
    ('Ourealgoat', 'Maybe', ''),
    ('Blued', 'Tears', ''),
    ('Nafla', 'C.R.E.A.M', 'C.R.E.A.M'),
    ('The Quiett', 'King Is Back', 'Luxury Flow'),
    ('Giriboy', 'Engineering', 'Engineering'),
    ('Giriboy', 'Girlfriend', ''),
    ('Kid Milli', 'Benzo', ''),
    ('Leellamarz', 'DAYDATE', 'DAYDATE'),
    ('Leellamarz', '모른 척', 'DAYDATE'),
    ('Jvcki Wai', 'Exposure', 'Exposure'),
    ('Deepflow', 'Flow the Life 6', 'Flow the Life 6'),
    ('Huckleberry P', 'Mantra 6', 'Mantra 6'),
    ('Don Mills', 'Don Mills Is Angry 6', 'Don Mills Is Angry 6'),
    ('Paloalto', 'GONE', ''),
    ('Uneducated Kid', 'UNEDUCATED KID', ''),
    ('Blase', 'Holiday (Feat. Lil Boi, 기리보이)', 'Show Me the Money 11'),
    ('허성현', '미운오리새끼 (Prod. R.Tee)', 'Show Me the Money 11'),
    ('Kan', '나침반 (Feat. UNEDUCATED KID, Superbee)', 'Show Me the Money 11'),
    ('Beenzino', 'Trippy', 'NOWITZKI'),
    ('Beenzino', 'NOWITZKI', 'NOWITZKI'),
    ('Zico', 'SPOT!', ''),
    ('Zico', 'Earthquake', ''),
    ('Lil Moshpit', 'TO GO', ''),
    ('82MAJOR', 'FIRST CLASS', 'ON'),
    ('82MAJOR', 'ON', 'ON'),
    ('Ahn Se-min', '물', 'Show Me the Money 11'),
    ('NSW yoon', 'Therapy + 으리으리 (Feat. 호미들)', 'Show Me the Money 11'),
    ('QM', 'Come To My Stu (Feat. 릴러말즈)', 'Show Me the Money 11'),
    ('노윤하', "Flick (Feat. BE'O, HAON)", 'Show Me the Money 11'),
    ('잠비노', 'Bingo (Feat. 미노이, George)', 'Show Me the Money 11'),
    ('이영지', 'WITCH (Feat. 밸재범, 황소윤)', 'Show Me the Money 11'),
    ('Owen Ovadoz', 'Drama', ''),
    ('Blase', 'City Life', ''),
    ('Owen Ovadoz', 'Freeze', '119'),
    ('The Quiett', 'Mercedes (메르세데스)', 'Luxury Flow'),
    ('meenoi', 'Malfunction', ''),
    ('Lil Moshpit', 'Money Only Shows Hustle', ''),
    ('meenoi', '3MAN', ''),
    ('DeVita', 'Ride or Die', ''),
    ('Mirani', 'Baby', ''),
    ('Woodie Gochild', 'Mood', ''),
    ('Crush', 'wonderego', 'wonderego'),
    ('CAMO', 'Wifey', ''),
    ('B.I', 'Lover', ''),
    ('Coq', 'Tweaker', ''),
    ('Coogie', 'Buck', 'DIFF'),
    ('Loco', 'VOLVO', ''),
    ('Dean', 'NO FUN', "howlin' 404"),
    ('Heize', 'Perhaps Happy Ending (아마도 해피 엔딩)', 'Last Winter'),
    ('Zion.T', 'UNLOVE', 'Zip'),
    ('Bobby', 'Drowning', 'S.i.R'),
    ('Mino', 'Smoke', 'BODY'),
    ('Changmo', 'VOOM', ''),
    ('PH-1', 'Rosario', 'But For Now Leave Me Alone 2'),
    ('Gray', 'Summer Surf', 'Summer Surf'),
    ('Punchnello', 'Motive', ''),
    ('Colde', 'Wave', ''),
    ('Dynamic Duo', 'Smoke (Prod. Dynamicduo, Padi)', 'Street Woman Fighter 2 Original Vol.1'),
    ('GroovyRoom', 'Brought the Heat Back', 'Brought the Heat Back'),
    ('PLT', 'Way Back Home', 'Way Back Home'),
    ('Jay Park', 'Candy', ''),
    ('Knoxx', 'Knoxx', ''),
    ('Polodared', 'Multiverse', ''),
    ('Hej!', 'Drive', ''),
    ('Futuristic Swaver', 'Villain', ''),
    ('Hodaky', 'Yellow', ''),
    ('Chillin Homie', 'Good Day', ''),
    ('Superbee', 'Superbee', ''),
    ('Bluso', 'Fade Away', ''),
    ('LeyonC', 'Fall', ''),
    ('Hyunsang', 'Take Care', ''),
    ('Woo', 'Rain Drop', 'Rain Drop'),
    ('Rohann', 'Sunday', ''),
    ('Lee Young Ji', 'O.K?', 'O.K?'),
    ('Jessi', 'Gum', 'Gum'),
    ('Lil Boi', 'Empty Head', ''),
    ('Baechigi', '상어의 이야기', "Shark's Tale"),
    ('BIG Naughty', 'Vogue', 'Vogue'),
    ('Mudd the student', 'Sleepy Beauty', ''),
    ('Olltii', 'Turtle Ship Remix', ''),
    ('Kid Milli', 'BEIGE theme', 'BEIGE'),
    ('Crush', 'Hmm-cheat', 'wonderego'),
    ('CAMO', 'Melody', 'Melody'),
    ('Coogie', 'Just For Fun', 'DIFF'),
    ('Loco', 'INEEDYOURLOVE', ''),
    ('Dean', 'Die 4 You', ''),
    ('Heize', 'From Autumn to Winter (가을에서 겨울로)', 'Last Winter'),
    ('Zion.T', 'Happy Ending', 'Zip'),
    ('Changmo', 'FWB', ''),
    ('PH-1', 'Final Bout', 'But For Now Leave Me Alone 2'),
    ('Colde', 'Reno', ''),
    ('Jay Park', 'Sunday Night Drive', ''),
    ('Lee Young Ji', 'Not Sure (낫 슈어)', '16'),
    ('Jessi', 'Cold Blooded (콜드 블러디드)', 'Cold Blooded'),
]
