# 힙플·힙플레이·전문가 평가 기준 2022년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Epik High', '그래서 그래 (Feat. 윤하)', 'Epik High Is Here 下, Part 2'),
    ('Epik High', '비 오는 날 듣기 좋은 노래 (Feat. 콜드)', 'Epik High Is Here 下, Part 2'),
    ('JUSTHIS', '마이웨이 (MY WAY) (Prod. by Alti)', 'Show Me the Money 11'),
    ('Kid Milli', '가볍게', ''),
    ('Giriboy', 'Vice Versa', 'Vice Versa'),
    ('Ash Island', '안전지대', 'Safety Zone'),
    ('The Quiett', 'Bentley', ''),
    ('TOIL', '처음 만났을 때처럼', ''),
    ('PH-1', 'BUT FOR NOW LEAVE ME ALONE', 'BUT FOR NOW LEAVE ME ALONE'),
    ('Beenzino', 'MONET', ''),
    ('Leellamarz', '그러지마', 'Toystory3'),
    ('Coogie', '굿나잇', 'Re:Up'),
    ('Dynamic Duo', 'ECO', 'ECO'),
    ('Mirani', 'Drama', 'Drama'),
    ('허성현', '펄펄 (Feat. Dynamic Duo)', 'Show Me the Money 11'),
    ('Kan', 'Therapy + 으리으리 (Feat. 호미들)', 'Show Me the Money 11'),
    ('이영지', '낫 쏘리 (Feat. pH-1)', 'Show Me the Money 11'),
    ('Zico', '새삥 (Prod. ZICO) (Feat. 호미들)', 'Street Man Fighter Original Vol.3'),
    ('BIGBANG', '봄여름가을겨울 (Still Life)', 'Still Life'),
    ('Crush', 'Rush Hour (Feat. j-hope of BTS)', 'Rush Hour'),
    ('PH-1', 'Zombies', 'BUT FOR NOW LEAVE ME ALONE'),
    ('Dynamic Duo', 'Smoke', 'ECO'),
    ('Giriboy', 'Braille', 'Vice Versa'),
    ('Ash Island', 'Malibu Night', 'Safety Zone'),
    ('Don Malik', 'Don Malik', 'Show Me the Money 11'),
    ('Huckleberry P', '우퍼', 'Mantra 3'),
    ('Lee Young Ji', 'WITCH (Feat. 밸재범, 황소윤)', 'Show Me the Money 11'),
    ('JUSTHIS', 'Signature (Prod. by Alti)', 'Show Me the Money 11'),
    ('GwangilJo', 'VVS (비비에스)', 'Show Me the Money 8'),
    ('Ahn Se-min', 'Ahn Se-min', 'Show Me the Money 11'),
    ('NSW yoon', 'NSW yoon', 'Show Me the Money 11'),
    ('QM', 'QM', 'Show Me the Money 11'),
    ('노윤하', '노윤하', 'Show Me the Money 11'),
    ('잠비노', '잠비노', 'Show Me the Money 11'),
    ('이영지', '이영지', 'Show Me the Money 11'),
    ('Kan', 'Kan', 'Show Me the Money 11'),
    ('Lee Young Ji', '낫 쏘리 (Feat. pH-1)', 'Show Me the Money 11'),
    ('Sokodomo', 'Winner', 'Show Me the Money 10'),
    ('Koonta', 'Grandma', 'Show Me the Money 8'),
    ('Owen Ovadoz', '119', '119'),
    ('Nafla', 'Freestyle', ''),
    ('Loopy', 'Freestyle', ''),
    ('Verbal Jint', 'Mainstream', 'Mainstream'),
    ('The Quiett', 'Luxury Flow', 'Luxury Flow'),
    ('Nafla', 'Swervin', 'C.R.E.A.M'),
    ('Beenzino', '덤보', 'Dumbo'),
    ('Zico', 'Grown Ass Kid', 'Grown Ass Kid'),
    ('Kid Milli', 'SUMMER', ''),
    ('Coogie', '혼자', 'Re:Up'),
    ('Leellamarz', '마지막 기회', 'Toystory3'),
    ('Loco', 'WIN', ''),
    ('GRAY', 'Remedy', ''),
    ('GroovyRoom', 'Whistle (Prod. GroovyRoom) (Feat. 식케이, Mirani)', 'Street Man Fighter Original Vol.3'),
    ('Woodie Gochild', 'Channel Surfing', '#GOchild'),
    ('Punchnello', 'Loveseat', ''),
    ('Colde', 'Star', ''),
    ('Changmo', 'Just the Two of Us', ''),
    ('Heize', 'Undo', ''),
    ('Jessi', 'Zoom', ''),
    ('Zion.T', 'Lonely Christmas', ''),
    ('Lil Moshpit', 'MOSHPIT ONLY', 'AAA'),
    ('Primary', 'BILLING', 'BILLING'),
    ('Gaeko', 'Sturgis', 'Sturgis'),
    ('Simon Dominic', 'Make Her Dance', 'Simon Dominic Part 3'),
    ('Jvcki Wai', 'Taxi Blurr', 'Taxi Blurr'),
    ('Mino', '안녕', 'To Infinity'),
    ('Tablo', 'Stop the Rain', ''),
    ('JJK', 'Go Back', 'Go-Back'),
    ('Baechigi', "Shark's Tale", "Shark's Tale"),
    ('meenoi', 'What Do You Think?', ''),
    ('CAMO', 'Life is Wet', ''),
    ('Uneducated Kid', 'UNEDUCATED KID 2', ''),
    ('BIG Naughty', 'Romance Symphony', ''),
    ('DeVita', 'Flowers', ''),
    ('Futuristic Swaver', 'Blue Hawaii', ''),
    ('Knoxx', 'Knoxx Tape', ''),
    ('Polodared', 'Polodared', ''),
    ('Hej!', 'Hej!', ''),
    ('Hodaky', 'Hodaky', ''),
    ('Chillin Homie', 'Chillin Homie', ''),
    ('Bluso', 'Bluso', ''),
    ('LeyonC', 'LeyonC', ''),
    ('Hyunsang', 'Hyunsang', ''),
    ('Woo', 'Woo', ''),
    ('BRADYSTREET', 'Heavy', ''),
    ('Gist', 'Engagement', ''),
    ('Blued', 'Melody', 'Melody'),
    ('Loco', 'Focus', ''),
    ('GRAY', 'Sweaty (Prod. GRAY) (Feat. 로꼬, Coogie)', 'Street Man Fighter Original Vol.3'),
    ('GroovyRoom', 'Brought the Heat Back (Feat. 식케이, Paloalto)', 'Brought the Heat Back'),
    ('Sik-K', 'MOON', 'MAKE OUT'),
    ('Swings', 'Per se', 'Per se'),
    ('Changmo', 'ANTHEM', 'Op.1'),
    ('Jessi', 'Who Dat B', 'Who Dat B'),
    ('Tablo', 'Fantasy', 'Drill Presents: Tablo x Fantasy'),
    ('meenoi', 'Business boy', ''),
    ('CAMO', 'Freak Like Me', ''),
    ('NO:EL', 'Rain Drop 2', 'Rain Drop 2'),
    ('Punchnello', 'Winter Blossom', 'Winter Blossom'),
    ('Colde', 'honestly', 'Star'),
]
