# 힙플·힙플레이·전문가 평가 기준 2021년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('TOIL', 'Switch', '1989'),
    ('Blase', 'ONOFF', 'Show Me the Money 10'),
    ('Blase', 'Good Life (굿 라이프)', 'Show Me the Money 10'),
    ('Owen Ovadoz', 'Diana (디ana)', 'Show Me the Money 10'),
    ('Owen Ovadoz', 'Freestyle (프리스타일)', 'Show Me the Money 10'),
    ('Lil Boi', '삐딱하게', 'Show Me the Money 9'),
    ('Lil Boi', 'Wave (웨이브)', 'Show Me the Money 10'),
    ('Ash Island', 'Me n Mine', 'Show Me the Money 10'),
    ("be'O", 'Countdown (카운트다운)', 'Show Me the Money 10'),
    ("be'O", 'Luxury (럭셔리)', 'Show Me the Money 10'),
    ('Mudd the student', 'Nectar (넥타)', 'Show Me the Money 10'),
    ('Mudd the student', 'Open', 'Show Me the Money 8'),
    ('Mirani', 'Villain (빌런)', 'Show Me the Money 10'),
    ('Mirani', 'Baby Steps', 'Show Me the Money 10'),
    ('Koonta', 'KOONTA (쿤타)', 'Show Me the Money 10'),
    ('Koonta', 'Ambition (앰비션)', 'Show Me the Money 10'),
    ('Sokodomo', 'SIGNATURE (시그니처)', 'Show Me the Money 10'),
    ('Sokodomo', 'Winner (위너)', 'Show Me the Money 10'),
    ('Woodie Gochild', 'Mud (머드)', 'Show Me the Money 10'),
    ('Woodie Gochild', 'SMTM10 (쇼미10)', 'Show Me the Money 10'),
    ('Lil Moshpit', 'Good Day (굿 데이)', 'Show Me the Money 10'),
    ('Lil Moshpit', 'ACHOO', 'Show Me the Money 10'),
    ('Wonstein', '10 Minutes (10분)', 'Show Me the Money 10'),
    ('Wonstein', 'Infrared (적외선)', 'Show Me the Money 10'),
    ('Trade L', 'Leave It (두고 가)', 'Show Me the Money 10'),
    ('Trade L', 'Blue Sky (블루 스카이)', 'Show Me the Money 10'),
    ('Roh Yun Ha', 'IF I (이프 아이)', 'Show Me the Money 10'),
    ('Roh Yun Ha', 'Trouble (트러블)', 'Show Me the Money 10'),
    ('TOIL', 'like when we first met (처음 만났을 때처럼)', ''),
    ('Paloalto', 'Brought the Heat Back', 'Brought the Heat Back'),
    ('Paloalto', 'Valentina', ''),
    ('Khundi Panda', 'Medicine (약)', 'Medicine'),
    ('Khundi Panda', 'Pick Up (픽업)', 'Medicine'),
    ('B-Free', 'Best Seller (베스트 셀러)', 'Best Seller'),
    ('B-Free', 'Hot Summer (핫 썸머)', 'Best Seller'),
    ('Changmo', '모래시계 (MORAESIGYE)', 'UNDERGROUND ROCKSTAR'),
    ('Changmo', 'TAIJI (태지)', 'UNDERGROUND ROCKSTAR'),
    ('Ash Island', 'Sculpture (조각)', 'Melodies'),
    ('Leellamarz', 'Marz', 'Marz & Ale'),
    ('Leellamarz', 'Don`t Say That', 'Don`t Say That'),
    ('Coogie', 'I Got A Feeling', 'I Got A Feeling'),
    ('Coogie', 'Justin Bieber (저스틴 비버)', 'Up!'),
    ('Sik-K', 'Brought the Heat Back (더운데)', 'Brought the Heat Back'),
    ('Sik-K', 'TAKE OUT (테이크 아웃)', 'Brought the Heat Back'),
    ('Kid Milli', 'Cliché (클리셰)', 'Cliché'),
    ('Kid Milli', 'OFF KEY', 'Cliché'),
    ('Beenzino', 'MODERN (모던)', 'MODERN'),
    ('Beenzino', "Walkin' on Water", 'MODERN'),
    ('PH-1', 'Ninth (나인스)', 'Ninth'),
    ('PH-1', 'Ninth Sense', 'Ninth'),
    ('Epik High', 'Rosario (로사리오)', 'Epilogue Pt.2'),
    ('Epik High', 'Breathe (브리드)', 'Epilogue Pt.2'),
    ('Lee Young Ji', 'Untouchable (언터처블)', 'Untouchable'),
    ('Lee Young Ji', 'Witch (위치)', 'Witch'),
    ('Dynamic Duo', 'Untouchable', 'Untouchable'),
    ('Crush', 'Rush Hour (오르트 구름)', 'Rush Hour'),
    ('Crush', 'Click Like', 'Click Like'),
    ('Jessi', 'Cold Blooded (냉혈한)', 'Cold Blooded'),
    ('Jessi', 'What Type of X (어떤X)', 'Cold Blooded'),
    ('GroovyRoom', 'Brought the Heat Back (더운데)', 'Brought the Heat Back'),
    ('GroovyRoom', 'Wavy (웨이비)', 'Brought the Heat Back'),
    ('Mino', 'Do You Remember (기억하니)', 'Do You Remember'),
    ('Mino', 'Booker', 'Booker'),
    ('Jay Park', 'To Life (투 라이프)', 'To Life'),
    ('Jay Park', 'McNasty', 'To Life'),
    ('Gray', 'Summer Surf (썸머 서프)', 'Summer Surf'),
    ('Gray', 'Adios (아디오스)', '00 XX'),
    ('Dean', '4:44', '4:44'),
    ('Dean', '포포 (4:44)', '4:44'),
    ('Heize', 'Midnight (미드나잇)', 'Midnight'),
    ('Heize', 'And Today (그리고 오늘)', '///'),
    ('Zion.T', 'Just (저스트)', 'Just'),
    ('Zion.T', 'Snow (눈)', 'OO'),
    ('Paul Blanco', 'Summer (썸머)', 'Summer'),
    ('Paul Blanco', 'Rain (비)', 'Summer'),
    ('Colde', '정 (Honesty)', 'Star'),
    ('Colde', '와르르 (Warrr)', 'Star'),
    ('Killagramz', 'Good Morning (굿 모닝)', 'Good Morning'),
    ('Killagramz', 'Good Morning Remix (굿 모닝 리믹스)', 'Good Morning'),
    ('Hanhae', '003', '003'),
    ('Hanhae', '001', '003'),
    ('B.I', 'Waterfall (워터폴)', 'Waterfall'),
    ('B.I', 'Illa Illa (illa illa)', 'Waterfall'),
    ('Basick', 'Nice Day (나이스 데이)', 'Nice Day'),
    ('Basick', 'Show Me The Money (쇼미)', 'Nice Day'),
    ('Tabber', 'RUN CHICKEN (런 치킨)', 'RUN CHICKEN'),
    ('Tabber', '3rd Eye (써드 아이)', 'RUN CHICKEN'),
    ('Illinit', 'Real Talk Live (리얼 토크)', ''),
    ('Illinit', 'Ill Street Live 2 (일 스트릿)', ''),
    ('Vasco', '더 바스코', 'The Vasco'),
    ('G2', 'G2 (지투)', 'G2'),
    ('G2', 'Business (비즈니스)', 'Business'),
    ('Cheetah', "I'll Be Back (아일 비 백)", ''),
    ('Cheetah', 'Keep It Movin (킵 잇 무빙)', ''),
    ("J'Kyun", 'Fly Away (플라이 어웨이)', 'Ready to Fly'),
    ("J'Kyun", 'Ready to Fly (레디 투 플라이)', 'Ready to Fly'),
    ('Outsider', 'Vol.2-Maestro 4', 'Vol.2-Maestro 4'),
    ('Outsider', '볼륨2 마에스트로 4', 'Vol.2-Maestro 4'),
    ('PLT', 'Summer', 'Summer'),
    ('Rad Museum', 'Girls', 'Life'),
]
