# 힙플·힙플레이·전문가 평가 기준 2020년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Deepflow', 'Flow the Life 5', 'Flow the Life 5'),
    ('Zico', 'Any Song', '아무노래'),
    ('Deepflow', '플로우 더 라이프 5', 'Flow the Life 5'),
    ('TOIL', 'Panorama', 'Show Me the Money 8'),
    ('Huckleberry P', 'Mantra 5', 'Mantra 5'),
    ('Huckleberry P', '만트라 5', 'Mantra 5'),
    ('Mudd the student', 'Do You Like Haeseon', 'Show Me the Money 9'),
    ('Mudd the student', 'Mockingbird (모킹버드)', 'Show Me the Money 9'),
    ('Hash Swan', '해시 브랜드 2', 'Hash Brand 2'),
    ('Woodie Gochild', 'New Champ (뉴 챔프)', 'Show Me the Money 8'),
    ('Woodie Gochild', 'SMTM Cypher (쇼미 사이퍼)', 'Show Me the Money 8'),
    ('Nafla', 'understand', 'understand'),
    ('Nafla', 'what is your name', 'understand'),
    ('Loopy', 'ON THE Radar', 'ON THE Radar'),
    ('Loopy', 'Radar (레이더)', 'ON THE Radar'),
    ('TOIL', 'MAZE (메이즈)', 'MAZE'),
    ('The Quiett', 'Nike (나이키)', ''),
    ('Blase', 'Quote That', ''),
    ('Don Mills', 'Don Mills Is Angry 5', 'Don Mills Is Angry 5'),
    ('Don Mills', '돈밀리 5', 'Don Mills Is Angry 5'),
    ('Verbal Jint', 'Rap Genius No. 10', 'Rap Genius No. 10'),
    ('Verbal Jint', '랩 genius no.10', 'Rap Genius No. 10'),
    ('Zico', '아무노래', '아무노래'),
    ('Changmo', 'METEORITE', 'Meteor'),
    ('Changmo', 'Band Up', 'Band Up'),
    ('Jessi', '누누나나 (NUNU NANA)', 'NUNU NANA'),
    ('Jessi', '강한 여자 (Strong Woman)', 'NUNU NANA'),
    ('Simon Dominic', 'make her dance (메이크 허 댄스)', 'GOTT'),
    ('PH-1', 'MEET N GREET', 'X'),
    ('PH-1', 'OKAY', 'X'),
    ('Coogie', 'Up!', 'Up!'),
    ('Coogie', 'Alright (올라잇)', 'Up!'),
    ('Kid Milli', 'Beige 0.5', 'Beige 0.5'),
    ('Kid Milli', 'PROUD (프라우드)', 'Beige 0.5'),
    ('Beenzino', 'Reset (리셋)', 'Reset'),
    ('Beenzino', 'Melody (멜로디)', 'Reset'),
    ('Ash Island', 'Melodies', 'Melodies'),
    ('Ash Island', 'Melody', 'Melodies'),
    ('HAON', 'You and I', 'Melodies'),
    ('HAON', 'Melody', 'Melodies'),
    ('Leellamarz', 'Ale', 'Marz & Ale'),
    ('Leellamarz', '1,2', 'Marz & Ale'),
    ('Giriboy', 'Lonely (론리)', 'Lonely'),
    ('Giriboy', 'Because I Love You', 'Lonely'),
    ('Jay Park', 'Forget About Tomorrow', 'Forget About Tomorrow'),
    ('Jay Park', 'Need That', 'Forget About Tomorrow'),
    ('Loco', 'Hello (헬로)', 'Hello'),
    ('Loco', 'The Show', 'Hello'),
    ('Gray', 'summer (썸머)', 'summer'),
    ('Gray', '00 XX', '00 XX'),
    ('Sik-K', 'Bungee (번지)', 'Bungee'),
    ('Sik-K', 'STOPTHAT', ''),
    ('Crush', 'Click Like (클릭해)', 'Click Like'),
    ('Paul Blanco', 'Click Like', 'Click Like'),
    ('Dean', 'Peace (피스)', 'Peace'),
    ('Punchnello', 'Loveseat (러브시트)', 'Winter Blossom'),
    ('Punchnello', 'Cream Cheese (크림 치즈)', 'Winter Blossom'),
    ('Colde', 'Star (스타)', 'Star'),
    ('Colde', 'honestly (어니스틀리)', 'Star'),
    ('Swings', 'Shook Ones', 'Shook Ones'),
    ('Swings', 'Remedy (레미디)', 'Remedy'),
    ('Gaeko', 'West Coast (웨스트 코스트)', 'Redingray'),
    ('Gaeko', 'Pass (패스)', 'Pass'),
    ('Bobby', 'Lalala (라라라)', 'Lalala'),
    ('Bobby', 'One Shot', 'One Shot'),
    ('Mino', 'Booker (부커)', 'Booker'),
    ('Mino', 'Do It', 'Do It'),
    ('Tablo', 'Tomorrow (내일)', 'Birthday'),
    ('Tablo', 'Day Day (데이데이)', 'Birthday'),
    ('Code Kunst', 'Buckle Up (버클 업)', 'Code Kunst Archive Pack 02'),
    ('Code Kunst', 'Rain (비)', 'Code Kunst Archive Pack 02'),
    ('Zion.T', 'Spring Dream (봄꿈)', 'Zionic'),
    ('Zion.T', 'Lonely Christmas (외로운 크리스마스)', 'Zionic'),
    ('Dok2', '올 아이 노우 이즈', 'Thug Life Part 2'),
    ('Penomeco', 'COCO BOTTLE (코코보틀)', ''),
    ('NO:EL', 'Rain Drop 5 (비 5)', 'Rain Drop 5'),
    ('NO:EL', 'Rain Drop 6 (비 6)', 'Rain Drop 6'),
    ('Elo', 'Trouble (트러블)', 'Hood'),
    ('Elo', 'Hood (후드)', 'Hood'),
    ('San E', 'Make Her Dance', ''),
    ('San E', '메이크 허 댄스', ''),
    ('Jvcki Wai', 'Taxi Blurr (택시 블러)', 'Taxi Blurr'),
    ('Jvcki Wai', 'Excessive (이과한)', 'Exposure'),
    ('Mirani', 'Peach (피치)', 'Ticket'),
    ('Mirani', 'Villain Prep (빌런 프렙)', 'Ticket'),
    ('YUMDDA', 'Shake', "I'm Good"),
    ('YUMDDA', '쉐이크', "I'm Good"),
    ('Primary', 'eee', '2'),
    ('Primary', '이', '2'),
    ('Olltii', '크리에이티브 컨트롤', 'Creative Control'),
    ('Lil Moshpit', 'MOSHPIT', 'MOSHPIT'),
    ('Lil Moshpit', '모스hpit', 'MOSHPIT'),
    ('Rad Museum', 'Life', 'Life'),
    ('Woo Won Jae', 'Hourglass', 'Hourglass'),
    ('Sumin', 'Mirrorball', 'Mirrorball'),
    ('Trade L', 'Rush', 'Rush'),
    ('Blued', 'Blue', 'Blue'),
    ('Queenpia', 'Queenpia', 'Queenpia'),
    ('Paul Blanco', 'Summer', 'Summer'),
    ('B.I', 'One and Only', ''),
]
