# 힙플·힙플레이·전문가 평가 기준 2025년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('Owen Ovadoz', 'TANG', 'POEMV'),
    ('Don Malik', 'Spinboutu', 'Love is a Song'),
    ('Don Malik', 'MADE IN SEOUL', 'MADE IN SEOUL'),
    ('EK', 'YAHO', 'YAHO'),
    ('Royal 44', 'Classical Freestyle', 'We Got What You Need'),
    ('Penomeco', 'EGGE (Feat. YDG)', 'RNSSNC TAPE'),
    ('Mushvenom', '돌림판 (Feat. 신빠람 이박사)', '얼'),
    ('Mushvenom', '몰러유', '얼'),
    ('Hebi', '시바세키', 'Odyssey'),
    ('The Quiett', 'Crystal Crates', 'Luxury Flow'),
    ('The Quiett', 'Look Inside', 'Luxury Flow'),
    ('Loopy', 'CROWN', 'SEOUL pt.A'),
    ('Loopy', 'DEAD MAN WALKING', 'SEOUL pt.A'),
    ('Khundi Panda', 'MODM 2 : The Bento Knight', 'MODM 2 : The Bento Knight'),
    ('Blase', 'KKUCKDARI', 'SELF MADE'),
    ('Blase', '12345678', 'SELF MADE'),
    ('Kid Milli', 'Feel Good', 'RAD MILLI'),
    ('Leellamarz', 'Hell yea', 'L&B'),
    ('Giriboy', 'Mechanical Album', 'Mechanical Album'),
    ('PH-1', 'GOSHA', 'WHAT HAVE WE DONE'),
    ('Crush', 'UP ALL NITE', 'FANG'),
    ('G-Dragon', 'Too Bad', 'Übermensch'),
    ('G-Dragon', 'TAKE ME', 'Übermensch'),
    ('Loco', 'work++', 'SCRAPS'),
    ('Heize', 'Love Virus (러브 바이러스)', 'LOVE VIRUS Pt.1'),
    ('foggyatthebottom', 'FOREVER YOUNG', 'POEMV'),
    ('GV', 'GV', 'YAHO'),
    ('Jeremy Que$t', 'Jeremy Que$t', 'YAHO'),
    ('MILLHAM', 'MILLHAM', 'YAHO'),
    ('Seo Ja Yeong', 'BE MY LOVE', 'POEMV'),
    ('DeVita', 'Spinboutu', 'Love is a Song'),
    ('DeVita', 'oh wow', 'Love is a Song'),
    ('B-Free', 'Free The Mane 3', 'Free The Mane 3'),
    ("BE'O", 'Healing', 'Show Me the Money 10'),
    ('Don Mills', '인생을 바꿀', 'The Life-Changing Album'),
    ('Owen Ovadoz', 'P.O.E.M.', 'P.O.E.M.'),
    ('Verbal Jint', 'Replay (Feat. Heize) (리플레이)', ''),
    ('Heize', 'Last Taxi (라스트 택시)', 'LOVE VIRUS Pt.1'),
    ('Crush', 'FANG', 'FANG'),
    ('Loco', 'SCRAPS', 'SCRAPS'),
    ('PH-1', 'WHAT HAVE WE DONE', 'WHAT HAVE WE DONE'),
    ('Lil Moshpit', 'LALALA', 'K-FLIP+'),
    ('Leellamarz', 'GONE', ''),
    ('Epik High', 'Frost (프로스트)', 'Strawberry'),
    ('Coogie', 'Shut Up (셧 업)', 'UPSET'),
    ('Gray', 'Real Love (리얼 러브)', 'Remedy'),
    ('Zion.T', 'Whale', 'Zip'),
    ('Bobby', 'Harmless', 'Sir.Robert'),
    ('82MAJOR', 'Stuck', 'Beat Road'),
    ('Qwala', 'If WONA becomes a gangster (Feat. Qwala, New Champ)', ''),
    ("O'koye", 'Hallelujah', 'Whether the Weather Changes or Not'),
    ('Sik-K', 'KC (BUST IT DOWN)', ''),
    ('ShyboiiTobii', 'Breaking Bad', ''),
    ('HD BL4CK', 'Vantablack Dreams', 'Vantablack Dreams'),
    ('KAMBO', 'Dreamatic', 'Dreamatic'),
    ('Minit', 'He♡rt', 'He♡rt'),
    ('Okashii', 'Orton', 'Orton'),
    ('Ted Park', 'Home Alone 2.0', 'Home Alone 2.0'),
    ('viceversa', "I'M UP", ''),
    ('EK', 'Escape', 'Escape'),
    ('Haon', 'Haonoah', 'Haonoah'),
    ('Flowsik', 'Worlds Apart', 'Worlds Apart'),
    ('Bryn', 'Supercharged', 'Supercharged'),
    ('Balming Tiger', 'Greatest Hits', 'Greatest Hits'),
    ('BIG Naughty', '+', '+'),
    ('RM', 'Right Place, Wrong Person', 'Right Place, Wrong Person'),
    ('Jay Park', 'Need To Know', 'THE ONE YOU WANTED'),
    ('Yung Blesh', 'Classical Freestyle', 'We Got What You Need'),
    ('BlackNut', '0', ''),
    ('Bassagong', 'Comfort (컴포트)', ''),
    ('YANGHONGWON', 'LEAN', ''),
    ('Nosun', 'Exit Wounds', 'Exit Wounds'),
    ('Wuuslime', 'Wuuslime', ''),
    ('Marv', 'Marv', ''),
    ('Nieah', 'Nieah', ''),
    ('GGM Kimbo', 'GGM Kimbo', 'We Got What You Need'),
    ('JMIN', 'JMIN', 'We Got What You Need'),
    ('Kimeen', 'Kimeen', ''),
    ('xorf1nn', 'xorf1nn', ''),
    ('lahaine', 'lahaine', ''),
    ('Pank', 'Pank', ''),
    ('Penomeco', 'When I Siege (웬 아이 시즈)', ''),
    ('Hoody', 'Us (어스)', ''),
    ('Kmjae', '비폴라', '비폴라'),
    ('BeeFree', 'Odyssey', 'Odyssey'),
    ('SINCE', 'New New New', ''),
    ('Liloyoung', 'Liloyoung', ''),
    ('RPT Kaigo', 'Kaigo', ''),
    ('YUNGIN', 'YUNGIN', ''),
    ('Kid Milli', '+', '+'),
    ('Epik High', 'Pump', 'Pump'),
    ('Coogie', 'Flame', 'UPSET'),
    ('Qwala', 'DISTORTED', 'DISTORTED'),
    ('ShyboiiTobii', 'ShyboiiTobii', 'We Got What You Need'),
    ('Royal 44', 'New Money', 'We Got What You Need'),
    ('Yung Blesh', 'New Money', 'We Got What You Need'),
    ('Bassagong', 'Rock N Roll Baby (Feat. G2 & CHANGMO)', ''),
    ('Kmjae', 'Polar (폴라)', '비폴라'),
    ('Hebi', 'Hebi', ''),
    ('SINCE', 'Wavy', ''),
]
