# 힙플·힙플레이·전문가 평가 기준 2024년 한국 랩/힙합 Top 100 (차트 미반영)
TRACKS = [
    ('TOIL', '염염상망', ''),
    ('Loopy', 'DOPE', 'SEOUL pt.A'),
    ('Owen Ovadoz', 'Diamond', '119'),
    ('The Quiett', 'LF Intro', 'Luxury Flow'),
    ('Antihuman', 'Antihuman', 'Antihuman'),
    ('QM', '개미', '개미'),
    ('Khundi Panda', 'Somozu Fury', ''),
    ('Garion', 'Garion 3', 'Garion 3'),
    ('B-Free', 'Free The Mane 2', 'Free The Mane 2 "Free The Mane VS 최승로"'),
    ('Kid Milli', '5AM', 'RAD MILLI'),
    ('Dean', 'NASA', '3:33'),
    ('Dean', 'Ctrl', '3:33'),
    ('Changmo', 'HOLDUP', 'Op.1'),
    ('Lil Moshpit', 'K-FLIP', 'K-FLIP+'),
    ('Qwala', '델러가 (Feat. MELOH & Posadic)', 'yorter'),
    ('BRADYSTREET', 'Brady Street', ''),
    ('Gist', 'Gist', ''),
    ('JUSTHIS', 'JUSTHIS', 'Show Me the Money 11'),
    ('G-Dragon', 'HOME SWEET HOME (Feat. 태양, 대성)', 'Übermensch'),
    ('G-Dragon', 'POWER', 'Übermensch'),
    ('Beenzino', 'Train', ''),
    ('Crush', 'Yes or No', ''),
    ('Heize', 'Even if (이븐 이프)', ''),
    ('Kid Milli', '술', 'RAD MILLI'),
    ('Don Malik', 'THURSDAYCLUB MIXTAPE', 'THURSDAYCLUB MIXTAPE'),
    ("BE'O", 'Momentum (모멘텀)', 'Show Me the Money 10'),
    ('Lil Boi', 'ONFleek (온플릭)', 'Show Me the Money 9'),
    ('Blase', 'INDUSTRY (인더스트리)', 'SELF MADE'),
    ('Don Mills', 'OK', ''),
    ('Paloalto', 'Lovers Turn to Haters', 'Lovers Turn to Haters'),
    ('Changmo', 'Wonderful Days', ''),
    ('Zico', 'ZOOM', ''),
    ('Lil Moshpit', 'KC2', 'K-FLIP+'),
    ('Sokodomo', 'Merry Go Round', 'Merry Go Round'),
    ('Jay Park', 'Stand Out', ''),
    ('Loco', 'random summer night', ''),
    ('Crush', "Fallin'", ''),
    ('Leellamarz', 'Let me go to heaven', ''),
    ('Bobby', 'Sae', 'Sir.Robert'),
    ('Coogie', 'ON FIRE', ''),
    ('PH-1', 'FLAT COKE', ''),
    ('Punchnello', 'before you', ''),
    ('Gray', "SLIDIN'", ''),
    ('Giriboy', 'heat', 'heat'),
    ('Epik High', 'Stop the Rain (스톱 더 레인)', ''),
    ('Lee Young Ji', 'Yumeyo', '16'),
    ('Sik-K', 'MAKE OUT (메이크 아웃)', 'MAKE OUT'),
    ('Zion.T', 'Snooze (스누즈)', 'Zion.T Special: OO'),
    ('82MAJOR', '뭘 봐 (TAKEOVER)', 'X-82'),
    ('Leellamarz', 'B', ''),
    ('Heize', 'Forgotten Love (포gotten Love)', 'Last Winter'),
    ('Crucial Star', 'Nihilism Watch', ''),
    ('ChaMane', 'BATON PASS', 'BATON PASS'),
    ('HD BL4CK', 'BATON PASS', 'BATON PASS'),
    ("J'Kyun", 'AGAPE', 'AGAPE'),
    ('meenoi', 'B', ''),
    ('GroovyRoom', 'Yes or No (예스 오어 노)', ''),
    ('Wonstein', "It's not beautiful and it doesn't hurt", ''),
    ('Flowsik', "Movin'", ''),
    ('GwangilJo', 'Light Adaptation', 'Light Adaptation'),
    ("O'koye", 'Yezzir', 'Whether the Weather Changes or Not'),
    ('Rad Museum', 'Rad Milli', 'Rad Milli'),
    ('Chillin Homie', 'Maze Runner', 'Maze Runner'),
    ('Dbo', 'Be Back Soon', 'Be Back Soon'),
    ('Homies', 'Yains', 'Yains'),
    ('Los', 'Skandalouz 2', 'Skandalouz 2'),
    ('HAON', 'KC (BUST IT DOWN)', ''),
    ('BIGONE', 'COLORFUL ZEBRA', ''),
    ('BOYCOLD', 'Sick of Love', 'Sick of Love'),
    ('viceversa', 'N!kes', ''),
    ('KIDO', 'MACHINES', ''),
    ('Ash-B', 'Wish', ''),
    ('XWALLY', 'BORN2RAVE', 'BORN2RAVE'),
    ('AP Alchemy', 'Monthly AP – January, 2024', 'Monthly AP – January, 2024'),
    ('Leebido', 'A prescription for 2', 'A prescription for 2'),
    ('ShyboiiTobii', 'Dillis', ''),
    ('Moon Sujin', 'Better', 'Better'),
    ('noisemasterminsu', 'I KNOW YOU LOVE ME', ''),
    ('lil9ap', 'Drama/R&B', 'Drama/R&B'),
    ('basecamp', 'camp', ''),
    ('CK', 'Verses', 'Verses'),
    ('KAMBO', 'Rapstar', ''),
    ('1300', 'Ape Sh*t', ''),
    ('YUGYEOM', 'LA SOL MI', ''),
    ('DPR ARTIC', 'KINEMA', 'KINEMA'),
    ('Marv', 'Ok', ''),
    ('Junoflo', 'Love Like This', ''),
    ('JMIN', "Sorry I'm Late", "Sorry I'm Late"),
    ('Panda Gomm', 'Home Vacation', 'Home Vacation'),
    ('CHIO CHICANO', 'Big Squad', ''),
    ('Tiger JK', 'T.K.D', 'T.K.D'),
    ('Dabin', 'Giggles', 'Giggles'),
    ('Untell', 'Animal', 'Animal'),
    ('Skinny Chase', 'Journey to the West', 'Journey to the West'),
    ('Fredi Casso', 'Death Therapy', 'Death Therapy'),
    ('Ambid Jack', 'Death Therapy', 'Death Therapy'),
    ('Ja Mezz', 'Only', 'Only'),
    ('Bangroz', 'Only', 'Only'),
    ('Hyeminsong', 'Reborn', 'Reborn'),
    ('Jay Park', 'Taxi Blurr', ''),
]
